### ISSUE TITLE
Rewarding different permissions

### ISSUE THREAD

**Issue by EvilPandaMan** [BenCodez/VotingPlugin#1000]
Hello. I'm trying to create a system in which the voting on all sites rewards different permissions with different items. 

I'm using the EverySiteReward in the end of the VOTESITES file. When I add one reward file name it works, eg; 

EverySiteReward;
  Rank1

this method works fine, but when I add more rewards for the different ranks it doesn't work. eg:

EverySiteReward:
  Rank1
  Rank2
  Rank3

This method does not work. Can anyone help me in how to solve this issue? how can I reward different permissions differently?

Thanks

F

**Comment by BenCodez** [comment]
No need to send a pm and here, closing as I answered via PM on spigot.
