### ISSUE TITLE
Need help to configure it for offline rewards

### ISSUE THREAD

**Issue by NoHoPeLess** [BenCodez/VotingPlugin#1001]
Hay need help for my setup, have no clue how i can do this...

We have a server network, we would make it possible to offline vote so that players can vote offline and get rewards when they are online.

I try many things for hours but it will not work for offline votes (online votes works great)

Any help?

**Comment by BenCodez** [comment]
Use one of these setups:
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by NoHoPeLess** [comment]
Oh this is fast, i try all setups except mysql, not sure if i can use it, we will keep track of the votes...?
Do i need NuVotifier on all servers?

**Comment by BenCodez** [comment]
I would recommend plugin messaging.

If it didn't work then you probably did something wrong.

**Comment by NoHoPeLess** [comment]
You mean on votifier? on VotePlugin we still use pluginmessaging

**Comment by BenCodez** [comment]
If your using plugin messaging for VotingPlugin then you only need votifier on bungee.

**Comment by NoHoPeLess** [comment]
hmm i will try that, i delete votefier on the other servers (Which settings do the votifier need on bungee?)

**Comment by BenCodez** [comment]
Just setup votifier, no forwarding.

**Comment by NoHoPeLess** [comment]
this is for now https://hastebin.com/nerowijaya.yaml

**Comment by BenCodez** [comment]
Should do the job.

**Comment by NoHoPeLess** [comment]
i will try

**Comment by NoHoPeLess** [comment]
dont work... get no offline reward

**Comment by BenCodez** [comment]
So you followed this?

https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by NoHoPeLess** [comment]
i will try again :D

**Comment by NoHoPeLess** [comment]
yes, now it works but "SendVotesToAllServers: true" result in double rewards when i joined another server...

**Comment by BenCodez** [comment]
Your gonna have to explain what you have done, it's working for everyone else using it currently.

**Comment by NoHoPeLess** [comment]
Yes, but not for me, its sad... 

i setup as above for now dont know how to explain?

I try to send u all configs?

**Comment by BenCodez** [comment]
That would help.

**Comment by NoHoPeLess** [comment]
Bungee:
NuVotifier: https://hastebin.com/cowuwukese.yaml
VotingPlugin: https://hastebin.com/sogoranace.yaml

Paper:
Voting Plugin:
- BungeeSettings.yml https://hastebin.com/muyorafuga.yaml
- Config.yml https://hastebin.com/iruqatatis.yaml
- VoteSites.yml https://hastebin.com/qarisimafi.yaml

Hope this helps :)

**Comment by BenCodez** [comment]
You can set DebugLevel to EXTRA and BungeeDebug (both on spigot) and send the log on double votes vs normal votes

**Comment by NoHoPeLess** [comment]
ok one moment

**Comment by NoHoPeLess** [comment]
Log Bungee: https://hastebin.com/laganikeva.sql

Log Survival_1: https://hastebin.com/iwicetepit.makefile

Log SkyBlock: https://hastebin.com/sipuwixiqo.yaml

Ok for now no doubled but they become one vote on survival_1 and one on skyblock.... i would it so that they only get one reward on the server they are, not on every server the same

**Comment by BenCodez** [comment]
just disable sendtoallservers and you'll get one global reward, if that's what you mean.

**Comment by NoHoPeLess** [comment]
No when i do that, only online votes will work... but i try it again

**Comment by BenCodez** [comment]
You'll only get one reward per the whole network, one server only.

**Comment by NoHoPeLess** [comment]
this is what i want, a player votes (online or offline) they come, go on the "reward" server and get the reward on this server

**Comment by BenCodez** [comment]
Should work with that setup.

**Comment by NoHoPeLess** [comment]
now i get no rewards with sendtoallservers to false

**Comment by NoHoPeLess** [comment]
log survival_1: https://hastebin.com/zujeregewi.makefile

log bungee: https://hastebin.com/diyaxedobo.sql

**Comment by BenCodez** [comment]
Console logs?

**Comment by BenCodez** [comment]
Does relogging work?

**Comment by NoHoPeLess** [comment]
above

**Comment by NoHoPeLess** [comment]
i try

**Comment by NoHoPeLess** [comment]
no, wont work

**Comment by BenCodez** [comment]
It shows in the log that it was sent to spawn

**Comment by BenCodez** [comment]
Guess I didn't count the backlist on online votes...

**Comment by NoHoPeLess** [comment]
yes we have a spawn (hub) but here are no votes or something so there is no votingplugin

**Comment by NoHoPeLess** [comment]
install it there too?

**Comment by BenCodez** [comment]
No, give me a minute.

**Comment by NoHoPeLess** [comment]
ok

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Copy that jar onto bungee (don't do spigot, bungee only) and tell me if that solves it.

**Comment by NoHoPeLess** [comment]
ill try :)

**Comment by NoHoPeLess** [comment]
no...

log survival_1: https://hastebin.com/lacaxupebe.makefile

log bungee: https://hastebin.com/sexijeciqo.sql

or must i restart the paper server too?

**Comment by BenCodez** [comment]
I'll have to look at it tomorrow

**Comment by NoHoPeLess** [comment]
ok ;D can it be open here? so we can try it tomorrow again whenever you want?

**Comment by NoHoPeLess** [comment]
so i am ready :D

**Comment by NoHoPeLess** [comment]
hope u have some ideas :D

**Comment by BenCodez** [comment]
Try this on bungee only:
http://bencodez.com/job/VotingPlugin-6.0/

**Comment by NoHoPeLess** [comment]
ill try

**Comment by NoHoPeLess** [comment]
wow it seems that it is :D its worked i think.... now, can i put the jar on the other servers?

**Comment by BenCodez** [comment]
I wouldn't, it's a dev build with a lot of changes you probably don't want to deal with

**Comment by NoHoPeLess** [comment]
ok :D but now? can i ran it so on my live servers? i mean this setup actually

**Comment by BenCodez** [comment]
Should be able to.

**Comment by NoHoPeLess** [comment]
then we found the error , i thank u very much for ur support and work 👍

**Comment by NoHoPeLess** [comment]
Hay, is there any chance to translate the confirmation menu?

**Comment by BenCodez** [comment]
Not right now.

**Comment by NoHoPeLess** [comment]
ehh... this is sad :( but thanks for the info

**Comment by NoHoPeLess** [comment]
Hay, another problem... they become the votepoints only on 1 server... not on the whole network

**Comment by BenCodez** [comment]
what?

**Comment by NoHoPeLess** [comment]
When the player voted, they become the vote point only on the server they joined, on the other server they have 0...

for example: 
- they voted on survival, get 1 vote point, on skyblock 0

**Comment by NoHoPeLess** [comment]
https://www.youtube.com/watch?v=h2Eej_WqcPE

**Comment by BenCodez** [comment]
Might need to enable the clearcache options in the config

**Comment by NoHoPeLess** [comment]
ClearCacheOnVote: true ? this is true

**Comment by BenCodez** [comment]
ClearCacheOnJoin?

**Comment by NoHoPeLess** [comment]
or all?

```
# ---------------------------------------------------------
# Mysql cache options 
# Clearing cache forces the plugin to pull from database
# Not needed unless you are using multiple servers
# ---------------------------------------------------------

# Clear cache on update, setting to true reduces update speed
# Also may require AlwaysUpdate set to true
ClearCacheOnUpdate: false

# Clear cache on player join always
ClearCacheOnJoin: false

# Clears cache for the player who voted only
# Only effects if using mysql
# Would recommend for some bungee setups
ClearCacheOnVote: true

# Clear cache when player leaves
ClearCacheOnLeave: false

ClearCacheOnVoteShopPurchase: true
```

**Comment by BenCodez** [comment]
Set all to true

**Comment by NoHoPeLess** [comment]
WOW it works! great so how can i spend u a coffee?

**Comment by BenCodez** [comment]
Donate link on spigot near the bottom if you feel like it.

**Comment by NoHoPeLess** [comment]
;D ok i spend it <3 thank u so much! (hope the confirmation button will translatable in the future)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Already add it :P 

You'll need to add the config options
https://github.com/BenCodez/VotingPlugin/blob/6.0/VotingPlugin/Resources/GUI.yml#L295

**Comment by NoHoPeLess** [comment]
wow can i update this on bungee? as we write above?

**Comment by BenCodez** [comment]
You'll need to do it on spigot

**Comment by NoHoPeLess** [comment]
ok so i only update the jar on spigot

**Comment by BenCodez** [comment]
Yep

**Comment by NoHoPeLess** [comment]
Hey me again :D when i use ur new gui.yml result in error...

ERROR:

while parsing a block mapping
  in "<unicode string>", line 9, column 1:
    GUIMethod:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 489, column 3:
      ShopConfirmPurchase:
      ^

with ur standard gui.yml the plugin cant load values ....

https://hastebin.com/iyozaqakix.sql

**Comment by BenCodez** [comment]
Send your file, if not reset it. The default gui.yml is fine for me.

**Comment by NoHoPeLess** [comment]
found my issue... there are must be spaces in the confirmation section... the spaces are missing by me ... sry

**Comment by NoHoPeLess** [comment]
now i have another bug?

![Unbenannt](https://user-images.githubusercontent.com/6246520/97817888-6d0edb00-1c9f-11eb-955d-0a966a6705e3.jpg)

**Comment by BenCodez** [comment]
What am I looking at?

**Comment by NoHoPeLess** [comment]
im not sure but was the gui not alone? without the inv?

**Comment by BenCodez** [comment]
That's not possible in minecraft

**Comment by NoHoPeLess** [comment]
ok my fault again... its late i must sleep sry

**Comment by NoHoPeLess** [comment]
but one question, my vote shop is now empty...

**Comment by BenCodez** [comment]
Need to configure it in the gui.yml

**Comment by NoHoPeLess** [comment]
https://www.file-upload.net/download-14344150/GUI.yml.html

**Comment by NoHoPeLess** [comment]
dont know was the fault is

**Comment by BenCodez** [comment]
Just use pastebin

**Comment by NoHoPeLess** [comment]
https://pastebin.com/p7nB8Rrp

**Comment by BenCodez** [comment]
The format changed for shop, see the default file.

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/blob/6.0/VotingPlugin/Resources/GUI.yml

**Comment by NoHoPeLess** [comment]
see it, ok now i have 1 empty item?

![2020-11-02_00 19 40](https://user-images.githubusercontent.com/6246520/97818155-25894e80-1ca1-11eb-9907-fbe10e92bde8.png)

**Comment by NoHoPeLess** [comment]
right from the egg

**Comment by BenCodez** [comment]
Check your file

**Comment by NoHoPeLess** [comment]
any tips? :D

**Comment by BenCodez** [comment]
Send what you have?

**Comment by NoHoPeLess** [comment]
ah spaces again wtf

**Comment by NoHoPeLess** [comment]
something going wrong and i dont know what...

**Comment by BenCodez** [comment]
Are you gonna send the file?

**Comment by NoHoPeLess** [comment]
or an reload brings false positives

**Comment by NoHoPeLess** [comment]
i will test and write here

**Comment by NoHoPeLess** [comment]
the placeholder %VotingPlugin_alltimetotal% dont work correctly... it displays 0 ....

i test /papi parse me %VotingPlugin_alltimetotal% result in 7 but the broadcast = 0

`  BroadcastMsg: '&8&l(&b&l!&8&l)&r &7Danke &a%player% &7fuer das Voten auf &b%SiteName%&7, &a%player% &7hat bisher &b%VotingPlugin_alltimetotal%&7x gevotet, vote auch mit &b/vote gui'`

**Comment by BenCodez** [comment]
It should broadcast the placeholders parsed as the person receiving the message.

**Comment by NoHoPeLess** [comment]
then i can do? nothing? :D

**Comment by BenCodez** [comment]
Don't think there is a good way to have it work any other way without some issue.

**Comment by NoHoPeLess** [comment]
will u fix this?

**Comment by BenCodez** [comment]
There isn't a good way to fix this?

The way it works is intended at the moment.

**Comment by NoHoPeLess** [comment]
ahh this is sad... so i must change the message for now

but before i updated to latest dev build, it works...

**Comment by NoHoPeLess** [comment]
yea i tested it, with the dev = dont work, with ur version from https://www.spigotmc.org/resources/votingplugin.15358/ it works

**Comment by BenCodez** [comment]
Try the most recent build.

If the player data isn't cached it returns 0, so it won't crash the server, modified it a bit so it won't do that unless needed.

http://bencodez.com/job/VotingPlugin-6.0/

**Comment by NoHoPeLess** [comment]
wow
ur amazing, it works wtf

**Comment by BenCodez** [comment]
Didn't understand what you said at first :)

**Comment by NoHoPeLess** [comment]
what do u mean? :D

**Comment by BenCodez** [comment]
I don't know, and it doesn't matter now :)

**Comment by NoHoPeLess** [comment]
hahaha thank u so much
