### ISSUE TITLE
votelinkhere

### ISSUE THREAD

**Issue by chacoby7** [BenCodez/VotingPlugin#1003]
**Versions**
Plugin version: 5.24.1 and spigot version: paper-247

**Relevant information**
https://pastebin.com/TGb6j98n

**Context**
When I type /vote in my minecraft chat i get a message "Vote here: www.votelinkhere.com" I have to type /voteurl in order to get the gui for vote sites. Is this normal? Can I change/fix this?

**Comment by BenCodez** [comment]
You have another plugin overriding the command.

**Comment by chacoby7** [comment]
Fixed, thank you!
