### ISSUE TITLE
Rewards w/ SkullTexture Ignore Amount Value

### ISSUE THREAD

**Issue by delbertina** [BenCodez/VotingPlugin#1004]
**Versions**
VP 5.24.1
Paper 1.16.3

**Describe the bug**
Reward file is linked below, but when rewarding a player with an item that uses the SkullTexture option it ignores the Amount argument and just gives 1. When the SkullTexture option is taken off the item the Amount option is followed. When I turned on debug I couldn't see anything to be the matter, but I did see that it was giving a stack of 1 so I'm assuming this issue is somewhere in this plugin and not a vanilla/spigot/paper bug.

**Screenshots/Configs**
[https://pastebin.com/T9nYhzjr](https://pastebin.com/T9nYhzjr)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Should solve that. Just there will be some other changes in the dev build, such as GUI.yml and a bit more other stuff.

Also your pastebin is private :)

**Comment by delbertina** [comment]
Sick, it does solve the issue! My b for fat fingering the pastebin privacy to private lol. 👌🏼
