### ISSUE TITLE
Bungee Setup

### ISSUE THREAD

**Issue by Skizzles** [BenCodez/VotingPlugin#1005]
**Versions**
VotingPlugin-4.24.1
Yatopia-1.16.3 (Paper Fork)

**Relevant information**
Spigot Server BungeeSettings
https://pastebin.com/swKb8hyy

**Context**
I am trying to setup the plugin with the best method for voting on the entire mode BUT with only claiming on one mode. From my understanding that was with the MYSQL setup. However when connecting every mode to the same MySQL database it allows claiming on every mode.

The above has my BungeeSettings.yml for how its setup on each mode.
 This is from my bungeeconfig.yml... does the "SendVotesToAllServers" mean it sends the rewards to all them as well? because the message states "If false will send to line server only", does that affect offline voting?
SendVotesToAllServers: true
BlockedServers:
- Hub1
- Hub2
BungeeMethod: MYSQL

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Try that build. Also disable sendvotestoallservers if you want to only be rewarded on one server.

**Comment by Skizzles** [comment]
I disabled that, they keep getting multiple keys every relog.

https://www.youtube.com/watch?v=uE0Ihhl_YMA

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

What setup are you using? Are you forwarding with nuvotifier?

**Comment by Skizzles** [comment]
BungeeMethod MYSQL

and forwarding should be with nuvotifier yes. I just switched from another Vote plugin so this one is a bit confusing for me.

**Comment by BenCodez** [comment]
Only have nuvotifier on one spigot server if your using that method. VotingPlugin will handle the rest. Or you can switch to another method and have nuvotifier only on bungee.

**Comment by Skizzles** [comment]
So if I switch over to PluginMessaging and remove Nuvotifier off everything except Bungee then it should work fine?

**Comment by BenCodez** [comment]
Yep, I would just use this build on bungee (Don't do spigot):
http://bencodez.com/job/VotingPlugin-6.0/

If you only want to be rewarded on one server with sendtoallservers set to false (little bug in the current spigot build)

**Comment by Skizzles** [comment]
gotcha, so for Nuvotifier I should:
```
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging.
  # - proxy - Proxies votes to other NuVotifier servers from this server.
  method: pluginMessaging
```

Set this to none?

**Comment by BenCodez** [comment]
Yes, to none

**Comment by Skizzles** [comment]
Okay I have done that, when attempting to vote the users vote does not go through to that specific server?

**Comment by Skizzles** [comment]
[13:34:44 INFO] [NuVotifier]: Got a protocol v1 vote record from  -> Vote (from:TopG.org username: address: timeStamp:1604176484 additionalData:null)

Nothing on Spigot server side.

**Comment by BenCodez** [comment]
Did you set the method and enable use bungeecoord on spigot servers?

**Comment by Skizzles** [comment]
UseBungeecord: true
BungeeBroadcastAlways: true
BungeeMethod: PLUGINMESSAGING

**Comment by BenCodez** [comment]
NuVotifier is on bungee right? Bungee config setup? Did you put the build on bungee I linked on above or just the spigot version?

**Comment by Skizzles** [comment]
Nuvotifier is on bungee, config is setup on bungee and all modes according to the guide you linked. I put that specific build only on bungee as you said.

**Comment by BenCodez** [comment]
enable debug on bungee and set debuglevel to EXTRA and enable bungeedebug on spigot servers and send the log on a vote.

**Comment by Skizzles** [comment]
I enabled debug on bungee and did votingpluginbungee reload, then enabled on my spigot mode and restarted the spigot mode, I don't see any extra voting debug.

The vote reaches Bungee and then is not sent anywhere.

**Comment by BenCodez** [comment]
Do a bungee restart? Send the full log of everything?

**Comment by Skizzles** [comment]
I can't really restart bungee with players online.... This should be fairly simple to setup but it has gone from semi working to not working at all.

**Comment by BenCodez** [comment]
Hmm. I know it works, just helped someone else with your exact setup a day ago, same jar and everything, can't really say much without you trying a restart and the logs at the moment.

Send your bungee config for votingplugin?

**Comment by Skizzles** [comment]
```# Set bungeecoord to true on servers on the network (In VotingPlugin)
# Set server name in each server related to what it is on bungee
#
# MYSQL Required on all setups
# MYSQL INFO --------------------------
Host: ************
# Default port is 3306
Port: **********
Database: *************
Username: **************
Password: *************
# Max number of connections
MaxConnections: 1
# Maxium size of caching mysql
# -1 for no limit
# Affecting this value may affect performance
MaxSize: -1
# Table name prefix, for use with mutliple servers
Prefix: ''
#UseSSL: true

Debug: true
# Have a reward on each server
# If false, will send to online server only
SendVotesToAllServers: false
# List of servers the plugin won't send the vote to
# Uses names from bungeecoord config if not using SOCKETS method
BlockedServers:
- Hub1
- Hub2

# What type of bungee setup
# Requires restart and set on all servers
# https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups
# Available:
# SOCKETS 
# PLUGINMESSAGING 
# MYSQL
BungeeMethod: PLUGINMESSAGING

# ----------------------------
# SOCKET METHOD Only, ignore otherwise
# ----------------------------
FallBackServer: factions

# Tell servers to broadcast
Broadcast: true

# Bungee communication, Add this to each spigot server
BungeeServer:
  Host: '127.0.0.1'
  Port: 1297
  
# Bungee communication, add each spigot server here
SpigotServers:
  lobby:
    Host: '127.0.0.1'
    Port: 1298
  factions:
    Host: '127.0.0.1'
    Port: 1999

**Comment by BenCodez** [comment]
What do you get on a vote?
Does /votingpluginbungee vote (player) (site) work?

**Comment by Skizzles** [comment]
When running the command above I see nothing at all, when I run an actual vote from the site I see [13:34:44 INFO] [NuVotifier]: Got a protocol v1 vote record from -> Vote

**Comment by BenCodez** [comment]
Did you restart after updating the jar?

**Comment by Skizzles** [comment]
Yes. I have followed all your instructions, followed the entire guide. The votes went through before and they just duplicated and sending on all modes. Now votes don't go through at all lol

**Comment by BenCodez** [comment]
It's because nuvotifier was on pluginmessaging, need to use proxy, incase
you feel like going back to that setup.

Did VotingPlugin enable on bungee at all? Startup log?

**Comment by Skizzles** [comment]
Looking at the log everything enabled without any errors.

I feel I could go back to that setup.... but then I have to restart my proxy **again**

This process is a little frustrating..

**Comment by BenCodez** [comment]
Unless you can tell me a better way really, there is no way around it.

Could always setup a test network and try it out before putting it on your server.
