### ISSUE TITLE
Problem with /vote

### ISSUE THREAD

**Issue by MultiCrafer** [BenCodez/VotingPlugin#1007]
Last published version of yours plugin.  spigot version 1.16.3

https://pastebin.com/f71unumh (my config of sites)

Hello I have question I reinstall yours plugin and setup new sites for /votegui or /voteurl. But when i Type /vote I just get only message example.com I cant change this nowhere or I dont find this any ideas how to fix this to url form /voteurl ? Thanks

**Comment by BenCodez** [comment]
Another plugin is interferring.

**Comment by MultiCrafer** [comment]
Hi can you recognize which if i give you all my plugins ?

**Comment by BenCodez** [comment]
venturechat is one I would check, otherwise wouldn't be able to say

**Comment by SkyyOrange** [comment]
This solved my problem! How dare venturechat have such a default alias...
