### ISSUE TITLE
Setting up rewards per vote

### ISSUE THREAD

**Issue by clefairy135** [BenCodez/VotingPlugin#1009]
**Versions**
5.24.1 

**Relevant information**
This is what I have in the "VoteSites" file:

VoteSites:
  MinecraftServers:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/vote/597422
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      commands:
        console:
        - 'crate givekey %player% golden 1'
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  TopG:
    Enabled: true
    ServiceSite: TopG.org
    VoteURL: https://topg.org/Minecraft/in-617499
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      commands:
        console:
        - 'crate givekey %player% golden 1'
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MC-Lists:
    Enabled: true
    ServiceSite: MC-Lists
    VoteURL: https://mc-lists.org/server-the-cave.96/vote
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      commands:
        console:
        - 'crate givekey %player% diamond 1'
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Minecraft-MP:
    Enabled: true
    ServiceSite: Minecraft-MP.com
    VoteURL: https://minecraft-mp.com/server/271321/vote/
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      commands:
        console:
        - 'crate givekey %player% netherite 1'
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Context**
So, I downloaded goldencrates so our members can receive 1 key per vote and open the crates. I set up the command for the reward in the VoteSites file, and I know the crate command is correct, but it is not working. Do you see anything wrong with the settings? Are we adding the reward in the wrong file? Thanks!

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - command here %player%

**Comment by beasty134** [comment]
Can you modify this so it dose this command crate key %player% vote 1 I can't get it to work
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/vote/598979
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Player: '&aThanks for voting on %ServiceSite%!'
  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://www.planetminecraft.com/server/voidpvp-4842676/vote/
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward: crate key %player% vote 1

**Comment by BenCodez** [comment]
Pastebin it.
