### ISSUE TITLE
/vote text not getting customized as in config.yml

### ISSUE THREAD

**Issue by YTMrSnipa** [BenCodez/VotingPlugin#1010]
Hello! I am not able to customize the default text that appears in /vote, I have changed it in the config.yml but it is still showing default "Vote for our server". What I mean is that when I click on "Click me for all voting sites" its showing this:
![Screenshot_2](https://user-images.githubusercontent.com/67626963/98024753-c48f8100-1e2e-11eb-93b5-2acde07a45c5.png)

**Comment by BenCodez** [comment]
Either create/add voting sites in votesites.yml or set it the config.yml (need to disable an option for that)
