### ISSUE TITLE
VoteShop Question

### ISSUE THREAD

**Issue by S1iceAb1eZues** [BenCodez/VotingPlugin#1011]
**Versions**
Latest Version

**Relevant information**
Configs that relate to the issue in a pastebin.
![image](https://user-images.githubusercontent.com/73928480/98077499-68a21800-1e81-11eb-8e52-61a33cd32bcf.png)

**Context**
How do I add a command to the voteshop reward?

**Comment by S1iceAb1eZues** [comment]
I pasted a photo because pastebin wasnt working

**Comment by BenCodez** [comment]
Just under Rewards

    Rewards:
      Commands:
      - command here %player%

**Comment by S1iceAb1eZues** [comment]
ty
