### ISSUE TITLE
Placeholders on 6.0 version?

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#1012]
**Versions**
6.0 the newest from jenkins

**Relevant information**
Hi, I think that my placeholders for vote party and vote next doesn't seem working, did you change something or?

**Comment by BenCodez** [comment]
What are you using?

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

That doesn't fix it by chance does it?

**Comment by bobhenl** [comment]
Fixed, thanks.
