### ISSUE TITLE
votesites> i dont know what i do wrong

### ISSUE THREAD

**Issue by Veruath** [BenCodez/VotingPlugin#1016]
**Versions**
(Version: 5.24.1 - Oct 05, 2020)

**Relevant information**
server paper_1.16.3

**Context**
i cannot figureout whats wrong 
https://pastebin.com/CC3uvs8g

**Comment by BenCodez** [comment]
https://pastebin.com/PYn9dFnL

**Comment by Veruath** [comment]
Vote sites duplicate themselves. i need to use correct serversites asu said i guess
correct servicesites are in the serverdata.yml? i used em instead, now i have only 1 link on BOOKGUI

https://pastebin.com/d85rStwq

**Comment by BenCodez** [comment]
VoteSites:
  Minecraft-MP.com:

You can't put dots there
