### ISSUE TITLE
Placeholder API Warning

### ISSUE THREAD

**Issue by EllairaX** [BenCodez/VotingPlugin#1017]
**Versions**
VotingPlugin: 5.21.1
Paper: 1.16.3 (248)

**Describe the bug**
Not exactly a bug, but this message appears upon the start of the server: 
`06.11 16:21:26 [Server] WARN [PlaceholderAPI] VotingPlugin is attempting to register placeholders via a PlaceholderHook class which is no longer supported!
`
On PAPI's Discord server, they said to notify plugin developers if this message appears. 

**To Reproduce**
1. Start the server.
2. Look for the error message in the console.

**Expected behavior**

**Screenshots/Configs**

**Additional context**

**Comment by BenCodez** [comment]
Update the expansion
