### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by argnapa** [BenCodez/VotingPlugin#1018]
**Versions**
Plugin version 5.24.1 and Paper 1.16.4

**Relevant information**
https://pastebin.com/jYL0CTVj

**Context**
Hi,

I keep getting errors: 
In game: VotingPlugin: Detected yml error, please check console for details
[22:02:51] [Server thread/ERROR]: Cannot load plugins/VotingPlugin/VoteSites.yml
[22:02:55] [Craft Scheduler Thread - 8/ERROR]: [VotingPlugin] Failed to load VoteSites.yml

I used 'console' instead of commands as per the Breakdown's video but have now changed that. Is there anything else wrong with what I am doing?

Thanks,
Adrianne

**Comment by BenCodez** [comment]
Just delete the file, let it regen, then vote on a site and it will auto generate. It's too much work to fix what you have at the moment.

**Comment by argnapa** [comment]
Alright, that's the yml deleted and has regen. How does the voting work if the voting link isn't linked to the yml?

**Comment by BenCodez** [comment]
It will just make a site for you.

**Comment by argnapa** [comment]
Ah right, then I just have to edit the rewards?

**Comment by BenCodez** [comment]
yes

**Comment by argnapa** [comment]
Alright. Sorry, is this in the actual configs? Does the config.yml or specialrewards.yml give out the actual rewards?

**Comment by BenCodez** [comment]
votesites.yml and specialrewards.yml have rewards.

**Comment by argnapa** [comment]
Thank you so much for all your help!
