### ISSUE TITLE
milestone

### ISSUE THREAD

**Issue by Veruath** [BenCodez/VotingPlugin#1019]
Versions
(Version: 5.24.1 - Oct 05, 2020)

Relevant information
server paper_1.16.3

i ccouldnt figureout whats wrong tried dif spaces. i dont know what is wrong. Thanks in advance, you are amazing :)
https://pastebin.com/r7py7qQY

**Comment by BenCodez** [comment]
Its not enabled?

    Enabled: false

**Comment by Veruath** [comment]
omg, i m so tired i guess. and you are amazing! i ll donate when i finish setting plugin

**Comment by Veruath** [comment]
i did enable and removed myself as /av userremove
tested by givin /av vote player website
but didnt give milestone
i tried /av user player forcemilestone 2
didnt happen

**Comment by BenCodez** [comment]
You put that in specialrewards.yml?

**Comment by Veruath** [comment]
yes it is in specialrewards.yml

**Comment by BenCodez** [comment]
Pastebin the whole file.

**Comment by Veruath** [comment]
https://pastebin.com/zs2h70kx

**Comment by Veruath** [comment]
votesites are working fine just fyi

**Comment by BenCodez** [comment]
https://pastebin.com/YuiVzCgY

You had 2 tabs at the end of the file.

**Comment by Veruath** [comment]
woooooo thnks

**Comment by Veruath** [comment]
fixed!!!! i love you! :D i spent 3 hours to find whats wrong :D

**Comment by Veruath** [comment]
1 more problem i have, after pple voting, i ger randomly generated websites in votesites.yml. how can i prevent it?

**Comment by BenCodez** [comment]
Use the correct service sites then

**Comment by Veruath** [comment]
thnks

**Comment by Veruath** [comment]
correct websites are in the serverdata.yml?
