### ISSUE TITLE
Many placeholders

### ISSUE THREAD

**Issue by YTMrSnipa** [BenCodez/VotingPlugin#1021]
Hey! While browsing through the PAPI page for this plugins placeholder's, I noticed that there were multiple placeholders for the same thing, or so i thought. Now I am very confused, what is the difference between %VotingPlugin_top_month_#_votes%
 and %VotingPlugin_top_month_#%??

**Comment by BenCodez** [comment]
/av placeholdes (player) - will parse every placeholder, /av placeholders should also show the description of every placeholder.
