### ISSUE TITLE
Large query size warning

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1022]
**Versions**
VotingPlugin 5.24.1
Paper 1.16.3

**Relevant information**
Nothing special in my config that I'm aware of. This was a lobby server on which this happened. 

**Context**
Saw this at shutdown
[22:59:44 INFO]: [VotingPlugin] Shutting down mysql, query size: 2089
[22:59:44 INFO]: [VotingPlugin] Shutting down mysql, queries to do: 2089, if number is higher than 1000, then something may be wrong

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Does it happen with this build? (There are a lot of changes in that build, it's almost a drop in replacement)

**Comment by x1p** [comment]
The server on which this happened is a lobby/hub server. It was (accidentally) running for a few days because the restart task failed.

I run this dev build now and haven't seen anything strange anymore.
