### ISSUE TITLE
Diamonds

### ISSUE THREAD

**Issue by argnapa** [BenCodez/VotingPlugin#1024]
**Versions**
Plugin version 5.24.1 and Paper 1.16.4

**Relevant information**
Votesite.yml: https://pastebin.com/abxn181x
Config.yml: https://pastebin.com/iJZeV3Hw

**Context**
Hi, how do I remove Diamonds from also being given as a reward?

**Comment by BenCodez** [comment]
Probably another plugin giving the diamond, check CMI if you have that.

**Comment by argnapa** [comment]
That's fixed, thank you sooooo much!!!
