### ISSUE TITLE
Votes are not counting

### ISSUE THREAD

**Issue by MrLarkyy** [BenCodez/VotingPlugin#1030]
**Versions**
5.24.1 and PaperSpigot 1.16.3

**Describe the bug**
Hello! From any reason when a player votes, it normally sends message and commands, but when I check total votes or votetop, nothing changed, like nobody got their vote counted. It gives rewards, but it doesn't increase the number of votes.

Do you think you will be able to help me with issue?
- Thank you, Larkyy.

(I also use VotingPlugin on bungeecord and nuvotifier is installed only on proxy, not on SubServer as it is told in guide)

**Comment by MrLarkyy** [comment]
My config: https://hastebin.com/alaxoyicuf.yaml

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

What setup are you using?

**Comment by MrLarkyy** [comment]
> https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups
> 
> What setup are you using?

I use pluginmsg

**Comment by BenCodez** [comment]
All the same mysql database? Anything in console?

**Comment by MrLarkyy** [comment]
Yup all same DB and nothing in console. (Just going to check proxy's log now)

**Comment by MrLarkyy** [comment]
https://pastebin.com/emsNPPSC

**Comment by MrLarkyy** [comment]
tbh I don't know, why it tells Build1 or Auth, because I didn't even type these servers somewhere and I use votingplugin on Proxy & Survival server only

**Comment by BenCodez** [comment]
Don't forward with nuvotifier. You need to forward with votingplugin

**Comment by MrLarkyy** [comment]
How can I make so?

**Comment by MrLarkyy** [comment]
Ah "none" I see

**Comment by MrLarkyy** [comment]
Ok, I have disabled it and restarted Proxy, but it still doesn't work

**Comment by BenCodez** [comment]
Votingplugin config on bungee?

**Comment by MrLarkyy** [comment]
https://pastebin.com/6UynYJkN

**Comment by BenCodez** [comment]
Prefix: 'Votes_'

Are you using a prefix on all servers?

**Comment by MrLarkyy** [comment]
I used the default config. And when I look into subserver, there is Prefix: '' (maybe would be good to change it by default :D To have it same)

**Comment by MrLarkyy** [comment]
Okay, will try to change it to Votes_ and let you know

**Comment by BenCodez** [comment]
Well, that's your problem then :)

**Comment by MrLarkyy** [comment]
It works, thank you very much sir! I was trying to find the issue for like 1 hour and you helped me really fast. Thank you again :)
