### ISSUE TITLE
Cant add to the vote shop

### ISSUE THREAD

**Issue by Parilia** [BenCodez/VotingPlugin#1031]
**Versions**
VotingPlugin is up to date! Version: 5.24.1.
PAPER-1.16.3-B253

**Relevant information**
https://pastebin.com/xMYWpzZp

**Context**
Trying to add a reward to the reward shop and it will not work. Trying to add the ability to buy land claim blocks from grief prevention.

**Comment by BenCodez** [comment]
1. Confirm your using specialrewards.yml?
2. A lot of spacing issues, to the point where I can't really fix it. Send the whole file?

**Comment by Parilia** [comment]
I was using config.yml as i did not see anywhere in the specialrewards.yml that suggested thats where i was to edit the points store. here is my config.yml
https://pastebin.com/cDa9k0CF

**Comment by BenCodez** [comment]
Yeah you kinda messed up the whole shop part. It's kinda hard to fix so I would just start with the default again. 


    Shop:
      # Identifier
      # Used in placeholders for formats
      # Do not have spaces in the identifier
      Diamond:
        Identifier_Name: 'Diamond'
        # Item
        Material: 'DIAMOND'
        Data: 0
        Amount: 1
        Name: '&4Buy A Diamond'
        # You can set skulls of the player using the following
        # Remove the # to enable
        #Skull: '%Player%'
        Lore:
        - '&c&lCost: &c3 Voting Points'
        # Number of voting points this cost
        Cost: 3
        # Permission required, leave blank for no permission
        Permission: ''
        # Limit how many times you can buy this
        #Limit: 3
        # Reset limit daily/weekly/monthly
        #Reset:
          #Daily: false
          #Weekly: false
          #Monthly: false
        # If true, item is not buyable
        #NotBuyable: false
        # Rewards to run if player buys successfully
        Rewards:
          Items:
            Diamond:
              Material: 'DIAMOND'
              Amount: 1
