### ISSUE TITLE
Toggable votingbroadcasting in Vanish

### ISSUE THREAD

**Issue by PsycPanda** [BenCodez/VotingPlugin#1032]
**Context**
Is it possible to turn off the votingbroadcast regarding specific people (like staffmembers)? Because when u are in Vanish u get broadcasted when voting so you lose the whole point of being in Vanish!

**Comment by BenCodez** [comment]
# Playernames to not be broadcasted when voting
    # case sensitive
    VotingBroadcastBlacklist: []

In config.yml

It also shouldn't broadcast in vanish (or it will regardless of player being online)
