### ISSUE TITLE
[23:36:20 ERROR]: [VotingPlugin] Failed to load VoteSites.yml

### ISSUE THREAD

**Issue by EllaMarie12348** [BenCodez/VotingPlugin#1034]
**Versions**
5.24.1 and 1.16.3

**Relevant information**
idk what to put here 
[Reports.1605656345847.zip](https://github.com/BenCodez/VotingPlugin/files/5556843/Reports.1605656345847.zip)

**Context**
I keep getting this error "[23:36:20 ERROR]: [VotingPlugin] Failed to load VoteSites.yml"

**Comment by BenCodez** [comment]
https://pastebin.com/DytRxm0c

Try that.

**Comment by EllaMarie12348** [comment]
/vote is working now but when i voted i didn't get the reward or anything.

**Comment by BenCodez** [comment]
Is the server getting the vote?

**Comment by EllaMarie12348** [comment]
it says thank you for voting when I vote on the website but the website also has my server marked as offline and idk how to fix that

**Comment by BenCodez** [comment]
Then you have a votifier issue you need to look at.
