### ISSUE TITLE
reward for voting.

### ISSUE THREAD

**Issue by CircuitWrenchy** [BenCodez/VotingPlugin#1037]
Can you modify this so it dose this command crate key %player% vote 1 I can't get it to work
I have - between the hashtag is so it is not big lettering
# 
#-Reward for any site
#-Similar to AnySiteReward
#-This requires the site to be configured in order to get the reward.
VoteSites:
  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/vote/598979
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Player: '&aThanks for voting on %ServiceSite%!'
  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://www.planetminecraft.com/server/voidpvp-4842676/vote/
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward: crate key %player% vote 1

**Comment by BenCodez** [comment]
Pastebin it.

**Comment by CircuitWrenchy** [comment]
https://pastebin.com/nVB1spLJ

**Comment by CircuitWrenchy** [comment]
I am also using the 1.12.2 version just thought I would let you know

**Comment by BenCodez** [comment]
There is no formatting with that pastebin.
