### ISSUE TITLE
Weird Double Reward Bug

### ISSUE THREAD

**Issue by EpicCryziz** [BenCodez/VotingPlugin#1038]
Plugin Version: 5.24.1 
Server Version: Paper 1.16.3

Relevant information
The plugin rewards the players 2 times for 1 vote despite having 1 command to give as a reward.
Except for VoteSites.yml and BungeeSettings.yml haven't touched anything.

![Screenshot_1](https://user-images.githubusercontent.com/34273948/99762368-58936500-2b1e-11eb-9664-2cf98afbe100.png)

BungeeSettings: https://pastebin.com/Dn85RWes
VoteSites.yml: https://pastebin.com/ZFHKqwJj

**Comment by BenCodez** [comment]
Set debug level to EXTRA and send the log on a double reward

**Comment by EpicCryziz** [comment]
I have only removed my ip for this part, rest of the log is unedited.
Log: https://hastebin.com/ivaqetiqas.yaml

**Comment by BenCodez** [comment]
You don't forward with nuvotifier, just disable that.

**Comment by EpicCryziz** [comment]
I am actually using pluginMessaging thing for forwarding votes from bungeecord server. It uses NuVotifier for that.

**Comment by BenCodez** [comment]
VotingPlugin has it's own forwarding (which you enabled)
https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

Disable nuvotifier forwarding

**Comment by EpicCryziz** [comment]
Alright, ill check and see if that fixes it.

**Comment by EpicCryziz** [comment]
Yeah it has been fixed. Thanks alot for helping <3
