### ISSUE TITLE
Hi all some of you may not know how to give rewards for older versions I found out how to here it is.

### ISSUE THREAD

**Issue by CircuitWrenchy** [BenCodez/VotingPlugin#1039]
Hope this helps.

    Rewards:
      Commands:
      - 'crate key %player% vote 1'
      Player: '&aThanks for voting on %ServiceSite%!'

  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/vote/598979
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
      - 'crate key %player% vote 1'
      Player: '&aThanks for voting on %ServiceSite%!'

**Comment by BenCodez** [comment]
This is the same as the new versions....
