### ISSUE TITLE
1.16.4 MySQL database won't connect

### ISSUE THREAD

**Issue by altruiis** [BenCodez/VotingPlugin#1041]
**Versions**
VotingPlugin 5.24.1
PaperMC 1.16.4-275

**Describe the bug**
Trying to connect to a MySQL database but it gives an error saying "Public Key Retrieval is not allowed." Talked to the server host, and they said to go here. Could there be a config entry for flags for the SQL settings?  We have other databases set up and they all require that "allowPublicKeyRetrieval=true" is there. (for example, LiteBans has a flags: entry in the config so we can enable it there)

**To Reproduce**
1. Set up MySQL information in the config
2. Restart server
3. Plugin fails to load because the database/plugin does not allow public key retrieval

**Expected behavior**
The database should connect without an error.

**Comment by BenCodez** [comment]
Under Mysql add:

    Line: '&allowPublicKeyRetrieval=true'

I think that should do it. I'll need to make sure I add that as an actual option

**Comment by altruiis** [comment]
> 
> 
> Under Mysql add:
> 
> ```
> Line: '&allowPublicKeyRetrieval=true'
> ```
> 
> I think that should do it. I'll need to make sure I add that as an actual option

Worked perfectly. Thanks!
