### ISSUE TITLE
Cumulative rewards

### ISSUE THREAD

**Issue by Beaunation** [BenCodez/VotingPlugin#1043]
**Versions**
6.0

**Relevant information**
https://hastebin.com/esavoduwim.yaml
SpecialRewards.yml

**Context**
I use luckperms to promote my players along ranks when they reach a certain voting milestone, however, when i put the milestone along with the command to promote my players, it does nothing when they reach the milestone.

**Comment by BenCodez** [comment]
https://pastebin.com/nNpteMw7
