### ISSUE TITLE
Jitpack 6.0 dependency not working

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#1044]
Was gonna update the dependency to 6.0 on my maven project but it didnt work, so when I checked jitpack it said it had failed and it showed this https://jitpack.io/com/github/Ben12345rocks/VotingPlugin/6.0/build.log error log.

**Comment by BenCodez** [comment]
Try now?

**Comment by DrakePork** [comment]
Nope still doesnt work


my repo and dependency:

        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>

        <dependency>
            <groupId>com.github.Ben12345rocks</groupId>
            <artifactId>VotingPlugin</artifactId>
            <version>6.0</version>
            <scope>provided</scope>
        </dependency>

**Comment by BenCodez** [comment]
<groupId>com.github.BenCodez</groupId>

Might have to make it votingplugin as well (lowercase)

**Comment by DrakePork** [comment]
Ah thats been changed. Might wanna update that on the readme.md and stuff. But yeah works now.

**Comment by BenCodez** [comment]
Yeah, forgot about that.
