### ISSUE TITLE
Disabling shop / GUI?

### ISSUE THREAD

**Issue by Johnibur** [BenCodez/VotingPlugin#1045]
**Versions**
Voting 6.0
Paper 288 (1.16.4) 

**Relevant information**
`VoteShopEnabled: false`
`Commands.UseGui.*` all false

**Context**
Shop and gui's are all working despite having those values to false. I think this is new with 6.0.

**Comment by BenCodez** [comment]
Options are in the GUI.yml

**Comment by Johnibur** [comment]
Okay. So that makes the values previously present in config.yml deprecated? That's a bit of a shame that an update brings default values instead of trying to migrate the old ones.

**Comment by BenCodez** [comment]
Was too much work and hence the 6.0 version name rather than 5.25 or something.
