### ISSUE TITLE
VoteItem Material is not used

### ISSUE THREAD

**Issue by MCD4U** [BenCodez/VotingPlugin#1053]
**Versions**
Plugin build #469 and paper 1.16.3.

**Describe the bug**
The /vote menu doesn't use the materials I specified in the config. For example I have `CanVoteItem` set to lime wool, but it still displays as emerald block.

**Expected behavior**
The materials specified in `AlreadyVotedItem` and `CanVoteItem` should be used

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
```
      AlreadyVotedItem:

        Material: 'RED_WOOL'

        Data: 0 

        Amount: 1

        Name: '&4All Voting Sites'

        Lore:

        - '&cClick Me'

      CanVoteItem:

        Material: 'LIME_WOOL'

        Data: 0

        Amount: 1

        Name: '&4All Voting Sites'

        Lore:

        - '&cClick Me'
```

**Comment by BenCodez** [comment]
Last update moved those options to GUI.yml

**Comment by MCD4U** [comment]
I see. Where is this  change documented though

**Comment by BenCodez** [comment]
In the change log?

**Comment by MCD4U** [comment]
Ok I will keep an eye on it in the future.
