### ISSUE TITLE
 Failed to validate connection (No operations allowed after connection closed.)

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#1054]
**Versions**
VotingPlugin 6.0
Paper-288 (1.16.4)

**Describe the bug**
After switching to MySQL instead of sqlite, every 1-3 minutes I now get 4 identical warns simultaneously.  Now the database as far as I can see is working fine and doing its job, but this warn is kinda filling up the console so is there anyway to fix it?

**To Reproduce**
Enable mysql.

**Expected behavior**
For this warn to not show up.

**Screenshots/Configs**
[Pastebin](https://pastebin.com/i7WjAfJ6)

**Comment by BenCodez** [comment]
Change maxlifetime value?

**Comment by DrakePork** [comment]
Where does one change that

**Comment by BenCodez** [comment]
Either in the config.yml or database side.

**Comment by DrakePork** [comment]
Doesnt seem to be editable in config, and if I check out 
https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/src/com/bencodez/votingplugin/bungee/BungeeMySQL.java
On line 50 theres `long lifeTime = section.getLong("MaxLifeTime", -1);` which cant be edited in the config. Would it be possible to do so that can be edited in the config?

**Comment by BenCodez** [comment]
Just add MaxLifeTime under MySQL

**Comment by DrakePork** [comment]
Yeah changing that and another value seems to have fixed it. Thanks.
