### ISSUE TITLE
Vote Shop not working

### ISSUE THREAD

**Issue by HiMyNameIsBoxxy** [BenCodez/VotingPlugin#1056]
**Versions**
Latest

**Describe the bug**
Before the update, my vote shop was properly displaying spawner items that can be purchased with points. Now it just shows the default diamond.

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
https://pastebin.com/Pke3Y1nW

**Additional context**

**Comment by BenCodez** [comment]
Need to use the GUI.yml, part of the new update. Was in the change log.
