### ISSUE TITLE
VoteShopRequireConfirmation

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1057]
**Is your feature request related to a problem? Please describe.**
For some shop items I would like a confirmation. But not all.

Imaging a shop like:
100 coins for 1 point
500 coins for 5 points
1000 coins for 10 points

e.g.: I would like to buy for 3 points. Then you won't like to confirm for each click. Where for bigger amounts, a confirmation appreciated.

**Describe the solution you'd like**
I would like to add `VoteShopRequireConfirmation` per shop item.

**Describe alternatives you've considered**
Currently using BossShop for this. Each item requires it's own confirmation gui (seperate shops).
Since BossShop is not updated very often, this leads to issues.
Not having to use BossShop eliminates the need for an extra plugin.

**Additional context**
Similar to CloseGUI option
As far as I'm concerned, the current (global) VoteShopRequireConfirmation option doesn't need to disappear.
An optional RequireConfirmation option would be fine and may garantee a smooth transition for those who don't update their gui file.

Btw: I tried Votingplugin 6.0.1 but reverted because BossShop didn't work for some reason. So I remain on 5.x

**Comment by BenCodez** [comment]
I can look at adding this.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Incase you want to test.

**Comment by x1p** [comment]
Seems to work just fine 👍

**Comment by x1p** [comment]
It works awsome. Thnx
