### ISSUE TITLE
/vote GUI <player_name> X /vote history <player_name> - feature request maybe?

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#1059]
**Versions**
Plugin version and spigot version
![image](https://user-images.githubusercontent.com/18662086/100900478-30631900-34c3-11eb-8cd0-7d7a08c64e1e.png)

**Relevant information**
Hi, when I open vote gui of specific player by /vote GUI <player_name> and look at book, it's probably voting history, but it's not voting history only of this player, cause I looked at player MattySenpai and on book are written another names too. Isn't this bug maybe? But what I wanna talk is that the book text is out of screen
![image](https://user-images.githubusercontent.com/18662086/100900004-b0d54a00-34c2-11eb-8db5-8db672478cea.png)
And also I wanna ask if there isn't any other command to see vote history

**Comment by BenCodez** [comment]
/vote today (what you see on the screenshot) shows the votes that have been received today

I probably should only make it show the most recent ones

**Comment by bobhenl** [comment]
And can I see history of specific player?

**Comment by bobhenl** [comment]
But I mean something like that shows you voting history - all votes of specific player for 2 days. I wanted use this when one of my player told me that he lost keys from voting by server accident and I can't simply see how many times he voted yesterday (yea today I could see, but yesterday not).

**Comment by BenCodez** [comment]
There is no history, since it would be a little difficult to store every vote there is.

**Comment by bobhenl** [comment]
Ok, then could be closed. Thanks for answering and improving the book icon.
