### ISSUE TITLE
VotingPlugin with MySQL and Bossshop issue.

### ISSUE THREAD

**Issue by austv** [BenCodez/VotingPlugin#1060]
**Versions**
6.0.1

**Describe the bug**
It appears to be it's taking too long to prepare the data to send it over to the MySQL database (1). Also, a hook problem with BossShop plugin. My points (coming from VotingPlugin) shop is not working anymore (2). 

1- https://pastebin.com/raw/t8eEEy0w
2- https://pastebin.com/raw/rnkg8Eyj

Could you help me?

**Comment by BenCodez** [comment]
1. Are you using sqlite? 
2. https://github.com/BenCodez/VotingPlugin/issues/1047#issuecomment-734160420

**Comment by austv** [comment]
Yes, I am.

**Comment by BenCodez** [comment]
sqlite uses a file in the plugin folder, it's not the same as mysql.

**Comment by BenCodez** [comment]
sqlite uses a file in the plugin folder, it's not the same as mysql.

**Comment by austv** [comment]
do you recommend changing the database the plugin uses? if so, which one?

**Comment by BenCodez** [comment]
Use mysql

**Comment by austv** [comment]
For now, everything seems to be fine. Thanks for the help, if another error occurs I will let you know
