### ISSUE TITLE
MileStones

### ISSUE THREAD

**Issue by ArmadaleMC** [BenCodez/VotingPlugin#1061]
**Versions**
Most Recent.

**Relevant information**
I am trying to set up voting ranks for my server. E.g. when someone reaches 10 votes, commands are activated giving rewards and a suffix. The code is below, why is it not working?

**Context**
    '10':
      Enabled: true
        Rewards: 
          Commands:
            Console:
            - 'pex user %player% suffix "&e*&7"'
            - 'give %player% diamond 5'
            - 'acb %player% 200'
            - 'eco give %player% 1000'
      
   '20':
    Enabled: true
    Rewards: 
      Commands:
        Console:
        - 'pex user %player% suffix "&a*&7"'
        - 'give %player% diamond 10'
        - 'acb %player% 300'
        - 'eco give %player% 2000'
    Messages:
      Console: '&c%player% &7reached 20 votes and is now a &aTier 2 &7Voter!'   

   '50':
    Enabled: true
    Rewards: 
      Commands:
        Console:
        - 'pex user %player% suffix "&b*&7"'
        - 'give %player% diamond 15'
        - 'acb %player% 400'
        - 'eco give %player% 4000'
    Messages:
      Console: '&c%player% &7reached 20 votes and is now a &aTier 2 &7Voter!'

   '100':
      Enabled: true
        Rewards: 
          Commands:
            Console:
            - 'pex user %player% suffix "&d*&7"'
            - 'give %player% diamond 20'
            - 'acb %player% 600'
            - 'eco give %player% 6000'
    Messages:
      Console: '&c%player% &7reached 100 votes and is now a &dTier 4 &7Voter!'   

   '150':
    Enabled: true
    Rewards: 
      Commands:
        Console:
        - 'pex user %player% suffix "&c*&7"'
        - 'give %player% diamond 25'
        - 'acb %player% 800'
        - 'eco give %player% 8000'
    Messages:
      Console: '&c%player% &7reached 150 votes and is now a &cTier 5 &7Voter'      
       
   '300':
    Enabled: true
    Rewards: 
      Commands:
        Console:
        - 'pex user %player% suffix "&c*&7"'
        - 'give %player% diamond 30'
        - 'acb %player% 1000'
        - 'eco give %player% 10000'
    Messages:
      Console: '&c%player% &7reached 300 votes and is now a &cTier 6 &7Voter'

**Comment by BenCodez** [comment]
Use pastebin
