### ISSUE TITLE
Drop items on full inventory - alternative

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#1062]
**Is your feature request related to a problem? Please describe.**
Hi, what about some alternative than only drop items on full inventory? It could be related to issue that players are for ex. in the fly, mining or doing something, or are in world with more people and they lost their things due to it.
**Describe the solution you'd like**
I had an idea about que system that items will be added to que and players will get them on next vote.
**Describe alternatives you've considered**
For ex. giving items when inventory is empty again, so try check free space in inv every few sec, and then give player these items.

**Comment by BenCodez** [comment]
I can look at adding something

I should also add there is a message you can send when the player's inventory is full

**Comment by bobhenl** [comment]
Yeah sorry there is I've missed it, so just maybe another mechanism (s)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

DropOnFullInv: false

Add that in the config, see if it works, checks every 30 seconds, untested

**Comment by bobhenl** [comment]
Oh thanks, is there also message?

**Comment by bobhenl** [comment]
FOr me it seems doesn't work, could you please test it yourselves? Items still dropped on the ground and I'm not sure if all of them. (that's why I'm asking this feature, yesterday someone reported me that items dropped on the ground but he didn't see it, only his teammate)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Should work now.

**Comment by bobhenl** [comment]
Probably not.
![image](https://user-images.githubusercontent.com/18662086/101711464-e31f1280-3a93-11eb-9c85-aa3aa421b82f.png)

DropOnFullInv: false in config.yml at the end
![image](https://user-images.githubusercontent.com/18662086/101711470-e5816c80-3a93-11eb-814d-1d2b6e837c97.png)
And message that items were dropped on the ground due to full inv.

[VotingPlugin] Received a vote from service site 'Czech-Craft.eu' by player 'Renzotom'!

My inventory
![image](https://user-images.githubusercontent.com/18662086/101711665-57f24c80-3a94-11eb-9764-1757e3e4b737.png)
Going to sleep now, please test again.

**Comment by BenCodez** [comment]
You downloaded the build correct? Send your config.yml?

**Comment by bobhenl** [comment]
https://pastebin.com/NXtykus3 Here, still doesn't work.

**Comment by BenCodez** [comment]
Are you using commands to give rewards?

**Comment by bobhenl** [comment]
Yea:
```
    Rewards:
      Money: 500
      Commands:
      - av User %player% AddPoints 3
      - cmi kit HlasovaniCraftList %player%
```
That's maybe the problem. I discovered now that you probably couldn't detect it, or could you?

**Comment by BenCodez** [comment]
Well,I have no control over that. Need to use the builtin item rewards

**Comment by bobhenl** [comment]
Ok, thanks. Then it's ok now.
