### ISSUE TITLE
Tabcomplete avConvertFrom

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1064]
**Versions**
6.0.1 build 470

**Describe the bug**
I was surprised that a default player can see the `/avConvertFrom` command.

**To Reproduce**
1. empty test server
2. Start server with VotingPlugin on it
3. Join with a default player account without any additional permissions
4. Type: `/a` and hit the `<tab>` key

**Expected behavior**
A default player shouldn't have any to do with /av.... commands

**Screenshots/Configs**
![Screenshot_214750](https://user-images.githubusercontent.com/28690790/101686033-cc16fb00-3a68-11eb-902a-e3605eb25859.png)

**Additional context**

**Comment by BenCodez** [comment]
Is AdvancedTab enabled in Config.yml?

**Comment by x1p** [comment]
You mean this?
```yaml
# Disable checking permissions on tab complete
DisableAdvancedTab: false
```

**Comment by BenCodez** [comment]
Oh, I removed that command, so it has no handle.

http://bencodez.com/job/VotingPlugin/

Should do it.

**Comment by x1p** [comment]
Yes, it's gone 👍
