### ISSUE TITLE
[Server] ERROR [VotingPlugin] Failed to load VoteSites.yml

### ISSUE THREAD

**Issue by EllaMarie12348** [BenCodez/VotingPlugin#1065]
This is what I have in my file. It keeps giving me this error though
------------------------------------------------------------

VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  MinecraftServers:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
 
    # Display name of voting site
    Name: 'MinecraftServers.org'
 
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 4
 
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'minecraftservers.org'
 
    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraftservers.org/vote/598293'
 
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
 
    # Use to have a minute votedelay
    #VoteDelayMin: 30
 
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
 
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
 
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
 
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
 
    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'Cr give to %player% vote 1'
      - 'eco give %player% 100'
      # Send player a message
      Messages:
        Player: 'You voted!'
 
  PlanetMinecraft:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
 
    # Display name of voting site
    Name: 'planetminecraft.com'
 
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 3
 
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'planetminecraft.com'
 
    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://www.planetminecraft.com/server/shady-oaks/vote/'
 
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
 
    # Use to have a minute votedelay
    #VoteDelayMin: 30
 
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
 
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
 
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
 
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
 
    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'Cr give to %player% vote 1'
      - 'eco give %player% 100'
      # Send player a message
      Messages:
        Player: 'You voted!'

  Minecraft-mp:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
 
    # Display name of voting site
    Name: 'minecraft-mp.com''
 
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 2
 
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'minecraft-mp.com'
 
    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraft-mp.com/server/272124/vote/'
 
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
 
    # Use to have a minute votedelay
    #VoteDelayMin: 30
 
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
 
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
 
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
 
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
 
    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'Cr give to %player% vote 1'
      - 'eco give %player% 100'
      # Send player a message
      Messages:
        Player: 'You voted!'

  minecraft-server:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
 
    # Display name of voting site
    Name: 'minecraft-server.net'
 
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 1
 
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'minecraft-server.net'
 
    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraft-server.net/vote/ShadyOaksmc/'
 
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
 
    # Use to have a minute votedelay
    #VoteDelayMin: 30
 
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
 
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
 
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
 
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
 
    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'Cr give to %player% vote 1'
      - 'eco give %player% 100'
      # Send player a message
      Messages:
        Player: 'You voted!'

# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by BenCodez** [comment]
Pastebin what you have.

**Comment by EllaMarie12348** [comment]
https://pastebin.com/k4atdU8T

**Comment by BenCodez** [comment]
https://pastebin.com/nkzNJ2xV

Try that.

**Comment by EllaMarie12348** [comment]
the votes aren't going thru to my server

**Comment by BenCodez** [comment]
Check votifier

**Comment by EllaMarie12348** [comment]
The rewards aren't going through now but i have votifier working

**Comment by BenCodez** [comment]
Console log on a vote?

**Comment by EllaMarie12348** [comment]
nothing shows up when i vote in the console but i have all of the things linked websites and stuff and votifier is having no errors

**Comment by BenCodez** [comment]
Then votifier isn't setup properly. Just because there is no errors doesn't mean it's all good. You should get a message in console on a vote.
