### ISSUE TITLE
Chance Reward confusion

### ISSUE THREAD

**Issue by NotableOsprey92** [BenCodez/VotingPlugin#107]
Im very confused on how to set up this bit because i want to have my old luckyvotes from GAL on this but i finf your way very confusing can you help me.

LuckyVotes im trying to convert:
http://pastebin.com/DFKf2HAS
# Chance out of 100
# Must be an integer
# Set to 0 or 100 for always, or delete this line to disable chance
# Will not give any rewards below unless chance is lucky or disabled

Chance: 40
# This is to give random rewards, with fallback
# Rewards defined in this reward file below are still given

Random:
  # Chance to give a randomly selected reward below (from list), will only give random reward
  # if lucky (according to chance)
  # Works same as chance above
  Chance: 40
  # When this reward file is being given, a random reward in the list below
  # will be given, if chance is lucky
  # Don't set this reward as a possible reward, may cause infinite loop
  Rewards: []
  # A list of fall back rewards if chance is unlucky
  # Don't set this reward as a reward, may cause infinite loop
  FallBack: []

**Comment by BenCodez** [comment]
My chance system works different than GAL. I might implement something thing like that in the next update. But for now can do a cumulative rewards, which are kinda similar (See Rewards.yml)

The first chance is the chance to run the stuff in the reward file.

The second chance (the one that has fallback, etc) is a little more advanced. Lets you give a random reward listed if chance is lucky, else give fallback rewards.

I hope that clarifies your understand a little. Let me know if you need more help.

Edit: Implemented the ability to have more than 1 cumulative reward in the next update (basicly allowing what you want above). Aiming for this weekend/following week for release.

**Comment by NotableOsprey92** [comment]
how do i disable both of them?

**Comment by BenCodez** [comment]
Just delete it. (Remove from file)

**Comment by BenCodez** [comment]
Released an update which allows you to do what you want, see Rewards.yml to configure it. (make sure to update it if you already have the file generated)
Let me know if you need assistance.
