### ISSUE TITLE
Milestones not being given to non-operators

### ISSUE THREAD

**Issue by redstonedesigner** [BenCodez/VotingPlugin#1075]
**Versions**
Plugin version and spigot version.

Plugin: 6.0.3
Spigot: 1.16.4-R0.1-SNAPSHOT

**Describe the bug**

Players are voting and are getting the reward for each site, but are not receiving the milestone rewards.  However, server operators (those with /op) are receiving the milestone vote rewards as well as the vote for each site.

**To Reproduce**

[Unknown as I'm not sure how the bug has occured]

**Expected behavior**

Users should be receiving the milestone rewards as well as the reward for voting on each site.

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

SpecialRewards.yml - https://hastebin.com/humetumuwi.yaml
VoteSites.yml - https://hastebin.com/osetisinuv.yaml
Config.yml - https://hastebin.com/ulalenujoy.yaml

**Additional context**

**Comment by BenCodez** [comment]
Do those commands work on non ops from console? There is no permission difference for milestones compared to votesites

**Comment by redstonedesigner** [comment]
Yes, they do work from console.  They work on ops but not on non-ops.

**Comment by BenCodez** [comment]
Well I can tell you right now there is no permission check for milestones. So something else it going on.

How are you testing?
Does this command work?
/av User (player) ForceMilestone (Number)

**Comment by redstonedesigner** [comment]
I have successfully fixed the issue.

For those that come to this issue in the future, the mstake was caused by a misconfiguration.  The '1' milestone rewards shoudl have been configured under "FirstVote" and not a '1' milestone within Milestones.
