### ISSUE TITLE
Broadcasts not appearing anymore

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1077]
**Versions**
VotingPlugin 6.0.3

**Describe the bug**
Broadcasts not appearing anymore

**To Reproduce**
1. Bungee setup:
    SendVotesToAllServers: true
    BungeeMethod: PLUGINMESSAGING
2. Paper setup:
    Format.BroadcastWhenOnline: false
3. Vote
4. See if it broadcasts

**Expected behavior**
Broadcast on every vote to all servers, regardless of online players
VotingPlugin v6.0.1 build 474 used to work just fine

**Screenshots/Configs**
Bungeeconfig:
```yaml
SendVotesToAllServers: true
BungeeMethod: PLUGINMESSAGING
```

Paper config:
```yaml
Format:
  BroadcastWhenOnline: false
```
**Additional context**
Between 6.0.1 build474 and 6.0.3, nothing is changed in configs

Edit: I reverted (only) 1 paper server back to 6.0.1 build 474 and it works again. That means that the bungee part is working properly. So I assume it must be the receiving (paper) server failing to broadcast.

**Comment by BenCodez** [comment]
BungeeSettings.yml? Also are all servers running the latest build?

**Comment by x1p** [comment]
All servers including the bungee were running v 6.0.3 stable as released on spigotmc.org

[BungeeSettings.zip](https://github.com/BenCodez/VotingPlugin/files/5726903/BungeeSettings.zip)

**Comment by BenCodez** [comment]
Try with BungeeBroadcastAlways enabled? Does it broadcast for any vote at all? Online/offline? Nothing was changed with regards to your exact issue, atleast I think so

**Comment by x1p** [comment]
> Does it broadcast for any vote at all? Online/offline?

I didn't receive "thank you for voting" messages on all 4 servers at all.

> Try with BungeeBroadcastAlways enabled? 

I could try that, but that is not desired. This causes re-broadcasting of votes received by empty servers.
Empty servers cache their votes. When e.g. the hub is empty, the vote is cached. When someone enters the hub, the past votes are repeated. What has been done, is done.

**Comment by Sikatsu** [comment]
Voting no longer works for me, 6.0.1 works fine however

**Comment by BenCodez** [comment]
Try this http://bencodez.com/job/VotingPlugin/

**Comment by x1p** [comment]
Doesn't work for me.
I see you changed something with the pluginmessaging. Perhaps this clue may help: I have 6.0.3 on the bungee and 6.0.1 on the servers. And it works anyway.

**Comment by BenCodez** [comment]
Run that build on all servers

**Comment by x1p** [comment]
It appears to function on a test environment.

**Comment by BenCodez** [comment]
Posted an update, should be all good

**Comment by x1p** [comment]
Running 6.0.4 stable. Works fine again.
Thank you
