### ISSUE TITLE
VotingPlugin says i need listeners

### ISSUE THREAD

**Issue by luigitime2** [BenCodez/VotingPlugin#1078]
**VotingPlugin 6.0.3 Spigot Version: CraftBukkit version git-Spigot-f011ca2-3af81c7, API version: 1.16.4-RO.1-SNAPSHOT**
Plugin version and spigot version.

**[16:29:58] [Server thread/ERROR]: [Votifier] See https://github.com/NuVotifier/NuVotifier/wiki/Setup-Guide#vote-listeners for
[16:29:58] [Server thread/ERROR]: [Votifier] a list of listeners you can configure. **
I tried doing a test vote and i got this as a response from the console
**To Reproduce**
1. I tried testing a vote with https://mctools.org/votifier-tester
2. Checked in console
3. Found the error

**Expected behavior**
It is supposed to respond with this user voted

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
it's talking about something completely different then what your thinking of. Does the server get the vote? (There will be a message in console if there is)
