### ISSUE TITLE
Voted on all sites reward bugged

### ISSUE THREAD

**Issue by HiMyNameIsBoxxy** [BenCodez/VotingPlugin#1080]
**Versions**
Latest

**Describe the bug**
I used to give a player a diamond when they voted on all sites. After a server crash, the plugin started giving a player a diamond every day they log in. How can I disable or fix this? I do not wish to wipe the player data.

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
I need a lot more info. Configs? Set DebugLevel to EXTRA and send the log on a diamond reward?
