### ISSUE TITLE
Villagers Exploded by Voting Fireworks

### ISSUE THREAD

**Issue by OpalMoonstride** [BenCodez/VotingPlugin#1083]
**Versions**
VotingPlugin version 6.0.1
Paper version git-Paper-263 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Describe the bug**
When I vote, if there are fireworks, and I am standing near villagers, apparently they explode. lol

**To Reproduce**
1. Stand near villagers, in your owned region.
2. Vote.
3. Receive rewards with fireworks.
4. Villagers die in blazing glory

**Expected behavior**
Villagers not to die in a blazing glory

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/39387146/103144469-b277e380-46f7-11eb-8074-9d7bf98d3b1d.png)
![image](https://user-images.githubusercontent.com/39387146/103144471-b73c9780-46f7-11eb-92fb-fa661b1edd2c.png)

**Comment by BenCodez** [comment]
Guess that's something I'll have to fix

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

That work?

**Comment by OpalMoonstride** [comment]
I can't explode my villagers using the admin test votes, so it appears to work 👍 Thanks!
