### ISSUE TITLE
VoteShop Not working

### ISSUE THREAD

**Issue by Hamosrealy** [BenCodez/VotingPlugin#1084]
**Versions**
Latest VotingPlugin Version 1.15.2 Spigot

**Relevant information**
Pastebin is currently down and isn't working for me heres the problem tho

Shop:
    Rewards:
      Items:
        UngewöhnlicherSchlüssel:
          Material: 'TRIPWIRE_HOOK'
          Amount: 1
          Commands:
          - 'cc give p Ungewöhnlich 1 %player%'
          Name: '&8&lUngewöhnlicher &r&fSchlüssel'
          Lore:
          - '&7Ein Schlüssel für eine Lootbox.'
          - '&7Löse den Schüssel am Spawn ein.'
          - ''
          - '&8&lUngewöhnlich'

**Context**
Why isn't this working?

**Comment by BenCodez** [comment]
You need to edit in GUI.yml since 6.0+

**Comment by Hamosrealy** [comment]
Im using that :/

**Comment by BenCodez** [comment]
Well, it doesn't look like the correct format. Follow the template

**Comment by Hamosrealy** [comment]
Can you give me an example of what it should look like please?

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/GUI.yml#L261

**Comment by Hamosrealy** [comment]
Diamond:
      Identifier_Name: 'Diamond'
      # Item
      Material: 'DIAMOND'
      Data: 0
      Amount: 1
      Name: '&4Buy A Diamond'
      # You can set skulls of the player using the following
      # Remove the # to enable
      #Skull: '%Player%'
      Lore:
      - '&c&lCost: &c3 Voting Points'
      # Number of voting points this cost
      Cost: 3
      # Permission required, leave blank for no permission
      Permission: ''
      # Whether or not to keep GUI open after purchase
      CloseGUI: true
      # Require confirmation on purchase, overrides global option above
      RequireConfirmation: false
      # Overrides other purchase message
      #PurchaseMessage: 'Thanks for the purchase'
      # Limit how many times you can buy this
      #Limit: 3
      # Reset limit daily/weekly/monthly
      #Reset:
        #Daily: false
        #Weekly: false
        #Monthly: false
      # If true, item is not buyable
      #NotBuyable: false
      # Rewards to run if player buys successfully
      Rewards:
        Items:
          Diamond:
            Material: 'DIAMOND'
            Amount: 1   
            
            I'm guessing its this  I still don't see how do I change the format so its a command

**Comment by BenCodez** [comment]
Just change the stuff under Rewards to a command

**Comment by Hamosrealy** [comment]
Bro yk u cann litterly just type it out for me...

**Comment by BenCodez** [comment]
Why should I do it for you for a free plugin?

    Rewards:
      Commands:
      - command here

**Comment by Hamosrealy** [comment]
Then don't add support pages if you wont provide support |

**Comment by Hamosrealy** [comment]
Pisses me off that your said that and I've been waiting all day

**Comment by BenCodez** [comment]
You mean 8 hours? If you want premium support go to a premium plugin, sorry. I provide support when I can. Not immediately when you ask for help. I'm tired of people demanding the best support for a plugin that's completely free to use. If you don't want my help go to another plugin. There is literally a wiki page that shows how to put a command:
https://github.com/BenCodez/VotingPlugin/wiki/Rewards

**Comment by Hamosrealy** [comment]
Its not my fault its free I would rather it be paid if it makes support easier to get

**Comment by Hamosrealy** [comment]
Also I'm pretty sure you got quite a few donations yes?

**Comment by BenCodez** [comment]
Actually I lose money making the plugin, don't even get a profit off doing this. If you read any of the reviews you'll notice I provide good support (probably better than some premium plugins). Anyway, not gonna argue this any longer. I provided you with the example above. But that still doesn't mean that I have to wake up in the middle of the night to come help you, even for a premium plugin. And I'm sure anyone else reading this would agree you can't expect 1 person to be active 24/7

**Comment by Hamosrealy** [comment]
I never expected you to do that I'm just  sayin you said this 'Why should I do it for you for a free plugin?' even after you where awake

**Comment by Hamosrealy** [comment]
Thanks anyway buddy
