### ISSUE TITLE
VOTESHOP 

### ISSUE THREAD

**Issue by Hamosrealy** [BenCodez/VotingPlugin#1086]
Merchant:
      Identifier_Name: 'Diamond'
      Material: 'DIAMOND'
      Data: 0
      Amount: 1
      Name: '&4Buy Merchant Rank'
      Lore:
      - '&c&lCost: &c10 Voting Points'
      Cost: 10
      Permission: ''
      CloseGUI: true
      RequireConfirmation: false
      Rewards:
        Commands:
        - 'lp user %player% parent set merchant'   
    Citizen:
      Identifier_Name: 'Diamond'
      Material: 'DIAMOND'
      Data: 0
      Amount: 1
      Name: '&4Buy Citizen Rank'
      Lore:
      - '&c&lCost: &c20 Voting Points'
      Cost: 20
      Permission: ''
      CloseGUI: true
      RequireConfirmation: false
      Rewards:
        Commands:
        - 'lp user %player% parent set Citizen' 
    Fighter:
      Identifier_Name: 'Diamond'
      Material: 'DIAMOND'
      Data: 0
      Amount: 1
      Name: '&4Buy Fighter Rank'
      Lore:
      - '&c&lCost: &c30 Voting Points'
      Cost: 30
      Permission: ''
      CloseGUI: true
      RequireConfirmation: false
      Rewards:
        Commands:
        - 'lp user %player% parent set fighter' 
    Gladiator:
      Identifier_Name: 'Diamond'
      Material: 'DIAMOND'
      Data: 0
      Amount: 1
      Name: '&4Buy Gladiator Rank'
      Lore:
      - '&c&lCost: &c40 Voting Points'
      Cost: 40
      Permission: ''
      CloseGUI: true
      RequireConfirmation: false
      Rewards:
        Commands:
        - 'lp user %player% parent set noble' 
        
        Whys isnt this working

**Comment by Hamosrealy** [comment]
Bump

**Comment by BenCodez** [comment]
pastebin the whole file, no need to bump it either....

**Comment by Hamosrealy** [comment]
https://pastebin.pl/view/27f83138

**Comment by Hamosrealy** [comment]
bump :D

**Comment by BenCodez** [comment]
use pastebin.com, can't open that link

**Comment by Hamosrealy** [comment]
wait I was using the wrong pastebin the whole time?

**Comment by Hamosrealy** [comment]
https://pastebin.com/AbNPQ5XH

**Comment by Hamosrealy** [comment]
Bump

**Comment by BenCodez** [comment]
https://pastebin.com/DzVM6wwU

Why did you have 2 shops?

**Comment by Hamosrealy** [comment]
Could you please fix it for me man?

**Comment by BenCodez** [comment]
I DID

**Comment by Hamosrealy** [comment]
Das very nice of u :D

**Comment by Hamosrealy** [comment]
Lemme test it out

**Comment by Hamosrealy** [comment]
Worked thanks  sso much <3333
