### ISSUE TITLE
Diamond is given to player joining everyday for no reason

### ISSUE THREAD

**Issue by HiMyNameIsBoxxy** [BenCodez/VotingPlugin#1087]
**Versions**
Latest

**Describe the bug**
When a player joins every 24 hours, the plugin gives the player a diamond and says "You have voted on all sites. Here is a gift!" But in fact, that player never voted on any site in the past 24 hours. This may be caused by the crash before and messed up the files in the plugin.

**To Reproduce**
Keeps happenings.

**Expected behavior**

**Screenshots/Configs**
https://pastebin.pl/view/b675a6b5 (Screenshot of my config)

**Additional context**

**Comment by BenCodez** [comment]
1. Use pastebin.com
2. Unless you specificed that message somewhere, that's another plugin probably

**Comment by HiMyNameIsBoxxy** [comment]
https://pastebin.com/GJ8VWLyh
The message is at around line 902

**Comment by BenCodez** [comment]
Send your specialrewards.yml? You have that message set on a vote party reward?

**Comment by HiMyNameIsBoxxy** [comment]
https://pastebin.com/ZA672gHx

**Comment by BenCodez** [comment]
VoteParty:
      Enabled: true
      VotesRequired: 80
      IncreaseVotesRquired: 40
      GiveAllPlayers: true
      ResetEachDay: true
      ResetMonthly: true
      ResetExtraVotesMonthly: false
      CountFakeVotes: false
      UserVotesRequired: 0
      Broadcast: '&aWe reached &b65 votes today! Everyone gets a gift!'
      Commands: []
      Rewards:
        Items:
          Diamond:
            Material: DIAMOND
            Amount: 1
        Messages:
          Player: '&6You have voted on all sites. Here is a gift!'

That gives every player on the server that reward every x number of votes.
