### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by Castiella** [BenCodez/VotingPlugin#1088]
https://pastebin.com/xbcaeqcM

Firstly, no matter how many times i change the "voteparty" total - it doesnt change. The config can say 5 votes required but in game its stuck at 200.

Also, it keeps broadcasting to everyone when someone votes.... and theres no option for this in the config...
![image](https://user-images.githubusercontent.com/29293070/103874205-cbee3780-50c8-11eb-8c60-0f0a0232bc31.png)

I'd appreciate any help
I'm running 1.16.4 paper & using the latest version of VP from spigot

**Comment by BenCodez** [comment]
You need to edit the vote party in specialrewards.yml (send that file?)

Just set the broadcast message to '' in the config

**Comment by Castiella** [comment]
Thank you!

Ive just set that in this https://pastebin.com/QKyLth6s

as for the broeadcast, its already set to that?


  # Broadcast vote message
  # Set to an empty message to disable
  BroadcastMsg: ''

**Comment by Castiella** [comment]
I have checked every single config and can not find anything for the broadcast. all possible areas have '' in.

This has only happened since updating, so must be something todo with where you've changed all the config files

**Comment by BenCodez** [comment]
https://privatebin.net/?20ffc9a1e2d85833#6hTQyXgshBQmXe1RqYjR8iyzZtXXzLVMNPci7JYyRAFs

Pastebin wouldn't let me upload that for whatever reason, use that for your config.
