### ISSUE TITLE
Detected yml error, please check console for details

### ISSUE THREAD

**Issue by beetlejuiceforpresident1** [BenCodez/VotingPlugin#1089]
Hello, I got this error after changing my VotesSites.yml
If anyone can see the error that would be greatly appreciated because I can't.
Thank you!

# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  minecraftmp:
    Enabled: True
    Name: Minecraft-MP
    Priority: 5
    ServiceSite: minecraft-mp.com
    VoteURL: https://minecraft-mp.com/server/276489/vote/
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - crate key %player% vote 2
      Messages:
        Player: '&6&l[Kangaroo Kingdom]&r&7You've been given a &bVote Coin &l(GRAND OPENING MULTIPLIER X2)&r&7!'
  topminecraftservers:
    Enabled: True
    Name: TopMinecraftServers
    Priority: 4
    ServiceSite: topminecraftservers.org
    VoteURL: https://topminecraftservers.org/vote/15053
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - crate key %player% vote 2
      Messages:
        Player: '&6&l[Kangaroo Kingdom]&r&7You've been given a &bVote Coin &l(GRAND OPENING MULTIPLIER X2)&r&7!'
  planetminecraft:
    Enabled: True
    Name: PlanetMinecraft
    Priority: 3
    ServiceSite: planetminecraft.com
    VoteURL: https://www.planetminecraft.com/server/kangaroo-kingdom/vote/
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - crate key %player% vote 2
      Messages:
        Player: '&6&l[Kangaroo Kingdom]&r&7You've been given a &bVote Coin &l(GRAND OPENING MULTIPLIER X2)&r&7!'
  topg:
    Enabled: True
    Name: TopG
    Priority: 2
    ServiceSite: topg.org
    VoteURL: https://topg.org/Minecraft/in-621659
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - crate key %player% vote 2
      Messages:
        Player: '&6&l[Kangaroo Kingdom]&r&7You've been given a &bVote Coin &l(GRAND OPENING MULTIPLIER X2)&r&7!'
  minecraftserver:
    Enabled: True
    Name: MinecraftServer
    Priority: 1
    ServiceSite: minecraft-server.net
    VoteURL: https://minecraft-server.net/vote/beetlejuiceforpresident1/
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - crate key %player% vote 2
      Messages:
        Player: '&6&l[Kangaroo Kingdom]&r&7You've been given a &bVote Coin &l(GRAND OPENING MULTIPLIER X2)&r&7!'

**Comment by BenCodez** [comment]
psatebin what you have

**Comment by beetlejuiceforpresident1** [comment]
> psatebin what you have

https://pastebin.com/pLeyDGnk

**Comment by BenCodez** [comment]
https://pastebin.com/jKAmMMJG Try that
