### ISSUE TITLE
task 1229612

### ISSUE THREAD

**Issue by s7an1slaw** [BenCodez/VotingPlugin#1090]
vote command is not working

[Fri, 8. Jan 2021 10:16:20 EET INFO] s7an1slaw issued server command: /vote
[Fri, 8. Jan 2021 10:16:20 EET WARN] Plugin VotingPlugin v6.0.4 generated an exception while executing task 1229612

**Comment by BenCodez** [comment]
That the full error?

**Comment by s7an1slaw** [comment]
this is ... and when changing from BOOK mode to CHAT is fixed

**Comment by BenCodez** [comment]
I think there should be more to that error, check the log file?
