### ISSUE TITLE
Votingsites.yml error

### ISSUE THREAD

**Issue by mrshadow-in** [BenCodez/VotingPlugin#1091]
**Versions**
Plugin version and spigot version
Spigot Version:This server is running CraftBukkit version git-Spigot-37d799b-3eb7236 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Plugin Version: 6.0.4
**Relevant information**
Configs that relate to the issue in a Pastebin
Error log: Console https://pastebin.com/p3YCPaUB
Votingsite.yml File: https://pastebin.com/piGnZter

**Context**
Context about the question/concern
I set-up the yml file by seeing Breakdown craft's video and one other but it was returning error constantly i tried by reinstilling the plugin and server.jar file but it doesn't help i not changed and code in other config  files i think is is the problem with set-up pls help

**Comment by BenCodez** [comment]
Remove the console: part and the first site would be correct. Change the
second site to the same as the first one after that.

**Comment by mrshadow-in** [comment]
The Previous Issue was Fixed but a new one came Error Log:
 [VotingPlugin] Failed to hook into vault economy
[11:13:33] [Server thread/WARN]: [VotingPlugin] Failed to hook into vault permissions
[11:13:35] [Craft Scheduler Thread - 4/ERROR]: [VotingPlugin] Failed to load VoteSites.yml
[11:13:35] [Craft Scheduler Thread - 0/INFO]: [VotingPlugin] VotingPlugin is up to date! Version: 6.0.4

<I Don't have Essential Economy Pls Ignore>
Voting Site.yml
https://pastebin.com/KmFJgBdL
pls response

**Comment by BenCodez** [comment]
Try that https://pastebin.com/FL26St0D
