### ISSUE TITLE
Duplicate entry 'uuid' for key 'PRIMARY'

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1092]
**Versions**
VotingPlugin 6.0.4
Paper 1.16.4

**Describe the bug**
Saw this error on the bungee. Didn't seem to do any harm. Looked up this entry in the database but did not see anything out of the ordinary.
https://pastebin.com/raw/hJTyyPKm

**To Reproduce**
Saw this error by accident. Not sure how to reproduce. The player seem to be new according to my information.

**Expected behavior**
No errors :)

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**
This issue is just for your information. Nothing is broken as far as I know.

**Comment by BenCodez** [comment]
Wouldn't worry about it unless it happens alot.

**Comment by x1p** [comment]
Ok, thank you
