### ISSUE TITLE
Unknown username generates error

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1094]
**Versions**
Votingplugin 6.0.4
Paper 1.16.4
Bungee setup

**Describe the bug**
This appeared on the bungee console when a player mistakenly writes his name wrong.
https://pastebin.com/raw/02972hCT

**To Reproduce**
1. Go to votesite
2. Vote for an non-existant playername
3. See error

**Expected behavior**
Maybe this error can be prevented or replaced by something like: VotedName is unknown player and therefor skipped

**Screenshots/Configs**
If you need any file, please say so

**Additional context**

**Comment by BenCodez** [comment]
I guess this is handled correctly, just the exception isn't hidden.

http://bencodez.com/job/VotingPlugin/

That will hide it unless debug is enabled

**Comment by x1p** [comment]
I guess this works. Haven't seen anything weird since.
