### ISSUE TITLE
Detected yml error when trying to add rewards

### ISSUE THREAD

**Issue by IAmNotLiable** [BenCodez/VotingPlugin#1095]
All I changed was the votesites.yml to include a diamond as a reward now, and now I get an error. I have vault installed with nuvotifier. Using Paper 1.16.4. 

**votesites.yml**
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  ExampleVoteSite:
    Enabled: false
    Name: ExampleVoteSite
    Priority: 5
    ServiceSite: PlanetMinecraft.com
    VoteURL: link to vote URL here, used in /vote
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - say hello
      Messages:
        Player: You voted
  Site2:
    Enabled: false
    Name: Site2
    ServiceSite: PlanetMinecraft.com
    VoteURL: link to vote URL here, used in /vote
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - say hello
      AdvancedPriority:
        Reward1:
          Chance: 50
          Messages:
            Player: You got first reward
        Reward2:
          Chance: 20
          Messages:
            Player: You got second reward
        Fallback:
          Messages:
            Player: You got unlucky
      Messages:
        Player: You voted
  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/vote/602296
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
/give %player% diamond 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%! Have a diamond!'
  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://www.planetminecraft.com/server/hemisphere-survival/vote/
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 2
    Rewards:
/give %player% diamond 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%! Have a diamond!'
  Minecraft-Server_net:
    Enabled: true
    ServiceSite: Minecraft-Server.net
    VoteURL: https://minecraft-server.net/vote/Hemisphere/
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 3
    Rewards:
/give %player% diamond 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%! Have a diamond!'
  MCSL:
    Enabled: true
    ServiceSite: MCSL
    VoteURL: https://minecraft-server-list.com/server/471321/vote/
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 4
    Rewards:
/give %player% diamond 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%! Take a diamond and shove a diamond up your arse!'
EverySiteReward: []

**Comment by BenCodez** [comment]
Pastebin what you have

**Comment by IAmNotLiable** [comment]
Here is the console log when I boot up the server:
https://pastebin.com/pCNW7Gh8

Here is a pastebin of votesites.yml:
https://pastebin.com/YxxHSwqV

Another solution that would work fine for me would be if this plugin could handle the UltimateEconomy plugin, which runs off of Vault. Then I could just give people money instead of diamonds.

**Comment by BenCodez** [comment]
Try this:
https://pastebin.com/tmdPkkWn

**Comment by IAmNotLiable** [comment]
Works perfectly. Thanks Ben! 5 Stars
