### ISSUE TITLE
New player - empty broadcast

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1096]
**Versions**
6.0.4 stable
Paper 1.16.4

**Describe the bug**
A new player comes online. He votes.
All servers registers the broadcast. Except the one server the player is online.

**To Reproduce**

1. Player is online for the first time
2. Plays for about 10 min.
3. Disconnects due to timeout.
4. Console broadcasts: "Thank "" for voting on votesite1"
5. Console: `[VotingPlugin] Player has not joined before, disregarding vote, set AllowUnjoined to true to prevent this`
6. Player joins again to survival game and continues to play
7. Player votes on the second site.
8. Broadcast runs fine again.

**Expected behavior**
Votingplugin on that server seems to not have noticed the player who played there for about 10 min.
Other servers on the same bungee did notice it and broadcasted it fine. Even the servers that the player did not joined.
The broadcast should have been: "Thank Player123abc for voting on votesite1"

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Is that the only server with AllowUnJoined set to false?

**Comment by x1p** [comment]
All servers have that setting.
I certainly don't want "funny" votes

**Comment by BenCodez** [comment]
Technically, there is no proper setting for that on bungee methods. I have a few solutions to that I wanna try, but you may have to enabled that to true and I implement something bungee side, will get back to you in a bit with something

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Added the option to bungee, did local testing, should work fine. Set allowunjoined to true on spigot servers. Bungee has the option set to false by default in that build.

**Comment by x1p** [comment]
Did a quick test and it is indeed stopped at the bungee.
`Ignoring vote from ..... `
