### ISSUE TITLE
Problem with Vote page name

### ISSUE THREAD

**Issue by TheDevTec** [BenCodez/VotingPlugin#1097]
**Versions**
VotingPlugin 511 - dev build

**Describe the bug**
We have a problem with the link to the voting page, we want to enter the player's name, but we can't because are translated colors in link to the voting page
-> https://minecraftservery.eu/server/182§nick=StraikerinaCZ

**Screenshots/Configs**
https://minecraftservery.eu/server/182&nick=%player%

**Comment by BenCodez** [comment]
Send your votesites.yml?
You should be able to put that as the voteurl.

**Comment by TheDevTec** [comment]
https://pastebin.com/FctnUsHz

**Comment by BenCodez** [comment]
That should work, this enabled?

      # If true, links will always be forced as urls
      ForceLinks: true

**Comment by TheDevTec** [comment]
What config and section in it should we add it to?

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L129
