### ISSUE TITLE
Querie Size high

### ISSUE THREAD

**Issue by derverdox** [BenCodez/VotingPlugin#1098]
**Versions**
6.0.4

**Describe the bug**
[VotingPlugin] Shutting down mysql, queries to do: 10649, if number is higher than 1000, then something may be wrong

**To Reproduce**
I don't know why that happened

I just wanted to ask what that means?

**Comment by BenCodez** [comment]
Just means mysql background might of failed. Did you do /av reloadall? Anything else in console regarding that?

**Comment by BenCodez** [comment]
Latest update (6.1) might help a bit. Let me know if it changes anything
