### ISSUE TITLE
VoteParty not enabled

### ISSUE THREAD

**Issue by MasonCrollie** [BenCodez/VotingPlugin#1100]
**Versions**
PaperMC: 1.16.5
VotingPlugin: 6.1

**Describe the bug**
Vote Party is enabled in config but not in game. Doing /vote party in game returns VoteParty not enabled.

**To Reproduce**
Enable vote party.
Do /vote party in game

**Expected behavior**
Error in game: VoteParty not enabled

**Screenshots/Configs**
N/A

**Additional context**
N/A

**Comment by BenCodez** [comment]
Send your specialrewards.yml?
