### ISSUE TITLE
Suggestion for Offline Vote spam

### ISSUE THREAD

**Issue by TKwSni** [BenCodez/VotingPlugin#1101]
**Is your feature request related to a problem? Please describe.**
https://github.com/BenCodez/VotingPlugin/issues/1076

**Describe the solution you'd like**
Count the offline votes and just broadcast 1 simple message when the player joins 
(I dont want to broadcast offline votes until players logs in)

This could be done by adding 1 new row to table

if the player is online, ignore it
if the player is offline sum each vote to this row
when the player comes online take the number and send the message
"player voted X times while offline"

**Comment by BenCodez** [comment]
Still looking for this? (You closed the issue)
