### ISSUE TITLE
VoteParty Error

### ISSUE THREAD

**Issue by LucidAPs** [BenCodez/VotingPlugin#1102]
I've been using the voting party feature for a while now with no problems but on the latest dev versions the event doesn't start.

![image](https://user-images.githubusercontent.com/42933023/105836115-6b6e5e00-5fd5-11eb-9a23-51bb596b27ef.png)

![image](https://user-images.githubusercontent.com/42933023/105836070-5db8d880-5fd5-11eb-83e7-34e4188cbc01.png)

SpecialRewards.yml
https://nekobin.com/mexajabeme

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

That better?

**Comment by LucidAPs** [comment]
No it is worse
https://nekobin.com/jisifecewi
unless it's my fault somehow

**Comment by LucidAPs** [comment]
I deleted my database and server data and now everything seems to be working okey.
