### ISSUE TITLE
Voting plugin doesnt give the rewars

### ISSUE THREAD

**Issue by Zlodek** [BenCodez/VotingPlugin#1103]
Hello im using voting plugin adn it does this
![Screenshot_11](https://user-images.githubusercontent.com/78033915/105863003-bb0e5300-5ff0-11eb-9366-9f58a57bc4bd.png)
![Screenshot_14](https://user-images.githubusercontent.com/78033915/105863021-bd70ad00-5ff0-11eb-8bae-9767261a30fc.png)

**Comment by BenCodez** [comment]
Its %player%, also pastebin the whole file

**Comment by Zlodek** [comment]
i dont understand

**Comment by BenCodez** [comment]
1. The player placeholder is %player% not &player&
2. Send your whole file with pastebin.com
