### ISSUE TITLE
VotingPlugin on Bungee org/slf4j/LoggerFactory NoClassDef Error

### ISSUE THREAD

**Issue by ProfessorZel** [BenCodez/VotingPlugin#1104]
Good day for Brilliant devs of VotingPlugin, 
There is a errors i am getting onStartup and onVoteRecieved (sorry for Java'ish notation)
[https://pastebin.com/F09yr5mE](https://pastebin.com/F09yr5mE)

### Overview:
**Bungee network:**
      BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1540
      2 servers: Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
### Configs:
**Bungee server:**
    BungeeSettings.yml - [https://pastebin.com/J9n7zWNj](https://pastebin.com/J9n7zWNj)
      **Survival server:**
            BungeeSettings.yml - [https://pastebin.com/ErDqzCMe](https://pastebin.com/ErDqzCMe)
            Config.yml - [https://pastebin.com/0MRahg7W](https://pastebin.com/0MRahg7W)
      **Factions server:**
            BungeeSettings.yml - [https://pastebin.com/zDJGGD0J](https://pastebin.com/zDJGGD0J)
            (same as survival bcz copied over) Config.yml - [https://pastebin.com/0MRahg7W](https://pastebin.com/0MRahg7W)
### Votifier: 
       nuVotifier installed ONLY on Bungee server. Forwarding is disabled on votifier.

**My understanding of problem:** Not loaded org.slf4j.LoggerFactory dependency causing plugin to throw errors on any vote received, so nothing is going thru.

I can be contacted via Discord: ProfessorZel#0040.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

That fix it?

**Comment by ProfessorZel** [comment]
Good day, so sadly not...
After putting it up we got SEVERE error, here is paste bin of them: [https://pastebin.com/Hp9kKZmN](https://pastebin.com/Hp9kKZmN)
So we setuped a MySQL settings (host, port, db_name, pass and name) (even though we are on PLUGINMESSAGING method), and also got some other SEVERE errors, here is paste bin: [https://pastebin.com/GG2wCV5z](https://pastebin.com/GG2wCV5z)

Right now we are switching to MySQL method, but will check any fixes you want as to.
\

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Should undo the changes of 6.1 which caused the issues.

**Comment by ProfessorZel** [comment]
We had a errors, i think we are out of options, so i moved server recieving votes to one of sub-server, [https://pastebin.com/HJi1A5Vp](https://pastebin.com/HJi1A5Vp)

**Comment by BenCodez** [comment]
'-General'

Did you have that anywhere?

**Comment by ProfessorZel** [comment]
Will search for that, be back in 12 hours.

**Comment by ProfessorZel** [comment]
Yes we have it in DB name, [https://pastebin.com/UsEH9crm](https://pastebin.com/UsEH9crm)
So just for info, we switced to nuVotifer to handle vote forwarding for us.

[https://pastebin.com/aAPjp52y](https://pastebin.com/aAPjp52y)

**Comment by BenCodez** [comment]
I think the - in the database name is the issue most likely (without knowing any more details). Also should be more to that log file (Mainly from startup)
