### ISSUE TITLE
"Could not calculate time until next vote"

### ISSUE THREAD

**Issue by Vehzx** [BenCodez/VotingPlugin#1105]
**Versions**
git-paper-443 | VotingPlugin 6.1

**Describe the bug**
Once you vote, doing /vote again puts the emerald block to a redstone block (as expected), but when hovering the block it no longer gives the expected delay time until vote, instead "Could not calculate time until next vote".

**To Reproduce**
1. Vote on a site
2. /vote
3. See "Could not calculate time until next vote"

**Expected behavior**
Give me an expected time until next vote is available

**Screenshots/Configs**
https://i.gyazo.com/523d56bb9504f81d4c5525bf28135207.png

VoteSites.yml config: https://pastebin.com/EkjNNM5Z

**Additional context**
This is most likely some config error on my side, it's also not a huge issue as most vote sites have their own cooldown if a user tries to vote on them again, just thought i'd send this anyway.

**Comment by BenCodez** [comment]
The message pops up when the votedelay is equal to 0. Which doesn't appear to be the case as far as I can tell. Anything in console? Does it do it for all the sites?

**Comment by Vehzx** [comment]
It does it for all sites once you vote, and nothing in console

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/ What happens with this build?

**Comment by Vehzx** [comment]
Seems it's still happening with that build
https://i.gyazo.com/b0f330f1bdd4cf4f0dbc70c6c38d13cf.png

**Comment by BenCodez** [comment]
Send your startup log?

**Comment by Vehzx** [comment]
[latest.log](https://github.com/BenCodez/VotingPlugin/files/5901343/latest.log)

**Comment by BenCodez** [comment]
I have no idea why you have this issue. For whatever reason it is reading the votedelay as 0, which I can't see any reason why. You can try adding VoteDelayMin: 60 and see what happens I guess

**Comment by Vehzx** [comment]
Do I replace "VoteDelay: 12" with "VoteDelayMin: 60" or should I just add it as a new line underneath in the config?

**Comment by BenCodez** [comment]
Try adding

**Comment by Vehzx** [comment]
still nothing, very strange
https://i.gyazo.com/a30e23afebb86cc477303440c542d78f.png

**Comment by BenCodez** [comment]
I got nothing right now. Do you have another server to test on?

**Comment by Vehzx** [comment]
I will test on a private server later today and get back to you

**Comment by Vehzx** [comment]
Sorry for taking a few days to get back to you, I recently updated the jar from a previously old version from sometime last year, and was using the old config layouts (no GUI.yml etc). I realised I could update the config with the command in-game, this solved the issue.

My bad for this, I really should have realised
