### ISSUE TITLE
All vote sites button sends old vote links

### ISSUE THREAD

**Issue by Vehzx** [BenCodez/VotingPlugin#1107]
Versions
git-paper-443 | VotingPlugin 6.1

Describe the bug
When using the "All vote sites" button, it still sends old voting links even though they have been updated in the votesites.yml.

When clicking on the individual button for that vote site, it sends the updated version.

To Reproduce

Clicking view all vote sites

VoteSites.yml config: https://pastebin.com/EkjNNM5Z

**Comment by BenCodez** [comment]
Send your config.yml?

**Comment by Vehzx** [comment]
Config.yml: https://pastebin.com/JwnmyvDQ

**Comment by BenCodez** [comment]
Commands:
      # Format for /vote
      # %num% = the number of the site, for a numbered list
      # %url% = site URL
      Vote:
        Text:
        - 'https://www.planetminecraft.com/server/foxmc-1-14-3-survival-crates-mcmmo-bosses-100-ranks/vote/'
        - '&ehttps://minecraftservers.org/vote/556887'
        - 'https://topg.org/Minecraft/in-516371'
        - '&ehttps://minecraft-mp.com/server/254705/vote/'
        - 'https://minecraftservers.biz/servers/144462/'
        - '&ehttps://minelist.net/vote/2588'
        - 'https://www.trackyserver.com/server/FoxMC-329982'

You manually set the text?

**Comment by Vehzx** [comment]
oh.. sorry for this pointless post I thought it pulled from the votesites.yml links my bad
