### ISSUE TITLE
Question about nonvotedplayercache

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1108]
**Versions**
Votingplugin 6.1

**Relevant information**
Bungee setup with mysql
AllowUnJoined: false

**Context**
I see a `nonvotedplayerscache.yml` file which begins to fill.
It contains payers who apparently did not vote yet.
So I wonder how long this cache is saved.
If forever: than that file can grow quite large, especially if a server regularly experience bot attacks.
Can't imaging it will keep the contents forever.

So my question is: how long does it keep the information?

**Comment by BenCodez** [comment]
Stores up to 5 days from last login right now. Also won't store if they are in the database.
