### ISSUE TITLE
VoteGui not opening, even with permission

### ISSUE THREAD

**Issue by skyman478** [BenCodez/VotingPlugin#1109]
**Versions**
6.1

**Describe the bug**
when players with the permission to use /votegui use it, it doesn't work, says that they don't have the perm.

**Expected behavior**
Open the voting gui.

**Comment by BenCodez** [comment]
What does it say in console? Does /av permsplayers (player) show they have the perms?

**Comment by skyman478** [comment]
i used this command and this is shown to me 
![image](https://user-images.githubusercontent.com/59271049/106395543-84b24880-63e1-11eb-8dd7-895a53a6e11d.png)

**Comment by skyman478** [comment]
i noticed that when i use /votegui it doesn't open, but when i use /vote gui it works

**Comment by BenCodez** [comment]
Using /votegui works fine for me. Is loadaliases enabled in the config?
