### ISSUE TITLE
More GUI's

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#111]
- [ ] AdminGUI

**Comment by renzotom** [comment]
- [ ] Add chat GUI using https://www.spigotmc.org/resources/chatapi.16245/ PS: This author use chat gui, view his plugin please. Here in chat GUI you can create more themes, more colours...
- [ ]  Add book GUI, how is here https://dev.bukkit.org/bukkit-plugins/slimefun/. PS: You don´t want continue with this plugin? Author now working on games and you are good author, but I don´t know, if you know how work with head textures and next.
- [ ] Add Anvil GUI for other /vote command, where is other PLAYER, ex. /v total PLAYER
- [ ]  Add online searching players (it can show their names and head with skin) for other /vote command, where is other PLAYER, ex. /v total PLAYER
- [ ]  Add to GUI informations about Vote Party
- [ ]  Add to GUI information, how many has player points
- [ ] If you add other GUIS (book and chat) you can do settings, where players can set their default GUI, or you can enable /vote ChestGUI /vote ChatGUI /vote BookGUI
- [ ] Add admin GUI, (/av gui), admins can easily control all in GUI (also can be chest, chat, book, anvil)
- [ ] Add to admin GUI too many commands from /av help 1 2 3

**Comment by BenCodez** [comment]
I'll look into it

**Comment by BenCodez** [comment]
@renzotom 
On a side note, added an api to AdvancedCore which allows users to change values ingame with their chosen method. Currently Anvil/Chat will be supported. But with the api I can easily add another method like signs or books, which I will do eventually. As a note for the other gui's I will look at adding them, but will be for the future :)
