### ISSUE TITLE
How to set up vote party

### ISSUE THREAD

**Issue by Zlodek** [BenCodez/VotingPlugin#1111]
Hello i just dont know how to set up a vote party i did everything else just this i dont have a qlue how to do

**Comment by BenCodez** [comment]
Just follow what is set in specialrewards.yml?

**Comment by Zlodek** [comment]
Hello how can i add how many times they voted  and vote party i have a
voteplugin installed and realscoreboard and that that would be on a
scoreboard

**Comment by BenCodez** [comment]
Use placeholderapi placeholders
