### ISSUE TITLE
Milestones not issuing rewards?

### ISSUE THREAD

**Issue by yatonHamoshiie** [BenCodez/VotingPlugin#1112]
latest versions of both voting plugin, running paper.
I don't seen in the console where any commands are even attempting to be issued once the player reaches the milestone listed below. I can provide anything further needed, but as for the actual milestones this is the first of them and has not been working at all. Thank you in advance for any helpful responses.

MileStones:
  # Number of votes required
  # Allows multiple milestones
  # Number be around ' (E.g. '1')
  # Can have multiple listed here
  '45':
    Enabled: true
    Rewards: 
    - lp user %player% promote vote-ranks
    - acb %player% 3000
    Messages: 
        Player: 'Congratulations! You are now considered a Local! Thanks for being a part of Not Even Vanilla!'

**Comment by BenCodez** [comment]
Wanna pastebin your specialrewards.yml?

**Comment by yatonHamoshiie** [comment]
I believe this is done right. Also thank you for the quick response

[SpecialRewards.txt](https://github.com/BenCodez/VotingPlugin/files/5907138/SpecialRewards.txt)

**Comment by BenCodez** [comment]
You have:

    '45':
      Enabled: true
      Rewards: 
      - lp user %player% promote vote-ranks
      - acb %player% 3000
      Messages: 
        Player: 'Congratulations! You are now considered a Local! Thanks for being a part of Not Even Vanilla!'

You need:

    '45':
      Enabled: true
      Rewards: 
        Commands:
        - lp user %player% promote vote-ranks
        - acb %player% 3000
        Messages: 
          Player: 'Congratulations! You are now considered a Local! Thanks for being a part of Not Even Vanilla!'

**Comment by yatonHamoshiie** [comment]
Of course lol, thank you so much this helps a TON with my stress. XD 20+ people daily on week two I needed this fixed. You rock
