### ISSUE TITLE
conflicting information

### ISSUE THREAD

**Issue by elaineandsparky** [BenCodez/VotingPlugin#1113]
After 5hrs of trying to setup voting through a bungee rather than a single server i've given up!

Your wiki appears to give conflicting information to nuvotifier setup guide in regards to whether nuvotifier should be installed on each backend spigot server or not. Please can you clarify as your info states:

Bungee (VotingPlugin settings):
BungeeMethod: PLUGINMESSAGING
SendVotesToAllServers: true (for a reward on each server) or false (reward on whatever server player connects to first)
**Votifier setup on here only** (no forwarding, nuvotifier forwarding method set to none)
Set MySQL settings

Spigot Servers:
BungeeMethod: PLUGINMESSAGING
UseBungeecord: true
BungeeBroadcastAlways: false (If true, always broadcast, even on cached votes)
VoteSites setup on each server
Some clear cache settings may need to be set to true (Most will be enabled with UseBungeecord enabled)
**No votifier installed**
Set AllowUnJoined to true (Bungee has option and control over this)
Set MySQL settings
Restart may be required for it to work

Yet nuvotifier state to install votifier on all spigot servers:

NuVotifier should be installed on each of the servers you wish to process votes on, as well as the proxy server. The proxy's NuVotifier server will act as the public facing Votifier instance, where as the Minecraft servers will instead receive votes forwarded from the proxy's NuVotifier.

Now you can configure each of the Minecraft servers to accept votes from the plugin messaging channel. Open each of the servers' NuVotifier configurations. Each one should have method under the forwarding configuration section set to pluginMessaging. Since we are receiving forwarded votes through plugin messaging and not through network ports, we should set port on each of the Minecraft servers to -1. This will disable NuVotifier's port, while still allowing it to receive forwarded plugin messaging votes.

**Comment by BenCodez** [comment]
Go by what my wiki says.

**Comment by elaineandsparky** [comment]
After a few more hours work we seem to have it almost setup. However, offline voting isn't working. Any ideas why?

We have nuvotifier proxy set to:
https://pastebin.pl/view/d59e7a38

and votingplugin proxy set to:
https://pastebin.pl/view/7e52f41e

and then votingplugin bungee settings on the spigot servers:
https://pastebin.pl/view/c20d0806

and votingplugin general config for the spigot servers:
https://pastebin.pl/view/182deab9

**Comment by BenCodez** [comment]
Use pastebin.com, pastebin.pl is a really sketchy site that most anti-virus
software won't allow

**Comment by elaineandsparky** [comment]
After a few more hours work we seem to have it almost setup. However, offline voting isn't working. Any ideas why?

We have nuvotifier proxy set to:
https://pastebin.com/xjqEutGa

and votingplugin proxy set to:
https://pastebin.com/Yn4Mp2eK

and then votingplugin bungee settings on the spigot servers:
https://pastebin.com/Q1vHM2rD

and votingplugin general config for the spigot servers:
https://pastebin.com/KSaypxkq

**Comment by BenCodez** [comment]
You need to set the bungeemethod on spigot bungeesettings.yml as well.

**Comment by elaineandsparky** [comment]
We have. The 3rd link is the bungeesettings.yml on the spigot servers

**Comment by BenCodez** [comment]
UseBungeecord: true
    BungeeBroadcastAlways: false
    BungeeDebug: false
    BungeeBroadcast: false
    Server: Bridleigh

Your missing this:

    BungeeMethod: PLUGINMESSAGING

Also restart is required after setting that.

**Comment by elaineandsparky** [comment]
we appear to have 2 different bungeesettings.yml. one of our spigot servers does not have the option to set the bungeemethod.  Our other server, does have this option, which is set. These are the two bungeesettings.yml in their entirety:

https://pastebin.com/kRSyDUVt
https://pastebin.com/92NFz0vC

both of those are the bungsettings.yml for two spigot servers, as you can see, totally different with the 1st one having no option to set the bungeemethod.

**Comment by BenCodez** [comment]
Make sure they both have that option, do a restart, you can test votes with /votingpluginbungee vote (player) (site) & /votingpluginbungee status (will show info in bungee)

**Comment by elaineandsparky** [comment]
ok. are you able to help with another problem?

We think it's due to both servers sharing the same mysql.

If i vote on bridleigh i get 6 points which i do not spend, one vote per site. Which is correct. I go to wichamley and I do not get my points again, which is correct, however, I have the same 6 points i had on bridleigh. Can we seperate the accumulated points? 

so for example, if i save my points over a few days, voting on both servers, i can have 6 points on bridleigh and 10 points on wichamley instead of 16 points on both servers?

**Comment by BenCodez** [comment]
Only way to do that is to separate everything. Which wouldn't work with pluginmessaging.
