### ISSUE TITLE
Milestones not giving rewards

### ISSUE THREAD

**Issue by Ben569483** [BenCodez/VotingPlugin#1116]
Hi,

I'm trying to set up milestones on my server using PEX as my group manager plugin. When I test the vote using /av vote I don't get set to the next rank. Here is my SpecialRewards.yml file: https://pastebin.com/Artmt9gs

I will appreciate any help. Thanks!

**Comment by BenCodez** [comment]
Test with: /av User (player) ForceMilestone (Number)
Might already think you got the milestones already.

**Comment by Ben569483** [comment]
> Test with: /av User (player) ForceMilestone (Number)
> Might already think you got the milestones already.

Yeah that was the issue. Thanks for the quick reply too!
