### ISSUE TITLE
Make /votelast and /votetotal accurate for bungee servers

### ISSUE THREAD

**Issue by kakduman** [BenCodez/VotingPlugin#1117]
**Is your feature request related to a problem? Please describe.**
I have a Discord bot that allows people to check when they last voted by reacting to a message. It worked fine, but it broke when I switched to a bungee server. On votingplugin's bungee configuration (pluginmessaging), /votelast and /votetotal does NOT update until they log in.

**Describe the solution you'd like**
I'd like for /votelast and /votetotal to update immediately.

**Describe alternatives you've considered**
I haven't been able to find any alternatives that actually look at when the player voted. The bot could watch bungee console and calculate /votetotal and /votelast manually but that seems redundant. It also doesn't fix the problem of other online players being unable to tell the offline player their /votetotal or their /votelast.

**Comment by BenCodez** [comment]
That's just a side effect of plugin messaging, I can see what I can do about that though. Spigot servers handle the specific votesites last times, while bungee handles the totals. Socket method could also work for you maybe, since it bypasses that issue.

**Comment by BenCodez** [comment]
I modified the socket method to work a lot more like pluginmessaging: http://bencodez.com/job/VotingPlugin/

If you switch to that it might solve your issue

**Comment by kakduman** [comment]
Awesome, I'll do that and let you know how it goes. I'll reopen the issue if it still exists.

Thanks for your help :)
