### ISSUE TITLE
Ignore votes from votifier

### ISSUE THREAD

**Issue by LucidAPs** [BenCodez/VotingPlugin#1121]
Hello, once again everything was working fine on my network but when I updated to the latest version #577 people stopped getting their rewards.
![image](https://user-images.githubusercontent.com/42933023/107746521-9c14fe00-6d1e-11eb-9b85-9c7fc89bf2fe.png)
Then I saw you made this change. 
"Ignore votes from votifier when using bungeemethod pluginmessaging"
So what am I supposed to do to get it working?

**Comment by BenCodez** [comment]
That means your not using one of the bungee methods as intended: https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by LucidAPs** [comment]
I was using plugin messaging and it was working just fine, until I switched to the latest version like I mentioned above. So I need to change my setup because of the changes you made.

**Comment by BenCodez** [comment]
Your forwarding with votifier, not votingplugin, so pluginmessaging isn't actually doing anything. You could set that to MYSQL and it should work I think. Might add an option to override

**Comment by LucidAPs** [comment]
Yeah I did it your way now instead of nuvotifier's that I had before and it's working fine. Thanks for the help.
