### ISSUE TITLE
[Suggestion] Add an option to not count offline votes towards /vote top

### ISSUE THREAD

**Issue by WhatsTheBadNews** [BenCodez/VotingPlugin#1122]
**Is your feature request related to a problem? Please describe.**
On my server, offline votes are not counted until the next time a player logs in. This means that they can vote offline for several days and then login and get multiple days worth of vote rewards. This is problematic because they can vote for multiple days before `/vote top monthly` resets, then login and be many votes ahead of people who only vote online. We have only have 3 voting websites and offline voters can easily have 15+ votes on /vote top monthly on the first day of the month.

**Describe the solution you'd like**
An option to make offline votes not count towards /vote top

**Comment by BenCodez** [comment]
What exactly is the setup that you are using? It shouldn't queue the totals to be added. 

There is no way to not count totals toward top voter without just ignoring the total addition altogether.
