### ISSUE TITLE
Not going to servers after votifier

### ISSUE THREAD

**Issue by FinlayHDev** [BenCodez/VotingPlugin#1128]
**Versions**
6.1.4 - plugin
latest bungee
latest paper server

**Relevant information**
https://bin.bloom.host/omohiwevuw

**Context**
I want the rewards to get sent to my bungee servers, probably going to be something stupid which I did but that's why I'm asking here :)

**Comment by BenCodez** [comment]
java.lang.NumberFormatException: For input string: "3306:3306"

Did you write the port like that?

**Comment by FinlayHDev** [comment]
It was and I've changed it now but still getting this with the votes not going to the servers 

https://pastebin.com/ydsWyGSB

**Comment by BenCodez** [comment]
That error shows something went wrong with mysql, restart proxy and check the logs

**Comment by FinlayHDev** [comment]
This is the log after restarting https://bin.bloom.host/sahokayora

**Comment by BenCodez** [comment]
Send your bungeeconfig.yml

**Comment by FinlayHDev** [comment]
[Bungeeconfig.txt](https://github.com/BenCodez/VotingPlugin/files/6046313/Bungeeconfig.txt)

*The password was there but I removed it before sending as this is public viewable

**Comment by BenCodez** [comment]
Host: 'x.x.x.x:3306'

You need to remove the port on that.

**Comment by FinlayHDev** [comment]
Oh yeah, I removed the port on my other servers and forgot about that

**Comment by FinlayHDev** [comment]
Seems to be working now, thanks
