### ISSUE TITLE
Clicking on a player in Vote Top GUI opens the Main GUI

### ISSUE THREAD

**Issue by AfkF24** [BenCodez/VotingPlugin#1129]
Hi,

Clicking on a player skull in the VoteTop GUI currently results in opening the main GUI. Is there a way to disable this behavior or have a custom command be executed instead? Not quite sure if this is intended or not.

Thanks

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

https://github.com/BenCodez/VotingPlugin/commit/492dca7a227fa8be0e672e4e747a018b2a4a310e

Added an option to disable that

**Comment by AfkF24** [comment]
Thanks for the quick update! Appreciate it.
