### ISSUE TITLE
Broadcast doesnt support multi-line messages

### ISSUE THREAD

**Issue by R1NZLER15** [BenCodez/VotingPlugin#1130]
**Versions**
VP: 6.1.4
Paper: 1.16.5 #505

**Describe the bug**
Broadcast doesn't appear to support multi-line messages. Is this intended?

**To Reproduce**

Player:
- 'test'
- 'test'
Broadcast:
- 'test'
- 'test'

**Expected behavior**
Uhh... Send a multi-line broadcast.

**Screenshots/Configs**
`
      Messages:
        Player:
        - '&r'
        - '&8&l&m--------------------------------'
        - '&r'
        - '&aYou got&8&l:'
        - '&e  Money&8&l: &6$%money%'
        - '&e  EXP&8&l: &a%exp%'
        - '&e  Items&8&l: &7x2 &bDiamonds'
        - '&r'
        - '&8&l&m--------------------------------'
        - '&r'
        Broadcast:
        - '&r'
        - '&8&l&m--------------------------------'
        - '&r'
        - '&a&l%player% &avoted and got&8&l:'
        - '&e  Money&8&l: &6$%money%'
        - '&e  EXP&8&l: &a%exp%'
        - '&e  Items&8&l: &7x2 &bDiamonds'
        - '&r'
        - '&8&l&m--------------------------------'
        - '&r'
`

**Comment by R1NZLER15** [comment]
The config got messed up. xd

Well. By the time i posted the issue i already got around the problem by using "\n" but as you know its a mess trying to go back and edit messages with that format.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Added support for a list. Should be the same as what you got above.

**Comment by R1NZLER15** [comment]
Thanks, can confirm it now works. Closing.
