### ISSUE TITLE
java.lang.NullPointerException Error

### ISSUE THREAD

**Issue by KptToasty** [BenCodez/VotingPlugin#1131]
Plugin Version: 6.1.4 - Spigot Version: 1.16.1 Bungeecord
The Plugin stops working after a couple of days. Error code is attached
![VotingPlugin](https://user-images.githubusercontent.com/72343058/110011327-990a9d80-7d1f-11eb-81ab-9a2fa2ad5ff8.PNG)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Any better?
