### ISSUE TITLE
%player% not working on VoteParty

### ISSUE THREAD

**Issue by ShockCharge** [BenCodez/VotingPlugin#1132]
https://discordapp.com/channels/407298294390325263/790267597513949184/817749141916483585
![image](https://user-images.githubusercontent.com/48907444/110217493-37009280-7eef-11eb-8fca-fb8aea98abb2.png)

**Comment by BenCodez** [comment]
You need to list the commands under Rewards. Where you have the commands is a global command system, which doesn't factor in the player

    Rewards:
      Commands:
      - 'command here %player%'

**Comment by ShockCharge** [comment]
Solved! you may close this issue.
![image](https://user-images.githubusercontent.com/48907444/110218956-61564e00-7ef7-11eb-930a-20398591af45.png)
