### ISSUE TITLE
Make /vote display URLs and bypass the Block Format

### ISSUE THREAD

**Issue by VimaMT** [BenCodez/VotingPlugin#1133]
VotingPlugin ver. 6.1.5 (and thank you for it)

I was once on another server where they bypassed the GUI and the Blocks when we entered /vote. They displayed a list of URLs instead.

How do I do this? I keep getting the blocks.

**Comment by VimaMT** [comment]
Follow-up question: Is it possible for me to provide some text at the beginning of the list of URLs that tell the players to click on them?

**Comment by VimaMT** [comment]
Would it work if I were to alias /vote to /vote all in my commands.yml, maybe?

**Comment by BenCodez** [comment]
Just set URL to CHAT in GUI.yml (top of the file)

**Comment by VimaMT** [comment]
Thanks.
