### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by istarengwa** [BenCodez/VotingPlugin#1135]
**Versions**
6.1.6 and purpurclip-1002.

**Describe the bug**
Hello, I don't know if this is a bug or an error on my part, but since the penultimate update, I no longer have the broadcast of votes for members, yet everything is activated in the configuration and players receive their winnings correctly for each vote.

**Configs**
Format:
  HelpLine: '&3&l%Commande% - &3%HelpMessage%'

  BroadcastMsg: '&6[&4Heregade&6] &2Merci, &c%player% &2d''avoir voté sur %SiteName%'
  
  BroadcastWhenOnline: false

**Comment by BenCodez** [comment]
Any bungee setup?

**Comment by istarengwa** [comment]
`Debug: false
# Have a reward on each server
# If false, will send to online server only
SendVotesToAllServers: true
# List of servers the plugin won't send the vote to
# Uses names from bungeecoord config if not using SOCKETS method
BlockedServers:
- hub

# What type of bungee setup
# Requires restart and set on all servers
# https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups
# Available:
# SOCKETS 
# PLUGINMESSAGING
# MYSQL
BungeeMethod: PLUGINMESSAGING

# ----------------------------
# SOCKET METHOD Only, ignore otherwise
# ----------------------------
FallBackServer: factions

# Tell servers to broadcast
Broadcast: true

# Bungee communication, Add this to each spigot server
BungeeServer:
  Host: '127.0.0.1'
  Port: 1297
  
# Bungee communication, add each spigot server here
SpigotServers:
  survie:
    Host: '127.0.0.1'
    Port: 1298
  semi-rpg:
    Host: '127.0.0.1'
    Port: 1299`

**Comment by istarengwa** [comment]
```
Debug: false
SendVotesToAllServers: true
BlockedServers:
- hub

BungeeMethod: PLUGINMESSAGING

FallBackServer: factions

Broadcast: true

BungeeServer:
  Host: '127.0.0.1'
  Port: 1297

SpigotServers:
  survie:
    Host: '127.0.0.1'
    Port: 1298
  semi-rpg:
    Host: '127.0.0.1'
    Port: 1299
```

**Comment by BenCodez** [comment]
Does it work with /votingpluginbungee vote (player) (site)?

**Comment by istarengwa** [comment]
this command does not exist

**Comment by BenCodez** [comment]
You have to do it on bungee.

**Comment by istarengwa** [comment]
It just sends me a personal message "thanks for voting on ...." when I put a test server, and for real sites it only gives me the reward, no broadcast

**Comment by BenCodez** [comment]
Wanna send your bungeesettings.yml?

**Comment by istarengwa** [comment]
I don't have a bungeesettings.yml file, if you are talking about the bungeeconfig.yml file I already put it in the conversation above

**Comment by BenCodez** [comment]
It's on the spigot servers

**Comment by istarengwa** [comment]
Ahhhh, I just saw this option in the bungeesettings that I didn't have before the 'BungeeBroadcastAlways' update and so set to false, is that what I need to enable?

**Comment by BenCodez** [comment]
That true and the bungeebroadcast false.
