### ISSUE TITLE
Bungee Issue

### ISSUE THREAD

**Issue by Brazem3** [BenCodez/VotingPlugin#1137]
[https://cdn.discordapp.com/attachments/816409672931082291/822189860961648671/Screenshot_45.png](url)I have this glitch on my bungee with votingplugin he just forward it and then he is like FUCK

**Comment by BenCodez** [comment]
That link doesn't open for me.

**Comment by Brazem3** [comment]
[https://www.mediafire.com/file/kdouf57l3p0y9v5/Screenshot_45.png/file](url)

**Comment by BenCodez** [comment]
Did mysql fail to load? Did you set the mysql database settings?

**Comment by Brazem3** [comment]
https://www.mediafire.com/view/850zs0izs9ta5ou/Screenshot_52.png/file

**Comment by BenCodez** [comment]
Votifier needs to be on bungee not spigot
https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by Brazem3** [comment]
That is already

**Comment by BenCodez** [comment]
Remove votifier off the spigot servers & disable forwarding from votifier on bungee.

**Comment by Brazem3** [comment]
Ok i will check

**Comment by Brazem3** [comment]
So forwarding to none

**Comment by BenCodez** [comment]
Yep

**Comment by Brazem3** [comment]
But now the server not getting anything

**Comment by BenCodez** [comment]
Did you follow this setup exactly?
https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by Brazem3** [comment]
What is MySQL settings

**Comment by BenCodez** [comment]
the mysql database

    # MYSQL Required on all setups
    # MYSQL INFO --------------------------
    Host: ''
    # Default port is 3306
    Port: 3306 
    Database: ''
    Username: ''
    Password: ''
    # Max number of connections
    MaxConnections: 1
    # Maxium size of caching mysql
    # -1 for no limit
    # Affecting this value may affect performance
    MaxSize: -1
    # Table name prefix, for use with mutliple servers
    Prefix: ''
    #UseSSL: true
    #PublicKeyRetrieval: false

**Comment by Brazem3** [comment]
Yeah but how do it work

**Comment by BenCodez** [comment]
that's a vague question, what exactly do you mean?

**Comment by Brazem3** [comment]
Where do i get those settings
