### ISSUE TITLE
Problem bungee

### ISSUE THREAD

**Issue by Brazem3** [BenCodez/VotingPlugin#1138]
**Versions**
Plugin version and spigot version.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by Brazem3** [comment]
He now dont forward it to the servers

**Comment by BenCodez** [comment]
What?
