### ISSUE TITLE
VotingPlugin servicesite for minecraftlist.org does not work

### ISSUE THREAD

**Issue by lcbrakel** [BenCodez/VotingPlugin#1139]
I have a problem with the VotingPlugin plugin. I use some websites to advertise my server on. Every website works but minecraftlist.org does not and the error that I get says that the servicesite is not correct. I had the same problem for other websites but I fixed it by changing it but when I did it for minecraftlist it did not work. The config part in the votesites.yml is here: https://pastebin.com/raw/GGNcgYkr Let me know if you need anymore information.

**Comment by BenCodez** [comment]
When you vote on the site there will be a message in console that would state the correct service site, check that.

**Comment by lcbrakel** [comment]
> When you vote on the site there will be a message in console that would state the correct service site, check that.

It worked thanks i don't know what i did wrong because i did exactly the same but it worked!
