### ISSUE TITLE
Prevent users receiving rewards when offline

### ISSUE THREAD

**Issue by LucidAPs** [BenCodez/VotingPlugin#1140]
Hello I am trying to make users receive rewards only when they are online on the server. I have the options on bungee and on bukkit servers, it was properly on earlier versions.
I am using build 6​47
AllowUnJoined: false
SendVotesToAllServers: false

**Comment by BenCodez** [comment]
What bungee setup are you running?

You can add RewardType: ONLINE within any Rewards to make them only only

**Comment by ThatOneTree** [comment]
I would also like this ability but with vote points as well.

**Comment by BenCodez** [comment]
Just disable PointsOnVote and add a point reward with the rewards?
