### ISSUE TITLE
Placeholder for milestone count

### ISSUE THREAD

**Issue by ehetteNandaYo** [BenCodez/VotingPlugin#1141]
**Describe the solution you'd like**
Basically add a placeholder that shows the value inside the MilestoneCount row

%VotingPlugin_MilestoneCount%

**Comment by BenCodez** [comment]
that already exists

**Comment by ehetteNandaYo** [comment]
Really? I guess Papi wiki is outdated ?

**Comment by BenCodez** [comment]
Use /av placeholders, will list them all up to date, can even do /av
placeholders (player) to see the values
