### ISSUE TITLE
isuue/error

### ISSUE THREAD

**Issue by JagritThukral** [BenCodez/VotingPlugin#1143]
**Versions**
latest plugin and latest paper version

**Describe the bug**
i have setuped nu votifier and voting plugin properly but when i send a test vote from minecraft-mp
it gives me this error 
`06:29:27 [INFO] [NuVotifier] Got a protocol v1 vote record from /149.202.74.183:48346 -> Vote (from:Minecraft-MP.com username:Jagri address:2409:4055:2ebc:d4e5:b18a:7c13:af50:2532 timeStamp:1617596967 additionalData:null)
06:29:27 [INFO] [VotingPlugin] Vote received Jagri from service site Minecraft-MP.com
06:29:27 [SEVERE] java.lang.NullPointerException
06:29:27 [SEVERE] 	at com.bencodez.votingplugin.bungee.VotingPluginBungee.vote(VotingPluginBungee.java:617)
06:29:27 [SEVERE] 	at com.bencodez.votingplugin.bungee.VoteEventBungee.onVote(VoteEventBungee.java:20)
06:29:27 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:29:27 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:29:27 [SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:29:27 [SEVERE] 	at java.lang.reflect.Method.invoke(Method.java:498)
06:29:27 [SEVERE] 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
06:29:27 [SEVERE] 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
06:29:27 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
06:29:27 [SEVERE] 	at com.vexsoftware.votifier.bungee.NuVotifier.lambda$onVoteReceived$2(NuVotifier.java:367)
06:29:27 [SEVERE] 	at com.vexsoftware.votifier.bungee.NuVotifier$$Lambda$414/0x000000003002bc70.run(Unknown Source)
06:29:27 [SEVERE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
06:29:27 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
06:29:27 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
06:29:27 [SEVERE] 	at java.lang.Thread.run(Thread.java:823)`

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Did you set mysql settings on bungee?

**Comment by JagritThukral** [comment]
Yes

**Comment by BenCodez** [comment]
Send bungee startup log?

**Comment by JagritThukral** [comment]
Ok give me a sec
