### ISSUE TITLE
YML Error - Detected yml error, please check console for details

### ISSUE THREAD

**Issue by IodineProx** [BenCodez/VotingPlugin#1144]
I know i have both nuVotifer and VotingPlugin installed FRESH with nothing changed but for some reason when i join my server i just an error message saying "Detected yml error, please check console for details". I have looked at the console but it dosn't really make any sence to me. 

These are all the plugins i have running: AdvancedBan, AuctionHouse, BasicInfo, Chairs, Citizens, CitizensCMD, CoreProtect, dynmap*, EnjinMinecraftPlugin, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), GoldenCrates, GSigns, HolographicDisplays, JetsMinions, Jobs, LibsDisguises, LuckPerms, mcMMO, Multiverse-Core, NexEngine, PlayerVaults*, ProCosmetics, ProtocolLib, Quests, RedeemMCMMO*, SkQuery, skRayFall, Skript, TAB, UltimateTimber, Vault, VoidGenerator, Votifier, VotingPlugin, Vouchers, Wild, WorldBorder, WorldGuard

I have also attached a Paste Bin of my Config.yml and VoteSites.yml - I can't seem to resolve this issue :( 

Config.yml - https://pastebin.com/knNMrdxS
VoteSites.yml - https://pastebin.com/3nMwia2Y

**Comment by BenCodez** [comment]
Send your startup log?

**Comment by IodineProx** [comment]
https://pastebin.com/AffqHnNt

Down towards the end is where i get the big errors

**Comment by BenCodez** [comment]
There is a line in the config, around line 250, replace - '&cToday's Votes
%page%/%maxpage%' with " on the ends instead of ', or remove the list
altogether, I'll need to fix that

**Comment by IodineProx** [comment]
That worked! Thankyou so much! :)
