### ISSUE TITLE
Getting YML Errors, and unsure on how to disable broadcast.

### ISSUE THREAD

**Issue by JustACookie** [BenCodez/VotingPlugin#1145]
**Versions**
Using Paper 1.16.5 and the latest version of the Plugin.

**Relevant information**
config.yml
https://pastebin.com/Wph61jds

votesites.yml
https://pastebin.com/4pGVHzji

**Context**
First off, amazing plugin, keep up the amazing work! I've been really stumped on why I'm getting yml errors and I cannot locate my startup log nor recognize the issue occurring. Additionally, I want to disable the broadcast message as I'm using a different plugin for this and I'm not sure how exactly to do that, I tried `` but it didn't work and I assume this is due to the yml errors.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/
This build will fix it. Just regen your config.yml

Should fix your broadcast issue as well
