### ISSUE TITLE
Placeholders for displaynames/nicknames parse as the current viewer instead of other players

### ISSUE THREAD

**Issue by Kenaestic** [BenCodez/VotingPlugin#1146]
**Versions**

**VotingPlugin:** 6.2.1
**Paper:** 1.16.5 build #584
**Java 11 Hotspot**

**Describe the bug**
In GUIs like VoteTop where other players are listed, the %player_displayname% placeholder parses as the viewer. Thus every player has the name of te viewer instead of the other player's names. Also tried this with %essentials_nickname% but had the same result. I think this worked a while ago. The incentive of using these placeholders is to see their nickname and not their playername. Optionally also gives people the possibility to use color codes, prefixes and suffixes.

**To Reproduce**
_To state the obvious: **PlaceholderAPI required**_

1. Edit GUI.yml
2. Scroll down until you find:
 ```
  VoteTop:
    Name: 'VoteTop %topvoter%'
    BackButton: true
    Item:
      Name: '&3&l%position%: &3%player%'
      Lore: '&3&lVotes: &3%votes%'
    OpenMainGUIOnClick: true
    SwitchItem:
      Name: '&3Switch TopVoter'
      Lore: '&bCurrently: %Top%'
      Material: 'OAK_SIGN'
      Amount: 1
      # 8 Slots over from the bottom left
      Slot: 7
    # Number of topvoters to display on page +9
    # 9 Slots on the botton are used for page buttons
    Size: 27
    # If true, /vote top will show player heads
    UseSkull: true
    # Item for player in GUI if use skull is false
    PlayerItem:
      Material: 'PAPER'
```
3. Change the ```%player%``` placeholder to anything that supports nicknames. For example: ```%player_displayname%```
4. Download the rght placeholders with the ```/papi ecloud download player``` command and then reload PAPI with ```/papi reload```.
5. Reload VotingPlugin.
6. Open up the vote GUI and navigate to VoteTop.
Every player listed should now have your display name.

**Expected behavior**
Other players should be shown with their own display name. Other plugins I use do parse this placeholder conditionally.

**Screenshots/Configs**

With ```%player_displayname%```:

![image](https://user-images.githubusercontent.com/9975975/114103788-020aa580-98ca-11eb-8d8b-d38b2b94df5b.png)
![image](https://user-images.githubusercontent.com/9975975/114103823-0f279480-98ca-11eb-9d66-1bdd2095c407.png)
![image](https://user-images.githubusercontent.com/9975975/114103835-19499300-98ca-11eb-8517-f019a95445d8.png)

With ```%player%```:

![image](https://user-images.githubusercontent.com/9975975/114103934-48600480-98ca-11eb-8664-d57741d39989.png)
![image](https://user-images.githubusercontent.com/9975975/114103948-4dbd4f00-98ca-11eb-852a-365f61f1ac71.png)
![image](https://user-images.githubusercontent.com/9975975/114103968-54e45d00-98ca-11eb-8e27-f6059127fb8f.png)

**Additional context**

My config.yml file: https://pastebin.pl/view/022e29f3
My GUI.yml file: https://pastebin.pl/view/4c460dd0

**Comment by BenCodez** [comment]
Does this work?
http://bencodez.com/job/VotingPlugin/

I don't think it ever was like that before, atleast it wasn't intentional to be like that. Only concern would be performance, but it might be okay

**Comment by Kenaestic** [comment]
Nope :/ and yeah I was becoming less certain every version I went back to check lol. In that case i'd like to make this a feature request 😄

**Comment by BenCodez** [comment]
Does this work? 
http://bencodez.com/job/VotingPlugin/

**Comment by Kenaestic** [comment]
Nope, still the same. Also if you manage to fix it, will that also affect the ```/votetop all``` command when the plugin sends the list in chat?

**Comment by BenCodez** [comment]
try another placeholder? I don't think this will work since it's pretty hard to get nicknames of player that are offline and is dependent on the placeholder your using.

**Comment by Kenaestic** [comment]
I tried it with ```%essentials_nickname%```, too. It doesn't seem to work and yeah that makes sense. AFAIK none of the plugins I have that use these placeholders show anything when the player is offline. Guess I'll be closing this now.
