### ISSUE TITLE
Modify VoteDelay to allow for half hour delay

### ISSUE THREAD

**Issue by banicola** [BenCodez/VotingPlugin#1147]
**Is your feature request related to a problem? Please describe.**
We use a voting website that has a delay of 1h30 between votes. Currently you can only use integer to specify a voting delay.

**Describe the solution you'd like**
Solution 1: Use minutes instead of hours, maybe with a boolean above like: 
- VoteDelayInMinute: true (default is false so that older config would still work)

Solution 2: Allow the use of Float instead of Int, example:
- VoteDelay: 1.5 (for 1h + 0.5*60min or a delay of 1h30)

**Describe alternatives you've considered**
I can only choose between 1 or 2 hours delay currently. That means that I have to choose 1 hour or my player wouldn't be able to vote after the countdown.

**Comment by BenCodez** [comment]
Use VoteDelayMin: 30 with votedelay of 1

**Comment by banicola** [comment]
Thanks for the tip. I didn't see this in the documentation.

**Comment by Uharn** [comment]
I cannot make it work, i have strange behaviours when editing trow adminvote GUI (like modifiing the min delay changes the delay.
and if I try using config it doesnt work as expected (i have a 90minutes voting site)

**Comment by BenCodez** [comment]
Edit it in votesites.yml?
