### ISSUE TITLE
Allow for different rewards in the VoteParty based on user's permission

### ISSUE THREAD

**Issue by banicola** [BenCodez/VotingPlugin#1148]
**Is your feature request related to a problem? Please describe.**
I want to give twice the vote party rewards to some players but it doesn't seem to be possible currently.

**Describe the solution you'd like**
A way to define rewards per user permission

**Describe alternatives you've considered**
No alternative

**Comment by BenCodez** [comment]
Already possible: https://github.com/BenCodez/AdvancedCore/wiki/AdvancedPriority-Examples
