### ISSUE TITLE
Alternative Broadcast option

### ISSUE THREAD

**Issue by JeffHD** [BenCodez/VotingPlugin#1149]
**Is your feature request related to a problem? Please describe.**
If several players vote at once, the chat can be spammed quickly with vote messages

**Describe the solution you'd like**
An option where the number of votes and the players who voted in a certain time is saved and after a fixed time a message is sent with the summary of the last half hour or what you specify as the interval.
For example, the message can then be:
[Vote] Player1, Player2, Player3 (more if wanted) and 13 other players have voted in the last half hour. Thank you all!
or
[Vote] 24 players voted in the last half hour. Thank you all!

Something like that would be great

**Comment by BenCodez** [comment]
I can see what I can do.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/
https://github.com/BenCodez/VotingPlugin/commit/b935d7f5781dd9c3b92abceb9bf054e6e15d77dc

Untested, but should work

**Comment by JeffHD** [comment]
Thanks. I tested it but couldn't get it to work. Debug says: Using alternate broadcast method
But the broadcast message doesn't get send. I looked at the code and in BroadcastHandler the onVote function to add the player to the list is not called anywhere, or I have overlooked it. Or I configured something wrong, but I took it from your config, only shortened the delay for testing

**Comment by BenCodez** [comment]
This better? http://bencodez.com/job/VotingPlugin/

**Comment by JeffHD** [comment]
Yes much better :)
Thanks for your work
