### ISSUE TITLE
Need help with Bungeecord setup

### ISSUE THREAD

**Issue by Shivelight** [BenCodez/VotingPlugin#1150]
**Versions**
Plugin version: 6.3
Spigot version: 1.16.5 (Paper)

**Relevant information**
Bungeecord
bungeeconfig.yml: https://pastebin.com/J7pRPBuE

Spigot
BungeeSettings.yml: https://pastebin.com/72Z3t0ZS
Config.yml: https://pastebin.com/ZvU2BKQZ

**Context**

I'll try to explain my desired configuration then the problem I'm facing. So, I have a Bungeecord server and several backends server, let say I have Hub, Creative, and Skyblock server.

I'm currently using [PLUGINMESSAGING](https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING) setup, each server (creative and skyblock) is using the same MYSQL database.

I want:
- Player can vote whether they are online or offline.
- Player can get a reward on each server. When they vote, they should get Skyblock reward when going to Skyblock server and Creative reward when going to Creative server.
- I want player stat (points, streak, etc.) is synchronized across servers. This is already achieved by connecting to the same MYSQL server.

The problem:
When a player is voting and is online in Hub, the vote is registered, their stat is updated, but when they connect to Skyblock or Creative they don't get any reward. Or, if they vote while online in Skyblock they got Skyblock reward but when they connect to Creative they don't get Creative reward.

If the player is offline while voting, they got the reward on each server when they online.

My wording might be hard to understand, I'm not a native speaker, let's try with scenarios:

- Player A login to the server and spawned in Hub, he then votes and after that, he connects to Skyblock to get his reward, but the reward is not given.
- Player B login to the server and connects to Skyblock, he then votes and gets his reward. Player B wants to get his Creative reward, so he connects to Creative, but the reward is not given.
- Player C is not connected to the server (offline), he then votes, and after that, he opens Minecraft and login to the server. He connects to Skyblock and gets his reward. After playing for a while, he wanted to play Creative, so he connects to Creative and gets his reward. 

The Player C scenario is the behavior I wanted, but it only works if the player is offline.

**Comment by BenCodez** [comment]
1. Latest plugin version?
2. Nuvotifier forwarding method set to none on bungee?
3. What does /votingpluginbungee status show in proxy console?
4. You all servers set on the same mysql database? (including bungee?)
5. You have each servers name set in BungeeSetttings.yml? (from what bungee sets them as)

**Comment by Shivelight** [comment]
>     1. Latest plugin version?
> 
>     2. Nuvotifier forwarding method set to none on bungee?
> 
>     3. What does /votingpluginbungee status show in proxy console?
> 
>     4. You all servers set on the same mysql database? (including bungee?)
> 
>     5. You have each servers name set in BungeeSetttings.yml? (from what bungee sets them as)

1. Yes, 6.3 (md5sum `0480e80b5b85f63cb59579d3e826c501`), equal with http://ben12345rocks.com/job/VotingPlugin/714/
2. Yes
3.
 ```
[01:08:58 INFO]: Checking status, waiting for response, check console, method: plugin messaging
[01:08:58 INFO] [VotingPlugin]: Sending request for status message on creative
[01:08:58 INFO] [VotingPlugin]: No players on server prison to send test status message
[01:08:58 INFO] [VotingPlugin]: Sending request for status message on rpg
[01:08:58 INFO] [VotingPlugin]: No players on server development to send test status message
[01:08:58 INFO] [VotingPlugin]: Sending request for status message on skyblock
[01:08:58 INFO] [VotingPlugin]: Sending request for status message on survival
[01:08:58 INFO] [VotingPlugin]: No players on server lobby to send test status message
```
4. Yes, including bungee
5. Yes

**Comment by BenCodez** [comment]
Does it work fine with /votingpluginbungee vote (player) (site)?

**Comment by Shivelight** [comment]
Nope, the exact same scenario as what I explained above

**Comment by BenCodez** [comment]
3. Judging from the log on that it doesn't seem pluginmessaging is working correctly. 

There is a few options we can try:
- You can set WaitUntilUserIsOnline on bungee to true (might not be the exact option name)
- You can go with this setup: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-SOCKETS pretty much like votifier forwarding, but with votingplugin handling it

**Comment by Shivelight** [comment]
Ok so, If run `/votingpluginbungee vote` or vote manually on web while I'm offline and then online afterward, there is a delay before I got the reward, but I do get the reward on each server I connected to.

What I expect is votingplugin on spigot only attempts to give rewards when the user is online on the server.

>     1. Judging from the log on that it doesn't seem pluginmessaging is working correctly.
> 
> 
> There is a few options we can try:
> 
>     * You can set WaitUntilUserIsOnline on bungee to true (might not be the exact option name)
> 
>     * You can go with this setup: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-SOCKETS pretty much like votifier forwarding, but with votingplugin handling it

If you mean WaitForUserOnline, it is already set to true.

I'll try to setup on my local machine and report back later.

**Comment by BenCodez** [comment]
try with that option set to false then?

**Comment by Shivelight** [comment]
Same result, it is false by default, setting it to true was my attempt to fix the problem.

**Comment by BenCodez** [comment]
it should be working with it set to false, socket method might be the way to go then

**Comment by Shivelight** [comment]
I'll close it for now.
