### ISSUE TITLE
Player Head / Skull

### ISSUE THREAD

**Issue by AnimeDrache** [BenCodez/VotingPlugin#1151]
**Versions**
Plugin version and spigot version
Current
**Relevant information**
Configs that relate to the issue in a pastebin.
-
**Context**
Context about the question/concern
Greetins, I am trying to figure out how people can acutally get a skull of themself with the vote points. This is my current setup for it but I am doing something wrong cause its not working. I appreciate your help =). ![index](https://user-images.githubusercontent.com/51856826/116954035-1ce4f580-ac8f-11eb-9b42-f7e411fce2bc.png)

**Comment by BenCodez** [comment]
change the material to PLAYER_HEAD

**Comment by AnimeDrache** [comment]
It still doesnt work. It charges the points but do nothing. If I add this to the "commands" then it just gives a basic player head but not the one from the person using that command.:
![Screenshot_1](https://user-images.githubusercontent.com/51856826/117338490-eaa9e280-ae9e-11eb-9c88-0f18c3af9f41.png)

**Comment by BenCodez** [comment]
If you use a command you need to use a command that sets the skull

    Rewards:
      Items:
        item:
          Material: PLAYER_HEAD
          Amount: 1
          Skull: '%player%'

**Comment by Royster-85** [comment]
Can confirm, that this is correct. It does show a generic head (I think its an Alex head) and not the head of the player. Have tried %player% and %Player%. Same thing. Just noticed this today.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Does this fix it?

**Comment by Royster-85** [comment]
Yep. Thats all working :D
