### ISSUE TITLE
Reward API Question

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#1152]
Heya, Im trying to setup a system whereby I prevent players from getting voting/vote party rewards while they are in parkour using: `Parkour.getInstance().getPlayerManager().isPlaying(player)`.

**Cases:**
```
- Rewards received while user is in parkour
- Join rewards received while player is in parkour
```
Im thinking of sending the message saying they voted and only preventing the reward until they player is out of the parkour. What direction do you recommend I take?

**Comment by BenCodez** [comment]
Is that in a different world? Otherwise you could inject a requirement into the reward system or javascript system.

**Comment by LogGits** [comment]
I'll try injecting requirements. In doing so would that prevent the user from getting the rewards until the requirements are net? If so, where can i find more info about requirements usage?

**Comment by BenCodez** [comment]
injectedRequirements.add(new RequirementInjectString("Server", "") {

			@Override
			public boolean onRequirementsRequest(Reward reward, AdvancedCoreUser user, String str,
					RewardOptions rewardOptions) {
				// set server to match
				String serverToMatch = str;
				boolean hadPlaceholder = false;
				if (str.isEmpty()) {
					if (rewardOptions.getPlaceholders().containsKey("Server")) {
						serverToMatch = rewardOptions.getPlaceholders().get("Server");
						hadPlaceholder = true;
					} else if (!rewardOptions.getServer().isEmpty()) {
						serverToMatch = rewardOptions.getServer();
					}
				}
				String currentServer = AdvancedCorePlugin.getInstance().getOptions().getServer();

				if (!serverToMatch.isEmpty()) {
					debug("Current Server: " + currentServer + ", ServerToMatch: " + serverToMatch);
					boolean matched = serverToMatch.equalsIgnoreCase(currentServer);

					if (!matched && !hadPlaceholder) {
						// add server for offline reward
						rewardOptions.addPlaceholder("Server", serverToMatch);
					}

					return matched;

				}

				return true;
			}
		}.priority(100).allowReattempt().alwaysForceNoData().addEditButton(
				new EditGUIButton(new ItemBuilder(Material.PAPER), new EditGUIValueString("Server", null) {

					@Override
					public void setValue(Player player, String value) {
						RewardEditData reward = (RewardEditData) getInv().getData("Reward");
						reward.setValue(getKey(), value);
						plugin.reloadAdvancedCore(false);
					}
				}.addOptions(Bukkit.getServer().getName()).addLore("Server to execute reward on"))));

That's for server handling, this allows reattempts if the require is not met. just use VotingPluginHooks.getInstance().addCustomRequirement(requirement)

**Comment by LogGits** [comment]
Ah cheers ill give it a shot later tonight.

**Comment by LogGits** [comment]
Wasn't too sure what the other builder options were. How's this lookin:
```java
RequirementInject parkourRequirement = new RequirementInject("parkour") {
    @Override
    public boolean onRequirementRequest(Reward reward, AdvancedCoreUser advancedCoreUser, ConfigurationSection configurationSection, RewardOptions rewardOptions) {
        return !Parkour.getInstance().getPlayerManager().isPlaying(advancedCoreUser.getPlayer());
    }
};
```
not able to test rn, could you confirm my usage will result in;
- Players vote rewards being delayed until they leave the parkour?
- Players party rewards being delayed until they leave the parkour?
(I can setup an event listener to check when the player exits the parkour)

**Comment by BenCodez** [comment]
RequirementInject parkourRequirement = new RequirementInject("parkour") {
		    @Override
		    public boolean onRequirementRequest(Reward reward, AdvancedCoreUser advancedCoreUser, ConfigurationSection configurationSection, RewardOptions rewardOptions) {
		        return !Parkour.getInstance().getPlayerManager().isPlaying(advancedCoreUser.getPlayer());
		    }
		}.alwaysForceNoData().allowReattempt();

this should do it

**Comment by LogGits** [comment]
Ah ok awesome, what do those builder methods do?
If I understand correctly, `alwaysForceNoData` forces there to be no reward if requirement isn't met and `allowReattempt` allows system to reattempt the requirement check on an interval (if so, what's the interval in seconds)

Cheers in advance :)

**Comment by BenCodez** [comment]
alwaysforcenodata - forces the requirement to be checked if not set within the reward (as in defined in the config)
allowReattempt - allows the reward to be reattempted later if requirement failed, rather than discarding the reward

Interval for background updates is 3 minutes or so and only happens on a vote

**Comment by LogGits** [comment]
Awesome, thanks for clarifying :) Will reopen if Im unable to get it working.

**Comment by LogGits** [comment]
Seems to have worked in preventing the rewards. Awesome!!!! Is there a way to force a background update for a player? (so i can give the rewards after they exit the parkour)

**Comment by BenCodez** [comment]
Easiest way is to run /av backgroundupdate, I can add something to make it easier to do 1 player only

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/commit/60db0e87f4ba3c6a38e1b9305f0c16d3c1118740

http://bencodez.com/job/VotingPlugin/

Added something to make it easier for you.

**Comment by LogGits** [comment]
Oh nice, thank you so much 🙂
