### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by JavierPM87** [BenCodez/VotingPlugin#1156]
Hello, I was configuring the plugin, and adding the last touches, but suddenly this appeared in the console, I reverted the changes with my backup, but it keeps giving the error, any idea what may be causing this?

https://pastebin.com/kThyMKEd

**Comment by JavierPM87** [comment]
https://pastebin.com/Z5AUXJgi

**Comment by BenCodez** [comment]
startup log from a fresh restart?

**Comment by JavierPM87** [comment]
If I delete the VotingPlugin folder there is no error when reloading, I think it is when I link it to the Mysql database that I created for the plugin and do / av reload
yesterday I was configuring the gui.yml file and doing / av reload was when the problems appeared for the first time

I have opened another ticket on NuVotifier for a warn that also appears
https://github.com/NuVotifier/NuVotifier/issues/242

**Comment by JavierPM87** [comment]
Now everything seems to be working properly, sorry for the inconvenience

https://github.com/NuVotifier/NuVotifier/issues/241
