### ISSUE TITLE
Broadcasts not working

### ISSUE THREAD

**Issue by tomhula** [BenCodez/VotingPlugin#1158]
**Versions**
6.3

**Describe the bug**
I've got all options related to broadcasts on. The rewards get processed as they should, but the broadcasts just don't show up. No error. No info in Debug.

**To Reproduce**
- Setup Bungeecord using PLUGINMESSAGING
- set your broadcast in Config.yml

**Expected behavior**
The broadcast showing up in the chat.

**Screenshots/Configs**
[bungeeconfig.txt](https://github.com/BenCodez/VotingPlugin/files/6524335/bungeeconfig.txt)
[BungeeSettings.txt](https://github.com/BenCodez/VotingPlugin/files/6524336/BungeeSettings.txt)
[Config.txt](https://github.com/BenCodez/VotingPlugin/files/6524337/Config.txt)

**Comment by tomhula** [comment]
Changed the mysql password btw ;)

**Comment by BenCodez** [comment]
Disable this in bungeesettings.yml: BungeeBroadcast: true

**Comment by tomhula** [comment]
It is.

**Comment by BenCodez** [comment]
You set that to false?

**Comment by tomhula** [comment]
Oh, I'm dumb thank you, I misread your reply. Could you please also explain me, what exactly does it do?

**Comment by BenCodez** [comment]
It disables the broadcast and tells bungeecoord to tell all servers to broadcast

**Comment by tomhula** [comment]
And how would I make it, so there is one reward on network, but the vote is broadcasted on all servers?

**Comment by BenCodez** [comment]
Then you would want that set to true in that case, ususally you would get double broadcasts otherwise.

**Comment by tomhula** [comment]
But then the broadcasts don't work altogether.

**Comment by BenCodez** [comment]
sounds like plugin messaging itself isn't working. You have that set on all servers and restarted?

Does /votingpluginbungee status work at all? (have players online to test that)

**Comment by tomhula** [comment]
Result of `/votingpluginbungee status`:
![VotingPluginBungee](https://user-images.githubusercontent.com/47734291/119348217-d9cddf00-bc9c-11eb-8379-deed9d28a048.png)

One player on Lobby server and nothing in Lobby console. No broadcast anywhere. The rewards work correctly.

**Comment by BenCodez** [comment]
Yeah, pluginmessaging itself isn't working. Do you set pluginmessaging and restart all servers? Also up to date on all servers?

**Comment by tomhula** [comment]
Yes. All servers are the newest version of VotingPlugin.

Configs (both spigot servers have the same):
[Spigot-Config.txt](https://github.com/BenCodez/VotingPlugin/files/6532719/Config.txt)
[Spigot-BungeeSettings.txt](https://github.com/BenCodez/VotingPlugin/files/6532720/BungeeSettings.txt)
[Bungee-bungeeconfig.txt](https://github.com/BenCodez/VotingPlugin/files/6532721/bungeeconfig.txt)

**Comment by BenCodez** [comment]
Yeah, I think the issue is with bungeecoord pluginmessaging itself not working, you could go with the socket method I guess.

Some bungeecoord setups don't seem to have pluginmessaging working correctly, check your bungeecoord is setup correctly, but if everything looks correct then go with socket method

**Comment by tomhula** [comment]
could the problem be in firewall?

**Comment by BenCodez** [comment]
Might be possible I guess, haven't been able to solve this issue for anyone that's experienced it so far, since I can't see what's wrong with it. Only been a couple of cases of it though

**Comment by tomhula** [comment]
Nope it's not problem with firewall.

**Comment by BenCodez** [comment]
Best thing I can say is try this method: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-SOCKETS

**Comment by tomhula** [comment]
And why is it normal, that the rewards work just fine, only the broadcasts don't (still pluginmess)?

**Comment by BenCodez** [comment]
because the rewards don't rely on bungeecoord

**Comment by tomhula** [comment]
How big the delay is in mysql method?

**Comment by BenCodez** [comment]
without pluginmessaging (uses plugin messaging to speed the time up), up to like 3 minutes

**Comment by tomhula** [comment]
Hm, I guess I'll go with the mysql. Thank you for your help :)

**Comment by tomhula** [comment]
Um, so is there something new about the pluginmessaging not working? Like if someone knows about some solution, or atleast what the cause might be?

**Comment by BenCodez** [comment]
@Tomasan7 What do you mean not working? Does /votingpluginbungee vote (player) (site) work?

**Comment by tomhula** [comment]
When I do `/votingpluginbungee status` and there is one player on one server, on bungee it says 
![image](https://user-images.githubusercontent.com/47734291/124818050-d780c500-df6a-11eb-8822-0c40f8208b0a.png)
But there is nothing in Survival's console.

**Comment by BenCodez** [comment]
So pluginmessaging isn't working, not sure what I can do for you, make sure your up to date on all servers

**Comment by tomhula** [comment]
Yup, I run the latest 6.4.1

**Comment by BenCodez** [comment]
I don't know, not much I can do if pluginmessaging itself doesn't work. Did it ever work?

**Comment by tomhula** [comment]
nope

**Comment by BenCodez** [comment]
is bungee setup correctly?

**Comment by tomhula** [comment]
Exactly as described [here](https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING).

**Comment by BenCodez** [comment]
I mean bungeecord itself: https://www.bisecthosting.com/clients/knowledgebase/29/How-to-setup-BungeeCord.html

**Comment by tomhula** [comment]
yes

**Comment by BenCodez** [comment]
Use sockets method then, can't do anything about pluginmessaging not working.

**Comment by tomhula** [comment]
Tommorow, Ill try if the plugin messaging doesn't work altogether or just this plugin (just in case)

**Comment by BenCodez** [comment]
Let me know the results, have had a few other people have similar issues.

**Comment by tomhula** [comment]
Ok, just now I tested if the PluginMessaging work, using some code I found on internet and it **did** work as expected.

Bungee code:
```java
public class PMCommand extends Command
{
	public PMCommand ()
	{
		super("pmtest");
	}

	@Override
	public void execute (CommandSender sender, String[] args)
	{
		if (!(sender instanceof ProxiedPlayer))
			return;

		ProxiedPlayer player = (ProxiedPlayer) sender;

		ServerInfo serverInfo = player.getServer().getInfo();

		PMBungee.getInstance().getLogger().info(ChatColor.AQUA + "Sending message to " + serverInfo.getName() + ".");

		sendCustomData(player, "data1", 69);
	}

	public void sendCustomData (ProxiedPlayer player, String data1, int data2)
	{
		ByteArrayDataOutput out = ByteStreams.newDataOutput();
		out.writeUTF("MySubChannel"); // the channel could be whatever you want
		out.writeUTF(data1); // this data could be whatever you want
		out.writeInt(data2); // this data could be whatever you want

		// we send the data to the server
		// using ServerInfo the packet is being queued if there are no players in the server
		// using only the server to send data the packet will be lost if no players are in it
		player.getServer().getInfo().sendData("my:channel", out.toByteArray());
	}
}
```

Spigot code:
```java
public final class PMSpigot extends JavaPlugin implements PluginMessageListener
{
	@Override
	public void onEnable ()
	{
		getServer().getMessenger().registerIncomingPluginChannel(this, "my:channel", this);
	}
	@Override
	public void onPluginMessageReceived (String channel, Player player, byte[] message)
	{
		if (!channel.equalsIgnoreCase("my:channel"))
		{
			return;
		}
		ByteArrayDataInput in = ByteStreams.newDataInput(message);
		String subChannel = in.readUTF();
		if (subChannel.equalsIgnoreCase("MySubChannel"))
		{
			String data1 = in.readUTF();
			int data2 = in.readInt();

			Bukkit.broadcastMessage("§6Data1: " + data1);
			Bukkit.broadcastMessage("§6Data2: " + data2);
		}
	}
}
```

**Comment by BenCodez** [comment]
Restart every server and see if it changes anything?

**Comment by tomhula** [comment]
nope, nothing changed.

**Comment by BenCodez** [comment]
Then I got no idea. Use socket method I guess.
