### ISSUE TITLE
Support for other plugins

### ISSUE THREAD

**Issue by renzotom** [BenCodez/VotingPlugin#116]
Please, add support for:
- [x]  BossShop plugin (I mean add Vote Points to this plugin) - https://www.spigotmc.org/resources/bossshop.222/
- [ ]  SlimeFun plugin (I mean too many items to give from this plugin) - https://dev.bukkit.org/bukkit-plugins/slimefun/
- [ ] Too many Quests plugin, beacuse it can be quest
- [x] Add to this plugin placeholder, how many is needed to Vote Party, how many players have now and next... https://www.spigotmc.org/wiki/placeholderapi-placeholders/
- [ ] TradeMe https://www.spigotmc.org/resources/trademe-bungeecord-trading-support.7544/ , I mean, players can trade with vote points
- [ ] Mail https://www.spigotmc.org/resources/mail-full-recode-80-off-sale.7351/ , I mean, players can send to others via mail their vote points
- [ ] Bank https://www.spigotmc.org/resources/bank-updated-for-1-10.3556/ , I mean, players can give to bank their vote points

Maybe I edit it with new ideas.

**Comment by BenCodez** [comment]
@renzotom 
Added the placeholder for an upcoming update. Also looking at the BossShop points. Slimefun's api is a bit tricky to allow items to be given directly, so I may not bother with that this update. Also what do you mean by quests plugin?

**Comment by renzotom** [comment]
I mean, they get quest ex. vote 5\* and after they get reward. Like this plugin https://www.spigotmc.org/resources/quests.3711/ support GAListener, but you can add also support to other quests plugin, beacuse this is not best. 

Author of BossShop reply me: Alright, I'll add support for VotingPlugin Points.

**Comment by BenCodez** [comment]
@renzotom 
https://www.spigotmc.org/resources/bossshop.222/update?update=111713

**Comment by renzotom** [comment]
Thank you and author also.

**Comment by BenCodez** [comment]
@renzotom 
Gonna close this since most of these things require other devs to do it, not me. 
As for stuff like slimefun I created this: https://github.com/Ben12345rocks/AdvancedCore/issues/14

**Comment by renzotom** [comment]
You can contact them for help, no? I also tried contact them.

**Comment by BenCodez** [comment]
Maybe
