### ISSUE TITLE
Not able to give group/rank

### ISSUE THREAD

**Issue by JagritThukral** [BenCodez/VotingPlugin#1161]
I wanted to add a group to users when they vote .
So i added
rewards:
   commands:
   - 'lp user %player% parent tempadd voter 24h '
   But it doesn't work

**Comment by BenCodez** [comment]
send the whole file

**Comment by JagritThukral** [comment]
[https://pastebin.com/TfqVxBFX](url)

**Comment by BenCodez** [comment]
It's Commands, not commands, case sensitivie

**Comment by JagritThukral** [comment]
Ok 😶
