### ISSUE TITLE
Cumulative Rewards Seem to use Alltime records when "TotalToUse" is set to Daily

### ISSUE THREAD

**Issue by Royster-85** [BenCodez/VotingPlugin#1162]
**Versions**
Paper Ver 754
VotingPlugin Ver 6.3.2

**Describe the bug**
In the SpecialRewards.yml under Cumulative, If the setting TotalToUse is set to Daily, It seems to keep picking up the AllTime Records. This doesn't seem right.

**To Reproduce**
If you add the line:  - av User %player% AddTotal AllTime -1 to each Cumulative setting, start with a clean record, The '2' will still run but '3' wont. Even when the daily total in /vote total = 3. Take the line out and clear the records, rerun and it runs '3' with no issue.

**Expected behavior**
Im assuming that if set to Daily, it should check for daily number of votes.

**Screenshots/Configs**

Taken from my config file:

Cumulative:
  # Number of votes required
  # Allows multiple cumulative rewards
  # Number be be around ' (E.g. '1')
  # Can have multiple listed here
  '2':
    Enabled: true
    # Wether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    # Valid options
    # AllTime
    # Monthly
    # Weekly
    # Daily
    TotalToUse: Daily
    Rewards:
      Commands:
      - give %player% minecraft:emerald_ore 2
      - xp add %player% 3 levels
      - adjustbonusclaimblocks %player% 100
  '3':
    Enabled: true
    TotalToUse: Daily
    Rewards:
      Commands:
      - give %player% minecraft:gold_ore 2
      - xp add %player% 3 levels
      - adjustbonusclaimblocks %player% 100

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

That better?

**Comment by Royster-85** [comment]
Yes sir. That does seem to work as intended. You have my thanks for the speedy resolve
