### ISSUE TITLE
Using /av User <IGN> AddMilestoneCount 1 Doesn't trigger Milestone if numbers match

### ISSUE THREAD

**Issue by Royster-85** [BenCodez/VotingPlugin#1165]
**Versions**
VotingPlugin Build 777 (only because you kindly fixed the cumulative issue prior for me.) 
Paper Ver 759

**Describe the bug**
Im being a pain again. But using /av User <IGN> AddMilestoneCount 1 doesn't trigger the configured milestone when the numbers match. Ironically... I was the one that asked for this command too :D ( See #438 )

**To Reproduce**
Just run the command in game with a configured milestone at 1 and players data reset all to 0. Adds 1 in the player data, doesn't trigger milestone.

**Expected behavior**
Should trigger the configured milestone.

**Comment by BenCodez** [comment]
http://bencodez.com/

Should do it I think.

**Comment by Royster-85** [comment]
Yes sir. That is working again. Many Thanks
