### ISSUE TITLE
Have a setting in SpecialRewards.yml that does the same as FirstVote, but for 1st daily vote registered, regardless of which site is voted on.

### ISSUE THREAD

**Issue by Royster-85** [BenCodez/VotingPlugin#1167]
**Is your feature request related to a problem? Please describe.**
Nope, Just an idea I had which may be quick and simple to implement.

**Describe the solution you'd like**
In SpecialRewards.yml There is a setting called FirstVote which runs on your very 1st vote registered. Then as the name suggests, wouldn't run again. 

My idea is the same as that but runs on the 1st daily vote registered, regardless of which site that is configured is voted on. So it runs once daily, when a vote is registered.

**Describe alternatives you've considered**
You could set a cumulative option to 1 but the problem with how this works that it would work on every vote as every number divides (without a remainder) into 1.

**Additional context**
As I say was just an idea I think would be simple to implement but it may give more options to reward players who vote :)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

https://github.com/BenCodez/VotingPlugin/commit/8b9aced63c18c2a63b31252c00b81033262864c5

Untested, but should work.

**Comment by Royster-85** [comment]
Will do some testing. Will take a couple of days to do. Thanks

**Comment by Royster-85** [comment]
So, Initial run: with AddTotals in the config.yml set to true, initial tests show it seems to run as expected. However, If AddTotals is set to false and you have in the VoteSites.yml under the individual configured sites the command /av user %player% AddDaily 1 (so manually adding to the totals) it doesn't trigger.

Something separate with the same test, Cumulative settings don't seem to trigger either if you manually add to the daily totals using commands.

**Comment by BenCodez** [comment]
It only gets checked on vote, not when manually adding a total

**Comment by Royster-85** [comment]
Ahhhh That would be why, I'm guessing the AddTotals config setting is a lot more integrated than I initially thought. Is that something that could be added to check on when manually adding as well or would that potentially cause more issues than solve?

**Comment by BenCodez** [comment]
I think that would cause more problems then you would think. Can I ask why your doing it like that?

**Comment by Royster-85** [comment]
Yeah sure. 

What it is, I have 3 vote sites which I want to give rewards to regardless of which site order they vote on, but I don't want to link the rewards directly to the vote sites. Hence the FirstVoteToday and Cumulative additions. Also I want them to be able to vote on all 3 sites, but only get one added to the milestone counter daily (hence the command additions for Addmilestonecount). 

Because I could use the cumulative for 2 and 3 to remove from the milestone counter, problem is, that when they are two votes from hitting a milestone, the first vote runs fine, the 2nd vote with the AddTotals set to true, triggers the milestone before the manual command can remove it. 

Which is why I was looking at adding it all manually, with AddTotals set to false because I could control what triggers when. 

I guess another thought would be if its possible to have something in the VoteSites.yml under each configured site an option to say "add to milestone count": true/false, but again not sure what complications this may cause.

Either way, the additions that have been made will benefit others. I'm just being picky (thinking outside the box)

Hopefully this makes sense

**Comment by BenCodez** [comment]
For bungee setups the totals are added on bungee, which complicate a lot of things. Not sure if what you want is exactly possible

**Comment by Royster-85** [comment]
I did think as much. I shall keep testing the addition anyway because its still something that be useful to have :) Thanks for replying though

**Comment by Royster-85** [comment]
Sorry this took longer than planned, But tested multiple ways. Including with a clean install and setup. It registers the vote on day 1 but on subsequent days, it doesn't trigger. Am using Build 797.

**Comment by BenCodez** [comment]
Are you using a bungee setup?

**Comment by Royster-85** [comment]
I am not. (probably should of mentioned that)

**Comment by BenCodez** [comment]
I just tested locally and it works for me, not sure how to recreate your issue
