### ISSUE TITLE
ERROR MYSQL

### ISSUE THREAD

**Issue by istarengwa** [BenCodez/VotingPlugin#1168]
**Versions**
plugin : 6.3.2
server : purpurclip-1051

**Describe the bug**
At each player vote, an error message is displayed in the console concerning the mysql database. When i put it in sqlite another error from the same context is displayed. Here is the error for mysql

**Screenshots/Configs**
https://pastebin.com/iKaHVHAb

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

It's because of the - in the server name of the server (never accounted for that). The above build should solve that I think. Or disable the extra check for allsites

**Comment by istarengwa** [comment]
Perfect work =) thank's
