### ISSUE TITLE
Delay Reward Functionality not working as expected

### ISSUE THREAD

**Issue by Jupitour** [BenCodez/VotingPlugin#1169]
#**Versions**
VotingPlugin 6.4 | Purpur 1.16.5 1169

#**Describe the bug**
When using the **delay** feature in the Rewards folder (as a VoteParty reward), it gives all of the rewards under delay to only one player. If there are three players on, the rewards runs three times (three items are given), but all to the same player. 

#**To Reproduce**
1) Turn on VoteParty in SpecialRewards.yml and set up rewards to be 'VoteParty'
2) Set up VoteParty.yml in the Rewards folder as the following:
RewardType: 'ONLINE'
Sound:
  Enabled: true
  Sound: 'ENTITY_ENDER_DRAGON_GROWL'
  Volume: 1.0
  Pitch: 1.0
Rewards:
  Delayed:
    Enabled: true
    Hours: 0
    Minutes: 0
    Seconds: 5
  Commands:
    - cr give to %player% super 1
  Sound:
    Enabled: true
    Sound: 'ENTITY_PLAYER_LEVELUP'
    Volume: 1.0
    Pitch: 1.0```

3) Run **/av ForceVoteParty** and watch all the rewards go to one player.

#**Expected behavior**
The rewards should go to each of the different players and not be given only to one player.

#**Screenshots/Configs**
This is how my **VoteParty.yml** is set up.
RewardType: 'ONLINE'
Sound:
  Enabled: true
  Sound: 'ENTITY_ENDER_DRAGON_GROWL'
  Volume: 1.0
  Pitch: 1.0
Rewards:
  Delayed:
    Enabled: true
    Hours: 0
    Minutes: 0
    Seconds: 5
  Commands:
    - cr give to %player% super 1
  Sound:
    Enabled: true
    Sound: 'ENTITY_PLAYER_LEVELUP'
    Volume: 1.0
    Pitch: 1.0

# This is my **VoteParty** section for **SpecialRewards.yml**:
VoteParty:
  Enabled: true
  VotesRequired: 100
  GiveAllPlayers: true
  ResetEachDay: false
  ResetWeekly: false
  ResetMonthly: false
  OnlyOncePerDay: false
  ResetExtraVotesMonthly: false
  CountFakeVotes: true
  UserVotesRequired: 0
  CountOfflineVotes: true
  Broadcast: '&a&lVote » &eA &dVoteParty&e will begin shortly! Please make space in your inventory!'
  Commands:
  - execute at @a run particle minecraft:heart ~ ~ ~ 0.5 1 0.5 0 10 normal
  - title @a title [{"text":"VoteParty","color":"light_purple","bold":"true"}]
  - title @a subtitle [{"text":"Vote party is beginning shortly!","color":"white","bold":"true"}]
  # Rewards to give per player
  Rewards: 'VoteParty'

#**Additional context**
I am using CrateReloaded to give the keys, but the sounds are also all played only for whoever receives the reward at the time.

**Comment by BenCodez** [comment]
wanna use pastebin.com to send the voteparty part?

**Comment by Jupitour** [comment]
Got it, here you go:

**SpecialRewards.yml VoteParty Config** https://pastebin.com/xiRvgHus

**Rewards Folder VoteParty.yml** https://pastebin.com/ZvQeZFBJ

**Comment by BenCodez** [comment]
From my quick testing it seems to work for me. Try adding a command to broadcast the player names and see if it shows different players?

**Comment by Jupitour** [comment]
That's strange. For some reason it works now. My server restarted between the time when I encountered the glitch and now, might have to do with that. In any case thanks for checking it out!

**Comment by BenCodez** [comment]
The restart might of updated the rewards or something.
