### ISSUE TITLE
Min and Max votes

### ISSUE THREAD

**Issue by renzotom** [BenCodez/VotingPlugin#117]
- [x]  Min votes, when player doesn´t have on end of day 5 votes, he get taxe or something else, we can set what command will be executed
- [ ]  Max votes, player can´t earn next rewards if he reach max votes

**Comment by BenCodez** [comment]
@renzotom 
I'll try and add the min votes feature in the next update. But sadly not the max votes feature, atleast how you described it. I'll just allow it to run a reward file after a certain number of votes in day, even though that is technically possible.

**Comment by renzotom** [comment]
It is done? And it come in new version?

**Comment by BenCodez** [comment]
@renzotom 
Yes I added the minvotes, currently untested but it should work. The max votes are somewhat already possible with cumulative votes.

**Comment by renzotom** [comment]
Ok, thank you.
