### ISSUE TITLE
Cannot set Milestones

### ISSUE THREAD

**Issue by LewisRad** [BenCodez/VotingPlugin#1170]
Hey there!

I cannot set Voting milestones for my players. 

I want to set 50 / 100 / 150 / 200 and award a rank for each milestone. But it is not letting me set anything via the GUI and my rewards config randomly reset recently

Thanks

I hope someone can help :)

**Comment by BenCodez** [comment]
Send what you got?

**Comment by LewisRad** [comment]
Hey Ben,

I have tried editing in the GUI, but it won't let me do anything there when it comes to milestones. My config is below
Milestones:
  '50':
    Enabled: true
    Rewards:
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
  '20':
    Enabled: true
    Rewards:
      Messages:
        Player: '&aYou got %milestone% milestone votes!'

**Comment by BenCodez** [comment]
Wanna pastebin that? does this work? /av User (player) ForceMilestone (Number)

**Comment by LewisRad** [comment]
Ofc! Is there a way to make it for everyone on the server? So the votes linked into it, give them the rank automatically when they hit the milestone? https://pastebin.com/bnaUT2f3

Basically I want
50 / 100 / 150 / 200 
My vote ranks are Explorer (50) / Scavenger (100) / Hunter (150) / Survivor (200) 
I want the reward to lp user %player% parent set (rank)

Thanks for the quick response!

**Comment by BenCodez** [comment]
https://pastebin.com/fGQBfd7e

just follow that format for it. Should give automaticlly
