### ISSUE TITLE
How do I add multiple websites to votingplugin?

### ISSUE THREAD

**Issue by gokusupersayin55** [BenCodez/VotingPlugin#1171]
At first i got one voting website working and connected to the votingplugin, but when i tried to add another one it stopped working. How do i fix this and how do i add multiple websites? Here is the votingsites file thing.

VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  VoteSite: Votesite1
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false 
   Enabled: true

    # Display name of voting site
    Name: 'Top-G'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 1
    
    # If true, voteside will be hidden from some GUI's, similar to being disabled
    Hidden: false
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://topg.org/minecraft-servers/'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://topg.org/minecraft-servers/server-630793'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 12
    
    # Use to have a minute votedelay
    #VoteDelayMin: 30
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    #Offset time for /vote next caculations
    #TimeOffSet: 0
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
         Console:      
              - 'eco give %player% 1000'
              - 'acb %player% 100'
      # Send player a message
      Messages:
        Player: '&bThanks for voting on our server %player% &b'

# VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  VoteSite: Votesite2
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false    
   Enabled: true

    # Display name of voting site
    Name: 'Minecraft Servers Org'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 2
    
    # If true, voteside will be hidden from some GUI's, similar to being disabled
    Hidden: false
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraftservers.org/'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraftservers.org/server/618073'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Use to have a minute votedelay
    #VoteDelayMin: 30
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    #Offset time for /vote next caculations
    #TimeOffSet: 0
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
         Console:      
              - 'eco give %player% 1000'
              - 'acb %player% 100'
      # Send player a message
      Messages:
        Player: '&bThanks for voting on our server %player% &b'

**Comment by gokusupersayin55** [comment]
@BenCodez

**Comment by BenCodez** [comment]
Send the file in a pastebin

**Comment by gokusupersayin55** [comment]
[votesites.txt](https://github.com/BenCodez/VotingPlugin/files/6704605/votesites.txt)
Ill just do notebook since i dont know how i do it in pastebin. If your gonna fix it just reply with a file

**Comment by BenCodez** [comment]
https://pastebin.com/UnhW8TsQ try using that

**Comment by gokusupersayin55** [comment]
The 1st votesite is working now,, but the 2nd one isnt showing

**Comment by BenCodez** [comment]
The second votesite wasn't enabled I guess: https://pastebin.com/y3RZWk6H

**Comment by gokusupersayin55** [comment]
Ah, cheers mate. I'll let you know if I need more help if thats okay😁

**Comment by gokusupersayin55** [comment]
VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  Site1: 
    # Enable examplevoteSite
    # If false, votesite will not be loaded by plugin
    # Default: false 
    Enabled: true
 
    # Display name of voting site
    Name: 'Top-G'
 
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 1
 
    # If true, voteside will be hidden from some GUI's, similar to being disabled
    Hidden: false
 
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://topg.org/minecraft-servers/'
 
    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://topg.org/minecraft-servers/server-630793'
 
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 12
 
    # Use to have a minute votedelay
    #VoteDelayMin: 30
 
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
 
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
 
    #Offset time for /vote next caculations
    #TimeOffSet: 0
 
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
 
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
 
    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'eco give %player% 1000'
      - 'acb %player% 100'
      # Send player a message
      Messages:
        Player: '&bThanks for voting on our server %player% &b'
  Site2:
    Enabled: true
    # Display name of voting site
    Name: 'Minecraft Servers Org'
 
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 2
 
    # If true, voteside will be hidden from some GUI's, similar to being disabled
    Hidden: false
 
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraftservers.org/'
 
    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraftservers.org/server/618073'
 
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
 
    # Use to have a minute votedelay
    #VoteDelayMin: 30
 
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
 
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
 
    #Offset time for /vote next caculations
    #TimeOffSet: 0
 
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
 
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
 
    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:  
      - 'eco give %player% 1000'
      - 'acb %player% 100'
      # Send player a message
      Messages:
        Player: '&bThanks for voting on our server %player% &b'
Site3:
    Enabled: true
    # Display name of voting site
    Name: 'Minecraft-MP'
 
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 3
 
    # If true, voteside will be hidden from some GUI's, similar to being disabled
    Hidden: false
 
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraft-mp.com/'
 
    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraft-mp.com/server-s288676'
 
    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
 
    # Use to have a minute votedelay
    #VoteDelayMin: 30
 
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
 
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
 
    #Offset time for /vote next caculations
    #TimeOffSet: 0
 
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
 
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
 
    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:  
      - 'eco give %player% 1000'
      - 'acb %player% 100'
      # Send player a message
      Messages:
        Player: '&bThanks for voting on our server %player% &b'

**Comment by gokusupersayin55** [comment]
the third one isnt working

**Comment by gokusupersayin55** [comment]
Hey @BenCodez, is there any way i can get your discord?

**Comment by BenCodez** [comment]
Discord is on plugin page
