### ISSUE TITLE
I don't get rewards when I vote.

### ISSUE THREAD

**Issue by gokusupersayin55** [BenCodez/VotingPlugin#1172]
So, I have set up votingplugin the correct way. But when i vote i dont get rewards. I think the system doesnt read the 'Rewards' thing. Here, take a look. The mctools is just for testing

VoteSites:
  Site1:
    Enabled: true
    Name: Top-G
    Priority: 1
    Hidden: false
    ServiceSite: https://topg.org/minecraft-servers/
    VoteURL: https://topg.org/minecraft-servers/server-630793
    VoteDelay: 12
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - eco give %player% 1000
      - acb %player% 100
      Messages:
        Player: &bThanks for voting on our server %player% &b
  Site2:
    Enabled: true
    Name: Minecraft Servers Org
    Priority: 2
    Hidden: false
    ServiceSite: https://minecraftservers.org/
    VoteURL: https://minecraftservers.org/server/618073
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - eco give %player% 1000
      - acb %player% 100
      Messages:
        Player: &bThanks for voting on our server %player% &b
  Site3:
    Enabled: true
    Name: Minecraft MP
    Priority: 3
    Hidden: false
    ServiceSite: https://minecraft-mp.com/
    VoteURL: https://minecraft-mp.com/server-s288676
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - eco give %player% 1000
      - acb %player% 100
      Messages:
        Player: &bThanks for voting on our server %player% &b
  MCTools_org:
    Enabled: true
    ServiceSite: MCTools.org
    VoteURL: VoteURL
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Command:
      - acb %player% 100
      - eco give %player% 1000
      Messages:
        Player: &aThanks for voting on %ServiceSite%!

**Comment by BenCodez** [comment]
What you send is useless with proper formatting. Use pastebin.com or send the file.

**Comment by gokusupersayin55** [comment]
[Uploading votingsites.txt…]()

**Comment by gokusupersayin55** [comment]
Didn't notice that

**Comment by BenCodez** [comment]
Did you sent it?

**Comment by gokusupersayin55** [comment]
https://pastebin.com/EFpr21RE

**Comment by BenCodez** [comment]
https://pastebin.com/xFR7w5iD there you go

**Comment by gokusupersayin55** [comment]
Can you tell me waht you changed incase it happens in the future

**Comment by BenCodez** [comment]
just use a file comparison website to check

**Comment by gokusupersayin55** [comment]
The system doesnt run anything under Rewards:. I changed it but still nothing

**Comment by BenCodez** [comment]
just use what I sent?

**Comment by gokusupersayin55** [comment]
Yes

**Comment by BenCodez** [comment]
Does it work with /av vote (player) (site)?

**Comment by gokusupersayin55** [comment]
Nope, i do get thank you message but not my own.

**Comment by BenCodez** [comment]
Send what message you got?

**Comment by gokusupersayin55** [comment]
[Broadcast] Thanks gokusupersayin for voting on MCTools_org
Thanks for voting on MCTools_org

**Comment by BenCodez** [comment]
that's the message that is set for that votesite....

**Comment by gokusupersayin55** [comment]
Yes, but i have a custom message set and rewards. None of them happens

**Comment by BenCodez** [comment]
change Command: to Commands:

**Comment by gokusupersayin55** [comment]
It already says Commands:

**Comment by BenCodez** [comment]
Not for this one:

    MCTools_org:
      Enabled: true
      ServiceSite: MCTools.org
      VoteURL: VoteURL
      VoteDelay: 24
      DisplayItem:
        Material: GRASS
        Amount: 1
      Rewards:
        Command:
        - acb %player% 100
        - eco give %player% 1000
        Messages:
          Player: '&aThanks for voting on %ServiceSite%!'

**Comment by gokusupersayin55** [comment]
Ah, okay. I havent tested with the ned config on the other votingsites so they might be working

**Comment by gokusupersayin55** [comment]
Cheers mate, it worked.
