### ISSUE TITLE
Project not building.

### ISSUE THREAD

**Issue by andrewkm** [BenCodez/VotingPlugin#1173]
`[ERROR] Failed to execute goal on project VotingPlugin: Could not resolve dependencies for project com.bencodez:VotingPlugin:jar:6.4.1: Failed to collect dependencies at net.md-5:bungeecord-api:jar:LATEST: Failed to read artifact descriptor for net.md-5:bungeecord-api:jar:LATEST: Failed to resolve version for net.md-5:bungeecord-api:jar:LATEST: Could not find metadata net.md-5:bungeecord-api/maven-metadata.xml in jitpack.io (https://jitpack.io)`

Shouldn't use "LATEST".

**Comment by BenCodez** [comment]
According to jitpack the last version (6.4 is built correctly), I forced it for 6.4.1, might be good now?

**Comment by andrewkm** [comment]
Doesn't seem to be working, it's nagging about Bungeecord being set to LATEST I believe.
https://pastebin.com/raw/8ATsw3zk

`[WARNING] 'dependencies.dependency.version' for net.md-5:bungeecord-api:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 284, column 13`

**Comment by BenCodez** [comment]
I don't know where you get that but this is what I just got: https://jitpack.io/com/github/BenCodez/VotingPlugin/6.4.1/build.log

**Comment by andrewkm** [comment]
This is on my jenkins.
Can you please try using the actual correct bungee version instead of "LATEST"?

**Comment by BenCodez** [comment]
I don't think that will make a difference, since it's showing it's pulling bungeecoord-api from jitpack (which doesn't exist) but here you go: https://github.com/BenCodez/VotingPlugin/commit/44ebd17356065b1601d440fc31b418b177a8fa0d

**Comment by andrewkm** [comment]
That fixes both of my jenkins servers. :) Thanks!
https://pastebin.com/raw/3CSHrrkY

Latest is deprecated xD some maven repos work with it, some don't, and sometimes... maven just shits itself lol.
