### ISSUE TITLE
Rank based weekly rewards

### ISSUE THREAD

**Issue by sebastiantho** [BenCodez/VotingPlugin#1174]
**Versions**
Paper 1.17, newest VotingPlugin

**Relevant information**
I want to give my players a special reward for the first daily vote, every day, that is based on their reached milestone. 
So Player 1 who has voted 100 times may get 10 iron for his first vote every day. While Player 2 who has voted 500 times may get 10 diamonds for their first vote every day. 

How can I achieve this?

Thank you in advance.

**Comment by BenCodez** [comment]
Something like this: https://github.com/BenCodez/AdvancedCore/wiki/AdvancedPriority-Examples

**Comment by sebastiantho** [comment]
And I put this under VoteSites.yml? 
Looking something like: 
"
Rewards:
  AdvancedPriority:
    Reward1:
      RequirePermission: true
      Permission: AdvancedCore.Reward.permhere
      Commands:
      - give %player% Iron_Block 1
    Reward2:
      RequirePermission: true
      Permission: AdvancedCore.Reward.permhere2
      Commands:
      - give %player% Gold_Block 1
      Messages:
        Player: Thanks for voting %player%!
"
Also, do I need advancedcore API for this to work?

**Comment by BenCodez** [comment]
send that with code formatting or pastebin, advancedcore is builtin to votingplugin

**Comment by sebastiantho** [comment]
https://pastebin.com/d8Ly2Lju 
Here's the VoteSite.yml snippet. 
Is that correct? Because it doesn't seem to work.

**Comment by BenCodez** [comment]
https://pastebin.com/deBQ01A1 try that

**Comment by sebastiantho** [comment]
Thank you, that did it. Very fast responses too.
