### ISSUE TITLE
Vote Party rewards are being given when a player joins for the first time each day.

### ISSUE THREAD

**Issue by Vehzx** [BenCodez/VotingPlugin#1177]
**Versions**
1.17 & 6.4.1

**Describe the bug**
For some reason when I had voteparty enabled, it would run the command I had set in there whenever a player joined for the first time in a new day.

For example, a player joins the server for the first time on a monday, when that happens, the command set in voteparty rewards is run.

I have 0 clue how this was happening, I just ended up disabling voteparty and it solved my issue.

**To Reproduce**
Put a command for reaching vote party, have vote party enabled.
Get someone to join for the first time in a day, the command runs for some reason.

This happens PER player that joins for the first time in that day, meaning this can be triggered many times if recurring players join each day.

**Expected behavior**
For this to not happen, this never used to happen and I used vote party for an extra reward for players on reaching the vote party goal.

**Screenshots/Configs**
Before I turned off voteparty entirely, this is what would happen in console logs:

https://pastebin.com/5GZnCdcX

My voteparty rewards were set to $15000 in-game currency and a crate key.
As you see in the logs, a player joined for the first time that day and the voteparty rewards were given.

**Additional context**

**Comment by BenCodez** [comment]
What settings did you have for voteparty?

**Comment by Vehzx** [comment]
![image](https://user-images.githubusercontent.com/45553158/124682498-cda38700-dec2-11eb-844f-9ec4347e1331.png)

These settings, under commands I had the 2 commands I would run (giving 15000 in-game currency and crate keys), I removed them since then to fix the issue.

Something to add that might help here, the issue continued initially after I removed the commands, it was only when I realised that in the rewards folder there are the directlydefined rewards, when I checked the voteparty rewards.yml within that folder, I saw the 2 commands were still in there.

After I removed them from both the specialrewards.yml and the directlydefined yml, then my issue was solved and this stopped happening.

**Comment by BenCodez** [comment]
So did every player who voted get a reward on every login? Or all players? 

Vote party is used pretty heavily, so I don't there would be a bug that is that bad without being noticed. 

Are you sure it's vote party reward on login? Any other information that would help?

**Comment by Vehzx** [comment]
I mean, the issue isn't happening anymore since I turned off the rewards for voteparty, so i'm almost certain it must have been voteparty causing it.

When a player joined for the first time in that set day, the reward was given. (trying to explain this sucks lol)
As an example, yesterday, when I joined the server, the voteparty commands ran (giving me $15000 and the command that gives all players a crate key). For the rest of the day, whenever I joined, it didn't happen.

Today, when I joined, it happened again, but for the rest of the day it didn't (and then I disabled it sometime after).

So, it only happens for the first time someone joins for that day.

The crate command I was using for voteparty gave every player a key, which is why all players were receiving a key, otherwise i'm pretty sure it's only giving the reward to that specific player.

This is a mess to try explain, sorry if it's confusing.

If others are not noticing it, then I am not sure how it happened, if you cannot replicate this and others are not reporting the issue then it's not a huge deal, I can live without the voteparty feature being enabled if it means my issue is solved.

If you need anything else let me know and i'll try help the best I can.

**Comment by BenCodez** [comment]
By default rewards are saved for offline players, so any who voted on the
voteparty will have an offline reward saved for vote party (unless you
disabled that). That's my guess right now.

**Comment by Vehzx** [comment]
Your guess here is as good as mine, again, wouldn't worry about it too much if you are not getting other reports about it, I can live without voteparty.

Just thought I would let you know about this incase you found an issue etc.

**Comment by BenCodez** [comment]
Did you want offline voting rewards?

**Comment by Vehzx** [comment]
No I didn't, honestly didn't even realize I had them enabled.

Even if that's the case and they are enabled and this was the problem, my vote rewards have nothing to do with keys, only the vote party did.

So why would my vote party rewards be given to offline players who vote as a vote reward?

**Comment by BenCodez** [comment]
Need to specify you want online only, I added a new option in a recent
update for offline rewards, it's easier than the other, way, just look at
github for the default file for it
