### ISSUE TITLE
Issue on votingplugin

### ISSUE THREAD

**Issue by Ariel01X** [BenCodez/VotingPlugin#1179]
**Versions**
Compiled from the master branch, server version doesnt matter
**Describe the bug**
VotingPlugin shades bungee-chat (net.md_5.bungee.api.chat) in its plugin jar

**To Reproduce**
build the jar
**Expected behavior**
votingplugin doesn't duplicate any classes already packaged in the server

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
![votingplugin](https://user-images.githubusercontent.com/67595051/125141724-7ef22900-e11e-11eb-8488-3ca2d125deaf.PNG)

**Additional context**

**Comment by BenCodez** [comment]
I don't see this as a bug. It's for spigot servers, but it's the same jar for bungee.

**Comment by A248** [comment]
The issue here is really that the same classes are present in the server. Spigot includes net.md_5.bungee.api.chat. Bungee also includes it.

If you have duplicate classes in multiple jars, it can lead to weird and obscure bugs. WE both try to report and fix duplicate classes shaded into plugins, for this reason.

In this case, there are classes which exist both in the server jar and the votingplugin jar.

**Comment by A248** [comment]
Here's an example of what can go wrong when you have duplicate classes present at the same time:

> java.lang.IllegalAccessError: class com.comphenix.protocol.wrappers.PlayerInfoData$1 tried to access protected field com.comphenix.protocol.wrappers.AbstractWrapper.handle (com.comphenix.protocol.wrappers.PlayerInfoData$1 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @24c75083; com.comphenix.protocol.wrappers.AbstractWrapper is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @77254de4)

This happened when a plugin accidentally shaded in ProtocolLib.

**Comment by BenCodez** [comment]
I had a reason for it, I think it was so the plugin wouldn't fail to load on craftbukkit I think, don't remember though. I can see about removing it

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ 

Should be removed now.

**Comment by Ariel01X** [comment]
Thank you
