### ISSUE TITLE
Main page on spigot and github

### ISSUE THREAD

**Issue by renzotom** [BenCodez/VotingPlugin#118]
Hello, you can add this on main page on spigot:
- [ ]  More images with sections
- [ ]  More videos (tutorials) I try make Czech and Slovakia tutorial for you
- [ ] Maybe make instead of bold text images, ex. image FEATURES ? (special text)
- [ ] Maybe when you gain more reviews, put some on your main page
- [ ] Also edit this page https://github.com/Ben12345rocks/VotingPlugin/wiki :D  With more text and images + you can give more images on other pages

**Comment by BenCodez** [comment]
I'll look into doing some of these things :)

**Comment by BenCodez** [comment]
@renzotom 
Gonna close this, since for the most part these are things I will naturally do.

**Comment by renzotom** [comment]
Ok
