### ISSUE TITLE
Custom Enchanted Tools

### ISSUE THREAD

**Issue by veploxmine123** [BenCodez/VotingPlugin#1180]
**Versions**
Plugin version and spigot version

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
How can I add like custom Enchanted tools how do I get there ID? so that I can put it in the voteshop also how to add description?

**Comment by BenCodez** [comment]
You could run a command, not sure about the display item.

Also don't know much about custom enchanted tools.

**Comment by veploxmine123** [comment]
what I mean is that Like fortune 5 books

**Comment by veploxmine123** [comment]
Because I saw a server that has one too I think its the same as your plugin here is the screenshot
![image](https://user-images.githubusercontent.com/85697813/125847038-c3f08a36-af0c-4f80-8dd3-c1c29c40f615.png)

**Comment by BenCodez** [comment]
Just set it to fortune 5?

**Comment by veploxmine123** [comment]
Yeah Like I want to sell Fortune 5 books at the Shop and like Fortune 5 Pickaxe too

**Comment by veploxmine123** [comment]
But I don't know what material: ID to use...

**Comment by veploxmine123** [comment]
Some servers has it and they wont tell me how they did it

**Comment by BenCodez** [comment]
ENCHANTED_BOOK

https://github.com/BenCodez/VotingPlugin/wiki/Item-Configuration

**Comment by veploxmine123** [comment]
Wait can you like give me an example it looks confusing to me because im kinda new about coding and stuff

**Comment by BenCodez** [comment]
Look at the wiki page for it.

**Comment by veploxmine123** [comment]
Wiki page on voteplugin?

**Comment by BenCodez** [comment]
The one I just sent.

**Comment by veploxmine123** [comment]
Wait I think I get it imma try it

**Comment by veploxmine123** [comment]
Oh thank you it helps me alot <3
