### ISSUE TITLE
Voting Site In List Not Recognized

### ISSUE THREAD

**Issue by Andarius68** [BenCodez/VotingPlugin#1181]
Just updated to the new version and now this site which always worked before is not being recognized even though it's in the votesites.yml file. Nothing else has changed. 

[16:47:00 WARN]: [VotingPlugin] No voting site with the service site: 'PlanetMinecraft.com' [16:47:00 WARN]: [VotingPlugin] Current known service sites: PlanetMinecraft.com, MinecraftServers.org, MCSL, Minecraft-MP.com, TopG.org lilist >> = [

**Comment by BenCodez** [comment]
send your votesites.yml

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ this should fix it

**Comment by Andarius68** [comment]
Thank you. Would you still like to see a copy of my votesites.yml file? I'm
just arriving to work but should be able to send it as soon as I can access
the wifi and boot up my laptop.

**Comment by BenCodez** [comment]
Nah, I just releaased an update to fix it (same as build above). It happens if you have a votesite disabled with the service site (like the default votesites.yml has)
