### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by QRGustavo** [BenCodez/VotingPlugin#1182]
[VotifierPlus] Protocol error. Ignoring packet - Socket closed
18.07 19:59:07 [Server] WARN java.net.SocketException: Socket closed
18.07 19:59:07 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:689)
18.07 19:59:07 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:762)
18.07 19:59:07 [Server] WARN at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:681)
18.07 19:59:07 [Server] WARN at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:647)
18.07 19:59:07 [Server] WARN at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:623)
18.07 19:59:07 [Server] WARN at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:580)
18.07 19:59:07 [Server] WARN at java.base/java.net.ServerSocket.accept(ServerSocket.java:538)

VERSION 1.17.1 PAPERMC

**Comment by BenCodez** [comment]
Send startup log?
