### ISSUE TITLE
Error in my Console

### ISSUE THREAD

**Issue by veploxmine123** [BenCodez/VotingPlugin#1184]
**Versions**
Plugin version and spigot version.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/85697813/126829764-aae8b698-2d97-4c5e-a5b0-a7955edcf139.png)
![image](https://user-images.githubusercontent.com/85697813/126829812-e29d1a92-bc52-4ade-b124-68f6f6669c3e.png)

**Additional context**

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by veploxmine123** [comment]
My Votesites works its just that Warning keeps popping up in my console

**Comment by BenCodez** [comment]
It's saying the server hasn't received a vote for that votesite

**Comment by veploxmine123** [comment]
So meaning I have to vote in the site first?

**Comment by BenCodez** [comment]
Yes

**Comment by veploxmine123** [comment]
2 of My players already voted 5 of my sites including the Warning sites that has been said then I still keep getting the message?

**Comment by BenCodez** [comment]
Might have the wrong service site?

**Comment by veploxmine123** [comment]
I copied the sites that says in the Warning and the links works just perfectly fine

**Comment by BenCodez** [comment]
What does /av servicesites show?

**Comment by veploxmine123** [comment]
![image](https://user-images.githubusercontent.com/85697813/126831288-a89bbce8-cf99-4b3d-8174-d1f872e0e673.png)
Oh I see now what should I do?

**Comment by BenCodez** [comment]
Create the votesite for that service site?

**Comment by veploxmine123** [comment]
what does it only shows 4 when I have a total of 5?

**Comment by BenCodez** [comment]
I don't know, can't see what you have

**Comment by veploxmine123** [comment]
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  MinecraftBuzz:
    Enabled: true
    priority: 1
    Name: 'Minecraft Buzz'
    ServiceSite: 'minecraft.buzz'
    VoteURL: 'https://minecraft.buzz/server/1774&tab=vote'
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - 'eco give @p 1000'
      
  TopMinecraftServers:
    Enabled: true
    priority: 2
    Name: 'Top Minecraft Servers'
    ServiceSite: 'topminecraftservers.org'
    VoteURL: 'https://topminecraftservers.org/vote/18501'
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - 'eco give @p 1000'
      
  MinecraftServersBiz:
    Enabled: true
    priority: 3
    Name: 'Minecraft Servers Biz'
    ServiceSite: 'minecraftservers.biz'
    VoteURL: 'https://minecraftservers.biz/servers/150271/#vote_now'
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - 'eco give @p 1000'
      
  MinecraftList:
    Enabled: true
    priority: 4
    Name: 'Minecraft List'
    ServiceSite: 'minecraftlist.org'
    VoteURL: 'https://minecraftlist.org/vote/24085'
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - 'eco give @p 1000'
      
  TopG:
    Enabled: true
    priority: 5
    Name: 'TopG'
    ServiceSite: 'topg.org'
    VoteURL: 'https://topg.org/minecraft-servers/server-612498'
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - 'eco give @p 1000'

**Comment by BenCodez** [comment]
The service site is wrong for minecraftlist.org (copy from /av servicesites)

**Comment by veploxmine123** [comment]
What is the correct one?
![image](https://user-images.githubusercontent.com/85697813/126832210-4663f496-3b96-454d-b6f6-aa532c163acc.png)
![image](https://user-images.githubusercontent.com/85697813/126832243-090bf810-92de-432c-9f29-03b6b5928749.png)

**Comment by BenCodez** [comment]
MinecraftServersList - as /av servicesites shows

**Comment by veploxmine123** [comment]
Alright so the MinecraftServersList works now I have only 1 problem left and its this.
![image](https://user-images.githubusercontent.com/85697813/126832797-8d94deba-2ff6-42a8-87ea-e7fe1332b1ed.png)

**Comment by BenCodez** [comment]
Send your votesites.yml with pastebin.com (make sure to reopen the file from the server)

**Comment by veploxmine123** [comment]
https://pastebin.com/GTKTcB5m

**Comment by BenCodez** [comment]
Might need to restart to update it.

**Comment by veploxmine123** [comment]
Yeah already did when I changed the thing "minecraft servers list"

**Comment by BenCodez** [comment]
You never changed it:     ServiceSite: 'minecraftlist.org'

**Comment by veploxmine123** [comment]
because that is the correct site, that is the site that I used for voting

**Comment by BenCodez** [comment]
Service does not mean the site url (atleast sometimes)

The website can make this whatever they want.

https://github.com/BenCodez/VotingPlugin/wiki/Service-sites

**Comment by veploxmine123** [comment]
![image](https://user-images.githubusercontent.com/85697813/126834247-2dc3f448-5ea6-478d-b0b7-58ecd289f1c1.png)
So anyways I can fix this thing?

**Comment by BenCodez** [comment]
Change the service site to what it says in /av servicesites (this is what service sites the plugin has seen from votifier)

**Comment by veploxmine123** [comment]
XD never mind I fixed it by myself

**Comment by veploxmine123** [comment]
All I did was to match up the Service sites to the ServerData
![image](https://user-images.githubusercontent.com/85697813/126834650-0adbbf4e-ffff-4641-9fdf-0b71cce89199.png)
![image](https://user-images.githubusercontent.com/85697813/126834815-e296c8c8-38cd-46ae-802e-3c609f6e741d.png)

**Comment by BenCodez** [comment]
Did you change that in ServerData.yml? If so that specific votesite won't work.

**Comment by veploxmine123** [comment]
You mean it wont work when I vote?

**Comment by BenCodez** [comment]
Yes, you need to change the service site in votesites.yml, changing in ServerData.yml has not effect expect for the /av servicesites command and console messages, plugin has not way of using that to determine the proper votesite

**Comment by veploxmine123** [comment]
Ohhh I see.x Alright all the sites works perfectly now thank you...
