### ISSUE TITLE
Formatting on hyperlinks

### ISSUE THREAD

**Issue by lolwtfisthis1231** [BenCodez/VotingPlugin#1185]
Hi, I am completely lost trying to format hyplinks. I feel like this is a very simple solution I can't wrap my head around.

# vote url for /vote
# Format for this can be set in Format.yml
# Do not include colors here
# If you need to force a url set the url as this:
# VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'

- But I cannot find a format.yml or a section for this so I'm going bonkers. 
When my code line shows this:
VoteURL: '[Text="testtext",url="url.test"]'  

I get this - [Text="testtext",url="http://testtext"] in game. What do I do? :(

**Comment by BenCodez** [comment]
Disable forcelinks in the config.yml

**Comment by lolwtfisthis1231** [comment]
> Disable forcelinks in the config.yml

I knew it was something minor -.- Thank you very much!
