### ISSUE TITLE
Can't read Rewards File - Apostrophe inside of the two initial apostrophes

### ISSUE THREAD

**Issue by MCHalfAssed** [BenCodez/VotingPlugin#1187]
**Versions**
AV 6.5.2 and Paper 1.17.2 v181

**Describe the bug**
I have a rewards file that isn't working. I believe the cause might be that there are Apostrophe marks inside the Apostrophe beginning and end itself. 
This is the reward file, please check the Command/Console line
https://mcpaste.io/5b983090ee914905
Error in console says "Cannot load plugins/VotingPlugin/Rewards/1ETH.yml" 

This command works normally via Command block, I have confirmed it. 

`
<html>
<body>

Commands:
--
6 | Console:
7 | - 'minecraft:give %player% amethyst_shard{display:{Name:'[{"text":"Ethereum","italic":true,"color":"light_purple"}]',Lore:['[{"text":"Also known as \\"ETH\\",","color":"aqua"}]','[{"text":"Ethereum is the currency","italic":true,"color":"aqua"}]','[{"text":"used in the Midgard Markets.","italic":true,"color":"aqua"}]','[{"text":"Can be used to trade for","italic":true,"color":"aqua"}]','[{"text":"valuable items.","italic":true,"color":"aqua"}]']},Enchantments:[{id:mending,lvl:1}],HideFlags:1} 1'

</body>
</html>`

**Expected behavior**
The reward file should load normally with a working command

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

Here is the text file included
[1ETH.zip](https://github.com/BenCodez/VotingPlugin/files/6995009/1ETH.zip)

**Comment by BenCodez** [comment]
You need to escape all the quotes, why not use? https://github.com/BenCodez/VotingPlugin/wiki/Item-Configuration

**Comment by MCHalfAssed** [comment]
> You need to escape all the quotes, why not use? https://github.com/BenCodez/VotingPlugin/wiki/Item-Configuration

Thanks for the quick reply! Also, what does it mean to escape all quotes? (Could you show me an example?)

Also, it's because I use this website to create my custom items (https://www.gamergeeks.net/apps/minecraft/give-command-generator), it helps a lot.

**Comment by BenCodez** [comment]
I think a backslash on every quote or something, personally don't like escaping that many quotes.

**Comment by MCHalfAssed** [comment]
Alright, I'm going to try that now. So it should look something like this I believe:
`minecraft:give %player% amethyst_shard{display:{Name:\'[{"text":"Ethereum","italic":true,"color":"light_purple"}]\',Lore:[\'[{"text":"Also known as \"ETH\",","color":"aqua"}]\',\'[{"text":"Ethereum is the currency","italic":true,"color":"aqua"}]\',\'[{"text":"used in the Midgard Markets.","italic":true,"color":"aqua"}]\',\'[{"text":"Can be used to trade for","italic":true,"color":"aqua"}]\',\'[{"text":"valuable items.","italic":true,"color":"aqua"}]\']},Enchantments:[{id:mending,lvl:1}],HideFlags:1} 1`

**Comment by BenCodez** [comment]
Need to do it for double quotes as well I think

**Comment by MCHalfAssed** [comment]
Thank you, will try that now;
`minecraft:give %player% amethyst_shard{display:{Name:\'[{\"text\":\"Ethereum\",\"italic\":true,\"color\":\"light_purple\"}]\',Lore:[\'[{\"text\":\"Also known as \"ETH\",\",\"color\":\"aqua\"}]\',\'[{\"text\":\"Ethereum is the currency\",\"italic\":true,\"color\":\"aqua\"}]\',\'[{\"text\":\"used in the Midgard Markets.\",\"italic\":true,\"color\":\"aqua\"}]\',\'[{\"text\":\"Can be used to trade for\",\"italic\":true,\"color\":\"aqua\"}]\',\'[{\"text\":\"valuable items.\",\"italic\":true,\"color\":\"aqua\"}]\']},Enchantments:[{id:mending,lvl:1}],HideFlags:1} 1`

**Comment by MCHalfAssed** [comment]
That (above) sadly did not work either. For reference, I have a different Rewards file with a different (but similar) command, and that one works without issue. The command is:
` Console:
  - 'minecraft:give %player% minecraft:potion{CustomPotionEffects:[{Id:22,Amplifier:3,Duration:6000}],CustomPotionColor:16181504,display:{Name:"[{\"text\":\"Golden Potion IV\",\"italic\":false,\"color\":\"yellow\"}]",Lore:["[{\"text\":\"Rewarded for voting.\",\"italic\":false}]","[{\"text\":\"Grants 8 Absorption Hearts.\",\"italic\":false,\"color\":\"yellow\"}]"]}}'
  `
  
  Hopefully this helps with troubleshooting

**Comment by BenCodez** [comment]
I personally hate escaping characters on yml, not very good at that part, so there isn't much I can do. You could just use the builtin item handling

**Comment by MCHalfAssed** [comment]
Thanks for all your help so far. I have tried to create the item using your built in item creator, and for some strange reason I still can not load the YML. Text file below:

https://mcpaste.io/acd5d845c6ea7138

I think my formatting may be off, would you be able to help?

**Comment by BenCodez** [comment]
https://pastebin.com/Tf8XbLEu try that

**Comment by MCHalfAssed** [comment]
That worked, thank you so much! What changes did you make?

ALSO - While I have you, how can I add this item to the Vote shop?

**Comment by BenCodez** [comment]
You missed a '

VoteShop works similar to the item rewards

**Comment by MCHalfAssed** [comment]
You're very helpful. Thanks again for the help, enjoy your day!
