### ISSUE TITLE
The command removepoints does not longer work

### ISSUE THREAD

**Issue by banicola** [BenCodez/VotingPlugin#1188]
**Versions**
6.6.1

**Describe the bug**
When I do /adminvote User <user> RemovePoints <points>, it does not decrease the points count.

**To Reproduce**
Use the command removepoints

**Expected behavior**
It should decrease the points count

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/25954399/129902585-adf48af4-bf2e-42cb-8f8d-fa06ad7b0b7e.png)

**Additional context**
It seems like after some time, maybe after a vote from someone else, it finally removed the points but it still allows players to use those points endlessly during that time

**Comment by banicola** [comment]
After looking more into it, when adding points there is also an issue at least in the message given which doesn't contain the correct amount of points after the addition
![image](https://user-images.githubusercontent.com/25954399/129904251-64baf603-6da2-44b2-939d-283fa215a8a5.png)

**Comment by BenCodez** [comment]
Try latest dev build at bencodez.com, might already fix it

**Comment by banicola** [comment]
Hey, I updated to the latest version and this issue came back. It does not change the placeholder value when I add or remove points to a player which means they can use their point multiple time to buy stuff...
