### ISSUE TITLE
VoteStreak not incrementing and AllSites not working for offline votes

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#1190]
**Versions**
```
Paper 1.17.1 build 200
VotingPlugin 6.6.2
```

**Describe the bug**
- Voting doesn't seem to add to the votestreak for both offline and online players.
- Voting offline on all sites doesn't trigger the "AllSites" rewards file when the player joins however voting while online does.

**Expected behavior**
Voting offline and online on all sites triggers allsites rewards file when player is online and voting increases the votestreak.

If you need more info please let me know here or in discord ticket.

**Comment by BenCodez** [comment]
Using anything bungee? Like votingplugin setup wise?

I also answered on discord.
