### ISSUE TITLE
Server crashing issue

### ISSUE THREAD

**Issue by overkidding** [BenCodez/VotingPlugin#1191]
**Versions**
5.13.6 - 1.8.8-R0.1-SNAPSHOT

**Describe the bug**
When i open the votetop and click back to votegui the server completely crashes

**To Reproduce**
/votegui wait until it opens (you need a good amount of votes)
click the paper item and the server will crash instantly

**Expected behavior**
Open back the menu without lagging -.-

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/46853321/132564479-abba40ed-c1af-4872-8062-2faee83e2566.png)
![photo_2021-09-08_20-26-39](https://user-images.githubusercontent.com/46853321/132564604-ade2466b-2610-4f7d-8705-a5a304a12714.jpg)
![photo_2021-09-08_20-21-43](https://user-images.githubusercontent.com/46853321/132564659-91286385-cb83-497b-b114-b472d8402ee6.jpg)

**Comment by BenCodez** [comment]
1. The crash log is useless as a screenshot
2. Can't really do much for an older version
