### ISSUE TITLE
Opt out from voting reward or broadcast

### ISSUE THREAD

**Issue by Johnibur** [BenCodez/VotingPlugin#1195]
Is there a way to make someone opt out from the voting reward? They vote with their name and get the glory, but they have chosen not to receive any reward for it. 

As an alternative, silently vote for selected users (would be useful for hidden staff)?

**Comment by BenCodez** [comment]
You can require a permission, which you could give to everyone by default and remove for specific players, probably the easiest way right now

**Comment by Johnibur** [comment]
Didn't actually know you can check for permission as a reward condition. So thanks!
