### ISSUE TITLE
Some next ideas

### ISSUE THREAD

**Issue by renzotom** [BenCodez/VotingPlugin#121]
- [ ] Players can pick they own reward
- [ ] Players can vote only, when..... (ex. have less than 10 food, have less than 10 health, have less than 100 money).... you know what I mean? Requirements for vote
- [ ] If player has some special item he earn bigger reward (special item requirement)
- [ ] When player has booster, he earn bigger reward (add boosters :D )
- [ ] Commands with holograms, when admin use /av leaderboard monthly or something else it spawn there hologram with best monthly voters, it is good to some locations, where are information about voting
- [ ] If player has ban, he doesn´t earn reward, if he will get unban
- [ ] Some smileys to messages and GUI
- [ ]  Some iccons to messages and GUI

**Comment by BenCodez** [comment]
@renzotom 
Closing this, add most of the stuff to: https://github.com/Ben12345rocks/AdvancedCore/issues/14
Not sure about a few of those things above though.

**Comment by renzotom** [comment]
Ok
