### ISSUE TITLE
Vote Party ideas

### ISSUE THREAD

**Issue by renzotom** [BenCodez/VotingPlugin#125]
- [ ] When vote party starts, it will remain untill set time and
- [ ] Players earn more rewards, we can set what (when vote party starts)
- [ ] Execute command, when vote party start
- [ ] Execute command, when vote party ends
- [ ] Command to start party
- [ ] Command to end party
- [ ] Schedule for vote party, in real time (ex. party starts in 1pm and ends in 10pm)
- [ ] Shcedule for vote party in Minecraft time (Minecraft time- ex. party starts in 1pm and ends in 10pm)
- [ ] When certain number of first votes is reached, vote party starts (per-first votes support)
- [ ] When certain number of cumulative votes is reached, vote party starts (per-cumulative votes support)
- [ ] Per-world support
- [ ] Per-permission support (if player is VIP, he earn better reward)
- [ ] Per-group support (when player is VIP, he need less or more votes to start vote party)
- [ ] Cumulative vote party per hour (when are two, three, four vote parties in hour, they earn bigger or smaller reward)
- [ ] Cumulative vote party per day  (when are two, three, four... vote parties in day, they earn bigger or smaller reward)
- [ ] Cumulative vote party per week  (when are two, three, four... vote parties in week, they earn bigger or smaller reward)
- [ ] Cumulative vote party per month  (when are two, three, four... vote parties in month, they earn bigger or smaller reward)
- [ ] Per-locations support
- [ ] Vote party in special locations (support residence, regions...)
- [ ] Temportally vote party in special locations, ex. when vote party starts, it starts only in spawn (residence/region) and vote party will be there 
- [ ] Temportally rewards in special locations, ex. when vote party starts, players will earn special rewards only in spawn (residence/region) and vote party will be there 
- [ ] Temportally rewards in special locations, ex. when vote party starts, players will earn rewards only in spawn (it disable normal vote in other locations) (residence/region) and vote party will be there

**Comment by BenCodez** [comment]
@renzotom 
That's a lot of things to do, so I'll see what I can do :)

**Comment by renzotom** [comment]
Thank you for read and do, what can do. I also write to your other two plugins ideas.
PS: You can do it in other updates, not all in this. And try do too many things please :(

**Comment by BenCodez** [comment]
@renzotom Just gonna close this, as I feel some of this is unnescary/already possible. But may add some stuff when I get around to it.

**Comment by renzotom** [comment]
Ok
