### ISSUE TITLE
Console error when you try to view voting rewards

### ISSUE THREAD

**Issue by ColeSkory** [BenCodez/VotingPlugin#126]
Whenever someone tried to view voting rewards I get this error:\

24.08 11:05:27 [Multicraft] Skipped 395 lines due to rate limit (30/s)
24.08 11:05:26 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
24.08 11:05:26 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10)
24.08 11:05:26 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33)
24.08 11:05:26 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1853)
24.08 11:05:26 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
24.08 11:05:26 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
24.08 11:05:26 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
24.08 11:05:26 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
24.08 11:05:26 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
24.08 11:05:26 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
24.08 11:05:26 [Server] WARN at sun.reflect.GeneratedMethodAccessor677.invoke(Unknown Source)
24.08 11:05:26 [Server] WARN at com.Ben12345rocks.AdvancedCore.Util.Inventory.BInventory.onInventoryClick(BInventory.java:172)
24.08 11:05:26 [Server] WARN at com.Ben12345rocks.VotingPlugin.Commands.Commands$1.onClick(Commands.java:277)
24.08 11:05:26 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243)
24.08 11:05:26 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
24.08 11:05:26 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
24.08 11:05:26 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
24.08 11:05:26 [Server] WARN at me.BukkitCodes.BVG.VoteGUI.onCommand(VoteGUI.java:236)
24.08 11:05:26 [Server] WARN at me.confuser.barapi.BarAPI.setMessage(BarAPI.java:131)
24.08 11:05:26 [Server] WARN at me.confuser.barapi.BarAPI.getDragon(BarAPI.java:340)
24.08 11:05:26 [Server] WARN at me.confuser.barapi.BarAPI.addDragon(BarAPI.java:351)
24.08 11:05:26 [Server] WARN at me.confuser.barapi.nms.v1_6.getSpawnPacket(v1_6.java:31)
24.08 11:05:26 [Server] WARN at me.confuser.barapi.Util.getCraftClass(Util.java:108)
24.08 11:05:26 [Server] WARN at java.lang.Class.forName(Class.java:264)
24.08 11:05:26 [Server] WARN at java.lang.Class.forName0(Native Method)
24.08 11:05:26 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
24.08 11:05:26 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
24.08 11:05:26 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
24.08 11:05:26 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
24.08 11:05:26 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.Packet24MobSpawn

**Comment by BenCodez** [comment]
Looks like you have another plugin interfering.

**Comment by BenCodez** [comment]
Do you have a plugin called VoteGUI installed?

Edit: Also the voting rewards have to be configured in GUI.yml

**Comment by ColeSkory** [comment]
Yes! That seemed to fix it! Thank you.

I am now running into a problem where it displays messages twice and doesn't update the timer for when you can vote next.

**Comment by BenCodez** [comment]
@ColeSkory 
Wanna send me your server ip?

**Comment by ColeSkory** [comment]
Yes :D It is SkoryCraft.com The voting is acting weird in the Factions server.

**Comment by BenCodez** [comment]
I will check it out later when I get a chance

**Comment by ColeSkory** [comment]
I'm getting another error when I try to do /vote gui :/ 

25.08 12:25:07 [Server] INFO ... 15 more
25.08 12:25:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.Executers.CommandVote.onCommand(CommandVote.java:214) ~[?:?]
25.08 12:25:07 [Server] INFO at com.Ben12345rocks.AdvancedCore.Objects.CommandHandler.runCommand(CommandHandler.java:316) ~[?:?]
25.08 12:25:07 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$48.execute(CommandLoader.java:757) ~[?:?]
25.08 12:25:07 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.Executers.CommandVote.voteGUI(CommandVote.java:474) ~[?:?]
25.08 12:25:07 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.Commands.openVoteGUI(Commands.java:238) ~[?:?]
25.08 12:25:07 [Server] INFO at com.Ben12345rocks.AdvancedCore.Utils.setSkullOwner(Utils.java:798) ~[?:?]
25.08 12:25:07 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_10_R1.inventory.CraftMetaItem cannot be cast to org.bukkit.inventory.meta.SkullMeta
25.08 12:25:07 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
25.08 12:25:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot110.jar:git-Spigot-c55900f-9af379f]
25.08 12:25:07 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'v' in plugin VotingPlugin v4.3
25.08 12:25:07 [Server] ERROR null
25.08 12:25:07 [Server] INFO TheHipsterPony issued server command: /v gui

**Comment by BenCodez** [comment]
I'll check it out when I'm on my PC later

**Comment by BenCodez** [comment]
Could you type /av report and send me the zip file that is created in the
reports folder of the plugin

**Comment by BenCodez** [comment]
@ColeSkory 
After coming on your server I think the GUI issue is due to a error in the GUI.yml. Do what I said above. Also, are there any errors on startup?

**Comment by ColeSkory** [comment]
Here is the ZIP you asked for.
There are no errors in my startup. I'll attach my GUI.yml file for you too: http://hastebin.com/icikidexok.vbs
[Report2016.8.26.8.44.19.zip](https://github.com/Ben12345rocks/VotingPlugin/files/439263/Report2016.8.26.8.44.19.zip)

**Comment by BenCodez** [comment]
@ColeSkory 
Get rid of using the skull in the URL icon. Looks like that is a bug on my end. So for now just remove it and it should work. I'll work on fixing it later.

Edit: Found problem, read below.

**Comment by BenCodez** [comment]
@ColeSkory 
Just found the problem. Your setting a skull on a bow.
Use this: http://pastebin.com/WjMRvKMx

**Comment by ColeSkory** [comment]
Perfect! That fixes that issue. Now the only issue I see is the double message thing;https://gyazo.com/da20b61a5a16dcb689417a52eaefea29

**Comment by BenCodez** [comment]
@ColeSkory 
It appears that this could be a bug on my end when the option BroadcastWhenOnline is true. I'll look at fixing. You could just set that to false to fix it.

Edit: Fixed in latest update. Let me know if it works properly now.
