### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by Potothingi** [BenCodez/VotingPlugin#1274]
I hope someday this plugin will support Folia.
Folia isn't a stable release yet, so don't rush.

Currently, 'ProtocolLib, Vault, LuckPerms, PlaceholderAPI, EssentialsX, ViaVersion, ViaBackwards, CoreProtect, DiscordSRV, Chunky, Spark' plugins already support Folia, or Folia support is ready in pull requests.

https://docs.papermc.io/folia
https://github.com/PaperMC/Folia#plugin-compatibility

**Comment by Potothingi** [comment]
You can refer to the commits that other plugins have added to support Folia.

https://github.com/NuVotifier/NuVotifier/commit/65007e248efc160b2f8d276546e030afb010f301

https://github.com/ViaVersion/ViaVersion/commit/7c9c602cec1c73f818379b79e1c116c32a278580
https://github.com/ViaVersion/ViaVersion/commit/c46bb5bcf5e88a415dc045271fe1a174c3a623f4

https://github.com/ViaVersion/ViaBackwards/commit/4293289468a6840001ece99fb4285ba5215f9bbc

https://github.com/pop4959/Chunky/commit/2a3f089861c65e5448983b6ef98dcb3a93b7fa4f
https://github.com/pop4959/Chunky/commit/38e99a87038c20ce8459228cd6c18634d35085a5
https://github.com/pop4959/Chunky/commit/3666d58e886bef17700aef66fef06ee43d49fb3b

https://github.com/dmulloy2/ProtocolLib/commit/65a9ef5acf00b978bd605090790a638384769c1c

https://github.com/MilkBowl/Vault/pull/915/files

https://github.com/LuckPerms/LuckPerms/pull/3615/files

https://github.com/lucko/spark/pull/312/files

https://github.com/PlaceholderAPI/PlaceholderAPI/commit/95786e32d2d5a877220705648c8139486549c781

https://github.com/EssentialsX/Essentials/pull/5291/files

https://github.com/PlayPro/CoreProtect/commit/7170e2945269f6aa7f6a8468cad8e2ae473357eb
https://github.com/PlayPro/CoreProtect/commit/ace870b93016b900f4726fcf2bfe4e71fc98accf
https://github.com/PlayPro/CoreProtect/commit/f2934fd876f4d5ec93e0488d7494b25ca41c9aff

https://github.com/DiscordSRV/DiscordSRV/commit/812c9b025bff260eb19e4ae4bb8c8cec61bb6829

https://github.com/e-im/FreedomChat/commit/dffbd3dc8e3381d0c6e5571ed00e1cdd28dd30de

**Comment by BenCodez** [comment]
I already have this as a work in progress, in theory it should work

https://bencodez.com/job/VotingPlugin-Folia/
