### ISSUE TITLE
Would like a way to show user money made during vote

### ISSUE THREAD

**Issue by foosratt** [BenCodez/VotingPlugin#134]
Not sure if this belonged here or in AdvancedCore but we would REALLY like a way for us to display how much money a user received after voting.  We have the reward set to give a min amount of $500 and max amount of $1000.  We would like to display what the user actually got after voting.

**Comment by BenCodez** [comment]
That is being added in 1.6, I actually already implemented it, might add it
in a small update instead this weekend.

**Comment by BenCodez** [comment]
1.6 as in advancedcore.

**Comment by foosratt** [comment]
You can wait. If the code is checked in I can pull it, build (if given instruction on how you build it you don't seem to be using maven or ant), test it, and put it up on my server for now.  Can you do a small blurb here how it would work in the config file though?  Also move this ticket to Advanced Core if you would like.  I can track it there just as easily.

**Comment by BenCodez** [comment]
It's in branch 1.6, untested. Just put %money% and it should replace it for
the correct amount.

**Comment by foosratt** [comment]
Sounds good.  I'll pull it tonight and play with it. Again though I don't see and pom files or ant files.  How is it you normally build?

**Comment by BenCodez** [comment]
I just use eclipse to do it and export.

**Comment by foosratt** [comment]
OK I have it in eclipse already.  Thanks.

**Comment by foosratt** [comment]
So I pulled the source durning lunch for a quick test.  Built with eclipse and overrode the jar file in my plugin directory. I then did a /av Vote <username> <vote site>.  Here is the section in the reward.ml file (in the case a reward I called diamond.yml) 

Messages:
  Broadcast: '&cThanks for Voting!  You received %money%''

Here is the screen shot from Admin
![2016-10-06_13 12 02](https://cloud.githubusercontent.com/assets/22380669/19162803/62011178-8bc7-11e6-89bc-2207520ceb85.png)
And the screen shot from the user
![2016-10-06_13 12 07](https://cloud.githubusercontent.com/assets/22380669/19162819/6e917086-8bc7-11e6-82b7-ed0f60960fe8.png)

If can get time tonight I'll pick through your recent changes to see why this doesn't look like it works.

**Comment by BenCodez** [comment]
@foosratt Pushed a commit, let me know if that fixes it.

**Comment by foosratt** [comment]
This is much better.  the %money% tag works.  I tried to add the %items% tag to the code as well where we would print the items amount and the item name in a comma separated list.  The HashMap for items though seemed to be empty.  I am attaching a patch of my changes as I couldn't commit a separate branch with these changes I made.  Take a look as it would be useful to have in addition to the money.
[0001-Tried-to-add-items-and-item-amount-to-broadcast-mess.zip](https://github.com/Ben12345rocks/VotingPlugin/files/515024/0001-Tried-to-add-items-and-item-amount-to-broadcast-mess.zip)

**Comment by BenCodez** [comment]
@foosratt Added that, let me know how it works.

Also, you should be able to commit (I might need to add you as a contributor, but I thought it). I use a github add-on in eclipse, maybe you can get it to work there.

**Comment by foosratt** [comment]
I will try to commit again. Although Just to be clear what I added didn't work as the HashMap seemed to be empty.  I simply got a 0 at the itemName string after going through the keySet.  Also I am using tortoise git to do the commit thing and it came up with my logging into Git  with my GIT user name.  I simply assumed I had to have some sort of permissions to commit a new branch (I didn't want to commit to 1.6)  I will bring in the latest 1.6 changes though probably tomorrow during lunch and test it (gotta do SOME coding for my company :) )

**Comment by BenCodez** [comment]
@foosratt Was hard to see from the patch why it was empty, I have a set that stores all the items. Find out if you can commit, I'm actually kinda wondering since no one has done it before.

**Comment by foosratt** [comment]
Let me try and commit my branch.

**Comment by foosratt** [comment]
git.exe push --progress "origin" Foosratt-Items-Change:Foosratt-Items-Change

remote: Permission to Ben12345rocks/AdvancedCore.git denied to foosratt.
fatal: unable to access 'https://github.com/Ben12345rocks/AdvancedCore.git/': The requested URL returned error: 403

git did not exit cleanly (exit code 128) (1248 ms @ 10/6/2016 9:07:33 PM)

I have a TS server we are on now (just me and the other co-owner of our server) if you would like to work through this  foodleball.com

**Comment by BenCodez** [comment]
@foosratt Added you as a collabrator, you have to accept this: https://github.com/Ben12345rocks/AdvancedCore/invitations

**Comment by foosratt** [comment]
Got it and that worked. MY branch (with the not working code :) ) is there now.

**Comment by BenCodez** [comment]
@foosratt 
Awesome. If you want to make your own changes feel free to. Just don't put it in the main branch. I would recommend forking and creating pull requests. Which I don't think you need to be a collabrator for.

Edit: Deleted your branch, since I already add that.

**Comment by foosratt** [comment]
cool I have my foosratt branch. I won't be doing much but you can always merge stuff in if I get stuff working.

**Comment by BenCodez** [comment]
@foosratt Do you wanna try forking and creating a pull request? If you do I'll remove you as a colabrator and see if you can make a pull request. Its much more cleaner than having a seperate branch.

**Comment by foosratt** [comment]
Take me off for now if you are concerned.  I will try the fork thing tomorrow.  Have a few more other things I have to work on and then try and get some sleep :)

**Comment by BenCodez** [comment]
@foosratt I'm not that concerned over it, I have local versions of the branch which I can use to override any changes. I removed you off the collaborators as you sent the message, pretty sure you can do the forking though.

**Comment by foosratt** [comment]
Great I'll try i later.  Again Thanks for all the help and I'll test the new changes and let you know.

**Comment by foosratt** [comment]
This issues is closed as the fixes in the repository has been tested by me and they work.  I will file a separate issue in AdvancedCore for the Items and the amounts given broadcast
