### ISSUE TITLE
It made an exception while executing task 14891 

### ISSUE THREAD

**Issue by Latamier** [BenCodez/VotingPlugin#136]
When I voted for my server at minestatus, this is what I saw in the console. It also gave me the rewards that you put in and not the one I put in. 

11.10 14:51:45 [Server] INFO ... 3 more
11.10 14:51:45 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
11.10 14:51:45 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
11.10 14:51:45 [Server] INFO at com.Ben12345rocks.VotingPlugin.Events.PlayerJoinEvent$1$1.run(PlayerJoinEvent.java:67)
11.10 14:51:45 [Server] INFO at com.Ben12345rocks.VotingPlugin.Objects.User.offVote(User.java:679)
11.10 14:51:45 [Server] INFO at com.Ben12345rocks.VotingPlugin.Objects.User.playerVote(User.java:799)
11.10 14:51:45 [Server] INFO at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.giveSiteReward(VoteSite.java:222)
11.10 14:51:45 [Server] INFO at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.giveRewards(VoteSite.java:205)
11.10 14:51:45 [Server] INFO Caused by: java.lang.NullPointerException
11.10 14:51:45 [Server] INFO at java.lang.Thread.run(Unknown Source)
11.10 14:51:45 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
11.10 14:51:45 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
11.10 14:51:45 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
11.10 14:51:45 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin VotingPlugin v4.4 generated an exception while executing task 14891
11.10 14:51:45 [Server] WARN Exception in thread "Craft Scheduler Thread - 103"

**Comment by BenCodez** [comment]
You must of made a mistake when listing the rewards.

**Comment by BenCodez** [comment]
@Latamier Are you still having this problem?
