### ISSUE TITLE
Milestones question

### ISSUE THREAD

**Issue by IceCraftNation** [BenCodez/VotingPlugin#145]
I was just wondering the milestones are set up for a one time reward or is it monthly.  We looking for a monthly reward for all players/staff who reach those certain milestones each month.  Is there any way the milestones can do that?

**Comment by BenCodez** [comment]
Milestones are one time only, don't think there is a way of doing that but
will look into a way. You can do this with Javascript feature I suppose.

**Comment by IceCraftNation** [comment]
Thank you for getting back to me so quickly.  I truly appreciate it :)

**Comment by BenCodez** [comment]
Added in latest version.
