### ISSUE TITLE
Votes not registered?

### ISSUE THREAD

**Issue by blazex224** [BenCodez/VotingPlugin#149]
Hey, I may be doing something wrong, but I am trying to set up a system where users can be promoted after a certain amount of votes. I am using the milestone rewards to do so, and it is not promoting any of my players once they receive the proper amount of votes. When I test it by fake-voting, it seems to work for me, so I am thinking that there is a possibility the real votes are not being registered.

A possible conflicting plugin I can think of is Enjin (which has it's own votes) but I don't see why or how it could cause any issues.

VotingPlugin rewards file: http://pastebin.com/Ct2n5x7P

VotingPlugin config: http://pastebin.com/RtA3E1Mz

VotingPlugin vote sites: http://pastebin.com/rHiYSf3F

AdvancedCore config: http://pastebin.com/LiLDXNR2

I have many rewards files for rank ups (in AdvancedCore), but here's the first one: http://pastebin.com/ui7cTEz7

AdvancedCore server data: http://pastebin.com/XJpaDUAU

Thanks for any help!

**Comment by BenCodez** [comment]
From a quick glance it looks okay to me, but I notice a few sites may be properly inconfigured. Does every voting site work? As in /vote total adds after a vote? Are you using the latest version? Turn debug on in AdvancedCore and it will print out some debug info for you (like if milestone was given or if it attempted to), send the log of that. Type /av report next time and it will create a zip file in AdvancedCore/Report with all the config files for you, so you don't have to do multiple pastebin's. If need be I can come on your server when I have a chance. Any errors in console?

**Comment by blazex224** [comment]
The only votesites that I want to be used are the 3 that are enabled, Minecraft-MP, MSL, and PlanetMinecraft. After a player votes on those 3, a message is broadcasted thanking them for their vote, so that part is working properly.

I made sure both plugins were updated, and I enabled debugging, so for now I assume I'll have to wait until the next person ranks up (the first rank up is at 9 votes, with a possible maximum 3 votes per day). I suppose making a test rank could work as well, that would trigger upon one vote or so.

**Comment by BenCodez** [comment]
The votes broadcast if if the site isn't setup properly.
Your votesites.yml should be like this:
http://pastebin.com/Q1bdQyng
Don't think even one was properly setup (in order for milestones to count the vote), so that may be the cause of the problem.

**Comment by blazex224** [comment]
That's most likely the reason then, a silly mistake on my end so thanks a ton for taking the time to help me out! Appreciate it :P

**Comment by BenCodez** [comment]
Yeah, no problem. I also posted an update like an hour ago. Let me know if it works.

**Comment by blazex224** [comment]
Alright thanks, I'll check it out, and I'll check back with you if this works or not so I'll be waiting until the next person ranks up

**Comment by BenCodez** [comment]
@blazex224 Does it work now?

**Comment by blazex224** [comment]
@Ben12345rocks Sorry I've been a bit busy and still am atm. It seems to work fine, however just one of the sites seems to not be registering the reward. I unfortunately am not able to send the files right now, but I will be able to send them a little later. Thanks!

**Comment by BenCodez** [comment]
Probably the service site is incorrect.
