### ISSUE TITLE
/vote dosent work at all and throws massive errors in console

### ISSUE THREAD

**Issue by Zaliphyr** [BenCodez/VotingPlugin#156]
http://pastebin.com/fNshLjWS

This is the Log from my server and all the plugins included, /v dosent work but /av works

Config:
http://pastebin.com/UbEDfFEd

VotingSites:
http://pastebin.com/R8ur867E

Im using version 5.1.3

**Comment by BenCodez** [comment]
Did you /reload your server? If so don't do that, it generally breaks most plugins.

**Comment by Zaliphyr** [comment]
i have reloaded the server frequently bc of installing and modifying other plugins yes, i could do a restart and see if that works

**Comment by Zaliphyr** [comment]
restarting didnt fix it

**Comment by BenCodez** [comment]
Send the full log

**Comment by Zaliphyr** [comment]
http://pastebin.com/ZtdahzTV

did a new restart, /v or /vote dosent work but /av gui does

**Comment by BenCodez** [comment]
I'll give you a beta version of the next update in a bit

**Comment by BenCodez** [comment]
You can take a look at the beta version here:
https://github.com/Ben12345rocks/VotingPlugin/wiki/Future-versions

It should help with your issue.
Note: It is a beta version with a lot of changes, so it is possible some bugs may occour, but it should be fine.
