### ISSUE TITLE
Up Coming Version Plans

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#158]
- [x] [AdvancedCore/#45](https://github.com/Ben12345rocks/AdvancedCore/issues/45) (New Reward System)
- [x]  Custom site display names
- [x] Remove GAL Converter

**Comment by renzotom** [comment]
Why remove GAL Converter?

And when you think, that version will be done?

And when there will be new reward system, it is good to set up plugin right now, or will be better wait?

**Comment by BenCodez** [comment]
No one else really uses the converter, plus its a lot of work to maintain.

Hoping to release it tomorrow.

The old system still would work, so it's up to you.

On Jan 30, 2017 9:26 AM, "renzotom" <notifications@github.com> wrote:

Why remove GAL Converter?

And when you think, that version will be done?

And when there will be new reward system, it is good to set up plugin right
now, or will be better wait?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/158#issuecomment-276075219>,
or mute the thread
