### ISSUE TITLE
Server stall

### ISSUE THREAD

**Issue by Eufranio** [BenCodez/VotingPlugin#159]
[Pagina.zip](https://github.com/Ben12345rocks/VotingPlugin/files/683875/Pagina.zip)

**Comment by BenCodez** [comment]
You gave me no information

**Comment by Eufranio** [comment]
Thought it was sufficient. I'm running VotingPlugin 5.2.2 (downloaded today from Spigot) in Thermos 1.7.10 build 58

**Comment by BenCodez** [comment]
I'm not able to see if you made any edits but I don't see any log of the
stall.

**Comment by Eufranio** [comment]
This is a WarmRoast report pointing for what stalled the server.

**Comment by BenCodez** [comment]
I'll look at in the morning when I get on my PC.

**Comment by Eufranio** [comment]
Wrong report, rip, I'll wait for another stall and send the right one

**Comment by BenCodez** [comment]
Just send the log of console when it stalls. The report zip doesn't tell me much of what I need to know.
