### ISSUE TITLE
BTW support for NuVotifier °_ °

### ISSUE THREAD

**Issue by renzotom** [BenCodez/VotingPlugin#162]
Hello, can you add support for NuVotifier? Our vote list in Czech and Slovakia republic stop support Votifier and start support NuVotifier.... I am too sad, but they said me, they don´t change it.... Please add support for that plugin, all peoples in these 2 states need it.

https://www.spigotmc.org/resources/nuvotifier.13449/

Or support already working / exist? If yea, add it to main page :D

**Comment by BenCodez** [comment]
I already support it.

**Comment by renzotom** [comment]
Nice! :D
