### ISSUE TITLE
Plugin interfering

### ISSUE THREAD

**Issue by markovic-petar** [BenCodez/VotingPlugin#163]
Hi, I recently istalled the Voting Plugin and I must say I'm really impressed with the plugin and its features. Everything works fine except that the /v command interferes with Voxel Sniper (a building plugin) so practically now i can't use voxel sniper with this plugin installed. Is there a way to just use the /vote command for this plugin or the shortcut /v can't be disabled? I am sorry if i have overseen something in the config but for now i can't find a way to fix this. Thank you in advance!

**Comment by BenCodez** [comment]
Use command aliases
