### ISSUE TITLE
Chance doesnt work correctly

### ISSUE THREAD

**Issue by stiderspace** [BenCodez/VotingPlugin#166]
I have been looking at how you work with you chance on randoms chance for rewards. 

What I noticed was that you get the nextdouble of the chance and add 1,
so it for instance if chance is 20 the random generator gets a number between 21 and 0
after that you check if the change is les of equal to chance so 20, wich means its not a 20% change to get it but a 95 % change. even when i put the chance to 1 its stil a 50% change becaus you will get a number between 0 and 2 and you check if the chance is lower than 1 so its a 50% chance to get the reward not 1%

i recomend
``` java
	public boolean checkRandomChance() {
		double chance = getRandomChance();

		if ((chance == 0) || (chance == 100)) {
			return true;
		}

		double randomNum = ThreadLocalRandom.current().nextDouble(100); //not chance + 1 

		plugin.debug("Random: Random: " + randomNum + ", Chance: " + chance);

		if (randomNum <= chance) {
			return true;
		} else {
			return false;
		}
	}

```

**Comment by BenCodez** [comment]
1 should equal 1%, I'll double check it after school.

**Comment by stiderspace** [comment]
okay awsome.

but after the doing abit of my own math with on the way you are checking the chance,
1 came out on 50% wich also explained the fact i got a reward that i had set to 1% way to many times.

**Comment by stiderspace** [comment]
https://gyazo.com/11d6249f62473d773fd21fc536cdf5e2

watch my hot bar i sould not be getting that many netherstart acording to the file i uploaded to my server (you can see the one im using in the back ground)

**Comment by BenCodez** [comment]
Turn debug on and it will show extra info about the chances.

**Comment by stiderspace** [comment]
https://gyazo.com/7cee5716c65c68c0b1805713d851780a
i have put the console on the background an random doesnt ever get higher than 2

I would have changed it myself but I have never worked with maven and just can't figure out how to set up the projects

**Comment by BenCodez** [comment]
I'll change it the next time i have a chance. Sunday by latest.

**Comment by stiderspace** [comment]
ah okay awsome.
 i like really the mod so far the fact that i can fully customize my rewards is awsome. great job. 
the bug is abit of a set back but still great job.

**Comment by BenCodez** [comment]
I think you mean plugin, and thanks. i upgraded so you could do decimals guess never noticed my error.

**Comment by stiderspace** [comment]
yeah plugin sorry bit used to modded minecraft XD

and things like that happen alot your sure not the first one

**Comment by BenCodez** [comment]
Here is a version that should fix it:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by stiderspace** [comment]
awsome  thanks.
ill try it out and keep an eye out for other bugs, also your fast.

**Comment by BenCodez** [comment]
Finished my homework earlier than I thought, also fixed a few other bugs as
well. Probably will release it tomorrow morning, trying to not spam updates
:)

**Comment by stiderspace** [comment]
cool it seems to work great now awsome thanks for the quick work.
