### ISSUE TITLE
Suggestion: placeholders for PlaceholderAPI for top voters.

### ISSUE THREAD

**Issue by Eufranio** [BenCodez/VotingPlugin#167]
If you want more info, just tell me, that would be nice to have.

**Comment by BenCodez** [comment]
Will add in the next update

**Comment by BenCodez** [comment]
Placeholders:
%VotingPlugin_Total_All%
%VotingPlugin_Total_Month%
%VotingPlugin_Total_Week%
%VotingPlugin_Total_Daily%

%VotingPlugin_top_all_#%
%VotingPlugin_top_month_#%
%VotingPlugin_top_week_#%
%VotingPlugin_top_daily_#%

%VotingPlugin_top_all_position%
%VotingPlugin_top_month_position%
%VotingPlugin_top_week_position%
%VotingPlugin_top_daily_position%

**Comment by Eufranio** [comment]
How would `%VotingPlugin_votetop_all_#%` work?

**Comment by BenCodez** [comment]
%VotingPlugin_votetop_all_1% - Returns number 1 in all time top

**Comment by Eufranio** [comment]
It's returning the same user:

![1](http://image.prntscr.com/image/56864538ff9a405282e8c3ddf9bafa17.png)

/papi parse %VotingPlugin_votetop_all_1%
/papi parse %VotingPlugin_votetop_all_2%
/papi parse %VotingPlugin_votetop_all_3%

**Comment by BenCodez** [comment]
What about now?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by BenCodez** [comment]
Have you tested if this works properly now?

**Comment by Eufranio** [comment]
![image](https://cloud.githubusercontent.com/assets/17598280/23591236/fc877abe-01cb-11e7-997f-268dd47eeb3b.png)

It will output a blank string now.

**Comment by BenCodez** [comment]
I changed it to top instead of votetop

**Comment by Eufranio** [comment]
Blank string.

![image](https://cloud.githubusercontent.com/assets/17598280/23591269/5442734e-01cc-11e7-9cae-8950bb2b9ad1.png)

**Comment by BenCodez** [comment]
What does '/vote top 1 all' show? I tested it myself a while ago and it worked

**Comment by Eufranio** [comment]
![image](https://cloud.githubusercontent.com/assets/17598280/23591287/99d3dcae-01cc-11e7-931e-47509ac69a90.png)

**Comment by BenCodez** [comment]
There is no top voter for all time, hence no one for the placeholder

**Comment by Eufranio** [comment]
Looks like it's having issues connecting with the database, and there we go back to https://github.com/Ben12345rocks/VotingPlugin/issues/169

**Comment by BenCodez** [comment]
Use this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0
I managed to figure out what that error is and found I could just silence it.
