### ISSUE TITLE
Bug with signs/heads

### ISSUE THREAD

**Issue by Eufranio** [BenCodez/VotingPlugin#168]
Steps to reproduce:

1. Place a head and a sign near it, and create a VotingPlugin's sign. In my case, I used this:

![1](http://image.prntscr.com/image/abf48ae279b94d37917b59ff8ef7b48e.png)

2. Break the sign and create another one, but with a different rank. I used the 2 rank.

![2](http://image.prntscr.com/image/07125ecd703b4f839a81df42d710ecab.png)

3. Break and create new signs as you want. The issue is when we right click the sign: all previous data will still be shown:

![3](http://image.prntscr.com/image/7bd0ecbbb1374a7b9643dd90ceb8868c.png)

The heads will also update a lot of times when placed in this loop, I hope it can be fixed. I'm using:
Thermos-1614-B58
VotingPlugin-5.5.1

**Comment by BenCodez** [comment]
Break sign, restart server, place sign?

**Comment by Eufranio** [comment]
Yeaah, that fixes, but is it supposed to happen?

**Comment by BenCodez** [comment]
No, will double check that

**Comment by Eufranio** [comment]
Fixed!
