### ISSUE TITLE
Vote sites are created wrongly in config

### ISSUE THREAD

**Issue by Eufranio** [BenCodez/VotingPlugin#170]
When the create servers on vote config is enabled and the plugin creates a vote site to VoteSites.yml, it's generated wrong, I believe becasuse of the dot. See:

![1](http://image.prntscr.com/image/c95c33bd4a47451fbe36a603feea3232.png)

**Comment by BenCodez** [comment]
Gonna double check that tomorrow

**Comment by Eufranio** [comment]
Fixed!
