### ISSUE TITLE
Shop Console Error

### ISSUE THREAD

**Issue by tylerking** [BenCodez/VotingPlugin#178]
Hey there. Just started using VotingPlugin today and loving it so far. I did run into a console error when using the /vote shop command. I'm running on Paper Spigot 1.11.2

http://pastebin.com/m9HHUpJL

Thoughts?

**Comment by BenCodez** [comment]
Your missing a section for some item.

**Comment by tylerking** [comment]
Hmm..ok. I checked out the shop section and nothing seemed off to me. Do you mind having a look at the config and tell me what I'm missing or even direct me to a section in the tutorial that explains what I'm missing?

http://pastebin.com/EjUBisRK

**Comment by BenCodez** [comment]
You messed up how you defined the rewards for the item. Only on my phone so
can't do much right now

**Comment by tylerking** [comment]
Ok. Well I went ahead and tried a fresh install and tried the /v shop command right from the get go and the issue still persists so I am pretty sure this isn't something I did.

**Comment by BenCodez** [comment]
Are you running the latest version? I'll look into it more tonight

**Comment by tylerking** [comment]
Yep. I am indeed. Thanks for looking into it.

**Comment by BenCodez** [comment]
Looks like its due to this:
    Shop:
      # GUI name
      Name: 'VoteShop'

Just remove that, gonna have to fix that in a bit

**Comment by tylerking** [comment]
Everything works with the latest update. Thanks so much.
