### ISSUE TITLE
/v used by voxelsniper 

### ISSUE THREAD

**Issue by anmghstnet** [BenCodez/VotingPlugin#187]
Is /v only used by this plugin as a shorter version of /vgui? /v is used by voxelsniper to select the type of block you want to paint with and I want to use both your plugin and voxelsniper. 

I am thinking it only requires removing the following line from the plugin code to resolve this:
```
for (CommandHandler handle : plugin.voteCommand) {
			msg.add(handle.getHelpLineCommand("/v") + " : " + handle.getPerm());
		}
```

**Comment by anmghstnet** [comment]
or rather /vote, not /vgui.

**Comment by BenCodez** [comment]
Don't think it would be that easy, but I might try.

You can always use a command alias

**Comment by BenCodez** [comment]
Just did some testing and this is not possible. You will just have to use a command alias.

**Comment by anmghstnet** [comment]
Yeah, I was messing around with the source as well, that command is definitely embedded. Thanks for trying at least.
