### ISSUE TITLE
TriggerPlayerVoteEvent does nothing

### ISSUE THREAD

**Issue by Dyllaann** [BenCodez/VotingPlugin#189]
I try to use /av TriggerPlayerVoteEvent <myname> Vote1
Nothing happens. No error in console, no message ingame, no 'fake' vote happens, just nothing.
Am I doing something wrong?

This is my config:
https://pastebin.com/UtdPN5q3

**Comment by BenCodez** [comment]
Use /av vote (palyer) (site)
That command does other things.
