### ISSUE TITLE
VoteShop cant buy

### ISSUE THREAD

**Issue by SaitDev** [BenCodez/VotingPlugin#191]
When i buy an item  from vote shop. Got a console error but no item, vote point still be consumed
https://pastebin.com/7pxP3ct3

The Shop config section:
```
Shop:
  Xang:
    Material: 'FIREBALL'
    Data: 0
    Amount: 1
    Name: '&2Xăng'
    Lore:
    - '&cGiá: 10 điểm vote'
    Cost: 10
    Rewards:
      Items:
        Material: 'FIREBALL'
        Amount: 1
        Name: '&2Xăng'
        Lore:
        - '&bNhien lieu dung de bay '
        - '&7Cam tren tay /fly on de bay, '
        - '&7/fly off de tat'
    Slot: 0
```

**Comment by BenCodez** [comment]
It's VoteShop: not shop:

**Comment by SaitDev** [comment]
by default the config section is `Shop`
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L493

Should i change to VoteShop?

**Comment by BenCodez** [comment]
Does the default work? I don't remember of the top of my head right now

**Comment by SaitDev** [comment]
I tried the default config, but I couldnt buy that default diamond too. Change Shop to VoteShop cant open vote shop anymore.

**Comment by BenCodez** [comment]
You have points?

**Comment by SaitDev** [comment]
Yes, have enough. I used /av addpoints .

**Comment by Ben12345rocks** [comment]
Server ip? I'll hop on and help

**Comment by SaitDev** [comment]
IP: vnminer.sytes.net
Thank you

**Comment by BenCodez** [comment]
This fix it:

    Items:
      fireball:
          Material: 'FIREBALL'
          Amount: 1
          Name: '&2Xăng'
          Lore:
          - '&bNhien lieu dung de bay '
          - '&7Cam tren tay /fly on de bay, '
          - '&7/fly off de tat'

Just realized you messed this up.

**Comment by SaitDev** [comment]
sorry, the spaces on ur config are broken. I tried like this:
```
Items:
  fireball:
    Material: 'FIREBALL'
    Amount: 1
    Name: '&2Xăng'
    Lore:
    - '&bNhien lieu dung de bay '
    - '&7Cam tren tay /fly on de bay, '
    - '&7/fly off de tat'
```

Update: Sorry. it worked. Thank for your great help
