### ISSUE TITLE
Some voting links are not working

### ISSUE THREAD

**Issue by jordanwilliams1** [BenCodez/VotingPlugin#199]
Hello, Some vote links are not working for some reason 😢 

Here is my config:
https://hastebin.com/dakizedewu.scala

Here are the links that don't work:
- serverpact
- planetminecraft
- topg
- minecraftservers.org

**Comment by BenCodez** [comment]
Did you manage to solve the problem?

**Comment by jordanwilliams1** [comment]
@Ben12345rocks I'm not sure, I Think it's my VoteDistribute plugin causing the problems. I'll let you know in 9 hours.

**Comment by jordanwilliams1** [comment]
@Ben12345rocks  Problem is resolved, It seems the services are case sensitive or the voting website just were broke.


SERVERPACT.COM
PlanetMinecraft.com
TopG.org
MinecraftServers.org
