### ISSUE TITLE
Allow rewards to be used when player is offline

### ISSUE THREAD

**Issue by kikelkik** [BenCodez/VotingPlugin#200]
Hey! I'm using VotingPlugin v.5.8.5 on PaperSpigot. Everything works very well, but:
Players do not get their reward if they aren't online despite of setting RewardType to BOTH or just leaving the setting out (BOTH is default). 
Just for testing: Even if I set this to OFFLINE, the reward doesn't appears until the player joins the server.

```
# Reward type
# Possible Values: ONLINE,OFFLINE,BOTH
# Default: BOTH
# Make this reward file only give rewards depending 
# if player was online/offline when the reward attempted to give
RewardType: 'BOTH'
```

Looking forward for help :)

**Comment by BenCodez** [comment]
Turn debug on and send the log of voting

**Comment by kikelkik** [comment]
https://pastebin.com/Hde1QCYu

I attached both rewards.yml of msl and mcseu. You see, on msl I did explicitly define 'both'. 

Result when I join on the server later: http://prntscr.com/fjiy5d

**Comment by BenCodez** [comment]
It seems like it worked, you should get the rewards when you log on. Don't
think this is an issue with Reward type, or I would be getting lots of bug
reports

**Comment by kikelkik** [comment]
I want to recieve the reward _instantly_ even if I am not logged on. I don't want to get the rewards for the last 16 votes in one rush when I voted 8 days on both sites but haven't been online for 8 days. This whould a manipulate the vote statistic valid only for a specific time and b massively spam the chat in this case.

So, did I make a mistake in setting it up or misunderstood the function of 'RewardType'? Is there any possibility to manage it?

**Comment by BenCodez** [comment]
That is how this is designed. Just don't have a broadcast on the rewards, use the default one in Config.yml The vote stats do update if the reward isn't sent however.

**Comment by kikelkik** [comment]
Okay I didn't recognize that the stats update for sure. 
Could you although explain me what the RewardType function is intended to do?

**Comment by BenCodez** [comment]
Reward type allows you to give a different reward based on if user was
online or not when voting

**Comment by kikelkik** [comment]
Okay thanks and sorry for misunderstanding!

**Comment by TheoRetisch1** [comment]
I am also interested in a message type feature, could you add it? It would be awesome if the plugin only send a message if the player is online when voting. I want a different vote message for every single vote site but I dont want 20 messages spamming the chat if a player who voted every day joined the server after several days. Even better would be the possibility to reward and send the message instantly even if the player isnt online.

**Comment by BenCodez** [comment]
You can set a broadcast to go off, which works if the player is offline (if enabled, is by default).
As for rewards giving offline (and a message) that's not really possible, specificly for items and such

**Comment by BenCodez** [comment]
I'll consider adding this as a possible feature. (forcing rewards to be given offline)

**Comment by BenCodez** [comment]
Decided that I would add this, certain cases when this is needed.
