### ISSUE TITLE
Problems with /vgui and /avgui

### ISSUE THREAD

**Issue by jordan-thirkle** [BenCodez/VotingPlugin#201]
Hello, 

I am informing you of an issue with the latest version of your plugin.
When i perform the command /vgui or /avgui, It does not open the GUI and i get an error/warn message in the console.

**/vgui error**
`15.06 17:53:00 [Server] WARN [VotingPlugin] Plugin VotingPlugin v5.8.6 generated an exception while executing task 744
15.06 17:53:00 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 0
15.06 17:53:00 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteGUI(PlayerGUIs.java:133) ~[?:?]
15.06 17:53:00 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$45.execute(CommandLoader.java:862) ~[?:?]
15.06 17:53:00 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.CommandHandler$1.run(CommandHandler.java:417) ~[?:?]
15.06 17:53:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
15.06 17:53:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
15.06 17:53:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
15.06 17:53:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
15.06 17:53:00 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

**/av gui error**
`15.06 17:53:00 [Server] WARN [VotingPlugin] Plugin VotingPlugin v5.8.6 generated an exception while executing task 744
15.06 17:53:00 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 0
15.06 17:53:00 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteGUI(PlayerGUIs.java:133) ~[?:?]
15.06 17:53:00 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$45.execute(CommandLoader.java:862) ~[?:?]
15.06 17:53:00 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.CommandHandler$1.run(CommandHandler.java:417) ~[?:?]
15.06 17:53:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
15.06 17:53:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
15.06 17:53:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
15.06 17:53:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
15.06 17:53:00 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

Thanks.

**Comment by BenCodez** [comment]
Both those are errors for /vgui, just remove the help button in the config, guess I broke the handle for that.

**Comment by BenCodez** [comment]
this should fix it if your still having problems:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0
