### ISSUE TITLE
Problems with world whitelisting

### ISSUE THREAD

**Issue by roopekoo** [BenCodez/VotingPlugin#202]
In the rewards, I have whitelisted worlds where the voting prizes should be given. Rewards are given incorrect worlds but when I'm not on whitelisted world and vote, I get the notification that I voted but not prizes, (that is still fine), but when I join to the whitelisted world where I should be given the prizes, nothing comes up.

I suggest you add queue option for "offline" voters. By offline voters, I mean players who aren't on the server or are not in the whitelisted world, not even message shows up when the player is in a wrong world.

**Comment by BenCodez** [comment]
Relog in the world. There is a option to check on world change.

**Comment by BenCodez** [comment]
Is this problem solved?

**Comment by roopekoo** [comment]
The problem is solved. Eventually player gets rewards when relogging back to the world. But that is really annoying because I want to get the "lost" rewards immediately when joining from blacklisted world back to whitelisted world.

**Comment by BenCodez** [comment]
Turn check on world change to true
