### ISSUE TITLE
Voting not connected to VotingPlugin

### ISSUE THREAD

**Issue by jonjonnnho** [BenCodez/VotingPlugin#209]
Hi. I finished configuring the VotingPlugin configs and rewards. The av vote test works successfully and all the sites say NuVotifier is connected but when the player does /vote, clicks on the link and then votes, the rewards aren't going through. Would you be able to help me with this? You can message me on Discord or skype if you like.

**Comment by BenCodez** [comment]
Check your service sites, and if the server gets the vote
