### ISSUE TITLE
Points displayed in GUI

### ISSUE THREAD

**Issue by AndrewB6** [BenCodez/VotingPlugin#210]
Is there any way to add an item to the /vote GUI that shows people the amount of points they have (/vote points)? Also, I would like to be able to remove some of the items (Last & Recent).

**Comment by BenCodez** [comment]
Can't remember if placeholders work, but you can just add/remove a section
to add/remove an item

**Comment by BenCodez** [comment]
Just doubled checked. You can use javascript in the GUI (any gui in fact), so you should have access to any placeholder.

Will look at making it easier though.

**Comment by AndrewB6** [comment]
How would I do this with javascript?

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/wiki/Javascript-API

**Comment by BenCodez** [comment]
Latest version allows for use of placeholder placeholders, which has points, so you can use that if you want.
