### ISSUE TITLE
Error in console?

### ISSUE THREAD

**Issue by PureLove-X** [BenCodez/VotingPlugin#213]
03.07 00:26:44 [Server] WARN Exception in thread "Timer-6" 
03.07 00:26:44 [Server] WARN org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
03.07 00:26:44 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403)
03.07 00:26:44 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144)
03.07 00:26:44 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:118)
03.07 00:26:44 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:101)
03.07 00:26:44 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.update(AdvancedCoreHook.java:710)
03.07 00:26:44 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$4.run(AdvancedCoreHook.java:407)
03.07 00:26:44 [Server] WARN at java.util.TimerThread.mainLoop(Timer.java:555)
03.07 00:26:44 [Server] WARN at java.util.TimerThread.run(Timer.java:505)

**Comment by BenCodez** [comment]
Does the issue occour after a restart?

**Comment by SkyVox** [comment]
Yeah

**Comment by BenCodez** [comment]
Are you disable/reloading the plugin at all or any plugin for that matter?

"Plugin attempted to register task while disabled"
Something happen there most likely

**Comment by BenCodez** [comment]
This fix it?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0
