### ISSUE TITLE
Players can duplicate items.

### ISSUE THREAD

**Issue by SkyVox** [BenCodez/VotingPlugin#214]
The player can duplicate items on "/vote" menu, he just press, Shift and the item come to his inventory, and them close and stay with this item.

**Comment by BenCodez** [comment]
Works fine for everyone. Check for plugin conflicts.

Can you reproduce on a fresh server with only my plugin?

**Comment by SkyVox** [comment]
I'll try do this, And this git is up to date with this new version on Spigot?

**Comment by BenCodez** [comment]
Yes.
