### ISSUE TITLE
How do i change the text of /vote?

### ISSUE THREAD

**Issue by flleeppyy** [BenCodez/VotingPlugin#216]
i dont want the gui. I want the text. I want it to be this:
  - '&a====================================================='
  - '&a            Voting Links
  - '&ahttp://minecraft-server-list.com/server/401736/vote/'
  - '&ahttp://minecraftservers.org/server/447778'
  - '&agoo.gl/2koau9'
  - '&ahttp://minecraft-mp.com/server/166201/vote/'
  - '&agoo.gl/vDRoH5'
  - '&a====================================================='
im tired on gui crap.
Please help me

**Comment by BenCodez** [comment]
Change this: https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L90

Change this:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L132

Add text here:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L127 (as a  list)
