### ISSUE TITLE
Some things that seems to be weird (tbc)

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#217]
Hey, @Ben12345rocks,

awesome plugin, seems to be a very good replacement for GAL. 
Please let this issue open for some days, atm I'm configuring VotingPlugin and I'll post some things here that I don't get yet.

- Why it's minecraft-server_eu in broadcast and in config?

![unbenannt2](https://user-images.githubusercontent.com/13700636/27987072-91fa83cc-6408-11e7-9b5b-76ab31555662.PNG)
![unbenannt3](https://user-images.githubusercontent.com/13700636/27987188-b92be91c-6409-11e7-8241-ba5b60c32f0e.PNG)

- Why it's always "days" here? And does _"2 weeks in a row"_ mean that you have to vote at 2 days in 2 consecutive weeks, let's say today and next Saturday?

![unbenannt](https://user-images.githubusercontent.com/13700636/27987101-fcc5d954-6408-11e7-84ca-feddcb7c1806.PNG)

Thank you so far! 👍

**Comment by Platinteufel** [comment]
At this voting site you can vote only once per day, but if you vote at 11 pm you can vote again at 0 am. How can I set up this in order to the "VoteDelay" feature? Otherwise I need to disable it.

VoteDelay: 24 does not fit in this case

**Comment by Platinteufel** [comment]
I'd love to show my players their total vote count when they type /vote, but it seems that it is not possible this way?

![unbenannt4](https://user-images.githubusercontent.com/13700636/27988002-0f127b30-6418-11e7-8a12-88c6dee66b27.PNG)

**Comment by Platinteufel** [comment]
What the .. is this behaviour? I'm also missing the "back" button?
https://youtu.be/WF5gs61W_B0

**Comment by BenCodez** [comment]
You need to vote at least once a week. 

You have to disable VoteDelay in that case. 

Use placeholderapi placeholders. 

I believe that's normal, it updates the numbers.

**Comment by Platinteufel** [comment]
Thanks!

Is it possible to implement an option like "every day"?

Hm, I don't want to install PlaceholderAPI just for that. But whatever.

It's a very weird behaviour, because of mouse jumping, inventory flickering and no chance to go back to main menu. For instance, this is a gui like I would imagine it:
https://youtu.be/1jI4LznPl-A

and what about this minecraft-server_eu?

**Comment by BenCodez** [comment]
You could use Javascript, but that's more advanced, I'll look at adding those placeholders. 

I'll look at those gui changes. 

You can set the site name for each site

**Comment by Platinteufel** [comment]
Okay, thanks! :) Any chance for this "next vote at 0 am" option?

**Comment by BenCodez** [comment]
I'll look at it.

**Comment by BenCodez** [comment]
Posted an update on spigot, take a look.
