### ISSUE TITLE
Own website template for top voters

### ISSUE THREAD

**Issue by renzotom** [BenCodez/VotingPlugin#218]
Hello, what about own website template for top voters? Like use bans plugins for banlist. I mean, you create a template for website, when players can see, how many they have votes. PS: Maybe for players, who have special statistics don´t use it, but some yes.

**Comment by BenCodez** [comment]
https://www.spigotmc.org/resources/votetop-provotes-addon.36368/

That what you want?

**Comment by renzotom** [comment]
Yeah

**Comment by BenCodez** [comment]
Well there you go :)

**Comment by renzotom** [comment]
OH thanks :D

**Comment by renzotom** [comment]
But...
DEPENCIES:
ProVotes (required) [MySQL setup]

??? I don´t need it, when I use VotingPlugin, no?

**Comment by BenCodez** [comment]
Read the description, there is a way to use votingplugin for it.
