### ISSUE TITLE
IllegalPluginAccessException:

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#220]
https://pastebin.com/gFMdyT4S

I'm not running AdvancedCore

**Comment by BenCodez** [comment]
Are you using the latest version?

**Comment by Platinteufel** [comment]
Yes. I was confused because the config didn't update automatically (I had to add the new daily-option manually). Don't know if this is intended.

**Comment by BenCodez** [comment]
There is no auto config update

**Comment by BenCodez** [comment]
This fix it?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Yes, seems to be fixed. 👍
