### ISSUE TITLE
Warning in console:  Error occured while obtaining item

### ISSUE THREAD

**Issue by SiuanSong** [BenCodez/VotingPlugin#225]
Getting this error in my console from time to time
[Error](https://pastebin.com/xfdmQKJy)
[Config.yml](https://pastebin.com/K7yP9gd0)

**Comment by BenCodez** [comment]
Your missing some sections of your config somewhere

**Comment by SiuanSong** [comment]
Would you mind taking a look because even after inputting all the info into a brand new config, I am still getting the error.
[Config.yml](https://pastebin.com/mnk6G9x7)

**Comment by BenCodez** [comment]
No idea right now.
