### ISSUE TITLE
Error when using commands

### ISSUE THREAD

**Issue by SamKemp** [BenCodez/VotingPlugin#228]
When I use a command such as /vote I get the following error in the console:

`19.07 18:53:31 [Server] INFO [VotingPlugin] VotingPlugin is up to date! Version: 5.9.3
19.07 18:53:32 [Server] WARN [VotingPlugin] Plugin VotingPlugin v5.9.3 generated an exception while executing task 29915
19.07 18:53:32 [Server] INFO java.lang.LinkageError: loader constraint violation: when resolving method "com.Ben12345rocks.VotingPlugin.UserManager.UserManager.getVotingPluginUser(Lorg/bukkit/entity/Player;)Lcom/Ben12345rocks/VotingPlugin/Objects/User;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/Ben12345rocks/VotingPlugin/Commands/GUI/PlayerGUIs, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/Ben12345rocks/VotingPlugin/UserManager/UserManager, have different Class objects for the type com/Ben12345rocks/VotingPlugin/Objects/User used in the signature
19.07 18:53:32 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteURL(PlayerGUIs.java:444) ~[?:?]
19.07 18:53:32 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$65.execute(CommandLoader.java:1180) ~[?:?]
19.07 18:53:32 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.CommandHandler$1.run(CommandHandler.java:447) ~[?:?]
19.07 18:53:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
19.07 18:53:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
19.07 18:53:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
19.07 18:53:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
19.07 18:53:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

**Comment by BenCodez** [comment]
Not sure how you caused that. Can you send more info?

**Comment by SamKemp** [comment]
I was having issues with the plugin when using MySQL due to failing to connect to the database and while debugging I switched to flatfine and tried SQLLite then realised I wasn't running the latest version so I removed the plugin and configs and switched to the latest version with a fresh config with no settings changed and tried running `/vote` which is when I saw the error posted in the console.

**Comment by BenCodez** [comment]
Redownload the latest version? No idea how you did that.

**Comment by SamKemp** [comment]
Thanks for the help. I'm not sure what happened but just installing the latest version seems to have worked.
also you might want to fix the typo when adding a new vote site to the config automatically:
`20.07 11:55:13 [Server] INFO [VotingPlugin] Recieved a vote from 'CraftServers.net' by player 'untamemadman'!
20.07 11:55:13 [Server] WARN [VotingPlugin] VoteSite CraftServers_net **doe** not exist, creating one, set AutoCreateVoteSites to false to prevent this
20.07 11:55:13 [Server] WARN [VotingPlugin] VoteSite CraftServers.net **doe** not exist, generaterating one... 
20.07 11:55:13 [Server] WARN [VotingPlugin] VoteSite CraftServers_net **doe** not exist, creating one, set AutoCreateVoteSites to false to prevent this`

Thanks
untamemadman

**Comment by BenCodez** [comment]
It syncs when needed
