### ISSUE TITLE
Delayed rewards not working when offline

### ISSUE THREAD

**Issue by AndrewB6** [BenCodez/VotingPlugin#233]
I'm trying to set up a double mcmmo xp reward for one hour as a vote party. The initial reward (giving the user the permission node) works fine and the expiry works if they are still offline. However, if they are not online when the hour is up, nothing happens. They keep the permission node and no commands run. Is there a way to set it up so that either the reward runs anyway or it waits for the person to come online and then immediately runs the command?

Steps to reproduce:
- Create any reward with a delay
- log out before that delay is over
- do not log back in until after the scheduled time
- observe: you did not receive the reward.

**Comment by BenCodez** [comment]
You need this option:
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleAdvanced.yml#L119

**Comment by AndrewB6** [comment]
Thanks. Is there a way to use the bossbar to show the time between the beginning of the vote party and the 1h delay? (IE have the bar get 1/60th smaller every minute)?

**Comment by BenCodez** [comment]
Only idea is to have a separate reward for each, or another plugin to that.
