### ISSUE TITLE
two perms per command or one with a pipe character?

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#234]
I'm investigating the use of NuVotifier and Voting Plugin.  When I look at the permissions list it is a bit confusing as as it is all mashed together separated by pipes "|" and no descriptions explaining why.  I have 7 servers using PEX for my permission system, Spigot 1.12 and BungeeCord Server 1.12 all on Windows servers.
/av AddPoints (Player) (Number) : VotingPlugin.Commands.AdminVote.AddPoints|VotingPlugin.Admin
/av BackgroundUpdate : VotingPlugin.Commands.AdminVote.BackgroundUpdate|VotingPlugin.Admin
/av ClearCache : VotingPlugin.ClearCache|VotingPlugin.Admin

Is the first permission node VotingPlugin.Commands.AdminVote.AddPoints|VotingPlugin.Admin
or are there two permissions for the one command and split out in the permissions.yml as:
VotingPlugin.Commands.AdminVote.AddPoints
VotingPlugin.Admin

There is no explanation on the page to describe the permissions or why there are multiple for one command.  It looks like there are perms for Admins, Mods and Players.  If our admins act as both admins and mods, do they need both permission nodes?

**Comment by BenCodez** [comment]
It means either permission. I'll update the wiki.

https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/Objects/CommandHandler.java#L347

They need both permissions nodes (last question)
