### ISSUE TITLE
sitename is case sensitive

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#235]
I'm using 5.9.4 on BungeeCord Server/Spigot 1.12 release. When I type in /adminvote votesite takemetominecraft check I get nothing returned.  However, if I use TakeMeToMinecraft, then I get "ServiceSite is properly setup - VoteURL is properly setup".  Please make the sitenames not case sensitive.

**Comment by BenCodez** [comment]
Didn't think it was case sensitive

**Comment by BenCodez** [comment]
Yeah, it kinda needs to be case sensitive, so I'm going to leave it for now.

Most people don't even use those commands, they use /av gui.

**Comment by smmmadden** [comment]
why would it need to be case sensitive?  Makes no sense to me that takemetominecraft or Takemetominecraft or TakeMetominecraft etc would need to be different references.  /av or /adminvote are the same, av is abbreviated version and if they are not why are they different? :-)

**Comment by BenCodez** [comment]
It directly edits/reads from the config, which is case sensitive.

**Comment by smmmadden** [comment]
understood, but it could easily be pushed to upper() or lower() to validate the name typed by the players.  Keeping in mind that this could be anywhere from years old an up for us.  Best practices suggest anything that can be typed by a user and validated elsewhere should have controls in place to ensure the user did it correctly or the software handles simple things like the case of a value. :-)

If it is not going to change anytime soon, the validation process of typing that command should inform the user the votesite provided doesn't exist.  In my case, no message shown in the chat window at all.  So either way, I do recommend tightening up that part of the code.

I at least understand what caused it, is and can work around it by making it all lower cased for now.  Supporting multiple named values for something like this could cause namespace issues later.   Please consider either option - if something doesn't match the config, display the error. If it matches the value in the config but not the cased the same - state that to the user.

**Comment by BenCodez** [comment]
Why not tab complete? Will look at improving that. I honestly forgot I had these commands, no one uses them, they just use the GUI, I might just remove some.

**Comment by smmmadden** [comment]
I use a combination of the two.  I'm old school, so commands are my life after being in this line for 35+ years :-)
