### ISSUE TITLE
vote party place holder api not working with this

### ISSUE THREAD

**Issue by ozm8** [BenCodez/VotingPlugin#245]
I have the broadcast like this when someone votes
 Broadcast: '&6%VotingPlugin_VotePartyVotesNeeded% &bVotes needed until vote party!'

but it actually comes up with the %VotingPlugin_VotePartyVotesNeeded% not a number.
I have PlaceholderAPI-2.8.2 and idk why its not working. Any help?

**Comment by BenCodez** [comment]
Don't think that's possible right now. Only other way is to message each
player right now.

**Comment by ozm8** [comment]
oh i see so the broadcast placeholder doesn't come up with broadcast but it does in player message?

**Comment by BenCodez** [comment]
Basically. Broadcasts have nothing to do with the player, so it's hard to
decide how placeholders work.
