### ISSUE TITLE
Next vote time not registering for craftservers

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#246]
This server shows I voted already by making the button non-clickable.
![image](https://user-images.githubusercontent.com/10309346/29486752-9299672a-84bb-11e7-9367-6e7f384c06c4.png)
And at the bottom of that [page](https://www.craftservers.net/server/198-take-me-to-minecraft/)
The Voting GUI doesn't say I voted yet.
![image](https://user-images.githubusercontent.com/10309346/29486740-689f4714-84bb-11e7-8ae1-4e926808222b.png)

But it does for the other voting server.
![image](https://user-images.githubusercontent.com/10309346/29486737-5e286428-84bb-11e7-9bcc-cda84e6c27e6.png)

Any idea why minecraftforum.net works and craftservers.net doesn't?

**Comment by BenCodez** [comment]
Server didn't get the vote. Also check the service site.

**Comment by smmmadden** [comment]
finally got everything all configured and registering.  Both craftservers and minecraft_forum votes are being recorded and sent back to my servers. :-)  Sorry it took this long to square it away, but you can close this now.
