### ISSUE TITLE
It's possible to get the clocks from the /vote total command 

### ISSUE THREAD

**Issue by Momshroom** [BenCodez/VotingPlugin#247]
If you vote WHILE the GUI for the vote links is open, then the automatic vote total command lets you get the items from the /vote total GUI. It does not work if you just do /vote total and grab them.  

To replicate:
1) Do /vote
2) click a link
3) Do /vote AGAIN
4) actually vote while the GUI is open
5) drag the clock out of the /vote total GUI that appears

The player that initially reported this to me was also able to get an emerald block from the actual /vote GUI as well.  I have not been able to do that as of yet.

Spigot 1.12.1
Votingplugin 5.9.6 (Also present on 5.9.4)

If this isn't clear enough, I can make a video.

**Comment by BenCodez** [comment]
Can't seem to cause that to happen. Are items present after a relog?

**Comment by Momshroom** [comment]
Yes, they are.  It only happens if the vote gui is up when the actual vote comes back to the server.  https://vimeo.com/230638978

**Comment by BenCodez** [comment]
I'll look into it when I get a chance.

**Comment by BenCodez** [comment]
Any update on this using latest version?

**Comment by Momshroom** [comment]
It's fixed now. Tyvm!
