### ISSUE TITLE
Broadcast Help

### ISSUE THREAD

**Issue by ahriee** [BenCodez/VotingPlugin#250]
Hi thank you for this amazing plugin!
I was wondering how to change the broadcast message? i tried editing it but it still shows the same thing.
I want to make a custom broadcast message, please help me.
Thank You in advance

here's my config:

> https://pastebin.com/ySbYnfKK

**Comment by BenCodez** [comment]
You sure that doesn't work? Do you have any broadcasts set as the reward? Reload the plugin? Restart the server?

**Comment by ahriee** [comment]
I have tried reloading the plugin and restarting the server. the only files i changed are config and votesites.
for the votesites i set a command as broadcast and it doubles when i check using the fake vote

heres the votesites.yml
https://pastebin.com/5Bs1Uhct

**Comment by BenCodez** [comment]
You messed up the spacing on the commands. Try that.

    Console:
    - 'broadcast &l&c%player% &r&bsuccessfuly voted and received rewards!'
    - 'eco give %player% 200'
    - 'crate key %player% basic'

**Comment by ahriee** [comment]
okay i will try and update you if it works. btw thank you so much for assisting me, you reply fast :)

**Comment by ahriee** [comment]
Okay so the votesite broadcast only show up when the player is online but the other broadcast show up despite everything XD
heres a screenshot:
http://imgur.com/a/zvIsX

**Comment by BenCodez** [comment]
That's exactly what should happen.

**Comment by ahriee** [comment]
ohh, so you cant change the broadcast message?

**Comment by BenCodez** [comment]
You made a yml error here:
About line 128
 Vote:
      Text:
     - '&4&lVote Links:'

**Comment by ahriee** [comment]
somehow it looks different in pastebin XD but it actually looks like this:
http://imgur.com/a/gDZzj

is it still wrong?

**Comment by BenCodez** [comment]
Looks correct. Paste your config here:
http://yaml-online-parser.appspot.com/

If its fine then it should work.

**Comment by ahriee** [comment]
OMG the error was in line 552 something about the first vote, i forgot to put hashtag .
THANK YOU! its working now, btw do u have a sample for setting up the voteshop? i cant find any helplink in your wiki. i cant seem to make the playerhead thing work XD

**Comment by BenCodez** [comment]
Just take a look at the example. Works just like the reset of the plugin. Can always use bossshop if needed.

**Comment by ahriee** [comment]
okay. thanks again for helping me out. youre awesome
