### ISSUE TITLE
total rewards given?

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#252]
I've been voting and have setup the reward files so I should be getting money and diamonds (for now) but all I see is the thank you for voting and the GUI open up acknowledging I voted.

If I use the /vote rewards I can see the options to view/change the reward details and they show what I added to the files.  What I'm trying to find out is, what is the total points, money, items I received and what I was rewarded so I can validate a) rewards are working, b) I can tally up who got what and players can see what they've earned by voting.

Thanks,
Steve

**Comment by BenCodez** [comment]
Turn debug on and see what you get in console

**Comment by smmmadden** [comment]
I turned on debugging for:

and when I typed in /vote rewards instead of /av rewards, it threw an [exception](https://pastebin.com/Xe4aVd1Q):
Debug: true
ExtraDebug: true

/av rewards still only opens the GUI but nothing shows in the logs
Not sure how that was going to get me the totals given to players.

**Comment by smmmadden** [comment]
I'm also seeing the two example files getting recreated and added when I'm trying to only use the two I had for the two voting servers.  I can't see anywhere not to use these "Example*" files so they don't appear in the GUI or loaded.
![image](https://user-images.githubusercontent.com/10309346/29819544-268ba918-8c8f-11e7-8b5c-fafb9fc88f69.png)

**Comment by BenCodez** [comment]
They are the example files, like a default config.

**Comment by smmmadden** [comment]
right, but the UI doesn't need to load or show them.  

Isn't that the reason why we create specific votesites so that only they get used and shown on the UI? Once something goes live into production, there isn't a need to have "Example*" anything shown. :-)

**Comment by BenCodez** [comment]
Player's can't see them, not really sure what the problem is.

**Comment by smmmadden** [comment]
I renamed the files so they wouldn't be shown in the UI, but when I do, the code creates them anyway and anything in this folder gets added to the UI.  What I only want to see is what matters for that server, not all the others that are only examples.  Is this making more sense now? :-)
![image](https://user-images.githubusercontent.com/10309346/29830521-7e92cd50-8cb0-11e7-9155-c84f05443a07.png)
![image](https://user-images.githubusercontent.com/10309346/29830529-86b61eec-8cb0-11e7-9861-8a1d813bb17f.png)
![image](https://user-images.githubusercontent.com/10309346/29830539-8e65730e-8cb0-11e7-91b0-ae5fa5c324df.png)
![image](https://user-images.githubusercontent.com/10309346/29830549-95e67790-8cb0-11e7-812c-79dfff0052c5.png)
![image](https://user-images.githubusercontent.com/10309346/29830638-ce4944be-8cb0-11e7-821c-863394a71c49.png)

**Comment by BenCodez** [comment]
Its like saying you don't want the default config and you want to get rid of it. It's there to show all the possibilities.

**Comment by smmmadden** [comment]
actually, that's not what I'm trying to do Ben.  Perhaps it's just the naming convention I'm getting stuck on.  There are words in the software industry that we don't use in a Production setting.  "test, testing, foobar, example, etc. are a few "examples". pun intended :-)

I created two files with the rewards in them based on the "examples" provided OOTB (your plugin).   VoteSites_CraftServers_Rewards.yml and VoteSites_MinecraftForum_net_Rewards.yml

Since these are the two servers players are getting rewarded by, having their names stated made sense.
What I expected in the UI was AllSites, FirstVote, VoteReminding_Rewards and the two I created.  The examples are no longer relevant since I copied some of the details into the new files.  However, if I delete the two example files from the folder or rename them, they get recreated by the plugin on restart or if I renamed the files as I did, they too get put into the UI. :-)  That's counter-intuitive to what I thought was going to help this scenario.

We got off topic a bit, but the initial question was how do I see what each player has been rewarded?  (e.g. Total Diamonds, Total Money Paid, Total Items given, etc.)  The UI shows what to give, but I don't see anything that shows me what we gave to each player.

**Comment by BenCodez** [comment]
Just manually give the reward?

Or do you what the player got in total in voting?

**Comment by BenCodez** [comment]
Any update on this?

**Comment by smmmadden** [comment]
sorry for delay.  Using some of the /av commands I could see how many times and where someone voted.  Great!
/av report only provides a zip file with all the configuration files.  Doesn't provide any meaningful report of rewards or total votes for all players and the like.  So as a server owner, I see where they vote and can confirm they received rewards (based on me testing), but I have no report showing how many diamonds were rewarded and to who.  Or how much money was rewarded for xx time period and for who.

Conceptually, I see the votes working properly, I can edit totals, edit settings and add points or .  What I don't have insight into is the rewards breakdown by player, by date, by server.  I know the rewards are working, as I've received what is configured.  I just can't get totals for anyone.

The second issue is the reward files.  If I've created named reward files for the two voting servers, the example files shouldn't be created if I rename or remove them.
Seen here in the folder, the examples are present even though I have *CraftServers* and *MinecraftForum_net* files. 
![image](https://user-images.githubusercontent.com/10309346/30769115-a007f350-9fe0-11e7-9180-bee16c53d48c.png)

This carries into the game shown here:
![image](https://user-images.githubusercontent.com/10309346/30769119-bcc3a76e-9fe0-11e7-8187-d91dff1801a9.png)
![image](https://user-images.githubusercontent.com/10309346/30769125-c69e5cfc-9fe0-11e7-8cae-da91c13ed3fe.png)
So somewhere you're hard-coding a requirement for the 3 example files to exist (always) and shown in-game. 
I hope this is more clear now.

**Comment by BenCodez** [comment]
I think its a waste of resources to track how many items the player got in total from voting.

I hardcoded the example rewards so people have a quick resource to look, since the majority people don't know how to use the wiki page or github to find the files. Only in the admin commands you can see ingame the other rewards.

**Comment by smmmadden** [comment]
I can understand that Ben.  That is only looking at it from one perspective.  

It's not a waste of resources to report on what was rewarded - that's the whole point of giving a reward. Some sites publicly advertise what rewards are given for voting and part of that marketing is to show which server gives the best rewards and who is the top rewarded player.  So if you look at this from the outside looking in (not the developer) and ask yourself, why would I go to Steve's server versus Ben's server.  

They both offer similar rewards, but Ben's server doesn't show any proof of what players are actually getting.  Steve's server advertises in the scoreboard and the website, who the top 5 voters are and what they've earned in money, xp and items.  That's what I'm looking at and was hoping the /av report would have done that or the UI for /av rewards would have provided.

I understand why the example files are provided, that makes sense to do for noobs. The plugin lets me name the reward files, but I don't care after I do that for the Examples to take up slots when I want to go through the totals.  It no longer adds value when I'm done experimenting. Perhaps a config setting that toggles it on/off to show in the GUI or not - even if the files remain, that would be fine - just not in the GUI.

**Comment by BenCodez** [comment]
Yes, but to save all the data on what rewards were given I feel is a huge waste, not to mention probably would cause lag. Why just in a broadcast say what he got?

I don't really see why I would need to remove the example files from the gui, but I'll see.

**Comment by smmmadden** [comment]
sorry, I'm not able to explain it any better than what I've already provided.  I've stated different reasons to do both and the value of doing so.  If you ask around and provide my scenario, I would be very surprised if others say they wouldn't want that too.

As for lag, it shouldn't be any different than all the other data points being saved as even Minecraft records all achievements automatically, this is just a hook to get that data.  The broadcasts are for "now", not historical - that's what is missing.

This is more about what server owners want to do with the plugin data, not personal preferences. :-)  Just give it some thought and ask around, that's all I ask. -Steve

**Comment by BenCodez** [comment]
So you just want a like a total amount of diamonds gotten kind of thing? I think the fun part about adding then would be how to store it efficiently, don't want a million columns in mysql, would take forever to load everything in that case.
