### ISSUE TITLE
Vote Party

### ISSUE THREAD

**Issue by ahriee** [BenCodez/VotingPlugin#253]
Hi, i copy pasted my rewards from votesites to the voteparty to check, but it doesnt seem to work. I have to wait for voteparty to see if it works XD Is there a way to force trigger the vote party? (aside from temporarily changing the number of votes needed)

**Comment by BenCodez** [comment]
Don't think there is a way other than what you said.

Can I see the config?

**Comment by ahriee** [comment]
Hello, i have fixed the config, its working now but my only problem is, even offline players get the rewards when they go online. here's my config:
https://pastebin.com/1fxp6kf5
(the config is working,it just looks like that in pastebin)

**Comment by BenCodez** [comment]
That's how it should work. You can do this to prevent that.

    Rewards:
      RewardType: 'ONLINE'
      Commands:
        Console:
        - eco give %player% 500
        - crate key %player% basic
        - crate key %player% lucky
        Player:
        - i EXP_BOTTLE 16 name:&d&lP&b&la&d&lr&b&lt&d&ly_&b&lB&d&le&b&le&d&lr
      Title:
        Enabled: true
        Title: '&l&k|||&r &cINCOMING VOTE PARTY!!&r &l&k|||'
        SubTitle: '&aCONGRATULATIONS!'
        FadeIn: 10
        ShowTime: 50
        FadeOut: 10

**Comment by ahriee** [comment]
ooohhh there's a reward type. thank you once again! :)
