### ISSUE TITLE
[Request] Global Rewards

### ISSUE THREAD

**Issue by jasonriv** [BenCodez/VotingPlugin#255]
Hi Ben,

Is it possible to make a global rewards feature? Due to the new EULA I cannot give a single player items for voting on the server, it must be global rewards.

For example:

Player A votes, and Player B is also on the server. Both players should receive the items for Player A voting.

**Comment by BenCodez** [comment]
Set voteparty to require 1 vote and use that.

**Comment by BenCodez** [comment]
Any update on this?
