### ISSUE TITLE
Voting not being broadcast/awards not being given

### ISSUE THREAD

**Issue by FatmanC** [BenCodez/VotingPlugin#259]
Hi
I have installed votifier and your voting plugin, configured it as recomended and as title suggests.... not broadcast of votes, no points or rewards being given. 
I have only one server list to vote on, and from THEIR website i can see people voted.... but from server side i can not. 

i watched the votifier listener as you suggested in your how to setup.... i have a listener installed in votifier listeners file.... but is this  listener also? should it be put into the listeners folder of votifer? is that what i am doing wrong?? or should i delete the listener in the listeners folder?

please help
thanks

**Comment by BenCodez** [comment]
Sounds like the server isn't getting the vote. Check votifier.

**Comment by FatmanC** [comment]
i wasnt able to get the plugin working so i went with a simpler one and for some reason it works now. Thanks anyway. Wish it had worked

**Comment by BenCodez** [comment]
It actually wouldn't of mattered which listener you used if its the issue I think you have.
