### ISSUE TITLE
Money per login

### ISSUE THREAD

**Issue by Acornmc** [BenCodez/VotingPlugin#261]
I am experiencing an issue. After I installed this plugin, players on my server now receive $100 each time they log in. I uninstalled it, and the issue stopped, except now I don't have a voting plugin. I want to reinstall it, but I don't know how to fix this problem.

**Comment by BenCodez** [comment]
You must of configured to give money on login. Turn debug on. Send console logs and config files.

**Comment by BenCodez** [comment]
Any update on this?
