### ISSUE TITLE
How to disable or change broadcast on vote?

### ISSUE THREAD

**Issue by IvanStajdi** [BenCodez/VotingPlugin#262]
![screenshot_8](https://user-images.githubusercontent.com/31400993/30387241-36070a6c-98ac-11e7-8664-3ce563da98d4.png)
Hello, I am unsure how to disable a message being broadcasted every time somebody votes on the server (an example of the broadcast included in the image). I want to add my own message which would be broadcasted by another plugin via the Commands in the Rewards file because the default broadcast has ugly colors, but without disabling the default broadcasting I'll just get a double message every time someone votes. Please help me and tell me how to disable the default broadcasting because I've scoured the config and didn't find any such option. Thank you in advance.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L121

Option in the Config.yml, set to '' to disable.

**Comment by IvanStajdi** [comment]
Thanks, I set it to '' in my config and then restarted the server but it still shows up whenever somebody votes.

Excerpt from my config: https://pastebin.com/TU4mGzVC

Any other ideas what could be causing this?

**Comment by BenCodez** [comment]
Are there any errors? You probably have a yml error

**Comment by IvanStajdi** [comment]
Hi, sorry for late response, I was busy. I don't have any errors in my console, I checked both on startup and when players voted. Here is my config.yml file, converted to .txt, so you can check if there's any errors.

[Config.txt](https://github.com/Ben12345rocks/VotingPlugin/files/1308666/Config.txt)

**Comment by BenCodez** [comment]
You have an error....
Paste it in here:
http://yaml-online-parser.appspot.com/

**Comment by BenCodez** [comment]
Any update on this?
