### ISSUE TITLE
Rather large issue with voting.

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#263]
I have the server setup to not take in fake votes aka require users to have joined the server before. A user voted with the the name "y" and received the vote? It didn't say their full name it said "y has voted for the server". It gave the user the reward however created a new user file for "y". It also doesn't count for voting on all sites. This is because it created a new user file called "y" and the user doesnt get the all sites reward cause it goes to "y". Per website vote rewards goto the user.

**Comment by BenCodez** [comment]
There is no way to deal with stuff like that. Players have to correctly enter their name.
You can set allowunjoined to false to prevent creating random data files.

**Comment by LogGits** [comment]
Allowunjoined is set to false. There is a way of dealing with this.
Let me reiterate what i was trying to say (i must say that now looking back at it i worded it poorly)

Lets say the users name is "ILikeCake8989"
if the user votes using "ilike" it will trigger a vote. On the server it will say "ilike has voted for the server!" and give the reward to "ILikeCake8989". The single website vote rewards will go to the user however when they vote on all websites that reward doesn't goto them. 

I want players to have to put in their full entire name. However, some players are voting using the first 4 characters of their name.

**Comment by BenCodez** [comment]
That shouldn't be possible. Players have to correctly enter their name. That's why they didn't get the all sites reward.

**Comment by BenCodez** [comment]
How is this in the newest version?

**Comment by LogGits** [comment]
I will test this when I get back home. Sorry for the slow response didn't see your message.

**Comment by LogGits** [comment]
Alright so I did a little testing and "T" accepted the vote whereas "c" didn't. This could be because I used T as a voting test before the update is there a way to delete userfiles like T or Y? I believe it would think that T and Y have joined the server when they actually haven't because its a 1 character name which u can't get in Minecraft.

**Comment by BenCodez** [comment]
Is allowunjoined set to false? If so it won't create those userfiles. Just go in and delete the ones you want.

**Comment by LogGits** [comment]
Yes it is set to false and I'll try deleting them.

**Comment by BenCodez** [comment]
This might help a bit:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Found a way allowunjoined can still create user files even if its an invalid player. That should fix that.

**Comment by LogGits** [comment]
@Ben12345rocks check your spigot direct messages.
