### ISSUE TITLE
Having trouble in the config with rewards

### ISSUE THREAD

**Issue by RegencySolid** [BenCodez/VotingPlugin#264]
For voting im having trouble finding out how to do multiple command rewards, one works fine if i do it like this

    Rewards:
      Commands:
        Console:
        - eco give %player% 1000

 but if i do it like this it doesnt work, even with the first

    Rewards:
      Commands:
        Console:
        - eco give %player% 1000
        - ce dust mystery 10 %player%
        - ce lostbook common 1 %player% 

Could I please get some help with this? thanks

**Comment by BenCodez** [comment]
Rewards:
      Commands:
        Console:
        - 'eco give %player% 1000'
        - 'ce dust mystery 10 %player%'
        - 'ce lostbook common 1 %player% '
Try that?

**Comment by RegencySolid** [comment]
I tried that too and it doesnt work

**Comment by BenCodez** [comment]
Can you send me your full VoteSites.yml?

**Comment by RegencySolid** [comment]
https://pastebin.com/V9937Qrj

does that work?

**Comment by RegencySolid** [comment]
also is there a way i can check to see if it works in game without voting?

**Comment by BenCodez** [comment]
Don't think this is the correct service site: (Vote and look in console for the correct one)
      ServiceSite: PMC

/av vote (name) (site)

**Comment by RegencySolid** [comment]
when i vote it comes up in the vote gui that the PMC and MinecraftForum one is still available but i've apparently voted for PlanetMinecraft_com

**Comment by BenCodez** [comment]
Its adding the votesite since there is no correct service site. (Option to disable that) Just look in console and you'll see what its doing.

**Comment by RegencySolid** [comment]
I changed the service site, that was the problem, all i had to do was change it back to PlanetMinecraft.com and MinecraftForum.com, thanks for the help!
