### ISSUE TITLE
Issue with service sites

### ISSUE THREAD

**Issue by RegencySolid** [BenCodez/VotingPlugin#265]
I'm trying to add minecraft forum as a service site and it doesnt work, ive tried all of these

MinecraftForum.com
MinecraftForum.net
MinecraftForum

Any idea what im supposed to use?

**Comment by BenCodez** [comment]
Vote on the site and look in console for the correct service site.

**Comment by RegencySolid** [comment]
It comes up in console as 

[00:06:41] [nioEventLoopGroup-2-1/ERROR]: [Votifier] Unable to process vote from /52.44.191.1:60640

**Comment by BenCodez** [comment]
That's an issue with the Votifier setup, check that

**Comment by BenCodez** [comment]
Any update on this?

**Comment by RegencySolid** [comment]
I still can't figure it out, all the others are working except for minecraft forum

**Comment by BenCodez** [comment]
You just have the wrong service site probably.

Vote on it and look in console.

**Comment by RegencySolid** [comment]
It doesn't come up in the console

**Comment by BenCodez** [comment]
Then its an issue with the votifier connection. Try resetting it up
