### ISSUE TITLE
How do i set up rewards

### ISSUE THREAD

**Issue by sniperboy2003** [BenCodez/VotingPlugin#268]
i am trying to set up the config to give rewards buts very confusing how u did it. Can you please help me? here's my config I am mainly looking for how to insert commands to give a player like a vote key so they  can use it in a crate Thanks

`	 	# This is a reward file
# Define rewards in here (Items, commands, etc)
# File name is the reward name, without file extention
# This reward is named "ExampleBasic"
# That is what you put as a reward for other plugins, like VotingPlugin
# DO NOT HAVE DUPLICATE NAMES!!

# Wiki Page: 
# https://github.com/Ben12345rocks/AdvancedCore/wiki/Reward-files

# This is basic reward file
# You can have multiple reward files that contain all kinds of rewards
# Below are some basic things you can have, see the advanced example for more

# You can just remove values you don't want (just delete it)
# If you just want money just have a reward file containg only "Money: 100", for example
# You can simply copy and paste from here what you want
# in other reward files, that is the way they are designed

# Items to give to user
Items:
  # Item
  # This is not item display name
  # No 2 names the same
  Diamond:
    # Item Material
    # List of material for 1.10: 
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    Material: 'DIAMOND'
    # Item data value (Eg 1:4, data is 4)
    Data: 0
    # Will only give Amount if min and max amounts are 0
    Amount: 1
    # Set item durability
    # Set to 0 or remove line for no durability
    #Durability: 100
    
    # Random amount of items between Min and Max will be given
    # if min and max are not both 0
    
    # Min amount of items
    #MinAmount: 1
    
    # Max amount of items
    #MaxAmount: 4
    
    # Item name
    # Remove this value to have no name
    Name: '&aSpecial Diamond'
    
    # Lore
    # Remove this value to have no lore
    Lore: 
    - 'Line 1'
    
    # Enchants
    # List of 1.10 Encahants can be found at
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
    Enchants:
      DURABILITY: 1
      
# Amount of money to give, requires vault
# Use 0 to give none
# Money is not per world
# Use negative to take money
Money: 500

# Pick random number between min and max amount
#MinMoney: 100
#MaxMoney: 3000

# Give player experience
EXP: 100

# Pick a random number between min and max amount to give
MinEXP: 100
MaxEXP: 1000

# Commands to run
# Use %player% for player name
# Set to Console: [] for no commands
Commands:
  # Commands here will be run by console
  Console:
  - 'say %player% was lucky'
  # Commands here are run by player
  Player:
  - 'vote total'

# The messages are sent when rewards above are given to user
# set to '' to give no message
# If no value is set, default in Format.yml is used
Messages:
  Player: '&eThank you for voting your reward will be issued shortly! You may need to leave and join back.'
  Broadcast: '&b%player% &bJust Voted From Cfoods Network! You can too by doing /vote!'`

**Comment by sniperboy2003** [comment]
sorry i tryed to make it look nicer

**Comment by BenCodez** [comment]
Use pastebin to send your config, here is an example
https://pastebin.com/hAPaBmbf

**Comment by sniperboy2003** [comment]
`	# This is a reward file

Define rewards in here (Items, commands, etc)

File name is the reward name, without file extention

This reward is named "ExampleBasic"

That is what you put as a reward for other plugins, like VotingPlugin

DO NOT HAVE DUPLICATE NAMES!!

Wiki Page:

https://github.com/Ben12345rocks/AdvancedCore/wiki/Reward-files

This is basic reward file

You can have multiple reward files that contain all kinds of rewards

Below are some basic things you can have, see the advanced example for more

You can just remove values you don't want (just delete it)

If you just want money just have a reward file containg only "Money: 100", for example

You can simply copy and paste from here what you want

in other reward files, that is the way they are designed

Items to give to user

Items:

Item

This is not item display name

No 2 names the same

Diamond:
# Item Material
# List of material for 1.10:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
Material: 'DIAMOND'
# Item data value (Eg 1:4, data is 4)
Data: 0
# Will only give Amount if min and max amounts are 0
Amount: 1
# Set item durability
# Set to 0 or remove line for no durability
#Durability: 100

# Random amount of items between Min and Max will be given
# if min and max are not both 0

# Min amount of items
#MinAmount: 1

# Max amount of items
#MaxAmount: 4

# Item name
# Remove this value to have no name
Name: '&aSpecial Diamond'

# Lore
# Remove this value to have no lore
Lore: 
- 'Line 1'

# Enchants
# List of 1.10 Encahants can be found at
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
Enchants:
  DURABILITY: 1
Amount of money to give, requires vault

Use 0 to give none

Money is not per world

Use negative to take money

Money: 500

Pick random number between min and max amount

#MinMoney: 100
#MaxMoney: 3000

Give player experience

EXP: 100

Pick a random number between min and max amount to give

MinEXP: 100
MaxEXP: 1000

Commands to run

Use %player% for player name

Set to Console: [] for no commands

Commands:

Commands here will be run by console

Console:

'say %player% was lucky'
Commands here are run by player

Player:

'vote total'
The messages are sent when rewards above are given to user

set to '' to give no message

If no value is set, default in Format.yml is used

Messages:
Player: '&eThank you for voting your reward will be issued shortly! You may need to leave and join back.'
Broadcast: '&b%player% &bJust Voted From Cfoods Network! You can too by doing /vote!'`

**Comment by sniperboy2003** [comment]
# This is a reward file
 
Define rewards in here (Items, commands, etc)
 
File name is the reward name, without file extention
 
This reward is named "ExampleBasic"
 
That is what you put as a reward for other plugins, like VotingPlugin
 
DO NOT HAVE DUPLICATE NAMES!!
 
Wiki Page:
 
https://github.com/Ben12345rocks/AdvancedCore/wiki/Reward-files
 
This is basic reward file
 
You can have multiple reward files that contain all kinds of rewards
 
Below are some basic things you can have, see the advanced example for more
 
You can just remove values you don't want (just delete it)
 
If you just want money just have a reward file containg only "Money: 100", for example
 
You can simply copy and paste from here what you want
 
in other reward files, that is the way they are designed
 
Items to give to user
 
Items:
 
Item
 
This is not item display name
 
No 2 names the same
 
Diamond:
# Item Material
# List of material for 1.10:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
Material: 'DIAMOND'
# Item data value (Eg 1:4, data is 4)
Data: 0
# Will only give Amount if min and max amounts are 0
Amount: 1
# Set item durability
# Set to 0 or remove line for no durability
#Durability: 100
 
# Random amount of items between Min and Max will be given
# if min and max are not both 0
 
# Min amount of items
#MinAmount: 1
 
# Max amount of items
#MaxAmount: 4
 
# Item name
# Remove this value to have no name
Name: '&aSpecial Diamond'
 
# Lore
# Remove this value to have no lore
Lore:
- 'Line 1'
 
# Enchants
# List of 1.10 Encahants can be found at
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
Enchants:
  DURABILITY: 1
Amount of money to give, requires vault
 
Use 0 to give none
 
Money is not per world
 
Use negative to take money
 
Money: 500
 
Pick random number between min and max amount
 
#MinMoney: 100
#MaxMoney: 3000
 
Give player experience
 
EXP: 100
 
Pick a random number between min and max amount to give
 
MinEXP: 100
MaxEXP: 1000
 
Commands to run
 
Use %player% for player name
 
Set to Console: [] for no commands
 
Commands:
 
Commands here will be run by console
 
Console:
 
'say %player% was lucky'
Commands here are run by player
 
Player:
 
'vote total'
The messages are sent when rewards above are given to user
 
set to '' to give no message
 
If no value is set, default in Format.yml is used
 
Messages:
Player: '&eThank you for voting your reward will be issued shortly! You may need to leave and join back.'
Broadcast: '&b%player% &bJust Voted From Cfoods Network! You can too by doing /vote!'

**Comment by sniperboy2003** [comment]
``   # This is a reward file
 
Define rewards in here (Items, commands, etc)
 
File name is the reward name, without file extention
 
This reward is named "ExampleBasic"
 
That is what you put as a reward for other plugins, like VotingPlugin
 
DO NOT HAVE DUPLICATE NAMES!!
 
Wiki Page:
 
https://github.com/Ben12345rocks/AdvancedCore/wiki/Reward-files
 
This is basic reward file
 
You can have multiple reward files that contain all kinds of rewards
 
Below are some basic things you can have, see the advanced example for more
 
You can just remove values you don't want (just delete it)
 
If you just want money just have a reward file containg only "Money: 100", for example
 
You can simply copy and paste from here what you want
 
in other reward files, that is the way they are designed
 
Items to give to user
 
Items:
 
Item
 
This is not item display name
 
No 2 names the same
 
Diamond:
# Item Material
# List of material for 1.10:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
Material: 'DIAMOND'
# Item data value (Eg 1:4, data is 4)
Data: 0
# Will only give Amount if min and max amounts are 0
Amount: 1
# Set item durability
# Set to 0 or remove line for no durability
#Durability: 100
 
# Random amount of items between Min and Max will be given
# if min and max are not both 0
 
# Min amount of items
#MinAmount: 1
 
# Max amount of items
#MaxAmount: 4
 
# Item name
# Remove this value to have no name
Name: '&aSpecial Diamond'
 
# Lore
# Remove this value to have no lore
Lore:
- 'Line 1'
 
# Enchants
# List of 1.10 Encahants can be found at
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
Enchants:
  DURABILITY: 1
Amount of money to give, requires vault
 
Use 0 to give none
 
Money is not per world
 
Use negative to take money
 
Money: 500
 
Pick random number between min and max amount
 
#MinMoney: 100
#MaxMoney: 3000
 
Give player experience
 
EXP: 100
 
Pick a random number between min and max amount to give
 
MinEXP: 100
MaxEXP: 1000
 
Commands to run
 
Use %player% for player name
 
Set to Console: [] for no commands
 
Commands:
 
Commands here will be run by console
 
Console:
 
'say %player% was lucky'
Commands here are run by player
 
Player:
 
'vote total'
The messages are sent when rewards above are given to user
 
set to '' to give no message
 
If no value is set, default in Format.yml is used
 
Messages:
Player: '&eThank you for voting your reward will be issued shortly! You may need to leave and join back.'
Broadcast: '&b%player% &bJust Voted From Cfoods Network! You can too by doing /vote!'``

**Comment by sniperboy2003** [comment]
[https://pastebin.com/zyYbTT4S](url)

**Comment by BenCodez** [comment]
Would recommend watching this:
https://www.youtube.com/watch?v=11R5ggomcI4&list=FLP6uxYyleyG5rt9mdmWpR8w&index=1

**Comment by sniperboy2003** [comment]
Thanks for the Help!
