### ISSUE TITLE
Errors in console after recent update

### ISSUE THREAD

**Issue by TheZenKitteh** [BenCodez/VotingPlugin#270]
https://pastebin.com/raw/GkqdBpxb

It seems to pop up if I do /vote then click the back icon then click the VoteNext icon. All the icons in there are stone.

Config file:
https://pastebin.com/raw/TetU9qB2

Some notes. After update I noticed some issues so backed up the config file, deleted it, and restarted the server so it would regenerate a default one. I then edited. This issue was there before the edit. Server is Spigot 1.12.1 (This server is running CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT))

**Comment by BenCodez** [comment]
Each site in the VoteSites.yml has an item section. Add that.

**Comment by Platinteufel** [comment]
Just some thoughts: If something like the Item section is missing there could be 2 opportunities:

1) Add it automatically with a standard item (e.g. diamond)
2) Disable this specific voting site and print a warning in console like
" .. service disabled. Please check it in VoteSites.yml"

Don't know if you think it would be useful, but maybe it will prevent some issues like this.

**Comment by BenCodez** [comment]
1. It deletes comments if I set a value, so that won't work for values in Config.yml
Been getting this same issue a lot now, might need to do that.

2. It's only used in GUI's, some people have them off,

**Comment by BenCodez** [comment]
Just added a message to log in console, hopefully this will make it easier to find the problem.
