### ISSUE TITLE
Issues with GUI

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#273]
It's possible to loose items and trigger exceptions in console by trying to shift items into **/vote gui**, see: https://youtu.be/SeUJdc0Osek
**NPE:** https://pastebin.com/px6P1DCh

Example for GUI:
https://youtu.be/qfOvuXkOU4A _(Plugin: AdvancedAchievements)_

**Comment by Platinteufel** [comment]
I don't know if you can see it in the video: 
Trying to shift an item into the gui will open another inventory.

**Comment by Platinteufel** [comment]
Futhermore: https://youtu.be/rEUhqXcmR1w
(tested with default files, no changes made in config)

**Comment by BenCodez** [comment]
This fix it?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Yes, thanks :)

**Comment by Platinteufel** [comment]
Sorry, wrong issue. Unfortunately this is not fixed in this jar.

**Comment by BenCodez** [comment]
This any better?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

If not give me the console logs when you use the gui.

**Comment by Platinteufel** [comment]
Yes, now it's not possible to lose items. Thanks!

**Comment by Platinteufel** [comment]
But you know that you can also control the GUI via **hotbar**? See: https://youtu.be/OOCw0-VaPog
I don't know if this is intended, just asking.

**Comment by BenCodez** [comment]
Well, technically those are the same slot numbers... I'll look into it though

**Comment by BenCodez** [comment]
This fix that?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Yes, it does. With 1 difference: A click on a hotbar item **does not close the inventory** - all other slots will close it instant. See: https://youtu.be/au6PDvUnUS4

**Comment by BenCodez** [comment]
This fix that?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Yes, now none of the players inventory slots will close the GUI and all inventory moves are cancelled. Nice work!

**Comment by BenCodez** [comment]
No problem! Thanks for testing.

**Comment by Platinteufel** [comment]
Uh, one last thing :/

1) Clicking on an **empty slot** in GUI will close it (intented for safety reasons?). Maybe doesn't make sense.
2) "Back" button in Vote Shop is missing.

See: https://youtu.be/TOewtz3CXoI

**Comment by BenCodez** [comment]
This should do both:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
You're awesome fast, works like a charm. :)
Just managed to trigger a NPE while spamming and trying to shift items into GUI, maybe you can catch it? https://pastebin.com/x0zwASma

**Comment by BenCodez** [comment]
And here you go:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

It helps that I'm working on a bunch of other bugs right now :)
