### ISSUE TITLE
Color code not parsed 

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#274]
Color code is shown in chat instead of parsing it, if you go to the top voters and try to open another GUI.

Video: https://youtu.be/ekvN-MwO1A8

**Comment by BenCodez** [comment]
Yeah, I'll need to fix that.

**Comment by BenCodez** [comment]
This fix it?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Yes, thank you. :)
