### ISSUE TITLE
Invalid entries in user.db - missing checks?

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#275]
After some tests I took a look into my **users.db** and found this:

![votesholy](https://user-images.githubusercontent.com/13700636/30838816-2b7dac4c-a26e-11e7-8dec-6fbc03529430.PNG)

Furthermore I've noticed that you can create every user-entry with /vote gui anyName, and there's no check like _"This user doesn't exist in database"_.

**Comment by BenCodez** [comment]
Will have to fix that tomorrow, thank's for reporting. It shouldn't cause any issues however.

**Comment by Platinteufel** [comment]
Thanks for your time! I think this specific case (row 7 in database) is caused by open the players GUI via **Todays** or **Top Voters**. 
That's unfavourable because you won't see the stats of the real player (Testaccount), but of the invalid entry §3§l3: §3Testaccount. 

![votescause](https://user-images.githubusercontent.com/13700636/30839023-6b2ee882-a26f-11e7-9b60-6ce0466693ed.png)

There also could be missing checks at some other points like **/vote gui name**.

**Comment by Platinteufel** [comment]
Additionaly I've noticed a little thing:

1) Open your /vote gui
2) Go into Top Voters and open an click another player (in this case Testaccount)
3) Close the GUI
4) Type something like /vote, so that you don't open the **main** GUI, but another GUI.
5) Use the back button
6) You're still in the other players GUI.

**Video:** https://youtu.be/BaaYSOLorxY

Shouldn't cause any issues, but just reported it too. :)

**Comment by BenCodez** [comment]
This should fix everything I think:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Yes, thanks! Just found another issue (?), but I'll open another ticket for it.
