### ISSUE TITLE
Vote rewards

### ISSUE THREAD

**Issue by Mylias** [BenCodez/VotingPlugin#277]
Hi,

I have set up VotingPlugin and it recognizes votes but isnt giving rewards. 
I am on hour 4 of tinkering with this  and cant find any solutions lol

could you take a look at this and see if you can spot where I went wrong? 
https://pastebin.com/AZ9Azfwn

Thanks! :)

**Comment by BenCodez** [comment]
Everything looks okay at first glance. 

Are the service sites correct? (Vote on the site and look in console to find out.

**Comment by Mylias** [comment]
Hi,

So sorry to bother you on this.. it has started working today. Not sure why cos nothing has changed since I went to sleep lol.
Thanks for the reply though!

~Mylias~
