### ISSUE TITLE
Write to database just after /av reload?

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#278]
If a player votes, he won't appear in vote lists till **/av reload** or **server restart**. Maybe it would make more sense to write it to database and update it instant?

Video: https://youtu.be/5xynkC8pA_8

**Comment by BenCodez** [comment]
There is a background update that happens every 3 minutes by default. Doing it after every vote is very inefficient, so I wait a bit before doing to save resources. You can decrease the delay in the config.

**Comment by BenCodez** [comment]
It will actually update after /av reload, it will just take a minute to load and sort the top voters and such.

**Comment by Platinteufel** [comment]
Okay, thanks, then I'll wait 3 minutes. 
One thing I want you to know: As long as you don't restart the server the new case-sensitive feature will also change the playername in database. But it will correct itself after restart, so I don't think that this could cause issues. :) https://youtu.be/jCFB9K0WayA

**Comment by BenCodez** [comment]
It works fine for me. then again I gave you a version a little while ago and I made a bunch of changes. Should be all good.

**Comment by Platinteufel** [comment]
Yes, after a few minutes it updates correctly. Thanks.
