### ISSUE TITLE
Vote Streak GUI issue

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#280]
**/votestreak GUI** seems to refer to **VoteBest** GUI

Also look at the title of the vstreak GUI -> it's Vote Best

**Comment by Platinteufel** [comment]
Sorry, wrong capture mode, new video in 2 mins

**Comment by BenCodez** [comment]
Looks like its the title that's wrong, still shows the right info

**Comment by Platinteufel** [comment]
New video (should be clear there)
https://youtu.be/BPOYx9tvb9I

**Comment by BenCodez** [comment]
It's a typo in the config (for the gui title), you can fix that. https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L471

This should fix the other issue:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
This fixes the GUI issue, thanks.

But I need to admit that I don't get this streak system.
As you can see I haven't voted once (just started testserver and did /av reload). 
My monthly streak is 1 (??) and all others are 0. If I go vote, nothing happens. 
Is there any explanation of the streak system?
https://youtu.be/PDH83_u1Id4

**Comment by BenCodez** [comment]
It's how many months in a row you voted

**Comment by Platinteufel** [comment]
yes, but i think it doesn't work properly. /vstreak tells me this:

Vote Streak:
Current Daily Streak: 0
Current Week Streak: 0
**Current Month Streak: 1**

How can I vote 1 month in a row, but 0 weeks and 0 days if I just voted yet?

**Comment by BenCodez** [comment]
Not exactly sure but vote streaks is probably my most tested feature, it
should work as intended

**Comment by Platinteufel** [comment]
Okay, I will test it on my own again later.

**Comment by Platinteufel** [comment]
Works as intended, but:
It seems to be weird, maybe it's interesting for debuging (if not, don't bother)

1) install plugin
2) look into /vstreak (all values are 0)
3) do /av reload
4) look again into /vstreak (month streak jumped to 1 even if you haven't voted once)

https://youtu.be/97ihhyR7DcU

**Comment by BenCodez** [comment]
That's probably a bug, but not sure how. I'll look into it.

**Comment by BenCodez** [comment]
Just tested this and it works as intended. No issues on my end.

**Comment by Platinteufel** [comment]
Did you tried the 4 steps I described above? It still happens for me.

**Comment by BenCodez** [comment]
Yes, exactly the same. Can't reproduce

**Comment by Platinteufel** [comment]
Got it, just recording a video

**Comment by Platinteufel** [comment]
Maybe you know what I mean with that? 

https://youtu.be/HNp24sApE0o

The first /av reload creates the missing server data, and if you look into console you'll see
**[VotingPlugin] Debug: Month Changed**

**Comment by BenCodez** [comment]
Why are you missing stuff in ServerData.yml? That's the problem.

**Comment by Platinteufel** [comment]
Well on first install it's missing until the first /av reload

**Comment by Platinteufel** [comment]
(on first install it only creates the file you saw)

**Comment by BenCodez** [comment]
Hmm.... I'll have to look into that later.
First time I've heard of that.

**Comment by Platinteufel** [comment]
Okay, you can also wait for the first background update (it will create the missing server data ~2 minutes after installing plugin). Should be okay I think.

**Comment by BenCodez** [comment]
Yeah, that's what I thought
