### ISSUE TITLE
Firework on rewards: Cancel damage 

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#282]
If there are blocks above your head the launched firework deals damage to entities. 
Video: https://youtu.be/WvnKq7QJ66I 

(Also fixed in an other plugin a while ago: https://github.com/PyvesB/AdvancedAchievements/commit/5e9767af2cae3d9b9ee211b2b63b4ba0709392ca)

**Comment by BenCodez** [comment]
Yeah, forgot that changed. Noted.
