### ISSUE TITLE
Maybe make two more things translateable in GUI

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#283]
Not really important, just reporting it

**AllTime, Monthly, ...** 
![vote1](https://user-images.githubusercontent.com/13700636/30935414-e6aff188-a3d0-11e7-9892-5d356fda8944.png)

**Next Page & Previous Page**
![vote2](https://user-images.githubusercontent.com/13700636/30934903-4eda2a5a-a3cf-11e7-82e6-412d5ead4178.png)

**Comment by BenCodez** [comment]
Noted.
