### ISSUE TITLE
AllowUnjoined: false doesn't work anymore

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#284]
#tested with your latest dropbox version

**Comment by BenCodez** [comment]
You sure?
[VotingPlugin] Player Badpadlas has not joined before, disregarding vote, set AllowUnjoined to true to prevent this

Just tested it.

**Comment by Platinteufel** [comment]
Pretty sure. Have you tried `/av vote anyName votingsite`?

**Comment by BenCodez** [comment]
Yep. I just recompiled, see if this helps:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Hmm, doesn't really help. 
That's how it works for me: https://youtu.be/iHk-LeK6Zg8

**Comment by BenCodez** [comment]
Same jar you just used:
28.09 19:51:12 [Server] WARN [VotingPlugin] Player akdaskdoaskd has not joined before, disregarding vote, set AllowUnjoined to true to prevent this

Reopen the config and see if the value is set?

**Comment by Platinteufel** [comment]
At the moment I can't get it to work with any plugin version. Does this feature need connection to mojang servers?

**Comment by BenCodez** [comment]
No. Is it not set to false or something? That's my only guess.

**Comment by Platinteufel** [comment]
It's set to false, but it still don't want to work ..
Just a stupid question: What does the first part of this 
`if (!PlayerUtils.getInstance().isValidUser(playerName) && !config.allowUnJoined())`

Otherwise I will test it again tomorrow, it's very weird atm ..

**Comment by BenCodez** [comment]
Checks if the player has joined before or is in the database.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/blob/2.9.3/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/Util/Misc/PlayerUtils.java#L163

For reference.

**Comment by Platinteufel** [comment]
Hm, thanks.
I think that doesn't help to find the issue? https://pastebin.com/CMnKCJrq

**Comment by BenCodez** [comment]
My only guess is the value is true in the config, no idea.

**Comment by Platinteufel** [comment]
Well, it's definitely set to false.

My only idea was that it has to do with authentication servers, because right now it works if I type account names that really exist, and if I type nonsense it does not happen anything

```
> av vote Gronkh mceu
[03:23:46 WARN]: [VotingPlugin] Player Gronkh has not joined before, disregarding vote, set AllowUnjoined to true to prevent this
 
> av vote nfsjefnsenufs mceu
 
> av vote Paluten mceu
[03:23:59 WARN]: [VotingPlugin] Player Paluten has not joined before, disregarding vote, set AllowUnjoined to true to prevent this
```

**Comment by BenCodez** [comment]
Is it blocking names that already exist/are real players?

**Comment by Platinteufel** [comment]
It's a testserver with an empty database, and right now it's only blocking real players (like Notch) and not something like `fnsenfiwsuenigs`

I don't know how this is possible if there is no connection to authentication servers?

**Comment by BenCodez** [comment]
It's gonna block players like Notch (unless they joined the server or are in the database.

**Comment by Platinteufel** [comment]
Okay, but it's not blocking unreal players like fnsenfiwsuenigs for me.

**Comment by BenCodez** [comment]
Took a second:
28.09 21:36:10 [Multicraft] Ben12345rocks ran command: av vote fnsenfiwsuenigs PMC
28.09 21:37:33 [Server] WARN [VotingPlugin] Player fnsenfiwsuenigs has not joined before, disregarding vote, set AllowUnjoined to true to prevent this

I'm guessing it's because its looking to see if the player has existed, and that takes time to lookup.

**Comment by Platinteufel** [comment]
I don't know what I'm doing wrong. Even if I type an invalid votesite it creates a new database entry. Maybe I should just go to bed.
Just to show you that I'm not crazy: https://youtu.be/JqRSv34j74s

**Comment by BenCodez** [comment]
Your on a test server right? 

Try clearing the plugin folder and trying again? My only guess is that the plugin thinks the value is true. Maybe yml error?

**Comment by Platinteufel** [comment]
Tested it on 3 different server and double checked the value, so my only guess was something about connection to something. I will test it again soon.

**Comment by BenCodez** [comment]
Works perfectly for me and everyone else. 

No yml errors? http://yaml-online-parser.appspot.com/

**Comment by Platinteufel** [comment]
I just deleted the VotingPlugin folder and regenerated it. I haven't touched the config after that and I absolutely don't get it to work anymore ..
Would you mind adding some debugging tests? I really don't know what's wrong.

**Comment by BenCodez** [comment]
Try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Well, it always tells me "UUID exists", even if my database is empty.
See: https://youtu.be/ERYrIGhCuN4

**Comment by BenCodez** [comment]
This should do it:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Unfortunately not, the only change I can see is that the debug message is gone, but it still let me type any name. :/

**Comment by BenCodez** [comment]
How's this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Boy you're awesome, I don't know what you have done, but it works again. Thank you! :)

**Comment by BenCodez** [comment]
Spent like an hour debugging is what I did :)

**Comment by Platinteufel** [comment]
Wow, thanks! If you need help testing things any time, just mark me here!
