### ISSUE TITLE
[Feature] Add chance rewards

### ISSUE THREAD

**Issue by maxlehot1234** [BenCodez/VotingPlugin#285]
I think it could be really nice ot add chance rewards.

Useful for voteparty for example.

Thank you so much :)

**Comment by BenCodez** [comment]
Already possible.

**Comment by maxlehot1234** [comment]
@Ben12345rocks How I can do it? Since I found nothing on the wiki :(

Thank you so much ;)

**Comment by BenCodez** [comment]
Everything you can do can be found in these 2 files in here:
https://github.com/Ben12345rocks/AdvancedCore/tree/master/AdvancedCore/Resources/Rewards

For a basic chance just add this:

    Chance: 20
    # 20% chance
