### ISSUE TITLE
Separate strings from config file, and need more strings translatable

### ISSUE THREAD

**Issue by lifehome** [BenCodez/VotingPlugin#287]
I suggest separating them to allow translators(like me :p) to dedicate more contribution reading and translating strings, not configuration files. Moreover, there are a few strings hardcoded in the plugin, leaving the translation injected to the java class overridden by each plugin update...

**Comment by BenCodez** [comment]
Got any specific examples what is hardcoded?

**Comment by lifehome** [comment]
I apologize for not leaving much details, as it is late night here in my timezone. And to explain the hardcoded strings, it turns out to be undocumented item attributions.

https://github.com/Ben12345rocks/VotingPlugin/blob/eac8078a65fc72a2cf2e94deb9dabbdbb8f30c6a/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/Commands/GUI/PlayerGUIs.java#L488-L493

For example, the `AllUrlsButton` in config file is really confusing, as it has zero description on it. Literally nowhere describing the use of the sub children of that configuration, and the use of `Name` to change the custom name attribution, not really much translator understands Java and do textual analysis. Further to these documentations, by separating these item names, lores, message strings to another file ensures the consistency of each language, and easy the updates afterward by appending new strings to language files, for translators to do their job.

**Comment by BenCodez** [comment]
The AllUrlsButton is for the GUI in /vote (the button that shows all urls). Not really sure what you mean by what problems your having. Don't really see any problem with what your talking, could also be misunderstanding what your saying.
