### ISSUE TITLE
/vote streak (player) & /vote best (player)

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#288]
/vote streak (player): 

- Every player has permission by default to also look for other players voting streaks
- It will create a database entry for every name you type for (player)

**Comment by Platinteufel** [comment]
**Edit:** Same with /vote best (player)

**Comment by BenCodez** [comment]
Here you go:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Should fix your other 2 issues.

**Comment by Platinteufel** [comment]
Thank you, fast as always! 👍 

- Enum Exception still happens: https://pastebin.com/6rfenPiZ
- Those red framed lines in the picture are still in `/vote help`, even players don't have the permission for that. Maybe they should just see commands there they have permissions for?

![unbenannt](https://user-images.githubusercontent.com/13700636/31057598-819456f0-a6e5-11e7-8abd-be258f1b9d14.PNG)

**Comment by BenCodez** [comment]
There is an option to only show stuff that have perms to, that enabled?
How's this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Just found this option
`# Require permission to see command in /v help or /av help`
`RequirePermission: true`
and yes, it's `true`

Enum Error is fixed, thanks :)

**Comment by Platinteufel** [comment]
Just tested this option, doesn't really seem to work. 

Just for your information: It's not possible to deny a player a specific permission, e.g. for `/vote next`. You need to deny him `VotingPlugin.Player` and allow the other permissions manually. 
Seems like you just have to have one of those two permissions in order to use the command:
`[21:00:33 INFO]: /vote Next : VotingPlugin.Commands.Vote.Next|VotingPlugin.Player`

It's **not** an issue for me, it was just a little bit confusing since I haven't seen this before. :)

**Comment by BenCodez** [comment]
Hmm. I'll need to look into that later.

**Comment by BenCodez** [comment]
Made a little change. See if that helps:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Uhm, better not this way .. 
https://pastebin.com/GcPqGrQ2

**Comment by BenCodez** [comment]
Well, here's a fix for that.
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
Hmm, there are still those commands in `/vote help` I don't have permission for, like `/vote Streak (player)`. (tested as normal player only with `VotingPlugin.player`)

**Comment by BenCodez** [comment]
This should fix that:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
No luck, now `vote help` is empty for normal players

**Comment by BenCodez** [comment]
Whoops... here:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Platinteufel** [comment]
That does the trick, thanks! :)
