### ISSUE TITLE
/vote SetRequestMethod (RequestMethod)

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#289]
`/vote SetRequestMethod (RequestMethod)` should not be free to use for every player I think?

**Comment by Platinteufel** [comment]
Also seems to throw an exception if the value is not in Enum
https://pastebin.com/x2FtSd3G

**Comment by BenCodez** [comment]
There is certain cases in which players might need to use it. (E.g. choice rewards, players need to choose a reward to get). Will fix that error.
