### ISSUE TITLE
Player help: Commands with (player) argument should not be shown here

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#290]
![unbenannt](https://user-images.githubusercontent.com/13700636/31051181-c99a918c-a661-11e7-9ba4-2e359a3740e4.PNG)

Players don't have the permission for the (player) argument (e.g. `/vote points (player)`), but they are all shown in player help.

**Comment by BenCodez** [comment]
Look at /av perms, you can see the permission for each command. 

Didn't think about the fact the this includes the player permission (so pretty much every command, whoops)

I'll need to change that.

**Comment by Platinteufel** [comment]
Thank you, fast as always! 👍 

- Enum Exception still happens: https://pastebin.com/6rfenPiZ
- Those red framed lines in the picture above are still in `/vote help`, even players don't have the permission for that. Maybe they should just see commands there they have permissions for?
