### ISSUE TITLE
Vote-Party: Perform background update onDayChange?

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#291]
![unbenannt](https://user-images.githubusercontent.com/13700636/31060355-8fdcde12-a712-11e7-8a73-e763ff6d17f7.png)

I just looked into `/vote today`. There were **7 players** that have voted since midnight, 5 of them shortly after midnight. 
Now I looked into `/vote party`. It shows **2 votes**, so it seems not to count those 5 that voted at midnight. Maybe a background update onDayChange would do the trick? Otherwise I will do some further tests. :)

**Comment by BenCodez** [comment]
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Done.

**Comment by Platinteufel** [comment]
Thank you!

**Comment by Platinteufel** [comment]
There are some players that voted at 00:00:15. Do you know if onDayChange happens at 00:00:00 or a little bit later?

**Comment by BenCodez** [comment]
It takes time to do the background update. But it should start in about 2 minutes:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0
Made a little change.

**Comment by Platinteufel** [comment]
Okay, thanks. :)
`/av ForceTimeChanged DAY` will trigger a day changed event I think? It seems to reset the VoteParty immediately, so I think it's just about when this event happens (exactly at midnight or a few seconds later).

**Comment by BenCodez** [comment]
Not exactly at midnight, within a few minutes of it.

**Comment by Platinteufel** [comment]
Okay, then that's the point why the votes at 00:00:15 were count for the "old" Vote-Party ^^
