### ISSUE TITLE
CrazyCrate keys

### ISSUE THREAD

**Issue by Zippers99** [BenCodez/VotingPlugin#297]
How would I put in reward file to give a crazycrate key?

**Comment by delbertina** [comment]
I believe it's as simple as the second code snip on [this page.](https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards)
`Console:
    - 'say %player%'`

Just replace the say command with [the command for the plugin you are using.](https://github.com/kicjow/Crazy-Crates/wiki/Commands-and-Permissions)
`CC Give <Physical/Virtual> <Crate> [Amount] [Player]`

Hope that helps :)

**Comment by BenCodez** [comment]
Rewards:
      Commands::
      - 'command'
