### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zed9K** [BenCodez/VotingPlugin#298]
Hello Ben,

I was using your Awesome VotingPlugin on my servers
one of my servers ( my SkyBlock server )
keep getting this error
what is the cause ?
https://hastebin.com/hipusexuri.sql

**Comment by BenCodez** [comment]
This help?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

I'm guessing you have an invalid player name somehow.
If that fixes it (or not) turn debug on and restart the server and send the log. (it should say who has a invalid name)

**Comment by BenCodez** [comment]
Any update?

**Comment by xXumarkuXx** [comment]
This actually helped me as i was having this same issue on a fresh test server. This jar worked for me, as i was using the latest version from spigot and it wouldn't load properly and only the config and votesites yml would load in and no commands would work.

**Comment by BenCodez** [comment]
Good to know.

**Comment by Zed9K** [comment]
@Ben12345rocks should i replace the VotingPlugin's jar with this one you listed ?

Sorry i was inactive for some reasons.

**Comment by BenCodez** [comment]
Latest version works.
