### ISSUE TITLE
VoteParty does not update

### ISSUE THREAD

**Issue by juhoooligan878** [BenCodez/VotingPlugin#300]
`Hi` Ben,
I'm currently having issues with the voteparty feature. It is enabled in the config, and required votes is 43.

> VoteParty:
  Enabled: enabled
  VotesRequired: 43
  GiveAllPlayers: false
  ResetEachDay: true
  CountFakeVotes: true
  UserVotesRequired: 3
  Broadcast: '&cReached the vote party amount!'
  Rewards:
    Commands:
      Console:
        - 'crate giveallkey VoteCrate 

Even with creating fake votes it does not seem to update. No error present in console- the ServerData.yml can be manually updated with votes for the VoteParty (that works).

**Comment by BenCodez** [comment]
Should be like this:

    Enabled: true

**Comment by juhoooligan878** [comment]
Oh, haha, apologises that seems like something obvious now. Thank you!
