### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by Lmmb74** [BenCodez/VotingPlugin#303]
Hello. I am getting [this](https://hastebin.com/jipamalevu.vbs) error on plugin startup, [this](https://hastebin.com/agajigewur.bash) error on command votegui execution, command which also does not display any gui, and [this](https://hastebin.com/inukawinuq.md) error on server stop.

I am using the a compilation of the following NuVotifier commit: https://github.com/NuVotifier/NuVotifier/commit/359b616a419d88336522dfd175fc5c27f1b915e7, Spigot 1.8.8, Vault 1.5.6 with TheNewEconomy 0.0.5.5 and VotingPlugin 5.10.5.

Thanks for any help in advance

**Comment by BenCodez** [comment]
Try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Lmmb74** [comment]
No errors at all. Thanks :D
