### ISSUE TITLE
Vote Party

### ISSUE THREAD

**Issue by Darkwaay** [BenCodez/VotingPlugin#305]
In wonder if you could see why my players dont get 1 votekey each when the "Vote Party" has reached 20. Is there another command for all players instead of %player%?
Like %allplayers% ?

This is the code:

VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 20
  # If true, players who did not vote to reach the votes required will 
  # recieve the reward
  GiveAllPlayers: true
  # If true, the vote count will reset each day
  ResetEachDay: true
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 0
  # Broadcast when vote party reached
  Broadcast: '&cReached the vote party amount, keys for everyone!'
  # Reward files to give
  Rewards:
      - 'cr givekey %player% VoteChest 1'

**Comment by BenCodez** [comment]
Rewards:
      Commands
      - 'cr givekey %player% VoteChest 1'
