### ISSUE TITLE
no longer getting rewards/diamond for voting

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#307]
I'm not sure if it was since I moved to using Waterfall Build 61 instead of BungeeCord Server, but I can access the voting GUI, click on a link to go vote, register the vote fine and come back into the game and have a thanks for voting message.  We don't see the rewards or the Inventory GUI appear when going to other servers in the network like we were previously.

That said, is Waterfall (1.12.2) Project supported instead of using BungeeCord?  This makes it possible to use Sponge Forge and allow both Spigot and Forge Servers talking to one another without needing to change the client Minecraft connections.

Thanks -Steve

**Comment by BenCodez** [comment]
Never tried waterfall, so no idea

**Comment by BenCodez** [comment]
It actually shouldn't matter what you use as bungeecoord, more about votifier. I'm guessing you had to reset votifier or something?

**Comment by smmmadden** [comment]
no change to Votifier and using VotingPlugin 5.10.6.  Still no awards of any kind.  Like I said earlier, I can type in /vote see the server to click on in the chat.  Click on the server and get directed there and vote.  Return to the game and I get the thank you for voting on xxxx.xxx.  What used to happen is I get the inventory popup almost immediately, sounds going off and showing the options for what I just did but that no longer happens.  I've been looking into possibly installing MySQL, but been trying to not go that route but may be inevitable.

Of course as soon as I vote and posted the above, I checked the console and I'm seeing "Invalid item section in site": CraftServers and MinecraftForum_net (twice each).  That's new and wasn't showing and also doesn't tell me which file and for what item. :-(

**Comment by BenCodez** [comment]
Show me your votesites.yml

On Nov 14, 2017 10:43 PM, "Steve Mekkelsen Madden" <notifications@github.com>
wrote:

no change to Votifier and using VotingPlugin 5.10.6. Still no awards of any
kind. Like I said earlier, I can type in /vote see the server to click on
in the chat. Click on the server and get directed there and vote. Return to
the game and I get the thank you for voting on xxxx.xxx. What used to
happen is I get the inventory popup almost immediately, sounds going off
and showing the options for what I just did but that no longer happens.
I've been looking into possibly installing MySQL, but been trying to not go
that route but may be inevitable.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/307#issuecomment-344477129>,
or mute the thread

**Comment by smmmadden** [comment]
https://pastebin.com/RLEeBtf7

**Comment by BenCodez** [comment]
You have no rewards set

**Comment by smmmadden** [comment]
Okay, so I do not know why it stopped working or what changed.  In any case, I tried this in the VoteSites.yml
    # List of reward files to give to voter
    Rewards:
    - 'ExampleReward'

And have mine shown as:
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
      - 'VoteSites_MinecraftForum_net_Rewards'
tried with and without the .yml extension.  The file exists in the Rewards folder.  The server isn't happy with the reference to it at all.
expected <block end>, but found BlockEntry in 'string', line 21, column 7;
- 'VoteSites_MinecraftForum_net_Rewards'

**Comment by smmmadden** [comment]
I managed to find a video of someone setting up this file but he removed the ExampleReward file reference and put in commands like the below and I did get that to work.
![image](https://user-images.githubusercontent.com/10309346/32874139-52d24d12-ca5e-11e7-9b26-60d32b62ce1e.png)
Though using the /av gui option, hovering over either of the voting server sites, says there is an invalid item for the site no matter what is added to it.  
![image](https://user-images.githubusercontent.com/10309346/32874161-770fc894-ca5e-11e7-8cf7-b2cc95a8c4db.png)

**Comment by BenCodez** [comment]
I he invalid item section doesn't refer to the rewards. You can look at the
default votesites.yml to see what you need

**Comment by smmmadden** [comment]
Hi Ben, I looked at the default votesites.yml and still don't see what line is not correct.  I can now vote and get money and messages shown in the console (audit trail) and in chat window using the votesites.yml to give the reward.  What I wanted to do though is reference the plugins\VotingPlugin\Rewards\VoteSites_CraftServers_Rewards.yml & ....\VoteSites_MinecraftForum_net_Rewards.yml but every time I add it nothing works using the syntax from wiki.
![image](https://user-images.githubusercontent.com/10309346/32980464-c21505a2-cc34-11e7-91ff-de952bf64a55.png)
So what would be great to work is, providing the initial reward as shown above, but also have the server specific reward file used and under EverySiteReward a pointer to another yml file to determine additional rewards.  Is that achievable here?

**Comment by BenCodez** [comment]
If you want to reference a reward file just do this:
  
    Rewards:
    - rewardfileName

This is what you are missing:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L38

**Comment by smmmadden** [comment]
Should that start in column 1, 3 or 5?  I think that's the problem.  I already have a Rewards: at column 5 under each sitename.  The file cannot load if I try to use - rewardfileName under the Rewards: at that level.  Perhaps I'm confusing myself? :-)

**Comment by BenCodez** [comment]
Look at this:
https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

**Comment by smmmadden** [comment]
That's the page I went to to get the commands/console/player settings which does appear to be working fine.  I think we're confusing multiple issues into one.  I'll create separate issues for them.  The original issue with not getting the reward is fixed, so let's close this one.
