### ISSUE TITLE
Votes not being spread across Bungee network correctly

### ISSUE THREAD

**Issue by serotonincrash** [BenCodez/VotingPlugin#309]
Contents of the network:
- Proxy
- Hub (not installed)
- Skyblock (gives vote reward VoteReward)
- Creative (gives vote reward VoteRewardCreative [this name is one of my attempts to fix it])
- Survival (not installed)
Storage is set to a MySQL database.
I have setup VotingPlugin such that offline voting is enabled (i.e vote on Skyblock and you'll receive rewards on Creative as well).
However, players that vote on Skyblock can simply relog (or connect to the hub and rejoin Skyblock) and they get their rewards again (and if they connect to creative after this they don't get their rewards there). 
If you have a solution to this and it's my error, I'll be happy to provide my config to help solve the issue.
Thanks!

**Comment by BenCodez** [comment]
Have the servers use different storage locations. And forward the vote to
all the servers you want

**Comment by serotonincrash** [comment]
Ah. I forgot to try that. I'll try and see if it's fixed.

**Comment by BenCodez** [comment]
Any update?
