### ISSUE TITLE
Including rewards file in VoteSites.yml not working

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#310]
My VoteSites.yml file has two voting servers, so they are listed as shown below and each has an immediate reward (a diamond and 100). - This is working for each voting site now.  What I'm trying to add is a rewards file reference for both voting servers (one each).

Which position do I add:
Rewards: 'VoteSites_CraftServers_Rewards'  - does the R in Rewards starting in column one, three or five?   The wiki pages doesn't state which column/location in the file the reference has to be made.
If I put it in column one like the below, wouldn't this apply to both voting servers?
![image](https://user-images.githubusercontent.com/10309346/32983994-adf91464-cc6b-11e7-99f4-54880f624023.png)
Since I already have a Rewards: section for each server, do I list it like this?  Because this causes and exception when reloading the file.
![image](https://user-images.githubusercontent.com/10309346/32984007-04eb41c0-cc6c-11e7-8460-d9922ca52c32.png)
The same is true if I move it two places to the left.
![image](https://user-images.githubusercontent.com/10309346/32984019-35e8ddf0-cc6c-11e7-843b-89eb9368de6d.png)

**Comment by BenCodez** [comment]
If use a reward file you have the put the commands and stuff in the reward file. Either directly define the rewards or use rewards files.

**Comment by smmmadden** [comment]
ah ha - so this is an either or scenario.  We can't do both.  Thanks :-)

**Comment by BenCodez** [comment]
Probably should make that more clear. I edited the wiki page.

**Comment by smmmadden** [comment]
Yes - this definitely worked now.  I commented out the rewards and changed it to:
Rewards: 'VoteSites_CraftServers_Rewards and reloaded.  The rewards file was used and now this is working again.  I just need to now replicate these changes to the other servers and be done. :-)  Thanks again for your patience and support, I do really appreciate it.  -Steve
