### ISSUE TITLE
av gui shows votesite with invalid item for site

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#311]
![image](https://user-images.githubusercontent.com/10309346/32984044-7f827cfa-cc6c-11e7-9c41-dc848e5ecf4c.png)

Everything appears to be working fine, so not sure why /av gui | VoteSites | CraftServers throws the above error.  I get the same for the other server as well.  The yaml file looks fine and VotingPlugin reloads okay.  I just don't know which item it is referring to or what is wrong with it.
![image](https://user-images.githubusercontent.com/10309346/32984063-e01b8ba6-cc6c-11e7-91db-d090bca148cc.png)

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L38

    VoteSites:
      Site1:
        Item:
          Material: 'DIAMOND'
          Amount: 1

**Comment by smmmadden** [comment]
got it - that works perfectly and no more invalid item.  Thanks!
