### ISSUE TITLE
Offline voting rewards (money)

### ISSUE THREAD

**Issue by RA3Unleashed** [BenCodez/VotingPlugin#313]
We've got the plugin set up to give money to players as follows:

`VoteSites:
  minecrafttrackerSite:
    Enabled: true
    Name: Minecraft Tracker
    Priority: 2
    ServiceSite: minecraft-tracker.com
    VoteURL: https://minecraft-tracker.com/server/5054/vote/
    VoteDelay: 24
    VoteDelayDaily: false
    GiveOffline: true
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Money: 20`

However, it doesn't seem to give players the money if they vote while not on the server. We've checked Vault and NUVotifer and can't find why this would be happening.

**Comment by BenCodez** [comment]
Set GiveOffline to false.

That gives the reward while the player is offline (aka not when he logs in)
