### ISSUE TITLE
Only enter player into the vote party when they have voted on all websites?

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#315]
Is there a way to do this? I don't want it to enter them into the voteparty when they have only voted on one website. Is there an option in the config or a command that I could use to do this?

**Comment by BenCodez** [comment]
Not right now. Don't really see why though.

**Comment by LogGits** [comment]
I am trying to set up rewards so that players who vote on all websites get entered into the vote party. This way people don't just vote on 1 website and get automatically entered into the vote party. The vote party on our server gives exclusive items and therefore we want to set it up so that only the players who have met the requirements (voting on all websites) get the rewards.

**Comment by BenCodez** [comment]
You can make it require a certain number of votes instead. The reason I don't have all votes requirement is because sometimes a site can fail to send or vote (happens quite a bit), so that's why I don't really think doing something like that is a good idea.

**Comment by LogGits** [comment]
That would be cool. How can i set that up? Also is there a way where i can make it so they need to vote on 3 specific sites to do one thing and 1 to do a seperate thing. total 4 vote links:
link1+link2+link3 = reward1
link4 = reward2
Would required link1+link2+link3 to get reward 1 if they do link2+link3+link4 they would only get reward 2. How could i set this up?

**Comment by BenCodez** [comment]
You can only require a certain number of votes

**Comment by LogGits** [comment]
similar to this, is there a way to reward for a number of votes? E.g. run a command on 3 votes and a different one on 4 votes?

**Comment by BenCodez** [comment]
Cumulative and milestones rewards

**Comment by BenCodez** [comment]
Any update on this?

**Comment by LogGits** [comment]
Yes I ended up getting this working thanks for your help :)
