### ISSUE TITLE
Vote Party Enhancement

### ISSUE THREAD

**Issue by Sikatsu** [BenCodez/VotingPlugin#318]
Could you add a start delay feature? And a delay message?

For example:

  start_delay: 10
  delay_message: ''The Vote Party will start in 10 seconds!''

This will allows players to switch to the right world before the vote party starts.

**Comment by BenCodez** [comment]
They can just get it when they switch.

**Comment by Sikatsu** [comment]
How exactly? If for example the player is in Creative world and the vote party starts, they will have the keys in Creative world instead of Survival?

**Comment by BenCodez** [comment]
Just set it so it only gives the reward in the survival world.

In the rewards have this

Worlds:
- Survival

You'll want checkonworldchange in the config to true as well.

**Comment by Sikatsu** [comment]
I don't use the rewards file. Just VoteSites.yml and Config.yml. 

Where exactly should I add Worlds: ?

And what happens if they are in creative while the vote party starts or when they vote? They will get the rewards as soon as they go back to survival?

**Comment by BenCodez** [comment]
Under the voteparty rewards.

If you set the rewards that way then yes.

**Comment by Sikatsu** [comment]
https://pastebin.com/QzArcRVj

Like this?

**Comment by BenCodez** [comment]
No idea if that will work since I can't see the formatting. But that is what you need to do.

**Comment by Sikatsu** [comment]
With formatting: http://prntscr.com/hkj1c9

**Comment by BenCodez** [comment]
Looks right

**Comment by Sikatsu** [comment]
While I don't get anything while i'm in the creative world, when I teleport back to the survival world I don't receive anything.

**Comment by Sikatsu** [comment]
It would be nice if it ''remembers'' and as soon as you go back to the survival world, the reward will still be given.

**Comment by BenCodez** [comment]
Set the checkonworldchange option to true like I said.

**Comment by Sikatsu** [comment]
I know, thats what I have.

**Comment by BenCodez** [comment]
Does it give it on relog?

**Comment by Sikatsu** [comment]
It doesn't give anything, the keys are basically lost if you are in creative.

**Comment by BenCodez** [comment]
This help?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Sikatsu** [comment]
Didn't update yet but found this error, might be related? https://pastebin.com/R5Tqekst

I'll test it now.

**Comment by Sikatsu** [comment]
The dropbox version works fine. 

Is there an option to get the same if the player would vote in the wrong world?

**Comment by Sikatsu** [comment]
Sometimes when a player logs in he gets like 2 or 3 times the vote party reward:

12.12 09:10:22 [Multicraft] FakeLuuk_NL ran command Message of the Day
12.12 09:10:22 [Server] INFO FakeLuuk_NL has recieved Vote2.
12.12 09:10:22 [Server] INFO FakeLuuk_NL has recieved Vote2.
12.12 09:10:22 [Server] INFO FakeLuuk_NL has recieved Vote2.

Not entirely sure how it counts this? With the previous plugin I used it would only be given to players that are online. Do all vote parties end up in a queue for offline players or something? o.o

**Comment by Sikatsu** [comment]
Sometimes even more. New bug perhaps?

12.12 09:32:38 [Multicraft] Morty1304 ran command Message of the Day

12.12 09:32:39 [Server] INFO Morty1304 has recieved Vote2.

12.12 09:32:39 [Server] INFO Morty1304 has recieved Vote2.

12.12 09:32:39 [Server] INFO Morty1304 has recieved Vote2.

12.12 09:32:39 [Server] INFO Morty1304 has recieved Vote2.

12.12 09:32:39 [Server] INFO Morty1304 has recieved Vote2.

12.12 09:32:39 [Server] INFO Morty1304 has recieved Vote2.

**Comment by BenCodez** [comment]
I'll do some testing on it later

**Comment by Sikatsu** [comment]
Thanks, it's a quite important matter.

**Comment by BenCodez** [comment]
I just had someone test it and it works fine for him...

You doing anything different?

**Comment by BenCodez** [comment]
This help?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Sikatsu** [comment]
I'm not doing anything different, you have my config files. I'll test.

**Comment by Sikatsu** [comment]
I see this: https://pastebin.com/LZ4DsuFW

**Comment by Sikatsu** [comment]
Still a player receives lots of vote party rewards somehow..
It should only give the reward to players that are online when the vote party happens.

12.12 23:07:34 [Multicraft] knetterzak ran command Message of the Day
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.

**Comment by BenCodez** [comment]
Turn debug on and send the log

On Dec 12, 2017 5:08 PM, "Sikatsu" <notifications@github.com> wrote:

Still a player receives lots of vote party rewards somehow..
It should only give the reward to players that are online when the vote
party happens.

12.12 23:07:34 [Multicraft] knetterzak ran command Message of the Day
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.
12.12 23:07:34 [Server] INFO knetterzak has recieved Vote2.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/318#issuecomment-351211069>,
or mute the thread

**Comment by Sikatsu** [comment]
It's hard to reproduce since it doesn't happen with every player.

It seems that if a vote party is triggered, it will be in a queue for offline players. As soon as they login, they will receive the rewards of all vote parties they missed in the meanwhile.

For some players it triggers it 3 times, others even higher. For me it just triggered twice. Not sure how I could reproduce this easily.

**Comment by BenCodez** [comment]
I just tested it and can't recreate it.
Maybe this will help:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Sikatsu** [comment]
Over the night I managed to get some debug on it.

https://pastebin.com/t1DGWvab

**Comment by Sikatsu** [comment]
Even with the latest jar it still happens: https://pastebin.com/BPpPEUZT

**Comment by BenCodez** [comment]
Hmm. Do you have multiple servers on the same database

**Comment by Sikatsu** [comment]
No it's just a spigot server.

**Comment by BenCodez** [comment]
How are you testing this? I can't recreate it

**Comment by Sikatsu** [comment]
I'm not testing this? It just happens with some players, I can't reproduce it on myself either. I just let it run over the night, I woke up with players reporting the issue again, I checked the latest.log and saw the issue is still there.

I believe this issue occured since some of the jars you sent here, not entirely sure.

**Comment by BenCodez** [comment]
Hmm. Is it always the same players? Does it work with the version on
spigot? Do /av report and send me the zip file in the reports folder

On Dec 13, 2017 5:00 AM, "Sikatsu" <notifications@github.com> wrote:

I'm not testing this? It just happens with some players, I can't reproduce
it on myself either. I just let it run over the night, I woke up with
players reporting the issue again, I checked the latest.log and saw the
issue is still there.

I believe this issue occured since some of the jars you sent here, not
entirely sure.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/318#issuecomment-351342424>,
or mute the thread

**Comment by Sikatsu** [comment]
I don't think it's always the same players. For the short while I used the version on spigot, this issue didn't seem to appear.

https://www.dropbox.com/s/nngl1uu5hfnwogp/Reports.1513159579095.zip?dl=0

**Comment by BenCodez** [comment]
Hmm okay. I'll do more testing when I can.

**Comment by Sikatsu** [comment]
Thanks.

**Comment by Sikatsu** [comment]
Just happened again: https://pastebin.com/jEzkSKLd

**Comment by Sikatsu** [comment]
I really hope you are able to solve this issue soon. Server is flooded with vote party keys now.

**Comment by BenCodez** [comment]
Try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Was able to recreate in a different way. I think its fixed.

**Comment by Sikatsu** [comment]
Updated. Guess I have to wait and see since I can't reproduce it myself. Since it's starting to become night not many players are online however.

**Comment by Sikatsu** [comment]
Issue I think.
This player received twice a vote party broadcast message, twice the message that he voted on all websites today and also twice the 5k bonus. 

 https://pastebin.com/i3zSumwL / http://prntscr.com/hn6k5b

**Comment by Sikatsu** [comment]
Also does it listen to the VoteParty rewards in config.yml or the one in the rewards folder? Those reward files confuse me all the time.

I've setup everything in config.yml and votesites.yml, but I also have reward files in the reward folder as seen here: http://prntscr.com/hn6mju

Same for the ''AllSites'' one, I set it up in the config.yml.

Can I delete the rewards folder perhaps? Or?

**Comment by Sikatsu** [comment]
Still happens: 

https://pastebin.com/02ngdd0H

**Comment by Sikatsu** [comment]
Alright I've setup a small test server to test this issue.

It seems if I vote and a vote party will start while i'm offline, I will receive all vote party rewards that i've missed while being offline. Not sure whether this is intended, but if I stay offline for long the vote party rewards will keep raising.

I would like to only give the vote party rewards to players that are online on the server.

Test: https://pastebin.com/gR6D5rXg

**Comment by BenCodez** [comment]
In the rewards add RewardType: ONLINE

**Comment by BenCodez** [comment]
It's probably still doing it since the rewards were set for offline.

**Comment by Sikatsu** [comment]
Seems to have fixed it.

**Comment by BenCodez** [comment]
I think the original issue was fixed. You had a majority of your players still with many vote party votes set to be given when they logged in (database was in the reports zip).

**Comment by BenCodez** [comment]
Actually, try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Run /av clearofflinerewards (Done from console)

See if setting rewardtype to BOTH and the issue still occours. It shouldn't. If you don't wanna test it its fine, just wanted to see if the issue was actually fixed.

**Comment by Sikatsu** [comment]
Updated, however i'm gonna have to go now for the weekend. Be back on monday.

**Comment by Sikatsu** [comment]
It still keeps spamming this at every vote party:

15.12 09:14:31 [Server] WARN Detected a reward file edited when it should be edited where directly defined, overriding

**Comment by BenCodez** [comment]
You do anything in the rewards folder?

**Comment by Sikatsu** [comment]
I added RewardType: Online in the VoteParty_Rewards.

However, later I added RewardType: Online in the config.yml within the rewards section and removed the VoteParty_Rewards within the rewards folder, let it regenerate, yet it still spams this error.

**Comment by BenCodez** [comment]
Wanna do /av report again? I'll take a look at it

On Dec 15, 2017 5:03 AM, "Sikatsu" <notifications@github.com> wrote:

I added RewardType: Online in the VoteParty_Rewards.

However, later I added RewardType: Online in the config.yml within the
rewards section and removed the VoteParty_Rewards within the rewards
folder, let it regenerate, yet it still spams this error.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/318#issuecomment-351965112>,
or mute the thread

**Comment by Sikatsu** [comment]
https://www.dropbox.com/s/s0bqmrs3me42yge/Reports.1513333468580.zip?dl=0

Have to go now though. Back on monday

**Comment by BenCodez** [comment]
This should fix it:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Sikatsu** [comment]
Players who never voted yet, do they receive the VoteParty? Because some players never voted yet and said they didn't receive the VoteParty either. But in console it says it has been given.

Also, the spam in the console is fixed.

**Comment by BenCodez** [comment]
They should if give all players is set to true

**Comment by Sikatsu** [comment]
They didn't, though

**Comment by BenCodez** [comment]
Turn debug and send the logs and your config

**Comment by BenCodez** [comment]
Any update on this?
