### ISSUE TITLE
Offline voting bug

### ISSUE THREAD

**Issue by Sikatsu** [BenCodez/VotingPlugin#320]
I've setup a 5,000 money bonus if you vote on all websites. 
If you vote while you are online you receive the bonus,
If you vote while you are offline you don't receive the bonus.

Example:

11.12 12:20:25 [Multicraft] Libertatia ran command Message of the Day
11.12 12:20:26 [Server] INFO CONSOLE issued server command: /eco give Libertatia 1000
11.12 12:20:26 [Server] INFO CONSOLE issued server command: /eco give Libertatia 1000
11.12 12:20:26 [Server] INFO CONSOLE issued server command: /eco give Libertatia 1000
11.12 12:20:26 [Server] INFO Libertatia has recieved Vote.
11.12 12:20:26 [Server] INFO €1.000,00 toegevoegd aan Libertatia zijn rekening. Nieuw saldo: €24.154,10
11.12 12:20:26 [Server] INFO Libertatia has recieved Vote.
11.12 12:20:26 [Server] INFO €1.000,00 toegevoegd aan Libertatia zijn rekening. Nieuw saldo: €25.154,10
11.12 12:20:26 [Server] INFO Libertatia has recieved Vote.
11.12 12:20:26 [Server] INFO €1.000,00 toegevoegd aan Libertatia zijn rekening. Nieuw saldo: €26.154,10

**Comment by Sikatsu** [comment]
# All vote rewards
# Reward for voting on all sites in one day
AllSites:
  Rewards:
    Commands:
      Console:
      - 'eco give %player% 5000'
    Messages:
      Player: '&3Je hebt op alle websites gevote vandaag!'

**Comment by BenCodez** [comment]
Pastebin your VoteSites.yml and Config.yml.

**Comment by Sikatsu** [comment]
VoteSites.yml: https://pastebin.com/BwYN1qLq

Config.yml: https://pastebin.com/LF4HTiqw

**Comment by BenCodez** [comment]
Did you vote on all sites to get the reward? Look at /vote next

**Comment by Sikatsu** [comment]
Ofcourse I did. All players are reporting, that if they vote offline they do not receive the bonus. If they are online while voting, it works fine.

**Comment by BenCodez** [comment]
Turn debug on and recreate it. Send the log of it happening

**Comment by Sikatsu** [comment]
Means I have to wait 24 hour before I can retry? o.o

**Comment by BenCodez** [comment]
You could /av vote

**Comment by Sikatsu** [comment]
Wasn't sure if that worked since I already voted.

Debug: https://pastebin.com/BKhtSLqH

**Comment by BenCodez** [comment]
Oh, I might know the issue. I'll have to fix it later

**Comment by Sikatsu** [comment]
Thanks

**Comment by BenCodez** [comment]
This fix it?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Sikatsu** [comment]
This issue is fixed.

**Comment by BenCodez** [comment]
Alright, Thanks for testing.

**Comment by Sikatsu** [comment]
@Ben12345rocks This issue appears to be back.

# All vote rewards
# Reward for voting on all sites in one day
AllSites:
  Rewards:
    Commands:
      Console:
      - 'eco give %player% 5000'
    Messages:
      Player: '&3Je hebt op alle websites gevote vandaag!'
    RewardType: BOTH

**Comment by BenCodez** [comment]
Are you on 5.12.4?

**Comment by Sikatsu** [comment]
When I reported it, 5.12.3, not sure if it's fixed in 5.12.4?

**Comment by BenCodez** [comment]
It's fixed in 5.12.4

**Comment by Sikatsu** [comment]
Ahh alright.
