### ISSUE TITLE
Adding more sites.

### ISSUE THREAD

**Issue by Thewhiteninja1** [BenCodez/VotingPlugin#323]
I've been trying but i can't seem to get more than one site I'm sure I'm doing it wrong could you help me?

**Comment by BenCodez** [comment]
VoteSites:
      Site1:
        [...]
      Site2:
        [...]

**Comment by Thewhiteninja1** [comment]
Thank you so just copy past and change it to site2??

**Comment by BenCodez** [comment]
Pretty much. Just make sure it's correctly formatted

**Comment by Thewhiteninja1** [comment]
Thanks man

**Comment by Thewhiteninja1** [comment]
VoteSites:
  Site1:
  # VoteSite name
  Minecraftservers:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true


so just like this then copy and change it to site2?

**Comment by BenCodez** [comment]
Pretty much
