### ISSUE TITLE
my player didnt get the reward

### ISSUE THREAD

**Issue by AkYamin** [BenCodez/VotingPlugin#324]
VoteSites:
  # VoteSite name
  Minecraft Mp:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'Minecraft MP'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com)
    ServiceSite: 'minecraft-mp.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'http://minecraft-mp.com/server/183025/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Reset vote delay each day (for certain sites that do this)
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (required ForceOffline to be true in the reward)
    GiveOffline: false
    
    # VoteSite Material for GUI's
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # List of reward files to give to voter
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 100'

  # VoteSite name
  Planet Minecraft:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'Planet Minecraft'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com)
    ServiceSite: 'planetminecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://www.planetminecraft.com/server/planetbn-4063728/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Reset vote delay each day (for certain sites that do this)
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (required ForceOffline to be true in the reward)
    GiveOffline: false
    
    # VoteSite Material for GUI's
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # List of reward files to give to voter
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 100'
    
# Reward for any site
# Similar to AnySiteReward
EverySiteReward: []

**Comment by BenCodez** [comment]
can you pastebin that?

**Comment by AkYamin** [comment]
https://pastebin.com/0gZqCudP

**Comment by BenCodez** [comment]
I can't see that pastebin

**Comment by AkYamin** [comment]
https://pastebin.com/ULDnCmns

**Comment by BenCodez** [comment]
You have VoteSites: twice

**Comment by AkYamin** [comment]
i try to reinstall and make new one but still doenst get the reward
https://pastebin.com/b8jmXaKs

**Comment by BenCodez** [comment]
Turn debug on and send the log when you vote

**Comment by AkYamin** [comment]
https://pastebin.com/99G9XNMa

**Comment by BenCodez** [comment]
If you tried voting then it looks like votifier isn't getting the vote.

**Comment by BenCodez** [comment]
Any update?
