### ISSUE TITLE
can't run reward command in GUI

### ISSUE THREAD

**Issue by bigyoor** [BenCodez/VotingPlugin#325]
**Hello,**

(sorry for my bad english)

First, I have to tell you that your plugin is awesome!

All the features are Okay but,
When i uncomment the lines to activate the reward command in GUI, the item appears in it but nothing happens on click.
(the command "/vote reward" works in tchat)

Do you have an idea that what is the problem ? there is an other option ta activate it ?

In the config file line 350 , the item display is named "rewards" and no"reward" , is the link is broken ? 
I've try to type "reward" instead , but it don't works too...

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L392

You have to configure that GUI yourself. It's not very good (That's why its commented out) Wouldn't recommend even having that. Might be better to code/make your own and have a item to open that.

**Comment by bigyoor** [comment]
thanks for your reply!

I probably did not express myself well
I don't have problems to configure the reward GUI itself, even if it's not very good xD

The problem is that the command "reward" don't runs when i click on the item displayed on the Main GUI. But the command works when typing it in chat.

**Comment by BenCodez** [comment]
Rewards:
      Item:
        Material: 'DIAMOND'
        Data: 0
        Amount: 1
        Name: '&4Voting Rewards'
      Slot: 7
      Command: 'vote reward'

try that. Guess I removed the code that automatically opens it

**Comment by bigyoor** [comment]
**It works perfectly!**

thanks a lot!
and have a good night! ;)
