### ISSUE TITLE
Large Frequent Error

### ISSUE THREAD

**Issue by Fluxty** [BenCodez/VotingPlugin#326]
We don't use the signs.  Spigot 1.8.8 with latest dev build of protocollib & latest VotingPlugin

https://hastebin.com/kuxujasucu.vbs

**Comment by BenCodez** [comment]
Are you using the right version for 1.8?

**Comment by Fluxty** [comment]
I do believe so, yes.

**Comment by BenCodez** [comment]
How's this?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Fluxty** [comment]
Unfortunately still seeing this, https://hastebin.com/awogogonub.coffeescript

**Comment by BenCodez** [comment]
Try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Made a typo.

**Comment by Fluxty** [comment]
We're now seeing this error when some people try to vote or use vote commands, maybe unrelated but definitely very problematic.

https://hastebin.com/ayegedokor.md

**Comment by BenCodez** [comment]
You must have an invalid uuid entry in your storage somewhere.

**Comment by Fluxty** [comment]
We just started up with this version today in one of our resets. I've deleted the database and still no luck. Almost nobody can get voting rewards atm.

**Comment by BenCodez** [comment]
Well, it looks like an invalid uuid in your storage. Somehow.

**Comment by Fluxty** [comment]
Also still getting this: https://hastebin.com/sayaderocu.coffeescript

This instance is running around 150-200 concurrent players

**Comment by BenCodez** [comment]
What version are you on?

**Comment by Fluxty** [comment]
1.8.8

**Comment by BenCodez** [comment]
Try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0
