### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by SeruhioX** [BenCodez/VotingPlugin#327]
I do not know if it is an error of this plugin or nuvotifier ...

The thing is that sometimes, this error appears and some user does not receive his vote

https://hastebin.com/zigohucutu.md

Thank you for your work

**Comment by BenCodez** [comment]
Try using SQLite or MySQL as your data storage option.

**Comment by SeruhioX** [comment]
I am using MYSQL

**Comment by BenCodez** [comment]
Can you /av report and send the zip file in the reports folder to me? I'll do some testing tomorrow.

**Comment by SeruhioX** [comment]
If I do that, the entire folder is saved in a zip file, including the password of my mysql, is that necessary or can I erase it?

**Comment by BenCodez** [comment]
Oh, just send me all your configs and erease the password

**Comment by SeruhioX** [comment]
[VotingPlugin.zip](https://github.com/Ben12345rocks/VotingPlugin/files/1595380/VotingPlugin.zip)

**Comment by BenCodez** [comment]
Use this as your serverdata.yml: https://pastebin.com/C5nKVrAQ

If the issue reappears try this version:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by SeruhioX** [comment]
I need a little time since it does not happen very often, moment does not seem to happen

Another thing that I would like to comment, and that is that I think it's "LeaderHeads", yesterday I updated it to the latest version and today "VotingPlugin" does not give many people their rewards, I also see certain errors in the log

https://hastebin.com/dewoluwaku.md

I do not know if I should report it to you or the author of "LeaderHeads"

**Comment by BenCodez** [comment]
Looks like it can't connect to the mysql database. Restart fix it? Or /av reload?

**Comment by SeruhioX** [comment]
"av reload" does not change anything, currently I can not restart the server since there are many people in it, tomorrow in the restart if it is solved I will inform you.

**Comment by BenCodez** [comment]
Something must of caused it to lose connection.

**Comment by SeruhioX** [comment]
I must have a jinx or something, today for some reason my users do not have permissions to execute the command /vote

I'm using LuckPerms, I've looked at what permission is and is non-existent, I leave the debug here.

https://gist.github.com/anonymous/56a71249cbbe0b99df6f7d09246456c9

I have also reported another error, although I think it is related to ChatControl

https://github.com/kangarko/ChatControl-Pro/issues/555

**Comment by BenCodez** [comment]
Are you using the version on spigot?

**Comment by SeruhioX** [comment]
No, I'm using the one you gave me a few days ago

**Comment by BenCodez** [comment]
Use the one spigot.

**Comment by BenCodez** [comment]
How this?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by SeruhioX** [comment]
Now the permissions work correctly, anyway the error of "ConcurrentModification" has not happened again.

Thank you for your time and I hope you continue just as incredible
