### ISSUE TITLE
Random Voting Reward - How it works?

### ISSUE THREAD

**Issue by Nikwitz** [BenCodez/VotingPlugin#329]
Hi there Ben12345rocks,
I'm using your plugin on a large community server and I want to know how to "enable", "configure" or setup the Random Pick reward system. I have been trying for a long time now and the only thing that works is the way all the items is giving at once.

https://hastebin.com/oxawemorey.bash - Here you can see my example of (VoteC.yml) one of my Reward Files and I only need that one thing to get it to work 100% as I wish. Can you help me? I would be gladly if you could make a new hastebin just with an example or something.

I have tried to move the Items: section up under Rewards: in Random: but still won't work.

Best Regards,
Mathias B. Christoffersen.

**Comment by BenCodez** [comment]
Quick example:
https://gist.github.com/Ben12345rocks/c913ba94878327c1a5bad69dd0c6de85#file-advancedchance-yml

You'll need to put the items in a separate reward file, not the one containing the random chances.

**Comment by Nikwitz** [comment]
Hi again,
I will try that! I thought you should put it all in one file, but I see where you are going with this. Is it possible to insert enchanted items or something into the rewardfile? When I try with the Random Reward it would not let me do that. Hopefully you can help me. :)

Thanks in advance,
Mathias B. Christoffersen.

**Comment by BenCodez** [comment]
Yeah you can, should be an example in one of the default reward files
