### ISSUE TITLE
[5.12] OnWorldChange issue

### ISSUE THREAD

**Issue by Sikatsu** [BenCodez/VotingPlugin#330]
On 5.11.1-BETA the issue was solved, but since 5.12 players do not receive their vote party keys when they switch to the survival world from creative. Did I miss something or is the issue back?

**Comment by BenCodez** [comment]
Turn debug on and send the logs when you test it.

**Comment by BenCodez** [comment]
Any update on this?

**Comment by Sikatsu** [comment]
Issue still persists, but i'm really busy + holiday so haven't been able to test yet.

**Comment by BenCodez** [comment]
5.11.1-BETA is the same as 5.12 (or mostly)

This do anything:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Send me your configs too.

**Comment by BenCodez** [comment]
It's working perfectly for me.

**Comment by BenCodez** [comment]
Let me know how it works on 5.12.1 (It works for me atleast)

**Comment by Sikatsu** [comment]
No-one reported this issue anymore ever since. However, it seems players that vote in the Creative world do not receive their keys. Must've forgotten the setting, but where should I put this?

**Comment by BenCodez** [comment]
Turn debug on and send the log while do a test vote. (and changing worlds)

**Comment by BenCodez** [comment]
Still a problem?

**Comment by Sikatsu** [comment]
I do not get reports anymore, haven't been able to test yet due to a busy schedule however.

**Comment by BenCodez** [comment]
Let me know whenever you have time

**Comment by BenCodez** [comment]
Reopen this if the issue exists.
