### ISSUE TITLE
Setting up multiple voting sites?

### ISSUE THREAD

**Issue by SaltedBiscuit** [BenCodez/VotingPlugin#331]
How would i set up multiple voting sites. i got the 1 site to work. but when i tried to add another line under it didnt do anything.
Mu config: 
VoteSites:
  # VoteSite name
  ExampleVoteSite:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'Server 1'
          
'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com)
    ServiceSite: 'minecraftlist.org'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://minecraftlist.org/vote/9480'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Reset vote delay each day (for certain sites that do this)
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline, NOT WHEN THE PLAYER IS OFFLINE
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      Commands:
      - 'say hello'
      - 'eco give {name} 100'
      Messages:
        Player: 'Thanks for voting!'
    
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by BenCodez** [comment]
The same way you do the first vote site. Send configs via pastebin, it's pretty much useless to just paste them on here.
