### ISSUE TITLE
Sponge / Forge version?

### ISSUE THREAD

**Issue by smmmadden** [BenCodez/VotingPlugin#335]
Hey Ben, was wondering if you have a Sponge or Forge version of the plugin?  I've got two Sponge Forge Servers that I'd love to add voting to it.  One is Pokecube Revival and the other Space Expedition 104.

Thanks,
Steve

**Comment by BenCodez** [comment]
None that I intend to make right now.

**Comment by smmmadden** [comment]
okay thanks for the quick reply :-)
