### ISSUE TITLE
UUID Issues

### ISSUE THREAD

**Issue by ashleyekm** [BenCodez/VotingPlugin#336]
Slightly different than other posted issue. All the votes were working fine today when the plugin was setup, then started erroring halfway through the day.

13.01 23:34:45 [Server] INFO CanadianCarly issued server command: /av reload
13.01 23:34:47 [Server] WARN java.lang.IllegalArgumentException: Invalid UUID string: 
13.01 23:34:47 [Server] WARN at java.util.UUID.fromString(UUID.java:194)
13.01 23:34:47 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.getPlayer(User.java:305)
13.01 23:34:47 [Server] WARN at com.Ben12345rocks.VotingPlugin.Objects.User.offVote(User.java:567)
13.01 23:34:47 [Server] WARN at com.Ben12345rocks.VotingPlugin.Main.update(Main.java:911)
13.01 23:34:47 [Server] WARN at com.Ben12345rocks.VotingPlugin.Main$2.run(Main.java:288)
13.01 23:34:47 [Server] WARN at java.util.TimerThread.mainLoop(Timer.java:555)
13.01 23:34:47 [Server] WARN at java.util.TimerThread.run(Timer.java:505)
13.01 23:34:47 [Server] INFO Looks like something went wrong.

As well as this UUID error: https://pastebin.com/LPGau883

**Comment by BenCodez** [comment]
Can I see your data storage? Is that using the version from the other
issue?

**Comment by ashleyekm** [comment]
I did try the other version and its still persisting. I deleted the database all together last night, a few people voted but then issue started up again.
I ended up switching to flatfile, and I think its working so far.

**Comment by BenCodez** [comment]
What were you using before?

**Comment by ashleyekm** [comment]
Sqlite

**Comment by BenCodez** [comment]
This should fix that:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0
