### ISSUE TITLE
useSSL=false

### ISSUE THREAD

**Issue by Artuto** [BenCodez/VotingPlugin#337]
Hi, I'd like to know if you could add a useSSL=false option to the config... Is annoying getting a lot of warns

_Sent from my LG K10 Power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BenCodez** [comment]
I'll add an option for it.

**Comment by BenCodez** [comment]
Here's the option:
https://github.com/Ben12345rocks/VotingPlugin/blob/5.12.1/VotingPlugin/Resources/Config.yml#L28

Untested.

https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Artuto** [comment]
Can confirm is working. You can close now 👍🏼

**Comment by BenCodez** [comment]
I'll leave it open until I release the version (It will auto close then)
