### ISSUE TITLE
Warn messages

### ISSUE THREAD

**Issue by Sikatsu** [BenCodez/VotingPlugin#338]
The plugin keeps warning me on every startup:

22.01 15:51:13 [Server] WARN No vote has been recieved from serverpact.nl, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
22.01 15:51:13 [Server] WARN No vote has been recieved from planetminecraft.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

The websites work fine, and nothing has changed. I'm assuming this is new since 1.12.1 update.

**Comment by BenCodez** [comment]
Probably not ignoring cases, noted.

**Comment by BenCodez** [comment]
How's this?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Sikatsu** [comment]
The issue was fixed.
