### ISSUE TITLE
Unbreakable Items in Vote Shop

### ISSUE THREAD

**Issue by tylerking** [BenCodez/VotingPlugin#344]
Hey there. I was setting up my vote shop and I didn't see an option to make an item unbreakable. Did I just miss this somewhere or is that feature missing? If its missing could you please add it? I have a lot of custom items that require it and I'd like to use those in my vote shop. Cheers.

**Comment by BenCodez** [comment]
Add Unbreakable: true in the item section.

You need this version too (Just added it):
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by tylerking** [comment]
That was fast. Thank you very much.

**Comment by BenCodez** [comment]
No problem

**Comment by tylerking** [comment]
So I tried that update and it doesn't seem to be working. Thoughts?

**Comment by BenCodez** [comment]
Show me what you have?

**Comment by BenCodez** [comment]
Actually try this:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by tylerking** [comment]
Hey. So this is what I have:

https://pastebin.com/raw/9WCj5CVB

I also just tried your update and now the plugin won't load and I'm getting this error:

https://pastebin.com/raw/gkPWb5wh

**Comment by BenCodez** [comment]
Any better?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by tylerking** [comment]
It loads now but no change. Here is a screenshot:

https://imgur.com/a/z470G

Since you are working on it might also be good to be able to hide attributes too.

**Comment by BenCodez** [comment]
You'll need to add the unbreakable in the rewards as well.

You can already hide attributes.

    ItemFlags:
    - FLAGHERE

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html

**Comment by tylerking** [comment]
Oh thanks. That item flags worked just fine but the item itself is still not "unbreakable" in the GUI. The rewards is also just a command reward so it doesn't need to be unbreakable. I just need the Vote Shop items to be unbreakable so my custom textures work.

**Comment by BenCodez** [comment]
Don't think setting an item as unbreakable will work to have a custom texture. (could be wrong) Try using an actual item section in the rewards to see if it makes it unbreakable.

**Comment by tylerking** [comment]
It does when you want to preserve the original items which I do. This guide explains how it works and its how I have mine setup:

https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/

Here are 2 items that are both a diamond_hoe:460 but the one on the left is unbreakable.

https://imgur.com/a/67ZsU

Also, I tried adding it to the rewards like you suggested an no change.

**Comment by BenCodez** [comment]
Try not having a data value.

**Comment by tylerking** [comment]
No change

**Comment by BenCodez** [comment]
Works fine for me.

          Material: DIAMOND_PICKAXE
          Amount: 1
          Unbreakable: true

**Comment by tylerking** [comment]
I used exactly what you just shared and still no change. Do you see the "Unbreakable" tag in the lore? This is what I get:

https://imgur.com/a/9VYxa

**Comment by BenCodez** [comment]
I got the unbreakable in the lore. Are you hiding it?

**Comment by tylerking** [comment]
Nope. I didn't hide any flags.

**Comment by tylerking** [comment]
I'm on PaperSpigot 1.12.2...not sure that's going to really matter but couldn't hurt to share.

**Comment by BenCodez** [comment]
Well, it works for me for whatever reason. Redownload the jar?

**Comment by tylerking** [comment]
Hah. Works now. I grabbed the latest immediately after you said "Any better?".

**Comment by BenCodez** [comment]
Its the same download link, maybe you downloaded an older version or something :P

**Comment by tylerking** [comment]
Yeah, it's the same download link where the source jar can only be updated by you. I downloaded a new copy immediately after you said "Any better?" so it's not my fault if the version wasn't up to par at that time. Anyway, I'm glad it works now either way. Thanks for making this update and working with me. Cheers.

**Comment by BenCodez** [comment]
No problem.
