### ISSUE TITLE
Need A Little Help

### ISSUE THREAD

**Issue by EnthusiastCraftr** [BenCodez/VotingPlugin#345]
Hello Ben

So I am using your VotePlugin. 
I am trying to add more then one voting site but its only showing one, and its not giving the rewards. 

Here is the Votingsites.yml file

VoteSites:
   # VoteSite name
   MineCraftVoting:
     # Enable voteSite
     # If false, votesite will not be loaded by plugin
     # Default: false
     Enabled: true

     # Display name of voting site
     Name: 'MineCraftServers'
     Name: 'CraftList'
     Name: 'MineCraftMP'
     Name: 'TopG'
     Name: 'MCServers'
     Name: 'MineServers'
     Name: 'MineTrack'
     Name: 'MineCraftServers'
     Name: 'MineCraftForum'
     # Priority of this site
     # Used for sorted list
     # High prority, higher on the list
     Priority: 5

     # The serviceName from the vote, has to be correct to work correctly
     # Gotten from voting on the site (will be in console/log)
     # Usually is the main part of the url(e.g. PlanetMinecraft.com)
     ServiceSite: 'https://minecraftservers.biz'
     ServiceSite: 'https://craft-list.net'
     ServiceSite: 'http://minecraft-mp.com'
     ServiceSite: 'https://topg.org'
     ServiceSite: 'https://mcserverstatus.com'
     ServiceSite: 'https://mineservers.com'
     ServiceSite: 'http://www.minetrack.net'
     ServiceSite: 'http://minecraftservers.org'
     ServiceSite: 'https://www.minecraftforum.net'

     # vote url for /vote
     # Format for this can be set in Format.yml
     # Do not include colors here
     VoteURL: 'https://minecraftservers.biz/servers/106073/'
     VoteURL: 'https://craft-list.net/minecraft-server/Enthusiast-Network-MC'
     VoteURL: 'http://minecraft-mp.com/server/187260/vote/'
     VoteURL: 'https://topg.org/Minecraft/in-484227'
     VoteURL: 'https://mcserverstatus.com/vote/35073'
     VoteURL: 'https://mineservers.com/server/YMXEsysL/vote'
     VoteURL: 'http://www.minetrack.net/vote/13613/'
     VoteURL: 'http://minecraftservers.org/server/481413'
     VoteURL: 'https://www.minecraftforum.net/servers/18555-enthusiast-network-mc/vote'

     # Time between votes in hours (used for /vote next)
     # Most sites are 24 hours
     VoteDelay: 24

     # Reset vote delay each day (for certain sites that do this)
     VoteDelayDaily: false

     # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
     # Setting this to true will execute the reward offline, NOT WHEN THE PLAYER IS OFFLINE
     # This basically disables offline voting if set to true, don't misinterpret this option
     ForceOffline: false

     # VoteSite Material for GUI's
     # Removing this may result in an error, required on each site
     Item:
       Material: 'DIAMOND'
       Amount: 1

     # Rewards to give
     # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
     Rewards:
       Commands:
         - 'eco give %player% 1500'
         - 'give %player% Diamond 5'

 # Reward for any site
 # Similar to AnySiteReward
 # This requires the site to be configured in order to get the reward.
 # EverySiteReward: []

Any help would be amazing

**Comment by BenCodez** [comment]
You need different sections

https://pastebin.com/Ez26UKqm

**Comment by EnthusiastCraftr** [comment]
Hi Ben, 

I am sorry I do not fully understand what you mean. 

Can you use my file as an example

**Comment by BenCodez** [comment]
Here's a quick example:
https://pastebin.com/GnB4qygr

**Comment by EnthusiastCraftr** [comment]
Hey Ben, 

It's only showing 4 Sites, and I have around 8..

VoteSites:
  MineCraftServers:
    Enabled: true
    ServiceSite: 'minecraftservers.biz'
    VoteURL: 'https://minecraftservers.biz/servers/106073/'
    Name: 'MineCraftServers'
    VoteDelay: 24
    Item:
      Material: 'GRASS'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Craft_List:
    Enabled: true
    ServiceSite: 'craft-list.net'
    VoteURL: 'https://craft-list.net/minecraft-server/Enthusiast-Network-MC'
    Name: 'CraftList'
    VoteDelay: 24
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  TopG_org:
    Enabled: true
    ServiceSite: 'TopG.org'
    VoteURL: 'https://topg.org/Minecraft/in-484227'
    Name: 'TopG'
    VoteDelay: 24
    Item:
      Material: 'REDSTONE'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Minecraft-MP:
    Enabled: true
    ServiceSite: 'Minecraft-MP.com'
    VoteURL: 'http://minecraft-mp.com/server/187260/vote/'
    Name: 'Minecraft-MP'
    VoteDelay: 24
    Item:
      Material: 'IRON'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MCServerStatus:
    Enabled: true
    ServiceSite: 'mcserverstatus.com'
    VoteURL: 'https://mcserverstatus.com/vote/35073'
    Name: 'MCServerStatus'
    VoteDelay: 24
    Item:
      Material: 'GOLD'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineServers:
    Enabled: true
    ServiceSite: 'mineservers.com'
    VoteURL: 'https://mineservers.com/server/YMXEsysL/vote'
    Name: 'MineServers'
    VoteDelay: 24
    Item:
      Material: 'WOOD'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineTrack:
    Enabled: true
    ServiceSite: 'minetrack.net'
    VoteURL: 'http://www.minetrack.net/vote/13613/'
    Name: 'MineTrack'
    VoteDelay: 24
    Item:
      Material: 'COAL'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineCraftServers:
    Enabled: true
    ServiceSite: 'http://minecraftservers.org'
    VoteURL: 'http://minecraftservers.org/server/481413'
    Name: 'MineCraftServers'
    VoteDelay: 24
    Item:
      Material: 'WOOL'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineCraftForum:
    Enabled: true
    ServiceSite: 'https://www.minecraftforum.net'
    VoteURL: 'https://www.minecraftforum.net/servers/18555-enthusiast-network-mc/vote'
    Name: 'MineCraftServers'
    VoteDelay: 24
    Item:
      Material: 'WOOL'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by EnthusiastCraftr** [comment]
Ben
Also not all sites are giving the Reward.
How Do I give money as well ...?

**Comment by BenCodez** [comment]
Can you pastebin that?

**Comment by BenCodez** [comment]
Just add a Money: 100 in the rewards to give money as well.

**Comment by EnthusiastCraftr** [comment]
Here you go ben
https://pastebin.com/NELG10Tu

**Comment by BenCodez** [comment]
You didn't space out a few of those sites.

**Comment by EnthusiastCraftr** [comment]
Sorry What do you mean by that Ben. 

"You didn't space out a few of those sites"

**Comment by BenCodez** [comment]
MCServerStatus:
    Enabled: true
    ServiceSite: 'mcserverstatus.com'
    VoteURL: 'https://mcserverstatus.com/vote/35073'
    Name: 'MCServerStatus'
    VoteDelay: 24
    Item:
      Material: 'GOLD'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineServers:
    Enabled: true
    ServiceSite: 'mineservers.com'
    VoteURL: 'https://mineservers.com/server/YMXEsysL/vote'
    Name: 'MineServers'
    VoteDelay: 24
    Item:
      Material: 'WOOD'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineTrack:
    Enabled: true
    ServiceSite: 'minetrack.net'
    VoteURL: 'http://www.minetrack.net/vote/13613/'
    Name: 'MineTrack'
    VoteDelay: 24
    Item:
      Material: 'COAL'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineCraftServers:
    Enabled: true
    ServiceSite: 'http://minecraftservers.org'
    VoteURL: 'http://minecraftservers.org/server/481413'
    Name: 'MineCraftServers'
    VoteDelay: 24
    Item:
      Material: 'WOOL'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
    MineCraftForum:
    Enabled: true
    ServiceSite: 'https://www.minecraftforum.net'
    VoteURL: 'https://www.minecraftforum.net/servers/18555-enthusiast-network-mc/vote'
    Name: 'MineCraftServers'
    VoteDelay: 24
    Item:
      Material: 'WOOL'
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 2
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

vs

    MineCraftServers:
      Enabled: true
      ServiceSite: 'minecraftservers.biz'
      VoteURL: 'https://minecraftservers.biz/servers/106073/'
      Name: 'MineCraftServers'
      VoteDelay: 24
      Item:
        Material: 'GRASS'
        Amount: 1
      Rewards:
        Items:
          Diamond:
            Material: 'DIAMOND'
            Amount: 2
        Messages:
          Player: '&aThanks for voting on %ServiceSite%!'
    Craft_List:
      Enabled: true
      ServiceSite: 'craft-list.net'
      VoteURL: 'https://craft-list.net/minecraft-server/Enthusiast-Network-MC'
      Name: 'CraftList'
      VoteDelay: 24
      Item:
        Material: 'DIAMOND'
        Amount: 1
      Rewards:
        Items:
          Diamond:
            Material: 'DIAMOND'
            Amount: 2
        Messages:
          Player: '&aThanks for voting on %ServiceSite%!'
    TopG_org:
      Enabled: true
      ServiceSite: 'TopG.org'
      VoteURL: 'https://topg.org/Minecraft/in-484227'
      Name: 'TopG'
      VoteDelay: 24
      Item:
        Material: 'REDSTONE'
        Amount: 1
      Rewards:
        Items:
          Diamond:
            Material: 'DIAMOND'
            Amount: 2
        Messages:
          Player: '&aThanks for voting on %ServiceSite%!'
    Minecraft-MP:
      Enabled: true
      ServiceSite: 'Minecraft-MP.com'
      VoteURL: 'http://minecraft-mp.com/server/187260/vote/'
      Name: 'Minecraft-MP'
      VoteDelay: 24
      Item:
        Material: 'IRON'
        Amount: 1
      Rewards:
        Items:
          Diamond:
            Material: 'DIAMOND'
            Amount: 2
        Messages:
          Player: '&aThanks for voting on %ServiceSite%!'

**Comment by EnthusiastCraftr** [comment]
Hi Ben, 

I tried to do what you said and still nothing is Working.. 
They can vote but dont get rewards. 

VoteSites:
  MineCraftServers:
    Enabled: true
    ServiceSite: https://minecraftservers.biz
    VoteURL: https://minecraftservers.biz/servers/106073/
    Name: MineCraftServers
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Craft_List:
    Enabled: true
    ServiceSite: https://craft-list.net
    VoteURL: https://craft-list.net/minecraft-server/Enthusiast-Network-MC
    Name: CraftList
    VoteDelay: 24
    Item:
      Material: WOOD
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  TopG_org:
    Enabled: true
    ServiceSite: https://topg.org
    VoteURL: https://topg.org/Minecraft/in-484227
    Name: TopG
    VoteDelay: 24
    Item:
      Material: COAL
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineCraftMP:
    Enabled: true
    ServiceSite: http://minecraft-mp.com
    VoteURL: http://minecraft-mp.com/server/187260/vote/
    Name: MineCraftMP
    VoteDelay: 24
    Item:
      Material: GOLD
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MCServerStatus:
    Enabled: true
    ServiceSite: https://mcserverstatus.com
    VoteURL: https://mcserverstatus.com/vote/35073
    Name: MCServerStatus
    VoteDelay: 24
    Item:
      Material: IRON
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineServers:
    Enabled: true
    ServiceSite: https://mineservers.com
    VoteURL: https://mineservers.com/server/YMXEsysL/vote
    Name: MineServers
    VoteDelay: 24
    Item:
      Material: GOLD
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineTrack:
    Enabled: true
    ServiceSite: http://www.minetrack.net
    VoteURL: http://www.minetrack.net/vote/13613/
    Name: MineTrack
    VoteDelay: 24
    Item:
      Material: EMERALD
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineCraftServers:
    Enabled: true
    ServiceSite: http://minecraftservers.org
    VoteURL: http://minecraftservers.org/server/481413
    Name: MineCraftServers
    VoteDelay: 24
    Item:
      Material: EMERALD
      Amount: 1
    Rewards:
      Items:
        Diamond:
          Material: DIAMOND
          Amount: 2
          Money: 1500
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by EnthusiastCraftr** [comment]
The Spacing is there just not on this thing

**Comment by BenCodez** [comment]
paste bin it.

**Comment by EnthusiastCraftr** [comment]
https://pastebin.com/FPAaZxzp

**Comment by BenCodez** [comment]
Now you need to have the correct service sites. Vote on them and see in console for the service site.

**Comment by EnthusiastCraftr** [comment]
Nothing Should In Game
No Rewards
I do not understand why this wont work

**Comment by BenCodez** [comment]
Then it's probably an votifier issue. There will be something in console if you get a vote and it will tell you if you need to change the service site.

**Comment by EnthusiastCraftr** [comment]
I am using NuVotifier
I set the port
I have the Public key set right
I do not understand

**Comment by BenCodez** [comment]
Port already taken? If you don't get the vote on the server then you have a votifier issue.

**Comment by EnthusiastCraftr** [comment]
Okay So now I have Changed ports 

Now it says this, After I had updated all websites with new port 

04.02 20:29:41 [Server] ERROR Unable to process vote from /52.44.191.1:51698
04.02 20:29:43 [Server] ERROR Unable to process vote from /52.44.191.1:51699
04.02 20:29:56 [Server] INFO CONSOLE issued server command: /list 
04.02 20:29:56 [Server] INFO Admins: [Admin]  Elmusic0, [Owner]  EnthusiastCraftr
04.02 20:30:23 [Multicraft] Updating config permissions.yml: True, Config file updated.
04.02 20:30:33 [Server] INFO Elmusic0 issued server command: /vote
04.02 20:30:44 [Server] INFO CONSOLE issued server command: /list 
04.02 20:30:44 [Server] INFO Admins: [Admin]  Elmusic0, [Owner]  EnthusiastCraftr
04.02 20:30:59 [Server] ERROR Unable to process vote from /192.99.101.31:56648

**Comment by BenCodez** [comment]
Probably the wrong key or something

**Comment by EnthusiastCraftr** [comment]
OKay, 

So I have changed the Key, Port,

player only got 2 diamonds from one vote but no diamonds from other votes and no money...

Can you please help me fix this.

**Comment by BenCodez** [comment]
Service sites correct?

**Comment by EnthusiastCraftr** [comment]
Yes Ben,
Everything is Set Correctly.
I do not understand why you're giving me the Runaround.
I just want the plugin to work

**Comment by BenCodez** [comment]
Okay, is the vote getting processed? Are you getting them?
Are there messages in console?

**Comment by EnthusiastCraftr** [comment]
Ben, 
Vote Links are correct.
Port Number Is Correct
VotingSites Yml is correct according to what you should me

Some votes go through but they do not give the Rewards. Each vote should give the player two diamonds and 1500 cash. It only gave me 2 diamonds, no cash and no extra diamonds.. 

What is wrong...!

**Comment by BenCodez** [comment]
Configs? And startup log?

**Comment by EnthusiastCraftr** [comment]
For Which ?

**Comment by BenCodez** [comment]
Votesites.yml

**Comment by EnthusiastCraftr** [comment]
Votifer Config: https://pastebin.com/JLr0Gd4Y
Votingsites YML: https://pastebin.com/1GXDxkfE
VotingPLugin Config: https://pastebin.com/vw71SXwr

**Comment by EnthusiastCraftr** [comment]
We Are actually think about giving Crate Keys Instead. 

So if you can let me know how to give them a crate ket instead of Diamonds and money that would be more helpful

**Comment by BenCodez** [comment]
Startup log?

**Comment by EnthusiastCraftr** [comment]
Where Do I find this? 
I mean like I have given so much info so

**Comment by EnthusiastCraftr** [comment]
I am getting this Ben
05.02 18:34:11 [Server] ERROR Unable to process vote from /209.90.232.167:61514
05.02 18:34:16 [Server] ERROR Unable to process vote from /209.90.232.167:61936
05.02 18:34:22 [Server] ERROR Unable to process vote from /209.90.232.167:62324
05.02 18:34:46 [Server] INFO CONSOLE issued server command: /list 
05.02 18:35:00 [Multicraft] Auto-saving world...
05.02 18:35:00 [Server] INFO Saving is already turned on
05.02 18:35:00 [Server] INFO Saving...
05.02 18:35:00 [Server] INFO World saved.
05.02 18:35:34 [Server] INFO CONSOLE issued server command: /list 
05.02 18:35:56 [Server] INFO UUID of player EnthusiastCraftr is 0ce59ad3-8cb5-41c8-aa77-3e3dcd4cab53
05.02 18:35:57 [Connect] User EnthusiastCraftr, IP 198.84.169.205
05.02 18:35:57 [Multicraft] EnthusiastCraftr ran command Message of the Day
05.02 18:36:22 [Server] INFO CONSOLE issued server command: /list 
05.02 18:36:22 [Server] INFO Admins: [Owner]  ~TheCrafter
05.02 18:37:10 [Server] INFO CONSOLE issued server command: /list 
05.02 18:37:10 [Server] INFO Admins: [Owner]  ~TheCrafter
05.02 18:37:57 [Server] INFO CONSOLE issued server command: /list 
05.02 18:37:57 [Server] INFO Admins: [Owner]  ~TheCrafter
05.02 18:38:45 [Server] INFO CONSOLE issued server command: /list 
05.02 18:38:45 [Server] INFO Admins: [Owner]  ~TheCrafter
05.02 18:39:25 [Server] ERROR Unable to process vote from /54.36.121.219:56824
05.02 18:39:30 [Server] ERROR Unable to process vote from /54.36.121.219:56889
05.02 18:39:33 [Server] INFO CONSOLE issued server command: /list 
05.02 18:39:33 [Server] INFO Admins: [Owner]  ~TheCrafter
05.02 18:40:00 [Multicraft] Server ran command Admin Say
05.02 18:40:00 [Multicraft] Server ran command Admin Say
05.02 18:40:12 [Server] INFO CrazyCrates: 1.7.4.4 now available.
05.02 18:40:20 [Server] ERROR Unable to process vote from /212.83.133.63:58113
05.02 18:40:21 [Server] INFO CONSOLE issued server command: /list 
05.02 18:40:21 [Server] INFO Admins: [Owner]  ~TheCrafter
05.02 18:40:26 [Server] ERROR Unable to process vote from /212.83.133.63:58241
05.02 18:40:31 [Server] ERROR Unable to process vote from /212.83.133.63:58342

**Comment by EnthusiastCraftr** [comment]
05.02 18:41:00 [Server] ERROR Unable to process vote from /54.36.121.219:57379
05.02 18:41:08 [Server] ERROR Unable to process vote from /212.83.133.63:58788

**Comment by BenCodez** [comment]
1. ServiceSite: https://minecraftservers.biz - I ususally don't see service sites with https://
2. 05.02 18:41:08 [Server] ERROR Unable to process vote from /212.83.133.63:58788 - Turn debug on in nuvotifier.
3. For crate keys just execute a command to give the key
4.

     Rewards:
       Items:
         Diamond:
           Material: DIAMOND
           Amount: 2
           Money: 1500

Money is in the wrong spot, should be directly under Rewards (2 spaces in)

**Comment by EnthusiastCraftr** [comment]
Making Progress the vote registered in for MineCraftServers_org

It did not give me the Crate Key reward 

  Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Items:
        VoteKey:
          /cc give p Vote (player) 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by EnthusiastCraftr** [comment]
Ben,

I did it just how you have above players are still not getting the Vote Crate Key

VoteSites:
  MineCraftServers:
    Enabled: true
    ServiceSite: http://minecraftservers.biz
    VoteURL: https://minecraftservers.biz/servers/106073/
    Name: MineCraftServers
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Craft_List:
    Enabled: true
    ServiceSite: http://craft-list.net
    VoteURL: https://craft-list.net/minecraft-server/Enthusiast-Network-MC
    Name: CraftList
    VoteDelay: 24
    Item:
      Material: WOOD
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  TopG_org:
    Enabled: true
    ServiceSite: http://topg.org
    VoteURL: https://topg.org/Minecraft/in-484227
    Name: TopG
    VoteDelay: 24
    Item:
      Material: COAL
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineCraftMP:
    Enabled: true
    ServiceSite: http://minecraft-mp.com
    VoteURL: http://minecraft-mp.com/server/187260/vote/
    Name: MineCraftMP
    VoteDelay: 24
    Item:
      Material: GOLD
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MCServerStatus:
    Enabled: true
    ServiceSite: http://mcserverstatus.com
    VoteURL: https://mcserverstatus.com/vote/35073
    Name: MCServerStatus
    VoteDelay: 24
    Item:
      Material: IRON
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineServers:
    Enabled: true
    ServiceSite: http://mineservers.com
    VoteURL: https://mineservers.com/server/YMXEsysL/vote
    Name: MineServers
    VoteDelay: 24
    Item:
      Material: GOLD
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineTrack:
    Enabled: true
    ServiceSite: http://www.minetrack.net
    VoteURL: http://www.minetrack.net/vote/13613/
    Name: MineTrack
    VoteDelay: 24
    Item:
      Material: EMERALD
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MineCraftServers:
    Enabled: true
    ServiceSite: http://minecraftservers.org
    VoteURL: http://minecraftservers.org/server/481413
    Name: MineCraftServers
    VoteDelay: 24
    Item:
      Material: EMERALD
      Amount: 1
    Rewards:
      Commands:
      - cc give p Vote %player% 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by BenCodez** [comment]
Pastebin it. It's pretty much useless sending it like that.

**Comment by EnthusiastCraftr** [comment]
https://pastebin.com/Dfq928r9

**Comment by BenCodez** [comment]
That looks correct, just fix your service sites.

**Comment by EnthusiastCraftr** [comment]
Sorry What do you mean fix Services sites????

**Comment by BenCodez** [comment]
You don't have the correct service sites, votes won't work unless you have the correct service sites.

See /av servicesites to see all the ones the plugin knows about.

**Comment by EnthusiastCraftr** [comment]
MineCraftServers.org
MineCraft-MP.com
MineTrack.net
MCServerStatus

MCTools not sure how to remove it
MineServers.com
Craft-list.net
Topg.org
MinecraftForum - but says No Sites with this Service Site

**Comment by BenCodez** [comment]
Then set to the service sites to what it says here?

**Comment by EnthusiastCraftr** [comment]
How do I remove Old Ones

**Comment by BenCodez** [comment]
Just replace the text?

**Comment by EnthusiastCraftr** [comment]
Okay so here is what the File Looks Like Now 
https://pastebin.com/TDaN4jPC

I will have a member test it

**Comment by BenCodez** [comment]
Don't think you change a single service site. 

    ServiceSite: http://minecraftservers.org

**Comment by EnthusiastCraftr** [comment]
I changed them All, to the correct address

**Comment by BenCodez** [comment]
http://minecraftservers.org != MineCraftServers.org

**Comment by EnthusiastCraftr** [comment]
This plugin is the Worst to config.
It seems like you need to be a coder to make it work
I have Followed Everything you have Said. 

It seems you can't give me a single answer that I can fully understand.. 

What Is Wrong With MineCraftServers.org

**Comment by BenCodez** [comment]
YOU CAN"T HAVE THE HTTP://

Not sure how much clearer I can be.

**Comment by EnthusiastCraftr** [comment]
Ben, 

Still players are not receiving the keys
or money. 

Can you please help me fix this so it works. 

https://pastebin.com/KxDbL194

**Comment by EnthusiastCraftr** [comment]
Also now the sites are not even showing

**Comment by BenCodez** [comment]
One command needs to be spaced one from the -, hard to show you on my phone

**Comment by FunsMcFuns** [comment]
my players disconnect every time they vote any idea? i tried turning on debug and nothing
except no uuid found for minecraft server .org

**Comment by BenCodez** [comment]
@FunsMcFuns Start a new issue.
