### ISSUE TITLE
Console Error and Plugin Wont Load

### ISSUE THREAD

**Issue by tylerking** [BenCodez/VotingPlugin#347]
Hey. So I'm getting this error on startup now and the plugin won't load:

https://pastebin.com/raw/r0nPCcnX

So a few things happened. I updated my vote sites on my lobby server and reloaded the plugin and it all worked fine. Then I copied what I did in the Lobby servers VoteSites.yml file and pasted it into another servers VoteSites.yml and went to reload the plugin and it stalled. I then restarted the server and that error showed up. I tried everything I could think of to fix it like checking to make sure the file permissions were on point and make sure the formatting was right but its still happening.

Any ideas?

**Comment by BenCodez** [comment]
Redownload the jar?

**Comment by tylerking** [comment]
Well, I updated all my servers just yesterday with the latest update you released and everything worked fine then too. I tried re-downloading the jar anyway and there is still no change.

**Comment by BenCodez** [comment]
Yeah no idea.

**Comment by tylerking** [comment]
Ok well, are you going to take a look at it?

**Comment by BenCodez** [comment]
"Another plugin on your server is incorrectly shading an old version of HikariCI"

A 10 second google

**Comment by tylerking** [comment]
Ok but the error is coming from your plugin alone and only happened after I took those steps. It is also running fine on my other servers with Luckperms.

**Comment by BenCodez** [comment]
Using a different version? Another plugin with HikariCI? Just because it comes from my plugin doesn't mean its on my end (could still be though, but unlikely)

**Comment by tylerking** [comment]
Ok. I'm going to remove all the MySQL plugins and put them back one by one and report back. Hopefully, its that simple and I'll find the culprit.

**Comment by tylerking** [comment]
Ok. It seems that LogBlock is the culprit here. Everything works fine without it installed.

**Comment by BenCodez** [comment]
I never use LogBlock. Interesting.

**Comment by tylerking** [comment]
Yeah, I wanted to give it a try over CoreProtect because it works with the Watson mod so I found a current build of it here:

https://ci.md-5.net/

It's not crucial I have it so I'll just remove it for now. Thanks for your time as always.

**Comment by BenCodez** [comment]
The latest version on there uses the same version that I use.

**Comment by tylerking** [comment]
Its a mystery
