### ISSUE TITLE
Stopped working after update?

### ISSUE THREAD

**Issue by j-Daddy** [BenCodez/VotingPlugin#348]
Updated plugin and now when entering the command to vote it doesn't respond.

Anyone else with this issue and any ideas why this is happening?

**Comment by BenCodez** [comment]
Redownload the jar? You're the only one who has this issue that I know of

**Comment by j-Daddy** [comment]
I re-downloaded and installed the jar, but no change. 

The main issue seems to be the /vote command to get the GUI menu.

Commands like /vote party and /vote best work okay.

Thanks.

**Comment by BenCodez** [comment]
Turn debug on and send the logs on startup

**Comment by j-Daddy** [comment]
I ended up copying the main configs settings, deleted then reinstalled the plugin.

- When I reinstalled a fresh copy of the latest version, I had the same issue.

- When I reinstalled it back to the previous version, everything worked fine.

Thanks

**Comment by BenCodez** [comment]
Why did you close it? Problem solved?
