### ISSUE TITLE
Milestone Question

### ISSUE THREAD

**Issue by tylerking** [BenCodez/VotingPlugin#349]
Hello again. I have a question about Milestone Rewards. So I have 8 servers setup with Milestone rewards that just rankup the player via a command in a particular track. Currently, once they reach a milestone those rewards get repeated on every server they join. Is there a way to prevent this from happening so that once they reach that milestone on 1 server it doesn't repeat it when they join another?

**Comment by BenCodez** [comment]
Just don't have the milestones on the other servers? Permissions?

**Comment by tylerking** [comment]
Ak ok. That simple enough. Take care.
