### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by NeedHelperino1** [BenCodez/VotingPlugin#351]
I'm trying to add the reward of $25 for every vote, but I'm doing something wrong.
https://pastebin.com/vvWMVhJ8
I also tried adding a chance to players depending on their rank/permission. Also went terrible
https://pastebin.com/pggAMDRW
Can you help me out?

**Comment by BenCodez** [comment]
EverySiteRewards:
      Commands:
      - 'say %player%'

To do the reward file with permission and chance (I hope thats a reward file?). You need to list the reward.
Rewards:
- RewardFileNames

**Comment by NeedHelperino1** [comment]
I have made 6 reward files called Rewards1,Rewards2 etc. I'm trying to set it up so players with a better rank have more chances of getting crates. I've pasted one of my reward files as I did previously, to show you how i've writen it. 
https://pastebin.com/yreqJYBb
Reward1 text 

Require Permission: true
Permission: 'AdvancedCore.Reward.Member'
Chance: 5
Commands:
- '&asay %player% was lucky and got a &6LootCrate Ticket &a!'
- 'crate key %player% Member 1

**Comment by NeedHelperino1** [comment]
Here's the book of errors it wrote :P 
https://pastebin.com/LWgnLp9X

**Comment by BenCodez** [comment]
You forgot a ' at the end of the crate command.

**Comment by NeedHelperino1** [comment]
What about the Votesites.yml ? I'm pretty sure there's an issue with that too.

**Comment by BenCodez** [comment]
Paste it in here and find out. Read the error to see where the problem is.
http://yaml-online-parser.appspot.com/

**Comment by NeedHelperino1** [comment]
I've edited my Votesites.yml, still doesn't work. Could you please tell me what's the issue? I've been trying to set this up for 2 days now..It no longer gives me any errors in the console, just won't give me the $25 you're suppost to get from each vote site neither do the chances of lootcrates work

**Comment by BenCodez** [comment]
The issue was in the reward file that you sent me.

**Comment by NeedHelperino1** [comment]
Require Permission: true
Permission: 'AdvancedCore.Reward.Member'
Chance: 5
Commands:
- '&asay %player% was lucky and got a &6LootCrate Ticket &a!'
- 'crate key %player% Member 1'
It's just these 4 lines, what do I need to change? Sorry about all this :/

**Comment by BenCodez** [comment]
'crate key %player% Member 1

You were missing a ', but that's no longer the case. What do the errors still say?

**Comment by NeedHelperino1** [comment]
https://pastebin.com/HGhxc1sQ this is one the reward files 
I'm getting no errors at all in console

**Comment by NeedHelperino1** [comment]
Also noticed that in the reward files this has been added automatically "

eco_give_%player%_25.yml
--

"

**Comment by BenCodez** [comment]
You must of messed up listing the rewards.

This is a command?
&asay

**Comment by NeedHelperino1** [comment]
I've fixed the command, that was stupid of me :P Still not working tho..
https://pastebin.com/uvqckmHJ This is what the reward file looks like now

**Comment by BenCodez** [comment]
Wanna send the VoteSites.yml?

**Comment by NeedHelperino1** [comment]
https://pastebin.com/URFFk3aB

**Comment by BenCodez** [comment]
EverySiteReward not EverySiteRewards

**Comment by NeedHelperino1** [comment]
Much better! Only small issue now is that the colourcodes didn't work

**Comment by BenCodez** [comment]
Don't think it works with /say.

**Comment by NeedHelperino1** [comment]
Oh I see, one last thing - in the Votesites.yml, If I want to disable the message a player is getting.
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
I just remove all the text from Rewards to ServiceSite?

**Comment by BenCodez** [comment]
Just set it to

    Rewards: []

**Comment by NeedHelperino1** [comment]
Thanks a ton for all the help! Going to give you 5 stars asap!

**Comment by NeedHelperino1** [comment]
Um I'm encountering another issue.. It's giving these chances too everyone even though they don't have the permission. This is my permissionsEx : https://pastebin.com/5c4QezEF 
I really can't understand what the problem is this time

**Comment by BenCodez** [comment]
No space for require permission

**Comment by NeedHelperino1** [comment]
What? You mean instead of - AdvancedCore.Reward.Member to put -AdvancedCore.Reward.Member ?

**Comment by NeedHelperino1** [comment]
Really need to get this up and running :/

**Comment by BenCodez** [comment]
RequirePermission: true

You had a space in there.

**Comment by NeedHelperino1** [comment]
What? :O 
# E.g: AdvancedCore.Reward.ExampleReward
RequirePermission: false
You've put a space there too? ^^

**Comment by BenCodez** [comment]
You have this:

    Require Permission: true

**Comment by NeedHelperino1** [comment]
Fixed that, still the same though..

**Comment by NeedHelperino1** [comment]
Hasn't solved the issue, will still give me permissions to all of the rewards even with Member rank (and of-course no op)

**Comment by BenCodez** [comment]
Try this:
https://pastebin.com/FRkNJEyz

You'll need to list the rewards in order. It will go through the rewards and give the first one the player has permission to. It also counts for chances.

**Comment by NeedHelperino1** [comment]
Hallelujah! Goodnight sir!

**Comment by NeedHelperino1** [comment]
I honestly just changes the intervals for some sites and reloaded, and now it's not working..It will give me the in-game money, just not the rewards..I tested both the config and the rewards with yaml and they have no mistakes.
VotingSites https://pastebin.com/d4V22pDm
One of the rewards (they are all pretty much the same) https://pastebin.com/tV9MqnHN

**Comment by BenCodez** [comment]
Any errors? Server restart?

**Comment by NeedHelperino1** [comment]
I haven't tried restarting yet. Shall I try restarting with the VotingSites config I sent you or this one? ->
I also tried this https://pastebin.com/k80kJBkb but it doesn't work either - in fact it doesn't even give me the $25

**Comment by BenCodez** [comment]
Its EverySiteReward, not rewards.

**Comment by NeedHelperino1** [comment]
huh one the first config it wouldn't work even though it was EverySiteReward. Second config worked fine though, thanks

**Comment by NeedHelperino1** [comment]
Everything seems to be working fine but I'm having these errors in console. 
15.02 19:29:11 [Server] WARN No rewards detected for the site: MinecraftForum_net. See https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards on how to add rewards
15.02 19:29:11 [Server] WARN No rewards detected for the site: MinecraftServers_org. See https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards on how to add rewards
15.02 19:29:11 [Server] WARN No rewards detected for the site: MCSL. See https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards on how to add rewards
15.02 19:29:11 [Server] WARN No rewards detected for the site: TopG_org. See https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards on how to add rewards
15.02 19:29:11 [Server] WARN No rewards detected for the site: Minecraft-MP_com. See https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards on how to add rewards
15.02 19:29:11 [Server] WARN No rewards detected for the site: PlanetMinecraft_com. See https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards on how to add rewards
15.02 19:29:11 [Server] INFO Enabled VotingPlugin 5.12.5
15.02 19:29:11 [Server] INFO Enabling VotingPlugin v5.12.5

**Comment by BenCodez** [comment]
Just ignore that then. Didn't add a check for every site reward.

**Comment by NeedHelperino1** [comment]
what? Can you just tell me how to fix this slight issue? :)

**Comment by BenCodez** [comment]
If everything works then just ignore it.
