### ISSUE TITLE
Need a bit of help pls

### ISSUE THREAD

**Issue by j-Daddy** [BenCodez/VotingPlugin#353]
First can I say everything is working great after the update a couple of days ago. It automatically fixed the issue I was experiencing.

I want to use the players skull as an item in the GUI menu, but cant seem to work out the 'Material' I need to use for your plugin.

eg:
      Item:
        Material: 'head; %Player_Name%'
        Data: 0
        Amount: 1

What would I need to use instead of 'head; %Player_Name%' in the eg above?

TIA.

**Comment by BenCodez** [comment]
I think its skull or something as the material and add this:

    Skull: '%player%'

**Comment by j-Daddy** [comment]
It says in your configs:
        # You can set skulls of the player using the following
        # Remove the # to enable
        #Skull: '%Player%'
I tried: Skull: '%Player%' and a lot of others, but I cant get it to work.
Anymore suggestions?

**Comment by BenCodez** [comment]
Did you have the correct material?

**Comment by j-Daddy** [comment]
Not sure what you mean, isn't  Skull: '%Player%' a material?

**Comment by BenCodez** [comment]
That's not the material. You put that under it.
