### ISSUE TITLE
Streak Broken Reward

### ISSUE THREAD

**Issue by AndrewB6** [BenCodez/VotingPlugin#355]
Hello,

I would like to set up a voting reward where I have some form of "regular voter" rank in which basically if a player has voted on at least 4 of the last 5 days (across 5 sites, ideally it would require 20 votes) they get this rank, but they lose the rank if they have voted less than 20 times in the past 5 days. I think I can use the streak system for this, but I'm not sure how to remove the rank when the streak is broken, or how I can allow people to miss a day without breaking the streak.
Any help would be appreciated.

Thanks,

Andrew

**Comment by BenCodez** [comment]
That's s little hard to do. Not sure if its possible

**Comment by BenCodez** [comment]
Don't think I will implement this, as it possible to accidently trigger a time change and break the streaks.
