### ISSUE TITLE
VoteParty rewards

### ISSUE THREAD

**Issue by Sikatsu** [BenCodez/VotingPlugin#358]
For some reason not every player receives VoteParty rewards when they are online.

**Comment by BenCodez** [comment]
Config?

**Comment by Sikatsu** [comment]
This is my config: https://pastebin.com/LSBWK1mf

Around 80% of the online players receive the VoteParty without issues, a couple of them do not receive anything. I've been able to confirm the issue by checking the latest.log and compare it with the online player names.

**Comment by BenCodez** [comment]
Worlds:
    - world
    - world_nether
    - world_the_end
    RewardType: ONLINE

This might be the cause.
Because of the reward type online it will discard the worlds (if they are in a different world). By best guess right now.

**Comment by Sikatsu** [comment]
That's because I don't want players that are offline to receive the
voteparty rewards. Only the players that are online. They should receive
the key in the main worlds, if for example they happen to be in a different
one it should give the key as soon as they switch to one of the main worlds.

Op ma 26 feb. 2018 22:44 schreef Ben <notifications@github.com>:

**Comment by BenCodez** [comment]
The reward type being online would cause the reward to not be given if not in the correct world.
Guess you could do something like this (I think this works):

    Rewards:
      RewardType: ONLINE
      Rewards:
        Worlds:
        - world
        # Othe rewards here

**Comment by Sikatsu** [comment]
Kinda got myself confused, my worlds are actually called world2 now instead of world since last week. Seems I forgot to change it within the config, yet i'd still wonder why it works for 80% but not fot everyone?

I'll try your setting tomorrow and see if that improves anything.

Will it give the key as soon as they switch to the survival world? And only for players that were online at that time?

**Comment by BenCodez** [comment]
Yes and yes.

**Comment by Sikatsu** [comment]
Like this? https://pastebin.com/4iAVgUsz

**Comment by BenCodez** [comment]
That should work.

**Comment by Sikatsu** [comment]
Seems to work fine. How could I achieve the same with the normal votes? So that they also receive the key once they switch to the survival world?

**Comment by BenCodez** [comment]
Same thing? Depends on if you want the online to count as well.

**Comment by Sikatsu** [comment]
Where exactly? Config.yml or VoteSites.yml?

**Comment by BenCodez** [comment]
Probably the votesites.yml

**Comment by Sikatsu** [comment]
Like this? https://pastebin.com/edpsX2t7

**Comment by BenCodez** [comment]
Should work.

**Comment by Sikatsu** [comment]
Thanks.
