### ISSUE TITLE
Lagg spike

### ISSUE THREAD

**Issue by Sikatsu** [BenCodez/VotingPlugin#359]
Server had a lagg spike, see some VotingPlugin traces.

https://pastebin.com/waFgTGCB

**Comment by BenCodez** [comment]
What commands were you doing at the time?

**Comment by Sikatsu** [comment]
Don't think I did any command?

Op ma 26 feb. 2018 22:42 schreef Ben <notifications@github.com>:

**Comment by BenCodez** [comment]
Looks like it was trying to get a skull or something. Would need more info to know for sure.

**Comment by Sikatsu** [comment]
First time it happened. Hard to give any more info for now.

Op ma 26 feb. 2018 23:06 schreef Ben <notifications@github.com>:

**Comment by BenCodez** [comment]
Let me know if it happens again. First time I've seen that.
