### ISSUE TITLE
Error stacktrace on player vote

### ISSUE THREAD

**Issue by aljaxus** [BenCodez/VotingPlugin#362]
Hello I am getting this error when any offline player votes.
https://hastebin.com/abecovogor.rb

Server version: 1.12.1 - paper
Plugin version: VotingPlugin version 5.12.4

Is there any know reason why this is happening? 

Thank you for any info in advance ^-^

Regards,
~Lazos

**Comment by BenCodez** [comment]
v5.12.4

Update :)

**Comment by aljaxus** [comment]
Ummm.... 

> Plugin version: VotingPlugin version 5.12.4

**Comment by BenCodez** [comment]
Latest is 5.12.6

**Comment by aljaxus** [comment]
Oh that's what you meant.

Pretty sure i've downloaded it already, just did not update yet 

Thanks !
