### ISSUE TITLE
[Feature] Add MVDW Placeholders support

### ISSUE THREAD

**Issue by maxlehot1234** [BenCodez/VotingPlugin#366]
Hi, is it possible for you to hook directly into featherboard for palceholders?

I try to get placeholdersAPI placeholders to work with featherboard and I get this:
![image](https://user-images.githubusercontent.com/5159244/37251146-7792fc82-24e0-11e8-8444-e154dfd9b5f4.png)

I try this:
{placeholderapi_VotingPlugin_Total_All}
{placeholderapi_VotingPlugin_VotePartyVotesCurrent}

Thanks again and have a nice day/night

**Comment by BenCodez** [comment]
Just use the placeholder api placeholders

**Comment by maxlehot1234** [comment]
It doesn't work into featherboard.. That's what I used :(

**Comment by BenCodez** [comment]
Talk with the developer then. I can't do anything on my end.
