### ISSUE TITLE
VoteGUI blank

### ISSUE THREAD

**Issue by poolcool2** [BenCodez/VotingPlugin#367]
I was editing the config file to make voting more rewarding and interesting, after a lot of editing I tried reloading the plugin. When I used /votegui everything was gone, the entire menu was blank. I went through the config undoing every change I made testing it after each undo, nothing worked, when I used /av ServiceSites it says "PlanetMinecraft.com : no site with this service site, did you do something wrong?"

![image](https://user-images.githubusercontent.com/17607921/37252838-b7716370-24e5-11e8-82b6-4551d0f252b3.png)

[VoteSites.txt](https://github.com/Ben12345rocks/VotingPlugin/files/1800272/VoteSites.txt)
[Config.txt](https://github.com/Ben12345rocks/VotingPlugin/files/1800273/Config.txt)

**Comment by BenCodez** [comment]
You probably have a yml error, check that.

**Comment by poolcool2** [comment]
It says the yml files could not be loaded, but it doesn't say why so I don't know how to fix it.
![image](https://user-images.githubusercontent.com/17607921/37257323-74476816-2525-11e8-8aec-59d522a55120.png)

**Comment by BenCodez** [comment]
Paste it in here: http://yaml-online-parser.appspot.com/

It will tell you what's wrong.

**Comment by poolcool2** [comment]
turns out the problem was entirely my fault, I forgot to unquote a quote, when I fixed that it worked fine for a bit, then after doing the same fix to the votesites.yml, my server said it was not a valid plugin, manually redownloading it fixed that problem, now it works just fine and has all the changes I made.

**Comment by BenCodez** [comment]
That's usually the case with yml errors
