### ISSUE TITLE
Able to Pull Items from Vote GUI

### ISSUE THREAD

**Issue by MCTyler** [BenCodez/VotingPlugin#369]
Hi, I just did a test vote on one of my Alts, offline, and when the Player logged on the Gui with the clocks came up. The Player was able to grab the items and put into his inventory. See Pic Below. MC Version 1.12.2
![2018-03-13_05 36 21](https://user-images.githubusercontent.com/6390898/37336993-0bcdb814-2681-11e8-9e4a-ceeaa8045b10.png)

**Comment by MCTyler** [comment]
I confirmed this bug with another Alt....
![2018-03-13_06 51 59](https://user-images.githubusercontent.com/6390898/37340286-9c681658-268b-11e8-8f63-67f3c8a75bf2.png)

**Comment by BenCodez** [comment]
Latest plugin version?

**Comment by MCTyler** [comment]
Yes Sir, Downloaded it from Spigot Last Night.

**Comment by BenCodez** [comment]
Turn debug on and send the logs when you use the gui

**Comment by MCTyler** [comment]
Not really a big deal as those items are cheap. Just wanted to report it.

**Comment by MCTyler** [comment]
You can close if you don't think its important.

**Comment by BenCodez** [comment]
So far your the only person who reported any issue with this. Do other
gui's work?

**Comment by MCTyler** [comment]
yea the Gui's Work fine that just happens when I did a fake offline vote and then I logged in. I was just testing a vote site and rewards.

**Comment by BenCodez** [comment]
I'll test it out later

**Comment by BenCodez** [comment]
Can't seem to recreate it. Might be a plugin conflict somewhere.

**Comment by BenCodez** [comment]
Did you end up fining the problem?

**Comment by MCTyler** [comment]
No, could of been client lag or anything, who knows. Since only I have reported it.....Please never add anything like a NetherStar to that Gui-Menu!
