### ISSUE TITLE
Duplicate Entry

### ISSUE THREAD

**Issue by tylerking** [BenCodez/VotingPlugin#370]
Hey there. I've been seeing this error in the console every now and then:

https://pastebin.com/raw/VY7PKR5p

Do you know what might be causing it?

**Comment by BenCodez** [comment]
Are you using the latest version?

**Comment by tylerking** [comment]
I wasn't when I reported this but I did update everything about 2 hours ago. Is this something you fixed in the latest version?

**Comment by BenCodez** [comment]
No, but it was a bug a long time ago

**Comment by tylerking** [comment]
This was from the previous version, 5.12.6.

**Comment by BenCodez** [comment]
Latest version do anything?

**Comment by tylerking** [comment]
Not yet but its only been running the latest version for a short while and its late so I'll have to report tomorrow when more people are joining.

**Comment by BenCodez** [comment]
Let me know if happens again

**Comment by tylerking** [comment]
Will do. Thank you.

**Comment by tylerking** [comment]
Alright, so it happened again: https://pastebin.com/raw/ew6H0Xnu

**Comment by BenCodez** [comment]
How the plugin setup? Multiple servers on the same database?

**Comment by BenCodez** [comment]
I sort of silenced the error in the latest build here, it also gives a few more details of the query.:
http://ben12345rocks.com/job/VotingPlugin/

Also tried a few fixes. See if it helps.

**Comment by tylerking** [comment]
K. I'll report back.

**Comment by tylerking** [comment]
Unfortunately still happening:

https://pastebin.com/raw/ghuKATAQ

**Comment by BenCodez** [comment]
Do you have multiple servers on the same database?

**Comment by tylerking** [comment]
Yes...its a Bungeecord network.

**Comment by BenCodez** [comment]
That might do it, is there a way to recreate it?

**Comment by BenCodez** [comment]
Latest version help?

**Comment by tylerking** [comment]
Ok. I've kept an eye on it and the error has yet to reappear over the last few weeks.

**Comment by BenCodez** [comment]
Alright, I think I made some changes and made the error silent as well, since it shouldn't effect anything.
