### ISSUE TITLE
VotingPlugin Shop Question

### ISSUE THREAD

**Issue by ProfCube** [BenCodez/VotingPlugin#371]
I know this is not an issue but could not find in the Wiki about the Vote Shop in the plugin more information so i currently am trying to set up the shop for the Plugin VotingPlugin and dont seem see how to add a command on to it.
this is currently what i have:
[Voting Plugin GUI SHOP](https://hastebin.com/weduxusomu.pl)

**Comment by BenCodez** [comment]
It's commands, not command
