### ISSUE TITLE
Setting daily reset hour

### ISSUE THREAD

**Issue by Segysmundo** [BenCodez/VotingPlugin#372]
Hi, could you add an option to set the hour at which the day starts? We are using minecraft-mp as our voting site which has a time difference of -6 hours with us and people can abuse the difference in time to vote more than once in 1 day.

For example:

If a user in our server votes at 05:00 on February 1, it will still be 23:00 of January 31 on the vote site. And when it's 06:00 on our server, people will be able to vote again since on the vote site now it's 00:00 of February 1, a new day, and it lets them vote again.

So in our server it's February 1 but the user has 2 votes while the rest that voted after 06:00 only have 1 vote.

If you have a look at the top monthly voters for march, you can see 1 user used this method to obtain 17 votes when we're still at day 16.
![f301a58b6fd199b53eaa3d016c47fffe](https://user-images.githubusercontent.com/19178945/37542358-33f16ad6-295e-11e8-847d-538462376991.png)

**Comment by BenCodez** [comment]
It's based on the servers time zone. It's not that easy to add an option to specify what hour. It would be possible to switch what timezone the plugin uses though, that might work. Let me know if that would work too.

**Comment by Segysmundo** [comment]
Yes, if we could set the timezone to -6 hours it would work prefectly.

**Comment by Segysmundo** [comment]
Well or specify the timezone yeh.

**Comment by BenCodez** [comment]
Latest build here adds it:
http://ben12345rocks.com/job/VotingPlugin/

Just add TimeZone: 'TimeZone'

Untested.

**Comment by Segysmundo** [comment]
Btw where on the plugin can I check what time it is for the plugin?

Any specific command?

**Comment by BenCodez** [comment]
There isn't any way. Just when it changes day

**Comment by BenCodez** [comment]
Turn debug on and you'll see a message when it resets. The time should be the time of the timezone

**Comment by Segysmundo** [comment]
So I added **TimeZone: EST** to the config.
 
If I now set my server's time to 23:59 and vote then wait for 00:01 and vote again, it should still count as 2 votes in 1 day for the plugin right? Since for the plugin its still 6 hours early.

**Comment by BenCodez** [comment]
In theory. I haven't tested it yet, so no idea. If you have debug on you'll get a message in console when the day switches.

**Comment by Segysmundo** [comment]
Sure let me check it out real quick.

**Comment by Segysmundo** [comment]
Btw on the vote gui where it shows last vote, it shows the time when you voted for the server's time zone right?

**Comment by Segysmundo** [comment]
I just checked and after passing the 00:00 time mark it changed month when we're still on day 16-17

**Comment by BenCodez** [comment]
The last vote goes by server time.

Changed month? Did you touch the ServerData.yml?

**Comment by Segysmundo** [comment]
Nope, I simply started the jar with a freshly generated votinplugin folder.

Added the TimeZone: EST line.

And before starting the server I set the server's time to 16/03/18 23:58:00

When the day changed to 17/03/18 it announced a new month.

**Comment by BenCodez** [comment]
What does ServerData.yml contain?

**Comment by Segysmundo** [comment]
![e3fc4bece02ab85032fcf8a11f6c01f2](https://user-images.githubusercontent.com/19178945/37546550-93bc01e2-296d-11e8-8810-5f5b623bbdd3.png)

**Comment by BenCodez** [comment]
Looks fine to me. Are you sure the month changed?

**Comment by Segysmundo** [comment]
![318528227662756f6b79eacd7d1f073c](https://user-images.githubusercontent.com/19178945/37546710-5d630b1c-296e-11e8-9df4-b1820b6650d0.png)

Maybe the month didn't pass? I assumed it did from this message that showed up after the day passed.

**Comment by BenCodez** [comment]
Turn debug on and in console, you'll get a message in console when day/month changes. Don't think the month changed, but no idea without more info.

**Comment by Segysmundo** [comment]
Alright I started fresh again.

Generated new folder.
Toggled debug.
Added line **TimeZone: EST**
Set server time to 23:58:00
Started server

This is the entire votingplugin log from the moment I join and vote.
https://pastebin.com/wMjm6h4M

I noticed it says EST timezone doesn't exist.

**Comment by BenCodez** [comment]
Try one of these names:
https://www.mkyong.com/java8/java-display-all-zoneid-and-its-utc-offset/

I should also mention that it doesn't change day right at the mark. It's a few minutes off from it (whenever the timer checks it)

**Comment by BenCodez** [comment]
Decided to try this:
TimeHourOffSet: 0

Replaces the timezone thing.

can go from -18 to 18

Try it out.

http://ben12345rocks.com/job/VotingPlugin/

**Comment by Segysmundo** [comment]
Does the same, but we just type in numbers instead of the actual offsets?

**Comment by BenCodez** [comment]
Pretty much.

**Comment by BenCodez** [comment]
Let me know how it works out.

**Comment by Segysmundo** [comment]
Unfortunately I can't check it out this night, I'm testing out something and need the server to be online and without restarts until  8 am.

I'll be sure to give it a try tomorrow though.

**Comment by BenCodez** [comment]
No rush. Just let me know whenever.

**Comment by Segysmundo** [comment]
Btw I just noticed on https://www.mkyong.com/java8/java-display-all-zoneid-and-its-utc-offset/ if you want to set an offset of UTC -5 the  id would be **ETC/GMT +5** which uses +5.

With your change of -18 to 18, do the negative numbers like -5 equate to UTC -5 or do they invert like the ones above?

**Comment by BenCodez** [comment]
Not really sure

**Comment by Segysmundo** [comment]
**TimeHourOffSet** doesn't seem to work, set the offset to -9 but still started a new day at 00:03.

**Comment by BenCodez** [comment]
Latest build now?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Segysmundo** [comment]
Using latest build, set **TimeHourOffSet: -3**

Just to make sure, I waited from 20:00 until 04:00, I got no new day message on any of those hours, including my server's 00:00.

I also set **DelayBetweenUpdates: 1**   but the time between background updates seems to be way longer, on the console the updates seemed to show up every 10 mins or so(didn't check the exact delay time). But according to the config it should appear every 1 minute.

**Comment by BenCodez** [comment]
I'll have to do more testing then

**Comment by BenCodez** [comment]
DelayBetweenUpdates doesn't control the background check for time, it was at 5 minutes, it should now be at 2.

http://ben12345rocks.com/job/VotingPlugin/

Turn debug on. It should say the hour and minute every 2 minutes.

**Comment by Segysmundo** [comment]
It works prefectly now, the debug showing the offset time is really helpful too.

As a side suggestion I'd like to know if this could be done as an improvement to the top voter rewards.

I'm assuming the plugin ranks top voters setting nº1 top voter to the user that voted the earliest that day?

So if I set monthly awards for the top 10 voters at the end of the month it will always choose the 10 guys that voted for example at 00:01 on day 1 of the month?

I think a nice alternative would be that at the end of the month the plugin should get all the players with the highest amount of votes that month, for example; 42 users obtained 31 votes. Then roll a random number from 0.01 to 100 for each of them, then the _**X**_ number of players that obtained the highest roll are rewarded with the top voter awards. 

_**X**_ being the number of users we want to reward in the config (similar to how it's donde atm).

 _**X**_ = 10 , if I only wanted 10 users rewarded out of the 42 that had 31 votes.

At the end of the month if  **_**X**_ **_<_** _nº users with 31 votes_** I guess it should directly reward all the users that got 31 votes and then do a random number roll for the users with 30 votes and reward _**Y**_ users with the highest rolls.

Where _**Y**_ = **_X_** - nº users with 31 votes


I'm sorry if I complicated it too much, you don't need to add it if it's too much work haha.

**Comment by BenCodez** [comment]
Basiclly reward a certain portain of top voters with a random reward essentially?

**Comment by Segysmundo** [comment]
Yes, instead of determining the top voters with the time at which they voted. So it's less unfair for people with other time zones who wake up later.

**Comment by BenCodez** [comment]
Not a bad idea, might implement something like this.

I think its fair for the most part when voting for each month, it's just sites that do a daily reset instead of 24 hours that throw things off.

**Comment by Segysmundo** [comment]
Yeh I used it for monthly awards but since the vote site resets at 6 am we have smartass users that on day 1 of the month they wait for the reset and vote at 6-7 am so when the rest of users wake up the plugin has already decided the top 10 players that will win the monthly awards and they won't try to vote the remaining 30 days of the month

**Comment by BenCodez** [comment]
I see. I'll see if I can do something.

**Comment by BenCodez** [comment]
Something like this should work on the latest dev build:
http://ben12345rocks.com/job/VotingPlugin/



    MonthlyAwards:
      '1-10':
        Rewards:
          Messages:
            Player: '&aYou came in %place% in %TopVoter%!'

**Comment by Segysmundo** [comment]
So what does it do essentially?

**Comment by BenCodez** [comment]
Give everyone the same reward from first to tenth place.

**Comment by Segysmundo** [comment]
So now it won't always pick the first 10 guys that voted the earliest?

**Comment by BenCodez** [comment]
It picks the first 10 in the top voter list. You can change the numbers

**Comment by Segysmundo** [comment]
This method picks the first 10 in the top voter list the same way the old method does?

**Comment by BenCodez** [comment]
Yes. It just makes it easier to do the top 25 voters for example.

**Comment by Segysmundo** [comment]
Damn I think we misunderstood each other haha.

I was looking for an alternate way of picking the top x voters different from selecting them in order of who voted earlier.

This post is the one I tried to make more or less clear as to why top voters had to be chosen randomly from all players with the highest amount of votes instead of picking them by who voted the earliest.

> Yeh I used it for monthly awards but since the vote site resets at 6 am we have smartass users that on day 1 of the month they wait for the reset and vote at 6-7 am so when the rest of users wake up the plugin has already decided the top 10 players that will win the monthly awards and they won't try to vote the remaining 30 days of the month

**Comment by BenCodez** [comment]
You can use that to give a chance reward. Like the top 100 voters have a 10% chance to get a reward each.

**Comment by Segysmundo** [comment]
Yeh but the problem is I still want only 10 players to be rewarded, but those 10 guys need to be picked randomly from all the players with 31 votes, not just the 10 guys that reached 31 first.

With setting top 100 voters and giving them a 10% chance sometimes less than 10 guys will get a reward and sometimes more than 10 guys will be rewarded.

**Comment by BenCodez** [comment]
Well, it was an easy implementation for that feature I just added, which is why I did it, not exactly to solve this specific problem. There isn't really much I can do. Most servers just use the file that stores the top monthly voters and give rewards them manually.

**Comment by Segysmundo** [comment]
Yeh my worries were that what I was looking for was too hard to add and I would end up having to manually get all the top voters at the end of the month and do a random selection of 10 of them.

Thnx for the effort anyways, at least some good additions came out of this really long thread haha.

**Comment by BenCodez** [comment]
Might see if I can do something still though, just not this second.

**Comment by BenCodez** [comment]
Will consider the the top voter issue another time, when I have a decent solution to it.
