### ISSUE TITLE
Vote Party DYNAMIC Type setting

### ISSUE THREAD

**Issue by VoidAngel** [BenCodez/VotingPlugin#373]
Hello :3 
I would like to request a feature, but first Ill start by telling you my problem.
(Not a complaint xD)

We all know that the main purpose of vote parties is to grow your servers daily vote count by setting goals for the playerbase to reach. Ive been having very good success doing so by using your vote party system. So thanks for that <3 
The issue Im haivng now is that the vote party amount is static. It doesnt change. So now that my network is consistently reaching its goal of 700 votes daily, I would like to increase the vote party required votes. However, if I raise the vote party amount by 100 or 200 the players will rage and possibly be discouraged. Sure I could raise it by 10 everyday, but that means changing about 10 configs everyday for my network, and I would also have to change the amount at midnight on the dot so that every servers count would be raised as the count reset (to avoid player outrage). That's not very feasible for the average person. It would be best if I could automatically raise the vote party required votes by a small percentage every time the vote party occurs. This way, the vote party required votes would sort of regulate itself and aid in raising the servers daily vote count. 

I was hoping to suggest two new config fields:
`VoteParty:`
`  Type: DYNAMIC`
`  Multiplier: 0.01 ##Only used if Type is DYNAMIC`

The end result would be that every time the vote party is reached, the vote party required votes updates itself to something like
`(int)(getVotePartyVotesRequired() + Math.floor((getVotePartyVotesRequired() * getVotePartyRequiredMultiplier()))`

Thanks for listening!

**Comment by BenCodez** [comment]
I like the idea, I'll take a look at implementing it later

**Comment by BenCodez** [comment]
Latest build on here add it (untested):
http://ben12345rocks.com/job/VotingPlugin/

Config option:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L601

**Comment by VoidAngel** [comment]
Thank you! Thats awesome to have.

**Comment by BenCodez** [comment]
Wanna let me know how it works for you? I haven't tested it yet.
