### ISSUE TITLE
onPacketReceiving(PacketEvent) error

### ISSUE THREAD

**Issue by Lurreisper** [BenCodez/VotingPlugin#374]
https://pastebin.com/L1Kz4q4P

What is this error ? :c

**Comment by BenCodez** [comment]
Update the plugin?

**Comment by Lurreisper** [comment]
The version is 5.12.7.

This error is ocurring too (https://prnt.sc/ivm4xq) when I put a sign.

**Comment by BenCodez** [comment]
It's only because your using 1.8. The error was suppose to be fixed in 5.12.7.

Latest build here do anything?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Lurreisper** [comment]
It's not fixed :c

**Comment by BenCodez** [comment]
Latest build now?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Lurreisper** [comment]
Ok, it's fixed. Thanks :D
