### ISSUE TITLE
GottenMilestones Re-Fresh?

### ISSUE THREAD

**Issue by BakProject** [BenCodez/VotingPlugin#375]
I am using the Milestones to promote people at certain amount of votes. Recently the auto promotes have stopped working and I have been checking all the points and total points. The Gotten Milestones has not been updating. Is there a way to refresh that every 30 minutes or something along that line?

**Comment by BenCodez** [comment]
You mean delete the gotten milestones?

**Comment by BakProject** [comment]
Yes. I have it and the Total points is higher then my next Milestone, 

For example. The first rank is at 9 vote/points so the GottenMilestone is at 9. The player keeps voting and there total points is at 45 which is past the next milestone at 15. The player has not been promoted because the GottenMilestone was not updated when they got 15 votes/points. I hope the makes sense. If not then I can think of a better way to explain and maybe you could help me out a bit more.

Thanks for reading!
BakProject (McForest.net)

**Comment by BenCodez** [comment]
Are you on the latest version? Milestones are checked on each vote. They don't go off points, they go off the Milestone count (basiclly the alltime total). Try this command:
/av ResyncMilestones

**Comment by BakProject** [comment]
Will this command promote/demote players to there correct Milestone on their next vote, or what will this do?

BakProject (McForest.net)

**Comment by BenCodez** [comment]
Just set the milestone count to the all time total (and milestones get checked on vote) Shouldn't do anything negative unless your resetting milestones monthly.

**Comment by BakProject** [comment]
Okay! I did this and one of the players that were close to being promoted voted and ranked-up up no problem! Maybe the command did it?

Thanks for the help!
BakProject (McForest.net)

**Comment by BenCodez** [comment]
I think there was a bug in an older version that caused the count to not be added. That just resynced the count.

**Comment by BakProject** [comment]
When you set up milestone promotions, what is being read when you reach that milestone of votes?

AllTimeTotal, MilestoneCount, So that way I know what to watch when I test out the vote promotions?

BakProject (McForest.net)

**Comment by BenCodez** [comment]
MilestoneCount, that command sets the MilestoneCount to the AlTimeTotal.
