### ISSUE TITLE
CumulativeRewards

### ISSUE THREAD

**Issue by Bioticwolf08** [BenCodez/VotingPlugin#377]
Your page on this doesn't explain anything, I'm trying to make ranks for a certain number of votes. I put a broadcast as the command just to test it and that doesn't execute. 
Config:

Cumulative:
  '1':
    Enabled: true
    # Wether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    VotesInSameDay: false
    VotesInSameWeek: false
    Rewards: 
      Commands:
        - '/broadcast &e%player% &ahas voted and been promoted to &lRecruit!&r&a'

**Comment by BenCodez** [comment]
No / in the commands.

**Comment by Bioticwolf08** [comment]
Is it supposed to give them the reward every time after

**Comment by BenCodez** [comment]
Yes. Milestones are the same as Cummulative but they only reward once.

**Comment by Bioticwolf08** [comment]
Thank you! So much, sorry if I wasted any of your time.

**Comment by BenCodez** [comment]
All good then?

**Comment by Bioticwolf08** [comment]
yep
