### ISSUE TITLE
VoteSites.yml reverting back to some save point?

### ISSUE THREAD

**Issue by Edwards07256** [BenCodez/VotingPlugin#378]
So I edited the config a long time ago and set the rewards in the votesites.yml but without the '' around the rewards. I recently added the '' and it was fine and working but I've been noticing my players voting and not getting rewards. This happened on multiple occasions where I go back into the config and I notice the '' isn't around the reward anymore.

VoteSites:
  planetminecraft:
    Enabled: true
    ServiceSite: PlanetMinecraft
    VoteURL: https://www.planetminecraft.com/server/the-myriad/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
      Commands:
      - di tiers give %player% uncommon 10 1
      Money: 500
  topminecraft:
    Enabled: true
    ServiceSite: TopMinecraft
    VoteURL: https://top-minecraft-servers.com/server/the-myriad/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
      Commands:
      - di tiers give %player% uncommon 10 1
      Money: 500
  Minecraft-MP_com:
    Enabled: true
    ServiceSite: Minecraft-MP.com
    VoteURL: http://minecraft-mp.com/server-s192061
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
      Commands:
      - di tiers give %player% uncommon 10 1
      Money: 500
  TopG:
    Enabled: true
    ServiceSite: TopG
    VoteURL: https://topg.org/server-the-myriad-id488799
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
      Commands:
      - di tiers give %player% uncommon 10 1
      Money: 500
  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Top-Minecraft-Servers_com:
    Enabled: true
    ServiceSite: Top-Minecraft-Servers.com
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  TopG_org:
    Enabled: true
    ServiceSite: TopG.org
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward: []

Notice how I do not have the '' around the di command, I have added it in so many times but it keeps reverting back to some save point where I didn't have them. I am very confused as to why it's doing this and is it easier to just use the EverySiteReward?

**Comment by BenCodez** [comment]
Probably a site auto generating causes yml to update the config. (You don't need the ' around for most things)
