### ISSUE TITLE
Bugged Vote items

### ISSUE THREAD

**Issue by andris155** [BenCodez/VotingPlugin#379]
https://www.youtube.com/watch?v=gITEmkJ79rI

**Comment by BenCodez** [comment]
1. Doesn't seem like I can play that video anymore
2. Latest plugin version?
3. More details?

**Comment by andris155** [comment]
2. 5.12.8
3. 
- Open /vote
- Click paper
- Write fast command /vote
- Move items my inventory

**Comment by BenCodez** [comment]
I tried that but I couldn't do it. Maybe a plugin conflict?

**Comment by poma123** [comment]
https://youtu.be/gITEmkJ79rI

**Comment by BenCodez** [comment]
No matter how hard I try I can't do it. I need more details. plugins, etc.

**Comment by andris155** [comment]
```
10.04 22:51:16 [Server] INFO This server is running Paper version git-Paper-1389 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
10.04 22:51:16 [Server] INFO Checking version, please wait...
10.04 22:51:16 [Server] INFO You are 1 version(s) behind
```

`10.04 22:54:16 [Server] INFO Plugins (78): 2048, AdditionsAPI, AreaShop, Battleship, ChangeSkin, ChatControl, ChestShop, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CrazyAuctions, CreativeNbtControl, EntityDetection, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, FastAsyncVoxelSniper, FastAsyncWorldEdit, GameBox, GemCrush, Heads, husvet, JukeBox, Kredites, LockettePro, LogicPuzzles, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MineMarketAPI, Minesweeper, MobArena, MobHeads, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, myZone, NametagEdit, NoCheatPlus, NoSpawnerChange, OpenInv, OpenTerrainGenerator, Paintball, PlayerWarp, PlotSquared, PlugMan, ProtocolLib, PvPManager, RandomTeleport, redclockdetector, RestrictedCreative, SafeTrade, Shopkeepers, SignEdit, Stats, SurvivalGames, TimeIsMoney, TitleManager, TreasureChest, VanillaAdditions, Vault, Vehicles, ViaBackwards, ViaVersion, Votifier, VotingPlugin, VoxelSniper, WhacAMole, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, YouTubeBridge`

**Comment by BenCodez** [comment]
Does using normal spigot change anything? Test server with no other
plugins?

**Comment by BenCodez** [comment]
This help?
http://ben12345rocks.com/job/VotingPlugin/
