### ISSUE TITLE
Players able to remove items from the Vote GUI

### ISSUE THREAD

**Issue by zenith4183** [BenCodez/VotingPlugin#380]
I've had several players report to me that they are able to remove the items from the /vote GUI screen (and only that particular one that I've found thus far).  I have also been able to reproduce this.  The way they are doing it is to hover over the item and hit their item drop key which then causes the item to drop to the ground in front of them.

**Comment by BenCodez** [comment]
Can't reproduce.
Latest version? 
Can you reproduce on a fresh test server?

**Comment by zenith4183** [comment]
I'm using the latest version of VotingPlugin and Spigot.  I loaded it up on a test server and I still get the same result, however it seems to happen most reliably when the /vote command is called via the ChestCommands plugin.  To test if it was more likely to be a ChestCommands issue (since it's rather old) or a VotingPlugin issue, I tested the same thing with the Animated Menu plugin which is still kept up to date.  I get the same result with both.

**Comment by BenCodez** [comment]
Well, I can't recreate it. Not much I can do unless I can recreate it.

**Comment by BenCodez** [comment]
This help?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by zenith4183** [comment]
Indeed it does.  I can not reproduce the problem any more with that build.

**Comment by BenCodez** [comment]
Good to know. Managed to find the cause thrn
