### ISSUE TITLE
More of a question: Multiple lines of message when a player votes

### ISSUE THREAD

**Issue by leaguest1358** [BenCodez/VotingPlugin#381]
Currently setting up the plugin, everything working except 1 thing.
When a player votes it receives rewards. i would like to be able to send a message with it to give them some info about what they received.
Now I got it to the point where i have 1 message printed out, but for design purposes i would like to be able to give the player a message spread over different lines.
so instead of 1 long piece of text, i would like to be able to spread it on different lines in chat.

I don't know if this is already possible, if not I would really love to see this feature in updates :)

**Comment by BenCodez** [comment]
Use %NewLine%

**Comment by leaguest1358** [comment]
i have the following message setup in the VoteSites.yml:       
    Player: '&bVote: Bedankt voor het voten op ons :D' %NewLine% '&bVote: &7Beliningen: &7Je hebt &b250 ingame money&7, &b250 ClaimBlocks&7, en
            &b5 XP Flesjes&7 gekregen'

I tried with and without the ' but it does not seem to work. Console keeps saying the following:

13.04 14:49:38 [Server] INFO ^ 13.04 14:49:38 [Server] INFO ... dankt voor het voten op ons :D '%Newline% '&bVote: &7Beliningen: ... 13.04 14:49:38 [Server] INFO in 'string', line 53, column 62: 13.04 14:49:38 [Server] INFO found character '%' that cannot start any token. (Do not use % for indentation) 13.04 14:49:38 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token 13.04 14:49:38 [Server] ERROR Cannot load plugins/VotingPlugin/VoteSites.yml

is it just me being dumb or is this a bug?

thanks in advance for helping!

**Comment by BenCodez** [comment]
Don't put the ' in the center of the message, that will mess it up

**Comment by leaguest1358** [comment]
I've tried, but still the same error

**Comment by BenCodez** [comment]
Copy and paste the config in here:
http://yaml-online-parser.appspot.com/

If it has errors you need to fix it.

**Comment by leaguest1358** [comment]
i've tried the site, it gives no errors at all
as furhter info: 
my current message is the following:     

      Messages:
        Player: '&bVote: &7Je hebt gevote voor onze server :D %Newline% &bVote: &7Beloningen: Je hebt &b250 ingame money&7, &b250 ClaimBlocks&7, en &b5
          XP Flesjes&7 gekregen'

this results in the following message when voting:

![knipsel](https://user-images.githubusercontent.com/37934317/38778252-23538f22-40b7-11e8-9eda-ba1919a6d8da.PNG)

when reloading the plugin with this config of the message. the console gives no errors, but only warnings:

15.04 06:11:24 [Server] WARN 345350368 [Craft Scheduler Thread - 8616] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-56 - Shutdown completed. 15.04 06:11:24 [Server] WARN 345350367 [Craft Scheduler Thread - 8616] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-56 - Shutdown initiated... 15.04 06:11:24 [Server] WARN 345350064 [Craft Scheduler Thread - 8616] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-57 - Start completed. 15.04 06:11:24 [Server] WARN 345349931 [Craft Scheduler Thread - 8616] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-57 - Starting... 15.04 06:11:24 [Server] INFO DaBoss1358 issued server command: /av reload

Edit: 

The warning messages happens every reload, even with no %Newline% in the vote message

**Comment by BenCodez** [comment]
use %NewLine% (case sensitive)

**Comment by leaguest1358** [comment]
hehe sorry for your waste of time, you were right all along!

I've used %NewLine% case sensitive and it works like a charm.
Thanks for helping! appreciate  it :)
