### ISSUE TITLE
How to reset MileStones for testing?

### ISSUE THREAD

**Issue by kunwon1** [BenCodez/VotingPlugin#383]
Hello-

I have setup MileStones. I am testing the rewards system. I am using `av vote <player> <votesite>` to test.

I want to reset my test player to start the ladder from the beginning, so i do `av clearpoints <player>`, `av cleartotal <player>`, and `pex user <player> delete` - then `av reload` and `pex reload`

This resets the totals and resets the users groups, but it does not reset the player's progress on the MileStones. After doing all of this, if i send in a bunch of fake votes, the player gets promotion messages from much later in the ladder (as though it is picking up where it left off and ignoring the fact that i deleted the vote totals)

How can I reset a player entirely?

**Comment by BenCodez** [comment]
/av UserRemove (uuid)

Deletes the entire player data for that user.

**Comment by kunwon1** [comment]
That worked perfectly. Thank you very much for the plugin and especially the very fast support responses <3
