### ISSUE TITLE
Items Removable from GUI

### ISSUE THREAD

**Issue by MacTh3Mac** [BenCodez/VotingPlugin#384]
Players type /vote  then click on the paper,  they then type /vote again prior to the 2nd GUI window opening and items become removable from gui

Video and screenshot attached

https://youtu.be/2RhqiVNStvw

https://youtu.be/rcp_yWjbcQc

![screen shot 2018-05-01 at 08 40 22](https://user-images.githubusercontent.com/34489434/39465452-5c11f1a8-4d1b-11e8-93f9-69368e832d6d.png)

![screen shot 2018-05-01 at 08 50 15](https://user-images.githubusercontent.com/34489434/39465713-b65fde08-4d1c-11e8-96fb-202f00c17345.png)

![2018-04-29_20 37 31](https://user-images.githubusercontent.com/34489434/39465903-e3904902-4d1d-11e8-8188-578d68e98497.png)

**Comment by BenCodez** [comment]
Use the latest version
