### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by howy7214** [BenCodez/VotingPlugin#385]
Hello

My title manager scoreboard not working  for the vote party.

%NeededVotes% does not display just %NeededVotes%
please help

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/PlaceHolderAPI-Expansion

**Comment by howy7214** [comment]
I even try them does not work
%VotingPlugin_VotePartyVotesCurrent%  
%VotingPlugin_VotePartyVotesRequired%

**Comment by howy7214** [comment]
![scoreboard](https://user-images.githubusercontent.com/3688598/39609269-06b386a0-4f8b-11e8-8cbc-9fd8ec2aa0f1.png)
Screenshot of the issues

**Comment by BenCodez** [comment]
Do you have the placeholder expansion?

**Comment by howy7214** [comment]
No

**Comment by BenCodez** [comment]
that's your problem then....

**Comment by howy7214** [comment]
so wat do I do?

**Comment by BenCodez** [comment]
get it....
https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by howy7214** [comment]
That did not work

**Comment by BenCodez** [comment]
Did you install the expansion?

**Comment by howy7214** [comment]
sorry need to update latest on spigot

**Comment by howy7214** [comment]
Thank you so much for helping it works now thank

**Comment by howy7214** [comment]
also can i put the votes into a broadcast msg eg: name has voted site 31 votes until a vote party?

**Comment by BenCodez** [comment]
Use the placeholders from placeholderapi
