### ISSUE TITLE
Error Mysql

### ISSUE THREAD

**Issue by howy7214** [BenCodez/VotingPlugin#387]
Hello

I am getting and error with connection on the mysql works fine on my main server not on my prison server
please help
[Error.txt](https://github.com/Ben12345rocks/VotingPlugin/files/1979454/Error.txt)

**Comment by BenCodez** [comment]
Check your mysql information

**Comment by howy7214** [comment]
The info same as main server gets no errors

**Comment by BenCodez** [comment]
Do you have too many connection to it or somthing?

**Comment by howy7214** [comment]
### MySQL:
  Host: 'not showing'
  # Default port is 3306
  Port: 3306 
  Database: 'not showing'
  Username: 'not showing'
  Password: 'not showing'
  # Max number of connections
  MaxConnections: 3
  # Maxium size of caching mysql
  # -1 for no limit
  # Affecting this value may affect performance
  MaxSize: -1
  # Table name prefix, for use with mutliple servers
  Prefix: 'Voteplugin'
  #UseSSL: true

I change how many connections to one database as i do run a bungee serer all pointing to one database yes the mysqdata correct not showing it, because same one off the main

**Comment by BenCodez** [comment]
Change the number of connections to 1?

**Comment by howy7214** [comment]
MaxConnections: 3 to 1?

**Comment by BenCodez** [comment]
1

**Comment by howy7214** [comment]
Had that still did not work

**Comment by BenCodez** [comment]
Well, there's something wrong with the connection. Probably too many
connections

**Comment by howy7214** [comment]
Looks to be working fine now without changing anything i kept it with 3 connections but thank you for the help

**Comment by BenCodez** [comment]
Probably a plugin closed its connection or something, that be my guess.
