### ISSUE TITLE
Vote URLs don't work anymore

### ISSUE THREAD

**Issue by BambuiZepelin** [BenCodez/VotingPlugin#388]
I don't know if it's just for me but when I open the GUI and select any voting site or even all voting sites it appears in the chat but no one can open the link. I tried different links to see if it works anyway but it seems that it just _doesnt trigger_ anything when someone clicks on the link. :/
It didn't seem to be an issue before it's quite recently.

**Comment by BenCodez** [comment]
Update the plugin

**Comment by BambuiZepelin** [comment]
I did though I only swapped the jar file as I didn't want to reconfigure the rewards, messages, and milestones. 
Do I need to delete the preset files (config, rewards, vote sites, etc) and reconfigure them?

**Comment by BenCodez** [comment]
Just update the jar file

**Comment by BambuiZepelin** [comment]
Yeah apparently I downloaded the jar file from the spigot page and it didn't work but when I got it from Jenkins it worked, might want to check it out.
Thanks a lot anyway, I appreciate.

**Comment by BenCodez** [comment]
You must be downloading an older version. As it was a bug in a recent version.

**Comment by BambuiZepelin** [comment]
I downloaded the last successful version from Jenkins and it worked that's all I know.
Thank you a lot.

**Comment by BenCodez** [comment]
You downloaded an older version earlier then.
