### ISSUE TITLE
[RESOLVED] User Not joined votes

### ISSUE THREAD

**Issue by Castiella** [BenCodez/VotingPlugin#389]
We're being spammed by votes with profanity names, who have never joined the server. We have our config set to:

# Let players who never joined before vote
# Recommend: False (Will prevent creating random user data files)
AllowUnjoined: false

so why is this still happening?

**Comment by BenCodez** [comment]
Latest version?
Is there a broadcast from the vote?

**Comment by Castiella** [comment]
5.13.1

Yes it broadcasts, for example, a player will writer a swear word instead of the username.

**Comment by Castiella** [comment]
![image](https://user-images.githubusercontent.com/29293070/40844167-1bb70316-65ab-11e8-954f-478d971217b5.png)

**Comment by Castiella** [comment]
Ignore the chat spam, but as you can see it allowed both "poop" and "Poops"

**Comment by Castiella** [comment]
Closing, issue was conflicting plugin which we have since removed. really sorry to waste your time.
