### ISSUE TITLE
Can't prevent players from using the voting shop

### ISSUE THREAD

**Issue by Castiella** [BenCodez/VotingPlugin#390]
I've tried negating the node "VotingPlugin.Commands.Vote.Shop"
but players still can access the shop and buy a diamond for 3 voting points.

It is very annoying that there isnt a simple "disable" option within the config.

Also, when i try to make the cost ridiculous to prevent them using it (30000) save the config, reload the plugin - it doesn't change the GUI at all.

**Comment by BenCodez** [comment]
Players get VotingPlugin.Player by default which gives the permission to use the command (option to disable that)

You can delete the item section from the vote shop to remove it.

Changing the cost doesn't update the lore (its set manually in the config, so it will still say 3 unless you change it)

**Comment by Castiella** [comment]
When i tried to delete the item section it removed the whole GUI function for voting

**Comment by BenCodez** [comment]
Then you deleted the wrong item section...
