### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by Sikatsu** [BenCodez/VotingPlugin#394]
I haven't touched the config in a long while and I don't think there are any issues, however this seems to showup on every VoteParty:

21.06 13:55:44 [Server] WARN Detected a reward file edited when it should be edited where directly defined, overriding
21.06 13:55:44 [Server] WARN Detected a reward file edited when it should be edited where directly defined, overriding

**Comment by BenCodez** [comment]
Edit any files in the rewards folder? If not ignore it.
