### ISSUE TITLE
Hikari times out and fails to get connections with databases using smaller max-lifetimes

### ISSUE THREAD

**Issue by egg82** [BenCodez/VotingPlugin#396]
Error: https://pastebin.com/bSdFWdGd
Caused by default "max-lifetime" set in HikariCP [here](https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/mysql/api/ConnectionManager.java#L152)
Solution: use [HikariConfig#setMaxLifetime](https://static.javadoc.io/com.zaxxer/HikariCP/2.7.4/com/zaxxer/hikari/HikariConfig.html#setMaxLifetime-long-) and create a config option

**Comment by BenCodez** [comment]
I'll add that whenever I get a chance

**Comment by BenCodez** [comment]
Latest build should have it:
http://ben12345rocks.com/job/VotingPlugin/

MaxLifeTime is the option

**Comment by BenCodez** [comment]
Any update on this?

**Comment by egg82** [comment]
Can't say just yet, as I haven't tested long enough for it to be an issue. Will post back when I get some data.

**Comment by egg82** [comment]
Looks good on our end, though getConnection() timings out returns a null value which causes a NPE to be thrown in AdvancedCore.mysql.api.queries.Query.<init>(Query.java:21)
Not a huge deal, though. Otherwise looks good.

**Comment by BenCodez** [comment]
Don't know if there is any way to prevent that.
