### ISSUE TITLE
Vote sign is not showing the correct total

### ISSUE THREAD

**Issue by Turbotailz** [BenCodez/VotingPlugin#397]
The top voter for all time and monthly is showing an incorrect vote count

![image](https://user-images.githubusercontent.com/10846855/42024077-7b6e9e5c-7b15-11e8-820a-b8e613511e8d.png)

![image](https://user-images.githubusercontent.com/10846855/42024133-9b574ea8-7b15-11e8-89bd-059565ef530e.png)

How can I fix this?

**Comment by BenCodez** [comment]
Your looking at monthly when the signs are all time

**Comment by Turbotailz** [comment]
My bad, but same deal.

![image](https://user-images.githubusercontent.com/10846855/42026288-d5ac3654-7b1a-11e8-9798-425c33fcb672.png)

**Comment by BenCodez** [comment]
Remake the signs?

**Comment by BenCodez** [comment]
Any update on this?

**Comment by Turbotailz** [comment]
Sorry haven't had time to check. I'll just close this and reopen if I have any more issues.
