### ISSUE TITLE
How can i set CMD for vote shop

### ISSUE THREAD

**Issue by Kinert** [BenCodez/VotingPlugin#398]
I have question i want to execute console the CMD to give player something is it real because i see that i can only set items

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - command for %player%

**Comment by Kinert** [comment]
i just broke config

**Comment by Kinert** [comment]
VoteShopBackButton: true
Shop:
  # Identifier
  # Used in placeholders for formats
  Diamond:
    # Item
    Material: 'DIAMOND'
    Data: 0
    Amount: 1
    Name: '&4Buy A MysteryBox'
    # You can set skulls of the player using the following
    # Remove the # to enable
    #Skull: '%Player%'
    Lore:
    - '&7&lCost: &71 Voting Points'
    # Number of voting points this cost
    Cost: 3
    # Rewards to run if player buys succesfully
    Rewards:
  Commands:
  - gmysteryboxes give %player% 1

**Comment by Kinert** [comment]
it wont work

**Comment by Kinert** [comment]
![capture](https://user-images.githubusercontent.com/34911403/42126780-c7eedaae-7c95-11e8-92fa-f917e51903f9.PNG)

**Comment by BenCodez** [comment]
Space it the way I had it

**Comment by Kinert** [comment]
yes
thx all works gine now!

**Comment by Kinert** [comment]
Why cant i add multiple items in vote shop 
![capture](https://user-images.githubusercontent.com/34911403/42126986-917b01c4-7c99-11e8-96b6-72dc3d89ec34.PNG)

**Comment by Kinert** [comment]
and i dont have morphs in my plugin why? i am using lates build

**Comment by BenCodez** [comment]
Add this to each and change the number.
Slot: 0

**Comment by Kinert** [comment]
Yeh but now i cant have more then 2 items in shop

**Comment by BenCodez** [comment]
Because you need the slots set

**Comment by Kinert** [comment]
i set them but i have only forst item and last in shop others are gona

**Comment by BenCodez** [comment]
set the others to different numbers?

**Comment by Kinert** [comment]
i did still i have only 2 items

**Comment by Kinert** [comment]
And where can i set CMD for vote reward
??

**Comment by BenCodez** [comment]
Pastebin it?

Same as those rewards.
