### ISSUE TITLE
SQL "SHOW FULL COLUMNS" and "SELECT *" execution on the main thread causing severe lag

### ISSUE THREAD

**Issue by egg82** [BenCodez/VotingPlugin#399]
Profiler evidence
https://image.prntscr.com/image/nX2dO19rQDWZB3dilTmeLQ.png
https://image.prntscr.com/image/YZ_xVEP8RcOteG79L0aQYg.png
https://image.prntscr.com/image/ZRV2krhnSxmPpNWr3ISqMA.png
https://image.prntscr.com/image/ViXPso90SUW9Hj7RQexIxA.png
https://image.prntscr.com/image/_6-2FRd-Q1OZjD-ujYu8lA.png
https://image.prntscr.com/image/n5YSjajESfeStcmsJIlyhQ.png

Suggested fixes:
1. Use in-memory caches for recent players to avoid multiple lookups (possibly add an option in configs to allow variable cache times)
2. Add "useDynamicCharsetInfo=false" as per https://stackoverflow.com/questions/29451069/tons-of-generated-show-full-columns-from-queries-in-mysql-connector-j
3. Remove the use of com.sun.rowset.CachedRowSetImpl here: https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/mysql/api/queries/Query.java#L107
4. Move SQL queries off the main thread since they tend to be quite slow

2 and 3 should be mutually exclusive, in theory

**Comment by BenCodez** [comment]
I don't execute sql queries on the main thread....
I'll look more into it later.

**Comment by BenCodez** [comment]
1. I do have cache
2. I Added that. Here's a dev build if you want to try it: http://ben12345rocks.com/job/VotingPlugin/
3. I don't think I ever execute that method except on startup, all queries are cached and executed in batches
4. I don't execute any on the main thread, check yourself: https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/Events/VotiferEvent.java#L172

**Comment by egg82** [comment]
Ah, you're right, none of those queries are sync tasks- I misread, my apologies.

However the two queries provided eat up a LOT of CPU and cause some pretty bad lag (as evidenced by the red in the thread profiling) - after cloning the repo and adding "useDynamicCharsetInfo=false" the issue goes away entirely. I'm also confused as to how a SELECT statement uses so much CPU time with a little over 2,000 rows when my plugin here (https://github.com/egg82/PlayerIPAPI/blob/master/src/me/egg82/ipapi/sql/SelectIpsCommand.java#L51) does the same but with 68,000+ rows and uses a fraction of the time. Is it possible the query is simply being run too many times? Or the data is stored in TEXT or BLOB form so the SQL server needs more lookup time?

**Comment by BenCodez** [comment]
Data is stored in a text. That might be why.

**Comment by egg82** [comment]
Ah, that might explain some of it. It might also be possible it's querying multiple times somehow- at least that's the only other explanation I can come up with. Could be either/or, or a combination of both. More testing might be required.

**Comment by BenCodez** [comment]
More testing is needed for sure.

**Comment by BenCodez** [comment]
I made this issue to remind me to do some optimizing, will close this one for now.
https://github.com/Ben12345rocks/AdvancedCore/issues/120

**Comment by BenCodez** [comment]
Did some optimizing, try it out:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by egg82** [comment]
Didn't work. Use "&" instead of "\&amp;" - none of the options you provided to the MySQL connection manager actually take effect because it's not expecting "amp;" as an option.

**Comment by BenCodez** [comment]
It needs to be "&amp;" else mysql will fail to load. Plus it does take affect.

**Comment by egg82** [comment]
To quick-fix the issue on our end previously I forked AdvancedCore and changed mysql.api.ConnectionManager to the following
```
	public boolean open() {
		try {
			Class.forName("com.mysql.jdbc.Driver");

			HikariConfig config = new HikariConfig();
			config.setDriverClassName("com.mysql.jdbc.Driver");
			config.setUsername(username);
			config.setPassword(password);
			config.setJdbcUrl(String.format("jdbc:mysql://%s:%s/%s", host, port, database) + "?useSSL=" + useSSL
					+ "&allowMultiQueries=true&rewriteBatchedStatements=true&useDynamicCharsetInfo=false");
			config.setConnectionTimeout(connectionTimeout);
			config.setMaximumPoolSize(maximumPoolsize);
			config.setMinimumIdle(maximumPoolsize);
			config.setMaxLifetime(300000L);
			dataSource = new HikariDataSource(config);
			return true;
		} catch (Exception e) {
			e.printStackTrace();
			return false;
		}
	}
```

That version does not have the aforementioned issues with "SHOW FULL COLUMNS" or #396 

I'm suggesting switching the "\&amp;" in https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/mysql/api/ConnectionManager.java#L163 to simply "&" as the former is showing in the actual SQL connection string in the profiler and I'm fairly sure MySQL doesn't know what "amp;" is. That seems to be the only real difference between your current version and my hacky fix, so it leads me to believe I'm likely correct on that.

**Comment by BenCodez** [comment]
What if you remove all the options after the &?

**Comment by egg82** [comment]
Same effect as before. The option doesn't apply and "SHOW FULL TABLES" executes on every query.

**Comment by BenCodez** [comment]
I think this is why I originally did it that way, but I guess that doesn't
apply here anymore

If the mechanism you use to configure a JDBC URL is XML-based, use the XML
character literal &amp; to separate configuration parameters, as the
ampersand is a reserved character for XML.

**Comment by egg82** [comment]
It's possible, though it also means that it'll ruin any SQL-based JDBC connection. Generally I don't think you'd be using Hikari for XML. Or if that would even be feasible. I'm sure someone's done it, but eh.

**Comment by BenCodez** [comment]
I tested it myself, mysql is like 100x faster. 

Good find :)
