### ISSUE TITLE
VoteParty not activating

### ISSUE THREAD

**Issue by RogerPlaysMC** [BenCodez/VotingPlugin#405]
We have voteparty set at 50 votes.  After we hit 50, the counter keeps going up, (says we have 51, need -1 for vote party) but a voteparty never triggers.

Running a custom 1.8.8 and the newest (as of today 5.13.5) version of VotingPlugin.  Same issue with 5.13.4.

**Comment by BenCodez** [comment]
Did you ever use increase votes required?

**Comment by RogerPlaysMC** [comment]
The owner had set it, then I set it back to 0.

**Comment by BenCodez** [comment]
In the serverdata.yml, there will be a value that says increasevotesrequired (or something like that for vote party). Set that to 0.

**Comment by RogerPlaysMC** [comment]
After a reboot that worked.  Thanks!

**Comment by BenCodez** [comment]
Np
