### ISSUE TITLE
Null Pointer exceptions in Version 5.13.5

### ISSUE THREAD

**Issue by MacTh3Mac** [BenCodez/VotingPlugin#406]
Null Pointer exceptions in Version 5.13.5

https://hastebin.com/osociyiyit.php

**Comment by egg82** [comment]
#407 Fixes this issue

**Comment by egg82** [comment]
For future reference, try to include Pastebin links, not Hastebin links, as Hastebin links expire

**Comment by BenCodez** [comment]
Fixed in latest build
