### ISSUE TITLE
Many exceptions thrown in AdvancedCore/UserData/getInt

### ISSUE THREAD

**Issue by egg82** [BenCodez/VotingPlugin#409]
http://prntscr.com/k910bl

Although they are all caught and handled, it doesn't do the CPU any favors to throw 17,000 exceptions all at once. Even on a new thread, it does create lag spikes.

**Comment by egg82** [comment]
also User/getMonthTotal

**Comment by BenCodez** [comment]
Did you modify anything?

**Comment by egg82** [comment]
No, this particular version is from Spigot

**Comment by BenCodez** [comment]
How about the column type?

**Comment by BenCodez** [comment]
This help?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by BenCodez** [comment]
I also converted columns to ints, so that should help even more

**Comment by egg82** [comment]
nice, I'll start testing that in a bit

**Comment by BenCodez** [comment]
The latest build now is 1.13 only, as a heads up
