### ISSUE TITLE
Generated an exception - won't register vote

### ISSUE THREAD

**Issue by LordSheep** [BenCodez/VotingPlugin#411]
A player on my server voted on server lists but it isn't registering his votes or giving him the rewards. Doesn't show his votes in VoteToday GUI. 

He just changed his MC name today before voting and voted with his new MC name.

When I vote it gives me my reward and registers my vote just fine. 

Error: https://pastebin.com/QJj3wW32

**Comment by BenCodez** [comment]
Update the plugin.

**Comment by LordSheep** [comment]
Do I delete the old  jar and replace it with the new one to update?

**Comment by BenCodez** [comment]
Yep

**Comment by LordSheep** [comment]
I updated it, now I will wait till the person votes again to see if it works.

**Comment by LordSheep** [comment]
Okay, player can vote now. Is there a way to manually add votes to someone to make up for the uncounted votes?

**Comment by LordSheep** [comment]
Would there be a way to remove votes, I may have added too many

**Comment by BenCodez** [comment]
Set the values manually

**Comment by LordSheep** [comment]
Where would I do that?

EDIT: Also the votes I added didn't count towards top monthly voters.

**Comment by BenCodez** [comment]
Change it with /av gui (go into users, there is a way to edit stuff there)

It should of added towards monthly votes

**Comment by LordSheep** [comment]
Okay, I just went in and changed the values. Does week vote streak, best week vote streak, and highest weekly total matter? What's milestone count for? Is that just the number of votes? (Sorry for asking so many questions) 

Anyway the /av vote only broadcasted the vote and gave the rewards, for me it didn't register toward monthly vote but did show in next, last vote times, and today.

**Comment by BenCodez** [comment]
The streaks are the number of days in a row you vote.
The highest totals don't matter really. If you don't use milestones then ignore that count. The top monthly voters don't update instantly to help improve performance. (usually 2 mins)

**Comment by LordSheep** [comment]
Okay then thanks for all your help.
