### ISSUE TITLE
Thanks .... However...

### ISSUE THREAD

**Issue by PJsDad** [BenCodez/VotingPlugin#412]
Hello ... LOVE VotingPlugin and I am sure I will enjoy it more once I get it set up correctly

I am running 1.12 and wont upgrade to 1.13 until there are more developers create/upgrade to 1.13.

How do I get v5.13.6 for 1.12 ?

It is great that you are so involved with your upgrades ... the links to youtube vids are not really helpful because they represent past versions. The only recent YT Video is by KaiddyTV, however the gentle-person who authored it failed to produce a video with enough audio volume to make it useable.

Your plug-in is the only game in town, considering GAListener is no longer supported, If servers wish to have voting on their server you are the "only game in town"

I may have more questions/comments but first I need the correct version to install.

Please let me know 

Hal aka PJsDad

**Comment by BenCodez** [comment]
Just go to the version history to get it.

**Comment by PJsDad** [comment]
Thanks and thanks for prompt reply

**Comment by BenCodez** [comment]
I should also mention that the older youtube videos still apply on the later versions.

**Comment by PJsDad** [comment]
For the most part yes you are correct at times the look of the config files
are different, but think I have it sorted thanks for following up.
I hope that you contacted the author of the one review that had audio
issues I know how important video reviews are to a developer and to have
one that fails to properly advertise your project is not what you are
looking I hope he has the ability to redo.

Take care and the best of luck!!
Hal aka pjsdad1947

**Comment by BenCodez** [comment]
I'm hoping to create my own videos, that are much more detailed.
