### ISSUE TITLE
Didn't create monthly reward #5 file

### ISSUE THREAD

**Issue by LordSheep** [BenCodez/VotingPlugin#413]
I set up 5 rewards for monthly voters and when it was the end of the month it only created MonthlyAwards_#_Rewards from 1-4. The fifth top voter (me) didn't get the reward for 5th place. It did say "You came in fifth place in Monthly!" though. 

Not sure why it didn't create a fifth file, on my test server with an older version of server it created all 5 files. 

Can I **manually create** a file and name it fifth place and set the reward? Will it work?

**Comment by BenCodez** [comment]
It only creates it if it needs to

**Comment by LordSheep** [comment]
Then what do I do if a reward file is missing?

**Comment by BenCodez** [comment]
Why do you need to create one? If you have rewards defined under the rewards then it should matter. Configs would help.

**Comment by LordSheep** [comment]
Config: https://pastebin.com/63gphmfw

**Comment by BenCodez** [comment]
Did you get the reward? If you did then everything is working fine.

**Comment by LordSheep** [comment]
![image](https://user-images.githubusercontent.com/30538383/43610239-918aabf8-9673-11e8-9ef9-af5008e982b6.png)

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/Objects/Reward.java#L1132

It only generates a reward file if the player was offline at the time (and some other cases). Manually creating one will have no effect.

**Comment by LordSheep** [comment]
So if a player was online at the time then what happens? Don't believe I got the reward

**Comment by BenCodez** [comment]
They get the reward....
Turn debug on and see for yourself.

**Comment by LordSheep** [comment]
Turned on debug in config. What would I do to see since the month rewards were already given out.

**Comment by BenCodez** [comment]
Test it with something else?

**Comment by LordSheep** [comment]
Nevermind, turns out you were right. I copied in votingplugin file and jar from a backup on the 31st and pasted it on a test server and it gave out the reward. Thanks for the help.
