### ISSUE TITLE
VoteParty not triggering

### ISSUE THREAD

**Issue by Xeyame** [BenCodez/VotingPlugin#415]
So i'm not very sure what i did wrong, but this is my VoteParty config section:
```VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 25
  # Increase the amount of votes required on each vote party reached
  IncreaseVotesRquired: 25
  # If true, players who did not vote to reach the votes required will
  # recieve the reward
  GiveAllPlayers: false
  # If true, the vote count will reset each day
  ResetEachDay: false
  # Reset at the end of the month
  ResetMonthly: false
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 1
  # Broadcast when vote party reached
  Broadcast: '&a[Vote&b] &eVote party! Everyone gets rewarded with 10 Points!'
  # List of commands to execute, these only execute once.
  Commands: []
  # Reward files to give
  Rewards:
    Commands:
      Console:
      - 'pointmanager give %player% 10'
```
However, when i do /voteparty, it says "Currently at 34, -9 more votes to go to reach 25". So it seems to not be triggering and just going to negative values. 

Not sure what to do, Please help :P

**Comment by BenCodez** [comment]
It's because of this:
# Increase the amount of votes required on each vote party reached
  IncreaseVotesRquired: 25

It increases the amount required after each voteparty, and the placeholder doesn't update (it's suppose to though)

**Comment by Xeyame** [comment]
So would setting it to 0 (and thus no increases sadly) fix the issue?

**Comment by BenCodez** [comment]
That should do it. You might need to change the number in ServerData.yml for IncreaseVotePartyVotes.

If your using 1.13 the bug is fixed so it displays the correct number here:
http://ben12345rocks.com/job/VotingPlugin/
