### ISSUE TITLE
In the shop don't show GoldenSword

### ISSUE THREAD

**Issue by Zarpyk** [BenCodez/VotingPlugin#419]
```
  Tesoro:
    # Item
    Material: 'GOLDEN_SWORD'
    Data: 1
    Amount: 1
    Name: '&c&lEspadaTSkull'
```
I put this but in the GUI, only show stone
And can you add Glowing effect plis

**Comment by BenCodez** [comment]
Are you using 1.13? if not its GOLD_SWORD. Also no data value should be needed.

**Comment by Zarpyk** [comment]
And is possible add Glow Effect?

**Comment by BenCodez** [comment]
Add an enchant and you can add an Item flag to hide enchants.

Basic idea:

    Enchantments:
      Unbreaking: 1
    ItemFlags:
    - HIDE_ENCHANTS

don't remember if that's the spelling I went with, it should be in the example basic reward.

**Comment by smmmadden** [comment]
All the GOLD_ material ID's changed to GOLDEN_* and WOOD_ changed to WOODEN_*
:-)

**Comment by BenCodez** [comment]
I know. I said if you weren't using 1.13 :)

Try no data value?

**Comment by Zarpyk** [comment]
In the 1.12 is Golden and the enchantment don't work

**Comment by BenCodez** [comment]
Are you using 1.12?
It might be UNBREAKING, don't remember
