### ISSUE TITLE
Changeable VoteSite Auto-Add Settings

### ISSUE THREAD

**Issue by falceso** [BenCodez/VotingPlugin#420]
Hello,

I was wondering if you can add the ability to set default settings upon automatic addition. This saves a few moments of revisiting the config when you are mass adding voting sites.

Thanks!

**Comment by BenCodez** [comment]
What would you change about the defaults? Don't see a reason to have default settings, since you have to change them anyway.

**Comment by falceso** [comment]
At the time of writing, I was thinking of the rewards field, or at minimum the default reward message (the one specified in the `config.yml` was overridden by the default message shown in `VoteSites.yml`.

**Comment by BenCodez** [comment]
What message in the Config.yml? If you wanted the same rewards for every site use the EverySiteReward.

**Comment by falceso** [comment]
Ah, I just realized that config line existed ~~since I overwrote the whole file leaving that line out.~~, *Correction, I didn't see the line whilst editing.*

Actually, I retract my statement on the messaging be overridden, I forgot to check before I logged in. The broadcast message is outputted before the player is even on.

Gotta love finding the answer to your own questions when you open a discussion. 😆 

Thanks for the plugin, also can you add a page that lists all the built-in placeholders (no relation to PlaceholderAPI)?

**Comment by BenCodez** [comment]
The built in placeholders are pretty standard. I usually list in comments what ones are available. You should be able to use javascript in any player message, so basicly you got every placeholder available. Any specific areas you want to know?

**Comment by falceso** [comment]
Nah, I think I'll be fine with `%ServiceSite%` for now. Just suggested in case I was looking for one that I removed. Closing this issue out now.
