### ISSUE TITLE
/av gui not working

### ISSUE THREAD

**Issue by keough99** [BenCodez/VotingPlugin#422]
hello im having an issue where /av gui is not working heres the error log:
`23.09 14:27:06 [Server] WARN Plugin VotingPlugin v5.15 generated an exception while executing task 208
23.09 14:27:06 [Server] INFO java.lang.NoSuchFieldError: PLAYER_HEAD
23.09 14:27:06 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.Commands.GUI.AdminGUI.openGUI(AdminGUI.java:95) ~[?:?]
23.09 14:27:06 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$17.execute(CommandLoader.java:420) ~[?:?]
23.09 14:27:06 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:387) ~[?:?]
23.09 14:27:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[custom.jar:git-Spigot-2cf50f0-8166d17]
23.09 14:27:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-2cf50f0-8166d17]
23.09 14:27:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
23.09 14:27:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
23.09 14:27:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by BenCodez** [comment]
That version doesn't support 1.12

**Comment by keough99** [comment]
which version supports 1.12.2?

**Comment by BenCodez** [comment]
5.13.6, it says on the plugin page.
