### ISSUE TITLE
I can' change VoteSite material.

### ISSUE THREAD

**Issue by Nelfis** [BenCodez/VotingPlugin#426]
Here's my config.

VoteSites:
  # VoteSite name
  ExampleVoteSite:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: '&bPlanetMC'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com)
    ServiceSite: 'planetminecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: '&aClick on it &b https://www.planetminecraft.com/server/goldenrye/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Reset vote delay each day (for certain sites that do this)
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline, NOT WHEN THE PLAYER IS OFFLINE
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'OAK'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      Commands:
      - 'say hello'
      Messages:
        Player: '&aThanks for voting! Here is your reward!'

**Comment by BenCodez** [comment]
What are you trying to change? It may be in the Config.yml.

**Comment by Nelfis** [comment]
I'd like to change items in /vote menu

**Comment by BenCodez** [comment]
Change it in the Config.yml
