### ISSUE TITLE
Emerald Vote Reward Enchantment Issue

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#427]
Items:
  EMERALD:
    Amount: 1
    Material: EMERALD
    Name: §aSkyCoin
    Durability: 100
    Enchants:
      MENDING: 1

When I spawn in the reward the Mending enchant is not there.

![image](https://user-images.githubusercontent.com/42560806/46427623-ba05d900-c6f6-11e8-95db-5fdf5a730e69.png)

**Comment by BenCodez** [comment]
Latest version?

**Comment by ghost** [comment]
Yes, I am using the latest version of your plugin, and 1.13.1 is my server version.

**Comment by BenCodez** [comment]
Use unbreaking, need to use vanilla names since 1.13

**Comment by ghost** [comment]
That doesn't work. I want enchants to display on vote reward items but it's just not working. Can you maybe send a config snippet like I did and I can try it when I have the time?

**Comment by andris155** [comment]
I used this page for enchants names and works perfectly my server.
https://www.digminecraft.com/lists/enchantment_list_pc.php

**Comment by ghost** [comment]
Andris155, can you message me via Discord? Kalasky#0001 is my username.

**Comment by BenCodez** [comment]
Did you set the display item or the reward item?

**Comment by ghost** [comment]
I set it as a reward. It's listed in the rewards folder as a yml file.

**Comment by BenCodez** [comment]
Change the display item in the Config.yml.

**Comment by ghost** [comment]
What do you mean?

**Comment by BenCodez** [comment]
Wanna send me your configs in a pastebin?

**Comment by ghost** [comment]
I only messed with the rewards as of right now. I haven't even touched the config.yml. https://ghostbin.com/paste/a66o8

**Comment by BenCodez** [comment]
Try Enchantments?

**Comment by BenCodez** [comment]
actually try mending in lowercase.

**Comment by ghost** [comment]
I tried all of that it doesn't work.

**Comment by BenCodez** [comment]
you are on the latest version right? enchantments don't work in 5.15 or lower.

I know this works:
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleBasic.yml#L58

**Comment by ghost** [comment]
I even tried my old config from my other server that got it to show mending on the item and it still didn't work, might just be a bug for 1.13.1?

**Comment by ghost** [comment]
Your ExampleBasic.yml looks different from mine?

**Comment by BenCodez** [comment]
In 1.13 you have to use the vanilla names.
Whatever you had in an older version probably won't work.

**Comment by ghost** [comment]
I copied your exact config, and the enchantment still doesn't pop up.
![image](https://user-images.githubusercontent.com/42560806/46586460-d6c24980-ca33-11e8-8c55-1944bed7a652.png)

**Comment by BenCodez** [comment]
What plugin version are you using?

**Comment by ghost** [comment]
5.15

**Comment by BenCodez** [comment]
.... enhantments don't work in that version... update (I said this a few times)

**Comment by ghost** [comment]
I saw your messages a few times saying that, I thought I was on 5.15.1 the whole time. Sorry for wasting your time, and my time as well. *sigh*

**Comment by BenCodez** [comment]
Always double check, don't assume :P

**Comment by ghost** [comment]
Yup, I'll take that into consideration next time, have a good one!
