### ISSUE TITLE
It wont work.

### ISSUE THREAD

**Issue by NightShadow696** [BenCodez/VotingPlugin#428]
so when i want to add something to my sites as rewards it just quits working on me can someone help me fix it and or fix it for me?.... 

         VoteSites:
         PlanetMinecraft:
         Enabled: true
         ServiceSite: PlanetMinecraft
         VoteURL: https://www.planetminecraft.com/server/shadow-craft-new-plugins-being-added/vote/
         VoteDelay: 24
         Item:
         Material: GRAVEL
         Amount: 1
         Rewards:
          Commands
          - 'eco give %player% 200'
          - 'crate key %player% vote 1'
          Player:'&aThanks for voting on %ServiceSite%! Heres $200 and a Crate Key!'
         Priority: 5
         TopG:
         Enabled: true
         ServiceSite: TopG
         VoteURL: https://topg.org/Minecraft/in-499325
         VoteDelay: 24
         Item:
         Material: STONE
         Amount: 1
         Rewards:
          Commands
          -'eco give %player% 200'
          -'crate key %player% vote 1'
         Messages:   
         Player: '&aThanks for voting on %ServiceSite%! Heres $200 and a Crate Key'
         Priority: 4
         mmp:
         Enabled: true
         ServiceSite: mmp
         VoteURL: https://minecraft-mp.com/server/205887/vote/
         VoteDelay: 24
         Item:
         Material: DIRT
         Amount: 1
         Rewards:
          Commands
          - 'eco give %player% 200'
          - 'crate key %player% vote 1'
         Messages:
         Player: '&aThanks for voting on %ServiceSite%! Heres $200 and a Crate Key!'
         Priority: 3
         msb:
         Enabled: true
         ServiceSite: msb
         VoteURL: https://minecraftservers.biz/servers/142377/vote/
         VoteDelay: 24
         Item:
         Material: GRASS
         Amount: 1
         Rewards:
         Messages:
         Player: '&aThanks for voting on %ServiceSite%! Heres $200 and a Crate Key!'
         Priority: 2
         minecraftservers:
         Enabled: true
         ServiceSite: minecraftservers
         VoteURL: https://minecraftservers.org/vote/514779
         VoteDelay: 24
         Item:
         Material: SAND
         Amount: 1
         Rewards:
          Commands
          - 'eco give %player% 200'
          - 'crate key %player% vote 1'
         Messages:
         Player: '&aThanks for voting on %ServiceSite%! Heres $200 and a Crate Key!'
         Priority: 1

Thats my config for it

**Comment by BenCodez** [comment]
1. Check that your service sites are correct
2. Are you getting the vote?

**Comment by NightShadow696** [comment]
Im nkt getting the vote cuz everytime i use it it says null on all of it and it removes the sites from my server

**Comment by BenCodez** [comment]
Screenshots, console log?
