### ISSUE TITLE
VotingPlugin Milestone Rewards

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#430]
In the Milestone section below, how can I make it to where a player will get a rank as a reward? I am using LuckPerms and the command would be something like /lp user <user> parents set <group>

Am I able to have this as a reward? If so how and where would I put it in the section below? Also, if I wanted to test if it worked what command would I run?

MileStones:

  # Number of votes required

  # Allows multiple milestones

  # Number be be around ' (E.g. '1')

  # Can have multiple listed here

  '20':

    Enabled: false

    Rewards: 

      Messages:

        Player: '&aYou got %milestone% milestone votes!'

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - 'say %player%'

**Comment by ghost** [comment]
Thank you!
