### ISSUE TITLE
Vote shop suggestions

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#432]
[Background]
I want to let players buy some extra permissions in game.
The first is easy. The seconds extra will be available when the first extra is bought and generates a special permission.
Now comes the difficult part: the first one has to disappear, otherwise it can be bought a second time, thus loosing vote points.
The only way a shoppable item will disappear is by removing the permission requirement. But a default player (with no additional personal permission) does not have a permission to remove since it inherits only the default group.

[Request]
So it would be nice to have a "one time execution" feature. Then something can be bought just once. After that, it would be nice if the item does not disappear. But rather grayed out. So it can be seen by the player that he has bought this item already. (Perhaps to go even further something like a counter how many times an item can be bought)

[Bug]
The slot allocation in the shop section cannot be removed. Otherwise, it will not be executed. The item is available, clickable, but the command is not executed.

[Minor]
It is not possible to allocate 2 items on 1 slot although only one is available at a single moment. This makes gapes inevitable.

**Comment by BenCodez** [comment]
I like the suggestion.

Don't know about the bugs though. I'll loook at it later.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Added the limit system. Just specifiy under Limit. Untested

Fixed the first bug.

That last bug isn't really a bug. You shouldn't be able to allocate 2 items on 1 slot. You can add as many rewards per item however. You won't need to set slots no more, I think (don't have time to test right now)

**Comment by x1p** [comment]
Tested and the "limited shop item" is not disabled after buying.
I thought maybe this was due to using a existing user database. So deleted the database, tested it once again. Same thing.

Icons seem to work just fine without assigning slots.

**Comment by BenCodez** [comment]
I'll have to test that later then.

**Comment by BenCodez** [comment]
Can I see the config?

**Comment by x1p** [comment]
This is a default config (from a test server) with only the vote shop area being filled with such function. (Look for the Homes_1 and so on)
https://hastebin.com/ifuwoziyig.bash

**Comment by BenCodez** [comment]
Found the problem, try now:
http://ben12345rocks.com/

**Comment by x1p** [comment]
Works indeed. Nice job

**Comment by x1p** [comment]
Now comes the difficult part: where does it stores its information. I need to edit the database in order to change the players that already bought this on my live server... I'll figure it out somehow.

**Comment by BenCodez** [comment]
In the user data, depends on what DataStorage you use

**Comment by x1p** [comment]
MySQL off course. I'll have to look into it.

**Comment by BenCodez** [comment]
It should be under a separate column

**Comment by x1p** [comment]
I saw it. I'll update soon. But I want every server to update same time, so the database won't see different version editting things that old versions might don't like.

**Comment by BenCodez** [comment]
Maybe wait until an official release? Which would be in a few days
