### ISSUE TITLE
Random extra vote points

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#433]
I got a player which reports getting 4 extra points.  A few weeks before I had almost the same issue with the same player, getting 15 points too much. This counts for probably more players which I haven't heard. ;-)

Scenario:
2 vote sites,
3 servers. (hub, game1 game2)

Player comes in the hub, gets 4 vote messages,
goes to server1, gets 4 vote messages,
goes to server2, gets 4 vote messages,
goes to server1.
From those 4 vote messages, only 1 or 2 of them are legit.
The messages were (in random order):
- Votesite1
- Votesite2
- Votesite1
- Votesite1

Apparently, there were 4 votes to much somewhere registrated.

How can I follow the votes being registrated?
What could be wrong here?

**Comment by BenCodez** [comment]
Latest version? Using the same database? Votifier setup?

**Comment by x1p** [comment]
VotingPlugin v 5.15.1
Same mysql database
Votifier set up via bungee with forwarding (proxy) to the different servers.
(Don't think its smart to display all the settings here. I can provide details, if only I know what part you might be interested in.)

Edit: I discovered I still had a older version of votingplugin running on an old server. Just disabled that one too.

**Comment by BenCodez** [comment]
Don't use the same mysql database and forward the vote to each server. That would cause what your seeing.

Do you want the player to be rewarded on each server?

**Comment by x1p** [comment]
Ehm no.

I just want a central database for the points.

The player must get the message on the server he is on.

**Comment by BenCodez** [comment]
Don't forward the vote to each server. Just to one of them.

**Comment by x1p** [comment]
I thought I had to set nuVotifier on every server and set `onlySendToJoinedServer: true` so only the server where the player is, fires the event and VotingPlugin catches that vote and sends it to the central database.

So you are saying:
Only put nuVotifier on the lobby/hub
Set `onlySendToJoinedServer:` to false I presume?
VotingPlugin on every server connected to a central database.
Am I right?

**Comment by BenCodez** [comment]
I'm not sure if you what you had would work. In theory it should of work, but not sure.

What you said to do is correct, it's what most people do.

**Comment by x1p** [comment]
Ok. I will put it into practice.
I find it quite difficult to understand how to setup a structure with multiple servers. There is not much documentation that explains this in a nutshell.

**Comment by BenCodez** [comment]
There is a few videos on it on the plugin page.
I'll probably have on something in it in the future

**Comment by x1p** [comment]
Do I understand correctly:
Bungee: nuVotifier
Lobby: nuVotifier + VotingPlugin
Other servers: VotingPlugin

**Comment by BenCodez** [comment]
Only issue with doing that is that players can get the reward on the lobby. I probably could make something for that. And all plugins on the same database.

**Comment by x1p** [comment]
Votingplugin will probably miss a votifier and give an error for that.
I'm afraid that the vote messages won't come through if players are on a server.

Our whole philosophy is that we have a central database and players are able to spend points on a server they wish.

**Comment by BenCodez** [comment]
# Disable this on a hub server for example
ProcessRewards: true

http://ben12345rocks.com/job/VotingPlugin/

Have that on the lobby. 

You may also wanna change this:

# Delay between background updates like signs and more
# Default: 3 Minutes
# Longer times result in longer wait in stuff updating after a vote, like topvoter
DelayBetweenUpdates: 3

^ That will determine how long it takes for the votes to be checked on each server.

**Comment by x1p** [comment]
```
# Disable this on a hub server for example
ProcessRewards: true
```
Why would I want to disable this? I my case, shouldn't matter where the player is, his vote must be stored into the database. Just that. It all points in the end, regardless of the server he's on. The only reward he gets are points.

I'll have to test this one.
I'm still planning to upgrade for 5.16 because I want all servers to update together and the weekend is not a good time to take servers down. So I'll prepare this one in addition with the 5.16 files.

**Comment by BenCodez** [comment]
it will still process everything and add the offline vote, just won't give the reward on the lobby/hub, so the player can get it on the other servers.

**Comment by x1p** [comment]
I'm not sure what to do with that. But we'll see.

**Comment by BenCodez** [comment]
Just have that set to false on the hub, the rest just leave.

**Comment by x1p** [comment]
On the game servers there won't be a nuvotifier if I understand correctly. So votingplugin will give
`[VotingPlugin] No VotifierEvent found, install Votifier, NuVotifier, or another Votifier plugin`
Is it alright to ignore that? I assume they listen to each other by something?

**Comment by BenCodez** [comment]
Yeah, that should be fine. It's just a warning to help avoid a simple mistake like that.

**Comment by x1p** [comment]
What is channel forwarding the vote? Is it a special channel, or via the database?
I'm on a shared host. It must not interfere with other servers, ports of messaging services.

**Comment by BenCodez** [comment]
whatever nuvotifier does + plus VotingPlugin database.

**Comment by x1p** [comment]
Ok. That's fine. That means It only takes some time till other servers find the vote in the database and send the message to the player.

**Comment by BenCodez** [comment]
By the time specified (that I showed you) or when the player logs in.

**Comment by x1p** [comment]
Roger that

**Comment by x1p** [comment]
The database does not sync at all. I've set the max connections a bit higher then 1. But still. Votes are not synced.

On the game servers, there is no message anymore. Players are wondering where their votes are.

Some players have gained around 20 votes today!
build 355

**Comment by BenCodez** [comment]
Turn the option for clear cache on update to true.

**Comment by BenCodez** [comment]
You also need the votesites to be in the votesites.yml with the same name.

**Comment by x1p** [comment]
> You also need the votesites to be in the votesites.yml with the same name.

Got that one already.

> Turn the option for clear cache on update to true.

Will do. Something like this?
```
ClearCacheOnUpdate: true
ClearCacheOnVote: true
```
But what will cause the sync to work again? What if someone buys something?
Any chance to get the messages pushed to other servers?

**Comment by BenCodez** [comment]
You can with mutliple rewards and specifing the server.

**Comment by x1p** [comment]
Still no sync.
I've got the impression that if a player checks his points, it is not looking it up in the database directly.

**Comment by BenCodez** [comment]
It reads from the cache which should get cleared every few mins

**Comment by x1p** [comment]
Did a test on a test server.
Changed my points in the database (as if lobby added point due to voting)
Waited several minutes.
Number of points did not change in game.
So sync does not work

**Comment by x1p** [comment]
Should I use VoteForwarder for bringing the messages to the game servers?

**Comment by x1p** [comment]
The points are not synced when a player joins.
Points are not synced regularly.
Only buying or voting in game will get the points written into the database.

Therefor: If a player buys something this happens:
Game server 1, Vote points = 20
Buying something for 10
Vote points 20 --> 10.
Writes to database: points = 10 (this goes well)

Player joins game server 2
No sync
Votes are there still 20 (votingplugin does not know database is changed)
Voting on a site -> +1 makes 21.
Over writes database: points = 21
Gained 11 points illegally.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Add AlwaysUpdate: true in your config.yml.

It's not gonna update because there is no votes on the server. Workaround with that ^

I got another solution if that doesn't work

**Comment by x1p** [comment]
I also have a plan B. ;-) It would certainly help if it would sync at join or disconnect.

I will try.

**Comment by x1p** [comment]
This version sure syncs after the 1 minute I've set it to.

**Comment by BenCodez** [comment]
Does it work for your needs now?

**Comment by x1p** [comment]
Yes.
Just to make sure that a sync is executed when someone joins, I have set an extra command.
We will soon find out if no one complains about extra/lost votes ;-)

**Comment by BenCodez** [comment]
Let me know. I'll probably make more changes on my end as well in the future.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Added this:
  
    # Clear mysql on player join always
    ClearCacheOnJoin: false

**Comment by x1p** [comment]
Ok. Nice. Will implement it soon.
I do find the description a little confusing: "Clear" obviously means "sync". This can be quite confusing for some maybe.

```
# Clear cache on update, setting to true reduces performance
ClearCacheOnUpdate: false

# Only update the background when needed when set to false
AlwaysUpdate: false

# Clear mysql on player join always
ClearCacheOnJoin: false

# Clears cache for the player who voted only
# Only effects if using mysql
# Would recommend for some bungee setups
ClearCacheOnVote: false
```

**Comment by BenCodez** [comment]
Clearing the cache will cause the plugin to pull from mysql, the cache is
there so doing /vote won't take 5 seconds.

**Comment by BenCodez** [comment]
Did some config improvements.
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml

Let me know what you think.

**Comment by x1p** [comment]
It's fine by me.
Couple of questions tho
```
# Clear cache on update, setting to true reduces performance
ClearCacheOnUpdate: false
```
This means that if someone buys something in the vote shop, it will be pushed to the database, right?
```
# Only update the background when needed when set to false
AlwaysUpdate: false
```
This also means that it will sync with the interval defined by `DelayBetweenUpdates: 3` right?

**Comment by BenCodez** [comment]
Yes and yes. I might need to clear cache every time someone buys from the
voteshop.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

It should clear cache before it processes a voteshop purchase, let me know how that goes.

**Comment by x1p** [comment]
That works. It's another great way to ensure that vote points cannot be abused in any way. This reduces the need for turning on `AlwaysUpdate`. But not always.

Scenario: only hub server connected to the (nu)votifier.
If admins have a central hub that adds the votes in the database, and the player is on another game server. The database is changed, without syncing the gameserver. Now suppose a player wants to check his points (vote points), he will still see his cached points number. The database is changed and only updates on /vote shop. So this might need a sync when /vote points or /vote gui is performed. So in this case I would still recommend `AlwaysUpdate: true`.

In my case: I have returned to my old setup. A nuvotifier on every server. (This is explained in most instruction video's). In this case, the database is only updated if the player is online. This ensures that the cache on the server where the player is, is updated. So the player sees his real number of voting points and sees his message that he has voted. When he returns to another server, the join update kicks in and ensures that the cache is updated on that server. This eliminates the need for a scheduled sync pretty much.

**Comment by BenCodez** [comment]
I like the idea, I'll try it later

**Comment by BenCodez** [comment]
Added a new option
UpdateWithPlayersOnlineOnly


http://ben12345rocks.com/job/VotingPlugin/

**Comment by BenCodez** [comment]
Version 5.16.1 is now available with all the new options :)

**Comment by x1p** [comment]
Great job. :+1: 
I think that closes this issue :-)
