### ISSUE TITLE
Placeholders not recognised

### ISSUE THREAD

**Issue by MirceaDumitrescu** [BenCodez/VotingPlugin#434]
So i'm using 1.13 with latest placeholder api and didnt have any placeholder issues so far. But for some reasons, the placeholders for this plugin arent recognised and returned as <unknown_palceholder>.

To be more exact, i'm trying to add it to UltimateBossBar. But i've also tested it with DeluxeChat for example and it doesnt recognize the placeholders.

**Comment by BenCodez** [comment]
Latest version? Latest placeholderapi expansion?

**Comment by silvasky54** [comment]
I hope this is ok, I didn't want to make a new issue for the same topic.

I'm having the same issue except it says the placeholder name such as %NeededVotes%

I'm using the latest version for 1.12 and the latest version of papi. One thing I have noticed is that papi is showing 0 placeholders for voting plugin.

**Comment by BenCodez** [comment]
@silvasky54 
Placeholderapi expansion? (don't remember if the latest expansion works on that build)
/papi parse work?

**Comment by silvasky54** [comment]
I've tried both 1.1.1 and 1.2

**Comment by silvasky54** [comment]
Sorry just saw the last bit. I'll check parse as soon as I get home.

**Comment by silvasky54** [comment]
Checked parse and it just prints the placeholder itself in chat.

**Comment by BenCodez** [comment]
Are you typing the correct ones?
https://github.com/Ben12345rocks/VotingPlugin/wiki/PlaceHolderAPI-Expansion

**Comment by silvasky54** [comment]
They didn't work in the latest version of papi but downgrading to an older version got it working

**Comment by BenCodez** [comment]
That's just because your using the version for 1.12. Nothing I can do.
