### ISSUE TITLE
Unable to change help message format (Release 5.13.6)

### ISSUE THREAD

**Issue by connorhsm** [BenCodez/VotingPlugin#435]
(Release 5.13.6 is used as [here](https://www.spigotmc.org/resources/votingplugin.15358/) it is stated to support my spigot version, 1.12.2)

In the config, customising the help page title & reloading works without any issues but customising the help page line & reloading shows no change.

_I'm doubting that this would even be supported being this is an outdated version. If this is the case, will you no longer be supporting anything apart from 1.13 (and future releases) at all?_

**Comment by BenCodez** [comment]
Did you solve this?

**Comment by connorhsm** [comment]
I found that another part of the config handled the message format, separate from the title formatting. Which is still weird, but was enough to fix my issue.
