### ISSUE TITLE
Suggestion: Register the vote but not increase their vote count.

### ISSUE THREAD

**Issue by Royster-85** [BenCodez/VotingPlugin#436]
Is it possible to add a setting where you can have multiple voting sites, get the rewards for each site but you only receive one vote in total from voting for that day?

**Comment by BenCodez** [comment]
Just remove the total manually?

**Comment by Royster-85** [comment]
Is there no way to stop it adding votes in the VoteSites.yml file?

**Comment by BenCodez** [comment]
AutoCreateVoteSites: true

Change that.

**Comment by Royster-85** [comment]
Ok, but how would I go about giving them rewards like extra Diamonds, Emeralds, etc for voting on the other sites? Sorry for asking some strange questions lol. Just thinking of other ways to improve my server :)

**Comment by BenCodez** [comment]
You won't be able to. You could just disable add totals in the config and add a total on the all sites reward.

**Comment by Royster-85** [comment]
Ok, I'll take a look at that and do some testing. Thanks for the help.
