### ISSUE TITLE
Feature: Setting/option to stop adding to vote totals or /av command to increment by 1 

### ISSUE THREAD

**Issue by Royster-85** [BenCodez/VotingPlugin#438]
Can you add a setting/option where you can stop the vote adding to the vote totals, or add an /av command which will increment the vote total by 1.

I think it would be a very useful addition to have

**Comment by BenCodez** [comment]
# Set this to false to disable the plugin adding totals
    # Not really recommended
    AddTotals: true

Already have it.

**Comment by Royster-85** [comment]
Ok, what about an /av command, similar to the /av AddPoints command but one for votes? Example: /av AddVote

**Comment by Royster-85** [comment]
You cant force a fake vote through to manually add a vote to it because if AddTotals is false, it doesnt increment it

**Comment by BenCodez** [comment]
/av SetTotal

Or use javascript to add it

I'll add a add total command though

**Comment by Royster-85** [comment]
That would be cool adding that. Also if it was linked to MilestoneCount variable in their player data, that would also be great. Thanks

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

/av addtotal
/av addmilestonecount

enjoy

**Comment by Royster-85** [comment]
Many Thanks. Im gonna have a play around with it for the next day or so as it may of resolved an issue ive seen on other servers that they want to use one voting plugin with multiple voting sites, but only one vote is registered. :D

**Comment by BenCodez** [comment]
Let me know how it goes. I haven't tested the commands yet.

**Comment by Royster-85** [comment]
Will do. Thanks

**Comment by Royster-85** [comment]
Commands work great. Can add and remove from total and milestone count. Also when they reach a milestone with any vote site, it only gives them one copy which is great. Want to do a bit more testing but need to know if they have any permission nodes attached to them? Thanks

**Comment by Royster-85** [comment]
Hi. 

So I managed to test it with 5 different voting sites. Having those 2 additional commands enables you to vote on all 5 sites and receive only one vote added to your totals. Which is exactly how I wanted it to work. I added them to the VoteSites file on the individual site settings, and made it take away the vote (You can use -1 at the end of the command to delete the vote count). So the commands allow you to manually add and remove vote totals from the AllTime and MilestoneCount settings in their Player Config file :D 
 
I did notice a small inconvenience when it came to Milestone Rewards, especially when the player is 2 votes away from the number set in the Milestones section in the Config file. When you vote on Site A, which is set to when you vote and it increments by 1, as intended. When you vote on site B/C/D/E, it increments again before the additional commands which I added to the individual settings for the sites in the VoteSites file can remove it. This triggers the Milestone settings in the config file. All this means is that the player can trigger the Milestone Rewards a day early. It will though sort itself out when they vote the next day as because as they've already received the Milestone reward, It doesn't trigger it a 2nd time which is good.

In essence, apart from the minor inconvenience above, this resolves the issue where you can vote on multiple sites and only receive one vote in total. And better still all from within one plugin, which I don't know any other plugin being able to do that. So thanks for adding them :D

I would like to ask another request though. In the /av SetTotal command, you can set the total of AllTime, Day, Week and Month. Would it be possible to add one for MilestoneCount there too?

Thanks

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

/av setmilestonecount

Should work just fine. Would disabling AddTotals and adding a total after all votes work too?

**Comment by Royster-85** [comment]
I'll test that this evening/morning and let you know.

**Comment by Royster-85** [comment]
Ok, I disabled the AddTotals setting and added the commands to add to the daily, weekly, monthly, AllTime and MilestoneCount totals (As disabling that setting obviously stops adding totals) to the Vote site I want to increment the totals. I noticed that when doing it manually, it doesn't trigger the Milestone settings in the config file when the conditions are met. However, when you vote on a 2nd site which is set not to increment the AllTime and MilestoneCount settings, it then triggers the Milestone config settings.

I dont know if its possible to set it that if you manually change the MilestoneCount using the newly made command, to check against the Milestone settings in the config and trigger when the conditions are met, without having to vote on a 2nd site to trigger the Milestone settings

I did check to see if vote points are added, and they do, so that is completely uneffected.

One thing I didnt check was if you add the totals manually with AddTotals disabled, if it then increments the vote streak. I'll check that out today if possible.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That should fix that. Not sure what else it needs to check. VoteStreak will still work, I think.

**Comment by Royster-85** [comment]
Cool thanks. I will test that out again this evening

**Comment by Royster-85** [comment]
I have good news. It works. It is set up where you can add multiple voting sites, receive rewards from them all, it still gives you the vote points, increments the vote streaks, still gives you the milestone rewards from the config, and best of all, it only increments the AllTime total and Milestone counts by 1. Many thanks for adding this feature and taking the time to configure it to the plugin. 

(On a side note, if you keep this feature in, could you capitalize the C in /av AddMilestonecount and /av SetMilestonecount? Only because the other commands have the same layout. :) Many Thanks)

**Comment by BenCodez** [comment]
I can look at that. Thanks for testing.

**Comment by Royster-85** [comment]
No problem. Thanks for making the enhancements :)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Already done.

**Comment by BenCodez** [comment]
In latest version
