### ISSUE TITLE
VoteStreak question - VoteStreak Percentages

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#439]
Does daily votestreak show the amount of days voted? If so, what counts as a day voted? e.g. I would like to do number of days whereby all websites have been voted on. Is this how it currently works, if not is there a way of doing this?
```
%VotingPlugin_DailyVoteStreak%  
%VotingPlugin_WeeklyVoteStreak%  
%VotingPlugin_MonthlyVoteStreak%  
%VotingPlugin_BestDailyVoteStreak%  
%VotingPlugin_BestWeeklyVoteStreak%  
%VotingPlugin_BestMonthlyVoteStreak%  
```

**Comment by BenCodez** [comment]
Yes. 1 vote needed. I didn't make it require all sites, as sometimes the site fails to send votes, but I might change it, or add an option for it.

**Comment by BenCodez** [comment]
I'm still debating this. I don't really want to make it require all votes to count (due to sites failing sometimes, or even server downtime). Only other solution would be to require a percentage of votes to count or something, not sure yet though.

**Comment by LogGits** [comment]
I mean, you can always make it optional. Personally, I would like it to only work if players have voted on all 4 websites. However, it would also be cool if it was setup so you can choose percentage. E.g. 100% or eve 60% etc 👍

**Comment by BenCodez** [comment]
I'll see.

**Comment by BenCodez** [comment]
Requirement:
      # Require certain percentage of votes
      UsePercentage: false
      # Percentage requirements of votes
      # 50 = %50
      Day: 50
      Week: 50
      Month: 50

https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L688
http://ben12345rocks.com/job/VotingPlugin/

Untested, but feel free to try it.
