### ISSUE TITLE
Question: Remove commands players dont have permissions to from Suggested List in 1.13

### ISSUE THREAD

**Issue by Royster-85** [BenCodez/VotingPlugin#443]
Not sure if its possible or not, but is it possible to remove any commands that players dont have access to from the suggested commands list in 1.13 onwards.

Thanks

Royster

**Comment by BenCodez** [comment]
It should already do that. I think there is an option for it as well.

**Comment by Royster-85** [comment]
Only reason I ask is because I use an alt as a tester and they can see all the adminvote commands. Admittedly they cant access them but they are viewable:

![2018-11-09_22 29 05](https://user-images.githubusercontent.com/44376499/48291835-c3116500-e46f-11e8-82b5-e770316df343.png)

**Comment by BenCodez** [comment]
I can't change that, that's server side. (you can disable that though). Tab completing for those commands will only work if you have perms for it though.

**Comment by Royster-85** [comment]
Its what I thought it was, but I thought I'd ask though. Thanks anyway 👍

**Comment by glorying16** [comment]
Ill start by saying I know NOTHING of developing plugins, so I am sure as heck not going to say youre wrong. But from what I have read and had very simply explained to me, this is actually more about how you put the commands in the plugin.yml. Something about having to add the permissions to it as well? Again I know nothing of developing, but im pretty sure this is actually possible. (Perhaps what ShaneBee said would make more sense to you than me lol https://www.spigotmc.org/threads/1-13-tab-complete.346550/#post-3218927 ) This is just something that I am REALLY wanting to get fixed (by many plugins).

**Comment by BenCodez** [comment]
I'll look at it, but it might not work as well as I want

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This work?

**Comment by glorying16** [comment]
Seems to be the same as before :/

Also I found this https://www.spigotmc.org/threads/event-handling-looking-for-feedback.347133/#post-3220501 Might be more descriptive than the last one.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Does this work?

**Comment by glorying16** [comment]
That one had significantly less options, but still a few that they dont have perms for unless its enabled by default. These were the options:
av reset
av reward
av serverdata
av triggerplayervoteevent
adminvote convert

**Comment by BenCodez** [comment]
I got no idea on that right now, I'll do more testing later. Any errors in console at startup?

**Comment by glorying16** [comment]
Only that I haven't received votes yet, which is normal (test server).

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Found the cause.

**Comment by glorying16** [comment]
Looks good except for a few things still popping up:
/adminvote
/votegivereward
/voteinfo
/votingpluginvaluerequestinput

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I got rid of the 2 middle ones. The other ones I'm not sure how to handle, since there isn't a specific permission for them.
