### ISSUE TITLE
[VotingPlugin] No name from vote on ....

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#447]
Bungee gets a vote. nuVotifier takes the vote and distributes it.
Lobby server should pick it up since the player is there online.

Log:
```
[VotingPlugin] No name from vote on voteblahblahblahsite
```
Player doesn't get it's vote

I've seen anonymous in the past, but this "no name" one is new.
What may be the cause?

VotingPlugin version 5.16.1 (stable one from spigotmc)

**Comment by BenCodez** [comment]
Either the vote site, or nuvotifier distributing the vote.
