### ISSUE TITLE
Cloud not load the plugin

### ISSUE THREAD

**Issue by Zed9K** [BenCodez/VotingPlugin#449]
Plugin Version : 5.16.2
Server Version : 1.12.2
Logs : https://hastebin.com/enobanomop.sql

**Comment by BenCodez** [comment]
1. Redownload the jar? It must of not downloaded correctly.
2. That version may not work on 1.12, try 5.13.6 if that's the case.

**Comment by Zed9K** [comment]
> 1. Redownload the jar? It must of not downloaded correctly.
> 2. That version may not work on 1.12, try 5.13.6 if that's the case.

ill try to now, but i have had 5.16.1 and it was working fully. on my 1.12.2 server.

**Comment by Zed9K** [comment]
Weird, i reuploaded it and now it works.
