### ISSUE TITLE
Permissions issue with Vote Commands

### ISSUE THREAD

**Issue by silverwolfg11** [BenCodez/VotingPlugin#452]
My players are denied access to any vote commands (except the basic /vote) such as /voteshop, /votechoices, /votetop, etc. They get the "I'm sorry you don't have permission to perform this command..." message when they try to run these commands. 

I confirmed that they have the permission VotingPlugin.Player. 
I further tested this by giving them a permission to a specific command. I gave them the perm VotingPlugin.Commands.Vote.Shop to access /vshop, however **it still did not work**.

I am only able to access these commands when I am a server operator (when I'm opped).

I am running a server on Spigot 1.13.2, using the LuckPerms permission plugin (it is not an issue with my permissions plugin), and have Vault installed.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This should work for now.

**Comment by BenCodez** [comment]
Latest version should work.
