### ISSUE TITLE
What does SetRequestMethod do?

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#458]
As the title says what is the use of "SetRequestMethod" and from what it looks like shouldnt it be an admin vote thing?

**Comment by BenCodez** [comment]
I think there use to be some user commands to required that, but it's pretty harmless. 

It changes what input method to use when the plugin asks for input.

**Comment by LogGits** [comment]
Input method? for commands?

**Comment by BenCodez** [comment]
I think it's mostly for admin commands now.

**Comment by LogGits** [comment]
Ah ok, i guess it would be more fitting as an `av` command

**Comment by BenCodez** [comment]
Probably, will do later.

**Comment by BenCodez** [comment]
Implement for the next version.

**Comment by LogGits** [comment]
Legend 🙂
