### ISSUE TITLE
HELP. CHECK AND SOLVE IT PLEASE.

### ISSUE THREAD

**Issue by Erlur** [BenCodez/VotingPlugin#459]
Check the file and please correct what i did wrong ! i don t know why i don t get the rewards i setted for each website

# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  ExampleVoteSite:
    Enabled: false
    Name: ExampleVoteSite
    Priority: 5
    ServiceSite: PlanetMinecraft.com
    VoteURL: link to vote URL here, used in /vote
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - say hello
      Messages:
        Player: You voted
  §2Minecraft MP:
    Enabled: true
    ServiceSite: minecraft-MP
    VoteURL: https://minecraft-mp.com/server/209584/vote/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 675'
        - 'give %player% diamond 7'
        - 'crate key %player% Gear 1'
        - 'crate key %player% Shields 1'
      Messages:
        Player: .
  §3Minecraft Server:
    Enabled: true
    ServiceSite: MINECRAFTSERVER
    VoteURL: https://minecraftservers.biz/servers/142862/vote/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 450'
        - 'crate key %player% Shields 1'
        - 'give %player% diamond 4'
      Messages:
        Player: .
  §4Planet Minecraft:
    Enabled: true
    ServiceSite: PLANETMINECRAFT
    VoteURL: https://www.planetminecraft.com/server/narlea/vote/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 450'
        - 'give %player% diamond 5'
        - 'crate key %player% Gear 1'
        - 'crate key %player% Potions 1'
      Messages:
        Player: .
  §eMinecraft SerVers:
    Enabled: true
    ServiceSite: MINECRAFTSERVERS
    VoteURL: https://minecraftservers.org/vote/522787
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 450'
        - 'give %player% diamond 8'
        - 'crate key %player% Tools 1'
        - 'crate key %player% Gear 1'
      Messages:
        Player: .
  §1TopG:
    Enabled: true
    ServiceSite: TOPG
    VoteURL: https://topg.org/Minecraft/in-502965
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 450'
        - 'give %player% diamond 5'
        - 'crate key %player% Gear 1'
        - 'crate key %player% Shields 1'
      Messages:
        Player: .
  §aMineVotes:
    Enabled: true
    ServiceSite: MINEVOTES
    VoteURL: https://www.minevotes.com/vote/372
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 450'
        - 'give %player% diamond 3'
        - 'crate key %player% Tools 1'
        - 'crate key %player% Gear 1'
      Messages:
        Player: .
  §6Minecraft-Servers:
    Enabled: true
    ServiceSite: MINECRAFT-SERVERS
    VoteURL: https://minecraft-server.net/vote/narlea
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'eco give %player% 450'
        - 'give %player% diamond 8'
        - 'crate key %player% Gear 1'
        - 'crate key %player% Potions 3'
      Messages:
        Player: .
  TopG_org:
    Enabled: true
    ServiceSite: TopG.org
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward: []

**Comment by BenCodez** [comment]
Pastebin please?

**Comment by BenCodez** [comment]
Are you still looking for help?
