### ISSUE TITLE
Crash with VotingPlugin v5.16.3

### ISSUE THREAD

**Issue by mart-r** [BenCodez/VotingPlugin#460]
Looks like the server got stuck with VotingPlugin while executing an event.
Log:
https://gist.github.com/mart-r/0ca48dff367ddd8dbd0fa95f955ad2ef

**Comment by BenCodez** [comment]
Config?

**Comment by mart-r** [comment]
It works normally most of the time. But today it crashed us (as linked above).
Here's the config (removed ip and passwords and the like):
https://gist.github.com/mart-r/fe19cc3e1da56621c1ef84a08b0c52dc

**Comment by BenCodez** [comment]
CheckNameMojang: true

Disable that and see if that helps.

**Comment by mart-r** [comment]
Like I said, I've only had this happen once and we've had the plugin for months now. So I can change that setting, but I wouldn't really know if it changes anything.
I thought I'd just report this in case there is anything obvious that can cause this.

We'll surely try the setting if or when we get another similar crash.
Thanks for the prompt replies!

**Comment by BenCodez** [comment]
Any update on this?

**Comment by mart-r** [comment]
I've not had the same issue since.

**Comment by BenCodez** [comment]
Closing for now, reopen if you have issues

**Comment by mart-r** [comment]
It's happening again:
https://gist.github.com/mart-r/16d686775d188bc7a5a8a265941d58e6
03.01 04:07:43 [Server] INFO [PlugMan] Plugin Information: VotingPlugin
03.01 04:07:43 [Server] INFO - Version: 5.17.3
EDIT:
I've already disabled `CheckNameMojang: true` -> `CheckNameMojang: false`

**Comment by BenCodez** [comment]
Seems to have issues with getting info from sqlite user file. Switch maybe?

**Comment by mart-r** [comment]
Are you proposing MySQL instead of SQLITE might fix the issue?
Had another crash today:
https://gist.github.com/mart-r/8c9a0dc9b1a307b61ed93526d1a9a574

**Comment by BenCodez** [comment]
This help at all?
http://ben12345rocks.com/job/VotingPlugin/

That crash looks to be a bit different. See if that helps

**Comment by BenCodez** [comment]
Closing this for now, reopen if you still have issues.
