### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RensDreuning** [BenCodez/VotingPlugin#461]
Hi,

I am using v5.13.6 together with the newest version of votifier and vault on a 1.12 server. Almost everything works fine, even test votes, but when someone votes on a site (like Top_g.org) you get no message, no reward, nothing. How can I solve this?

**Comment by BenCodez** [comment]
That's an issue with votifier. Try changing ports?

**Comment by RensDreuning** [comment]
Thank you, it's solved!!!!
