### ISSUE TITLE
/vote not working with 5.1.7

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#462]
Pastebin error: https://pastebin.com/2j9MvZMu
VotingPlugin version: 5.1.7
Paper version: git-Paper-475

**Comment by BenCodez** [comment]
Server version? More details? Also it's 5.17

**Comment by ghost** [comment]
Server is running Paper release 475 for Minecraft 1.13.2. Error is also present in version 5.16.3, which is interesting because we assumed that this error was the cause of /vote not working in version 5.17, but that now appears to be a completely separate issue (since /vote is working in 5.16.3 even with the error.)

**Comment by BenCodez** [comment]
It was working or it wasn't working in the previous version?

**Comment by ghost** [comment]
@Ben12345rocks /vote is not working in version 5.17 and above (it tells players they do not have permission for the command). /vote IS working in 5.16.3.

The error I reported is a separate issue and is present in both versions.

**Comment by BenCodez** [comment]
How about 5.17.1?

**Comment by ghost** [comment]
The vote command does not work in 5.17.1

**Comment by BenCodez** [comment]
What does it do? It seems to work fine for everyone else running the later versions. I don't have enough details to determine anything.

**Comment by ghost** [comment]
Figured it out. Guess you just added the permission `VotingPlugin.Commands.Vote`.
