### ISSUE TITLE
/vote gui not working

### ISSUE THREAD

**Issue by TheSmuelGuy** [BenCodez/VotingPlugin#464]
The /vote gui command does not work and it doesn't work in the other guis as well. Please, can you help me!.
Plugins: 
![image](https://user-images.githubusercontent.com/45816912/49861642-6cbd8a80-fe50-11e8-8a6f-3a8bc1019bee.png)
I am using Spigot 1.12.2 and I am using NuVotifier and Vault.

**Comment by BenCodez** [comment]
Errors?

**Comment by TheSmuelGuy** [comment]
No. I dont think there are any errors that appear in the console. I'm on my phone E rn. I'm from Australia so I'll see in the morning. But apart from that I don't think there are any errors. It doesn't work for my friend that is opped and has '*' permission. I can check in the morning. Is that ok?

**Comment by BenCodez** [comment]
Make sure you using 5.13.6 for 1.12, the later versions don't fully support 1.12 or lower

**Comment by TheSmuelGuy** [comment]
Ok. I'll try that

**Comment by TheSmuelGuy** [comment]
Ok. thank you it works fine! I don't know what to do without your help xd. I will keep using your plugin until the end of time!
