### ISSUE TITLE
Votestreak question

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#467]
Is there a way to check a players current total votestreak while they are offline? `/votestreak <player>`
gives daily,weekly,monthly but doesn't say their current votestreak.

**Comment by BenCodez** [comment]
Check the user data? /av gui can do it

**Comment by LogGits** [comment]
`/av users <username>` doesn't have a CurrentVoteStreak

**Comment by BenCodez** [comment]
Go to edit data.
/vote streak (player) I guess works too.
