### ISSUE TITLE
Avtotal bug

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#468]
Av total does nothing but has tabcomplete for main command and says that its an unknown command.

**Comment by BenCodez** [comment]
There is no /av total?

**Comment by LogGits** [comment]
ye there is no `/av total` either

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/Commands-&-Permissions

There is no /av total command right now.

**Comment by LogGits** [comment]
Yes but tabcomplete is saying https://gyazo.com/703c4cfae93815228e1b45b78fb55be2

**Comment by BenCodez** [comment]
It should be /avaddtotal

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Fixed here.
