### ISSUE TITLE
VoteStreaks don't update until the end of the day

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#469]
`%VotingPlugin_DailyVoteStreak%` doesn't update instantly. It requires a complete restart to update the value. It would be useful if this updated at the same speed as a vote placeholder does.

**Comment by BenCodez** [comment]
It should update instantly. Atleast after the plugin updates it in the background.

**Comment by LogGits** [comment]
It isnt updating instantly. Using `/papi parse <my username> %VotingPlugin_DailyVoteStreak%` on a user who just voted on all 4 websites it still says `0` when it should be `1`.

**Comment by BenCodez** [comment]
The plugin waits until the next day to update it. It's working the way I made it. It's the only way to be fully reliable.

**Comment by LogGits** [comment]
It should be set to 1 upon completing votes on the first day. It doesn't make sense to start at 0. If by default it starts at 0 and a user votes on the websites it should be increased by 1.

**Comment by BenCodez** [comment]
At the end of the day/week/month the plugin checks if it should increase the vote streak amount. 

This is the system right now, I don't really intend to change it any time soon, since it has worked pretty well.

**Comment by LogGits** [comment]
For the first one, why not set it up using vote percentage so when a user has voted on, for example, 50% of the websites, it triggers their streak to increase. There wouldn't be a need to check at the end of the day, you could store uuid and timestamp and compare to check if its within 24 hrs. I have had a lot of people telling me that it is inaccurate even though i know its accurate, it just doesn't update as expected.

**Comment by BenCodez** [comment]
It is possible to setup percentages (Last update). What if 1 person votes at 1 am. Then at 1 am the next day it resets, but it's still possible to vote the rest of the day.

Anyway. I'll probably look more into this later. It still works fine, so I'll save it for a future update.

**Comment by OfficialAndyX** [comment]
I have also been having this problem. I thought it was a bug.

**Comment by LogGits** [comment]
I see what you are saying. VoteStreakDaily should be on a daily cycle like you mentioned. I just think it should be instantly updated when a user does the voting. Otherwise, we have to wait awhile to reward a player for hitting their vote streak as opposed to instantly giving them our custom rewarding. We also keep a tablist of votestreaks and have had people complain that they voted and the system didn't update. Loving the plugin so far, keep up the great work 👍

**Comment by BenCodez** [comment]
I'll be sure to look into making it a bit better.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Made a change to it. Untested, use at your own risk.

**Comment by LogGits** [comment]
This gets resolved with #472
