### ISSUE TITLE
Problems with executing commands

### ISSUE THREAD

**Issue by kennethlinzj** [BenCodez/VotingPlugin#470]
The plugin recognises when there's a vote, but doesn't execute the commands. I've followed the guides and the video tutorials and made sure to do exactly as instructed, but it doesn't work. On 1.13.1, and using NuVotifier and Minecraft-MP_com.

[Reports.1544980176274.zip](https://github.com/Ben12345rocks/VotingPlugin/files/2683783/Reports.1544980176274.zip)

**Comment by BenCodez** [comment]
You have 2 voting sites for Minecraft-MP, just use the other one and delete the one.

**Comment by kennethlinzj** [comment]
Thanks!

Kenneth
