### ISSUE TITLE
Some voting links wont work

### ISSUE THREAD

**Issue by Scabista** [BenCodez/VotingPlugin#473]
Hey, so out of my 7 voting sites, I cant seem to get two to work. That would be "Votesite2" and "votesite7" They don't mark as voted for in the GUI, nor give rewards to players. All of my other sites work perfectly though. Any idea what I've messed up here?

"/av servicesites" command output:
https://i.imgur.com/ZeWKA8f.png

VotingSites:
https://gist.github.com/Scabista/0fca199f477b719458c9b9a71523e779

Config:
https://gist.github.com/Scabista/0c531722b61b5f30a18b8152621be611

**Comment by BenCodez** [comment]
Your service sites need to be correct.

**Comment by Scabista** [comment]
Define "correct." As far as I can tell I've filled them out the exact same way as I've done the rest. I've checked the sites public keys, votifier IPs, ports, and all as well. The service site links are formatted the same way as the working ones, and will direct you to the websites when pasted in the url bar.

**Comment by BenCodez** [comment]
Vote on the site and it will tell you the service site. Some voting sites don't use the url as the service site.

**Comment by Scabista** [comment]
Awesome, I did not know about that. Thanks my dude.
