### ISSUE TITLE
Error on Starting up ( Spigot 1.12.2 )

### ISSUE THREAD

**Issue by Zed9K** [BenCodez/VotingPlugin#476]
Hello, i would like to report an error i keep getting every time i turn on my server,
i have Spigot 1.12.2
the plugin Version is 5.17.1
here is the error i get
`[14:19:41] [Server thread/ERROR]: [VotingPlugin] Plugin VotingPlugin v5.17.1 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.PlayerCommandSendListener because org/bukkit/event/player/PlayerCommandSendEvent does not exist.
`

**Comment by BenCodez** [comment]
It will work fine in 1.13. 1.12 and below aren't fully supported, so you'll have to just ignore it.

**Comment by Zed9K** [comment]
okay, thanks.
