### ISSUE TITLE
Error on startup, mentions SQL and Java

### ISSUE THREAD

**Issue by almateoskott** [BenCodez/VotingPlugin#477]
Seeing error on startup.  Tested with latest build 520 from Jenkins.  Could be my SQL or could be plugin--I don't know enough about Java to figure it out.  It doesn't seem to actually affect the results of the Voting, the votes still go through, produce rewards, etc.  

Running Spigot 1.13.2  /version says:
CraftBukkit version git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Here is what I see in the logs.  

------------
28.12 08:47:00 [Server] WARN ... 8 more 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1197) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:939) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2739) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2373) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) 28.12 08:47:00 [Server] WARN Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'PlayerName' at row 18 28.12 08:47:00 [Server] WARN at java.util.TimerThread.run(Unknown Source) 28.12 08:47:00 [Server] WARN at java.util.TimerThread.mainLoop(Unknown Source) 28.12 08:47:00 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142) 28.12 08:47:00 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:546) 28.12 08:47:00 [Server] WARN at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java) 28.12 08:47:00 [Server] WARN at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1013) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1218) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:408) 28.12 08:47:00 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) 28.12 08:47:00 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source) 28.12 08:47:00 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) 28.12 08:47:00 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) 28.12 08:47:00 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 28.12 08:47:00 [Server] WARN java.sql.BatchUpdateException: Data truncation: Data too long for column 'PlayerName' at row 18

--------------

Thanks.

**Comment by BenCodez** [comment]
One player name is really long, any way for me to see the list of players on the database?

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That should fix it.
