### ISSUE TITLE
Vote party exhausts threads

### ISSUE THREAD

**Issue by creator3** [BenCodez/VotingPlugin#480]
With `VoteParty.GiveAllPlayers: true`, a bunch of async tasks are created for giving rewards to all the offline players. Too many threads get created, and the server crashes from "OutOfMemoryError: unable to create new native thread"

`BLOCKED Craft Scheduler Thread - 2818: com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.addOfflineRewards(User.java:150)
 com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.Reward.giveReward(Reward.java:520)
 com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.RewardHandler$2.run(RewardHandler.java:280)
 org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
 org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)`

**Comment by BenCodez** [comment]
Latest version?
Rewards?

**Comment by creator3** [comment]
Sorry, I might not have communicated well, but I'm pretty sure I already know the cause of the issue.

With VoteParty.GiveAllPlayers enabled, all players are given rewards, as intended (see [this line in VoteParty.java](https://github.com/Ben12345rocks/VotingPlugin/blob/2d5208a5683f5cdd2678cba36803ba26c2247a4f/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/VoteParty/VoteParty.java#L206))

In order to give each player their reward, an async task is scheduled (see [this line in RewardHandler.java](https://github.com/Ben12345rocks/AdvancedCore/blob/786ef888e057f4bbe9b09c970e39a26341f2af4d/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/Rewards/RewardHandler.java#L275))

Normally, this is no problem, but with a bunch of players in the database all being given rewards, it runs into trouble.
The Bukkit scheduler creates threads to accommodate all the async tasks (one for each player in the database), crashing the server.

**Comment by BenCodez** [comment]
How about now?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by BenCodez** [comment]
Any update on this?

**Comment by creator3** [comment]
Looks good! Thanks
