### ISSUE TITLE
/vote Command permission - Spigot 1.13.2 / VotingPlugin Build #547

### ISSUE THREAD

**Issue by DeadIntermediate** [BenCodez/VotingPlugin#481]
I have added the permissions "VotingPlugin.Commands.Vote" but still was not able to perform the command.

**Comment by BenCodez** [comment]
Just type /av perms for all the permissions

**Comment by DeadIntermediate** [comment]
I am not sure, you notice, but the list is so long, I can only see maybe half of it?

**Comment by BenCodez** [comment]
Use console, or try /av perms (player)

**Comment by DeadIntermediate** [comment]
I got this as responce: [10:36:19 INFO]: No valid arguments, see /adminvote help!

**Comment by BenCodez** [comment]
Latest version? What did you type?

**Comment by DeadIntermediate** [comment]
#build #547

And I typed in console: av perms DeadIntermediate

**Comment by BenCodez** [comment]
I guess look at wiki page, can't look to much on my phone.

**Comment by DeadIntermediate** [comment]
I fixed it.
