### ISSUE TITLE
/vote top command server lag

### ISSUE THREAD

**Issue by andris155** [BenCodez/VotingPlugin#485]
https://www.youtube.com/watch?v=MrecNTcZ7L0

**Comment by BenCodez** [comment]
The plugin is waiting on the server to get the skulls, only solution is to preload it.

**Comment by BenCodez** [comment]
This help?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by andris155** [comment]
No :/
![jegyzet 2019-01-07 140253](https://user-images.githubusercontent.com/8324198/50769705-1ee84680-1285-11e9-8f5b-00c2dffbb51b.jpg)

**Comment by BenCodez** [comment]
Can you provide more details on that?

**Comment by BenCodez** [comment]
This any better?
http://ben12345rocks.com/job/VotingPlugin/

Turn debug on and show me the console when using the command.

**Comment by andris155** [comment]
No better. I enabled debug on config and no write extra information.
```
[21:26:31] [Server thread/INFO]: andris155 issued server command: /av reload
[21:26:34] [Server thread/INFO]: andris155 issued server command: /vote top
```

**Comment by BenCodez** [comment]
Hmm, I'll do more testing. What kind of lag are you getting?

**Comment by BenCodez** [comment]
Is there a way I can get a copy of your database? Would make my testing better.

**Comment by andris155** [comment]
[Users.zip](https://github.com/Ben12345rocks/VotingPlugin/files/2739648/Users.zip)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This should help. The first time opening the GUI will be slow, but after that it should be good until restart

**Comment by andris155** [comment]
Thanks

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Does this help more?

**Comment by BenCodez** [comment]
I also added an option to disable skulls in vote top, which solves the loading time

**Comment by Matthew777k** [comment]
```
# If true, plugin will send scoreboards on some commands
SendScoreboards: false

```
Changing this from true to false fixed the issue for me. The issue is most likely caused by the plugin conflicting with featherboard?

**Comment by BenCodez** [comment]
There is no reason for that to do that. Interesting, will look into more later.

**Comment by BenCodez** [comment]
Are you using the GUI still? There is no way that option would make any difference if your using the GUI.

**Comment by Matthew777k** [comment]
This is a different user. For me I wasn't using the GUI.

**Comment by BenCodez** [comment]
@Matthew777k I guess that would explain it.
