### ISSUE TITLE
Error Giving Rewards Back to Offline Player

### ISSUE THREAD

**Issue by falceso** [BenCodez/VotingPlugin#486]
Well to begin with, I accidentally upgrade to the latest version and downgraded back to 5.16.3 since I'm still on 1.12.2 for this server.

The plugin works perfectly fine when online, but the moment I leave and do a few more vote sites. It collapses to only 1 reward. In addition, there is sometimes some lingering rewards coming in when you rejoin a couple of times.
Console Log:
https://gist.github.com/falceso/dd8b7d971ddc7ceb3bda1d6603a05149

Config:
https://gist.github.com/falceso/e6a3522253273f0bff868a1a55ea3212

**Comment by BenCodez** [comment]
Your using an older version, not much I can do. The latest version sort of works on 1.12, you can try it.

**Comment by falceso** [comment]
The latest version does work, except the useful GUI no longer works. It also appears that rewards are lingering when joining a couple of times. Clearing cache resolved that issue but continues afterwards.

 I might be able to upgrade this server to 1.13 but it's a bit of a hassle with the method I use.

**Comment by BenCodez** [comment]
Well, I can't update the older versions.
