### ISSUE TITLE
Vote Parties execute commands and rewards multiple times

### ISSUE THREAD

**Issue by Leomelonseeds** [BenCodez/VotingPlugin#492]
Not sure if this feature is intentional, but vote parties will execute the "Rewards:" section multiple times (often spamming the chat with commands such as /eco give). This resulted in a broken economy for my server.

The "Commands:" section also seemed to activate twice, at a much greater interval though.

I do not know if this is intentional or not but you must fix this.

**Comment by BenCodez** [comment]
Rewards execute for each player and Commands each voteparty

**Comment by Leomelonseeds** [comment]
I see. So just to clarify, the rewards section is executing the reward from console for each online player? And the commands execute once each vote party?

**Comment by BenCodez** [comment]
For every player to recieve the reward (whatever is set) and correct

**Comment by Leomelonseeds** [comment]
Alright I see. But there was one strange occurence in which the command executed twice. I have no idea why but it happened like a few minutes after the first time the command was dispatched.

**Comment by BenCodez** [comment]
Show me the console log when that happens?

**Comment by Leomelonseeds** [comment]
Well, the console log only says “Console issued server command: (command).” Nothing related to votingplugin. I am not entirely sure if its votingplugin that caused it, but that is my only conclusion. I will be testing later today again to test this out.

**Comment by BenCodez** [comment]
What's the command?

**Comment by Leomelonseeds** [comment]
Simple command. "w M310N hi", M310N is my ign

**Comment by BenCodez** [comment]
Does that work from console?

**Comment by Leomelonseeds** [comment]
Yes it does

**Comment by BenCodez** [comment]
Can you pastebin your Config.yml?

On Jan 28, 2019 5:53 PM, "Leomelonseeds" <notifications@github.com> wrote:

Yes it does

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/492#issuecomment-458334845>,
or mute the thread

**Comment by Leomelonseeds** [comment]
Here ya go: https://pastebin.com/36CiHLEc

**Comment by Leomelonseeds** [comment]
By the way, it seems that the command is executing whenever someone joins the server. Not for everyone though, only for a certain few. I don't see a pattern.

**Comment by BenCodez** [comment]
Why not just do an individual command? I think that would solve a lot of issues.
Also where is that command you have set? You have no vote party rewards set other than global commands. Unless it's executing a reward file somewhere.
