### ISSUE TITLE
Question About Rank Promotion

### ISSUE THREAD

**Issue by justinhike1** [BenCodez/VotingPlugin#494]
I'm not sure if this is the correct place to put this, but I am really struggling trying to do a rank promotion with a certain amount of votes. I am currently using LuckPerms as my permission base.

I am trying to run the command 'lp user <player> parent set <group>' as a reward for voting so many times. For example, members will move from guest to member after 9 total votes. I have a couple of questions..

1. What section would I put this under? Would I place it in the consecutive section or milestone section?
2. Would I run it as command or console? I have tried both ways and couldn't get anything to work. 
3. I'm not sure which version of the player tag I should use. I've tried @p, %player%, and <player>. I'm not sure if I'm even in the ballpark in terms of writing this command correctly.

Any help would be greatly appreciated!

**Comment by BenCodez** [comment]
1. Milestones
2. Just under Commnads: will work
3. %player%

**Comment by justinhike1** [comment]
Thanks for the quick response! So it should look like this?

MileStones:
  '9':
    Enabled: true
    Rewards: 
      Commands:
       - 'lp user %player% parent set [name of group]' (without [] obviously.

**Comment by BenCodez** [comment]
Yeah, I can't see your formatting, but that's the idea.

**Comment by justinhike1** [comment]
Just tried it out and it worked. Thank you so much!

**Comment by justinhike1** [comment]
Shoot, I have another question. As I'm working through this, I'm trying to make it so that the command doesn't work on certain players. For example, I would like the admin to vote but not be moved to the member group. How can I make that work? Is there a way to negate the command for specific players?

**Comment by BenCodez** [comment]
Make it require permission would be the easiest way

**Comment by justinhike1** [comment]
Thanks for the response, I will try it out soon and let you know how it worked out!

**Comment by justinhike1** [comment]
Okay, I'm struggling to figure this out. Sorry to be such a bother. Could you walk me through how I would make that specific command require a permission?

**Comment by BenCodez** [comment]
Rewards:
     RequirePermission: true
     Permission: 'VotingPlugin.CommandReward'

**Comment by justinhike1** [comment]
I think that worked! Thank you again for all of the help. I really appreciate it!
