### ISSUE TITLE
Monthly top voter rewards not being handed out.

### ISSUE THREAD

**Issue by mibby** [BenCodez/VotingPlugin#495]
VotingPlugin dev 586

@Ben12345rocks The monthly top voter rewards do not seem to give out at the start of the new month. None of the top voters have received their reward (in-game key item and permission node).

**Comment by BenCodez** [comment]
Did the messages get sent out?

**Comment by mibby** [comment]
I assume it would only send the message to players if they were online, as it isn't an in-game mail? Checking the logs, I could not find any notification of VotingPlugin handing out the rewards or messages.

**Comment by BenCodez** [comment]
Turn debug on to get the messages when rewards are given out.

**Comment by mibby** [comment]
Alright, I'll do that for future reference to keep track of VotingPlugin events. However shouldn't these rewards been given out as soon as the month rolled over? VotingPlugin did detect that at the start of the new month.

```
[00:01:31] [Timer-2/INFO]: [VotingPlugin] Time change: DAY, Fake: false
[00:01:31] [Timer-2/INFO]: [VotingPlugin] Time change: MONTH, Fake: false
```

**Comment by BenCodez** [comment]
It will process the rewards and give it when player is online.

**Comment by mibby** [comment]
The players have logged in since the new month started. However the server has also restarted between the roll-over date and them logging in again. One of the top voters did manage to login an hour before the restart, but he did not receive his rewards. All 3 top voters are affected without any rewards after logging in again.

**Comment by BenCodez** [comment]
I'll do some testing, but I'm sure it still works

**Comment by mibby** [comment]
Okay. Is there any reason why it would not work in my case? 

I have the default 2 Example.yml rewards and two MileStone_#_Rewards.yml files as well. However the top monthly voter rewards should be handled by what's configured in the main config.

**Comment by BenCodez** [comment]
No idea, I'll try it later.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Fixed the problem.

**Comment by mibby** [comment]
Thanks! I'll update to the newest dev build and let you know if it still doesn't work next month. :P Don't really use the daily or weekly top voter rewards, but I'll assume you got it covered now.
