### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by nilsrob1** [BenCodez/VotingPlugin#496]
How can I add custom items as rewards? I would like to add some crate keys.

**Comment by BenCodez** [comment]
Look in the example basic reward

**Comment by nilsrob1** [comment]
I mean in the vote shop so peoplw can use vote points on crate keys

**Comment by BenCodez** [comment]
Use a command for that.
Item format works the same as rewards.

**Comment by nilsrob1** [comment]
I dont get what u mean by basic reward

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleBasic.yml

**Comment by nilsrob1** [comment]
Oh so I can jsut copy that over?

**Comment by BenCodez** [comment]
Not sure what your trying to do but I guess so.

**Comment by nilsrob1** [comment]
I want to make an item just like this
https://cdn.discordapp.com/attachments/518907267039494169/541061666536947752/cratekey.png

**Comment by BenCodez** [comment]
Just copy it over

**Comment by nilsrob1** [comment]
This is what I did:
        Tripwire Hook:
          # Item ID
          Material: 'TRIPWIRE HOOK'
          # Item Data (Eg 1:4, data is 4)
          Data: 0
          # Amount of items
          # Should be greater than 0
          Amount: 1
          # Item name
          # Remove this line for no name
          Name: 'Chest Crate Key'
          # Lore
          # Remove this line for no lore
          Lore:
          - 'Right-click on a "Chest" crate to win an item!'

But how do I add enchants, I see that I need unbreaking 1

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleBasic.yml#L59

It's actually in the example.

**Comment by nilsrob1** [comment]
**Does this look correct?**
        Tripwire Hook:
          # Item ID
          Material: 'TRIPWIRE HOOK'
          # Item Data (Eg 1:4, data is 4)
          Data: 0
          # Amount of items
          # Should be greater than 0
          Amount: 1
          # Item name
          # Remove this line for no name
          Name: 'Chest Crate Key'
          Enchants:
           unbreaking: 1
          # Lore
          # Remove this line for no lore
          Lore:
          - 'Right-click on a "Chest" crate to win an item!'

**Comment by BenCodez** [comment]
I don't know. I can't see your formatting like that. It should look like the example. Find out by trying it.

**Comment by nilsrob1** [comment]
Its not even in the shop? you know what could be wrong?

**Comment by BenCodez** [comment]
Yml error?

**Comment by nilsrob1** [comment]
There is no error, I just have the basic 1 diamond for 3 VP in the vote shop.

**Comment by BenCodez** [comment]
Pastebin your full config.

**Comment by nilsrob1** [comment]
https://pastebin.com/3nYaF5WF

**Comment by BenCodez** [comment]
You never edited the shop item....

**Comment by nilsrob1** [comment]
I did add the tripwire thingy the one I need im pretty sure

**Comment by nilsrob1** [comment]
Or you can actually just remove the diamonds from the shop, only have the crate key

**Comment by BenCodez** [comment]
Shop:
      # Identifier
      # Used in placeholders for formats
      Diamond:
        # Item
        Material: 'DIAMOND'
        Data: 0
        Amount: 1
        Name: '&4Buy A Diamond'
        # You can set skulls of the player using the following
        # Remove the # to enable
        #Skull: '%Player%'
        Lore:
        - '&c&lCost: &c3 Voting Points'
        # Number of voting points this cost
        Cost: 3
        # Permission required, leave blank for no permission
        Permission: ''
        # Limit how many times you can buy this
            #Limit: 3
        # Rewards to run if player buys succesfully
        Rewards:
          Items:
            Diamond:
              Material: 'DIAMOND'
              Amount: 1    
     

Don't think that is a tripwire.

**Comment by nilsrob1** [comment]
Okay I added it at the wrong place lol, wil try again!

**Comment by nilsrob1** [comment]
Is this better?
https://pastebin.com/9wia7DC7

**Comment by BenCodez** [comment]
No. Follow the shop format.

**Comment by nilsrob1** [comment]
Items:
        Tripwire Hook:
          Material: 'TRIPWIRE HOOK'
          Amount: 1
          Name: 'Chest Crate Key'  
          Enchants: unbreaking 1
          Lore: 'Right-click on a "Chest" crate to win an item!'

**Comment by BenCodez** [comment]
Shop:
      Tripwire:
        Material: 'TRIPWIRE_HOOK'
        Amount: 1
        # other item info
        Rewards:
          Commands:
          - give crate key command # in order for it to work

**Comment by nilsrob1** [comment]
How do I type it in the command format for it to work?

**Comment by nilsrob1** [comment]
Can you please just do it for me make it simple

**Comment by BenCodez** [comment]
whatever the command is with %player%
I already did everything I needed todo. I can't configure the plugin for you.

**Comment by nilsrob1** [comment]
Well that makes no sense to me, Im not a coder like you, you can easily do it for me you know what item im trying to get and you know your own plugin really well

**Comment by nilsrob1** [comment]
Like I got no idea how to add enchants and lore in a command

**Comment by BenCodez** [comment]
If I did that for everyone I never would have a chance to code. Most plugin devs do as much as me when it comes helping people using their plugins. I also have like no time.

On a side note you really should understand basic yml if you have a server. 

You also had the item formatting correct before, just in the wrong place.

**Comment by nilsrob1** [comment]
I run a pretty good server, but this is really hard for me to setup for some reason, its the only thing missing, 
and if you just did it from the beginning it would have been done for minutes ago, me not understanding is taking much longer, can you do it or do you want me to do it?

**Comment by BenCodez** [comment]
I'm just extra tired this week, else I probably would've done it.

Try it, send the config if it doesn't work and I'll fix it. It's easier to fix it then for me to start one.

**Comment by nilsrob1** [comment]
https://pastebin.com/pfhcMecs

**Comment by BenCodez** [comment]
Shop:
      Tripwire:
        Material: 'TRIPWIRE_HOOK'
        Amount: 1
        # other item info
        # Number of voting points this cost
        Cost: 5
        Name: 'Chest Crate Key'  
        Enchants: 
          unbreaking 1
        Lore: 
        - 'Right-click on a "Chest" crate to win an item!'
        Rewards:
          Commands:
          - give crate key command # in order for it to work

Get the right command and that should work.

**Comment by nilsrob1** [comment]
How do I know the command?

**Comment by BenCodez** [comment]
Find it from the plugn your using for keys.

**Comment by nilsrob1** [comment]
It doesnt say?

**Comment by nilsrob1** [comment]
Oh nvm you mean the command i get it

**Comment by nilsrob1** [comment]
Would it be like this /crate key %player% chest 1

**Comment by BenCodez** [comment]
no /

**Comment by nilsrob1** [comment]
yeah i forgot my bad

**Comment by nilsrob1** [comment]
Do i need the 'crate key %player% chest 1 ' the dots '''

**Comment by BenCodez** [comment]
it doesn't hurt.

**Comment by nilsrob1** [comment]
Thanks, it works you're a god!
