### ISSUE TITLE
[Bug] VoteParties Only Giving Rewards The First Time in 1 Day

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [BenCodez/VotingPlugin#497]
Vote parties will only reward players the first time in 1 day. If a second voting party happens in the same day then it will not announce a new vote party has happened, nor will it give rewards for it. However, it will reset the vote party counter (/voteparty). This can be easily tested by changing the required votes for a vote party to 1-2 (I did 2) and voted 4 times. It announced the first vote party but not the second.

Config.yml: https://pastebin.com/eykqYXfq
/version: "You are running the latest version" (Spigot 1.13.2)

**Comment by BenCodez** [comment]
Works fine for me. I got no idea. Turn debug on and send the log when this happens.

**Comment by PiggiesGoSqueal** [comment]
Just tested it with the latest version (from another issue you fixed). It's fixed. Thanks (for whatever you did in the past that fixed it)! :P

**Comment by BenCodez** [comment]
Hmm. Were you using an older build then?

**Comment by PiggiesGoSqueal** [comment]
I guess so. But when I updated to the build link you provided here: https://github.com/Ben12345rocks/VotingPlugin/issues/498 it worked.
