### ISSUE TITLE
[Bug] Top Voter Monthly Rewards Don't Work

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [BenCodez/VotingPlugin#498]
2019_JANUARY.yml:
Monthly:
- '1: Zaparaa: 121'
- '2: Zapara: 114'
- '3: legolace999: 112'

Zaparaa and Zapara (same person, different accounts) reported there was no reward message and he was not given the rewards for being top monthly voter on either of his accounts.

Config.yml: https://pastebin.com/eykqYXfq
/version: "You are running the latest version" (Spigot 1.13.2)
Top Voter Reward Files: https://gyazo.com/0a05e18af3eb20b1ac55cae8054ef92c

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This has been fixed already.

**Comment by PiggiesGoSqueal** [comment]
Okay thanks!
