### ISSUE TITLE
Back button on main GUI page

### ISSUE THREAD

**Issue by smellyonionman** [BenCodez/VotingPlugin#502]
I like to put every single command my users can run into my own GUI, but in cases like yours being so complete and customisable, I just open /vgui with a button on my own menus.

Can you offer us an option for an optional and customisable back button on the **main** GUI screen?  Hopefully we can supply a slot number, material, name, lore, and a command to issue when pressed.  I'd really appreciate the extra effort for that last bit of polish.

**Comment by BenCodez** [comment]
You can add custom buttons to the main gui, if that's the one your
referring to.
