### ISSUE TITLE
Broadcast Issue

### ISSUE THREAD

**Issue by sccooottttie** [BenCodez/VotingPlugin#507]
There's something wrong with my vote broadcasting.
It doesn't broadcast the vote to everyone.

 ```
  # Broadcast vote message
  # Set to an empty message to disable
  BroadcastMsg: '&aThank you &6%player% &afor voting the server! Vote now for rewards! &9/vote&a.'
  
  # Broadcast only when player is online
  BroadcastWhenOnline: false
```

I need help with my issue. Thanks.

**Comment by BenCodez** [comment]
Is the server getting the vote?

**Comment by sccooottttie** [comment]
Yep.

**Comment by BenCodez** [comment]
Startup log?

**Comment by sccooottttie** [comment]
```[05:07:19 INFO]: [VotingPlugin] Enabling VotingPlugin v5.17.5
> [05:07:20 ERROR]: [VotingPlugin] Plugin VotingPlugin v5.17.5 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.PlayerCommandSendListener because org/bukkit/event/player/PlayerCommandSendEvent does not exist.
> [05:07:25 WARN]: [VotingPlugin] Plugin VotingPlugin v5.17.5 generated an exception while executing task 27
java.lang.NoSuchFieldError: PLAYER_HEAD
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.loadPlayerSkull(PlayerUtils.java:356) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils$1.run(PlayerUtils.java:367) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]```

**Comment by BenCodez** [comment]
Later versions don't support 1.12, look on the plugin page for the version
to use

**Comment by sccooottttie** [comment]
It did broadcast last time after I installed the plugin for the first time.
Now it didn't work after I modified it.

**Comment by BenCodez** [comment]
You probably have a yml error in the config or something.

**Comment by sccooottttie** [comment]
If the yml has errors, then the plugin itself won't work... I think?

**Comment by BenCodez** [comment]
No it would still work. The plugin would read default values, so it would still work just with the wrong message. Is the server actually getting the vote (do you see it in console?) Does /av vote work?

**Comment by sccooottttie** [comment]
/av vote is working, and the server can receive votes.

**Comment by BenCodez** [comment]
Does the server receive the vote actually? (Read console for this) If you get nothing then that's your issue.

**Comment by sccooottttie** [comment]
Yep. I see it from the console.
"Received a vote from 'CHMC' on PlanetMinecraft!"

**Comment by BenCodez** [comment]
Wanna send me what it says?

**Comment by sccooottttie** [comment]
Okiee

**Comment by sccooottttie** [comment]
`> [19:10:11 INFO]: [VotingPlugin] Recieved a vote from 'MinecraftServers.org' by player 'CHMC'!`

**Comment by BenCodez** [comment]
Then it should work the same as you do with /av vote (player) MinecraftServers.org

**Comment by sccooottttie** [comment]
But the broadcast doesn't work. :<

**Comment by BenCodez** [comment]
Pastebin your Config.yml and VoteSites.yml

**Comment by CHMC2017** [comment]
Okie.

**Comment by sccooottttie** [comment]
config.yml
> https://pastebin.com/vmSKTixA

votesites.yml
> https://pastebin.com/V3u6BSPJ

**Comment by BenCodez** [comment]
Do you have something blocking broadcasts? It should be working.

**Comment by BenCodez** [comment]
Are you vanished?

**Comment by sccooottttie** [comment]
I don't have a broadcast blocker. But indeed, I'm vanished.

**Comment by sccooottttie** [comment]
Oh. It works now when I'm not in vanish mode. Thanks for helping me. :>
