### ISSUE TITLE
[Suggestion] Independent Debug to file

### ISSUE THREAD

**Issue by Segysmundo** [BenCodez/VotingPlugin#508]
Could you to make `LogDebugToFile` work even when normal debug is off? Or add an option like `DebugInConsole: true / false` so we can still have debug active and logging it to a file but it's not showing on the console.

We prefer checking the VotingPlugin log files to view any problems with player votes as it is way easier to find but on the other hand when viewing the console there is too many debug messages coming from VotingPlugin, but we can't log to file without having debug in console, so that's the reason for this susggestion.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should just be able to set logdebugtofile and it should work. Untested.

**Comment by Segysmundo** [comment]
Plugin doesn't seem to load. [Pastebin](https://pastebin.com/wfBDGE8q)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

How about now?

**Comment by Segysmundo** [comment]
Yep, that one seems to be working.

Thnx for the quick addition.
