### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by Biscuitius** [BenCodez/VotingPlugin#510]
Hey, sorry to be a pain here but I'm having difficulty with the VoteSites.yml

I've looked over this config a hundred times and I can't seem to figure out what I'm doing wrong that's prevening the sites from appearing in-game. Any help would be appreciated!

https://pastebin.com/TGyBx7K8

**Comment by BenCodez** [comment]
https://pastebin.com/cPP8aXRE

Try that.

**Comment by Biscuitius** [comment]
Perfect, thank you!
