### ISSUE TITLE
Force url for vote sites

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#514]

**Comment by dryter97** [comment]
i got an exemple for minecraftlist.online seem to be working whit an /tellraw with a json format. obiviously not working from your votingplugin

**Comment by BenCodez** [comment]
Not much I can do right now, I'll see.

**Comment by BenCodez** [comment]
Turns out this is already possible with json message in the plugin:
https://github.com/Ben12345rocks/AdvancedCore/wiki/Json-Messaging
