### ISSUE TITLE
Incompatible with EssentialsX.

### ISSUE THREAD

**Issue by MartynBlackburn** [BenCodez/VotingPlugin#518]
I am unable to use /vote command with your plugin whilst using EssentialsX. Removing EssentialsX makes the plugin work, so clear incompatibility issue.

**Comment by BenCodez** [comment]
Set an alias to override.

**Comment by MartynBlackburn** [comment]
Is the plugin not configured to work with EssentialsX? It's an essential plugin. Also: how do I create an alias? Thanks.

**Comment by BenCodez** [comment]
This is the first time I heard of such an issue, so I got no idea. Might be something you configured?

Use the spigot command aliases. Google it.

**Comment by MartynBlackburn** [comment]
I've had people check my config and there's no errors. No-one knows why I am having this issue with your plugin, and EssentialsX discord team have no idea either. I will google the alias commands thanks.

**Comment by BenCodez** [comment]
Does it work with /votingplugin:vote?

**Comment by MartynBlackburn** [comment]
That command is not recognised.

**Comment by BenCodez** [comment]
Then the plugin isn't loaded.

**Comment by MartynBlackburn** [comment]
Oh hang on I had someone get me to try that without the ?  But yes /votingplugin:vote? does work, but not /vote

**Comment by BenCodez** [comment]
Then using an alias will work.

**Comment by MartynBlackburn** [comment]
Okay I will use an alias and see how it goes. Thanks very much.

**Comment by MartynBlackburn** [comment]
Hi Ben I managed to resolve it without using an alias. Turns out the command file in EssentialsX was being used by the plugin or something along those lines...so I just deleted the content of the command file and it was resolved, but I have a new problem, namely that I am not able to get the plugin (VoteSites.yml) to record the mc listing sites that I visit and vote on. I've voted on three sites and none of them were recorded in the file. I got no response in-game either.

**Comment by BenCodez** [comment]
Anything in console when you vote? If not votifier isn't receiving the vote.

**Comment by MartynBlackburn** [comment]
Well I voted using two tester sites and they both recorded in the file. But any of the genuine list sites I visited to vote on successfully are never recorded in the file. The tests record in console, but that's all.

**Comment by BenCodez** [comment]
Then votifier isn't correctly setup.

**Comment by MartynBlackburn** [comment]
I'm getting help that with atm from their discord but I'm running out of options. I've already redownloaded the Nuvotifier files twice to make sure.

**Comment by MartynBlackburn** [comment]
I think I have an idea. Something I missed out. The tests work okay, but none of the genuine sites...probably because I haven't configured them on their end. On pmc I did not set votifer up and that's probably why.

**Comment by MartynBlackburn** [comment]
If I have any further problems (as I cannot do much since my host provider is doing maintenance) I will let you know, if that's okay? Thanks for the speedy reponse!

**Comment by BenCodez** [comment]
Alright.
