### ISSUE TITLE
Not running command

### ISSUE THREAD

**Issue by blankverse14** [BenCodez/VotingPlugin#522]
AllSites: 
  Messages:
    Player: '&aYou voted on all sites in 1 day! You have been awarded a &lVoter Key!'
  Command: 'crate key %player% voter 1'

Hi,
Can you help me fix this? I'm trying to give the player a Voter key after voting on all the sites. However, the command does not run. Does the plugin not support this?

**Comment by BenCodez** [comment]
It's like so:

    Commands:
    - 'command'
