### ISSUE TITLE
Allow items in the VoteShop

### ISSUE THREAD

**Issue by ontvlambaargames** [BenCodez/VotingPlugin#524]
So I'm giving out renamed diamonds with a lore for voting. We currently have special stuff people can buy from a shopkeeper using those diamonds. 
I'd like the VoteShop to accept items as payment method, while preferably checking for names and lores of those items. 

I hope this is not too much to ask, but makes for even greater customization!

**Comment by BenCodez** [comment]
Would recommend using bossshop for stuff like that. The vote stop revolves around points.

**Comment by ontvlambaargames** [comment]
Gotcha, I will definitely try this. Can I add voting links from VotingPlugin to a custom GUI too?

**Comment by BenCodez** [comment]
You can make one.
