### ISSUE TITLE
Reward not working

### ISSUE THREAD

**Issue by SliderKP** [BenCodez/VotingPlugin#525]
AllSites: 
  Messages:
    Player: '&aVotaste en todos los sitios, muy bien!! Mensaje 1 (Dile a SliderKP por discord)'
    Commands:
    - 'eco give %player% 250'
    - 'cr give %player% pandora 10'
    - 'points give %player% 3'
    - 'mail send %player% Votaste en 4 sitios, por lo tanto te llevas un premio extra,  tambien puedes votar en /vote40 - AVISALE A SLIDERKP SI RECIBES ESTE MENSAJE Y DILE MENSAJE 3 - 1'

Not working for me (1.12 version, is not the latest dev, but im running spigot 1.12)
problem like this https://github.com/Ben12345rocks/VotingPlugin/issues/522

**Comment by BenCodez** [comment]
What's not working? The points command is wrong and pastebin the Config.yml

**Comment by SliderKP** [comment]
If a user vote in all Sites not giving the rewards, only receive the message:
Player: '&aVotaste en todos los sitios, muy bien!! Mensaje 1 (Dile a SliderKP por discord)'

Pastebin: 
https://pastebin.com/mu1CLCsc

**Comment by BenCodez** [comment]
AllSites:
      Messages:
       Player: '&aVotaste en todos los sitios, muy bien!! Mensaje 1 (Dile a SliderKP por discord)'
      Commands:
      - 'eco give %player% 250'
      - 'cr give %player% pandora 10'
      - 'points give %player% 3'
      - 'mail send %player% Votaste en 4 sitios, por lo tanto te llevas un premio extra,  tambien puedes votar en /vote40 - AVISALE A SLIDERKP SI RECIBES ESTE MENSAJE Y DILE MENSAJE 3 - 1'

Try that.

**Comment by SliderKP** [comment]
Nice, thanks for your help, please do not close the issue, maybe i need to make another question, wait some days to close.

**Comment by BenCodez** [comment]
Closing for now, reopen if needed.
