### ISSUE TITLE
BossShop integration / Voteshop confirmation

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#526]
I'm making my own voteshop in BossShop pro. I need a shop with confirmation before buying happens, which VotingPlugin can't (yet).

So, I need to reroute the `/voteshop` command if I disable the inbuild voteshop of VotingPlugin. Now 2 plugins listen to the `/voteshop` command, but VotingPlugin still gives the `Vote shop disabled` message.

So my request would be if the `/voteshop` command can be disabled as a command if the internal voteshop is disabled so other plugins get a chance to handle this command.

Could the internal voteshop button in the main menu be linked to the bossshop `/shop`

**Comment by BenCodez** [comment]
you can disable the aliases in the config.

But this should disable the command:
http://ben12345rocks.com/job/VotingPlugin/

Unsure what you mean by internal button, that isn't really possible.

**Comment by x1p** [comment]
I meant the diamond button in the vote gui menu to open the vote shop

**Comment by x1p** [comment]
Works
