### ISSUE TITLE
Manually adding/setting points

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#527]
I used to have the ability to manipulate points by executing:
`av AddPoints (player) (number)` or `av SetPoints (player) (number)`
Worked in 5.16.x. But it doesn't seem to work anymore. Am I missing something?
I used it rarely, but it was nice to have the ability without diving into the database.

**Comment by BenCodez** [comment]
Commands changed:
https://github.com/Ben12345rocks/VotingPlugin/wiki/Commands-&-Permissions
