### ISSUE TITLE
(Suggestion)

### ISSUE THREAD

**Issue by johnsoncui02** [BenCodez/VotingPlugin#528]
add a placeholder for the Item reward that would display the item custom name and lore, along with enchantments if it's a equipment or tool.

**Comment by BenCodez** [comment]
Not exactly sure what you mean.

**Comment by johnsoncui02** [comment]
pretend we broadcast a person with a reward with the command to showcase the tool information. Although I do see it might be difficult for you to implement that sorts of things as it might change the whole dynamic of the plugin. But I'd just thought since this plugin is so configurable already I might as well at every last possibility i can think of that would help the features out.

Commands:
 Console:
- 'broadcast %player% %diamondSwordWithEnchantments%'

**Comment by BenCodez** [comment]
I'm still unsure, you can just manually set a message.

**Comment by johnsoncui02** [comment]
![image](https://user-images.githubusercontent.com/23487437/56176397-c628f800-5faf-11e9-885b-add1eae9f50e.png)
a message like that, not sure if it's possible. players hover over the item and it displays the enchantments and name with lores of the item.

**Comment by BenCodez** [comment]
You could probably use a command, but I'll see what I can do

**Comment by BenCodez** [comment]
This doesn't seem possible without nms, and I'm trying to avoid using nms unless I have to. Maybe in future.
