### ISSUE TITLE
(Problem) Lucky/Chances

### ISSUE THREAD

**Issue by johnsoncui02** [BenCodez/VotingPlugin#529]
I'm probably not understanding "Lucky" correctly, but what I did was basically gave the same equal amount of chances for list of items to be rewarded. All items are 1/3 but it's always the very bottom item gets chosen if not it's the item with the lowest integer gets selected. Can you help me out here?

[donator1.txt](https://github.com/Ben12345rocks/VotingPlugin/files/3078899/donator1.txt)

**Comment by BenCodez** [comment]
You can't have them be all the same chance.

**Comment by johnsoncui02** [comment]
so what do you suggest i can do so i can accomplish the same goal that I wanted to be able to do?

**Comment by BenCodez** [comment]
Have one lucky reward with a random reward so it gives a random reward from a list.

**Comment by johnsoncui02** [comment]
can I do that with multiple items with that in the same rewards > .yml file?

**Comment by BenCodez** [comment]
You can have chances per item, if that works.

**Comment by johnsoncui02** [comment]
can you give an example or if there is a example, can you show us how to create random rewards with the Rewards having more than 1 item in it with the following example?

Random:
  Chance: 50
  PickRandom: True
  Rewards: [how do I display rewards here, can it be multiple items instead of multiple file rewards]
  Fallback: [do I need this if I don't want a fallback and just give nothing]

Or maybe you have a discord with a community that could possibly help each other out? I'm trying to understand this plugin as best as I can and the instructions are clear, but as far as advanced rewards go it's just not as clear. 

I assumed you didn't create this Random and Chance reward to assume players going to make multiple files for each and every single item if we only want the players to obtain one item. (while there's a chance they don't get anything in the bundle at all)

Overall, great plugin. I love it so much. But i'm sure there's more I'm not understanding, and I am trying to reach out to you.

**Comment by johnsoncui02** [comment]
Currently stuck on here
[test.txt](https://github.com/Ben12345rocks/VotingPlugin/files/3082836/test.txt)

Pastebin: https://pastebin.com/g7JSPR7G

**Comment by BenCodez** [comment]
It's a list of reward files

**Comment by johnsoncui02** [comment]
oh i see, so the only way is to create multiple files of single item rewards. yikes. thanks!
