### ISSUE TITLE
(Issue) Chance not working correctly

### ISSUE THREAD

**Issue by johnsoncui02** [BenCodez/VotingPlugin#530]
Not sure what I did wrong here, 
I used chanceDonator1.yml
as the chance giver to the rest of the reward files
but it's only giving diamondSword1.yml and giving diamondPickaxe1.yml
and these are not 100% chance even when i set them to, it's more like 30% chance.

edit: perhaps there's already another chance going on? since i set 2 rewards as the given from the voteSites.yml where it gives 2 of the following
defaultReward.yml (gives lucky out of 3 commands)
donatorReward1.yml (gives chance of the rest of the reward files)

[voteplugin.zip](https://github.com/Ben12345rocks/VotingPlugin/files/3086135/voteplugin.zip)

**Comment by BenCodez** [comment]
All good?
