### ISSUE TITLE
Voting Reward

### ISSUE THREAD

**Issue by qvisten1** [BenCodez/VotingPlugin#531]
Not every voting sites give the players their rewards

**Comment by BenCodez** [comment]
And? Is the server getting the vote? What does it say in console?

**Comment by qvisten1** [comment]
It  is  getting the  vote, I can tell  from ingame . Add my discord and i could show you KPVP#5046

**Comment by BenCodez** [comment]
Just put it here. And your VoteSites.yml

**Comment by qvisten1** [comment]
You should get 25 oliver per vote 
Oliver = Our currency 
https://gyazo.com/62065512239a6421faa4371e277b4060

**Comment by BenCodez** [comment]
VoteSites.yml?

**Comment by qvisten1** [comment]
Couldn't send the file
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  ExampleVoteSite:
    Enabled: false
    Name: ExampleVoteSite
    Priority: 5
    ServiceSite: PlanetMinecraft.com
    VoteURL: link to vote URL here, used in /vote
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - say hello
      Messages:
        Player: You voted
  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Minecraft-MP_com:
    Enabled: true
    ServiceSite: Minecraft-MP.com
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  TopG_org:
    Enabled: true
    ServiceSite: TopG.org
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MinecraftServers_biz:
    Enabled: true
    ServiceSite: MinecraftServers.biz
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MCSL:
    Enabled: true
    ServiceSite: MCSL
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward: []

**Comment by qvisten1** [comment]
Should i type Rewards: 25?

**Comment by BenCodez** [comment]
Add a command to the rewards and you could pastebin it.

https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

**Comment by qvisten1** [comment]
So like this?

https://gyazo.com/4d26e740020150d76a5e6f9187008e86

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - 'command'

Like that.

**Comment by qvisten1** [comment]
https://gyazo.com/d65508117dd2602b817b452d215753bf

**Comment by BenCodez** [comment]
You have to match the spacing (2 spaces indented after Rewards:)

**Comment by qvisten1** [comment]
Should i remove the ' '?

**Comment by BenCodez** [comment]
No, that's fine.
