### ISSUE TITLE
Distinguish voting sites by server IP and call sign

### ISSUE THREAD

**Issue by lifehome** [BenCodez/VotingPlugin#533]
Due to the fact that some lame voting script shares the same voting call sign(the `ServiceSite` option in config), I suggest distinguish voting sites by both server IP, where is the IP of which vote came from, and the call sign.

Currently the `MinecraftServersList` dominates the majority of lame script market, where people just host the script and change nothing other than styles and css. Hoping that this feature would enhance the recognition on the source of votes.

**Comment by BenCodez** [comment]
I don't really see a need for it, but I'll probably add it. Considering
most people can't figure out a ServiceSite, only a few people would use
this.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Build here should have it, just have the ip under service site.
