### ISSUE TITLE
per world rewards how?

### ISSUE THREAD

**Issue by Xandervyvey** [BenCodez/VotingPlugin#535]
hey, can you help me with per world rewards 
i dont know how i can do that?
pls help as quik as possible

**Comment by BenCodez** [comment]
Just add a list of worlds under Worlds: in the reward.

**Comment by Xandervyvey** [comment]
> Just add a list of worlds under Worlds: in the reward.

wym i dont find a line with worlds and i maked one myself but it didnt work
can you like show me an example?

**Comment by Xandervyvey** [comment]
or can i like make that they only can do /vote in one world?

**Comment by Xandervyvey** [comment]
btw i have the rewards that need to be given in folder Votesites
https://pastebin.com/w9H7xQ7S

**Comment by BenCodez** [comment]
Rewards:
      Worlds:
      - world
      Commands:
      - crate key %player% vote 1
      - eco give %player% 5000
      - token add %player% 10
      Messages:
        Player: You voted
