### ISSUE TITLE
User SetVoteStreak

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#536]
Votestreak is really confusing to set and people keep losing it. Could you add a simple way of doing it through `/av user {username} SetVoteStreak (Daily/Week/Month) (amount)` this would make it alot easier for me to correct the votestreak issues and make it overall easier.

**Comment by BenCodez** [comment]
I think that is possible already.

**Comment by LogGits** [comment]
How? There is a way using that gui but it takes too many steps that makes it more difficult expecially with offline players

**Comment by BenCodez** [comment]
/av User (player) SetData (DataKeys) (text) : VotingPlugin.Commands.AdminVote.SetData|VotingPlugin.Admin

**Comment by LogGits** [comment]
how do i find out the `(dataKeys)` it doesnt tabcomplete them

**Comment by BenCodez** [comment]
You can find out by source code or from data storage.

https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/Objects/User.java#L846

WeekVoteStreak

**Comment by BenCodez** [comment]
You can also use /av user (player) ViewData to get the keys.
