### ISSUE TITLE
Duplicated rewards

### ISSUE THREAD

**Issue by MithrandirCraft** [BenCodez/VotingPlugin#537]
Hey. Using VotingPlugin 5.18.2 (Haven't updated the server to 1.14, but would the latest build work still on 1.13?).

Apparently you can duplicate rewards by voting right before a server restart.
I haven't experienced it myself but I've been told that you can reproduce this by voting on all sites right before a restart (I'm guessing a few minutes before works since it takes a while to vote), getting the rewards (which on my server are crate keys), and then once the server has restarted, you apparently get the keys again without doing anything. You just receive them.

If you need any more details or I find out anything more I'll let you know.

**Comment by BenCodez** [comment]
Latest version works on 1.13.

Storage option? Console logs with debug enabled and copy of user data before restart and after will help a lot (use /av user (player) viewdata)

**Comment by MithrandirCraft** [comment]
Update: Apparently it's worse, you can reproduce this with the same steps, just log out and log back in again without waiting for a restart and you get the duplicated rewards.

Will test with this procedure.

**Comment by BenCodez** [comment]
Try it with the latest version.

**Comment by MithrandirCraft** [comment]
Storage is mySQL.
Not being able to reload VotePlugin kinda makes it harder to activate debug.

**Comment by BenCodez** [comment]
Use the latest version, it probably fixes the issue. I'm guessing you have an error that a few others had.
What you mean not able to reload? /av reload?

**Comment by MithrandirCraft** [comment]
latest version fixes it.

**Comment by MithrandirCraft** [comment]
Hey, just wanted to warn about the fact that this issue is probably still present in one of it's two reproductable shapes: logging out on reward receivent and receiving reward and later waiting for an inmediate server restart.
Allthough no one is abusing it currently on my server that I know of... We'll try to reproduce it again since last thing said about it was that it was still there.

**Comment by BenCodez** [comment]
You'll need to give more details if that is the case. Like setup, etc. The plugin saves mysql data within a few seconds of data but caches it locally.

**Comment by MithrandirCraft** [comment]
For now I have this information:
The issue occurs during restarts. The way you reproduce it is the following:
1. Vote and get all possible keys from voting, close to a server restart.
2. Wait for the restart. You get kicked from the server, once you log back in, you get all the keys you already received again. Thus duplicating them.

**Comment by BenCodez** [comment]
This help?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by MithrandirCraft** [comment]
I'll let you know.

**Comment by BenCodez** [comment]
Made some more improvements, let me know how that goes.
http://ben12345rocks.com/job/VotingPlugin/

**Comment by MithrandirCraft** [comment]
It still happens, even with your last build. With the mentioned method.

**Comment by BenCodez** [comment]
Console logs? Shutdown and startup?

**Comment by MithrandirCraft** [comment]
https://gist.github.com/MithrandirCraft/60e2b32e5ae07059647c7df9f8ba9751

This is all I gathered from startup with VotingPlugin...
That last error has been there for ages, I should check it out some time. Not sure what it could refer to though.

Is this enough? Can't see any errors close to voteplugin loading.

**Comment by BenCodez** [comment]
How do you shutdown? Does the plugin properly shutdown?

**Comment by BenCodez** [comment]
Try it with the latest spigot build

**Comment by MithrandirCraft** [comment]
It's a scripted /stop
The plugin shuts down properly.
The spigot build is already the latest on 1.13.2
I can't update to 1.14 yet.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/

Tjos any better?

**Comment by MithrandirCraft** [comment]
Is this a new build? We'll test it out but it might take some time.
I'm pretty sure duplicating (or even triplicating) rewards with restarts is still possible though.

**Comment by BenCodez** [comment]
It should force the mysql database to finish all the queries

**Comment by BenCodez** [comment]
Any update on this?
