### ISSUE TITLE
(Question) voting message cannot be found

### ISSUE THREAD

**Issue by johnsoncui02** [BenCodez/VotingPlugin#538]
![image](https://user-images.githubusercontent.com/23487437/56877783-3cdce100-6a05-11e9-99ad-69e9fc15cf68.png)

I wanted to get rid of the first line of message, but I've been looking and couldn't find where the message is. Can you help me out?

**Comment by BenCodez** [comment]
Not from my plugin I'm guessing

**Comment by johnsoncui02** [comment]
If that's not it, then it's votifier? I don't recall votifier can do that.
![image](https://user-images.githubusercontent.com/23487437/56928389-7d7f3d80-6a8b-11e9-949a-e35e91bf85c3.png)

**Comment by BenCodez** [comment]
Check cmi

**Comment by johnsoncui02** [comment]
you are correct, thanks and sorry about that.
