### ISSUE TITLE
Detected an issue with voting sites

### ISSUE THREAD

**Issue by Mortderas** [BenCodez/VotingPlugin#539]
Greetings! I keep on encountering this error:
WARN [VotingPlugin] Detected an issue with voting sites, check the plugin startup log for more details
Someone told me it's from the Votifier, but when I run a test the outcome is positive.
Vote by Mortderas succesfully sent to mc.hidden-forest.com:8004
Tried so on more than one port

Also the message that tells if a player voted does not appear, neither the reward.

**Comment by BenCodez** [comment]
It means you have a votesite configured with a service site the server hasn't a recieved a vote from.

    check the plugin startup log for more details

^ Might help you :)

**Comment by Mortderas** [comment]
Thanks for replying, where can I find the startup log? I only see the logs and there's only 2 propositions repeating themselves..

**Comment by BenCodez** [comment]
It's the server log.
