### ISSUE TITLE
(Question) AllSites.yml

### ISSUE THREAD

**Issue by johnsoncui02** [BenCodez/VotingPlugin#540]
So if this is the message and I have 3 vote links, after player voting all 3 links it would execute this command? Not sure if i'm understanding this right.

`# Directly defined reward file. ANY EDITS HERE CAN GET OVERRIDDEN!
Messages:
  Player: '&7You voted on all sites today. You have received an item that allows you to fly for 30 mintues.'
DirectlyDefinedReward: true
Commands:
  Console:
      - 'broadcast &e%player% &7Voted on all sites in a day and earned 30 minutes /fly'
      - 'cmi kit fly%player%'`

**Comment by BenCodez** [comment]
You would need to set that in Config.yml, but it would execute after all voting sites are voted on.
