### ISSUE TITLE
[Question] Execute command on first vote today.

### ISSUE THREAD

**Issue by BaxAndrei-SEC-ACC** [BenCodez/VotingPlugin#541]
How I can execute an command here https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L597 when player vote first time today? I want to give him an crate key but only for first vote per day.

Thanx!

**Comment by BenCodez** [comment]
FirstVote:
      Commands:
      - command %player%

**Comment by BaxAndrei** [comment]
Thanx!
