### ISSUE TITLE
Cannot Force Rewards for offline player

### ISSUE THREAD

**Issue by A1Gaming** [BenCodez/VotingPlugin#542]
Hi Ben,
I use the current version of your plugin, 5.18.3 on a 1.13.2 server with the current version of NuVotifier. 

I use player points system that is integrated into your plugin.

My Network looks like this: 1. BungeeCord Proxy (with Nuvotifier forwarding votes) directed to a Hub server. Also connected to the proxy are 4 gaming servers, and a server called "utility".

The Utility server is a light Spigot server that I want to handle the issuing of points to players. This server is Whitelisted and no players will be able to join it (it's sole purpose is to receive votes, and give points). 

For various voting actions, I want to give players points for. By default, every player gets 5 points per vote per service site. I want to give players additional 100 points per first vote, 60 points additional for voting on all sites, extra points for Voting party, and weekly/monthly point bonuses.

HERE IS MY PROBLEM: When a vote comes into Bungee and forwarded to Utility server, the voter DOES get their 5 points (points given per vote per service site) just fine. BUT they DO NOT get REWARDED for anything else (first vote, all sites in one day, etc) because they are "offline". I TRIED to use the ForceOfflineRewards: TRUE in the rewards file I created, but it STILL does not work! Is my arrangement even possible, where a player can get points for voting offline? 

I appreciate your help Ben!

**Comment by BenCodez** [comment]
Add ForceOffline: true

**Comment by A1Gaming** [comment]
![120501](https://user-images.githubusercontent.com/36427041/57562580-0dfa2f80-7362-11e9-95b2-71c006aea143.JPG)

Hi Ben, this is the issue. I DID add this line in my rewards file.

**Comment by BenCodez** [comment]
Are you doing that for the vote site? You'll also need to add ForceOffline there.

**Comment by A1Gaming** [comment]
Thank you for the lightning quick response!
So, configure it like so?
![51251](https://user-images.githubusercontent.com/36427041/57562655-a09ace80-7362-11e9-87e8-b9aa0d615a98.JPG)

**Comment by BenCodez** [comment]
I mean this:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L43

Add it in the votesite itself.

**Comment by A1Gaming** [comment]
![5151](https://user-images.githubusercontent.com/36427041/57562770-c674a300-7363-11e9-8160-2e7eb58ee022.JPG)
I did this as instructed. I'm not sure why that option wasn't in there. However, I ran a vote, and it still is cached as offline reward. I only got 20 points total (5 votes per service site, 4 service sites total). It says AllSites%placeholder% in database for Offline Rewards. I have not logged into the server with my character yet.

**Comment by A1Gaming** [comment]
So in other words, I did not get rewarded for "all sites".

**Comment by BenCodez** [comment]
You don't have any reward listed?

**Comment by BenCodez** [comment]
Also pastebin next time, I can't read screenshots.

**Comment by A1Gaming** [comment]
https://pastebin.com/wQ6i5wLS

this is my config.yml AND rewards file for PointsAllSites.

**Comment by A1Gaming** [comment]
https://pastebin.com/qM2aaZtA

this is my entire VoteSites.yml file

**Comment by BenCodez** [comment]
AllSites:
    - rewardfile

**Comment by A1Gaming** [comment]
oh so eliminate the "Rewards:" on line 606?

**Comment by BenCodez** [comment]
Have it like I have it.

**Comment by A1Gaming** [comment]
AllSites: 
    - 'PointsAllSites'

I entered it like this, saved the yml, restarted the Utility server, and ran 4 votes through with another account. Success! 20 points were given (5 per vote site, which worked before) AND 60 bonus points were given! The reward file processed correctly! AND there are NO cached offline rewards! Thank you Ben! I'm sorry that I have to use up your time like this, but it helps greatly, especially when small mistakes are made. I also have 1 further question and some suggestions.

**Comment by BenCodez** [comment]
Go right ahead.

**Comment by A1Gaming** [comment]
This is for the vote party. As a reward, I would like to give out to all the players INVOLVED in the party that earned their reward 100 points. 

Here is the vote party section of the Config.yml
https://pastebin.com/MCm7NpcU

Will the command for the Reward work for ALL the players involved in the vote party?

**Comment by A1Gaming** [comment]
Rewards: 
    Commands:
    - adminvote user %player% addpoints 100

CORRECTION: I realized this is the new syntax for your updated plugin and UPDATED it

**Comment by BenCodez** [comment]
Are you asking for a requirement? By default it will only give rewards to those who voted in it.

**Comment by A1Gaming** [comment]
I am asking if this command "adminvote user %player% addpoints 100" will work for the Voting Party reward for all those involved in it. Since there could be 7-8 players who can be rewarded for their votes, will your plugin run this command for each UUID that is in the party?

**Comment by BenCodez** [comment]
Yep. It gives reward for each player.

**Comment by A1Gaming** [comment]
Sorry edited my comment.

**Comment by BenCodez** [comment]
Yes to that edit.

**Comment by A1Gaming** [comment]
Ok, thank you so much for taking 1 hour to help me out! As a Dev, I understand that you're busy.

Also, here are my suggestions:

1. Make a Bungeecord version of Voting Plugin: A great many Minecraft servers utilize a proxy system, and a VotingPlugin that operates in the proxy server would be extremely useful. This is why I created a "utility server" that no one can join, to basically operate your plugin for my Points System.

And I forgot my other suggestions. I can contact you if/when I remember them!

**Comment by BenCodez** [comment]
Thought about it, it's a lot of work though to make a bungeecoord version. It's on a list of things to tackle :)

**Comment by A1Gaming** [comment]
Also here is another suggestion I just thought of (not the previous ones I forgot, though).

Do you have a Discord server for your Plugin(s)? Since your plugin is very very essential to the Minecraft Community, I believe it would be useful (although more work) if you did have one.

**Comment by BenCodez** [comment]
I'm currently against discord, it's easier to use github and spigot for me.

**Comment by A1Gaming** [comment]
Ok, no problem. If I have any further issues, questions, concerns or comments, I will go ahead and contact you via Github! Thank you so much for your time and thank you for making an awesome plugin!
