### ISSUE TITLE
Specify hour at which VoteDelayDaily resets

### ISSUE THREAD

**Issue by Segysmundo** [BenCodez/VotingPlugin#543]
Most sites reset their vote delay every day so we must set this option to true in our **votesites.yml**:
![image](https://user-images.githubusercontent.com/19178945/57898814-da843d00-785a-11e9-9fa3-f2cc42ffcab1.png)

The thing is some sites don't have the same timezone as the server so the site resets at a certain hour while votingplugin resets the day at a different time.

If we could specify the hour of the day at which we want the vote delay to reset we could match it with the site so both reset at the same time.

This way we make sure there are no inconsistencies on vote totals every day/week/month.

Adding something like this would be nice:
![image](https://user-images.githubusercontent.com/19178945/57899645-208ed000-785e-11e9-9c12-5463a3846aa4.png)

Edit: Fail, forgot to set **WaitUntilVoteDelay** to **true**, for this example assume it's active.

**Comment by BenCodez** [comment]
You can offset the time it globally resets currently

**Comment by Segysmundo** [comment]
Ah since I didn't see the option in the config and didn't find anything about it in the wiki I thought you removed that option.

**Comment by BenCodez** [comment]
It still exists, just hidden

**Comment by Segysmundo** [comment]
@Ben12345rocks 

It's 23:00 local time and I have **TimeHourOffSet: -1**, I also have **VoteDelayDaily: true** but when I use **/vote next** it says I will be able to vote in 1 hour. Shouldn't it say in 2 hours, since I moved my hour offset 1 hour back?

I'm guessing the same happens with the placeholder **%VotingPlugin_CanVote_Votesite%**

**Comment by BenCodez** [comment]
It should say you can vote then, I'll look at it later

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

How's that?

**Comment by Segysmundo** [comment]
Yep now it shows properly in /vote next thnx.

Does it show the placeholderapi placeholder right too? I cant test that right now.

**Comment by BenCodez** [comment]
It should.

**Comment by Segysmundo** [comment]
At 00:00 /vote next showed up as this
![image](https://user-images.githubusercontent.com/19178945/58133724-da05f080-7c24-11e9-811d-9476a0497392.png)
And it let me vote.

It should have showed 1 hour remaining and not let me vote yet.

**Comment by Segysmundo** [comment]
At 23:00 it said there was 1 hour remaining.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Any better?

**Comment by Segysmundo** [comment]
If I set **VoteDelayDaily: true** it just says go vote but wont let me.

If I remove it and just let it as **VoteDelay: 24**, and set **TimeHourOffset: -1** in config.

Then this shows up
![image](https://user-images.githubusercontent.com/19178945/58134373-e5f2b200-7c26-11e9-8641-e348dbd9a060.png)

It says 24h 54min remaining instead of 23h 54min, I think the TimeHourOffset is working really weird.

**Comment by Segysmundo** [comment]
The same thing works the other way around, setting **TimeHourOffset: 1** shows this
![image](https://user-images.githubusercontent.com/19178945/58134464-336f1f00-7c27-11e9-8df4-527dbe8fddd1.png)

**Comment by BenCodez** [comment]
Now?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Segysmundo** [comment]
Still shows the same as above.

**Comment by BenCodez** [comment]
It worked for me. Redownload the latest?

**Comment by Segysmundo** [comment]
Now that it's 1:12 and I set **VoteDelayDaily: true** and **TimeHourOffset: -1** it shows this
![image](https://user-images.githubusercontent.com/19178945/58136561-cf505900-7c2e-11e9-8379-b925cf09e286.png)
But if you set **TimeHourOffset: -2** it shows this
![image](https://user-images.githubusercontent.com/19178945/58136600-ebec9100-7c2e-11e9-81be-753912fac1fd.png)

**Comment by Segysmundo** [comment]
I think it goes crazy if the offset switches days. If I have an offset but it's still the same day as if I didnt have offset it works ok.

For example above -1 would make it still be 00:15 which is 22/05/19 but offset -2 would make it 23:15 21/05/19.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That better?

**Comment by Segysmundo** [comment]
I think you fixed it.

Does VoteDelay ignore offsets now?

**Comment by Segysmundo** [comment]
![image](https://user-images.githubusercontent.com/19178945/58136914-302c6100-7c30-11e9-9c42-bd700de4704b.png)
___
![image](https://user-images.githubusercontent.com/19178945/58136919-34587e80-7c30-11e9-97ea-5c031681a861.png)
___
![image](https://user-images.githubusercontent.com/19178945/58136923-37536f00-7c30-11e9-95e4-4c019e580c45.png)

**Comment by Segysmundo** [comment]
Yep I think it's working now.

**Comment by BenCodez** [comment]
Good :)

**Comment by Segysmundo** [comment]
Thanks man that was some fast bug fixing haha.

**Comment by Segysmundo** [comment]
I think it's not entirely working. Once it reached **02:00** I used /vote next and **Go Vote** showed up correctly as it should:
![image](https://user-images.githubusercontent.com/19178945/58138340-f2323b80-7c35-11e9-88c3-3b889f61e1f8.png)
But when attempting to vote, console showed this and the vote didn't go through:
![image](https://user-images.githubusercontent.com/19178945/58138366-12fa9100-7c36-11e9-8e23-dc4d4ef7a51d.png)

Edit: Do I have to remove **VoteDelay: 24** line and only leave **WaitUntilVoteDelay: true** and **VoteDelayDaily: true** ?

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Try now.

**Comment by Segysmundo** [comment]
Mhmm now I can't test it out until its 3 am haha, let me see if I can change server time.

**Comment by Segysmundo** [comment]
Just tested it, seems to be working correctly, I was able to vote, wait until date change and vote again.

Since I'm using **VoteDelayDaily: true** should I remove **VoteDelay: 24** or leave it there?

**Comment by BenCodez** [comment]
Won't matter.

**Comment by Segysmundo** [comment]
Ah, thanks for fixing it and clarifying.

The plugin keeps getting better and better. :P
