### ISSUE TITLE
VotingPlugin Not Detecting Voting Sites

### ISSUE THREAD

**Issue by imskyyc** [BenCodez/VotingPlugin#545]
Console: 
[04:45:15 WARN]: [VotingPlugin] Detected no voting sites, this may mean something isn't properly setup
[04:45:15 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-2 - Starting...
[04:45:15 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-2 - Start completed.
[04:45:15 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Shutdown initiated...
[04:45:15 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Shutdown completed.
[04:45:15 INFO]: VotingPlugin v5.18.3 reloaded!

VotingSites.yml:
VoteSites:
  # VoteSite name
  minecraftservers.org:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'minecraftservers.org'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 1
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'minecraftsevers.org'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://minecraftservers.org/vote/546655'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Send player a message
      Messages:
        Player: '&6You voted at &aminecraftservers.org! &6Thanks for voting!'

  # VoteSite name
  minecraft-mp.com:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'https://minecraft-mp.com'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 2
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraft-mp.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://minecraft-mp.com/server/219535/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'GOLD_INGOT'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Send player a message
      Messages:
        Player: '&6You voted at &aminecraft-mp.com! &6Thanks for voting!'

  # VoteSite name
  minecraft-server-list.com:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'https://minecraft-server-list.com'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 3
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraft-server-list.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://minecraft-server-list.com/server/438552/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'IRON_INGOT'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Send player a message
      Messages:
        Player: '&6You voted at &ahttps://minecraft-server-list.com! &6Thanks for voting!'

  minecraft-server.net:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'https://minecraft-server.net'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 3
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraft-server.net'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://minecraft-server.net/vote/StarCraftMC/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'COAL'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Send player a message
      Messages:
        Player: '&6You voted at &ahttps://minecraft-server.net! &6Thanks for voting!'
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by BenCodez** [comment]
Pastebin it please.

**Comment by imskyyc** [comment]
https://pastebin.com/QZ4q7QhZ

**Comment by BenCodez** [comment]
No dots under votesites
