### ISSUE TITLE
Votes not going through to server

### ISSUE THREAD

**Issue by Segysmundo** [BenCodez/VotingPlugin#546]
Since I updated the plugin to the version you sent me here;

>_Originally posted by @Ben12345rocks in https://github.com/Ben12345rocks/VotingPlugin/issues/543#issuecomment-494604052_
> http://ben12345rocks.com/job/VotingPlugin/
> Try now.

I've been getting this error when players vote:
**[Error](https://pastebin.com/7Ghq7Fee)**

**Comment by BenCodez** [comment]
Redownload it?

**Comment by Segysmundo** [comment]
You mean download and use the same version that's causing the error?

**Comment by BenCodez** [comment]
See if that helps

**Comment by Segysmundo** [comment]
Did you change anything since yesterday?

**Comment by Segysmundo** [comment]
I'd have to restart the server and make 20 ppl disconnect just to try that out.

**Comment by Segysmundo** [comment]
Also getting this error whenever I do **/av reload**

[**Error**](https://pastebin.com/WwFXVX2C)

I'll redownload the jar and try it again when some users leave, see if that fixes it.

**Comment by Segysmundo** [comment]
Just tried reinstalling the plugin, same error shows up.

It has to do with MySQL setup I think.

**Edit:** Found a new error:

[**Error**](https://pastebin.com/gS0cUcu9)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This help?

**Comment by Segysmundo** [comment]
Still seems to be happening.

[**Error 1**](https://pastebin.com/n81heWzn)

[**Error 2**](https://pastebin.com/NQP00DM8)

**[Error 3](https://pastebin.com/5UysN7vD)**

**Comment by BenCodez** [comment]
Turn debug and extra debug on and send the full log when and before that error happens.

**Comment by Segysmundo** [comment]
That's with debug and extra debug on.

What do you mean with full log of before and after?
The only thing that happens before each error is a player votes or logs in.

Let me check if I can manage to replicate it without other stuff happening in between.

**Comment by BenCodez** [comment]
There should be some debug 30 seconds before that error.

**Comment by Segysmundo** [comment]
I just tried to vote, this is everything in the log.

[**Error**](https://pastebin.com/FMmDLjL0)

**Comment by BenCodez** [comment]
Try this:
http://ben12345rocks.com/job/VotingPlugin/

If that doesn't work set log debug to file and send that file (in votingplwith console log.

**Comment by Segysmundo** [comment]
I already had the debug to file activated, this is what was logged when I voted, no errors showed up.

[**Error**](https://pastebin.com/fp95Lwru)

**Comment by BenCodez** [comment]
So it works now?

**Comment by Segysmundo** [comment]
Wait forgot to say this, that was before trying that last file you just sent, I won't abe able to restart server and try that one until later or tomorrow.

Just wanted to show that no errors show up in the debug to file log, even before.

**Comment by BenCodez** [comment]
Let me know how it goes after you try it.

**Comment by Segysmundo** [comment]
Still having errors, debug to file doesn't show any error. They appear in the server console log.

Here's an example of the same error on 3 different players.

**[Player 1](https://pastebin.com/4vdPC0vY)**
**[Player 2](https://pastebin.com/RpEfgmhG)**
**[Player 3](https://pastebin.com/HAzM9kPS)**

They vote on the site, the server receives the vote from the votesite, and the errors occurs.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I'm hoping this works... 
If not I'll need the whole server log with the debug in order to track it down the issue.
The errors no longer spam console without debug on as well. It will also attempt to reconnect on the error as well.

**Comment by Segysmundo** [comment]
Sorry for the late response, have been pretty busy yesterday.

I tried out the last version you sent me and everyone seems to be receiving their rewards correctly.

But you can still see errors in console, I filtered everything related to votingplugin and advancedcore from the whole server startup log so you can check it out.

Log from startup until latest hour:
**[Console Log](https://pastebin.com/459McNCS)**

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I think this one will do it. I finally found the source of the problem.

**Comment by Segysmundo** [comment]
Since the last file you sent me, everyone receives their rewards ingame when they vote. But the votes aren't getting saved into the dabatase.

We are also getting some more errors in console.

**[Error 1](https://pastebin.com/SggW71F9)**
**[Error 2](https://pastebin.com/jKwByFYb)**
**[Error 3](https://pastebin.com/W1KZg2Kq)**

**Comment by BenCodez** [comment]
Let's try it now....
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Segysmundo** [comment]
They still don't get added into the database.

I had 20 votes and voted 1 more time, in the database my total votes were still at 20, but if I used the command **/vote total** ingame it said I had 21 so there it's showing them correctly.

Getting this error now and then:
**[Error](https://pastebin.com/nUcespJj)**

**Comment by BenCodez** [comment]
I actually think this one should do it:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Segysmundo** [comment]
It seems to all be working fine as of now, I'll check it again later when more players have tested it out.

**Edit:** Right after posting the message above, this popped up in console:

**[Error](https://pastebin.com/NXtZ2wT7)**

Aside from the error above, players are receiving their rewards and votes are getting added to the database properly as far as I've seen.

**Comment by BenCodez** [comment]
I'm pretty sure it should be good now

**Comment by Segysmundo** [comment]
> _Originally posted by @Segysmundo_
> Edit: Right after posting the message above, this popped up in console:
> **[Error](https://pastebin.com/NXtZ2wT7)**

Just checked console again after a couple hours, this error has been showing up for a bunch of players now.

**Comment by BenCodez** [comment]
This should solve that:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Segysmundo** [comment]
Been waiting until the month change just to make sure it was working properly.

Everything seems to be fixed, everything is saved and given out properly and top voter awards are given correctly on month change even with hour offsets.

Thanks for fixing the recurring bugs on this issue. It has really helped us with getting our voting system perfectly set!

**Comment by BenCodez** [comment]
No problem. This has been a bug I wanted to track down for awhile.

**Comment by BenCodez** [comment]
Going to be closing this since the issue is solved and it the issue was due to the dev build from before.
