### ISSUE TITLE
Server Crashes 

### ISSUE THREAD

**Issue by BboyZeroOne** [BenCodez/VotingPlugin#547]
Whenever a player clicks on the icon shown in the image below, the server crashes.
https://imgur.com/a/czMnsFo

I have also uploaded the crash logs.
[crash-2019-06-03_15.05.54-server.txt](https://github.com/Ben12345rocks/VotingPlugin/files/3248273/crash-2019-06-03_15.05.54-server.txt)

**Comment by BenCodez** [comment]
Are you using the latest version? Config?

**Comment by BboyZeroOne** [comment]
Yes, I am using the latest version.
 Config:
https://pastebin.com/T0b8VEhi

**Comment by BenCodez** [comment]
Does disabling preloadskulls fix it? Can you upload the whole crash log? (server log should do it)

**Comment by BboyZeroOne** [comment]
[2019-06-03-3.log.gz](https://github.com/Ben12345rocks/VotingPlugin/files/3249556/2019-06-03-3.log.gz)
[2019-06-03-2.log.gz](https://github.com/Ben12345rocks/VotingPlugin/files/3249557/2019-06-03-2.log.gz)
[2019-06-03-4.log.gz](https://github.com/Ben12345rocks/VotingPlugin/files/3249558/2019-06-03-4.log.gz)


I have not tested disabling it but here are my server logs, i have sent u the crash logs above too.

**Comment by BenCodez** [comment]
Found the problem, try this build:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by BboyZeroOne** [comment]
I've updated to the latest version. now the sign does not work. Is it intended?

**Comment by BboyZeroOne** [comment]
And do i need to re-enable preloadskulls?

**Comment by BenCodez** [comment]
Does it work with that enabled?

**Comment by BenCodez** [comment]
The GUI opens after a few seconds once the skulls get loaded. (Just the first time it's opened)
You can disable using skulls for instant loading.

**Comment by BenCodez** [comment]
Try this:
http://ben12345rocks.com/job/VotingPlugin/
