### ISSUE TITLE
Unsure of what my mistake was

### ISSUE THREAD

**Issue by ServerMom** [BenCodez/VotingPlugin#550]
Ive reviewed my work a few times and I can't find what I did wrong. None of the servers appear in the API or when clicking list all server.
https://pastebin.com/Si7ZFLSy

**Comment by BenCodez** [comment]
No periods under votesites, yml reads that differently than a normal
character

**Comment by ServerMom** [comment]
Thank you. what would I replace the periods with?

**Comment by BenCodez** [comment]
Anything, it doesn't matter.

**Comment by ServerMom** [comment]
So simply remove every period?

**Comment by BenCodez** [comment]
VoteSites:
      PlanetMinecraft.com: <--- only these ones

**Comment by ServerMom** [comment]
Thank you so much for the help!

**Comment by ServerMom** [comment]
I removed all periods in the Votesites: and I still cant get them to appear in the GUI

**Comment by BenCodez** [comment]
Player: "&BThank you for voting! Don't spend it all in one place~"

Change your messages to that.

**Comment by ServerMom** [comment]
It works! thank you!
