### ISSUE TITLE
Next Page Function in the Vote shop does not work

### ISSUE THREAD

**Issue by vkolasa** [BenCodez/VotingPlugin#551]
After reaching 56 items in the vote shop, it switched its formatting to the next page function, only problem is when you click the icon for the next page, it doesnt do anything. Help is appreciated! thanks.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That do anything?

If not, send your config.

**Comment by vkolasa** [comment]
Works perfectly, Thanks for the support :)
