### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by qvisten1** [BenCodez/VotingPlugin#552]
When ever someone votes, The plugin gives the players 2 votes
https://gyazo.com/6143a5f5c0794a86c0d40909d15772d6
( 2 rewards and everything )

**Comment by BenCodez** [comment]
Pastebin that.

**Comment by qvisten1** [comment]
https://pastebin.com/TgP8zC76

**Comment by BenCodez** [comment]
Votesites.yml?

**Comment by qvisten1** [comment]
https://pastebin.com/EK05TWDR

**Comment by BenCodez** [comment]
Are you using the latest version?

**Comment by qvisten1** [comment]
Yes I am

**Comment by BenCodez** [comment]
Turn debug on and send the log when someone gets a reward

**Comment by qvisten1** [comment]
How do i turn it on?

**Comment by BenCodez** [comment]
Option in the config

**Comment by qvisten1** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/20997276/59549803-2e219d80-8f63-11e9-9b4a-97f80ab4e816.png)

**Comment by BenCodez** [comment]
Are you getting double rewards or double messages? The first one doesn't appear to be from VotingPlugin

**Comment by rybuilder23** [comment]
hi i have the same  problem

https://pastebin.com/GVpzw8qg
https://pastebin.com/GXBpS7rq

screen
http://prnt.sc/o8bf8c

**Comment by BenCodez** [comment]
@rybuilder23 turn extra debug on and send the log.

**Comment by rybuilder23** [comment]
> @rybuilder23 turn extra debug on and send the log.

i logt in today and it works fine now ;p

**Comment by BenCodez** [comment]
Hmm, might of been the votesite sending the vote twice.
