### ISSUE TITLE
all vote messages

### ISSUE THREAD

**Issue by slvlr** [BenCodez/VotingPlugin#554]
https://gyazo.com/8c65419e1d96cd320907dff9a655b582

Is there a way to customise the all vote message?
I am trying to remove the red server names but I cannot figure out how to?

**Comment by BenCodez** [comment]
Check the Config.yml

**Comment by slvlr** [comment]
I don't see this, where can I remove the red messages?

https://pastebin.com/5pUpYLam

**Comment by BenCodez** [comment]
Commands:
      # Format for /vote
      # %num% = the number of the site, for a numbered list
      # %url% = site URL
      Vote:
        Text:
        - '&4&lVote for our server!'
       
        # If you want to want to use the feature below where the plugin will
        # automaticly list the sites then set the message in the text above
        AutoInputSites: true
        # For each VoteSite
        # make sure to set VoteURL in your VoteSites
        # Requires above to be true
        # Text will be sent before this
        Sites: '&4%num%: &c&l%SiteName% - &c%url%'

**Comment by slvlr** [comment]
Its not that simple, could you add me on Rangewonk / SlVlR#9222 discord to discuss please?

**Comment by BenCodez** [comment]
It is that simple, change the color code. I don't use discord.

**Comment by slvlr** [comment]
That is for singular links, it doesn't display the red name for singular links, but when I click the "all votes" button it says the name twice. Once in red and once in the color I chose. ??

**Comment by BenCodez** [comment]
That is the format for each link.... do you have 2 votesites?

**Comment by slvlr** [comment]
I think I sorted it, thank you
