### ISSUE TITLE
/vote and /av gui and any other command not working

### ISSUE THREAD

**Issue by noellerjd** [BenCodez/VotingPlugin#555]
I get no error, I get no input back; except when I use /avBackgroundUpdate which shows up as a command when I type /av but only says unknown command, could you help me fix this?

Server Log https://pastebin.com/raw/muqhLHb9

Plugins (26): LuckPerms, dynmap, WorldEdit, WildTP, ClearLag, WorldBorder, Votifier, Multiverse-Core, VotingPlugin, Images, mcMMO, Vault, GriefPrevention, ChestShop, Essentials, RestrictedCreative, Jobs, CommandSigns, Citizens, EssentialsXMPP, EssentialsProtect, EssentialsGeoIP, ChatEx, EssentialsSpawn, dtlTradersPlus, CrateReloaded

**Comment by noellerjd** [comment]
I tried deleting both the jar and folder, and fresh installing; but still it doesn't let me use any commands; I am op

**Comment by BenCodez** [comment]
I have no idea. Looks like a liabiary is missing in spigot or something.
