### ISSUE TITLE
Votes arent going through the server

### ISSUE THREAD

**Issue by NiceGuyMitch** [BenCodez/VotingPlugin#558]
so iv set up the plugin evrything works absolutly fine but the rewards dont seem to be send to the player is there any mistake you see in the config?
[Nieuw tekstdocument (2).txt](https://github.com/Ben12345rocks/VotingPlugin/files/3320997/Nieuw.tekstdocument.2.txt)

**Comment by BenCodez** [comment]
Can you pastebin your configs?
