### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Jg747** [BenCodez/VotingPlugin#559]
Here's the Log

https://pastebin.com/0HAFQmeH

**Comment by BenCodez** [comment]
[12:46:26] [Server thread/WARN]: java.sql.SQLException: null,  message from server: "Host 'autoapi.servereasy.it' is not allowed to connect to this MySQL server"

**Comment by Jg747** [comment]
How do i resolve this?

This is my config in lobby (same in Creative and Factions): https://pastebin.com/mbR7vrRb

**Comment by Jg747** [comment]
With other plugins it works, yours is the one that not works and i don't know why

**Comment by BenCodez** [comment]
It's not on my end, nothing I can do. You need to allow the connection on the mysql server.

**Comment by Jg747** [comment]
Why is only your plugin doing this? How can i allow the connection if access informations are right? (sorry for my multiple messages)

**Comment by Jg747** [comment]
OK I DID IT

I only changed my host, first i had my VPS IP address, now i have the simple localaddress (127.0.0.1 or localhost)
