### ISSUE TITLE
It doesn't work for me please help <3

### ISSUE THREAD

**Issue by Welnnys** [BenCodez/VotingPlugin#560]
My VoteSites.yml.Please help me <3

VoteSites:
  # VoteSite name
  Minecraft Multiplayer:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: true
    Enabled: true
    
    # Display name of voting site
    Name: 'Minecraft Multiplayer'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraft-mp.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://minecraft-mp.com/server/224555/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
       Console:
       - 'crate key %player% vote 1'
      # Send player a message
      Messages:
        Player: '&a&lТи успешно vote-на!'
  # VoteSite name
  Planet Minecraft:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: true
    Enabled: true
    
    # Display name of voting site
    Name: 'Planet Minecraft'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 4
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://www.planetminecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://www.planetminecraft.com/server/vexcraft-4323692/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
       Console:
       - 'crate key %player% vote 1'
      # Send player a message
      Messages:
        Player: '&a&lТи успешно vote-на!'
  # VoteSite name
  Minecraft Servers:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: true
    Enabled: true
    
    # Display name of voting site
    Name: 'Minecraft Servers'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 3
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'https://minecraftservers.org'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://minecraftservers.org/vote/554292'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
       Console:
       - 'crate key %player% vote 1'
      # Send player a message
      Messages:
        Player: '&a&lТи успешно vote-на!'
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by BenCodez** [comment]
Pastebin it.

**Comment by Welnnys** [comment]
Appreciete it hope it works ^^ <3

**Comment by Welnnys** [comment]
Hey what is pastebin and how am I supposed to use it ?

**Comment by Welnnys** [comment]
https://pastebin.com/iLTg5E7D

**Comment by Welnnys** [comment]
here ^^ <3

**Comment by BenCodez** [comment]
Your service sites are incorrect, vote on the site and it will tell you the
service site in console. You have a few random lines which aren't
commented, that would mess things up as well. Can't say much more until I
got on my PC later.

**Comment by Welnnys** [comment]
I made it work appreciete the help tho <3 + such a good plugin <3

**Comment by Welnnys** [comment]
Hey it works now.it shows the votes and other things but when I vote with fakevote it gives the reward ( crate key ) but when somebody votes it doesn't .Can you help me please <3 :) ?

**Comment by Welnnys** [comment]
https://pastebin.com/YBshGuJN
