### ISSUE TITLE
VoteForwarding doesn't work

### ISSUE THREAD

**Issue by Jg747** [BenCodez/VotingPlugin#561]
I configured my server with the BungeeSetup. I connected all my servers to MySQL database, i set the ProcessRewards to false in Lobby and ClearCacheOnJoin - ClearCacheOnUpdate to false and AlwaysUpdate to true in Creative and Factions server.

Well it doesn't forward the vote. I did tge fakevote and it didn't forward. I tried to vote on the site and it doesn't forward.

How can i fix? (if you need config or something else contact me)

**Comment by BenCodez** [comment]
You can't forward with all the servers having the database. It will go only on one server.

**Comment by Jg747** [comment]
Ok I found the error. I put the VPS IP on Host instead of LoocalHost

**Comment by Jg747** [comment]
Sorry for my response, i thought it was for another thread. But ok now i understand
