### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by stw222** [BenCodez/VotingPlugin#563]
i used 
/av user techuntrtm forcevote planetminecraft_com
and it gives this error:
[https://pastebin.com/rdcnB2i9](https://pastebin.com/rdcnB2i9)

this is my config:
[config](https://pastebin.com/Miw1HSwQ)

[votesites.yml](https://pastebin.com/ss6s3yQ9)

[easyrewards.yml](https://pastebin.com/FwEjpgzU)

[hardrewards.yml](https://pastebin.com/gUUpANBz)

[allrewards.yml](https://pastebin.com/AP6EDyb2)

[allsiterewards.yml](https://pastebin.com/eatnnq1w)

im not really sure what is causing this error. it could be some mistake i made in the config because i had a few of those when some of these files wouldnt load.

**Comment by BenCodez** [comment]
Turn debug on and extra debug on and send the log when you test it.

**Comment by stw222** [comment]
[https://pastebin.com/DHnSBhW3](https://pastebin.com/DHnSBhW3)

**Comment by BenCodez** [comment]
I need the server log.

**Comment by stw222** [comment]
[https://pastebin.com/cnPNUZpK](https://pastebin.com/cnPNUZpK)

**Comment by BenCodez** [comment]
You misspelled this on the easyrewards
 MaxAmound: 3

**Comment by stw222** [comment]
fixed that typo

**Comment by BenCodez** [comment]
I assume that fixed it?

**Comment by stw222** [comment]
nope. still generates an error

**Comment by BenCodez** [comment]
Can you send it?

**Comment by stw222** [comment]
[https://pastebin.com/5tACabcH](https://pastebin.com/5tACabcH)

**Comment by BenCodez** [comment]
Same problem in hard rewards, I would check them all.

**Comment by stw222** [comment]
Ill check them when i get time

**Comment by stw222** [comment]
that seems to have fixed it. I do have one question though, where do I put reward files so they activate when someone votes for a week strait or something like that?

**Comment by BenCodez** [comment]
Under vote streak in the Config.yml
