### ISSUE TITLE
Items not dropping on the ground when inventory is full

### ISSUE THREAD

**Issue by Davidozs** [BenCodez/VotingPlugin#564]
Exactly as the title says, players with a full inventory that vote for the server don't get their rewards at all. I'd like the items to drop on the ground when their inventory is full, but I can't find the setting  to enable this. Any help?

**Comment by BenCodez** [comment]
Console log with debug when that happens?

**Comment by Davidozs** [comment]
> [23:04:56] [Votifier NIO worker/INFO]: [Votifier] Got a protocol v1 vote record from /149.202.74.183:58264 -> Vote (from:Minecraft-MP.com username:Leytew address:80.12.33.91 timeStamp:1561755897 localTimestamp:1561755896257)
> [23:04:56] [Server thread/INFO]: [VotingPlugin] Recieved a vote from 'Minecraft-MP.com(80.12.33.91)' by player 'Leytew'!
> [23:04:56] [Craft Scheduler Thread - 9/INFO]: [Broadcast] Thanks Leytew for voting on Minecraft-Mp
> [23:04:56] [Server thread/INFO]: CONSOLE issued server command: /give Leytew experience_bottle 5
> [23:04:56] [Server thread/INFO]: Giving 5 of experience bottle to Leytew.
> [23:04:56] [Server thread/INFO]: Not enough space, 5 experience bottle was lost.
> [23:04:56] [Server thread/INFO]: CONSOLE issued server command: /give Leytew diamond 2
> [23:04:56] [Server thread/INFO]: Giving 2 of diamond to Leytew.
> [23:04:56] [Server thread/INFO]: Not enough space, 2 diamond was lost.

**Comment by Davidozs** [comment]
call me dumb, I have no clue where to find the debug.

**Comment by BenCodez** [comment]
[23:04:56] [Server thread/INFO]: CONSOLE issued server command: /give Leytew experience_bottle 5
[23:04:56] [Server thread/INFO]: Giving 5 of experience bottle to Leytew.
[23:04:56] [Server thread/INFO]: Not enough space, 5 experience bottle was lost.

You need to use the reward api to give the item, not a command (unless another plugin does it)

**Comment by Davidozs** [comment]
Alright, that's done in the config right?

**Comment by BenCodez** [comment]
Wherever the reward is.

**Comment by Davidozs** [comment]
Alright, thanks for helping out.
