### ISSUE TITLE
[Suggestion] Limit mensual votes

### ISSUE THREAD

**Issue by SeruhioX** [BenCodez/VotingPlugin#565]
I would like an option that limits the number of votes a user can have monthly to the maximum number of days you have that month.

Occasionally there is a user who gets (I do not know exactly how) 1 or 2 votes more than the other people, for example this month there was a user with 31 votes when the month was 30 days.

Something like this:

YearMonth yM = YearMonth.of(year, month);
int daysInMonth = yM.lengthOfMonth();

Obviously this would be multiplied by the number of pages you have to vote.

I hope you can do something like that, since I have since all the users who vote all month can receive a reward and only gave it to one user because to have 1 vote more than the others.

**Comment by BenCodez** [comment]
I think something like this could work. I'll try to add it.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Untested.

New option:

    # Limit monthly votes to number of days of a month
    LimitMonthlyVotes: false

**Comment by BenCodez** [comment]
This is now available in the latest spigot version

**Comment by SeruhioX** [comment]
Hello,

Last month, which had 30 days, there was one person who got 31 votes, that made only one person get the reward and the rest I had to give them manually. Could it be that are not setting the value of the month correctly?

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That better?
