### ISSUE TITLE
How to add a reward w/ chance?

### ISSUE THREAD

**Issue by willc5** [BenCodez/VotingPlugin#569]
Here is one of the sites configs:

VoteSites:
  PlanetMinecraft:
    Enabled: true
    ServiceSite: PlanetMinecraft
    VoteURL: https://www.planetminecraft.com/server/simplysurvival-4313758/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        Console:
        - eco give %player% 20
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

How do I add a 33% chance reward to give the player a vote key?
Also, why do the voting sites double in /vote when I reload the plugin? They either double or more show up but they are duplicates

**Comment by BenCodez** [comment]
Rewards:
      # Your other rewards
      Rewards:
        Chance: 33
        Commands:
        - crate key command

Your service site is wrong, the plugin is making a new site because of that.

**Comment by willc5** [comment]
Thanks. And to remove the messsage sent to the player, just remove the messages section?

**Comment by BenCodez** [comment]
Yep.
