### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by SinderellaDeVita** [BenCodez/VotingPlugin#572]
My voting stopped giving rewards randomly, my console is not showing any issues,
I'm at a loss as to what to do,

**Comment by BenCodez** [comment]
Is the server getting the vote?

**Comment by SinderellaDeVita** [comment]
on the page it does, it just doesn't announce it or give rewards on the server

**Comment by BenCodez** [comment]
Then the server doesn't get the vote...

**Comment by SinderellaDeVita** [comment]
So how do i fix this?

**Comment by BenCodez** [comment]
Check your votifier connection.

**Comment by SinderellaDeVita** [comment]
How do I do that? I've never used votifer before.

**Comment by BenCodez** [comment]
Then how did you get it to work in the first place? Check your startup log, see if it enables properly.

**Comment by SinderellaDeVita** [comment]
I watched a video.  It was enbled properly. It gave rewards for two days. But just randomly stopped

**Comment by BenCodez** [comment]
Check the startup log. Restart the server.

**Comment by SinderellaDeVita** [comment]
okay I looked it says this 
[08:47:29] [Votifier NIO boss/ERROR]: [Votifier] Votifier was not able to bind to /167.114.102.117:8192
also there is this
[08:47:30] [Server thread/WARN]: [VotingPlugin] No vote has been recieved from www.planetminecraft.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

**Comment by BenCodez** [comment]
Try a new port.

**Comment by SinderellaDeVita** [comment]
Idk how to do that. But okay lol

**Comment by SinderellaDeVita** [comment]
I called my cable company and they said "They don't allow people to log into the routers" so is there a way to fix this without port forwarding?

**Comment by BenCodez** [comment]
Why do you need to port forward? I don't have any control over that.

**Comment by SinderellaDeVita** [comment]
Don't you have to port forward to get a new port?

**Comment by BenCodez** [comment]
Just change the number in the config of votifier....

**Comment by SinderellaDeVita** [comment]
Seriously, that easy..

**Comment by BenCodez** [comment]
It should be :)

**Comment by SinderellaDeVita** [comment]
that worked.
I feel stupid.
Thanks for the help
