### ISSUE TITLE
Plugin trying to change time?

### ISSUE THREAD

**Issue by JasonHorkles** [BenCodez/VotingPlugin#573]
When my server starts, the plugin says this:
`[08:17:07 INFO]: [VotingPlugin] Time change: DAY, Fake: false
[08:17:07 INFO]: [VotingPlugin] Created zip file at D:\Server\plugins\VotingPlugin\Backups\Backup-2019_JULY_11.zip`
What's it supposed to mean when it says that? Also, is there any way to prevent it from saying those things?
Thanks

**Comment by BenCodez** [comment]
It's detecting that it's a different time then when it last checked the time.
