### ISSUE TITLE
Having trouble adding ranks to rewards

### ISSUE THREAD

**Issue by Nikkiokbye** [BenCodez/VotingPlugin#575]
Hello, I am trying to add ranks promotions to my milestone rewards however I can't seem to figure it out. I believe it's just a simple spacing error but I'm not sure. 

 '35':
    Enabled: true
    Rewards:
     Commands:
     - 'lp user %player% parent set Noble'
      Messages:
        Player: '&2You have been promoted to Noble!'

**Comment by Nikkiokbye** [comment]
https://pastebin.com/W4XQ534g

**Comment by BenCodez** [comment]
You have yml errors
https://yaml-online-parser.appspot.com/
