### ISSUE TITLE
Could not pass event InventoryOpenEvent to VotingPlugin v5.19.1

### ISSUE THREAD

**Issue by malsem** [BenCodez/VotingPlugin#576]
14.07 13:27:50 [Server] ERROR Could not pass event InventoryOpenEvent to VotingPlugin v5.19.1
14.07 13:27:50 [Server] INFO java.lang.NullPointerException: null
14.07 13:27:50 [Server] INFO 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory.onInvOpen(BInventory.java:371) ~[?:?]
14.07 13:27:50 [Server] INFO 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor656.execute(Unknown Source) ~[?:?]
14.07 13:27:50 [Server] INFO 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1169) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.EntityPlayer.openContainer(EntityPlayer.java:1142) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.BlockChest.interact(BlockChest.java:202) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.IBlockData.interact(IBlockData.java:226) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:489) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1392) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:50 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
14.07 13:27:52 [Server] ERROR Could not pass event InventoryOpenEvent to VotingPlugin v5.19.1
14.07 13:27:52 [Server] INFO java.lang.NullPointerException: null
14.07 13:27:52 [Server] INFO 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory.onInvOpen(BInventory.java:371) ~[?:?]
14.07 13:27:52 [Server] INFO 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor656.execute(Unknown Source) ~[?:?]
14.07 13:27:52 [Server] INFO 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1169) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.EntityPlayer.openContainer(EntityPlayer.java:1142) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.BlockChest.interact(BlockChest.java:202) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.IBlockData.interact(IBlockData.java:226) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:489) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1392) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-131]
14.07 13:27:52 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

Im running paper 1.14.3 build #131

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That work?
