### ISSUE TITLE
Unable to send vote to (ip):(port)

### ISSUE THREAD

**Issue by FireByteApplications** [BenCodez/VotingPlugin#578]
So i have configured everything corrects that i am aware of but whenever i send a test vote from one of my voting webistes i get this error 24.07 07:38:59 [Server] SEVERE Unable to send vote to /167.114.186.68:1267. Will retry sending in 8 second(s).
24.07 07:38:59 [Server] INFO Sent request: VoteRequest{challenge='1fbhj8dlh7hu6s59ds5dru9rjo', vote=Vote (from:MinecraftServers.org username:MinecraftServers.org address:127.0.0.1 timeStamp:1563953928 
I will attach my proxy and 2 backend server config files
[Config files.zip](https://github.com/Ben12345rocks/VotingPlugin/files/3425601/Config.files.zip)

**Comment by BenCodez** [comment]
Don't think its anything to do with VotingPlugin. Try new ports?

**Comment by FireByteApplications** [comment]
Oh crap sorry this was meant for nuvotifier aha soz
