### ISSUE TITLE
Can't find the place to see global votes (total votes from all voting sites the server received)

### ISSUE THREAD

**Issue by Davidozs** [BenCodez/VotingPlugin#579]
As the title says, I can't find a command, or a place in the config where you can simply see the total amount of votes the server has gotten, from every voting site configured. Right now I just count from voting site to voting site, but there must be an alternative for this. Any help?

**Comment by BenCodez** [comment]
/vote Total All : VotingPlugin.Commands.Vote.Total.All|VotingPlugin.Player
