### ISSUE TITLE
VotingPlugin issues

### ISSUE THREAD

**Issue by VictorK-M** [BenCodez/VotingPlugin#580]
For some reason, I can't get VotingPlugin to work. I keep getting errors in my console and I'm not sure of what to do. 
[Here's the errors I'm getting.](https://pastebin.com/Ep21SJwZ)

**Comment by BenCodez** [comment]
You have a yml error in the config

**Comment by VictorK-M** [comment]
Yeah that I understand, I don't understand why I get it. I should probably have sent my config, but [here it is](https://pastebin.com/P0FExbbi)

**Comment by BenCodez** [comment]
Can't tell from my phone, will have to look into it later

**Comment by BenCodez** [comment]
I have no idea where the problem is. Try a fresh config?
