### ISSUE TITLE
No permissions

### ISSUE THREAD

**Issue by JoshJJones** [BenCodez/VotingPlugin#581]
Being told I don't have enough permissions in chat when I try and do /vote, or if any player does it. Keep in mind I have * permission, latest votingplugin on spigot, latest nuvotifier.

JoshJones was denied access to command, required permission: VotingPlugin.Commands.Vote|VotingPlugin.Player

No other console errors at all

Paperspigot 1.13.2
Ultrapermissions for perm handling

**Comment by BenCodez** [comment]
Manually add the perm? I feel like something is wrong, since by default you have permission to that command. Never use ultrapermissions, so no idea.

**Comment by JoshJJones** [comment]
It's a great plugin, and I've set both perms for the groups, no success

VotingPlugin.Player is a bundle thing too right? that doesn't work either

**Comment by BenCodez** [comment]
Try a different permission plugin?

**Comment by JoshJJones** [comment]
It's my primary permissions plugin, and it's premium, no issues with any else at all so far.

**Comment by BenCodez** [comment]
Well, I have no idea.

**Comment by JoshJJones** [comment]
I'm also op so permissions shouldn't be an error for me even if it was for players.

**Comment by JoshJJones** [comment]
I'm stumped too

**Comment by BenCodez** [comment]
Do you have vault?

**Comment by JoshJJones** [comment]
Yep

**Comment by BenCodez** [comment]
Latest version, spigot, etc...

**Comment by JoshJJones** [comment]
https://www.spigotmc.org/resources/vault.34315/
That version of vault.

PaperSpigot 1.13.2

**Comment by BenCodez** [comment]
votingplugin version? Does it work using just spigot? Other than that I have no idea.

**Comment by JoshJJones** [comment]
Whatever the current version on spigotmc is... I updated an hour ago just in case it was my version, was working up until very recently with no major changes

Also nuvotifier current version

**Comment by BenCodez** [comment]
My first guess is the permission plugin, but I have no clue without testing.

**Comment by JoshJJones** [comment]
I mean it's premium so I can't share it.
I understand that can be a wall, just causing a huge issue for me that's all

**Comment by BenCodez** [comment]
Get a test server testing it with a different perm plugin?

**Comment by BenCodez** [comment]
Try this:
http://ben12345rocks.com/job/VotingPlugin/

Add this option:

    DisableVaultPermissions: true

**Comment by JoshJJones** [comment]
Trying it now

**Comment by JoshJJones** [comment]
Worked fine, does that allow users to use any command without permission now though?

**Comment by BenCodez** [comment]
Shouldn't. It just uses the server to handle the permission check rather than vault.

**Comment by JoshJJones** [comment]
Ok, thanks. 
Both for the fix and the quick replies.

**Comment by BenCodez** [comment]
This would mean the permission plugin isn't hooking into vault correctly.

**Comment by bryantvdberg** [comment]
I have this issue also with ultra Permission. Only with * permission i can do /vote

**Comment by BenCodez** [comment]
Then apply the same fix...
