### ISSUE TITLE
I can't find any option for cumulative voting // rewards after x amounts of votes.

### ISSUE THREAD

**Issue by Davidozs** [BenCodez/VotingPlugin#585]
I have searched through the config multiple times, the wiki, youtube, anything. But I can't find anything about the so called " cumulative voting " that was mentioned on the spigot page. I want to have players get rewards after voting certain amounts of times, but I really can't find any examples or explanations for it. Any help?

**Comment by BenCodez** [comment]
It's in the Config.yml, with all the other rewards
