### ISSUE TITLE
Problem with GUI

### ISSUE THREAD

**Issue by poqdavid** [BenCodez/VotingPlugin#586]
I am using Spigot 1.12.2 and i keep getting these errors how i can fix the default config so these work
https://pastebin.com/RK4b5NUy

**Comment by BenCodez** [comment]
Read the plugin page. Latest versions supports 1.13+ only.

**Comment by poqdavid** [comment]
Oh which version should i be using?

**Comment by BenCodez** [comment]
Read the plugin page.
