### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by 6ixxes** [BenCodez/VotingPlugin#590]
https://pastebin.com/dBVT1cwv

These errors occur on server startup and also when a player joins the server.

**Comment by BenCodez** [comment]
Use spigot

**Comment by 6ixxes** [comment]
Will I have any compatibility issues between bukkit/ spigot plugins?

**Comment by BenCodez** [comment]
No... There is no reason why it should matter

**Comment by 6ixxes** [comment]
Got everything working. Thanks for the quick response.
