### ISSUE TITLE
Rewards for vote count

### ISSUE THREAD

**Issue by willc5** [BenCodez/VotingPlugin#591]
Can you give a reward/run a command when a player reaches a certain amount of votes?

**Comment by BenCodez** [comment]
On the plugin page:

    Give rewards for the following:
      For specific sites or every site (Configured in VoteSites.yml)
      All Sites - A reward for voting on all sites
      First Vote - Reward for first time voting
      Voting x amount of votes (with per day/week option), also known as Cummulative rewards - Vote x number of times for reward
      Milestones - Give player a 1 time reward for voting x amount of times (Can be reset monthly)
      VoteStreak - Give player for voting x number of times in a row
      VoteParty - Everyone on server (or who voted) get reward after x amount of global votes
      VoteCoolDownEnded - Give a reward when player can vote again

**Comment by willc5** [comment]
Thanks.

Also you reply so damn fast
