### ISSUE TITLE
Votepoints

### ISSUE THREAD

**Issue by sikur7** [BenCodez/VotingPlugin#592]
Hi. I've been using votingplugin and the voteshop and players are supposed to receive 1 votepoint with every vote, which they do. But something clears them. E.g. they'll vote, receive 8, then 30 minutes later it'll say they have 0 even after not spending any of them. I really can't imagine what the issue is as its extremely randomized. Thanks.

**Comment by BenCodez** [comment]
Turn debug on and extra debug and send the logs between checking the points.
