### ISSUE TITLE
VotePlugin Total Votes Resets Upon Server Restart

### ISSUE THREAD

**Issue by AlureonTM** [BenCodez/VotingPlugin#593]
So everytime my server restarts the total votes for each player is reset. This causes quite a few issues. 

#1: Total Votes signs are no longer accurate
#2: when people do /vote it tells you you are able to vote on the sites when you cant

**Comment by BenCodez** [comment]
Wanna provide me with more details? Sounds like a storage issue.

**Comment by AlureonTM** [comment]
Umm, not sure what kinda details you want. Do you have discord so I can show you? It definitely does seem like a storage issue. Basically, if I voted for all options, and the server restarts. All of them show up as I can vote again. On top of that, in spawn I have signs with the top voters. All of them are incorrect and then reset to 0 total votes after a restart.

**Comment by BenCodez** [comment]
Data storage? With copy?
Server logs? With debug and extra debug?
Latest version? Server version?

**Comment by AlureonTM** [comment]
Server Ver: 1.14 (currently PaperMC but was using Spigot and has same issue)
Latest version of the plugin
Dunno what server logs you want...if I pasted them all it would be way too much.
Not sure what u mean by data storage with copy?

**Comment by BenCodez** [comment]
Just server logs, and some image of the storage before it resets and after?

**Comment by BenCodez** [comment]
Try it with the latest spigot version.

**Comment by AlureonTM** [comment]
I tried it with the latest Spigot version. Had the same issue. Here are a couple of screenshots of all the files. This what you wanted for storage? https://i.imgur.com/kQniH2Z.png https://i.imgur.com/GMAfQJj.png https://i.imgur.com/DYpjLsG.png https://i.imgur.com/bIKW6Ds.pnghttps://i.imgur.com/Ue6k88a.png

Logs for a full day (8/10/2019): https://pastebin.com/Tj7d3NFD

**Comment by BenCodez** [comment]
What user storage do you have?

**Comment by AlureonTM** [comment]
DataStorage: SQLITE is what is in the config. Full config can be seen here. https://pastebin.com/hDbHwVj1

**Comment by BenCodez** [comment]
Switch to mysql or flat and see if that works

**Comment by AlureonTM** [comment]
Update, I switched to flat and it seems to be working better but still not perfect. E.g my top monthly voter was higher than my alltime voter. Anyway should be fine.

**Comment by James-P-Bennett** [comment]
Same issue happened on one of my high pop servers today, I fugured it was a first of the month thing but only several people lost progress. Switched to flatfile after I couldn't identify any mysql issues in the log. 

![image](https://github.com/BenCodez/VotingPlugin/assets/85420204/e6d3f6e7-2937-4d47-bb46-f61adbb77148)

**Comment by BenCodez** [comment]
Your quite a few versions behind

**Comment by James-P-Bennett** [comment]
I generally avoid plugin updates that contain Config option changes that could potentially break a the existing one on the live server or reset progress. Yet it looks like [6.12.2](https://www.spigotmc.org/resources/votingplugin.15358/update?update=498580) fixes an issue with SQLite storage when it comes to monthly time changes. Sounds like the prognosis of what happened today.

**Comment by BenCodez** [comment]
I usually try to prevent breaking changes in updates unless it's unavoidable

**Comment by James-P-Bennett** [comment]
Yes, I noticed! Thank you, didn't have to change anything to update
