### ISSUE TITLE
not always getting rewards

### ISSUE THREAD

**Issue by irobertrs** [BenCodez/VotingPlugin#594]
I have my votesite set up with a few sites. the voting go through and register all fine but only some sites will give rewards and a few wont, not sure what i did wrong as its all doing the same command but if someone votes on 6 sites they get around 3- 4 rewards. I have attached the votesite and it says they get 2 crates on it as thats my temp fix giving them extra crates.

https://pastebin.com/Lu9BG0eE

**Comment by BenCodez** [comment]
What does it say in console when you vote?
If you get nothing, then it's an issue with votifier.

**Comment by irobertrs** [comment]
10.08 11:24:22 [Server] INFO [Votifier] Got a protocol v1 vote record from /173.199.123.179:43702 -> Vote (from:Minecraft-Server.net username:bobbyrass address:175.39.25.229 timeStamp:1565400261 localTimestamp:1565400262294)
10.08 11:24:22 [Server] INFO [VotingPlugin] Recieved a vote from service site 'Minecraft-Server.net' by player 'bobbyrass'!

**Comment by irobertrs** [comment]
sorry for the mess on that

**Comment by BenCodez** [comment]
Does ti work with /av vote? Which sites don't work?

**Comment by irobertrs** [comment]
minecraft server list is the only one im 100% sure dosnt work for me. /av vote works

**Comment by BenCodez** [comment]
Make sure you have the right service site (Vote on the site and check console for it)

**Comment by irobertrs** [comment]
well one thing too is whenever it happens it seems to revert the votesites file to a older one that has 2 sites without vote urls

**Comment by BenCodez** [comment]
Did you reload the plugin? That means it's creating a site since no site exists with the proper service site. It will say that in console.

Just check console... it will tell you
