### ISSUE TITLE
voting file reverts

### ISSUE THREAD

**Issue by irobertrs** [BenCodez/VotingPlugin#596]
My votingsites.yml file keeps reverting back to a older file 

it will be like this which is the good voting site file -->
![good](https://user-images.githubusercontent.com/53958548/62829011-41857800-bc37-11e9-857c-ad87bc0f80d6.png)

Then it will revert to the older file and make /vote do this -->
![bad](https://user-images.githubusercontent.com/53958548/62829013-4ea26700-bc37-11e9-83ff-79b4f22cf3d7.png)

every time i restart it changes back and i deleted everything and saved a copy of the good voting site file and replaced it and started the server but still does it.

**Comment by BenCodez** [comment]
Those sites are added because there is no voting site with the proper service site, read the console log.
