### ISSUE TITLE
Sites not showing up under 'All Voting Sites'

### ISSUE THREAD

**Issue by CMCosMic** [BenCodez/VotingPlugin#597]
When I open the gui and click all voting sites, none are showing up. Heres my VoteSites.yml

https://pastebin.com/wpe2KjbD

**Comment by BenCodez** [comment]
Pastebin that.

**Comment by CMCosMic** [comment]
> Pastebin that.

Updated,

**Comment by BenCodez** [comment]
Commands:
    - command here

Config.yml as well?

**Comment by CMCosMic** [comment]
> ```
> Commands:
> - command here
> ```
> 
> Config.yml as well?

https://pastebin.com/xznJ8CLP

**Comment by BenCodez** [comment]
Other than that command issue (change it to what I sent you), it should work.

Wanna send screenshots or something so I can see what you see? Does a restart fix it?

**Comment by CMCosMic** [comment]
Actually, looks like it was the command that made it stop, thanks so much. Also is there a command to reload the plugin instead of stopping it every change?
