### ISSUE TITLE
Adding 'Choices' to 'AllSites'

### ISSUE THREAD

**Issue by Khongen** [BenCodez/VotingPlugin#598]
Hey, I'll cut right to the chase, I want to make certain choice "kits" for my smaller server and give them the option to get one kit after voting on all websites.

I have issues with using the correct format however, could you help me make the plugin read it correctly?

`AllSites: 
   Enabled: true
   EnableChoices: true
   Choices:
  Sleepy:
    DisplayItem:
      Name: '&cGoodnight'
      Material: PINK_BED
      Amount: 2
    Rewards:
      Items:
        Sleepy:
          Material: 'PINK_BED'
          Amount: 2
    Rewards:
      Items:
        Sleepy:
          Material: 'MILK_BUCKET'
          Amount: 2
    Rewards:
      Items:
        Sleepy:
          Material: 'COOKIE'
          Amount: 2
      Messages:
        Player: '&aYou picked %choice%'
  Miner:
    DisplayItem:
      Name: '&cMiners dream'
      Material: IRON_PICKAXE
      Amount: 1
    Rewards:
      Items:
        Miner:
          Material: 'TORCH'
          Amount: 48
    Rewards:
      Items:
        Miner:
        Material: 'IRON_PICKAXE'
          Amount: 1
          Enchants:
            unbreaking: 1
            efficiency: 2
      Messages:
        Player: '&aYou picked %choice%'
  Flower:
    DisplayItem:
      Name: '&cFlower power'
      Material: CORNFLOWER
      Amount: 1
      Enchants:
        unbreaking: 1
    Rewards:
      Items:
        Flower:
          Material: 'CORNFLOWER'
          Amount: 32
    Rewards:
      Items:
        Flower:
        Material: 'Poppy'
          Amount: 1
          Enchants:
            knockback: 3
    Rewards:
      Items:
        Flower:
        Material: 'PINK_TULIP'
          Amount: 12
    Rewards:
      Items:
        Flower:
        Material: 'ORANGE_TULIP'
          Amount: 12
    Rewards:
      Items:
        Flower:
        Material: 'RED_TULIP'
          Amount: 12
      Messages:
        Player: '&aYou picked %choice%'
  Food:
    DisplayItem:
      Name: '&cFood Coma'
      Material: SUSPICIOUS_SOUP
      Amount: 1
      Enchants:
        unbreaking: 1
    Rewards:
      Items:
        Food:
          Material: 'GOLDEN_CARROT'
          Amount: 3
    Rewards:
      Items:
        Food:
        Material: 'BREAD'
          Amount: 5
    Rewards:
      Items:
        Food:
        Material: 'SUSPICIOUS_SOUP'
          Amount: 1
    Rewards:
      Items:
        Food:
        Material: 'CAKE'
          Amount: 1
    Rewards:
      Items:
        Food:
        Material: 'COOKIE'
          Amount: 12
      Messages:
        Player: '&aYou picked %choice%'`

**Comment by Khongen** [comment]
![image](https://user-images.githubusercontent.com/54181176/63176208-cb717e80-c045-11e9-9085-09f25afeda4b.png)
I got a picture of the first "kit" for better understanding

**Comment by BenCodez** [comment]
Pastebin that. The rewards are incorrect, send a pastebin and I can correct it.

**Comment by Khongen** [comment]
https://pastebin.com/fGPX1Z01

thank you for being so active, really appreciate it

**Comment by BenCodez** [comment]
https://pastebin.com/HEngMhLr

Something like that.

**Comment by Khongen** [comment]
Hey again, so that worked out very well! 
I still have an issue with the claimage of the "choice" reward, how do I add a visual to this so you can see you have an available unclaimed choice?

This is what it looks like even though I have given myself the reward, and it works if I click the first empty spot, theres just no visual.

**Comment by Khongen** [comment]
![image](https://user-images.githubusercontent.com/54181176/63217966-2bece280-c150-11e9-845c-0fc59eea7f3f.png)

**Comment by BenCodez** [comment]
The reward needs a display item, forgot about that.

**Comment by Khongen** [comment]
So where in the format you sent me should I add that?

**Comment by BenCodez** [comment]
Under allsites.

**Comment by Khongen** [comment]
![image](https://user-images.githubusercontent.com/54181176/63218458-b1c25b00-c15b-11e9-8099-db9505c26ae5.png)
Like this?

**Comment by BenCodez** [comment]
Looks right.

**Comment by Khongen** [comment]
The command to get the allsites rewards are found under /votechoices right?

**Comment by BenCodez** [comment]
that's an alias, but yes.

**Comment by Khongen** [comment]
ah what's the straight up way to get there then?

**Comment by Khongen** [comment]
The DisplayItem didn't work sadly, any idea where I did wrong?

**Comment by BenCodez** [comment]
Delete the file named AllSites in VotingPlugin/Rewards and regive the reward, see if that works then.

**Comment by Khongen** [comment]
So I gave myself the reward by /av gui -> user -> myself -> give reward
But since the reward isnt there anymore how do I make it generate again?

**Comment by Khongen** [comment]
There's a command to help me with that?

**Comment by Khongen** [comment]
So I reloaded the plugin using the av gui and the reward .yml for allsites is just an empty file

**Comment by BenCodez** [comment]
Any errors? Latest version? Delete the file to let it regenerate?

**Comment by Khongen** [comment]
Ah sorry I will have to check tomorrow! It is soon 3 am :)

**Comment by Khongen** [comment]
Sleep well when you get to that point and thank you a lot for the help!

**Comment by Khongen** [comment]
hey again, sorry for the long wait, so I got it to work!

**Comment by Khongen** [comment]
The new error I'm facing is a bit of a tricky one though, so I have a friend that for some reason doesn't have his "pop-up" thing close when he choose 1 reward, so he can basically stack if infinite. I also tried it myself and it only happens for him (can be repeated) and when I try to spam it, I can do the reward 1-3 times according on the tps of the server maybe. 

Any way to limit the rewards to 1 after they already received 1 reward with a daily timer? So this can be avoided? fx. "You already spent your daily kit token!"

**Comment by Khongen** [comment]
Also for anyone interested in how my final choices looks in the config here you go:
https://pastebin.com/qAmJdjg6
This added 4 different kits.

**Comment by BenCodez** [comment]
Does that person have multiple unclaimed rewards (look in his usser data)
