### ISSUE TITLE
VotingPlugin i want players to only recive when online, how is that possible to do?

### ISSUE THREAD

**Issue by AchyMake** [BenCodez/VotingPlugin#599]
i tried so many ways then accidently reset the scoreboard of top all votes.......
how the do i make it so it only sent's to online/connected server?
it's pretty annoying that they can  just be offline and vote every day and not being online

then they recive the keys anyways why is that on default? and how the do i change that?

**Comment by BenCodez** [comment]
Add RewardType: ONLINE in the reward.

**Comment by AchyMake** [comment]
PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      RewardType: Online
      Commands:
        - crates givekey %player% vote 1
        - eco give %player% 200
        - execute as %player% at @s run playsound minecraft:item.book.page_turn master %player% ~ ~ ~ 0.25 1

**Comment by AchyMake** [comment]
yes?

**Comment by AchyMake** [comment]
no it was not there
where do i type that?

**Comment by AchyMake** [comment]
in the config.yml or wich file?

**Comment by AchyMake** [comment]
i tried this aswell

  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: VoteURL
    VoteDelay: 24
    RewardType: ONLINE
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
        - crates givekey %player% vote 1
        - eco give %player% 200
        - execute as %player% at @s run playsound minecraft:item.book.page_turn master %player% ~ ~ ~ 0.25 1

**Comment by AchyMake** [comment]
come on dude what is the secret?
and why is this option so hidden

**Comment by AchyMake** [comment]
when can i hear about how to change this to online players only?

**Comment by AchyMake** [comment]
you should try explain little more specefik cause just that message is just useless 👎

**Comment by BenCodez** [comment]
Pastebin what you have?
What you had the first time looked right just it needed to be ONLINE. Also don't keeping asking in the review section and spamming me here. I will respond when I can.
