### ISSUE TITLE
Placeholder Issue

### ISSUE THREAD

**Issue by Al3366** [BenCodez/VotingPlugin#600]
Hey, the %money% placeholder does not round up nicely. Rather than showing what it does, could it be rounded to the nearest tenth to make it visually better for a player. In our case we want to tell them how much money they got. I've attached a picture of what it currently looks like.

Thank you

![image](https://user-images.githubusercontent.com/14044900/63377580-4f01d700-c388-11e9-88d0-d5937db9496d.png)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This better?

**Comment by Al3366** [comment]
It's closer. In terms of money, only 2 digits after the decimal are needed rather than 4. Could that be changed?

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should be good now, but didn't test it yet.
