### ISSUE TITLE
Cannot give players ultimate kit keys

### ISSUE THREAD

**Issue by Chronic-Reflexes** [BenCodez/VotingPlugin#603]
Hello, i am reporting a bug

Ive tried setting the command through console, and player, but the command will not deploy

Affected plugins: UltimateKits, and Voting Plugin

to reproduce:
Download ultimate kits, and voting plugin, make a kit with ultimate kits, enter the command on vote: uk key vote regular %player% 1

it wont give the player the key

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - 'command here %player%'

Is that how you have it?

**Comment by Chronic-Reflexes** [comment]
Commands:
  Console:
  - 'uk key vote Regular %player% 1'

**Comment by Chronic-Reflexes** [comment]
rewards:
 Commands:
 - 'uk key vote Regular %player% 1'

**Comment by Chronic-Reflexes** [comment]
tried with both, and still nada

**Comment by Chronic-Reflexes** [comment]
is there a discord i can join quick time

**Comment by BenCodez** [comment]
Pastebin it, neither are exactly what I had

**Comment by Chronic-Reflexes** [comment]
https://pastebin.com/G32WEigz

**Comment by BenCodez** [comment]
Pastebin the whole file

**Comment by Chronic-Reflexes** [comment]
https://pastebin.com/iBc0BVjJ

**Comment by Chronic-Reflexes** [comment]
im in the flatland world testing it btw

**Comment by BenCodez** [comment]
https://pastebin.com/AtBXugLn

Use that. Is the reward file listed? How are you testing it, with /av vote, /av givereward?

**Comment by Chronic-Reflexes** [comment]
im testing it with /av test
and tried it to no avail

**Comment by Chronic-Reflexes** [comment]
i originally tried making the thing with the gui
tried setting it for regular command, command.player and command.console
nothing worked

**Comment by Chronic-Reflexes** [comment]
any updates?

**Comment by BenCodez** [comment]
VoteSites.yml?

**Comment by Chronic-Reflexes** [comment]
trying that now

**Comment by Chronic-Reflexes** [comment]
works
note though, creating rewards ingame wont make it work off the bat

**Comment by BenCodez** [comment]
Well, you can't expect a complete ingame solution now can you? :)
