### ISSUE TITLE
Not an issue, more just a support question. 

### ISSUE THREAD

**Issue by JoshJJones** [BenCodez/VotingPlugin#605]
Hi, this plugin works flawlessly on my server, all votesites are automatic and its very simple to set up.

I just have a quick request, is there a way to give a group a permission which enabled their rewards to be applied twice? Like not for it two count two votes for the person since it would break top voters and stuff, but for it to simply give the reward twice.

Great plugin by the way.

**Comment by BenCodez** [comment]
You can have it apply a different reward based on permission with AdvancedPriority, which should work.

**Comment by JoshJJones** [comment]
Is there a setup for this somewhere? thanks for the insanely quick response time by the way.

**Comment by BenCodez** [comment]
Just within the rewards, look at the exampleadvanced reward for a little example.

**Comment by JoshJJones** [comment]
Thanks, I'll take a little look.

Any chance we might see a votefly module included in this at some point? or is that not something you're looking to add (eg - allowing a user to get 5m of 'votefly' per vote). Could be handy for some servers.

**Comment by BenCodez** [comment]
Already possible with using 2 rewards, one to give fly and one to disable fly (with a delay)

**Comment by JoshJJones** [comment]
Ok thank you, Great support :)

I'll close now :)
