### ISSUE TITLE
Not an issue - Support Question

### ISSUE THREAD

**Issue by JoshJJones** [BenCodez/VotingPlugin#606]
Ok I'm sorry to create a question like this twice in one day.

In the last 'issue' I asked about double rewards, I found the exampleAdvanced config, can I just edit my rewards into that with a 100% chance and give the permission? That will run it each time off each voting site as long as they have the permission?

right now I have all rewards given via the VoteSites config, will it interfere with that or just give the reward I set in exampleAdvanced too? (as long as they have the permission)

**Comment by BenCodez** [comment]
You don't need to have a chance (which makes it 100%) You can have it all in votesites.yml if you want.

**Comment by JoshJJones** [comment]
How can I add the permission based reward to votesites.yml?

  Minecraft-Server_net:
    Enabled: true
    ServiceSite: Minecraft-Server.net
    VoteURL: https://minecraft-server.net/vote/-----/
    VoteDelay: 24
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - eco give %player% 25000
      - crate give to %player% Vote 1

That's an example of a site I have right now.


Chance: 100
Random:
  Chance: 100
  PickRandom: false
  Rewards:
    Commands:
    - eco give %player% 25000
    - crate give to %player% Vote 1
  FallBack: [] 
RequirePermission: true
Permission: 'AdvancedCore.Reward.DonorDouble'

That's the part of the DonorDouble YML which is enabled.


How can I combine the two?
It seems you have quite the impressive plugin here, lots of options and mixing which would usually break other plugins :)

I removed my ACTUAL link just to avoid advertising btw 👍

**Comment by BenCodez** [comment]
Site2:
      Enabled: false
      Name: 'Site2'
      ServiceSite: 'PlanetMinecraft.com'
      VoteURL: 'link to vote URL here, used in /vote'
      VoteDelay: 24
      Item:
        Material: 'DIAMOND'
        Amount: 1
      Rewards:
        AdvancedPriority:
          # Similar to priority, but no need to have to use reward files
          # Add requirements under each reward
          # Will go in order from list here and try to run each of the following rewards...
          # This name can be anything, but they need to be different
          Reward1:
            RequirePermission: true
            Permission: 'perm'
            # Any other requirement here
            # If any requirement fails, the next will be attempted
            Messages:
              Player: 'You got first reward'
          Fallback:
            Messages:
              Player: 'You got unlucky'

Basic idea

**Comment by JoshJJones** [comment]
So I would put the AdvancedPriority sections under 
```
Rewards:
  Commands:
  - eco give %player% 25000
  - crate give to %player% Vote 1
  AdvancedPriority:
  EverythingRelatingTo:
  - The double permission
  - Here?
```

Just as an example :)

**Comment by BenCodez** [comment]
Sort of, would do it the way I had it, the fallback is given to those who don't have the permission.

**Comment by JoshJJones** [comment]
Will it still give both though? the fallback and the permission reward?

to clarify, all the double reward will do is repeat the normal reward when a user votes. (as long as they have the perm)

Thanks again, ultra quick.

**Comment by BenCodez** [comment]
You can double the rewards in the permission reward.

**Comment by JoshJJones** [comment]
Oh true, duh I didn't think about that :) 
Thanks, I love the 'one lucky command' thing too, will 100% add that soon to give random rewards.

Great work man, I'll close again :) I should be able to figure it out.
