### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by willc5** [BenCodez/VotingPlugin#609]
I have VotingPlugin installed on my bungee, hub, main server, & my second server. The votes seem to be working on the main server however they don't sync on the second server when testing the votifier through hub/main server. I setup everything correctly I believe

**Comment by BenCodez** [comment]
Forward the votes? Unless you only want one server to get the reward?

**Comment by willc5** [comment]
How do I do that?

**Comment by BenCodez** [comment]
Use nuvotifier or another plugin.
