### ISSUE TITLE
I cant add an 2cnd3th and 4th vote link 

### ISSUE THREAD

**Issue by Itunesboyy** [BenCodez/VotingPlugin#610]
i dont know how but i cant add an 2cnd link to the vote links how do i do this and why doesnt it work for me this is how my votelinks config looks like full: https://paste.helpch.at/

**Comment by BenCodez** [comment]
There is no config.

Is it formatted correctly?

**Comment by Itunesboyy** [comment]
https://paste.helpch.at/zavuvigimo.bash sorry! this one is it

**Comment by BenCodez** [comment]
AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 85
      - 'customcrates gk %player% Vote 1'
      - 'eco give %player% 2000'
          Messages:
            Player: 'You voted and got your reward!'
        Reward2:
          Chance: 100
      - 'customcrates gk %player% Legendary 1'
      - 'eco give %player% 8000'
          Messages:
            Player: 'You are lucky and won an legendary key!'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

I have no idea what happened here, but yml doesn't like how this is. You need to list the commands under Commands under each section of advanced priority.

**Comment by Itunesboyy** [comment]
i copy paste that one from one of ur configs
so when i copy rewards of first site and paste everywhere will work?

**Comment by BenCodez** [comment]
You can't really copy/paste yml files, since some formatting gets messed up, but yeah.

**Comment by Itunesboyy** [comment]
oke i gonna try cahgne all of them when wont work make new link with the one i have oke!

**Comment by Itunesboyy** [comment]
IT worked finaly!!!
thanks buddyy!
