### ISSUE TITLE
Adding custom tags to the material

### ISSUE THREAD

**Issue by Brzam** [BenCodez/VotingPlugin#616]
Hey, feature request/question if it already exists. I'm trying to add it so that in my /voteshop the spawners for each mob I'm selling will appear as that mob's head using the {SkullOwner:MHF_Sheep} etc, but it doesn't appear to be a valid material :(

Thanks in advance! :)

**Comment by BenCodez** [comment]
Just add Skull: Name under the material

**Comment by Brzam** [comment]
Amazing, thank you!
