### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#618]
Sometimes, a player gets double thank you for voting message.

What happens:
Vote site 1 give 1 point
Thank you for voting on vote site 1
Vote site 2 give 1 point
Thank you for voting on vote site 2
...(so far so good)...
...(after a while)...
Thank you for voting on vote site 1
Thank you for voting on vote site 1

**Comment by BenCodez** [comment]
VoteSites.yml?

**Comment by x1p** [comment]
https://hastebin.com/sijoleyuja.rb

**Comment by BenCodez** [comment]
Turn debug and extra debug on and send the logs when you get the double
message

**Comment by x1p** [comment]
This is the debug output at the time of such a message appearing. User already got both votes received 7 minutes before this.
https://hastebin.com/ejovoyuvon.md

FYI: player only receives "points" which go directly in the database. So no items/commands/random stuff.

**Comment by BenCodez** [comment]
Set clearcache on update to true?

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This better as well?

**Comment by x1p** [comment]
> Set clearcache on update to true?
```
# Clear cache on update, setting to true reduces update speed
ClearCacheOnUpdate: true

# Clear mysql on player join always
ClearCacheOnJoin: true

# Clears cache for the player who voted only
# Only effects if using mysql
# Would recommend for some bungee setups
ClearCacheOnVote: true
```
I will try new build

**Comment by x1p** [comment]
Unfortunately that didn't solve it.

**Comment by BenCodez** [comment]
Try it again with a later build, if not send the log from the first message
with debug

**Comment by x1p** [comment]
I will send logs as soon as I have more info

**Comment by x1p** [comment]
https://pastebin.com/UnJeGNgE

The result the player sees:
`Rewards.Messages.Player message` (=thanks for voting on site 1)
`Rewards.Messages.Player message` (=thanks for voting on site 2)
`Rewards.Messages.Player message` (=thanks for voting on site 1)

I miss the broadcast:
`Format.BroadcastMsg` (=Player player_name has voted)
From the log I understand that it skipped this, because the player is in vanish.
```
  # Broadcast only when player is online
  BroadcastWhenOnline: false
```
I assumed this meant that the vote is broadcasted the moment the server has received whether the player is online or not.

BTW: I had hoped this would prevent debug messages from appearing on the console:
```
# Debug info ingame
# Players with permission "VotingPlugin.Debug"
# will see debug info if debug is true
DebugInGame: false

# Will log debug messages to VotingPlugin/Log/log.txt
# Requires Debug to be on
# Only needed for extreme cases
LogDebugToFile: true
```
It does log this in the `Log.txt` file, but spams the console too.

**Comment by BenCodez** [comment]
Your correct about the broadcast. I prefer to use debug with console log, makes it easier to see what's going on. 

How does the server get the votes? Is it forwarded?

**Comment by x1p** [comment]
Personally I would prefer log but everyone has his preferences.

Votes are forwarded by nuvotifier (only) to the server the player is on (or saves the vote for later in its cache). VotingPlugin listens to the locally nuvotifier and should broadcast the vote. All received points should go into the central database.

So the path looks something like this
```
Bungee               Hub            Server
nuvotifier   ->   nuvotifier   ->   nuvotifier
                         |                |
                   VotingPlugin ->   VotingPlugin
                   Broadcast          Broadcast
```
The reason for this distributed setup is that I want every server to broadcast that someone has voted. That is not possible when only the hub has VotingPlugin.

**Comment by BenCodez** [comment]
Are the servers hooked to the same database? If so, that would be the problem.

**Comment by x1p** [comment]
Yes all connect to the same central database. Players can spend vote points wherever they like.

The funny thing is: it worked so far fine

**Comment by BenCodez** [comment]
Then you need to forward the votes to the hub server (with that set to process rewards false) and change all the cache options. 

You could some plugin to broadcast on all servers (there is plugins that do that)

That would be your problem. On restart it repulls from the database, otherwise causing that issue,

**Comment by x1p** [comment]
That could be a solution but that has a few disadvantages.
- no voting shop on servers
- the need for another plugin to broadcast the vote
- lack of vote points commands
- lack of vote points placeholder (this breaks my scoreboard)

I think the problem is purely the fact that this player is in vanish.

**Comment by BenCodez** [comment]
VotingPlugin would still be on each server

It's just the need for another plugin to broadcast, you could do it from bungee.

I mean, if it works it works, but the way I said is the way I would recommend.

**Comment by x1p** [comment]
I'll have to rethink the whole proces. For now I think I can disable the reward message, it's pretty useless anyway in my case.

What is the effect of `ProcessRewards: false`?
Would it still add a point to the database? (`PointsOnVote: 1`)
Will it still broadcast?  (`BroadcastMsg`)

Nevertheless, when:
```
  # Broadcast only when player is online
  BroadcastWhenOnline: false
```
If false it shouldn't matter whether the player is in vanish or not, it should always broadcast imho.
If true it should check if the player is vanished. Because vanished is similar to not online.

**Comment by BenCodez** [comment]
Process rewards prevents any rewards running, still gives points.

Broadcasts don't run if the player is in vanish, I could make it do nothing
if in vanish if that would help

**Comment by x1p** [comment]
I'm rethinking and testing your recommendation. Your recommendation sounds nice.
Nuvotifier can setup in proxy mode or pluginmessaging. Proxy relies completely on the hub to be always online or else the vote will be lost. Pluginmessaging has the advantage of caching the vote. However it won't give the vote when no one is online in the hub. Despite being `BroadcastWhenOnline: false`

I wish that the hub would process the vote immediately regardless of anyone in the Hub.
I noticed now that at least 1 player must be in the Hub otherwise nothing seems to be processed/broadcast/executed.
Then I can try to configure VotingPlugin to execute a (bungee) broadcast command. Although I can't imaging any bukkit plugin accepting a command to execute on the bungee. And VotingPlugin can't execute a bungee command I suppose.

If only VotingPlugin could run on the bungee itself... wishfull thinking.

**Comment by BenCodez** [comment]
Plugin messaging requires a player on the hub, there is no way around that other than using proxy mode.

Proxy mode would process the reward immediately. 

I eventually plan on having VotingPlugin on bungee, which would help a lot.

**Comment by x1p** [comment]
That would be awsome
