### ISSUE TITLE
Request: /vote list

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#619]
When users /vote it pops the GUI up and they have to click the first icon to list all vote sites, can we also get /vote list or /vote all or /votelist or /voteall or something to quickly list all vote websites without going through the GUI, I like the GUI its nice to do one by one, but some people want a quicker way to see them all!
Thanks.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Added, untested. Added both /vote list and /vote all. /voteall and /votelist won't work right now.
