### ISSUE TITLE
Vote Sound

### ISSUE THREAD

**Issue by seema84** [BenCodez/VotingPlugin#62]
i think a option to enable/disable with a vote confirmation sound it would be nice :-)

**Comment by BenCodez** [comment]
Sure, I'll try and get it in for the next version.

**Comment by seema84** [comment]
thanks :dancer:

**Comment by BenCodez** [comment]
I have a lot planned already, you can see the plan [here](https://github.com/Ben12345rocks/VotingPlugin/wiki/Future-versions)

**Comment by seema84** [comment]
yes i know can i find you in irc? than i dont need create for every question a issue

**Comment by BenCodez** [comment]
I don't use irc. You can also always message me on spigot too, instead of on here if you like, either is fine.

**Comment by seema84** [comment]
please add a timeformat translation .. but ... i think its not so easy
edit without names its enough i think 

but the default time 01.01.1970 01:00 is confused :-)

**Comment by BenCodez** [comment]
Take a look at this: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html, and look at the examples
You can change the time/date format using Format.yml

**Comment by BenCodez** [comment]
Also, I'm guessing the vote sound would be the same across everything? Or shall I do it per votesite

**Comment by seema84** [comment]
per votesite its the best

**Comment by BenCodez** [comment]
Yeah, found a problem with doing it that way, vote on 3 sites and log in.. don't want to play every sound at once or one by one.

I think I will do one sound for all the sites, just to make this simple.

**Comment by seema84** [comment]
i think if a player not log in you need only one sound and one message "you get 3x rewards" (for 3 votesites)
but if a player online its better to hear 3 sounds .. some player do not vote n all votesites

**Comment by BenCodez** [comment]
Already made it do that, just need to test it later
