### ISSUE TITLE
rewards

### ISSUE THREAD

**Issue by yoshiverde04** [BenCodez/VotingPlugin#620]
sometime players dont recive the reward, everything set well

# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  Site1:
    Enabled: true
    Name: Minecraft-Server-List
    ServiceSite: MCSL
    VoteURL: https://minecraft-server-list.com/server/445643/vote/
    VoteDelay: 8
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      AdvancedPriority:
        Reward1:
          Chance: 65
          Commands:
          - cc give physical common 1 %player%
        Reward2:
          Chance: 30
          Commands:
          - cc give physical rare 1 %player%
        Reward3:
          Chance: 5
          Commands:
          - cc give physical epic 1 %player%
      Messages:
        Player: '&aYou successfully voted the server!'
  Site2:
    Enabled: true
    Name: minecraft-server
    ServiceSite: minecraft-server.net
    VoteURL: https://minecraft-server.net/vote/yoshi_verde04/
    VoteDelay: 24
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      AdvancedPriority:
        Reward1:
          Chance: 65
          Commands:
          - cc give physical common 1 %player%
        Reward2:
          Chance: 30
          Commands:
          - cc give physical rare 1 %player%
        Reward3:
          Chance: 5
          Commands:
          - cc give physical epic 1 %player%
      Messages:
        Player: '&aYou successfully voted the server!'
  Site3:
    Enabled: true
    Name: minecraft-mp
    ServiceSite: minecraft-mp.com
    VoteURL: https://minecraft-mp.com/server/232986/vote/
    VoteDelay: 12
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      AdvancedPriority:
        Reward1:
          Chance: 65
          Commands:
          - cc give physical common 1 %player%
        Reward2:
          Chance: 30
          Commands:
          - cc give physical rare 1 %player%
        Reward3:
          Chance: 5
          Commands:
          - cc give physical epic 1 %player%
      Messages:
        Player: '&aYou successfully voted the server!'
  Site4:
    Enabled: true
    Name: PlanetMinecraft
    ServiceSite: planetminecraft.com
    VoteURL: https://www.planetminecraft.com/server/foxcraft-4392093/vote/
    VoteDelay: 24
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      AdvancedPriority:
        Reward1:
          Chance: 65
          Commands:
          - cc give physical common 1 %player%
        Reward2:
          Chance: 30
          Commands:
          - cc give physical rare 1 %player%
        Reward3:
          Chance: 5
          Commands:
          - cc give physical epic 1 %player%
      Messages:
        Player: '&aYou successfully voted the server!'
EverySiteReward: []

**Comment by BenCodez** [comment]
1. Can't read that, pastebin it.
2. Only the stuff under Reward is executed, so a 65% chance to run that command, meaning exactly what you experience.

**Comment by yoshiverde04** [comment]
ooooh i understood
