### ISSUE TITLE
/av convertfrom VoteRoulette does noting.

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#622]
Running Paper 1.12.2, Using 5.13.6 as suggested on your page.
Following
https://github.com/Ben12345rocks/VotingPlugin/wiki/Converting-from-another-plugin

Using your version of VoteRoulette linked on that page, I have 667mb of VoteRoulette data, such a waste to not import it.

VR running, VP running, Vault Running, when I run `av convertfrom VoteRoulette` nothing happens, no conformation that I've run the command, nothing.

Your Vote Plugin has been setup with MySQL, I can see the table it created.

Does it rely on the world all users are using? Im trying to do this offline on a test server as I have so much data to convert, my VoteRoulette users folder has 108,873 users in it.

**Comment by BenCodez** [comment]
Don't support that version, not much I can do

**Comment by TomLewis** [comment]
What was the last version that had working import from VoteRoulette? maybe I can use an old version and import the data then move to a newer build.

**Comment by BenCodez** [comment]
Don't even know if it works

**Comment by TomLewis** [comment]
Are you teh developer?

**Comment by BenCodez** [comment]
I am.

**Comment by TomLewis** [comment]
Do you have an example mysql database full of votes so I can try and write a script myself to do this

**Comment by BenCodez** [comment]
Just create one using the plugin.

**Comment by TomLewis** [comment]
That dousnt give me how 100s of users voting looks like in your schema, and it can't to public yet so it's limited to local use to setup.

**Comment by BenCodez** [comment]
I don't have an easy copy offhand, but you can force the plugin to add users to it. Just do fake votes.

Each user is the same.

**Comment by TomLewis** [comment]
How do you do fake votes? And force users to it?

**Comment by BenCodez** [comment]
/av vote (player) (site)

May need to set allow unjoined to true
