### ISSUE TITLE
Troubles getting rewards to work

### ISSUE THREAD

**Issue by ravensniper72** [BenCodez/VotingPlugin#624]
Currently I can't get rewards through files to work. I am trying to make reward with a custom name and lore. Help please.

**Comment by BenCodez** [comment]
What do you have?

**Comment by ravensniper72** [comment]
Please elaborate on the question.

**Comment by BenCodez** [comment]
What rewards do you have set?

**Comment by ravensniper72** [comment]
Anytime i try to set one in the sites yml it errors and doesnt work. I made a reward file for a iron nugget with a name and lore. Thats all

**Comment by BenCodez** [comment]
Pastebin what you have and I can add/fix up an example for you.

**Comment by ravensniper72** [comment]
Sites
https://pastebin.com/5htjQaY2

reward
https://pastebin.com/3WftVTsA

**Comment by BenCodez** [comment]
YML can't do that. 

https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

Remove the message stuff and it should work.

**Comment by ravensniper72** [comment]
What part is the message stuff?

**Comment by BenCodez** [comment]
Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

All of that.

**Comment by ravensniper72** [comment]
Ok ill give it a try and let you know if it works

**Comment by ravensniper72** [comment]
It works perfectly now. Thankyou very much.
