### ISSUE TITLE
I need help configuring votesites.yml

### ISSUE THREAD

**Issue by techdean** [BenCodez/VotingPlugin#625]
Here is the pastebin for my current votesites.yml I get the thank you for voting but no rewards.

https://pastebin.com/6fcJvM3X

**Comment by BenCodez** [comment]
https://pastebin.com/NPg5KGJq

That work?

**Comment by techdean** [comment]
trying it now

**Comment by techdean** [comment]
Nope getting error in votesites.yml that it's not configured properly the one i pasted doesn't give me any errors I just don't get any vote rewards.

**Comment by BenCodez** [comment]
What error?

**Comment by techdean** [comment]
votingplugin: detected yml error, please check console for details

**Comment by techdean** [comment]
detected no voting sites, this may mean something is't properly setup. I am using notepad++

**Comment by BenCodez** [comment]
https://pastebin.com/h41N6Fme

Should work now

**Comment by techdean** [comment]
ok will give it a try

**Comment by techdean** [comment]
Nice it's working now thank you very much! really appreciate it!

**Comment by BenCodez** [comment]
No problem
