### ISSUE TITLE
Add placeholder for VoteShop item name and item amount

### ISSUE THREAD

**Issue by KeirLoire** [BenCodez/VotingPlugin#630]
Hello,

Can you add placeholders for item name (%name%) and item amount (%amount%) from vote shop instead of the %Identifier% which is a YAML Node in the next release?

Thank you.

**Comment by BenCodez** [comment]
You could just type it in? But I guess I could add that.

**Comment by KeirLoire** [comment]
Yes, but the YAML node doesn't support spaces.

**Comment by BenCodez** [comment]
I think it can.

**Comment by KeirLoire** [comment]
Okay, I'll try.

**Comment by BenCodez** [comment]
It's also alot of work to add this placeholder, so I might just hold off on it, unless you really have a need for it.

**Comment by KeirLoire** [comment]
Never mind, thanks a lot. 

I didn't know nodes from YAML can work like this. I always thought of it as a variable which is against naming conventions.
