### ISSUE TITLE
Problem with head display on topvoter signs

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#632]
If I have a set up like this
![2019-09-23_01 03 57](https://user-images.githubusercontent.com/29175884/65395638-10ec3e80-dd9e-11e9-9d1f-1ff89011585e.png)

and then make the first sign into a topvoter sign, this happens:
![2019-09-23_01 05 02](https://user-images.githubusercontent.com/29175884/65395657-39743880-dd9e-11e9-9a1a-b62576627c2e.png)

If I remove the sign and make a new one in the center all 3 heads become the head of the one sign. Adding a sign to the other heads doesnt fix it, as the other head overwrites that head.

**Comment by BenCodez** [comment]
You can't have it that close to each other.

**Comment by DrakePork** [comment]
So there's no fix for it to have it right next to eachother?

**Comment by BenCodez** [comment]
Not currently, might add a way for that to work though

**Comment by DrakePork** [comment]
Ah mkay, well I'll just put them as seperate for now.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Just click the sign and then the skull.

Not fully tested, but works when I tested it just now.
