### ISSUE TITLE
Not all TLDs are supported

### ISSUE THREAD

**Issue by unisteven** [BenCodez/VotingPlugin#633]
By using the /vote command not all urls are clickable.
All urls that end with .net, .org, .com etc will work and are clickable. However as soon as a domain with .games comes along it is not clickable.

Url that does not work: 
https://serverlist.games/vote/2230

If I send this url in the normal minecraft chat it will be clickable but when it gets returned from the /vote command it isn't.

**Comment by BenCodez** [comment]
That's weird, it should be the same as typing it in chat.

**Comment by unisteven** [comment]
Indeed, have you already tried reproducing the issue? I have seen this issue on multiple servers. And looking at the code I don't see anything out of place that might cause this.

**Comment by BenCodez** [comment]
When I type that in chat it doesn't work. I can force it to work with some code. I can add something to force it.

**Comment by BenCodez** [comment]
Set this as your vote url:

     VoteURL: '[Text="serverlist.games/vote/2230",url="https://serverlist.games/vote/2230"]'

It will force it to work.

**Comment by unisteven** [comment]
Is there a possibility to include this way to force it in code? so when a url has not https:// or http:// it will add it. and when it does contain it it will still force the url?

**Comment by BenCodez** [comment]
Use what I had and change the first text.

**Comment by unisteven** [comment]
Yes indeed this might fix it for me, but what about other unknowing servers? As this problem with this specific url has been found on many servers?

**Comment by BenCodez** [comment]
Well, that is a good solution for now.
