### ISSUE TITLE
/av reload deleted all user data

### ISSUE THREAD

**Issue by endoped** [BenCodez/VotingPlugin#634]
I realized that one of the serviceSites was incorrect in my config. So I corrected it and ran /av reload. It reset all of my user's data and votes, is that normal??

**Comment by BenCodez** [comment]
No, no user data just deletes.

**Comment by endoped** [comment]
Oh, sorry. I typed up a comment to this shortly after opening but I guess I never submitted it! Yeah, you can probably close this unless you wanted to dig in further. I looked in Users.db and all of the data was still there, so I reloaded the plugin again and everything looked fine.
