### ISSUE TITLE
Console being spammed every second [URGENT]

### ISSUE THREAD

**Issue by Castiella** [BenCodez/VotingPlugin#635]
https://pastebin.com/U1ggNu4M - snip of issue

latest log: https://pastebin.com/rF7vvMEk

**Comment by Castiella** [comment]
Furthermore, when i try to disable /vote top using the VotingPlugin.Commands.Vote.Top permission the players can still use the command. Why aren't the permission nodes working?

**Comment by BenCodez** [comment]
Disable the VotingPlugin.Player permission.

Someone else had these errors when using a certain paper spigot version, try updating the server.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This help?

**Comment by BenCodez** [comment]
Fixed in latest version
