### ISSUE TITLE
Cant figure out "You reached your vote threshold!"

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#636]
Using 5.13.6 on Paper 1.12.2 (You said you do not support this, I know) But I need you to explain why this is showing.
I'm still testing locally, you showed me how to send fake votes in #622 
When i do /vote the very first item is to list all vote websites.
For some reason, it says "You reached your vote threshold!" This is very confusing, as I have only voted on one of the vote sites using the fake vote you told me about.
I cannot see any setting for a threshold anywhere, or limits, Ive searched the code the wiki, the files for key words.

It makes sense that it makes the website you voted on a redstone block as you have voted on it, but its showing the "list all vote websites" button and saying its an "AlreadyVotedItem".

Why is this? surely this should only show once ALL vote websites have been voted on?

![2019-09-25_19 11 26](https://user-images.githubusercontent.com/144046/65628121-b84cb980-dfc8-11e9-98af-b9f3584b692e.png)

**Comment by BenCodez** [comment]
There is no such message in the plugin.

**Comment by TomLewis** [comment]
The section to show all sites **AllUrlsButton**, is showing the "AlreadyVotedItem" when a user has **NOT** voted on all the websites, Why is this, can I just disable this? 


  ```
# GUI for /vote url
  # And /vote if enabled in Config.yml
  VoteURL:
    # GUI Name
    Name: '&7&l&m--&8&l&m--&a&lVote Pirate!&8&l&m--&7&l&m--'
    BackButton: true
    SiteName: '&b&l%Name%'
    SeeURL: '&cClick to see URL'
    NextVote: '&cCan Vote In: %Info%'
    ViewAllUrlsButtonEnabled: true
    AllUrlsButton:
      AlreadyVotedItem:
        Material: 'REDSTONE_BLOCK'
        Data: 0 
        Amount: 1
        Name: '&cVote again tomorrow!'
        Lore:
        - '&fYou reached your vote threshold!'
        - '&fYou can vote again tomorrow!'
      CanVoteItem:
        Material: 'EMERALD_BLOCK'
        Data: 0
        Amount: 1
        Name: '&3&lList All Voting Sites'
        Lore:
        - '&fAll Vote websites will be shown in chat'
```

**Comment by BenCodez** [comment]
There is no message in the plugin saying "you reached your vote threshold"
in the default config. There is a vote delay for how long it says until you
can vote.

**Comment by TomLewis** [comment]
Doesn't matter, the config allows to customise the messages. that's not what i'm asking.

Let me try and explain this even more simple.

The button that you click to show all the vote links, is changing, you can see its change from the initial screenshot I posted.
It should not change.

I cannot make this any simpler for you to understand.
The AllUrlsButton setting has 2 options AlreadyVotedItem and CanVoteItem.

it changes from an emerald block to a red-stone block, when a user votes once, this is not right.

**Comment by BenCodez** [comment]
It's not something I can fix for that version, but I can change it for
newer versions.

**Comment by BenCodez** [comment]
Changed in newer version
