### ISSUE TITLE
Questions: How to give reward for voting on 3x vote websites & How do I set the rewards file?

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#637]
**Question 1: How do I set VotingPlugin to give reward for voting on X amount of vote websites**
Trying to still move from VoteRoulette where it has vote on X amount of vote websites before it triggers the reward, how do I do this with VotingPlugin? I can see that its got a chance, but not specifics 

**Question 2: Can you give me an example how I would tell a vote to trigger a vote file?**
I would assume in VoteSites.yml, you would need to put the name of the rewards file (without the .yml) under the rewards section, would I do it like this?
```
    Rewards:
      RewardFile
```

Second part, how would I use ```EverySiteReward: []``` in VoteSites.yml
Would I change it to:
```
EverySiteReward:
  RewardFile
```
to make every site run this 1 rewards file?

**Comment by BenCodez** [comment]
1. Use cummulative rewards
2. https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
