### ISSUE TITLE
Voting Plugin no class found error.

### ISSUE THREAD

**Issue by MassiveLag** [BenCodez/VotingPlugin#639]
Hi....
So like a hour ago it worked fine, but now after a restart the plugin gives this error:
https://paste.helpch.at/ocilihomob.shell

**Comment by BenCodez** [comment]
The plugin doesn't support 1.8

**Comment by MassiveLag** [comment]
Since when? I used legit this version like today and yesterday and the day before.

**Comment by BenCodez** [comment]
Read the plugin page. For like a year now. The plugin shouldn't even be able to load.

**Comment by MassiveLag** [comment]
https://paste.helpch.at/ugijidogoz.bash

Yea its soo weird, since your config looks different on the spigot page. but i updated the plugin today since it asked to update. the current config looks like this on my server.

**Comment by BenCodez** [comment]
Well, I don't support 1.12 or lower, nothing I can do.

**Comment by MassiveLag** [comment]
What version does support 1.8? Do you know that.

**Comment by BenCodez** [comment]
Read the plugin page.

**Comment by MassiveLag** [comment]
ok, but why dont support 1.8 anymore? Its still one of the most common versions on minecraft. and 1.13 + is one of the most disgusting / resource wasting versions on the mc community atm...

**Comment by BenCodez** [comment]
No, it's a waste of time, plus a very old version.

**Comment by MassiveLag** [comment]
"waste of time" - You really don't care about the customers, that's what i already can confirm. Making a plugin 1.8 - 1.14 compatiple is easy asf. Even i did.

**Comment by BenCodez** [comment]
Why should I support an old version? I don't get paid to make plugins.
