### ISSUE TITLE
uuids.yml

### ISSUE THREAD

**Issue by seema84** [BenCodez/VotingPlugin#64]
I use a Whitelist and why get this File all Player?
I can show Player with /vote top which not listed on my  Whitelist. Thats not good.

Please list only Player with min one Vote for this Server. thanks

**Comment by BenCodez** [comment]
Already done for next version

**Comment by seema84** [comment]
thanks

**Comment by seema84** [comment]
player now removed from toplist but not from uuid and data
i dont need all player in this data from player they never join my server
maybe its better to save uuid und data only from a player with votes

(the readd from help has hardcoded colors)

**Comment by BenCodez** [comment]
Just add colors over top, should work I think. If not I'll change that.
Its because players who join trigger the join event, I'll see what I can do

**Comment by seema84** [comment]
i can change the color thats ok  ...  its only a info for you (maybe fix in next versions)
