### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by tman2001hi** [BenCodez/VotingPlugin#640]
https://pastebin.com/ShPLhpD2

In the pastebin you can see my setup, the list below none of them work but they wont give the keys, it appears to be the last ones apart from planetminecraft, I dont know if i messed up the coding somewhere or what, but it wont give the crate keys which the command for them is whats in the command. everything appears to be lined up, and also although its not in the pastebin at the very bottom it will seem to glitch part of one of the codes and just stick it down at the bottom and seem like a big mess, If you could if i messed up somewhere make a copy paste with the code edited and fixed where it works I would really appreciate that I spent alot og time today setting it all up but appeared to have messed up
 MinectaftServerList
MinecraftServer.net
top-minecraft-servers
minecraftlist
TopMcServers
www_minecraft-servers-list_org

**Comment by tman2001hi** [comment]
For the ones not listed they DO give the keys

**Comment by BenCodez** [comment]
What does it say when you vote in console?

**Comment by tman2001hi** [comment]
It says they voted but it just dont reward them

**Comment by BenCodez** [comment]
Does it work with /av vote?

**Comment by tman2001hi** [comment]
How do i need to use admin vote?

**Comment by BenCodez** [comment]
Make a test vote?

/av vote (player) (site)

**Comment by tman2001hi** [comment]
It appears /av is broken as whatever I type it just says invalid argument

**Comment by BenCodez** [comment]
Startup log?

**Comment by tman2001hi** [comment]
One moment will restart

**Comment by tman2001hi** [comment]
[19:55:46] [Server thread/INFO]: [VotingPlugin] Enabling VotingPlugin v5.20.1
[19:55:46] [Server thread/INFO]: [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
[19:55:46] [Server thread/INFO]: [VotingPlugin] Enabled VotingPlugin 5.20.1
[19:55:46] [Server thread/WARN]: [VotingPlugin] No vote has been recieved from minecraft-servers-list.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[19:55:46] [Server thread/WARN]: [VotingPlugin] No vote has been recieved from top-minecraft-servers.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[19:55:46] [Server thread/WARN]: [VotingPlugin] No vote has been recieved from minecraftlist.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[19:55:46] [Server thread/WARN]: [VotingPlugin] No vote has been recieved from topminecraftservers.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

**Comment by tman2001hi** [comment]
which those are the ones that dont work it appears, so what did i do wrong?

**Comment by BenCodez** [comment]
Doesn't look like the server get's the vote. Check votifier.

**Comment by tman2001hi** [comment]
but it does get it, because when the players vote on it it says they voted on the website

**Comment by tman2001hi** [comment]
ingame

**Comment by BenCodez** [comment]
Is the service site correct? It say the service site in console at time of the vote.

**Comment by tman2001hi** [comment]
Will you look in the pastebin i sent, I put the correct service name I think

**Comment by BenCodez** [comment]
They can be whatever the website sets it to. You can use /av servicesites to see what service sites the plugin knows about currently.

**Comment by tman2001hi** [comment]
![2019-09-29_21 05 02](https://user-images.githubusercontent.com/55964308/65842934-e13cb980-e2fc-11e9-9a81-8a4c2c99611a.png)

**Comment by BenCodez** [comment]
You'll need to fix the service sites. Vote on the site, look in console for the service site, change it accordingly.

**Comment by tman2001hi** [comment]
okay will do

**Comment by tman2001hi** [comment]
29.09 20:16:34 [Server] Craft Scheduler Thread - 7/INFO [VotingPlugin] Current known service sites: minecraft-mp.com, minecraft-tracker.com, minecraftservers.org, minecraftservers.biz, topg.org, minecraft-servers-list.org, minecraft-server.net, top-minecraft-servers.com, minecraftlist.org, topminecraftservers.org, PlanetMinecraft.com, http://www.minecraft-servers-list.org

**Comment by tman2001hi** [comment]
so all of those are the CORRECT servicenames?

**Comment by BenCodez** [comment]
Should be.

**Comment by tman2001hi** [comment]
'http://www.minecraft-servers-list.org' by player 'Icy_glaze'!
29.09 20:16:34 [Server] Craft Scheduler Thread - 7/WARN [VotingPlugin] VoteSite with service site 'http://www.minecraft-servers-list.org' does not exist, attempting to generaterate...
29.09 20:16:34 [Server] Craft Scheduler Thread - 7/WARN [VotingPlugin] VoteSite http://www_minecraft-servers-list_org does not exist, creating one, set AutoCreateVoteSites to false to prevent this

**Comment by tman2001hi** [comment]
Should be as in they should be what i need to enter in as new service names or should be as in only if i entered correct names in config

**Comment by BenCodez** [comment]
It's generating a vote site with that service site, open the file and you'll see it there.
It's generating the site since no site has that service site.

**Comment by tman2001hi** [comment]
where would the newly generated site be

**Comment by BenCodez** [comment]
VoteSites.yml

**Comment by tman2001hi** [comment]
minecraft-servers-list.org

**Comment by tman2001hi** [comment]
which is the same thing that was in there before so nothign was updated

**Comment by BenCodez** [comment]
29.09 20:16:34 [Server] Craft Scheduler Thread - 7/WARN [VotingPlugin] VoteSite with service site 'http://www.minecraft-servers-list.org' does not exist, attempting to generaterate...

The service site is right there ^ 

'http://www.minecraft-servers-list.org'

You'll need to reopen the file to see the sites generated.

**Comment by tman2001hi** [comment]
http://www_minecraft-servers-list_org:
    Enabled: true
    ServiceSite: http://www.minecraft-servers-list.org
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  /Top Minecraft Servers:
    Enabled: true
    ServiceSite: /Top Minecraft Servers
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward: []

**Comment by tman2001hi** [comment]
It put this at the bottom of my config automatically why?? how do i get rid of it?? I erased it but it didnt do anything

**Comment by BenCodez** [comment]
You need to use the service site it has, that's why it generates in the
first place. Just copy it over

**Comment by tman2001hi** [comment]
can I just delete it?

**Comment by BenCodez** [comment]
You can, but the site will generate again if you don't use that service site
