### ISSUE TITLE
Could not pass event InventoryClickEvent to VotingPlugin v5.20.1

### ISSUE THREAD

**Issue by SgtChrisCross** [BenCodez/VotingPlugin#641]
![image](https://user-images.githubusercontent.com/53583350/65905637-36420380-e3c1-11e9-9ecd-dbdae00af707.png)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This better?

**Comment by SgtChrisCross** [comment]
I test it tomorrow .

**Comment by BenCodez** [comment]
Should be fixed in latest version, let me know if not.
