### ISSUE TITLE
AllSites choices causes players to make choices infinitely.

### ISSUE THREAD

**Issue by EMcKee10** [BenCodez/VotingPlugin#642]
[Reports.1570030291112.zip](https://github.com/Ben12345rocks/VotingPlugin/files/3681911/Reports.1570030291112.zip)
I have tried to set up the AllSites Rewards to allow users to get a choice of heads if they vote on all sites. problem i am having, is that:
1. When they do /vote choices they can click the UnClaimed choice and then they go to a menu, to which they can either click one item as many times as they want (given they dont click to fast) or it brings them back out to the previous menu, but then they can click the UnClaimed choice again, and be brought back to that inner menu, infinitely.
2. The above causes a error

Attached is the report. if i need to provide anything else for help please let me know

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

How's that?

**Comment by EMcKee10** [comment]
Do i need to change any configs up with that? im about to restart the server now to test it.

**Comment by BenCodez** [comment]
No, just restart with that.

**Comment by EMcKee10** [comment]
Yep that seemed to do the trick. 👍
