### ISSUE TITLE
Multiple rewards file for the same site.

### ISSUE THREAD

**Issue by EMcKee10** [BenCodez/VotingPlugin#643]
I'm not sure this is even technically possible the way i understand it and also my understanding of it might be flawed.

What i'm wanting is that each vote site has 2 possible rewards files, i want it to run through the first one and if it doesn't come back with a reward, then i want it to run through the second, which has rewards but also has a fallback message.

I've attached the votesites, and my two rewards files. 
According to the wiki you can do this
Rewards:
- 'RewardFile1'
- 'RewardFile2'

and from what i understand it will run through the first file and try and get a reward, and if it succeeds, it will not go through the second file. but i could be wrong about this. As far as i could find the wiki doesn't explicitly say this (to my knowledge that is)

From what i'm experiencing on the server, it contradicts my knowledge. Players vote on the sites seem to always be receiving rewards from the second file, and the fallback message of the first rewards file never gets triggered (and neither does the rewards).

also i am aware that from my above knowledge that if the fallback message in the first file was to be triggered then based on my thinking, the second file shouldn't even be triggered. I plan to remove this fallback message in the first file anyway.

Sorry if that is confusing. Please feel free to ask for a better explanation :)

[votesites.yml](https://pastebin.com/JLbB0ib1)
[luckyvote.yml](https://pastebin.com/HV5GcMVC)
[vote.yml](https://pastebin.com/vhqzBZ1g)

Side note, i wanted to make sure i got the debug file for you but i keep getting that its a invalid argument. 

this is what i typed:
av Config SetDebug true
[Thu, 3. Oct 2019 15:37:07 UTC INFO] No valid arguments, see /adminvote help!

**Comment by BenCodez** [comment]
You need to use AdvancedPriority. There is an example in the default votesites.yml on github here.
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L77

You could make a reward containing advanced priority and give that reward file on the vote.

The command change for debug (changed it in the latest version, forgot to update wiki)

    /av Config TempDebug : VotingPlugin.Commands.AdminVote.Config.Edit|VotingPlugin.Admin
    /av Config TempExtraDebug : VotingPlugin.Commands.AdminVote.Config.Edit|VotingPlugin.Admin

**Comment by EMcKee10** [comment]
Wouldnt that just try and give one reward file? 

If im incorrect, would this be what you mean by your message?
Something along this line, where if reward1 checks the reward file "votelucky" and no reward is given, then it would do the reward file "vote"
```
      AdvancedPriority:
        Reward1:
          - votelucky #all votes in this yml are really low chance.
        Fallback:
          - vote
```

If so then this is what i am looking for, as votelucky has the lucky vote chances. i want to make a set of rewards that are really low chance to get (1/35 to be exact) but if they fail, and they likely will, then i wanted it to just try and give the "vote.yml" rewards. Within there i use advanced priority already.

This morning i got on and saw you message but noticed that you had made a update and i had indeed updated the plugin to the newest versions but didn't check the update notes. if i had i would have seen that you did in fact change it. sorry about that.

**Comment by BenCodez** [comment]
You want to use the rewards files method of doing it then use priority, otherwise you can put it all here.

But it does do what you want. Goes through and gives the first reward it can.

**Comment by EMcKee10** [comment]
Im sorry Ben, im not sure i follow. the message i posted above is incorrect?

**Comment by BenCodez** [comment]
Priority: 
    - reward1
    - fallback

If you use reward files use that ^

AdvancedPriority avoids multiple files.

**Comment by EMcKee10** [comment]
ohhhh i see. so with this Priority: it would run the reward1 and either come back with a reward and be good, or it wouldnt and then run fallback.

Thank you :) super helpful. ill be sure to leave a good review.
