### ISSUE TITLE
Recieve Vote but no Voting Points

### ISSUE THREAD

**Issue by Dreandor** [BenCodez/VotingPlugin#644]
I'll receive a vote but I don't get Votepoints. Command to give points doesn't work at all.
![Screenshot_4](https://user-images.githubusercontent.com/6794796/66252724-10b94f00-e75f-11e9-8f92-4a6db12a45d8.png)

**Comment by BenCodez** [comment]
I think I'll need to see more info.

**Comment by Dreandor** [comment]
What informations do you need?

**Comment by BenCodez** [comment]
Startup log?

**Comment by Dreandor** [comment]
[latest.log](https://github.com/Ben12345rocks/VotingPlugin/files/3694727/latest.log)

**Comment by BenCodez** [comment]
What command are you using to give vote points?
/av user (player) setpoints/addpoints) (num)

Is the config set to give voints (there is an option PointsOnVote)

**Comment by Dreandor** [comment]
# ------------------------------------------------
# Advanced
# Most of these values can be left untouched for most setups
# ------------------------------------------------

# Number of points to give on vote
# Set to 0 to give no points
PointsOnVote: 1

AlwaysCloseInventory: false

# Set this to false to disable the plugin adding totals
# Not really recommended
AddTotals: true

It works

**Comment by BenCodez** [comment]
All good then?
