### ISSUE TITLE
Your Database schema has numbers saved as TEXT! This means you cannot sort them!

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#647]
Your database schema needs to change, you are storing numbers as "TEXT" in MySQL, all the columns where you are saving numbers, like AllTimeTotal, MonthTotal, WeeklyTotal, Points etc, Im creating an API to create my own web UI as the current ones are absolutely terrible and was confused why I couldn't do a basic SORT BY in SQL, I looked and all your schema is terrible! 

Try it yourself
`SELECT * FROM VotingPlugin_Users ORDER BY AllTimeTotal DESC`

Will not work, until you change it to INT (Integer as its a number you are sorting, not TEXT).

Does this mean you are not using proper SQL to sort your results in-game?

If I change all the schema to be INT where they should be, will this break anything in-game where you are updating/selecting/deleting from those rows? Depends if you are calling them as strings or not.

Im gutted as I wanted to make a better WEB UI API and ive been thrown off this early, I guess I will have to throw everything into an array and then sort the array as even if it is fixed I wont be able to use any updates on 1.12.2.

My MonthTotal is INT as I was testing.
![Screenshot 2019-10-09 at 13 06 59](https://user-images.githubusercontent.com/144046/66480072-b3423c80-ea95-11e9-9eee-16d70e38cf0a.png)

**Comment by BenCodez** [comment]
Change it to INT, it's suppose to change automatically, but guess using an older version might be the cause. Did you restart the server once since the columns were added?

**Comment by TomLewis** [comment]
Servers definitely rebooted quite a few times as this is a backup from Production.

If its an older version, will it break parts of the plugin if I manually update these columns to INT?

V5.13.6 (for 1.12.2 paper)

**Comment by BenCodez** [comment]
Should be fine, might need a restart though
