### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by EchoGravity** [BenCodez/VotingPlugin#651]
Hey could you please help me find the issue with my config?

https://pastebin.com/3dAtS0dU

**Comment by BenCodez** [comment]
Your spacing is wrong.

    VoteSites:
      Site1:
        # Site options
        Rewards:
          Commands:
          - command here

Hope you get the idea.

**Comment by EchoGravity** [comment]
wow thanks for the fast response

**Comment by EchoGravity** [comment]
wait what do you mean, what needs changing?

**Comment by BenCodez** [comment]
The spacing of rewards.

**Comment by EchoGravity** [comment]
so like this:

VoteSites:
  MinecraftServers:
    Enabled: true
    Name: MinecraftServers
    Priority: 5
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Rewards:
      Commands:
       Console:
       - crate give p vote 1 %player%
       - broadcast &cThank you %player% for voting for RapidzSurvvival! Vote for vote crate keys! [/vote]
      Messages:
        Player: You voted

**Comment by EchoGravity** [comment]
wait it messed it ip

**Comment by EchoGravity** [comment]
https://pastebin.com/uF5PHn33

**Comment by BenCodez** [comment]
That's better, but just list the commands under Commands, no need for Console.

**Comment by EchoGravity** [comment]
when i vote it doesn't broadcast or give anything

**Comment by BenCodez** [comment]
Config?

**Comment by EchoGravity** [comment]
https://drive.google.com/file/d/1jjed7O-Kxxg5zIwoDk_i51fPS3Yr63Uz/view?usp=sharing

**Comment by BenCodez** [comment]
Oh I meant votesites.yml (the one you you sent before but with fixes you just did)

**Comment by EchoGravity** [comment]
sure one sec

**Comment by EchoGravity** [comment]
https://drive.google.com/file/d/1B5sqmBcI_d9Ldi4OdjS7XiFeGT78m74-/view?usp=sharing

**Comment by BenCodez** [comment]
https://pastebin.com/dA6VBykT

Follow that format.

**Comment by EchoGravity** [comment]
What did i do wrong?

**Comment by BenCodez** [comment]
You spaced the commands wrong, which causes a yml error.

**Comment by EchoGravity** [comment]
ok so is this correct?

https://pastebin.com/WuhNSKA2

**Comment by BenCodez** [comment]
From what I see, looks good.

**Comment by EchoGravity** [comment]
i did use a yaml checker but i didnt know what i had to do to fix the errors.

**Comment by EchoGravity** [comment]
way to send test votes?

**Comment by EchoGravity** [comment]
https://imgur.com/a/yRCLag7

**Comment by BenCodez** [comment]
Is the server getting the vote?

**Comment by EchoGravity** [comment]
no broadcasts are going through no

**Comment by EchoGravity** [comment]
im typing /av vote echotest MinecraftserversBiz

**Comment by BenCodez** [comment]
Check votifier and console log.

**Comment by EchoGravity** [comment]
been reloading with PlugMan, would that cause anything?

**Comment by BenCodez** [comment]
Don't use plugman, it breaks plugins. /av reload.

**Comment by EchoGravity** [comment]
just did /av reload and its the same error, should i restart server?

**Comment by EchoRapidz** [comment]
should i give you my ftp so you can see?

**Comment by BenCodez** [comment]
Restart it. Send console log.

**Comment by EchoGravity** [comment]
ok

**Comment by EchoGravity** [comment]
Voting -- https://pastebin.com/DPvntc2W
Whole Console Boot -- https://pastebin.com/VqUiGX80

**Comment by BenCodez** [comment]
1. It's an issue with votifier. Try https://mctools.org/votifier-tester
2. Update the plugin.

**Comment by EchoGravity** [comment]
is hostname the server ip or the votifier ip

**Comment by BenCodez** [comment]
votifier.

**Comment by EchoGravity** [comment]
it worked using that webiste

**Comment by EchoGravity** [comment]
"you voted for your first tiem"
"thanks for voting on mctools.org"

thats what it printed out

**Comment by EchoGravity** [comment]
no other commands run, eg broadcast and key give

**Comment by BenCodez** [comment]
That first (unless you set that on the first reward) message is probably a different plugin
There is no reward set on the site, since you don't have one set.

**Comment by EchoGravity** [comment]
wdym no reward set on the site

**Comment by BenCodez** [comment]
I lost on what your asking. Is votifier setup on each voting site?

**Comment by EchoGravity** [comment]
yes

**Comment by BenCodez** [comment]
Vote on them? I can't help you step by step. Does voting work? /av vote work?

**Comment by EchoGravity** [comment]
I got /av to work

**Comment by BenCodez** [comment]
Vote on the site and look in console to see if you get the vote.
