### ISSUE TITLE
Url on one site is not clickable

### ISSUE THREAD

**Issue by bradstar1081** [BenCodez/VotingPlugin#652]
Its vote site 6

https://pastebin.com/RZRp8fXM

**Comment by BenCodez** [comment]
Set your voteurl to this:
[Text="https://serverlist.games/server/2269",url="https://serverlist.games/server/2269"]

**Comment by bradstar108** [comment]
Its still not working

**Comment by bradstar108** [comment]
Also Voting site 7 is creating another votingsite labled msl

**Comment by bradstar108** [comment]
MCSL

**Comment by BenCodez** [comment]
That means that voting site doesn't have the proper service site, you need to change it.

Wanna send your votesites.yml to how it is now?

**Comment by bradstar1081** [comment]
I changed the vote site to MCSL and its working fine. Still having an issue with vote site 6 tho. I temporally removed it until I can resolve it.

**Comment by BenCodez** [comment]
VoteURL: '[Text="&cClick me",url="URL HERE"]'

Did you do this?
