### ISSUE TITLE
InventoryClickEvent error

### ISSUE THREAD

**Issue by Buzzbugs** [BenCodez/VotingPlugin#654]
Hello, might anyone know the cause of this error which shows up very often in my server log?

16.10 19:41:04 [Server] ERROR Could not pass event InventoryClickEvent to VotingPlugin v5.20.2
16.10 19:41:04 [Server] INFO java.lang.NullPointerException: null

**Comment by BenCodez** [comment]
Try this build:
http://ben12345rocks.com/job/VotingPlugin/
