### ISSUE TITLE
so i use ultrapermissions for a permissons plugin and i give my self the perms to use voting plugin but i doesn't allow to use the commands and even when i try it when i am opped. also i need help adding another site 

### ISSUE THREAD

**Issue by Ramen1234** [BenCodez/VotingPlugin#657]
**Versions**
Plugin version and spigot version

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Context about the question/concern

**Comment by BenCodez** [comment]
Set this to true:
UseVaultPermissions: false

Just add the votesite? It will auto generate the votesite for you when you vote.

**Comment by Ramen1234** [comment]
where is that isevaultpermissions:false

**Comment by BenCodez** [comment]
Config.yml

**Comment by Ramen1234** [comment]
my players aren't getting their rewards am i doing something wrong heres the config for voting sites https://pastebin.com/jdkV69mn

**Comment by Ramen1234** [comment]
sorry to be such a bother

**Comment by BenCodez** [comment]
It's Console not console

**Comment by Ramen1234** [comment]
ok
