### ISSUE TITLE
.yml Files with Voting Site does not work

### ISSUE THREAD

**Issue by zoiden25** [BenCodez/VotingPlugin#658]
**Versions**
Spigot 1.14  VP 5.20.3

**Relevant information**
VoteSites:
  minecraft-serverlist_net:
    Enabled: true
    ServiceSite: minecraft-serverlist.net
    VoteURL: https://www.minecraft-serverlist.net/vote/52269
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
    - 'Title'
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Context**
Trying to implement Rewards with the created rewards title.yml but a reload the plugin it states that there is a error in the plugin

Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'string', line 3, column 5:
Enabled: true
^
expected , but found ''
in 'string', line 12, column 7:
Messages:
^

**Comment by BenCodez** [comment]
You can't list the reward with the messages after that.

https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
