### ISSUE TITLE
VoteShop Tutorial/Wiki Page?

### ISSUE THREAD

**Issue by Hqvox** [BenCodez/VotingPlugin#662]
I'm not finding anything anywhere in the plugin or relevant wiki pages that describes how to use the VoteShop.. Is there a resource somewhere I can use to help me set it up to make more than just items available (ex. commands)?

**Comment by BenCodez** [comment]
Rewards work the same as anywhere else in the plugin
https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

You just add more items under the shop to add more items to buy. The default config has a good example.
