### ISSUE TITLE
Full inventory claim system for plugins giving items

### ISSUE THREAD

**Issue by EMcKee10** [BenCodez/VotingPlugin#664]
**Is your feature request related to a problem? Please describe.**
There definitely could be a issue with it. When a player's inventory is full, the reward is not received. normally if your talking about the /give command or other minecraft related commands, you could use the reward API. However, if your talking about issuing a command to another plugin that gives players items (in my case, custom heads from Head DB) then the items are not actually given, despite the console saying it has. For example: I use head db because i want a chance of 1 head out of thousands of heads to be given to a player when they vote and i dont want to have to manually type every head choice, as there are way to many, nor a program to do it either. This all works perfectly by triggering the /headdb give command they have. however, if inventory is full, there isn't a way for that player to receive the reward they lost.

**Describe the solution you'd like**
this is just a suggestion on how to, but maybe a /vote claim, where a inventory GUI opens up with the rewards lost for that player when there inventory was full. that way, they can empty there inventory, do /vote claim, then get the item/command they lost. There could be a item representation for commands that were suppose to run when players inventory was full, or the actual item itself. there would need to be a check on if the inventory was full at the time of voting, but if full then place in claim inventory for that player. and if claim inventory GUI became full, then you could drop on the ground, or replace the items in a order.

If this is already a feature, i apologize. let me know what you think.

**Comment by BenCodez** [comment]
It does this already for items set in the rewards (as in dropping the items), but not from commands unless the command handles it.
