### ISSUE TITLE
Placeholders and Offline VoteParty Rewards

### ISSUE THREAD

**Issue by xFrann** [BenCodez/VotingPlugin#665]
**Versions**
Plugin version: 5.20.4 running on paper-187 (1.14.4)

**Describe the bug**
About the placeholders, the one listed on PlaceholdersAPI for the top votes works only for names and not amount of votes, also the placeholder i was given in the review section returns blank as well.

**To Reproduce**
No errors whatsoever in console.
**Expected behavior**
Second bug is about the VoteParty giving players who were offline rewards even if they voted or not by enabling the setting GiveAllPlayers: true.
I'd want to give rewards to all players (either they voted or not) but only when they are online, and i can't quite seem to understand how i would be able to do that as the FaQ or Wiki section doesn't help much.

**Screenshots/Configs**
VoteParty Configuration:
VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 5
  # Increase the amount of votes required on each vote party reached
  #IncreaseVotesRquired: 10
  # If true, players who did not vote to reach the votes required will 
  # recieve the reward
  GiveAllPlayers: true
  # If true, the vote count will reset each day
  ResetEachDay: false
  # Reset at the end of the month
  ResetMonthly: false
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 0
  # Broadcast when vote party reached
  Broadcast: '&cReached the vote party amount!'
  # List of commands to execute, these only execute once.
  # %player% does not work here
  Commands: []
  # Rewards to give per player
  Rewards: 
    Commands:
    - fly %player% add 5m

**Additional context**
![image](https://user-images.githubusercontent.com/54155911/68999524-dac4ca00-08c9-11ea-8609-8178675d6967.png)
this is the screenshot to the result of the placeholder given by the dev, the ones listed on the placeholderapi github page returns the name of the top player.
Help lmao thanks.

**Comment by BenCodez** [comment]
Add RewardType: ONLINE in the reward.

Look at /av placeholders and /av placeholders (player)
It lists every placeholder.

**Comment by xFrann** [comment]
Thanks about the rewardtype: online thing, worked like a charm, do the fakevotes count in the placeholders count for top?
The placeholders listed there for the top still giving me blanks.

**Comment by BenCodez** [comment]
I assume placeholders are working properly, as in any placeholder?

**Comment by xFrann** [comment]
Some of them do of course work, like they are giving a value in the chat either 0 or something else.
Those one return me blank even tho i have this in the TopVoter this month:
Monthly:
- '1: xFrann: 5'
Now neither the name nor the amount of votes are showing.
I also used papi parse me to try them, they are not giving me any value.

**Comment by xFrann** [comment]
Also for example this one %VotingPlugin_GlobalMonthTotal% returns me 0, i only used fakevotes, not real ones, that's why i am asking if they count for those placeholders.

**Comment by BenCodez** [comment]
Unless you disabled it, fakevotes should count. 

%VotingPlugin_Top_Month_Position% - Get user top voter position

That work?

**Comment by xFrann** [comment]
![image](https://user-images.githubusercontent.com/54155911/68999708-1c0aa900-08cd-11ea-956b-937a0b29162d.png)
  # Count votes from /av vote?
  CountFakeVotes: true

**Comment by BenCodez** [comment]
What does /av placeholders (player) show? (send me what it says)

**Comment by xFrann** [comment]
![image](https://user-images.githubusercontent.com/54155911/68999717-5411ec00-08cd-11ea-8e6b-0517dfcd7b3e.png)
![image](https://user-images.githubusercontent.com/54155911/68999718-570cdc80-08cd-11ea-9914-461687afcfed.png)
![image](https://user-images.githubusercontent.com/54155911/68999719-596f3680-08cd-11ea-956d-73303af6c34c.png)

**Comment by BenCodez** [comment]
Will look it later so I can test it.

**Comment by xFrann** [comment]
Alright, thank you very much.

**Comment by BenCodez** [comment]
This works for me:
/papi parse me %VotingPlugin_Top_MonthVotes_1%

Is top voter working correctly? /vote top?

**Comment by xFrann** [comment]
![image](https://user-images.githubusercontent.com/54155911/69006193-3cba1980-0934-11ea-8de6-a3b9c20225b1.png)
well not really

**Comment by BenCodez** [comment]
load top voters monthly enabled?

**Comment by xFrann** [comment]
Oh shoot that seems to be it, it was disabled for some reason, maybe i got a little to hasty on the configuration.
Sorry for the wasted time and thanks for the help.
