### ISSUE TITLE
[VotingPlugin] Failed to load Config.yml

### ISSUE THREAD

**Issue by Mortderas** [BenCodez/VotingPlugin#668]
**Versions**
Latest version

**Describe the bug**
I've added rewards for the cumulative votes in the config.yml now I get this error

ERROR pastebin
https://pastebin.com/5pfRdzTx

CONFIG pastebin
https://pastebin.com/mGyLQjNQ

**Comment by BenCodez** [comment]
You have yml errors, you need to fix those.

**Comment by Mortderas** [comment]
How do I do that?

**Comment by BenCodez** [comment]
Follow proper spacing I can't do much from my phone

**Comment by Mortderas** [comment]
Okay, will do my best and then come back with an resolvation. Going to work soon so it will take some time

**Comment by Mortderas** [comment]
The errors are fixed now, but I don't get the reward from voting on all sites. Is it correct how I configured the rewards?
https://pastebin.com/7aQfKw2T

**Comment by Mortderas** [comment]
First vote/ All sites/ Etc. don't work =/ may I see a premade config to make an idea on how it should look?

**Comment by Mortderas** [comment]
This is whit what I came up
# First vote rewards
FirstVote: 
  Messages:
  Enabled: true
  Player: '&aYou have voted for your first time!'
  Money: '1000'
  Item: bedrock
  Amount: 1
  Rewards:
  Commands:
  Console:
  - give %player% bedrock 1

**Comment by Mortderas** [comment]
This is with what I came up so it wont break
https://pastebin.com/R475Dk19
Still not giving the rewards

**Comment by BenCodez** [comment]
Rewards:
      Messages:
        Player: 'message here'
      Money: 1000
      Items:
        Item1:
          Material: STONE
          Amount: 1
      Commands:
      - command here

Something like that

**Comment by Mortderas** [comment]
I am updating it now. Do they have to be Enabled: true?

**Comment by Mortderas** [comment]
The layout works perfect but it doesn't pop any message or give any rewards

**Comment by BenCodez** [comment]
Send the config? You don't need enabled there.

**Comment by Mortderas** [comment]
One second please

**Comment by Mortderas** [comment]
https://pastebin.com/5UPVDQmb

**Comment by BenCodez** [comment]
https://pastebin.com/WuCmdDis

try that.

**Comment by Mortderas** [comment]
It works so good. Thank you! I've managed to make the 10 cumulative votes config, but it doesn't give me the reward as I've got 70+ votes in total

**Comment by Mortderas** [comment]
Also the all vote sites reward is doubled

**Comment by BenCodez** [comment]
Config?

**Comment by Mortderas** [comment]
https://pastebin.com/h309QsW2
Sorry for the late response. By the way, what's the difference between cumulated votes and milestones?

**Comment by BenCodez** [comment]
Milestones are a 1 time reward.

You have double rewards set every where. You could just remove the commands
