### ISSUE TITLE
Multiple sites  

### ISSUE THREAD

**Issue by shadowremnent** [BenCodez/VotingPlugin#669]
1.13

Hi just have a question, im trying to add another site, the youtube tutorial says to just copy and paste and rename etc. I've done all that but the next website is not showing up. There are no errors coming up? 

is this config right? what do i need to change?

VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  PlanetMinecraft:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'planetminecraft.com'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'PlanetMinecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://www.planetminecraft.com/server/the-spungy-experiment/vote/''

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
       Console:
       - 'GoldenCrates Givekey %player% mystery 1'
      # Send player a message
      Messages:
        Player: '&5Thankyou for voting for The Spungy Experiment, here is your Mystery Key'
  # Site 1 example
  Site1:
    Enabled: false
    Name: 'Site1'
    ServiceSite: 'PlanetMinecraft.com'
    VoteURL: 'link to vote URL here, used in /vote'
    VoteDelay: 24
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next will be attempted
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'You voted'
        
    VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  minecraftservers:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'minecraftservers.org'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 4
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'minecraftservers.org'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'https://minecraftservers.org/vote/569332'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
       Console:
       - 'GoldenCrates Givekey %player% roll 1'
      # Send player a message
      Messages:
        Player: '&5Thankyou for voting for The Spungy Experiment, here is your Mystery Key'
  # Site 2 example
  Site2:
    Enabled: false
    Name: 'Site2'
    ServiceSite: 'minecraftservers.org/vote/569332'
    VoteURL: 'link to vote URL here, used in /vote'
    VoteDelay: 24
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next will be attempted
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'You voted'
    
    
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by BenCodez** [comment]
VoteSites:
      Site1:
        # Site info here
      Site2:
        # Site info here
