### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by devonzimmi** [BenCodez/VotingPlugin#671]
**Versions**
Plugin version and spigot version.
VP 5.20.5
Spigot 1.14.4
**Describe the bug**
I'm trying to input my SQL database details but for some reason, it's telling me I have a syntax error. I find this highly unlikely as the namespace for every single other database works fine.
meerkat-< plugin >
Out of every single database I've set up, your plugin is the only one presenting this error:
https://i.imgur.com/1bcP6GC.png

**To Reproduce**
Set config like so:
MySQL:
  Host: 'noved.io'
  # Default port is 3306
  Port: 3306
  Database: 'meerkat-votingplugin'
  Username: 'root'
  Password: '######'

**Expected behavior**
Zero errors.

**Screenshots/Configs**
https://pastebin.com/7yzPN2gv

**Comment by BenCodez** [comment]
Don't think it likes the - in the database name, does it work without it?

**Comment by devonzimmi** [comment]
An error still pops up:
https://pastebin.com/DEwLa9F7

The database name changed to meerkatvotingplugin instead of meerkat-votingplugin

Also, I'd really like to keep my namespace the same for every plugin.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin

This help with the orginal name scheme?

**Comment by devonzimmi** [comment]
Sadly the error still persists:
https://pastebin.com/QcrvqQZQ

**Comment by BenCodez** [comment]
Maybe this works?
http://ben12345rocks.com/job/VotingPlugin/

I might need more details if it doesn't work.

**Comment by devonzimmi** [comment]
Sadly the error still persists:
https://pastebin.com/XzNtgSCb

Although the syntax error includes more of the database name. Maybe a typo in the code? 
MariaDB server version for the right syntax to use near **''meerkat-votingplugin'**' at line 1
meerkat-votingplugin is now encased in two sets of single quotes.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Try it without the - again. It said table didn't exist when you tried that. Try manually creating the table?

**Comment by devonzimmi** [comment]
same error, this time with the double set of single quotes:
https://pastebin.com/jNbmWvsj

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Try that, if not the latest spigot build should work.

**Comment by devonzimmi** [comment]
The problem still occurs:
https://pastebin.com/9cKZCrsr

**Comment by BenCodez** [comment]
You'll need to not use the - I guess, not sure why it doesn't work. Try what you had the second time from before.
