### ISSUE TITLE
Prevent cached votes from past months to carry onto the next.

### ISSUE THREAD

**Issue by markusew** [BenCodez/VotingPlugin#675]
Hello, on my server we take use of the monthly top voters function to reward the most dedicated voters. We also cache our votes in nuvotifier so that people are able to vote offline. 

This gives people the ability to vote while offline, stacking up multiple votes in the cache before logging on and making them trigger all at once. This mechanic allows them to abuse the monthly top system since they are able to vote before a new month starts, and have those votes carry with them, giving them an "impossible" amount of votes for that month, which is unfair to all the others.

Since votes are timestamped, I suggest that VotingPlugin adds a check to see if the timestamp matches the current month, else it should not towards the top monthly vote. (Same type of check for other time periods as well but I'm personally only interested in monthly)

**Comment by BenCodez** [comment]
Let VotingPlugin handle the offline rewards, the totals are added at time of vote. I also don't remember if the timestamps on votes actually work correctly.

**Comment by markusew** [comment]
But we're using a bungee setup with per server local voting plugin storage. So votifier wouldnt know which server to send it and just send to every server, right?

**Comment by BenCodez** [comment]
I guess that would be a problem. VotingPlugin has a way of doing that though, but requires mysql and shared storage.

https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by markusew** [comment]
Yea, I figured as much, and I assume there's no convenient way of merging databases into one right?

Also, if you use a shared storage, can you separate certain parts of the storage or would everything be accessible from all servers? (Vote points, vote streaks etc.)

**Comment by BenCodez** [comment]
Everything would be accessible from all servers. There is a way to convert the storage from sql to mysql (and vise versa) but not a way to merge them all.

I also made a fork of votifier myself, maybe I could add something like this to that.

Created an issue to remind me later.
https://github.com/Ben12345rocks/VotifierPlus/issues/3

**Comment by markusew** [comment]
Okay, thanks for the response. I will probably avoid switching over to a shared database cause its a minor annoyance so it's not worth it imo. 

I thought it would be possible to add the timestamp check to the plugin since nuvitifier seems to have accurate timetamps.

Anyways, thanks for all the help!
