### ISSUE TITLE
Option for setting TimeHourOffSet dropped? (old issue #543)

### ISSUE THREAD

**Issue by AnttiMK** [BenCodez/VotingPlugin#676]
Was the functionality for offsetting the vote delay hour dropped in some version of the plugin? Minecraft-mp.com resets their votes at 12:00pm EST, and I would like to offset our vote delay to their reset time. I found an old issue (#543) that supposedly fixed this, but couldn't find any documentation of it nor any functionality in the code either.

**Comment by BenCodez** [comment]
It's still there, just hidden from the config by default.

**Comment by AnttiMK** [comment]
Ah, got it. Any plans to add official documentation or support for per-server offsets?

**Comment by BenCodez** [comment]
Technically it's official, I just hid to keep people from getting confused.

**Comment by AnttiMK** [comment]
Gotcha. :D What about per-voting-service offsets? I've already got one toplist that uses a different offset >.<

**Comment by BenCodez** [comment]
Time is delt in a global way, so I don't know how to handle that.

**Comment by AnttiMK** [comment]
Hm, what do you mean by _"in a global way"_?

**Comment by BenCodez** [comment]
I have a event system to handle time changes, so it's not really easy to add a one site delay. Not to mention other problems that would need to be solved.
