### ISSUE TITLE
Reward help please!

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#677]
**Versions**
Paper 1.15

**Relevant information**
N/A

**Context**
Trying to set up a 25/25/25/25 chance of reward for two sites and later more.

Hello,

I am trying to set up a system when you vote on one site you have a 25% chance of getting an item, 25% another, 25% another and finally 25% another. This for the same set of items for two voting sites.

My items to give upon vote:
25% - 16 Cooked Beef
25% - 48 White Wool
25% - 6 Iron Ingot
25% - 5 XP Bottles
*Same list for both websites

I attached my VoteSites.yml file
[VoteSites.zip](https://github.com/Ben12345rocks/VotingPlugin/files/3976132/VoteSites.zip)
(.yml file inside .zip file)

Thank you :)

**Comment by BenCodez** [comment]
Use advancedpriority:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L79

**Comment by ghost** [comment]
Thanks for your response but that is what I am struggling with. Can you please give an example how can I do what I want and how to link it to the VoteSities.yml.

Thank you!

**Comment by BenCodez** [comment]
Rewards:
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 25
          # Any other requirement here
          # If any requirement fails, the next will be attempted
          Item:
            Material: 'COOKED_BEEF'
            Amount: 16
        Reward2:
          Chance: 25
          Item:
            Material: 'COOKED_BEEF'
            Amount: 16

Something like that, that's the idea.
