### ISSUE TITLE
In-Game Announcements Not Working!

### ISSUE THREAD

**Issue by chris23075** [BenCodez/VotingPlugin#678]
I downloaded both NuVotifier and VotingPlugin, and I set all the sites up correctly. On the server I able able to do /vote and go to the websites, but when voted on the websites no message appears in the server chat. I believe my Votifier is not connected correctly but I cant seem to find out whats causing it. When I do the test votes on test websites to see if it is connected to my server it shows a successful connection but no message appears in my console or anything like that, leading me to believe it is not connected correctly. I have done this before and this is the first time it is happening. Any help would be greatly appreciated!

**Comment by BenCodez** [comment]
Try a new port
