### ISSUE TITLE
Plugin crash when buying an expensive item from donation store

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#679]
**Versions**
Plugin Version: 5.20.5
Paper Version: 1.14.4  v237

**Describe the bug**
After a player bought an expensive voteshop item an error was thrown in console, and after doing /av reload the plugin crashed.

**To Reproduce**
1. Buy something expensive from voteshop I guess? Havn't had time to try and reproduce it myself due to it being late when I'm writing this.

**Expected behavior**
The voteshop works fine and processes the purchase without crashing the entire plugin.

**Screenshots/Configs**
[Pastebin](https://pastebin.com/FR7VXxwy)

**Comment by BenCodez** [comment]
Config?

**Comment by DrakePork** [comment]
https://pastebin.com/CweDHUyV

**Comment by BenCodez** [comment]
Change this TP Bypass to TP_Bypass

Don't think it likes the spaces. There is a few other spaces too.

**Comment by DrakePork** [comment]
Ah okay
