### ISSUE TITLE
Rewards not working

### ISSUE THREAD

**Issue by Aeyori** [BenCodez/VotingPlugin#680]
**Versions**
Plugin version and spigot version.
5.20.5 
Paper 1.15.1
**Describe the bug**
Rewards aren't giving the proper items I set but are instead giving me 1 diamond every time. 
**To Reproduce**
When voting on PlanetMinecraft, it gives me a diamond. When I try to use a vote test website, it still gives me diamond instead of what I put,
**Expected behavior**
It should be giving the item I listed under rewards, which is the Stal music disc with a rename and lore.
**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Configs?

**Comment by Aeyori** [comment]
https://pastebin.com/dYRrByDy

Pastebin is really slow rn or is it just me?

**Comment by BenCodez** [comment]
The rewards you set would be nice, can't help without seeing what you did.

**Comment by Aeyori** [comment]
Oh shoot, I can't believe I forgot to send the other pastebin of the actual rewards

EDIT: Here it is https://pastebin.com/78iMGLhq

**Comment by BenCodez** [comment]
Rewards:
      Items:
        Item1:
          Material: 'STONE'
          Amount: 1

Basic idea.

**Comment by Aeyori** [comment]
So after Items, I needed to have the Item1? I'll give that a try

**Comment by Aeyori** [comment]
So I gave that a try and it works now, I get the music disc but it's still giving me a diamond too though even though its not stated under rewards.

(Sorry for the late reply I was caught up in some other work)

**Comment by BenCodez** [comment]
Do you have CMI?

**Comment by Aeyori** [comment]
I do have CMI

**Comment by BenCodez** [comment]
Check your configs on that.

**Comment by Aeyori** [comment]
Yup, I didn't realize CMI also dealt with Votifier! That's cool but I'll be sticking to your plugin! Thank you for the help (:
