### ISSUE TITLE
Not recieving rewards.

### ISSUE THREAD

**Issue by XxRosiexX** [BenCodez/VotingPlugin#681]
**Versions**
Plugin: 5.20.5
PaperMC: 1.15.1

**Relevant information**
Vote Sites: https://pastebin.com/Zc1q4JrH
I want the plugin to completely disregard these files and reward directly from the vote sites config
Advanced: https://pastebin.com/svnBbgQR
Basic: https://pastebin.com/UrDgz31t

**Context**
Context about the question/concern
I want the plugin to completely disregard these files and reward directly from the vote sites config
However when voting players recieve none of the rewards from the VoteSites rewards area

**Comment by BenCodez** [comment]
You didn't send any files.

You can simply add rewards in votesites.yml like so:
https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

**Comment by XxRosiexX** [comment]
updated

**Comment by BenCodez** [comment]
Its Commands, not commands.

**Comment by XxRosiexX** [comment]
Its really caps senstive xD?

**Comment by BenCodez** [comment]
YML is cap sensitive :)

**Comment by XxRosiexX** [comment]
Aha
What's this error about o.o
28.12 15:48:10 [Server] INFO in 'string', line 12, column 1:
28.12 15:48:10 [Server] INFO DataStorage: SQLITE
28.12 15:48:10 [Server] INFO ^
28.12 15:48:10 [Server] INFO expected <block end>, but found '<block mapping start>'

**Comment by BenCodez** [comment]
You have a yml error

**Comment by XxRosiexX** [comment]
I know but it says line 12? There's nothing wrong with line 12

**Comment by BenCodez** [comment]
Config.yml?

**Comment by XxRosiexX** [comment]
sec ill give u it
https://pastebin.com/9VYff8dm

**Comment by BenCodez** [comment]
Try that
https://pastebin.com/JMzcDQGE

**Comment by XxRosiexX** [comment]
That worked, thanks a bunch!

**Comment by XxRosiexX** [comment]
Forgot to ask, can i add items to that? 
Items:
  Paper:
    Material: PAPER
    Data: 0
    Amount: 1
    Durability: 100
    Name: '&c&lVote Rewards'
    Lore:
    - '&d&lTo open crates do /cc'

inside of the vote sites config

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - command here
      Items:
        Paper:
          Material: PAPER
          Amount: 1
          Durability: 100
          Name: '&c&lVote Rewards'
          Lore:
          - '&d&lTo open crates do /cc'

Something like that.

**Comment by XxRosiexX** [comment]
Thanks!
