### ISSUE TITLE
Rewards not working properly

### ISSUE THREAD

**Issue by Aeyori** [BenCodez/VotingPlugin#682]
**Versions**
Plugin version and spigot version.
5.20.5, Paper 
**Describe the bug**
Not receiving a reward
**To Reproduce**
1. Vote for website while on server
2. Receive no reward

**Expected behavior**
A command is supposed to run that gives me a key.
**Screenshots/Configs**
**Additional context**
I tried it with - 'crates key %player% vote 1' as well but no avail

If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
```VoteSites:
  PlanetMinecraft:
    Enabled: true
    Name: '&aPlanet&bMinecraft'
    Priority: 5
    ServiceSite: PlanetMinecraft.com
    VoteURL: '[Text="Haroyuki - Click here!",url="https://www.planetminecraft.com/server/haroyuki-harmony-within-chaos-survival-rpg-server-classes-skills-dungeons-server-town-money/vote/"]'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Rewards:
      Commands:
        - crates key %player% vote 1

**Comment by BenCodez** [comment]
Have the commands list directly under Commands, space it back 2.
