### ISSUE TITLE
Voteshop Item Dupe

### ISSUE THREAD

**Issue by vkolasa** [BenCodez/VotingPlugin#685]
Summary: Shift clicking in the voteshop occasionally lets players take and keep the item used to represent the reward.

Using Version 5.20.5
on paper: git-paper-29 (MC: 1.15.1)

http://prntscr.com/qljtbf

**Comment by BenCodez** [comment]
Set AlwaysCloseInv to true. (Not sure if that's the exact name)

**Comment by vkolasa** [comment]
Is this in the config or something else, I searched the whole thing for any of those key words and nothing was found...

**Comment by BenCodez** [comment]
Check the default config on github for that option

**Comment by vkolasa** [comment]
Just did, just set it to true, player is still able to take the actual item from the voteshop and use it.

**Comment by BenCodez** [comment]
Does this happen in the latest spigot build?

**Comment by vkolasa** [comment]
unfortunately I cant test that as my host has me use preselected versions :|
when I enabled the alwayscloseinventory it DID make it harder to pull off.

**Comment by BenCodez** [comment]
You should be able to use any jar you want, if not you got a terrible host.

**Comment by vkolasa** [comment]
So I did manage to upload Paper-42 (most recent at this time) and run it, and the tester is still able to pull items out of the voteshop.

**Comment by BenCodez** [comment]
This help?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by vkolasa** [comment]
Player is still able to perform this glitch

**Comment by BenCodez** [comment]
I can't recreate right now, does it happen on a plain spigot build? (Non paper) And config?

**Comment by vkolasa** [comment]
Did this on the latest spigot build, same outcome.

**Comment by BenCodez** [comment]
Wanna send me your config?

**Comment by vkolasa** [comment]
https://pastebin.com/Zgp424Gp

**Comment by BenCodez** [comment]
I managed to take the item out, but only once and now can't recreate it again. 

http://ben12345rocks.com/job/VotingPlugin/

Does this help?

**Comment by vkolasa** [comment]
Still no luck :/

**Comment by BenCodez** [comment]
Yeah, I got no idea right now. I can't recreate it now.
