### ISSUE TITLE
VotingPlugin

### ISSUE THREAD

**Issue by Mapfelkuchen** [BenCodez/VotingPlugin#686]
Hello :)
I followed the instruction to install the plugin.
I can vote, but i dont recieve anything. but i should.

What am i Doing wrong? Can u help fixing ?

**Comment by BenCodez** [comment]
Is the server getting the vote? VoteSites.yml?

**Comment by Mapfelkuchen** [comment]
Hello, yes the server is getting the vote. But there is a problem with the
rewards.


Ben <notifications@github.com> schrieb am Fr. 10. Jan. 2020 um 22:53:

**Comment by BenCodez** [comment]
Wanna send them then?
