### ISSUE TITLE
You are my only hope

### ISSUE THREAD

**Issue by eatmychiz** [BenCodez/VotingPlugin#687]
**Versions**
VotingPlugin 5.20.5 and Spigot 1.15.1

I just have a a couple questions. I have my votesites.yml half completed. All my sites are set to false and the voteURL is not in existence yet so it's just set to the default. My console receives an error saying it cant load the votesites.yml file is this because all my information hasn't been fully entered yet and when I do this problem will be solved? Or do I have deeper problems awaiting me. Thank you for your time sorry for the silly question.

**Comment by BenCodez** [comment]
Sounds like a yml error. Votesites.yml?

**Comment by eatmychiz** [comment]
[message.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4059608/votesites.yml)

the only thing I receive as an error is when starting up the server my console says it cant load votesites.yml

**Comment by BenCodez** [comment]
https://pastebin.com/6ga3FpRp

Try that.

**Comment by eatmychiz** [comment]
You're the best fam so I guess I shouldn't have made the console: after the commands: I appreciate your help great plugin sorry for my stupidity haha!
