### ISSUE TITLE
multi line lore

### ISSUE THREAD

**Issue by Boastful1353** [BenCodez/VotingPlugin#688]
how does one add a second line of lore to a vote shop item?

    Lore:

    - '&c&lCost: &c1000 Voting Points, DO NOT PURCHASE MORE THAN ONCE'

i want a new line at the comma

**Comment by BenCodez** [comment]
Add another - '' under it.

**Comment by Boastful1353** [comment]
strange, i did try that and when i did that it didn't like it. The vote shop was emptied out when i reloaded it.

**Comment by BenCodez** [comment]
You probably made a yml error when doing that.

**Comment by Boastful1353** [comment]
thanks. i'll give it another go.
