### ISSUE TITLE
VotePoint data sometimes not loading when doing /av reload

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#689]
**Versions**
VotingPlugin 5.20.5
Paper v51

**Describe the bug**
Sometimes when I do /av reload the votepoint data doesnt load and everyone is on 0 points. If I do /av reload a few more times the issue fixes itself, however if someone gets any votepoints while their data isnt loaded in and then their data gets loaded in they dont have their points restored and are stuck at the new value they received.

**To Reproduce**
Doesnt happen each time but type /av reload then check how many votepoints you have with /vote points. If its now 0 but wasnt before it has happened.

**Expected behavior**
That votepoint data gets loaded every time you type /av reload.

**Comment by BenCodez** [comment]
What's in console when that happens? It will reconnnect to mysql on /av reload, probably because of that.

**Comment by DrakePork** [comment]
As far as I'm aware there doesn't seem to come up anything special in console when it happens.

**Comment by BenCodez** [comment]
Are you using sqlite or mysql?

**Comment by DrakePork** [comment]
Sqlite

**Comment by BenCodez** [comment]
Does the problem go away with mysql?

**Comment by DrakePork** [comment]
Would need to get that set up to test so idk

**Comment by BenCodez** [comment]
My guess is the server can't handle writing to the database on a reload (probably a lot going on to cause that), but unless I can recreate it, won't really be able to fix it.
