### ISSUE TITLE
Vote Reward Configuration

### ISSUE THREAD

**Issue by Phamous1** [BenCodez/VotingPlugin#690]
**Versions**
Plugin version and spigot version
Current Plugin Version, and PAPERMC 1.15.1 
**Relevant information**
Configs that relate to the issue in a pastebin.
https://pastebin.com/CjGjiJsc
https://pastebin.com/W6EaESua
https://pastebin.com/eFynRUgt
**Context**
Context about the question/concern
I am trying to configure for the rewards and i have read all the wiki and still dont quite understand.  I am attempting to set up a chance rewards from a few different rewards files and a single reward for first time vote on the server.  I cannot find any video or step by step on how this all works together.  And cant find a copy of an actual rewards file that works to go off of.  I know im missing something here but not sure where to start lol.

**Comment by BenCodez** [comment]
1. No / on commands.
2. It's Commands, not Command

List the rewards where needed
https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

**Comment by Phamous1** [comment]
Yes i did see and fix that last night while searching through it troubleshooting it.  Also it seems like the enchantments are broken.  So it will give me the armor, but i had to switch the color codes to the §5 format, then the enchantments still don't work.  Is there a way around this to or is it just broken

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleBasic.yml#L65

You need it like that.

**Comment by Phamous1** [comment]
Ok i got all that fixed but now its giving me an error in the config.yml.  I have played with a ton of different positioning and orders to try and get it to work like i had to with other yml files but nothing seems to be working.  

https://pastebin.com/KPmLYWvM
[consecutiverewards.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4096510/consecutiverewards.txt)

and error log
https://pastebin.com/LmFFFwWv
[errorfile.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4096527/errorfile.txt)

**Comment by BenCodez** [comment]
You can't start a quote with a ' and end with a " on those lines

**Comment by Phamous1** [comment]
i resolved that but still same error showing
[A8hgefyi.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4096938/A8hgefyi.txt)

[k1aXhjFy.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4096952/k1aXhjFy.txt)

**Comment by Phamous1** [comment]
It seems to not like the hyphen but everywhere else in the config it works fine.

**Comment by Phamous1** [comment]
Alright seems like i resolved it, moved some things around and was missing a space in between one of the hyphens
