### ISSUE TITLE
Internal Error message when using the command /vote

### ISSUE THREAD

**Issue by BboyZeroOne** [BenCodez/VotingPlugin#691]
**Versions**
5.20.6, Paper Spigot 1.13.2 and 1.14.4

**Describe the bug**
A "An internal error occurred while attempting to perform this command" message when using the command /vote/

**To Reproduce**
1. Type "/vote" in game.
2. Tadaa

**Expected behavior**
Vote GUI should pop up as usual.

**Screenshots/Configs**
No changes made to config, only update to latest version of the plugin.

**Additional context**
https://pastebin.com/adZEdsAn

**Comment by BenCodez** [comment]
Redownload the jar?

**Comment by BboyZeroOne** [comment]
Let me give it a try
