### ISSUE TITLE
Votes don't go through

### ISSUE THREAD

**Issue by RyzeR0it** [BenCodez/VotingPlugin#692]
This is on 1.14.4, it doesn't show people voted. I can do /vote, the list of vote sites come up, you can go to them and vote like normal, but you don't get any rewards, it doesn't show you voted on the server, or even in console, and you don't get any "vote points"  There's no errors or warnings shown up in console.

**Comment by BenCodez** [comment]
Then the server isn't getting the vote. Check votifier.

**Comment by RyzeR0it** [comment]
Hmm. i don't see a problem with votifier, unless I have to change the forwarding.

**Comment by BenCodez** [comment]
There will be a broadcast and message in console when a vote comes through, regardless if you set the plugin up correctly.

**Comment by RyzeR0it** [comment]
Yeah, i don't get anything in console, nor is there a broadcast.

**Comment by BenCodez** [comment]
Then check votifier.
