### ISSUE TITLE
Config Reload Issues

### ISSUE THREAD

**Issue by Shewolf1896** [BenCodez/VotingPlugin#693]
When trying to reload the config, its informing me there is yml issues. 

I succeeded in fixing the issues in VoteSights and ExampleBasic - the issues where my fault and I figured them out.

I can't figure out whats wrong with the config.yml, however, It says where the issues are, But I do not fully understand them.....

` ERROR Cannot load plugins/VotingPlugin/Config.yml
29.01 13:37:58 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
29.01 13:37:58 [Server] INFO in 'string', line 12, column 1:
29.01 13:37:58 [Server] INFO DataStorage: SQLITE
29.01 13:37:58 [Server] INFO ^
29.01 13:37:58 [Server] INFO expected <block end>, but found '<block mapping start>'
29.01 13:37:58 [Server] INFO in 'string', line 807, column 3:
29.01 13:37:58 [Server] Startup 3:
29.01 13:37:58 [Server] INFO ^
29.01 13:37:58 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.YML.YMLFile.reloadData(YMLFile.java:91) ~[?:?]
29.01 13:37:58 [Server] INFO at com.Ben12345rocks.VotingPlugin.Main.reload(Main.java:1074) ~[?:?]
29.01 13:37:58 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$14.execute(CommandLoader.java:468) ~[?:?]
29.01 13:37:58 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:382) ~[?:?]
29.01 13:37:58 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
29.01 13:37:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
29.01 13:37:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
29.01 13:37:58 [Server] INFO Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
29.01 13:37:58 [Server] INFO in 'string', line 12, column 1:
29.01 13:37:58 [Server] INFO DataStorage: SQLITE
29.01 13:37:58 [Server] INFO ^
29.01 13:37:58 [Server] INFO expected <block end>, but found '<block mapping start>'
29.01 13:37:58 [Server] INFO in 'string', line 807, column 3:
29.01 13:37:58 [Server] Startup 3:
29.01 13:37:58 [Server] INFO ^
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.15.2.jar:git-Paper-84]
29.01 13:37:58 [Server] INFO ... 13 more
29.01 13:37:58 [Server] ERROR [VotingPlugin] Failed to load Config.yml`

I have uploaded my config here too - I do edit it in Notepad++ But I was unable to upload it as that file. 
[Config.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4127980/Config.txt)

**Comment by BenCodez** [comment]
https://pastebin.com/nF9BuedG

Try that.
