### ISSUE TITLE
Question about custom GUI item in votegui ,custom command

### ISSUE THREAD

**Issue by rybuilder23** [BenCodez/VotingPlugin#694]
**Versions**
paper 88 
votingplugin version 5.20.5

**Relevant information**
<>

**Context**
Hi thanks for having time to anser my question 

my Question is how do i add a item with custom command like a back button for my custom deluxemenus menu.

i read in [https://github.com/Ben12345rocks/VotingPlugin/issues/502#issue-409087120(url)
that it is possable but how do you add it ?

like this?
but how do i add a command?
 
for example
Command:  'dm open mainservermenu  %playername%'

    Custombutton:
      Item:
        Material: 'ARROW'
        Data: 0
        Amount: 1
        Name: '&3back to main server menu
      Slot: 7

**Comment by BenCodez** [comment]
Custombutton:
      Item:
        Material: 'ARROW'
        Data: 0
        Amount: 1
        Name: '&3back to main server menu
        Lore:
        - lore here
      Command: 'command here'

**Comment by rybuilder23** [comment]
Thank you!
:)
