### ISSUE TITLE
What does issue with VoteSite entail - What needs to be changed to fix issue?

### ISSUE THREAD

**Issue by NightshineRecorralis** [BenCodez/VotingPlugin#696]
**Versions**
VotingPlugin 5.20.6, Paper 645 - MC 1.13.2

**Relevant information**
In console:
[VotingPlugin] Issue with VoteURL in site Craft-List

**Context**
Here's my VoteSites.yml for that link:
  Craft-List:
    Enabled: true
    Name: Craft-List
    ServiceSite: Craft-List.net
    VoteUrl: '&bhttps://craft-list.net/minecraft-server/HavanaMC/vote'
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
    - ExampleBasic
    Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

I have tried with and without formatting on the url, with and without the 'www', and http and https. What am I missing? debug mode sheds no light on what's causing the issue :/

**Comment by BenCodez** [comment]
From the default votesites.yml:

    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
