### ISSUE TITLE
Does this work with CatServer?

### ISSUE THREAD

**Issue by XxRosiexX** [BenCodez/VotingPlugin#697]
**Versions**
5.20.6, and 1.12.2

**Relevant information**
Not a config related issue. Thanks though <3

**Context**
08.02 23:31:34 [Server] Server thread/ERROR [VotingPlugin] Detected running git-CatServer-1.12.2-47463d5 (MC: 1.12.2), this version is not supported on this build, read the plugin page. Disabling...

CatServers link. https://github.com/Luohuayu/CatServer/releases

Info about CatServer. It allows spigot plugins on a forge server.

**Comment by BenCodez** [comment]
From the plugin page:

    Use v5.13.6 for 1.12 and older versions, support WILL NOT be provided for these versions, so 
    please don't ask for support for these versions.

**Comment by XxRosiexX** [comment]
Thank you <3
