### ISSUE TITLE
Bungeecord Question/Issue

### ISSUE THREAD

**Issue by MegaJoshy** [BenCodez/VotingPlugin#698]
**Versions**
Plugin: `latest on spigot`
Bungeecord: `Waterfall version git:Waterfall-Bootstrap:1.15-SNAPSHOT:4339bb7:317`
Spigot: `git-Paper-79`

I am wondering how I would setup bungeecord, I have tried the way of putting the plugin in the bungeecord server but that doesn't seem to work at all. I am looking for it to reward in all servers but I am really looking for the information to be synced like top votes, vote party and other information like that. How would I go about doing this? I have tried reading other issues around this but can't find much on what I'm looking to do.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by MegaJoshy** [comment]
I have read them before and tried to do it but not been able to setup the Bungeecord plugin one and I'm unsure the Independent Storage makes sense in my use case. I'm looking to have the things like VoteStreak the same on all servers.

**Comment by BenCodez** [comment]
You want to use the first or last method. Depending on your setup

**Comment by MegaJoshy** [comment]
Never got the first method to work, configured everything correctly. Think I got the ports wrong though as that's a little confusing and not explained much.

**Comment by BenCodez** [comment]
It's similar to votifier ports. (Same connection method)

You need to make sure the ports are available as well.

I haven't explained it much since I recently added this method, but it has been tested and seems to work for everyone whose got it working.

Let me know if you need more help.

**Comment by MegaJoshy** [comment]
Been using MCTools to send test votes through but they never get to the actual server. NuVotifier picks it up on bungeecord but it doesn't get picked up on VotingPlugin.

**Comment by BenCodez** [comment]
There is a command /votingpluginbungee vote (name) (site) to test

There is no message in console at the moment on it working bungee side (probably will add that now)

The spigot servers handle the vote after bungee sends it to them.

**Comment by MegaJoshy** [comment]
Issued the command but got this error: 
https://hastebin.com/cinufaxufa.md

**Comment by BenCodez** [comment]
the sockets aren't working, would need to double check that there working.

**Comment by MegaJoshy** [comment]
Just a quick question I don't need NuVotifier right inside the spigot server? If so I'm guessing I can ignore these right? 
`[14:09:00 ERROR]: [VotingPlugin] Plugin VotingPlugin v5.20.6 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent because com/vexsoftware/votifier/model/VotifierEvent does not exist.`

`[14:09:00 WARN]: [VotingPlugin] No VotifierEvent found, install Votifier, NuVotifier, or another Votifier plugin`

**Comment by BenCodez** [comment]
Just on bungee.

**Comment by MegaJoshy** [comment]
Yeah, so how would I check the sockets then? To me everything seems correct.

**Comment by BenCodez** [comment]
There really isn't a way. Make sure the ports are open and that the information is correct. And that nothing is blocking the connection.

**Comment by MegaJoshy** [comment]
From what I can tell then everything is done correctly: https://hastebin.com/aqafonogus.http

**Comment by BenCodez** [comment]
Did you set that on the bungee server? Try specify the host instead of just localhost.

**Comment by MegaJoshy** [comment]
It was set on Bungee and Spigot, I think I messed up the bungeeconfig as I reset it, I'm going ot try and do it agian and see if that fixes it.

**Comment by MegaJoshy** [comment]
I tried assigning the bungeecord server in the config the actual IP itself instead of `127.0.0.1` but now it says it just can't bind to it.

**Comment by BenCodez** [comment]
Try a different host or port?

**Comment by MegaJoshy** [comment]
Yeah tried a different port and got this: 
https://hastebin.com/gavojiciwe.md

**Comment by BenCodez** [comment]
Use a different host I guess. 127.0.0.1 uses localhost, you'll need to set that to be the same across all servers. (Unless localhost is all the same)

**Comment by MegaJoshy** [comment]
Yeah, I can try use `127.0.0.1` on everything again and see what happens as with that I didn't get any bind errors.

**Comment by BenCodez** [comment]
You won't be able to use that, if you know the localhost ip then set it to that. as localhost on bungee will probably be different than on spigot server. Reason for your issue before.

**Comment by MegaJoshy** [comment]
Localhost is the same on everything, but I can try using the actual IP for everything if that would work better.

**Comment by MegaJoshy** [comment]
I'm a little confused about everything TBH, a little tired and will probably pick this up in the morning. I think you where saying to set it to the IP of localhost `94.130.X.XXX` on everything where it needed an IP and I have done that but it said it couldn't bind to the and it is correctly configured though. If I don't reply I will reply back back in the morning, night!

Josh. P

**Comment by BenCodez** [comment]
It should work after you set the ip, not sure why it couldn't bind.
