### ISSUE TITLE
Rewards Not Working

### ISSUE THREAD

**Issue by mooshlandia** [BenCodez/VotingPlugin#699]
Hello. When players vote on my server they do not get rewards. I've tried everything I could think of and find on the internet. It won't let me send the votesites.yml file so here's it copy and pasted.
VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  PlanetMinecraft:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: true
    
    # Display name of voting site
    Name: 'PlanetMinecraft'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'PlanetMinecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    VoteURL: 'https://www.planetminecraft.com/server/mooshlandia/vote/'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      -  /crates givekey %player% vote 1
      -  /money give %player% 100
      # Send player a message
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  # Site 2 example
  Site2:
    Enabled: false
    Name: 'Site2'
    ServiceSite: 'PlanetMinecraft.com'
    VoteURL: 'link to vote URL here, used in /vote'
    VoteDelay: 24
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next will be attempted
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'You voted'
    
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by BenCodez** [comment]
No / on commands. Pastebin next time please :)

**Comment by mooshlandia** [comment]
I tried that also and it does not work

**Comment by BenCodez** [comment]
Pastebin that please?

**Comment by mooshlandia** [comment]
How do you pastebin?

**Comment by BenCodez** [comment]
https://pastebin.com/

**Comment by mooshlandia** [comment]
file:///C:/Users/mhk20/Desktop/VoteSites%20.yml

**Comment by BenCodez** [comment]
Go to https://pastebin.com/ and copy and paste it there and post it as unlisted, then send the link.

**Comment by mooshlandia** [comment]
I had the no / before and it did not work. I only added it to see if it made a difference. Ok I'll fix it.

**Comment by mooshlandia** [comment]
How do I publish it? When I drag the file in it takes up the entire screen. There's no more buttons.

**Comment by BenCodez** [comment]
https://www.youtube.com/watch?v=oCS0kU5VFA4

**Comment by mooshlandia** [comment]
https://pastebin.com/KFiiMaPf

**Comment by BenCodez** [comment]
Just remove the / on the commands.

Try the rewards with /av vote (player) (site)

**Comment by mooshlandia** [comment]
Is there a way to reload the plugin without restarting the server?

**Comment by mooshlandia** [comment]
So I typed the command and it works. The new problem is that when players vote they don't get anything.

**Comment by BenCodez** [comment]
Check votifier.

**Comment by mooshlandia** [comment]
How do I do that? I don't know what I would be looking for.

**Comment by BenCodez** [comment]
Valid host/port? Correct public key setup on the voting site?

Use this to test:
https://mctools.org/votifier-tester

**Comment by mooshlandia** [comment]
is the host just the number ip?

**Comment by mooshlandia** [comment]
i did the port and public key earlier

**Comment by BenCodez** [comment]
Make sure it's an open port. Votifier is your problem right now

**Comment by mooshlandia** [comment]
What is an open port?

**Comment by BenCodez** [comment]
A port not in use elsewhere.

**Comment by mooshlandia** [comment]
I used the port listed in the server menu, my IP, and public key. It says the vote was sent successfully.

**Comment by BenCodez** [comment]
It will always say sent successfully even if it doesn't work. I would try another port.

**Comment by mooshlandia** [comment]
Ok so how do I get another port? Do I use the one in the config?

**Comment by BenCodez** [comment]
Just change the port in the votifier config

**Comment by mooshlandia** [comment]
The one in the config is different from the one in the server menu. I believe the people who host my server changed it to make it work.

**Comment by BenCodez** [comment]
Check the startup log

**Comment by mooshlandia** [comment]
When I changed it and did /nv reload in the console this error came up.
ERROR [Votifier] Votifier was not able to bind to /104.128.70.110:25579

**Comment by BenCodez** [comment]
Try a new port

**Comment by mooshlandia** [comment]
Just any port?

**Comment by BenCodez** [comment]
Try a random number

**Comment by mooshlandia** [comment]
Ok I changed to a random number and it says after /nreload that it works

**Comment by mooshlandia** [comment]
So do I just change the port in the voting plugin config to match the votifier port?

**Comment by BenCodez** [comment]
No, on the voting sites.

**Comment by mooshlandia** [comment]
what is the port by default that's in the config?

**Comment by BenCodez** [comment]
Why does that matter?

**Comment by mooshlandia** [comment]
Because I changed it but I think I figured out what it use to be. Anyway, I don't see where I'm supposed to put the port in votingsites.yml

**Comment by BenCodez** [comment]
You don't change any ports in votingplugin. On the actual voting website.

**Comment by mooshlandia** [comment]
Ok so I did that and the server appears to be linked to the voting site. Now when I try to vote it shows redstone blocks and says I need to wait a certain amount of hours. A player just voted but it didn't give them anything.

**Comment by BenCodez** [comment]
Use this to test:
https://mctools.org/votifier-tester

**Comment by mooshlandia** [comment]
Ok so it went through and gave me a diamond

**Comment by BenCodez** [comment]
Did you set a reward for a diamond? If not do you have CMI?

**Comment by mooshlandia** [comment]
I have CMI

**Comment by mooshlandia** [comment]
The test vote gave me a diamond, not the one I have installed

**Comment by BenCodez** [comment]
Disable the diamond reward in CMI

**Comment by mooshlandia** [comment]
How and where?

**Comment by mooshlandia** [comment]
By the way, the player didn't get anything when they voted. Not even the diamond.

**Comment by mooshlandia** [comment]
Ok, so I cut the broadcast and give diamond commands out of the cmi config

**Comment by BenCodez** [comment]
So all good then?

**Comment by mooshlandia** [comment]
No. When I do the test vote it still gives me the diamond.

**Comment by mooshlandia** [comment]
Players don't get anything when they vote.

**Comment by BenCodez** [comment]
Does the server get the vote? Check console.

**Comment by mooshlandia** [comment]
No

**Comment by mooshlandia** [comment]
Nothing shows up

**Comment by BenCodez** [comment]
Did you update the votifier info on the site?

**Comment by mooshlandia** [comment]
Yes

**Comment by BenCodez** [comment]
Well, nothing I can do, it's a votifier issue.

**Comment by mooshlandia** [comment]
Ok thank you
