### ISSUE TITLE
Adding Multiple sites to vote 

### ISSUE THREAD

**Issue by Spooonnn** [BenCodez/VotingPlugin#701]
**Versions**
Spigot 5.20.6

**Context**
I am trying to add multiple vote sites for /vote. The congif only allows 2 examples, how do I add more than 2?

**Comment by BenCodez** [comment]
Add one the same as the first one or let the plugin generate one for you.

https://github.com/Ben12345rocks/VotingPlugin/wiki/Adding-VoteSites

**Comment by Spooonnn** [comment]
Ok I know how to add them in game now thanks, but now a new problem, when i do and /av or /vote commands nothing happens. I have votingplugin.* on my perms as well so i don't think its a perm issue. i don't see any errors in the console ethier

**Comment by BenCodez** [comment]
Is the plugin loading?

**Comment by Spooonnn** [comment]
yes. I can see alist of commands but none of them work

**Comment by BenCodez** [comment]
Startup log?

**Comment by Spooonnn** [comment]
wait im sorry, kinda said it to early. /votegui and the other commands seem to work but nothing happens when i do /vote

**Comment by Spooonnn** [comment]
so its just /vote

**Comment by BenCodez** [comment]
Is there another plugin or something blocking the command? You need to provide a little more detail.

**Comment by Spooonnn** [comment]
Hmm i can give a list of plugins i have alot

**Comment by BenCodez** [comment]
Console logs, plugin version, configs, etc....

**Comment by Spooonnn** [comment]
AAC 
  |   | AdvancedPortals
  |   | AutoAnnouncer 
  |   | Citizens | Directory | 4 KB | Feb 16 20:14 |  
  |   | CoreProtect | Directory | 4 KB | Feb 16 20:26 |  
  |   | Essentials | Directory | 4 KB | Feb 16 17:36 |  
  |   | FastAsyncWorldEdit | Directory | 4 KB | Jan 20 07:38 |  
  |   | Holograms | Directory | 4 KB | Jan 12 01:39 |  
  |   | IPWhitelist | Directory | 4 KB | Jan 11 01:54 |  
  |   | JoinFireworks | Directory | 4 KB | Jan 11 19:21 |  
  |   | LobbyAPI | Directory | 4 KB | Jan 20 00:35 |  
  |   | MassiveCore | Directory | 4 KB | Jan 11 19:21 |  
  |   | MultiChatSpigot | Directory | 4 KB | Jan 20 15:42 |  
  |   | Multiverse-Core | Directory | 4 KB | Jan 11 19:21 |  
  |   | Multiverse-Inventories | Directory | 4 KB | Jan 11 19:22 |  
  |   | Multiverse-Portals | Directory | 4 KB | Jan 11 19:24 |  
  |   | PermissionsEx | Directory | 4 KB | Jan 20 03:11 |  
  |   | PixelPrinter | Directory | 4 KB | Jan 20 15:19 |  
  |   | PluginManagerReloaded | Directory | 4 KB | Jan 20 00:00 |  
  |   | PluginMetrics | Directory | 4 KB | Jan 20 15:18 |  
  |   | ProtocolLib | Directory | 4 KB | Feb 16 19:16 |  
  |   | Serverlist | Directory | 4 KB | Jan 20 19:29 |  
  |   | UltraCommand | Directory | 4 KB | Jan 20 21:16 |  
  |   | Updater | Directory | 4 KB | Jan 11 19:24 |  
  |   | Vault | Directory | 4 KB | Jan 11 19:25 |  
  |   | Votifier | Directory | 4 KB | Feb 16 03:35 |  
  |   | VotingPlugin | Directory | 4 KB | Feb 16 20:24 |  
  |   | WildTP | Directory | 4 KB | Jan 11 19:25 |  
  |   | WorldEdit | Directory | 4 KB | Jan 11 19:25 |  
  |   | WorldGuard
  |   | bStats
  |   | dynmap
  |   | uSkyBlock

**Comment by Spooonnn** [comment]
plugins

**Comment by Spooonnn** [comment]
thats on my hub server, forgot to mention im running a bungeecord server

**Comment by BenCodez** [comment]
VoteSites.yml?

**Comment by Spooonnn** [comment]
what?

**Comment by Spooonnn** [comment]
here is the log
[latest.log](https://github.com/Ben12345rocks/VotingPlugin/files/4210866/latest.log)

**Comment by BenCodez** [comment]
Wanna send me the VoteSites.yml file?

**Comment by Spooonnn** [comment]
I have votingplugin on my bungee, hub, and factions server

**Comment by BenCodez** [comment]
[15:23:38] [Server thread/INFO]: [UltraCommand] Spooonnnn issued custom command: /vote

Check that.

**Comment by Spooonnn** [comment]
yes that worked thanks! I think one of my mods installed UltraCommand and never configed it right, so what is the command to add a site again?

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/Adding-VoteSites

**Comment by Spooonnn** [comment]
do i need to add this to all my servers including bungee

**Comment by BenCodez** [comment]
Yes.

**Comment by Spooonnn** [comment]
alright thanks

**Comment by Spooonnn** [comment]
Im still confused on how to add more than 2 sites that are in the config, if i do /avgui i can only edit the one i have made not add

**Comment by BenCodez** [comment]
From the wiki:

Creating VoteSite:
- Vote on website, will cause file to be autocreated - SiteName will be the service site by default)
- Create site manually, take a look at the VoteSites.yml
- Create ingame, /av gui (Middle click votesites)

**Comment by Spooonnn** [comment]
ok it says i added one but when i go to the config i dont see it in votesites.yml

**Comment by Spooonnn** [comment]
wait neverming

**Comment by BenCodez** [comment]
Did you reopen the file? 

I can't help you step by step, even if I wish I could.

**Comment by Spooonnn** [comment]
do you happen to know why the names with . get replaced with _ (for ex minebrowse.com is now minebrowse_com

**Comment by BenCodez** [comment]
Because yml reads periods differently.

**Comment by Spooonnn** [comment]
is there a way i can put the . ?

**Comment by Spooonnn** [comment]
or should i just leave it be

**Comment by BenCodez** [comment]
You can set a name on the votesite.

**Comment by Spooonnn** [comment]
I just set up all my sites but when i go to vote i dont see any conformation ingame

**Comment by BenCodez** [comment]
You need to provide more information.

**Comment by Spooonnn** [comment]
well when i go to one of my links and I put my username for a website, I dont get any reward or message ingame

**Comment by BenCodez** [comment]
Sounds like a votifier issue. Check that.

**Comment by Spooonnn** [comment]
I used a votifier test tool and the votes seem to go through

**Comment by BenCodez** [comment]
Try a new port, usually the problem.

**Comment by Spooonnn** [comment]
I also get this error for almost all my sites in the conssole

Server thread/WARN No vote has been recieved from Minecraftservers.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

**Comment by BenCodez** [comment]
Like I said, a votifier issue.

**Comment by Spooonnn** [comment]
So im using NuVotifer, my current ports for bungee are 2267, do i need to change that and allo the other ports aswell?

**Comment by Spooonnn** [comment]
like my other 2 spigot

**Comment by BenCodez** [comment]
Is it an open port? You need to make sure that's working.

**Comment by Spooonnn** [comment]
Sorry im not really sure what that means

**Comment by BenCodez** [comment]
Is the port available? There isn't much I can do for you at the moment.

**Comment by Spooonnn** [comment]
well im guessing the ports I have now are availible becuase like I said the votes on the tester went through

**Comment by BenCodez** [comment]
It always says it goes through, the votifier tester has no way of knowing if the server gets the vote.

**Comment by Spooonnn** [comment]
ah ok then i will cahnge the ports

**Comment by Spooonnn** [comment]
still doesnt work

**Comment by Spooonnn** [comment]
I changed all the ports on my bungee and spigot server but the rewards still dont come through

**Comment by BenCodez** [comment]
There isn't much I can do for you right now.

**Comment by Spooonnn** [comment]
alright, anything else i can try?

**Comment by BenCodez** [comment]
I got nothing right now. Check some tutorials and double check everything?

**Comment by Spooonnn** [comment]
alright thanks
