### ISSUE TITLE
Hole in the Voting Rewards

### ISSUE THREAD

**Issue by Phamous1** [BenCodez/VotingPlugin#702]
**Versions**
Paper 1.15.2 / VotingPlugin v 5.20.6

**Describe the bug**
So i have rewritten the Rewards files like 20 different times.  I have them set up the only way i have been able to get it to work so far, i did a main reward file with chance rewards, which then have a list of rewards files in each chance section. Ill Provide the pastebin of my main rewards file below.  It works 95% of the time, but then it just doesnt give a reward sometimes. I did just get an error which ill pastebin below as well in the console when i just tried to fix it.  But i assume it is from the Fallback i tried to implement on the entire reward file.   

**Expected behavior**
This should give out a chance reward based on the percentages. So i should have 60% chance of first reward files, a 25% chance of 2nd, a 10% chance of the 3rd, and 5 % chance of the 4th.  Yet i get actually more than normal amount of the lower chance rewards lately for some reason. 

**Screenshots/Configs**
config.yml
https://pastebin.com/XXvUcTdv

voterid.yml 
https://pastebin.com/kv66vm9v

VoteSites.yml
https://pastebin.com/K0U6VF5B

**Additional context**
This is the Console error i just recieved. 
https://pastebin.com/ewgSsiKR

**Comment by BenCodez** [comment]
https://pastebin.com/dnwjjTZe

That help? 

This should solve the error:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Phamous1** [comment]
If i do that wont that give reward 4 priority if all other ones fail ?

**Comment by BenCodez** [comment]
Yeah, wasn't sure if you wanted that. You can change that.

**Comment by BenCodez** [comment]
You can also reverse the order as well. Not sure how that would work out.

**Comment by Phamous1** [comment]
ok so i should reverse it so reward 1 gives if all others fail, and have the chances above yes ?

**Comment by Phamous1** [comment]
https://pastebin.com/egvAaw7P 

Something like this ?

**Comment by Phamous1** [comment]
Alright awesome i think i got it worked out and found another error in my yml that was creating the last hole :) Thanks for explaining it lol
