### ISSUE TITLE
Duplicating Voting Pages

### ISSUE THREAD

**Issue by nilsrob1** [BenCodez/VotingPlugin#703]
**Versions**
Paper Version 1.15.2

**Describe the bug**
When reloading the plugin after awhile it duplicates 2 of our voting pages that is already been added without a link, It also removes a page or two something, it makes no sense, take a look at our config, I dont think there is anything wrong.

**Screenshots/Configs**
Our configs: [https://pastebin.com/81X4fTrr](https://pastebin.com/81X4fTrr)

**Comment by BenCodez** [comment]
Check console when that happens. It will generate a votesite if there is none found with the proper votesite.

**Comment by nilsrob1** [comment]
> Check console when that happens. It will generate a votesite if there is none found with the proper votesite.

So the config is right?

**Comment by BenCodez** [comment]
The one that generates is.

**Comment by nilsrob1** [comment]
As far as I know and have seen, there is no logs/console

**Comment by BenCodez** [comment]
Just vote on the site and it will say in console if it generates. You can disable this in the config if needed. There is also /av servicesites, might help as well.

**Comment by nilsrob1** [comment]
The thing is, it works but it sometimes duplicated more voting pages and once I click the link it says "VOTEURL" in chat as if there is a voting page without an URL linked to it.

**Comment by BenCodez** [comment]
Because that's the default voteurl when it generates.

**Comment by nilsrob1** [comment]
We shut down our server and set it up properly, gonna see if it fixed the problem, seem like there was a problem with editting the plugin while running the server at the same time.

**Comment by BenCodez** [comment]
Did you vote in between edits?
