### ISSUE TITLE
Command usage improvements

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#704]
**Is your feature request related to a problem? Please describe.**
Not being able to understand command usage easily.

**Describe the solution you'd like**
I'd like for every command to have a usage message as opposed to the very vague:
`"No valid arguments, see /adminvote help!"`

**Describe alternatives you've considered**
Using `/av help` but it's just overly complicated when it could simply be sent as a usage message.

**Comment by BenCodez** [comment]
It says no valid arguments if there is no valid command, which would mean I couldn't put a usuage message. Did you have something in mind?

**Comment by LogGits** [comment]
For example these commands show `This show "No valid arguments, see /adminvote help!`:
```
/av user
/av user {playername}
```
now here's the thing, i then have to goto /av help page 5 to finally find any info about `/av user`. This makes it really annoying to use the commands. It would be nice if `/av user` would show the info.

**Comment by BenCodez** [comment]
Use tab complete? That would be a lot of work to do that.
