### ISSUE TITLE
cant seem to get milestones to work wondering if you could have alook at my code ?

### ISSUE THREAD

**Issue by Callmewheato** [BenCodez/VotingPlugin#706]
'5':
  Enabled: true
  Rewards:
  Commands:
  Console:
  - 'manuadd %player% RED'
  - 'pay %player% 5,000'
  - '{RED}%player% {RED}Has voted 5 times and ranked up to {RED} RED RANK!'

**Comment by BenCodez** [comment]
Wanna pastebin that whole milestone section?
