### ISSUE TITLE
Plugin disabled during startup

### ISSUE THREAD

**Issue by LJIT-WD** [BenCodez/VotingPlugin#707]
**Versions**
Plugin version: 5.20.6
Paper 1.15.2

**Describe the bug**
The plugin disabled itself during startup.

**To Reproduce**
1. Upload the plugin to /plugin folder
2. Restart server
3. Change some settings in config.yml
4. Restart server
5. No issues after restarting server
6. Restart server again (because uploaded some plugins)
7. Error occurred!

**Expected behavior**
Enable the plugin when startup.

**Screenshots/Configs**
Config.yml: https://hastebin.com/yovobonepe.coffeescript

**Additional context**
Console log: https://hastebin.com/owocekavim.md

**Comment by BenCodez** [comment]
User ljit_ljcraft already has more than 'max_user_connections' active connections

Looks like mysql has too many connections.

**Comment by LJIT-WD** [comment]
I set the max_user_connections to 100 and it works!

**Comment by LJIT-WD** [comment]
I need to reopen the issue because even when I set the max_user_connections to 99999, it still causes the same error. What can I do?

**Comment by BenCodez** [comment]
I'm not exactly sure. Is it the same error?

**Comment by LJIT-WD** [comment]
Please see the log:
https://hastebin.com/iwimefifoj.md

**Comment by BenCodez** [comment]
Yeah, not much I can do.

**Comment by LJIT-WD** [comment]
I found a free MYSQL database provider, which lets me create unlimited users. I used different accounts on every server, and this method seems working! Hope you can fix the issue.

**Comment by BenCodez** [comment]
Not much I can do.
