### ISSUE TITLE
Help with reward please?

### ISSUE THREAD

**Issue by Cyclopeanserver** [BenCodez/VotingPlugin#708]
**Versions**
latest plugin version, latest paper

**Relevant information**
rewards

**Context**
Good afternoon, I'm having some problems with getting rewards passed to the player. I want to give the players one random item from a list of items. What would a reward look like to do a random console command? For instance, potion, gapple or emerald could be a reward. Can you do something like.
reward:
commands:
 console:
  randomcommand:
  - '/give reward1
  - '/give reward 2
 - '/give reward 3

Perhaps you could supply a small sample of reward code for this example, that I could build on? Also one thing I'm confused. I want the same reward to be given for any vote. Do I just add the same reward to every site in votesites.yml, or do rewards like that belong somewhere else? Please help, great plugin and my first server.

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - 'say %player%'

Something like that?

**Comment by Cyclopeanserver** [comment]
The idea is a list of random rewards, mainly the top tier potions, diamonds, etc... but only one random item from the list. In your opinion, which is the best way to achieve this? Also, would I just copy paste the same "reward" into each of the voting sites rewards? Apologies, I'm new to this. I have everything working great, except I can't get the reward formatting correct.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleAdvanced.yml#L41

Something like that

**Comment by Cyclopeanserver** [comment]
When I try something like this in the votesites reward area. In the console i get unknown command, use /help. but the vote goes through and is counted. Should i put the rewards in a file, and point that that?

RandomItem:
  Diamond:
    Material: DIAMOND
    Amount: 1
  Iron:
    Material: potion{Potion:"minecraft:long_fire_resistance"}
    Amount: 1

update: the above works when using the gui to give a reward file, but when the potion is chosen, it's an invalid material and give stone.

**Comment by BenCodez** [comment]
Then the command you put is wrong. No / on command.
Use a command for the potion.

**Comment by Cyclopeanserver** [comment]
when I do:

RandomCommand:
  console:
    - give minecraft:diamond 1
    - give minecraft:potion{Potion:"minecraft:long_fire_resistance"} 1

I get this in the console. I need to run the /give command from console correct?
22.02 19:30:52 [Server] INFO Cyclopean_Server issued server command: /VotingPluginvaluerequestinput String reward

**Comment by BenCodez** [comment]
just a list under randomcommand

**Comment by Cyclopeanserver** [comment]
First off, i really apprciate the support. OK, progress. Now when I do this:

RandomCommand:
  - give minecraft:diamond 1
  - give minecraft:potion{Potion:"minecraft:long_fire_resistance"} 1

I get this:
22.02 19:38:05 [Server] INFO Cyclopean_Server issued server command: /VotingPluginvaluerequestinput String Cyclopean_Server
22.02 19:38:10 [Server] INFO Cyclopean_Server issued server command: /VotingPluginvaluerequestinput String reward
22.02 19:38:11 [Server] INFO Expected whitespace to end one argument, but found trailing data
22.02 19:38:11 [Server] INFO ... minecraft:diamond 1<--[HERE]

I tried also with removing the quantity with same error.

**Comment by BenCodez** [comment]
That command is wrong for the potion, don't know off top of my head.

**Comment by Cyclopeanserver** [comment]
I left out the %player% variable (*facepalm). It worked fine when i used just the diamond. I think I've wrapped my head around this part. If i have this random reward file as reward.yml inside the rewards folder... is the correct format to point to this reward.yml in the votesites.yml like this?

Rewards: 'reward.yml'      (with or without the ' ' ?)

**Comment by BenCodez** [comment]
Don't include .yml

**Comment by Cyclopeanserver** [comment]
Thanks a bunch! I'll give that a shot. I'll consider this particular issue closed.
