### ISSUE TITLE
Message for multiple votes 

### ISSUE THREAD

**Issue by WolverStones** [BenCodez/VotingPlugin#709]
Please add the option to display only one message with the number of votes instead of listing each vote separately ...

**Comment by BenCodez** [comment]
What exactly do you mean?

**Comment by WolverStones** [comment]
http://prntscr.com/r6lq4x

**Comment by BenCodez** [comment]
You're going to need to provide more details.

**Comment by WolverStones** [comment]
I have set up 2 voting services if a player votes and connects to the server in the chat you will see a message that the player has voted .. but the problem is that when a player vote 20 times, 20 messages appear in the chat ... it is possible to add a function that only one message will be displayed with the number of votes the player has voted. ?

**Comment by BenCodez** [comment]
There is a reward called anyvotesite in the config, use that for any messages.
