### ISSUE TITLE
people dont get their rewards

### ISSUE THREAD

**Issue by Backstabber010** [BenCodez/VotingPlugin#710]
**Versions**
Plugin version and spigot version.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
?

**Comment by Backstabber010** [comment]
well like i said, people dont get their rewards, why? I dont own a website btw for my minecraft sserver. The links are working and you can click it, but nothing happens ingame

**Comment by BenCodez** [comment]
Is the server getting the vote? Check console when you vote, if not it's a votifier issue.
