### ISSUE TITLE
Dupe Items when voting 1 time.

### ISSUE THREAD

**Issue by Agaloth** [BenCodez/VotingPlugin#711]
**Versions**
VotingPlugin 5.20.7 and paper 1.14.4, 239

**Relevant information**
https://pastebin.com/Ws5Dpyie

**Context**
When I vote 1 time it gives the reward 4 times.

The console gives that when I test votes:

28.02 16:33:10 [Server] INFO Agaloth issued server command: /av test agaloth Site1 1
28.02 16:33:10 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 16:33:10 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 16:33:10 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 16:33:10 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 16:33:10 [Server] INFO [VotingPlugin] Time to process votes (1): 106 ms, average per vote 106 ms. SQLITE, 1103 users. 7 votesites

**Comment by BenCodez** [comment]
Turn debug on and check what the logs say.

**Comment by Agaloth** [comment]
How can I save the logs?

**Comment by BenCodez** [comment]
Either console or the log file.

**Comment by Agaloth** [comment]
![image](https://user-images.githubusercontent.com/33335971/75591591-64b33000-5a80-11ea-8698-745801395c00.png)
![image](https://user-images.githubusercontent.com/33335971/75591607-6bda3e00-5a80-11ea-9243-c79a56757efd.png)

**Comment by Agaloth** [comment]
I get that

**Comment by Agaloth** [comment]
And I only get that in the console:

28.02 23:15:51 [Server] INFO Agaloth issued server command: /av test Agaloth Site1 1
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO GoldenCrates » Given x1 Vote Crate! crate key(s) to Agaloth
28.02 23:15:51 [Server] INFO [VotingPlugin] Time to process votes (1): 438 ms, average per vote 438 ms. SQLITE, 1108 users. 7 votesites

**Comment by BenCodez** [comment]
Use /av vote? Also need the log, not a screenshot.

**Comment by Agaloth** [comment]
The plugin doesn't create logs in /plugins/VotingPlugin

**Comment by Agaloth** [comment]
Do I have to shut down the server?

**Comment by BenCodez** [comment]
It's the server log.

**Comment by Agaloth** [comment]
oh okay

**Comment by Agaloth** [comment]
[latest.log](https://github.com/Ben12345rocks/VotingPlugin/files/4269362/latest.log)

**Comment by Agaloth** [comment]
Here is my current server log

**Comment by BenCodez** [comment]
You didn't enable debug

**Comment by Agaloth** [comment]
I enabled it on the config.yml and I get the in game debug messages

**Comment by BenCodez** [comment]
# Debug levels:
    # NONE
    # INFO
    # EXTRA
    DebugLevel: NONE

Set that to extra

**Comment by Agaloth** [comment]
[latest.log](https://github.com/Ben12345rocks/VotingPlugin/files/4269376/latest.log)
The infos should be all below!

**Comment by BenCodez** [comment]
I think it might just be from using /av test, you should use /av vote (player) (site)

**Comment by Agaloth** [comment]
okay

**Comment by Agaloth** [comment]
[latest.log](https://github.com/Ben12345rocks/VotingPlugin/files/4269398/latest.log)
Here is it with /av vote agaloth site1

**Comment by BenCodez** [comment]
Yeah, I got no idea. Redownload the jar, restart the server?

**Comment by Agaloth** [comment]
I didn't redownload the .jar let me try it

**Comment by Agaloth** [comment]
restarting rn

**Comment by Agaloth** [comment]
Issue has been fixed, reinstalling the .jar fixed it :/
