### ISSUE TITLE
make the rewards setup easier

### ISSUE THREAD

**Issue by CaszGamerMD** [BenCodez/VotingPlugin#712]
have a command that adds item in hand to the rewards

**Comment by BenCodez** [comment]
/av gui, you can edit reward files, which you can then list on the rewards.

**Comment by CaszGamerMD** [comment]
sorry meant the shop

**Comment by BenCodez** [comment]
Copy the item configuration from a reward file? It works the same way. 

You can always use bossshop, it has a dedicated application to edit its configs.
