### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [BenCodez/VotingPlugin#713]
Plugin Version: Build #58 
Waterfall : Build #323

I get a console error on waterfall/bungee at startup, i am not sure what it is but i want to fix it. Help please, also you should make a discord.

https://pastebin.com/aeMTGqrc

**Comment by BenCodez** [comment]
Did you enable bungeecoord in the plugin?

**Comment by LucidAPs** [comment]
Ofcurse.

**Comment by BenCodez** [comment]
Are you using the specific bungee features for that? The error is because it's not setup correctly.

**Comment by LucidAPs** [comment]
You are right, it was my fault. If i may ask before we close this. At the config you have this:

Get the plugin to broadcast to all servers
BungeeBroadcast: true

Is there a specific plugin you are referring to? Because there are a lot of bungee broadcast plugins, will any of them do? I want the broadcast that happens when you vote to be visible on all servers.

Also if i set this to false.

Have a reward on each server
SendVotesToAllServers: false

This will mean that users will get only one reward based on the server they are in right?

**Comment by BenCodez** [comment]
You need to set the sockets up on each server. There is no other plugin
needed.

**Comment by LucidAPs** [comment]
Sockets? The votes are currently working fine on each server and they are all connected in the network. But the voting broadcast only appears on local server and not in the whole network and also the user gets a reward from all the servers when he visits them, i want to disable that, hence my second question above.

**Comment by BenCodez** [comment]
There is a wiki page on it

**Comment by LucidAPs** [comment]
Using this setting:
SendVotesToAllServers: false

This will mean that users will get only one reward based on the server they are in right?
Can you please just answer?

**Comment by BenCodez** [comment]
Should be.

**Comment by LucidAPs** [comment]
Thanks.
