### ISSUE TITLE
Monthly votes did not reset at the end of the month

### ISSUE THREAD

**Issue by JHarris12345** [BenCodez/VotingPlugin#714]
**Versions**
Plugin Version - 5.20.7
Spigot - 1.14.4

**Describe the bug**
Its fine on all my other servers but on one of my servers the /vote top command is still not reset for march and did not issue top voter commands

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots/Configs**
Config https://pastebin.com/0iJqx4ny

**Comment by JHarris12345** [comment]
Also here is my montly awards.yml in rewards folder but I have also defined monthly awards in config.yml https://pastebin.com/CDpZ8G49

**Comment by BenCodez** [comment]
/av forcetimechange month

What does the time say on the specific server? The plugin reads the time off the server.

**Comment by JHarris12345** [comment]
They are all on the same server

**Comment by BenCodez** [comment]
Yeah, not sure what happen there, was there an error on the new month?

**Comment by JHarris12345** [comment]
Nope

**Comment by BenCodez** [comment]
Yeah, I got no idea right now.
