### ISSUE TITLE
An Op running /av User (Player) ViewData shows that data to the player being queried

### ISSUE THREAD

**Issue by switchbranch** [BenCodez/VotingPlugin#715]
**Versions**
CraftBukkit version git-Spigot-8faa8b4-fba9f48 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

VotingPlugin 5.20.7

**Describe the bug**
As an op, I want to run /av User (Player) ViewData

But it displays nothing to me on run

**To Reproduce**
1.) In-game or in-console, run
/av User notch ViewData
It shows the data that you just requested to see to Notch

**Expected behavior**
The data should instead output to the op or within console.

**Comment by BenCodez** [comment]
Fixed here:
http://ben12345rocks.com/job/VotingPlugin/
