### ISSUE TITLE
Cumulative Rewards Run in sequence on every vote instead of just once

### ISSUE THREAD

**Issue by switchbranch** [BenCodez/VotingPlugin#716]
**Versions**
CraftBukkit version git-Spigot-8faa8b4-fba9f48 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
VotingPlugin 5.20.7

**Describe the bug**
Cumulative rewards seem to be running in a sequence every time a player votes.

**To Reproduce**
1.) A player has voted 20 times.  They have just submitted a 21st.  At 21 votes, the third cumulative reward should be given, which is a promotion to a higher rank.

2.) The system detects they have voted.

3.) The system runs the reward for 1 vote, then 6 votes, then 21 votes.

**Expected behavior**
The system should only run the reward for 21 cumulative votes.

The cumulative vote counter also seems to reset itself for some reason, even though VotesInSameDay and VotesInSameWeek are set to 'false'

**Screenshots/Configs**
Config: https://pastebin.com/7sWkyhrd

**Comment by BenCodez** [comment]
That's intentional, use milestones for a one time reward
