### ISSUE TITLE
/av User (player) ForceCummulative returns no confirmation or error

### ISSUE THREAD

**Issue by switchbranch** [BenCodez/VotingPlugin#717]
**Versions**
CraftBukkit version git-Spigot-8faa8b4-fba9f48 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
VotingPlugin 5.20.7

**Describe the bug**
/av User (player) ForceCummulative returns no confirmation or error

**To Reproduce**
1.) In console or in-game, run:
/av User notch ForceCummulative 6

2.) No success or error message is displayed.

**Expected behavior**
A success or error message should be displayed.  Not sure if this command works.

**Comment by BenCodez** [comment]
Should have a message here:
http://ben12345rocks.com/job/VotingPlugin/
