### ISSUE TITLE
A placeholder or config option for formatted votepoints

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#718]
**Is your feature request related to a problem? Please describe.**
My feature is to add a placeholder to the placeholderapi expansion, or an option in the config which makes the votepoint amount formatted like 1,000 1,000,000 instead of 1000000.

**Describe the solution you'd like**
Basically just a config option or a placeholder that does the above thing.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

%VotingPlugin_Points_Format%

Untested.
