### ISSUE TITLE
Cant find the correct ServiceSite URL

### ISSUE THREAD

**Issue by cantercrow** [BenCodez/VotingPlugin#719]
**Versions**
VotingPlugin 5.20.7 running on Paper Spigot 1.14.4

**Relevant information**
ServiceSite: 'minecraft-mp.com'
VoteURL: 'https://minecraft-mp.com/server/246769/vote'
ServiceSite: 'minecraftservers.org'
VoteURL: 'https://minecraftservers.org/server/575420'
ServiceSite: 'minecraft-mp.com'
VoteURL: 'https://minecraft-mp.com/server/246769/vote'

**Context**
I am getting the error below in my console, I am using VotifierPlus is its the only one that supports 1.14.4, in the VotifierPlus config there are no settings.

[VotingPlugin]: No vote has been recieved from minecraftservers.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[VotingPlugin]: No vote has been recieved from minecraft-mp.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[VotingPlugin]: No vote has been recieved from topg.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

**Comment by cantercrow** [comment]
![image](https://user-images.githubusercontent.com/54336827/76142609-37a9e300-6067-11ea-8414-1af73ff6a307.png)

I found a VotingPlus command to test and it returns ok

**Comment by BenCodez** [comment]
https://mctools.org/votifier-tester

Does that work?

**Comment by cantercrow** [comment]
Hi, yes works
![image](https://user-images.githubusercontent.com/54336827/76144310-cffb9400-6076-11ea-9acd-b9e1b0b9371e.png)

**Comment by cantercrow** [comment]
do you need a certain port open?

**Comment by BenCodez** [comment]
Did the server receive the vote? That's what your testing. It usually sends without trouble.

**Comment by cantercrow** [comment]
Hi,

 

Yes the server received the vote.

 

Regards

Julian

**Comment by BenCodez** [comment]
When the server gets the vote you will see the service site in console.
