### ISSUE TITLE
java.net.ConnectException: Connection refused: connect / Could not pass event PlayerVoteEvent to VotingPlugin v5.20.7

### ISSUE THREAD

**Issue by budies2001** [BenCodez/VotingPlugin#720]
https://pastebin.com/v3KFLHP3 / https://pastebin.com/h2jNug1a hope that helps

**Comment by BenCodez** [comment]
The sockets in VotingPlugin aren't setup properly.

**Comment by budies2001** [comment]
Could that be something I did or might that be a bug? It was working for a while then all of a sudden it stopped.

**Comment by BenCodez** [comment]
Are you using the bungee version of votingplugin? If not just remove that.

https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by budies2001** [comment]
No I am not

**Comment by BenCodez** [comment]
Did you enable bungee in votingplugin?

**Comment by budies2001** [comment]
Yes.

**Comment by BenCodez** [comment]
Disable that.

**Comment by budies2001** [comment]
Ok. You mean UseBungeecoord: true to UseBungeecoord: false?

**Comment by BenCodez** [comment]
Yep

**Comment by budies2001** [comment]
Ok hold on.

**Comment by budies2001** [comment]
Ok I did that but got the same error.

**Comment by budies2001** [comment]
Hold on

**Comment by BenCodez** [comment]
Did you restart?

**Comment by budies2001** [comment]
No.

**Comment by budies2001** [comment]
I am using mysql

**Comment by BenCodez** [comment]
You need to restart.

**Comment by budies2001** [comment]
I have nuvotifier on all my servers and bungee.

**Comment by budies2001** [comment]
One error is gone but one is still there. Could not pass event PlayerVoteEvent to VotingPlugin v5.20.7
org.bukkit.event.EventException: null

**Comment by BenCodez** [comment]
Pastebin the error.

**Comment by budies2001** [comment]
Ok.

**Comment by budies2001** [comment]
https://pastebin.com/3RYiUarS

**Comment by BenCodez** [comment]
Disable bungeebroadcast.

**Comment by budies2001** [comment]
YUP YUP YUP YUP. THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU. It worked.
