### ISSUE TITLE
Voting Plugin crates new sites

### ISSUE THREAD

**Issue by preppy420** [BenCodez/VotingPlugin#721]
5.20.7

I set up 7 sites in votingsites.yml rewards and everything works fine, except when i vote for some reason it makes a new site so now i have 8 sites and then 9 and so on

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Then your service sites are not correct. It will generate a vote site if no site with the correct votesite is found (check console log)
