### ISSUE TITLE
Not getting rewards

### ISSUE THREAD

**Issue by Spooonnn** [BenCodez/VotingPlugin#722]
**Versions**
Spigot 1.15.2 and 5.20.7

**Relevant information**
https://pastebin.com/p5DWzm2S

**Context**
Players were getting rewrds originally until i added 2 new sites in the VoteSites.yml, and now we are not getting rewards from any sites

**Comment by BenCodez** [comment]
Last couple of votesites aren't as correct as the rest, I would point it
out but that's hard on a phone

**Comment by Spooonnn** [comment]
Here is the corrected config ( i think) https://pastebin.com/GC0gsZxa
And heres and error message In the Console - https://pastebin.com/jEh45TxJ

**Comment by BenCodez** [comment]
Are you using the bungee specific features (usebungeecoord and bungeebroadcast)? If not disable that.

**Comment by Spooonnn** [comment]
it is a bungee server though

**Comment by Spooonnn** [comment]
but ill try

**Comment by Spooonnn** [comment]
doesnt work

**Comment by BenCodez** [comment]
Config and console logs?

**Comment by Spooonnn** [comment]
https://pastebin.com/GC0gsZxa

**Comment by Spooonnn** [comment]
https://pastebin.com/jEh45TxJ

**Comment by BenCodez** [comment]
You need to restart after disabling those settings.

**Comment by Spooonnn** [comment]
Where can I find them, A reminder I am using bungeecord and 2 spigot servers

**Comment by BenCodez** [comment]
Config.yml

If your not using VotingPlugin on bungeecord to forward votes then disable it.

**Comment by Spooonnn** [comment]
I'm using votingplugin to foward votes that go to my bungeeserver to my spigot servers, sorry i'm kinda dumb so you might have to explain it like im five

**Comment by BenCodez** [comment]
Read on it here:
https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by Spooonnn** [comment]
Ok now that is strange that worked thanks, why is it when they are set to false instead of true?

**Comment by BenCodez** [comment]
Then you weren't using that bungee version.

**Comment by Spooonnn** [comment]
ah ok thanks
