### ISSUE TITLE
Votes not registering

### ISSUE THREAD

**Issue by BlackMalakDown** [BenCodez/VotingPlugin#726]
**Versions**
VotingPluging version 5.20.8
Paper 1.15.2

**Describe the bug**
No rewards are given to voters, emerald does not change to redstone in the gui when they do vote.

**To Reproduce**
unknown? occurred after most recent update

**Expected behavior**
Voters should be rewarded when they vote.

**Additional context**
NuVotifier is up to date and listening properly to the webites. Plugin had worked prior to updating the plugin. I can add anything else that might help by request

**Comment by BlackMalakDown** [comment]
https://drive.google.com/file/d/1crI-fRYHC6h06neyRMEVYQE7VvJODQrw/view?usp=sharing

to show votifier is set up.

**Comment by BenCodez** [comment]
That picture doesn't prove that votifier is working, you need to look in console and see if the vote comes.
