### ISSUE TITLE
Vote Party Key Given Multiple Times

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#727]
**Versions**

Plugin Version: 5.20.7
Minecraft Version: 1.15.2 

**Describe the bug**
    Vote parties run the reward command multiple times? I am not completely sure if this is a problem my side or it is a bug, but we made it so when a vote party happens it drops vote party keys. After testing this however, it gave us multiple keys when we had the vote party. 

**To Reproduce**
1. Go to 'VotePlugin'
2. Click on 'Config.yml'
3. Scroll down to 'VoteParty and down to the rewards section'
4. Can't exactly see error, but it runs the command multiple/many times.

**Expected behavior**
    Single Vote Party Key given to each player.

**Screenshots/Configs**
`VoteParty:`
`  # Wether or not vote party is enabled`
`  Enabled: true`
`  # Number of votes required to give rewards`
`  VotesRequired: 20`
`  # Increase the amount of votes required on each vote party reached`
`  #IncreaseVotesRquired: 0`
`  # If true, players who did not vote to reach the votes required will`
`  # recieve the reward`
`  GiveAllPlayers: true`
`  # If true, the vote count will reset each day`
`  ResetEachDay: false`
`  # Reset at the end of the month`
`  ResetMonthly: false`
`  # Reset extra votes`
`  ResetExtraVotesMonthly: false`
` # Count votes from /av vote?`
`  CountFakeVotes: true`
`  # Number of user votes that apply to vote party total the user needs to get rewards`
`  UserVotesRequired: 0`
`  # Broadcast when vote party reached`
`  Broadcast: '&6&lWe have reached the vote party amount!'`
`  # List of commands to execute, these only execute once.`
`  # %player% does not work here`
`  Commands: []`
`  # Rewards to give per player`
`  Rewards: `
`    Commands:`
`       Console:`
`        - goldencrates givekey * voteparty 1'`

**Additional context**
    We are using a crate plugin called GoldenCrates

**Comment by BenCodez** [comment]
List that command under Commands right above, Rewards execute for every
player
