### ISSUE TITLE
Maven Support

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#728]
Is there a maven repo for the API?

**Comment by BenCodez** [comment]
<repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>

    <dependency>
        <groupId>com.github.Ben12345rocks</groupId>
        <artifactId>VotingPlugin</artifactId>
        <version>LATEST</version>
        <scope>provided</scope>
    </dependency>

    Versions:
    LATEST - latest stable release
    BRANCH-SNAPHSOT - unstable builds

**Comment by DrakePork** [comment]
Thanks
