### ISSUE TITLE
BroadcastToggle Broken

### ISSUE THREAD

**Issue by Bubbery** [BenCodez/VotingPlugin#729]
**Versions**
version 5.20.8 paperspigot 1.15.2

**Context**
When a user types /vote togglebroadcast, the server sends the following response:
"YamlConfiguration[path='', root='YamlConfiguration']

**Comment by BenCodez** [comment]
Is this in your config?

**Comment by Bubbery** [comment]
The response gets sent as a chat message in game, no console errors are generated. My config should just be the default config with a few things changed to true/false, but the toggle broadcast is enabled, I’m not sure why it’s generating this response.

**Comment by BenCodez** [comment]
I got no idea. I've had a few people had this before with different messages, usually it's when the specific message is missing or some yml error in the config.
