### ISSUE TITLE
Argument for /vote shop

### ISSUE THREAD

**Issue by datatags** [BenCodez/VotingPlugin#730]
**Is your feature request related to a problem? Please describe.**
If you're connected to the server as a text-only client (minechat etc.) it would be handy to be able to use /vote shop.  This isn't possible at the moment because the only way to use the command is through a GUI.  Using /vote shop \<item\> results in an invalid usage message.

**Describe the solution you'd like**
I'd like to be able to use /vote shop \<item\> like /vote shop MineKey or whatever else.

**Describe alternatives you've considered**
Waiting until later to purchase it, although some items are time-sensitive.
Just not purchasing it, but that's not ideal either.

**Additional context**
I don't think so

Thanks!

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

See if it works.

**Comment by datatags** [comment]
It does work, but the invalid input behavior is a little weird.  If a shop item that doesn't exist is asked for, (/vote shop AnItemThatDoesntExist) there is no output to the player or the console.  But if you ask for a shop item that does exist but isn't case-correct, it says "You have bought the \<incorrectly-capitalized item\> for 0 points!" and doesn't do anything.  If the input is correct it works like a charm though!

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should fix that.

**Comment by datatags** [comment]
Works perfectly now, thank you!!
