### ISSUE TITLE
How to Enable Broadcasts and Reminders?

### ISSUE THREAD

**Issue by farhaanlevy** [BenCodez/VotingPlugin#731]
**Versions**
Plugin version and spigot version.
1.15.2 - both

**Describe the bug**
Players are not getting reminded to Vote!
There is no Reminders! for anyone...
**To Reproduce**
just installed plugin?
**Expected behavior**
Remind players to vote?
**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
They are enabled by default, configs, logs?
