### ISSUE TITLE
Not reviving votes on one of my servers

### ISSUE THREAD

**Issue by Spooonnn** [BenCodez/VotingPlugin#732]
**Versions**
Votingplugin 5.20.8 Spigot 1.15.2

**Relevant information**
https://pastebin.com/CVvmrZMT

**Context**
I am not getting the voting rewards on my main server, but getting it on my fallback server (Im running bungee and spigot) Im not really sure why but it was working before and it just suddenly stopped

**Comment by BenCodez** [comment]
Your gonna need to provide more details

**Comment by Spooonnn** [comment]
Here is as much info as I can provide -
https://pastebin.com/9cTDt9mq

This has happened multiple times. Also I forgot to add, I would put something onto the pastebin about the consoles error message, but there isn't one at all. It also seems to be only working on one spigot server only. The pastebin is of the one that isn't working.

**Comment by BenCodez** [comment]
[NuVotifier] Unable to send vote to /96.78`.140`.57:8622. Will retry sending in 1 second(s).

You'll need to check that.

**Comment by Spooonnn** [comment]
Sorry it took so long to respond, but what am I supposed to check, actually the day after you sent the message, it started working again, but now its not.

**Comment by Spooonnn** [comment]
Now it stopped working on all of my servers...

**Comment by BenCodez** [comment]
It's a votifier issue, nothing I can do.

**Comment by Spooonnn** [comment]
Ok, unfortunately I can't find anything that's wrong with the nuvotifier config wise on any of the servers, i've done basically everything I can do, I find it weird that it works sometimes and sometimes doesn't, is their any plugin related to NUvotifier that you recomend?

**Comment by BenCodez** [comment]
Some firewall or the voting site itself? 
This is one you can try (made by me)
https://www.spigotmc.org/resources/votifierplus.74040/

**Comment by Spooonnn** [comment]
How to I setup, do you have a video I can watch or something, I know its similar to NUvotifier, I tried to set it up myself and it didnt work

**Comment by BenCodez** [comment]
What did you try and what didn't work? You need to be specific
