### ISSUE TITLE
I keep getting the same error when a certain player joins and periodically during play

### ISSUE THREAD

**Issue by stw222** [BenCodez/VotingPlugin#733]
**Versions**
VP: 5.20.7 (from /ver votingplugin)
Paper: 1.15.2 Paper-137

**Describe the bug**
A player on my survival server (we are a bungee network but don't use VP on the bungee server) for some reason cant use a few slots in his inventory. he will attempt to modify items in the effected slots but he cant. He is the only player on our server affected by the bug (we have a few dozen active players) and in my 6 months of using VP, no one else has complained about the bug.

when he joins, there is an error that appears in console and sometimes periodically when he i guess attempts to interact with those slots in his inventory.
Error: https://pastebin.com/ijbe54NN

**To Reproduce**
I have no idea how to reproduce this error, but it happens when he joins the server and sometimes while he is just online

**Expected behavior**
He should be able to modify all slots in his inventory

**Screenshots/Configs**
zip file with all of our configs and such for VP: https://drive.google.com/open?id=1xv2MWyY6c52GUTPQMirwpwmKdElfToVn

**Additional context**

**Comment by BenCodez** [comment]
Somewhere where you have min/max money the max isn't higher than the min.

I don't see the inventory issue related to the plugin at the moment.

**Comment by stw222** [comment]
its possible its caused by a different plugin but this is the only error that comes up

**Comment by BenCodez** [comment]
One your rewards is a little messed up, that error shouldn't stop anything other than the receiving money on one of the rewards

**Comment by stw222** [comment]
ya, i found the min max issue and fixed it

**Comment by BenCodez** [comment]
Can't do anything about the inventory issue.
