### ISSUE TITLE
Votesites

### ISSUE THREAD

**Issue by MinecraftCitiesNetwork** [BenCodez/VotingPlugin#736]

**Comment by BenCodez** [comment]
https://pastebin.com/gbnDmnYU

**Comment by democracycraft** [comment]
It's working now. However it isn't registering that I have voted?

**Comment by BenCodez** [comment]
Is the server getting the vote?

**Comment by democracycraft** [comment]
No. I can vote on the websites, however it won't show on the server. I also can't get votegui up now.

**Comment by BenCodez** [comment]
Console log?

**Comment by democracycraft** [comment]
[latest.log](https://github.com/Ben12345rocks/VotingPlugin/files/4384461/latest.log)

/vote and /votegui not working.
Server not receiving votes

**Comment by BenCodez** [comment]
[20:10:23] [Server thread/ERROR]: Ambiguous plugin name `Votifier' for files `plugins/nuvotifier.jar' and `plugins/votifier-1.9.jar' in `plugins'

Why do you have both jars?

Config.yml?
Check votifier, server isn't getting the vote.

**Comment by democracycraft** [comment]
Just deleted nuvotifier.

Do you want votifier config?

**Comment by BenCodez** [comment]
Try a new port and use a votifier tester, just Google one

**Comment by democracycraft** [comment]
Yeah votifier isn't listening

**Comment by BenCodez** [comment]
Try a new port or host, make sure it can listen

**Comment by democracycraft** [comment]
Hi again.

I have tested it on a second port to no avail. 

Port: 25310

Host: 38.107.214.250

Public Key:
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAka5wq7T6BvzOcjEKO3/5NpcnfeLBnU5S8WH6Od6VHSdqO8yC6ovyzxIEODUTbqvPglNYLjYs4NbyU1UBuVajV/UZkO9xbnoBedOxmkCP+ik8Zl9hhWzL2NWuv9m+MYWWZggf1dU0d8r2QqzgawhJK8F5dCUqnS8EkZwsYlHKBRQWpcQwwyz4eTsmtEqX8w4wFhEA+9DFQnIU5EKM50fgW+aXbSmc6oE0zXv80LRI3oFKUzphn9fQRFEhqj/2BFqbBM+ggL44+0lb9h1wpktYRc1eQuj5YC8ykvPQwStOLgx49mc5RMgt5Tlk6UvStfqmJ6EsW+z/zzcgTnqbEnAv6wIDAQAB

**Comment by BenCodez** [comment]
Theres nothing I can do, it's a votifier issue t the moment
