### ISSUE TITLE
i cant get the rewards to work like for exemple vote keys

### ISSUE THREAD

**Issue by theunlucky1999** [BenCodez/VotingPlugin#738]
this is what i have and every time i try to ad a reward it wont activete 
VoteSites:
  minecraftservers_org:
    Enabled: true
    ServiceSite: https://minecraftservers.org
    VoteURL: https://minecraftservers.org/server/576871
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
     command:
      - 'crate key %playername% vote'
     Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  votemc:
    Enabled: true
    ServiceSite: https://votemc.com
    VoteURL: https://votemc.com/deadbushcraft.114/vote
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  minecraft-mp:
    Enabled: true
    ServiceSite: https://minecraft-mp.com
    VoteURL: https://minecraft-mp.com/server/248469/vote/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  craft-list_net:
    Enabled: true
    ServiceSite: https://craft-list.net
    VoteURL: https://craft-list.net/minecraft-server/deadbushcraft/vote
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by BenCodez** [comment]
Pastebin it.

**Comment by theunlucky1999** [comment]
> Pastebin it.

What does that mean

**Comment by BenCodez** [comment]
Copy and paste your file in here, then send the link

**Comment by theunlucky1999** [comment]
`VoteSites:
  minecraftservers_org:
    Enabled: true
    ServiceSite: minecraftservers.org
    VoteURL: https://minecraftservers.org/server/576871
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      command:
       - crate key %playername% vote
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  votemc:
    Enabled: true
    ServiceSite: votemc.com
    VoteURL: https://votemc.com/deadbushcraft.114/vote
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      command:
       - crate key %playername% vote
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  minecraft-mp:
    Enabled: true
    ServiceSite: minecraft-mp.com
    VoteURL: https://minecraft-mp.com/server/248469/vote/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      command:
       - crate key %playername% vote
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  craft-list_net:
    Enabled: true
    ServiceSite: craft-list.net
    VoteURL: https://craft-list.net/minecraft-server/deadbushcraft/vote
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      command:
       - crate key %playername% vote
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  `

**Comment by theunlucky1999** [comment]
https://drive.google.com/open?id=1-yAibKwBuFMIB9WZAABTgKxNvhm2ZNMB

**Comment by BenCodez** [comment]
Its Commands not command
