### ISSUE TITLE
Vote Reward Multiplier

### ISSUE THREAD

**Issue by farhaanlevy** [BenCodez/VotingPlugin#740]
I have a Server and on the Webstore i added a Option where players can Buy Vote point multipliers... They can instead of getting 1 vote point they get x2 or x5 for a month depending on what package they bought...Is there a way i can have this multiplier have effect? if there is Please tell me how, If not please add it i need something like this...

**Comment by BenCodez** [comment]
Use PlayerReceivePointsEvent and you can code it.

**Comment by farhaanlevy** [comment]
? Where is that?!?

**Comment by BenCodez** [comment]
In VotingPlugin?
