### ISSUE TITLE
Error in console upon setting enabled to true under cumulative rewards in config.yml file

### ISSUE THREAD

**Issue by ItsMatthewP** [BenCodez/VotingPlugin#741]
**Versions**
Plugin version: 5.20.8
Spigot version: paper 1.15.2
**Describe the bug**
The console gives me an error in the config.yml line 629 for me which is where I set "Enabled" to "true" for cumulative rewards. The error states that a block end was expected but a block mapping was started.

**To Reproduce**
`28.03 01:04:43 [Server] ERROR Cannot load plugins/VotingPlugin/Config.yml
28.03 01:04:43 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
28.03 01:04:43 [Server] INFO in 'string', line 629, column 5:
28.03 01:04:43 [Server] INFO Enabled: true
28.03 01:04:43 [Server] INFO ^
28.03 01:04:43 [Server] INFO expected <block end>, but found '<block mapping start>'
28.03 01:04:43 [Server] INFO in 'string', line 636, column 7:
28.03 01:04:43 [Server] INFO Messages:
28.03 01:04:43 [Server] INFO ^
28.03 01:04:43 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.YML.YMLFile.reloadData(YMLFile.java:91) ~[?:?]
28.03 01:04:43 [Server] INFO at com.Ben12345rocks.VotingPlugin.Main.reload(Main.java:1087) ~[?:?]
28.03 01:04:43 [Server] INFO at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$15.execute(CommandLoader.java:481) ~[?:?]
28.03 01:04:43 [Server] INFO at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:382) ~[?:?]
28.03 01:04:43 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
28.03 01:04:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
28.03 01:04:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
28.03 01:04:43 [Server] INFO Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
28.03 01:04:43 [Server] INFO in 'string', line 629, column 5:
28.03 01:04:43 [Server] INFO Enabled: true
28.03 01:04:43 [Server] INFO ^
28.03 01:04:43 [Server] INFO expected <block end>, but found '<block mapping start>'
28.03 01:04:43 [Server] INFO in 'string', line 636, column 7:
28.03 01:04:43 [Server] INFO Messages:
28.03 01:04:43 [Server] INFO ^
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.15.2.jar:git-Paper-143]
28.03 01:04:43 [Server] INFO ... 13 more
28.03 01:04:44 [Server] ERROR [VotingPlugin] Failed to load Config.yml`

**Expected behavior**
I expected to be able to use cumulative rewards?

**Screenshots/Configs**
https://gyazo.com/23a3dc3bd6ab5e6a4c6476316d635695

**Comment by BenCodez** [comment]
Pastebin your config

**Comment by ItsMatthewP** [comment]
Sure thing! https://pastebin.com/jceqU5KW

**Comment by BenCodez** [comment]
Rewards: 'ExampleBasic'
         Messages:
            Player: '&6&lYou voted twice in 1 day and received a vote key!'
            Broadcast: '&6&lPlayer &b%player% &6&l voted twice in the same day and received a vote crate key!'

You can't do that. YML can't understand that.

**Comment by ItsMatthewP** [comment]
Which part can I not do? Because I copy pasted this from the ExampleBasic reward file:
https://pastebin.com/cHda2eyd

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

You can't have the 'ExampleBasic' part.

**Comment by ItsMatthewP** [comment]
Okay so if I would like to use cumulative vote rewards I cannot use reward files. Got it, thanks

**Comment by BenCodez** [comment]
Well you can, just nothing under Rewards then.

**Comment by ItsMatthewP** [comment]
So if I set cumulative to true and on 2 votes, players will not receive the vote reward until they vote twice? How does the plugin know which reward file to execute?

**Comment by BenCodez** [comment]
Whatever you have under Rewards.

**Comment by ItsMatthewP** [comment]
But you just said don't put anything under rewards didn't you?

**Comment by BenCodez** [comment]
That's if you want to use a reward file.

https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

**Comment by ItsMatthewP** [comment]
So I can move the messages and commands that would otherwise be under "Rewards:" in the Cumulative section, into a reward file and under "Rewards:" put the file name?

**Comment by BenCodez** [comment]
Yeah.
