### ISSUE TITLE
How can i set command for cumulative rewards

### ISSUE THREAD

**Issue by flofydech502** [BenCodez/VotingPlugin#742]
**Versions**
5.20.8

**Relevant information**
  '15':
    Enabled: true
    # Wether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    VotesInSameDay: true
    VotesInSameWeek: false
    Rewards: 
      Messages:
        Player: '[lang]Cumulative.Rewards.Messages.player.vote[args][arg][cumulative][/arg][/args][/lang]'

**Context**
I would set a rewards by commands for cumulative rewards but i don't see the way to do it

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - command %player%
      Messages:
        Player: 'Messages'

**Comment by flofydech502** [comment]
Ok thank you a lot for this help ! 

I have another question i don't found a message in config. Look screen http://prntscr.com/rpgbgk 

The first message i have found it but not the second : " player's voted" can you say me where i can found it ? 

Thank you

**Comment by BenCodez** [comment]
Another plugin?

**Comment by flofydech502** [comment]
I don't know i have check all :/

**Comment by BenCodez** [comment]
There is no default message that says that (Atleast I'm sure). So that would be my guess

**Comment by flofydech502** [comment]
ok ok sorry for annoying you with this

Thank for help again

**Comment by flofydech502** [comment]
Hi, i have some website with 1h 30m delay of vote but when i set 1.5 in config of votesite it don't work :/ is it normal ? 

Thanks for help

**Comment by BenCodez** [comment]
There is no way to do that currently. 

I just tried to change it, see how it works:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by flofydech502** [comment]
Ok i have test it but the time are not correct.

i have set config like this https://onyxworld.fr/upload/notepad%2B%2B_RWZoPOsFuP.png

And the timer say me 57 min

**Comment by BenCodez** [comment]
Might need some work. Might need to separate votedelay to have a minute option.

**Comment by flofydech502** [comment]
Yes, i think it's better to do it like this. :)

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L37

http://ben12345rocks.com/job/VotingPlugin/

Added VoteDelayMin

**Comment by flofydech502** [comment]
I need to config like this     
VoteDelay: 1
VoteDelayMin: 30

Or i set the all time in minutes ?

**Comment by BenCodez** [comment]
That should work.

**Comment by flofydech502** [comment]
It say me again 1 hour before next vote.

I have set it like this 

https://onyxworld.fr/upload/notepad%2B%2B_4t1fGLHU4K.png

**Comment by BenCodez** [comment]
TimeUntilVote: '%hours% Hours and %minutes% Minutes'

You have that in the Config.yml?

**Comment by flofydech502** [comment]
Yes i have this

**Comment by BenCodez** [comment]
Where do you read the 1 hour from?

**Comment by flofydech502** [comment]
in the /vote when i pass my mouse on the website

**Comment by BenCodez** [comment]
Works fine for me.

Did you install the dev build?

**Comment by flofydech502** [comment]
yes

**Comment by BenCodez** [comment]
Redownload? Like I said it works fine for me.

**Comment by flofydech502** [comment]
maybe because i use version for 1.12.2 ?

**Comment by BenCodez** [comment]
That would do it.... It won't work on 1.12.

**Comment by flofydech502** [comment]
There is no way to update it for 1.12.2 ? :/

**Comment by BenCodez** [comment]
No.

From the plugin page:
Use v5.13.6 for 1.12 and older versions, support WILL NOT be provided for these versions, so please don't ask for support for these versions.
