### ISSUE TITLE
Problem with database

### ISSUE THREAD

**Issue by flofydech502** [BenCodez/VotingPlugin#743]
**Versions**
5.20.8

**Relevant information**
I have some vot in database with playername in nul. 
http://prntscr.com/rov1ti
**Context**
Database

**Comment by BenCodez** [comment]
You can ignore it. Null will default to 0 or whatever the default value is going to be.

**Comment by flofydech502** [comment]
Yes but i try to make a top vote on website and i have some problem .. 
Look here : https://onyxworld.fr/pages/vote/ 

Thanks for help

**Comment by BenCodez** [comment]
Edit the column to default value to 0
