### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Triviaplayer** [BenCodez/VotingPlugin#744]
I was just looking for some assistance setting up milestones on votingplugin. We want to make it so that players get a special reward on every interval of three votes, not neccessarily in a row. If anyone could offer any assistance that would be great!

**Comment by BenCodez** [comment]
Use cumulative rewards then. Milestones are one time rewards

**Comment by Triviaplayer** [comment]
Would you be able to give me an example of what to input in the config in order to get a specific item every three votes?

**Comment by BenCodez** [comment]
Cumulative:
      '3':
        Enabled: true
        Rewards: 
          Messages:
            Player: '&aYou got %cumulative% cumulative votes!'
          # Item/command here
