### ISSUE TITLE
Not A Bug Or Anything

### ISSUE THREAD

**Issue by noblecraft12** [BenCodez/VotingPlugin#745]
So I cant seem to find any kind of Answer. Been at this for awhile. Im Sure its simple but I just need sleep to see it. I have been told that I Only need Nuvotifier and VotingPlugin on my proxy server and VotingPlugin on all the rest . But I have also been told that in Configs for Proxy plugins/VotingPlugin/bungeeconfig.yml I need votifiers port aswell as the ips to other servers.

**Comment by BenCodez** [comment]
VotingPlugin has it's own communication system. Look in Config.yml
