### ISSUE TITLE
Service Site Not Matching

### ISSUE THREAD

**Issue by delbertina** [BenCodez/VotingPlugin#746]
**Versions**
5.21 & Paper 1.15.2 build 145
**Describe the bug**
Matching for service sites seems to get borked when the site sets it as their full URL. Does it require special escaping?

**Screenshots/Configs**
```
[Mon, 30. Mar 2020 18:39:15 CDT INFO] Received a vote from service site 'https://www.minecraft-servers-list.org/' by player '[redacted]'!
[Mon, 30. Mar 2020 18:39:15 CDT WARN] No voting site with the service site: 'https://www.minecraft-servers-list.org/'
[Mon, 30. Mar 2020 18:39:15 CDT WARN] Please read here on how to fix it: https://github.com/Ben12345rocks/VotingPlugin/wiki/Common-Problems
[Mon, 30. Mar 2020 18:39:15 CDT WARN] Current known service sites: MinecraftServers.org, MCSL, TopG.org, Minecraft-MP.com, PlanetMinecraft.com, Minecraft-Server.net, https://www.minecraft-servers-list.org/, TopMinecraftServers, MinecraftServersList, Serverlist.games, MC-Servers.com, MINEVOTES.COM
```

Have tried with no quotes around the service site also to no avail. 
```
  Site9:
    Enabled: true
    Priority: 18
    Name: 7-Minecraft-Servers-List.org
    ServiceSite: 'https://www.minecraft-servers-list.org/'
    VoteURL: [redacted]
    VoteDelay: 24
    Rewards:
    - IfOneReward
```

**Comment by BenCodez** [comment]
Hmm, that's new. Never seen a votesite use the full url. Not sure why they did that.

Try with double quotes "

**Comment by delbertina** [comment]
Changed to 
```
  Site9:
    Enabled: true
    Priority: 18
    Name: 7-Minecraft-Servers-List.org
    ServiceSite: "https://www.minecraft-servers-list.org/"
    VoteURL: [redacted]
    VoteDelay: 24
    Rewards:
    - IfOneReward
```
and same error unfortunately.

**Comment by BenCodez** [comment]
Use \ to escape : and - (in front of each of those) I think that should do it. If not look up how to escape that. There is a few ways of doing it.

**Comment by delbertina** [comment]
I'm not able to get the escaping to fix the issue from your suggestion. Googling brings up that the double quotes should work, but also that no quotes or escaping should also work which is very weird. 

If it helps in troubleshooting, doing `/av servicesites` shows all of the other ones configured as "Current site = X" but the one having an issue says `No site with this service site, did you do something wrong?` next to it. I'm not sure if that helps, but found that in trying to troubleshoot myself

**Comment by BenCodez** [comment]
YML is probably reading it weird. I don't know a good way around it.
