### ISSUE TITLE
Cant get the plugin to give cash reward.

### ISSUE THREAD

**Issue by cole3050** [BenCodez/VotingPlugin#747]
**Versions**
Paper bukkit, fully up to date.

**Relevant information**

VoteSites:
  PebbleHost Vote Tester:
    Enabled: true
    ServiceSite: PebbleHost Vote Tester
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      commands:
        Console:
        - say %player% voted and received $200
        - eco give %player% 200
      Messages:
        Player: '&aTesting this plugin is less painful on %ServiceSite%!'

**Context**
Cant seem to get plugin to give money as a reward even following examples online and trying to understand the wiki.

**Comment by BenCodez** [comment]
Pastebin?
