### ISSUE TITLE
Not turning red after voting

### ISSUE THREAD

**Issue by slvlr** [BenCodez/VotingPlugin#748]
**Versions**
Voting Plugin 5.21
Tuinity 1.15.2

**Relevant information**
Config: https://pastebin.com/R406hYTQ
Vote Sites: https://pastebin.com/kTr818Rb
Server Info: https://pastebin.com/yxxaPXhA

**Context**
The vote is registering and I am getting the key however this one link stays as an Emerald block and does not turn into redstone after voting. How can I fix this please? 

I thought it may have had something to do with the https:// but when I try to remove this, the server still doesn't go red and then it creates a duplicate URL one. 
https://gyazo.com/e5e6b0e8698f5d539b60191176629d72

**Comment by BenCodez** [comment]
https://pastebin.com/1rcQdYPy

That work?

**Comment by slvlr** [comment]
@Ben12345rocks 

It removes the Https but it does not go red. It still stays green after voting?

**Comment by BenCodez** [comment]
Is the server getting the vote? Check console.

**Comment by slvlr** [comment]
Hi @Ben12345rocks The server is getting the vote, it is executing the broadcast command, giving the player $500 and the vote crate key.

**Comment by BenCodez** [comment]
Wanna show me the log when that happens?

**Comment by slvlr** [comment]
@Ben12345rocks 
Now none of the links are turning red since I did the change you suggested. Strange.
This is the log. (I voted on the second emerald block in)
https://gyazo.com/86e9ed940660890d1697e03ee75f3a51


>.... [18:05:46 INFO]: [Votifier] Got a protocol v1 vote record from /192.99.101.31:34628 -> Vote (from:TopG.org username:Rangewonk address:2.30.186.49 timeStamp:1585929947 localTimestamp:1585929946772)
>.... [18:05:46 INFO]: [VotingPlugin] Received a vote from service site 'TopG.org' by player 'Rangewonk'!
>.... [18:05:46 INFO]: (!) Rangewonk has voted for the server! Use /vote to vote
>.... [18:05:46 INFO]: SUCCESS! Given physical key for crate: Vote
>.... [18:05:46 INFO]: CONSOLE issued server command: /eco give Rangewonk 500
>.... [18:05:46 INFO]: $500 added to [Owner] Rangewonk account. New balance: $656,767.99
>.... [18:05:46 INFO]: Logged "Rangewonk"

**Comment by BenCodez** [comment]
What does /vote next show?

**Comment by slvlr** [comment]
They are all redstone blocks now... Maybe I didn't restart the server properly earlier I am not sure...
Seems to have fixed itself new though, thank you. I'll re-open if it happens again.
