### ISSUE TITLE
An option to customize the GUI of today's voters

### ISSUE THREAD

**Issue by ChrisTaylor201** [BenCodez/VotingPlugin#749]
Since the names and the lores of the player heads in this GUI are currently hard coded, see [the code](https://github.com/Ben12345rocks/VotingPlugin/blob/a44070b5051bb138b036ae76a2ea0749be4aa9fe/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/Commands/GUI/PlayerGUIs.java#L459-L460), it would be great if they were customizable.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L235

http://ben12345rocks.com/job/VotingPlugin/

Give it a try.

**Comment by ChrisTaylor201** [comment]
Thank you very much, it works as intended! I appreciate the speed of your response.

I don't want to bother you with negligible details, but would it also be possible to change the names (titles) of the player heads or at least the formatting codes? They're currently formatted as `&e&o` – it would be wonderful if there was an option to customize them, too.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L449

I moved the other option down with that one.

http://ben12345rocks.com/job/VotingPlugin/

**Comment by ChrisTaylor201** [comment]
I think you've forgot to add dots to the [paths](https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/Config/Config.java#L323-L329) because it showed `YamlConfiguration[path='', root='YamlConfiguration']` instead.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I did :)

**Comment by ChrisTaylor201** [comment]
Now it's perfect – I appreciate your effort, thank you once again!
