### ISSUE TITLE
How to edit the reward shop

### ISSUE THREAD

**Issue by danny1jiang** [BenCodez/VotingPlugin#750]
Version:
1.12.2 Spigot

Question:
How do I edit the reward shop section without BossShop? I am on 1.12 so it is not compatible. 

Explanation: 
How do I edit the items in the reward shop that can be bought with vote points? I see that the features of the reward shop can be expanded with the BossShop plugin, but I can't install that on my server. I am on Spigot 1.12.2

**Comment by BenCodez** [comment]
Just edit it in the config.yml
