### ISSUE TITLE
Title Delay

### ISSUE THREAD

**Issue by FourDown** [BenCodez/VotingPlugin#751]
Add a configureable delay for reminder titles to allow for other title plugins to display their messages

**Comment by BenCodez** [comment]
You could add a delay to the reward, or disable the title.

**Comment by FourDown** [comment]
I'd like to use the titles, they're pretty annoying so they're likely to increase votes.

As to adding delay to the reward, I'm unsure of how that effects reminders on join?

**Comment by BenCodez** [comment]
The vote reminding runs a reward to remind, so it would delay that.

https://pastebin.com/ZZE3pDRG

**Comment by FourDown** [comment]
What's your Discord?

**Comment by BenCodez** [comment]
I don't like to use discord.

**Comment by FourDown** [comment]
Okay, might as well ask here then. How can I stop users from seeing voting broadcasts after voting on all 5 sites, but then have them start seeing them again once they can vote again?

**Comment by BenCodez** [comment]
That's not possible at the moment.

**Comment by FourDown** [comment]
One of the examples says you can give perms and take them away 10 mins later.

How come I can't make a reward that will give the perm and make them run the command, then another to do the opposite 24 hours later?

**Comment by BenCodez** [comment]
If you want to do that, go ahead.

**Comment by FourDown** [comment]
Could you demonstrate it?

**Comment by BenCodez** [comment]
https://pastebin.com/h7A4WbCn
