### ISSUE TITLE
Possible bug dont want to get your hopes up is probably just config issue.

### ISSUE THREAD

**Issue by johncsuti** [BenCodez/VotingPlugin#752]
**Versions**
Plugin version and spigot version
Plugin: 5.21
Spigot: git-Paper-155 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Relevant information**
Configs that relate to the issue in a pastebin.
https://pastebin.com/gMV5wiBh

**Context**
Context about the question/concern
RewardInject Validator: vote, Directly Defined: false Path: Messages.Player : No player message set
RewardInject Validator: vote, Directly Defined: false Path: Messages.Broadcast : No broadcast was set

**Comment by BenCodez** [comment]
You have a blank message set?

**Comment by johncsuti** [comment]
Should that be warning console about that though? I was also getting a message after I set EXP to be 0 instead of removing it all together.

**Comment by BenCodez** [comment]
If you don't need it then just remove it. You could also just ignore it

**Comment by johncsuti** [comment]
Okay I was wondering if removing it would silence it. Sorry if that wasn't clear. I don't like things nagging in console personal preference I guess. :/

**Comment by johncsuti** [comment]
Also thanks for the quick reply!
