### ISSUE TITLE
/votetop monthly didn't reset

### ISSUE THREAD

**Issue by Sotlol1** [BenCodez/VotingPlugin#753]
**Versions**
Version: 5.21
Server: Paper 1.15

**Describe the bug**
/votetop monthly didn't reset but monthly rewards were given correctly. Server time says 6th April so the server time is correct.

**Expected behavior**
Excpected it to reset to 0.

**Screenshots/Configs**
Config: https://pastebin.com/K5g6yYbJ

**Additional context**
I did "/av forcetimechanged month" to reset it manually but then they got double the rewards.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should be fixed in that build. There should be an error on the first day of the month on the log.
