### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [BenCodez/VotingPlugin#754]
Voting plugin: 111
Votes get processed and appear correctly but the reward commands never get send.
https://pastebin.com/raw/BZH4ryL1

**Comment by BenCodez** [comment]
Bungee voting isn't setup correctly

**Comment by LucidAPs** [comment]
But vote processing and notifications appear correctly in all server consoles, the rewards just don't trigger. Maybe i should increase the MaxConnections ?

**Comment by BenCodez** [comment]
Disable usebungeecord and bungeebroascast

**Comment by LucidAPs** [comment]
Em lol yeah that fixed it, i don't understand why though. They are part of the bungee network, oh well. Thank you.

**Comment by BenCodez** [comment]
You would need to use VotingPlugin on bungee for that bungee stuff

**Comment by LucidAPs** [comment]
I do have it on Bungee though, hhmmm :/

**Comment by BenCodez** [comment]
Then your not using that setup. Your using votifier to forward the votes
