### ISSUE TITLE
Bungeecord - Getting 1 vote per Spigot server, have more votes than intended.

### ISSUE THREAD

**Issue by africsnail** [BenCodez/VotingPlugin#755]
**Versions**
Latest Paper Spigot + Waterfall

I have a three Spigot + 1 Bungee server configuration. I use MySQL as a storage for this plugin.
The Plugin works well. Only thing is that I get the votes on every single Spigot server, so if I vote once and join all the Spigot servers I actually get 3 votes instead of 1.

Any clues?

Thank you

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by africsnail** [comment]
> https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

Already done that all

**Comment by BenCodez** [comment]
Did you set it to send to one server?

**Comment by africsnail** [comment]
> Did you set it to send to one server?

No, because I want every server to notify the players that they voted, but at the same time want to get 1 vote per vote and not 3.

If I set it to send to just one server then I will get the desired one vote, but on the other hand I won't get notified at all on the other 2 servers, Right?

**Comment by BenCodez** [comment]
It does broadcast to each server.

**Comment by africsnail** [comment]
Ok, thanks.
What about the "thanks for vote" message, I set up in the VoteSites.yml file, is that also a broadcast?

**Comment by BenCodez** [comment]
No, just a player message.

**Comment by africsnail** [comment]
Then that won't show up on the other two servers, right?

**Comment by BenCodez** [comment]
no

**Comment by africsnail** [comment]
:/

**Comment by africsnail** [comment]
Will have to live with just the broadcast then

**Comment by BenCodez** [comment]
That message won't show on the other servers.

**Comment by africsnail** [comment]
Yes I know. Will have to not use the message for consistency then

**Comment by africsnail** [comment]
The 3 servers are equally important

**Comment by africsnail** [comment]
Well, that about sums my question. If I could request a feature I would request these messages working across all the servers. But I reckon it isn't possible.

Thanks

**Comment by BenCodez** [comment]
Yeah, that's not really possible.
