### ISSUE TITLE
Lots of timings on login

### ISSUE THREAD

**Issue by mrunningmasterc** [BenCodez/VotingPlugin#756]
**Versions**
Plugin version and spigot version.

5.21, latest paper 1.15.2

**Describe the bug**
Hi, so votingplugin is creating a lot of timings for me on player login for paper 1.15.2
Timings: https://timings.aikar.co/?id=37af6a0c731340eba9495121184a67f3

**To Reproduce**
1. Go to 'join and relog a bunch of times on paper 1.15.2 with the lastest version of essentials'
2. Click on 'Checking Timings'
3. See errors 'should be- VotingPlugin::Event: c.B.V.L.PlayerCommandSendListener'

**Expected behavior**
Lags the server when a player joins..

**Screenshots/Configs**
Timings: https://timings.aikar.co/?id=37af6a0c731340eba9495121184a67f3

**Additional context**
none

**Comment by BenCodez** [comment]
# Disable checking permissions on tab complete
    DisableAdvancedTab: false

Enable that
