### ISSUE TITLE
Broadcast blacklist

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#757]
**Is your feature request related to a problem? Please describe.**
The broadcast "Player123 has voted on vote site 1" is like an advertisement and a reminder for other players to vote for our server. This works fine.
Sometimes we have players with unpleasant names containing swears. If they are real players that play nicely at our server, they get a nickname. However, they still have to vote under there real name. This means that everybody on the every server see the "Thanks swearingplayer for voting" message. This can upset players if the curse is really bad.

**Describe the solution you'd like**
I want to block or alter the broadcast messages in some cases.
Possible options:
- `Thanks %nickname% for voting on %SiteName%` in this case votingplugin should lookup the nick name for this real name (CMI or Essentials or any nick plugin). I don't think this will work(?)
- Blacklist command to blacklist certain names. Voting plugin should lookup the real name in a blacklist. If the realname is on the blacklist, broadcast an alternative broadcast, eg, like: `Thanks "someone" for voting on %SiteName%`

**Describe alternatives you've considered**
Filter the broadcast with my chat filter (ChatControl)

**Additional context**
-

**Comment by BenCodez** [comment]
You should already be able to put %nickname% on there. Will default to player name if there is no nickname.

**Comment by x1p** [comment]
I tried `%cmi_user_nickname%` but that one didn't work

**Comment by BenCodez** [comment]
use %nickname%

**Comment by x1p** [comment]
Ok, tried %nickname%. However this shows the real name and not the CMI nickname.

**Comment by BenCodez** [comment]
Hmm. Does it work with essentials nickname? It should.

**Comment by x1p** [comment]
I don't use essentials. I use CMI. CMI has a few placeholders which are usable in other plugins too. https://www.zrips.net/cmi/placeholders/

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Try using some placeholderapi placeholder, should work.

**Comment by x1p** [comment]
Unfortunately this doesn't work 100%
When the player (with or without nick) is online, it works with the cmi placeholder `%cmi_user_display_name%`
When the player is not online, the placeholder is not resolved, leaving a gap ("Thanks  for voting").
`%cmi_user_nickname%` only returns something when a player has a nick, so this is also no option.

**Comment by BenCodez** [comment]
That would be a cmi issue then.

**Comment by x1p** [comment]
Hmm so it seems

**Comment by BenCodez** [comment]
I might look at a blacklist

**Comment by x1p** [comment]
That would be awesome

**Comment by BenCodez** [comment]
# Playernames to not be broadcasted when voting
    # case sensitive
    VotingBroadcastBlacklist: []

http://ben12345rocks.com/job/VotingPlugin/

**Comment by x1p** [comment]
With what will it be replaced then?

**Comment by BenCodez** [comment]
Nothing, just prevent the broadcast.

**Comment by x1p** [comment]
Ok, will test it

**Comment by x1p** [comment]
I assume it must be writen like:
```
VotingBroadcastBlacklist:
- Player123
```
Tested it with the command `/av Vote Player123 1` and it was still broadcasted.

**Comment by BenCodez** [comment]
Made a typo:
http://ben12345rocks.com/job/VotingPlugin/

Should work now.

**Comment by x1p** [comment]
Works. The player executing the av vote command to test the broadcast gets `Possible issue with service site, has the server gotten the vote from 1?`
I assume this is a default message? I couldn't get a test setup working fast enough with votifier to really test it.

**Comment by BenCodez** [comment]
That's because the server hasn't gotten a vote from votifier from the service site "1".

**Comment by x1p** [comment]
I'll put it on the production servers and let you know how it went
Many thanks in advance

**Comment by x1p** [comment]
Works awesome
Thank you very much.
