### ISSUE TITLE
I cannot set up the rewards. I'm have a very difficult time :(. 

### ISSUE THREAD

**Issue by banejryan** [BenCodez/VotingPlugin#759]
So, I set up my votifier, and have tested that the votes go through. When I went to set up the rewards I had a very difficult time. 
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: &b https://minecraftservers.org/vote/579511
    VoteDelay: 24
    Rewards:
    - 'ExampleBasic'
  Minecraft-MP_com:
    Enabled: true
    ServiceSite: Minecraft-MP.com
    VoteURL: &b https://minecraft-mp.com/server/251246/vote/
    VoteDelay: 24
    Rewards:
    - 'ExampleBasic'
This is what I have in the votesites .yml. I set up everything I wanted in the examplebasic rewards folder. I even got the rewards in the examplebasic when I forcevoted the rewards. I've tried several with test accounts that voted. No one gets the rewards,  but the vote does go through. pls help.

**Comment by BenCodez** [comment]
1. What rewards? 
2. Don't use the examplebasic reward file as a reward, it will not work.
3. https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

**Comment by banejryan** [comment]
@Ben12345rocks so should I make a new file?

**Comment by BenCodez** [comment]
Just put the rewards under Rewards in the votesites.yml, you don't need to create a file unless you really want to. Look at that wiki page.

**Comment by banejryan** [comment]
@Ben12345rocks I tried putting the rewards under rewards in the votesites.yml, and it didn't work. I tried doign it for like 2 hours and it just wouldn't work.

**Comment by BenCodez** [comment]
Send what you had?

**Comment by banejryan** [comment]
https://gyazo.com/1628e72c9a1937c3320a5548d82335d1

**Comment by BenCodez** [comment]
https://pastebin.com/1d3mSE0U

have that in the votesites.yml, under Rewards.

**Comment by banejryan** [comment]
is there a way to test a vote without having someone to actually vote

**Comment by banejryan** [comment]
you're a life saver. thank you :D
