### ISSUE TITLE
Purchase Confirmation

### ISSUE THREAD

**Issue by kakduman** [BenCodez/VotingPlugin#760]
My server only refunds voteshop purchases if someone requests a refund within 24 hours. Unfortunately, there seems to be no way to ensure that players know this when they purchase an item.

It'd be really nice if VotingPlugin had a feature that asked "Are you sure you want to purchase this item?" and had users respond either by selecting "Yes" in a gui, or by typing a command similar to /voteshop confirm. Taking this one step further, it'd also be nice if the confirmation message was customizable, but customizability isn't absolutely necessary.

**Comment by BenCodez** [comment]
Not sure if bossshop can do this already, but I can look at it.

**Comment by kakduman** [comment]
I believe it's possible on BossShop, but just a simple confirmation to the built-in /voteshop would be very convenient if it's an easy addition.

**Comment by BenCodez** [comment]
It's a little bit of work, might add it when I get around to it.

**Comment by BenCodez** [comment]
VoteShopRequireConfirmation: false

http://ben12345rocks.com/job/VotingPlugin/

Untested, give it a try.

**Comment by kakduman** [comment]
Thanks for adding it! It doesn't seem to work. I tested it both on my server and a test server that used the default config (with the VoteShopRequireConfirmation set to true).

**Comment by BenCodez** [comment]
Works for me. I made it rebuild the jar.

http://ben12345rocks.com/job/VotingPlugin/

**Comment by kakduman** [comment]
Updated to build 134 and it's working! I think the feature could be improved if it asked "Are you sure you want to purchase this?" with the responses "Yes" and "No" instead of the current "True" and "False."

Thanks again for the addition!

**Comment by BenCodez** [comment]
I'll look at it. I used my builtin api to request values because I was lazy.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

How's that?

**Comment by kakduman** [comment]
Sorry for the late response, it looks great! Thank you for the continued support. One last request to finish it up, though: can you change &c to &a for the "Yes" in the confirmation message on line 387?

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

How's that?

**Comment by kakduman** [comment]
Looks great! Thanks for the changes!
