### ISSUE TITLE
Votingshop LimitPerDay

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#763]
A new limit option for voting shop items where you can limit players to only being able to buy X amount per day, and it then resets the limit every day.

**Comment by BenCodez** [comment]
I'll look at it.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Added resets for voteshop limit
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L598

**Comment by DrakePork** [comment]
Would it be possible to make it per item based?

**Comment by BenCodez** [comment]
It is.

**Comment by DrakePork** [comment]
ooohh, I just read the config incorrectly ;p
