### ISSUE TITLE
Only executing one reward file

### ISSUE THREAD

**Issue by Casper2416** [BenCodez/VotingPlugin#764]
I am using VotingPlugin 5.21.1 and PaperMC 1.15.2 183 and LuckPerms

VoteSites: https://pastebin.com/b1uB3KCM

Rewards for non-vip users: https://pastebin.com/wvyfFNKM
Rewards for Twitch Subscribers (Vip's): https://pastebin.com/C3tVqLFk

I want to know how I can make it so only one reward file is executed.I am not geting my rewards when doing a test vote. When testing I had my default rewards working. So I added a voting.default premission to my default rewards so Twitch Subs wouldn't get 2 rewards. I placed myself in my twitch group and now nothing is working. Can somebody help me out

Thanks!!
- Casper

**Comment by BenCodez** [comment]
You need either permission for it to work.

**Comment by Casper2416** [comment]
> You need either permission for it to work.

I am sorry but I do not understand what your are say. Can you please reprase that??

**Comment by BenCodez** [comment]
The permissions you set to be required for either reward. You need to have that.

**Comment by Casper2416** [comment]
For each reward?? I at least have it for the rewards they need to get (Twitch = Twitch.yml, Default Users = Default.yml

**Comment by Casper2416** [comment]
> The permissions you set to be required for either reward. You need to have that.

But if I have premission for the premium rewards. Do I get the premium rewards??

**Comment by BenCodez** [comment]
You have:

    RequirePermission: true
    Permission: voting.default

and

    RequirePermission: true
    Permission: voting.twitch

I'm not sure what your problem is other than that. You need one of these permissions to get the reward.

**Comment by Casper2416** [comment]
> You have:
> 
> ```
> RequirePermission: true
> Permission: voting.default
> ```
> 
> and
> 
> ```
> RequirePermission: true
> Permission: voting.twitch
> ```
> 
> I'm not sure what your problem is other than that. You need one of these permissions to get the reward.

Huh... Very strange. I have to go now ( Here in the Netherlands it's bad time. ) Thank you for your quick response!! Have a good day sir!!

- Casper
