### ISSUE TITLE
One voting site working, other isnt (spacing issue?)

### ISSUE THREAD

**Issue by TheHumdrum** [BenCodez/VotingPlugin#765]
**Versions**
5.21.1 version 1.15.2 paper

**Relevant information**
https://pastebin.com/0gLFMtcZ

**Context**
The first voting site (mcserverlist.com ) is working, but the second one does not come up

**Comment by BenCodez** [comment]
Delete the advanced priority part?

**Comment by TheHumdrum** [comment]
you're a god, thanks for the quick reply. i hate how specific "coding?" is in config files for plugins, so nitty picky
