### ISSUE TITLE
Can't use obsidian or a enchanted golden apple as a reward in my rewards file

### ISSUE THREAD

**Issue by Casper2416** [BenCodez/VotingPlugin#766]
I am using VotingPlugin 5.21.1 and PaperMC 1.15.2 183

I can't use the material Id for obsidian and a enchanted golden apple

Can I get some help??

Thank you!!
- Casper

**Comment by BenCodez** [comment]
Use the right material name?

**Comment by Casper2416** [comment]
I am using obisidian for the material name and I think the enchanted golden apple just has the normal golden apple material name but with a :1 data tag

**Comment by BenCodez** [comment]
Send what your using?

**Comment by Casper2416** [comment]
Nevermind just fixed it. Thank you for your time!! :)
