### ISSUE TITLE
How to divide rewards into different ranks?

### ISSUE THREAD

**Issue by Tauses** [BenCodez/VotingPlugin#767]
**Versions**
Latest version of Plugin and Spigot

**Relevant information**
I haven't configured it yet.

**Context**
How do I give VIP's more voting cash than regular players?

**Comment by BenCodez** [comment]
Rewards:
      AdvancedPriority:
        Reward1:
          RequirePermission: true
          Permission: 'permhere'
          # Rewards....
        Reward2:
          # Non vip rewards
