### ISSUE TITLE
Problem with vote point

### ISSUE THREAD

**Issue by flofydech** [BenCodez/VotingPlugin#769]
Versions
spigot : 1.12.2 votingplugin : 1.12.2

Describe the bug
Some problem in database i have some player with a big amount of vote points

Expected behavior

**Screenshots/Configs**.
https://onyxworld.fr/upload/chrome_YmxLTACOP1.png

Thank you for help

**Comment by BenCodez** [comment]
1. Spigot 1.12 isn't supported, read the plugin page
2. 1.12.2 isn't a plugin version

**Comment by flofydech** [comment]
https://onyxworld.fr/upload/chrome_deEWM4B37J.png 
I use exactly this version like you recommand

**Comment by BenCodez** [comment]
Yes, any bugs/issues there is nothing I can do about it. There is no support.
