### ISSUE TITLE
/vote does not display enabled in VoteSites.yml

### ISSUE THREAD

**Issue by SupaYoshi** [BenCodez/VotingPlugin#770]
**Versions**
VotingPlugin 5.21.1 / Spigot 1.15.2

**Relevant information**
Config.yml https://paste.ubuntu.com/p/ccsMdX2fhj/
VoteSites.yml https://paste.ubuntu.com/p/bvtmCCFNB9/
**Context**
Context about the question/concern
What am i doing wrong, when typing /vote, it just outputs , "Vote for United Factions" and the site MCserverlist is not displayed in a list.

**Comment by BenCodez** [comment]
Your gonna have to provide more details.

**Comment by SupaYoshi** [comment]
What do you need? :) Haha

**Comment by BenCodez** [comment]
Console logs?
