### ISSUE TITLE
Can you give extra vote points as a reward by chance?

### ISSUE THREAD

**Issue by TheLastBlockbender** [BenCodez/VotingPlugin#771]
**Versions**
Votingplugin: 5.21.1
Paper version git-Paper-194 (MC:1.15.2)

**Context**
Pretty much exactly what the title says. I'm trying to create a rather basic reward system that has a chance to give extra vote points for a vote shop. How would I do that? I looked at the wiki and didn't see much regarding this. I guess I could do an admin command that gives you extra points? I thought I might be missing something. Thanks!

**Comment by BenCodez** [comment]
Just a reward with something like this:
  
    Chance: 50
    Points: 5
