### ISSUE TITLE
Error Spam in console

### ISSUE THREAD

**Issue by Zeus-MC** [BenCodez/VotingPlugin#772]
**Versions**
Plugin version and spigot version.
1.15.2 - 5.21.1
**Describe the bug**
https://pastebin.com/Uiashn7F
**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Your on 5.21, update.
