### ISSUE TITLE
Address already in use (Bind failed)

### ISSUE THREAD

**Issue by Forsetinn** [BenCodez/VotingPlugin#773]
**Versions**
Voting Plugin 5.21.1
Spigot 1.15.2-R0.1-SNAPSHOT

**Relevant information**
I am running BungeeCord Network and on a single dedicated machine with 3 servers (All Same IP)
I'm not getting any broadcasts through but the votes do work.
Console log:
https://pastebin.com/mmVGsKeR

Config.yml
https://pastebin.com/h0L580L8

**Context**
All of my votes do go through successfully. But I'm having issues with this. Also the broadcast stopped showing up.

**Comment by BenCodez** [comment]
Address already in use (Bind failed)

Change the address... new port would do it.

**Comment by Forsetinn** [comment]
New port didn't work.

**Comment by BenCodez** [comment]
What did you change?

**Comment by Forsetinn** [comment]
Okay, I was following tutorials on YT and all of them said to install VotingPlugin ONLY on the Spigot servers, Then I looked into the Github wiki and says to install on Spigot+Bungee servers. I'm testing this.

**Comment by BenCodez** [comment]
The youtube videos won't go by the first method.

**Comment by Forsetinn** [comment]
One question. I don't see this documented but what does `FallBackServer: `do?

**Comment by Forsetinn** [comment]
Still get the same error. The ports for the config.yml and bungeesetup.yml the actual servers port or the votifier ports?

**Comment by BenCodez** [comment]
The error you sent before was the port on the spigot server for votingplugin.

**Comment by Forsetinn** [comment]
I am using completely different ports. I'm still getting this error.

**Comment by Forsetinn** [comment]
I boot Proxy and 1 spigot server. When I boot the second spigot server I get address in use. Does it require more than just a different port? Is it talking about the actual IP? I can't do that because I'm runnin this on one machine.

https://pastebin.com/aTsF9zYy

**Comment by BenCodez** [comment]
Each spigot server needs a port.

Fallbackserver just incase it needs to fallback to a server

**Comment by Forsetinn** [comment]
I set each spigot server port to 1297 - 1301 and I'm still getting the error.
bungeeconfig.yml: https://pastebin.com/K4Qy9MBx
Spigot #1 Lobby: https://pastebin.com/yu5P9Qyd
Spigot #2 SMP: https://pastebin.com/YFeTZfVF

/votingpluginbungee vote player site returned this if this is unrelated or not.
https://pastebin.com/kBEAC8wL

**Comment by BenCodez** [comment]
This is what it looks like on the spigot configs, or how it should look like.

    # --------------------------
    # Bungee Setup 
    # Only if using votingplugin bungee to send votes
    # REQUIRES RESTART FOR CHANGES TO TAKE EFFECT
    # --------------------------

    # Plugin using bungee, requires plugin on bungee server
    UseBungeecoord: false

    # Get the plugin to broadcast to all servers
    BungeeBroadcast: false

    # What server this is in bungee (must match)
    # Also can be applied to rewards
    Server: PleaseSet

    # Bungee communication, add bungee host/port here
    BungeeServer:
      Host: '127.0.0.1'
      Port: 1297
      
    # Bungee communication, add this to bungee server
    SpigotServer:
      Host: '127.0.0.1'
      Port: 1298

**Comment by Forsetinn** [comment]
use bungee and broadcast false?
Is it just one SpigotServer: on each spigot config?. It also didn't work.

**Comment by Forsetinn** [comment]
I even removed all `SpigotServers:` and I still get the error. Also when removing `BungeeServer:` in spigot config, I still get the error. Also removed all servers listed every spigot config including Bungeeconfig error still persists. I'm starting to get convinced that this is a bug.

**Comment by BenCodez** [comment]
I think you mixed up the configs from bungee with spigot.

What I sent you is all for the sockets on 1 spigot server. (Set those values to true)

**Comment by Forsetinn** [comment]
Aaah, It works!. This was a little confusing because it was in plural. SpigotServer's': So I thought I had to add every server in the Spigot Config. It broadcasts for every website Can it be set so it only broadcasts when a user has voted on all sites?

**Comment by BenCodez** [comment]
Disable the bungee broadcast and add a broadcast on AllSites reward.

**Comment by Forsetinn** [comment]
Nice thank you.
