### ISSUE TITLE
Console error on inital startup

### ISSUE THREAD

**Issue by Stormrunn3r** [BenCodez/VotingPlugin#774]
**Versions**
Plugin version and spigot version.
Plugin: 5.21.1
Waterfall: git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327

**Describe the bug**
Wen the server starts only with "NuVotifier" and "VotingPlugin" enabled votingplugin spits out this error. The server is hosted on a Pterodatyl container in a Pterodactyl network.

**To Reproduce**

**Expected behavior**
Plugin starts up without any issues, or maby states that something is wrong in the config.

**Screenshots/Configs**
https://paste.projectdev.org/aroxutuxor.groovy

**Additional context**
It could be that the plugin needs a special port open, but this is not stated in the doc's or guides.

**Comment by BenCodez** [comment]
Plugin can't connect to mysql

**Comment by Stormrunn3r** [comment]
Fixed! Thanks for the quick response.
