### ISSUE TITLE
Not all top level domains seem to be supported

### ISSUE THREAD

**Issue by unisteven** [BenCodez/VotingPlugin#775]
**Versions**
All versions

**Describe the bug**
When you list websites ending in .com or .net is handels them fine and they are clickable from the menu
However when you try to use a top level domain such as .games it wont be clickable.

This isn't an issue with Minecraft itself since it does work with some other plugins and it does work when sending the url in chat. 

**To Reproduce**
Add the following website "https://serverlist.games/vote/2652"  to the config as a voting website and try to click on it when using /vote It wont be clickable.

**Expected behavior**
A clickable url no matter what the domain is.

**extra**
I'm the owner of that website and have received multiple complaints about this bug telling me the website itself is not working. So I thought lets file a bug report in the hope it can get fixed :)

**Comment by BenCodez** [comment]
They can just set this as the url:

    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'

**Comment by unisteven** [comment]
Yeah but that isnt what most people would do, they just expect it to work. This is a fine work arround if it was an isolated case but it is happening quite often, isnt is possible to check for this in de code?

**Comment by BenCodez** [comment]
Could, but I currently rely on minecraft to handle urls. Haven't received enough complaints to change it yet since I have that workaround.

I'll add it for the next update.

**Comment by unisteven** [comment]
Nice, if you'd want to I could try to make a fix and make a pull request for it

**Comment by BenCodez** [comment]
Nah, I'll do it.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

https://github.com/Ben12345rocks/VotingPlugin/commit/bef017c12d9faf3e9084c896b96147b95b6b58da

I decided to go with a config option. I can think of a few cases to where always forcing the url could cause trouble, so gonna try this and see how that works out.

**Comment by unisteven** [comment]
Thank you for the update, however I have some doubt about ho effective this is going to be. It still requires alteration of the config and it isn't an option that is obvious to set to true when you notice the url is not working. From my experience most just blame it on the website and remove the url. Since this problem isn't happening with many website but mostly in particular mine. Would it be possible to make a 'hacky' solution that checks for .games domains and then forces the config? Checking for a negative might be a better option: if it is not '.com, .net etc' force it.

**Comment by BenCodez** [comment]
Changed it so the default option is true.

**Comment by unisteven** [comment]
Hello, I see the issue has indeed been resolved however there is still one problem left I have demonstrated that in this video: https://www.youtube.com/watch?v=PPrDaCYToWs 

It seems that the url is not being forced on the entire list.

**Comment by BenCodez** [comment]
Hmm, will need to do some testing later.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should be solved.

**Comment by unisteven** [comment]
Tested it, and yes it has been resolved! Thank you.
