### ISSUE TITLE
VoteReminding

### ISSUE THREAD

**Issue by gazdyy** [BenCodez/VotingPlugin#776]
**Versions**
VotingPlugin: 5.21.1

**Relevant information**
I would like to set VoteReminding to send a notification every 5 minutes to a player who can vote and has not voted yet for the last 2 hours as I have set on the voting site

**Comment by BenCodez** [comment]
Then set it? You can't really do the the 2 hours though.

**Comment by gazdyy** [comment]
Should this work every 2 hours or how do I set it up? And how can it be set if not for 2 hours?
my config: https://pastebin.com/HnQAuLhD

**Comment by gazdyy** [comment]
solved
