### ISSUE TITLE
Multiple rewards for each site.

### ISSUE THREAD

**Issue by Forsetinn** [BenCodez/VotingPlugin#777]
**Versions**
Plugin v5.21.1 Spigot 1.15.2

**Describe the bug**
Players keep getting duplicate rewards and for each site voted on (Supposed to be when voted on each site. (Running bungee setup)

**To Reproduce**
1. Voted on site. Gets reward for `EverySiteReward:`
2. Gets rewarded 2-3 times for each site.
3. No errors in logs.

**Expected behavior**
Only get rewarded for voting on all sites.

**Screenshots/Configs**
https://prnt.sc/s4s3lc
VotingSites.yml: https://pastebin.com/VNFE5PNV
config.yml https://pastebin.com/8K7gu3tw

**Additional info**
In rewards folder it generated files for each site. I don't know if its related but It only contains:
```
Messages:
  Player: '&aThanks for voting on %ServiceSite%!'
DirectlyDefinedReward: true
```

**Comment by BenCodez** [comment]
The EverySiteReward gives a reward for every site....

Use AllSites reward in Config.yml

**Comment by Forsetinn** [comment]
Right. Thank you!
