### ISSUE TITLE
Duplicate AllSites reward.

### ISSUE THREAD

**Issue by Forsetinn** [BenCodez/VotingPlugin#779]
**Versions**
Plugin5.21.1 spigot 1.15.2

**Relevant information**
https://pastebin.com/kkGPhFCv
https://prnt.sc/s5b25v

**Context**
After all sites have been voted on users get final reward when voting on all sites twice.
I can't figure out how to fix it. At first I thought It was because of first time vote. But It happens with users who have voted before. Also when testing with adminvote `/av vote USER SITE` it gives the reward once which It's supposed to.
Running bungee setup btw.

**Comment by BenCodez** [comment]
That would be because of the bungee setup. How did you set it up?

**Comment by Forsetinn** [comment]
bungeeconfig.yml: https://pastebin.com/fV3BA0tD
Hub/Lobby: https://pastebin.com/vRRC4Qww
SMP Config: https://prnt.sc/s5b25v
Other server configs are the same as SMP

**Comment by BenCodez** [comment]
Set debuglevel to EXTRA in one the servers and have the double reward happen and send the log.

**Comment by Forsetinn** [comment]
https://pastebin.com/rC8QUE17

This time it didn't happen. He has voted before.
But he tells me he's getting duplicate "Thanks for voting"
And sometimes a full 30 seconds and 1 minute afterwards he finished voting.

**Comment by BenCodez** [comment]
Are you using votifier to forward the vote? You can't do that when running votingplugin on bungee.

**Comment by Forsetinn** [comment]
I'm using nuvotifier. How else do I link it to the sites?

**Comment by BenCodez** [comment]
VotingPlugin handles it.

**Comment by Forsetinn** [comment]
So the public.key is the same as secret.key? I place that key instead of votifier?
Little problem all my keys are the same. Can I generate a new one somewhere?

**Comment by Forsetinn** [comment]
Because I read on the wiki same key on all servers. So i thought the key needed to be the same on each server.

**Comment by BenCodez** [comment]
secret.key file the same on all servers. Nuvotifier on bungee and that is all. Sockets should be setup (looks like they were from what I can tell)

/votingpluginbungee vote (player) (site)

**Comment by Forsetinn** [comment]
So should I delete all nuvotifier.jar from the spigot servers?

**Comment by BenCodez** [comment]
Yes

**Comment by Forsetinn** [comment]
/votingpluginbungee vote (player) (site) worked! Lets hope it's the same when players vote! Thank you so much. Legend mate.
