### ISSUE TITLE
Commands not working, error in console

### ISSUE THREAD

**Issue by foxyhusky** [BenCodez/VotingPlugin#780]
i run a 1.15 spigot server

and try to setup rewards in the voteplugin but whenever i enter something other then what is allready there it gets an YML error

VoteSites:
  minecraftservers_org:
    Enabled: true
    ServiceSite: minecraftservers.org
    VoteURL: https://minecraftservers.org/server/581890
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
  Commands:
  - goldencrates givekey %player% coal
  Messages:
    Player: 'Thanks for voting!'

**Comment by BenCodez** [comment]
Pastebin that.

**Comment by foxyhusky** [comment]
https://pastebin.com/wtMjp94g

**Comment by BenCodez** [comment]
https://pastebin.com/R6beBvwb
