### ISSUE TITLE
/vote givepoints Takes Points when Using a Negative Point Value

### ISSUE THREAD

**Issue by HuskerFan34** [BenCodez/VotingPlugin#781]
**Versions**
Plugin: 5.21.1
Spigot: 1.15.2

**Describe the bug**
When running the /vote givepoints command with a negative number, the command takes points from the player and gives them to the player issuing the command. For example, if player A ran /vote givepoints PlayerB -10, Player B would have 10 points taken from them and given to player A. 

**To Reproduce**
1. Run the /vote givepoints or /votegivepoints command with a negative number
2. Gain points from the player instead of giving points

**Expected behavior**
I would expect the command to not work with negative values and the player would instead receive an error message. This loophole was abused on my server to steal voting points from other players. 

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/59267792/80314484-5864fe00-87b7-11ea-92e0-9a4a2bd7b2ff.png)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Try that.

**Comment by HuskerFan34** [comment]
Yes! Gives an error messaging saying the number of points needs to be greater than 0.
