### ISSUE TITLE
Vote Sites Bug

### ISSUE THREAD

**Issue by SmexyDuk** [BenCodez/VotingPlugin#782]
**Versions**
1.15.2

**Describe the bug**
Certain vote sites doesn't work.

**To Reproduce**
1. put minecraft-server-list.com as a vote site
2. set up the rewards
3. save and reload

**Expected behavior**
Automatically redirects you to "MCSL" and adds it as a votesite on your /vote
making minecraft-server-list.com not work, every other site doesn't work as well.

**Comment by BenCodez** [comment]
VoteSites.yml?

**Comment by SmexyDuk** [comment]
Yep.

**Comment by BenCodez** [comment]
Are you gonna send it?

**Comment by SmexyDuk** [comment]
https://pastebin.com/HkYFxPe9
I have already deleted the other websites last night, just decided to post it here again to see if there are any fixes. But thats what my config currently looks like.

**Comment by BenCodez** [comment]
If it generates a votesite then you have an incorrect service site. Check console when that happens.

**Comment by SmexyDuk** [comment]
minecraft-server-list.com <- I used this one and it generated the error. Is there something wrong with the link? Thats how i exactly wrote it down on the configs. Not "https://minecraft-server-list.com/"

**Comment by BenCodez** [comment]
The service site could be anything, check console on a vote.

**Comment by SmexyDuk** [comment]
Let me reproduce it real quick.

**Comment by SmexyDuk** [comment]
https://pastebin.com/pv5iNBhb
https://pastebin.com/AWrxVEH1 - votesites.yml

**Comment by BenCodez** [comment]
VoteSite with service site 'MCSL' does not exist

**Comment by SmexyDuk** [comment]
Yup, I did not even put MCSL anywhere on the votesites.yml
Other voting sites produce that error as well.

**Comment by BenCodez** [comment]
MCSL is the service site, set it to that.

**Comment by SmexyDuk** [comment]
Thanks, it works now. :)
