### ISSUE TITLE
VotingPlugin adding seemingly random amounts of money to people's balances

### ISSUE THREAD

**Issue by CaptainKirk55** [BenCodez/VotingPlugin#784]
**Versions**
Plugin version 5.20.8 Spigot version git-Spigot-2040c4c-893ad93

**Relevant information**
Rewards Folder:
ExampleAdvanced.yml: https://pastebin.com/5pbQKiBC
ExampleBasic.yml: https://pastebin.com/5Dw3iSFc
FirstVote.yml: https://pastebin.com/RSJjBgbR
MonthlyAwards_1_Rewards.yml: https://pastebin.com/Au3j5jeN

Config.yml: https://pastebin.com/0sHU6Cj5
VoteSites.yml: https://pastebin.com/4uP1GJF5

**Context**
I have a fixed amount of money on my server, that increases by $100 as new people join. I noticed this problem a few months ago when for what seemed like no reason, the person who votes the most suddenly had some random amount of money in excess of $200,000 with no information about how he got that amount of money being logged.
I have a chest shop plugin to be able to transfer money between players, but that doesn't allow them to add or remove money from the economy.
In suspicion of it being the voting plugin I removed it for 2 weeks where the economy sat normal with the server balance not changing other than when people would join for the first time.
I really hope I'm just being stupid and overlooking something, but when I went to bed last night my server total was an even number ($21,570), and then 2 new people joined before I got back on today and the server balance has increased by $399.02 ($21,969.02).
I would really like to be able to use this specific voting plugin because I like that the vote shop allows me to give players the choice of what reward they would like, and incentivizes them to vote more to save for better rewards. Because of this I give them $50 for their first vote and then no reward except a vote token every vote after. pls help

**Comment by BenCodez** [comment]
Your not using any random money, so I don't think VotingPlugin is doing that

**Comment by CaptainKirk55** [comment]
I'd like to think voting plugin isn't doing that either, but after another two days without it, the balance has yet to be messed up

**Comment by BenCodez** [comment]
Set debug level to Extra, you'll see in console every reward there is being
executed and what exactly is given

**Comment by CaptainKirk55** [comment]
https://pastebin.com/c44cufhQ
It seems like it thinks that there are multiple reward files or something?? I'm not really sure what's going on because I only have the 4 reward files that I put in here. Should I maybe just try to do a fresh reinstall of the plugin? I already tried to update it.

**Comment by BenCodez** [comment]
That's all from one reward file (it's just for me debugging, I can really trace issues).

You can see what it attempts to give and what it actually gives. No money was given on that pastebin you sent.
