### ISSUE TITLE
Having issues setting up

### ISSUE THREAD

**Issue by iSpudnik** [BenCodez/VotingPlugin#785]
**Versions**
Latest versions

**Relevant information**
VoteSites.yml
https://pastebin.com/wR9FdGSC

Config.yml
https://pastebin.com/ZA1pkXt4

**Context**
So i tried setting it up, i was able to get it working for votes and messages but it would not give the player anything.

I am rather confused by this and could really use guidance

**Comment by BenCodez** [comment]
https://pastebin.com/3s3cVepV
