### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#788]
**Versions**
5.21.1 , Spigot 1.15.2

**Describe the bug**
I try to make a network reward and when i vote on one server i get 10 rewards
![error](https://user-images.githubusercontent.com/64692581/80865400-82bc2d00-8c89-11ea-94fb-17c167da2d4e.png)

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Gonna have to send the rewards and explain your setup.
