### ISSUE TITLE
How do I add a button to votesites.yml to show all sites

### ISSUE THREAD

**Issue by Vehzx** [BenCodez/VotingPlugin#789]
**Versions**
5.21.1

**Relevant information**
Just want to know how to add a button to the votesites.yml (so it appears in the GUI in-game) that lists all the vote sites into the chat, so that players don't have to open the vote menu everytime after clicking a vote site.

**Comment by BenCodez** [comment]
Use the allsites button

**Comment by Vehzx** [comment]
How do I got about using that in the votesites.yml config?

I tried looking for the default votesites config but I don't see an example in there?

**Comment by BenCodez** [comment]
The allsites button is automaticlly added. Unless you removed it.

**Comment by Vehzx** [comment]
I must have removed it on accident when filling out the votesites yml, could you possibly copy paste the default example of it for me?

Sorry to be a pain :/

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L393

**Comment by Vehzx** [comment]
tysm
