### ISSUE TITLE
After voting, it gives the player $100 and broadcasts a message when I didn't set it to...

### ISSUE THREAD

**Issue by Niccckkkk** [BenCodez/VotingPlugin#790]
**Versions**
5.21 Plugin version and 1.15.2 spigot version.

**Describe the bug**
After a player votes, I have it so it gives the player in game currency (coins), which it does, however, it also broadcasts a message: "[Broadcast] (player) has voted!" and it gives $100 in essentials money, even though I did not set it to do those two things..

**To Reproduce**
Vote for anything and it executes those commands.

**Expected behavior**
A clear and concise description of what you expected to happen. I expected for only my coins command to execute, not the broadcast and essentials money.

**Screenshots/Configs**

Example_Basic.yml: https://paste.helpch.at/uponufugux.coffeescript 
ExampleAdvanced.yml: https://paste.helpch.at/xecutokomo.shell
Config.yml: https://paste.helpch.at/ugogiyojun.coffeescript
VoteSites.yml: https://paste.helpch.at/unecitelef.php

**Comment by BenCodez** [comment]
The broadcast can be disabled by setting the broadcast message to an empty message in the config.

The money I don't know where it's coming from. Another plugin?

**Comment by Niccckkkk** [comment]
I already disabled the broadcast message in the config, but I keep getting one that pops up. Let me check some other configs real quick for other plugins to see if another plugin is causing it like you mentioned.

**Comment by BenCodez** [comment]
You need to set it to BroadcastMsg: ''

**Comment by Niccckkkk** [comment]
> You need to set it to BroadcastMsg: ''

Yeah, just fixed that, it still pops up though. I'm going to go check some other configs real quick.

**Comment by Niccckkkk** [comment]
I honestly can't figure out what could be causing it... just for reference, the plugins I think that could contribute to causing it, is Essentials... since the commands being executed are from that plugin, but I can't find anything in the config related to it.

**Comment by BenCodez** [comment]
CMI? 

You can also set debuglevel to EXTRA and check the console, you'll see if it's from votingplugin.

**Comment by Niccckkkk** [comment]
https://paste.helpch.at/fuyoxakosa.bash
Found the console message giving those commands, but I can't find what plugin it is giving it from. Definitely not VotingPlugin.

**Comment by BenCodez** [comment]
Yeah, not votingplugin.
