### ISSUE TITLE
All time votes get reseted for some users

### ISSUE THREAD

**Issue by LotusDemon** [BenCodez/VotingPlugin#791]
Paper 229

VotePlugin version:
http://prntscr.com/sas6kf

Votes for users who are playing the server (total votes & monthly votes) get reset this does not happen with users who used to vote but stopped playing the server.

We don't know the exact steps to reproduce (we aren't sure what could trigger the reset) but it happened the 1st day of the new month (yes all time votes DID reset for some user its not that we are just checking monthly votes)

The total votes should not reset each month, just the monthly votes

**Screenshots/Configs**
This is an image of the 2020_APRIL.yml in VotingPlugin>TopVother>Monthly

![image](https://user-images.githubusercontent.com/64795139/80985296-517d6180-8e2f-11ea-9b13-5baa63ecd26e.png)

And this is an image of the ingame **all time** top voters:
![image](https://user-images.githubusercontent.com/64795139/80985441-8689b400-8e2f-11ea-82c1-afcdb3307fac.png)
As you can see the second one should be Ivanovic24 (according to the first image), but his votes, and those of many people else got reset.

**Additional context**
The plugin was up for nearly all of April and until today.

**Comment by BenCodez** [comment]
Config?

**Comment by LotusDemon** [comment]
> Config?

[Config.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4578187/Config.txt)

**Comment by BenCodez** [comment]
My only idea is the data failed to saved and messed up. Could try MySQL

**Comment by LotusDemon** [comment]
We might do just that, is there any way to migrate the data to MySQL from the data stored by the plugin?

**Comment by BenCodez** [comment]
/av convertfromdata SQLITE

Switch to mysql first.

**Comment by LogGits** [comment]
i was having this issue with SQLITE back in the day @Ben12345rocks (before migrating to mysql) maybe there is a flaw in VP's sqlite data handling?

**Comment by BenCodez** [comment]
@LogGits I think it's depending on the storage on the server. Since I don't cache sqlite (tried a few times and didn't work so well)
