### ISSUE TITLE
Error While Enabling

### ISSUE THREAD

**Issue by XipsAhoy** [BenCodez/VotingPlugin#792]
**Versions**
VotingPlugin 5.21.1 PaperSpigot 1.8.8

**Describe the bug**
I get this error when I load the plugin!

**To Reproduce**
1. Load the server

**Expected behavior**
The plugin to load correctly.

**Screenshots/Configs**
https://pastebin.com/5WbiTzFx Here's the error!

**Additional context**

**Comment by BenCodez** [comment]
From the plugin page:

    Use v5.13.6 for 1.12 and older versions, support WILL NOT be provided for these versions, so please don't ask for support for these versions.
