### ISSUE TITLE
Custom Reward

### ISSUE THREAD

**Issue by XipsAhoy** [BenCodez/VotingPlugin#794]
**Versions**
VotingPlugin 5.21.1

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Can I give a not fisical reward to a player on the shop, like when the player clicks in the diamond, he does not get the diamond, he get's a reward from a command!

**Comment by BenCodez** [comment]
So set it as a command?

**Comment by XipsAhoy** [comment]
Yes, I click in the diamond, but I don't get the diamond, I get a reward that is given by a command!

**Comment by BenCodez** [comment]
Then set a command? Doesn't sound that hard

**Comment by XipsAhoy** [comment]
Yes, how can I do that!

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - command here

**Comment by XipsAhoy** [comment]
But, when I do that, the player gets the diamond!, I don't want the player to get a diamond. I am talking about the vote shop!

**Comment by BenCodez** [comment]
That's how you do it for the vote shop.

**Comment by XipsAhoy** [comment]
Ok, if I do that, the player won't get the diamond, right? Only the reward from the command

**Comment by BenCodez** [comment]
You would need to remove the diamond reward.

**Comment by XipsAhoy** [comment]
Ok
