### ISSUE TITLE
Signs with heads no longer works

### ISSUE THREAD

**Issue by Klawdek** [BenCodez/VotingPlugin#795]
**Versions**
Plugin version and spigot version.
VotingPlugin version 5.21.1
Paper version git-Paper-251 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Describe the bug**
Signs with heads no longer works.  The heads either remain generic player heads and sometimes they take on skins that are for different players than the sign says.
**To Reproduce**
Make a sign wall as described in these docs under the sign section.
**Expected behavior**
The heads to be the skin of the player on the sign
**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Gonna provide any more details? How did you set the heads up? Did you click the sign then the head?

**Comment by Klawdek** [comment]
I set the heads up just like the picture.  I tried your advice about clicking on sign and then head and it works.  It sometimes takes a few tries to get it to work and I had one that would not work at all so I redid sign.  I never saw anything about having to click on signs and heads to get it to work.  Nor have I had to do that in the past.  Thank you for your help.

**Comment by BenCodez** [comment]
I added that awhile ago to avoid issues like this.
