### ISSUE TITLE
World whitelist?

### ISSUE THREAD

**Issue by Qekker** [BenCodez/VotingPlugin#796]
How do i use world whitelist? Im new to this plugin. So help would be nice!

**Comment by BenCodez** [comment]
Add list of worlds in the rewards

    Rewards:
      Worlds:
      - world
      # rewards...

**Comment by Qekker** [comment]
so now the rewards will only be awarded in the "world"

**Comment by BenCodez** [comment]
Yep.

**Comment by Qekker** [comment]
Enabled: true
    Name: minecraft-server-list.com
    ServiceSite: minecraft-server-list.com
    VoteURL: https://minecraft-server-list.com/server/459567/vote/
    VoteDelay: 24
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Worlds:
      - skyworld
      Commands:
        Console:
        - crate give to %player% Votekey 1
      Messages:
        Player: Thanks for voting, heres a reward
So this should work?

**Comment by BenCodez** [comment]
Should.

**Comment by Qekker** [comment]
^^ Another quest why wont my second voting site pop up anymore. # 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  ExampleVoteSite:
    Enabled: true
    Name: minecraftservers.org
    Priority: 5
    ServiceSite: minecraftservers.org
    VoteURL: https://minecraftservers.org/vote/583658
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Worlds:
      - skyworld
      Commands:
        Console:
        - crate give to %player% Votekey 1
      Messages:
        Player: Thanks for voting, heres a reward
Site2:
    Enabled: true
    Name: minecraft-server-list.com
    ServiceSite: minecraft-server-list.com
    VoteURL: https://minecraft-server-list.com/server/459567/vote/
    VoteDelay: 24
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Worlds:
      - skyworld
      Commands:
        Console:
        - crate give to %player% Votekey 1
      Messages:
        Player: Thanks for voting, heres a reward
        # BOY
EverySiteReward: []

**Comment by Qekker** [comment]
Why does my second vote site not pop up? 
[VoteSites.zip](https://github.com/Ben12345rocks/VotingPlugin/files/4617837/VoteSites.zip)

**Comment by BenCodez** [comment]
https://pastebin.com/msCRzd5s
