### ISSUE TITLE
Auto-Updater and In Game & Console messages when an update is released. 

### ISSUE THREAD

**Issue by DamianJBurgos** [BenCodez/VotingPlugin#798]
Please add a feature that automatically updates the plugin when a new update is released. If that is not an option to notify OP players in the MOTD that an update has been released, and also print a message in console on server startup. 

If auto-updater is possible please add a disable option in the config and also an option to opt-in to dev builds.

**Comment by BenCodez** [comment]
Already exists. Just doesn't display ingame. There is also commands to download the builds.
