### ISSUE TITLE
Milestones and MontlyVotes

### ISSUE THREAD

**Issue by ehetteNandaYo** [BenCodez/VotingPlugin#800]
**Versions**
5.21.2

**Context**
How do I force milestones o reset them?

I have tried using different commands like setmonthlyvotes and set milestone and then force a vote to reach the milestone but nothing happens, because for some reason various users didnt get their milestone reset this month and I want to give them their rewards by setting the montly votes and resetting the milestones.

**Comment by BenCodez** [comment]
I think that would require going into the data of the player
