### ISSUE TITLE
Is it possible to give vote rewards offline without using a vote file?

### ISSUE THREAD

**Issue by Ant0ny1** [BenCodez/VotingPlugin#801]
Is it possible to give vote rewards offline without using a vote file? I have tried doing [this](https://imgur.com/a/HWcuWGD) but it doesn't seem to work. Is there any way to do this or do I have to actually use a reward file?

**Comment by BenCodez** [comment]
That should work. Console log on a vote?

**Comment by Ant0ny1** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/65314382/82077280-04518900-9694-11ea-9f9b-34035e7e4aa3.png)
![Screenshot (9)](https://user-images.githubusercontent.com/65314382/82077301-0ddaf100-9694-11ea-8d21-fb22ed546e66.png)

First one is an offline vote, second is an online vote

**Comment by BenCodez** [comment]
Disable ForceOffline
