### ISSUE TITLE
Server Freezes or Crashes After a new player joins...

### ISSUE THREAD

**Issue by farhaanlevy** [BenCodez/VotingPlugin#804]
**Versions**
1.15.2

**Describe the bug**
I checked the logs, I think it says there's an Error with the Voting Plugin Expansion,
When a new player joins the whole server freezes for 20+ seconds and sometimes crashes...

**To Reproduce**
1. Get Voting Plugin Expansion on PlaceholdersApi
2. A new player joins...

**Expected behavior**
Laggs or crashes server..

**Screenshots/Configs**
https://pastebin.com/JcF6XH3F

**Additional context**
Please fix, If there is a way to fix it tell me, Players are leaving my server due to server crashes and lag..

**Comment by BenCodez** [comment]
Use MySQL
