### ISSUE TITLE
Is there a command for giving players vote points?

### ISSUE THREAD

**Issue by JGCKyle** [BenCodez/VotingPlugin#805]
**Versions**
Plugin is on latest version, running on a server with Spigot 1.15.2

**Relevant information**
Is there a command that I can use in game to give players vote points manually?

**Context**
I am looking into adding the ability to purchase vote points in my server store.

Many thanks,

JGCKyle

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/Commands-&-Permissions

**Comment by JGCKyle** [comment]
vote.givepoints , I see it on there! Thank you so much Ben! Love your plugin so far :)

**Comment by BenCodez** [comment]
Use one of the /av commands.

**Comment by JGCKyle** [comment]
I can't seem to get it working.. Is it /av givepoints (username) (amt) I tried that and it didnt do it for me

**Comment by JGCKyle** [comment]
I found it, please disregard! Thanks again 👍
