### ISSUE TITLE
VoteParty ADD ExtraRequired

### ISSUE THREAD

**Issue by Bricec6** [BenCodez/VotingPlugin#807]
# New command
**Describe the solution you'd like**
Hello currently we have this order:
/av VotePartyExtraRequired 15

allowing to add +15 to the VoteParty, the problem is that it adds +15 to the initial VoteParty but does not add example:
1st party vote reached:150 +15 = 165 
2nd vote party reached: 150 + 15 = 165

 then you'll need an order like this:

/av VotePartyAddExtraRequired 15

which would add +15 to the party vote every time
1st vote party reached:150 +15 = 165 
2nd vote party reached: 165 + 15 = 180
3rd vote party reached: 180 + 15 = 195

  # Reset at the end of the month or day
This system resets itself every day or month if you have activated it:
  ResetMonthly: true
  ResetEachDay: true

thanks to you, top plugins!

**Comment by BenCodez** [comment]
This already exists (not in command form), but there is an option on vote party.

**Comment by Bricec6** [comment]
![image](https://user-images.githubusercontent.com/51750055/82374707-b637df00-9a1f-11ea-814e-c3360bebfb5d.png)

What the command?

**Comment by BenCodez** [comment]
There is no command. Just an option.
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L658

**Comment by Bricec6** [comment]
Perfect you are the boss, thank you!
