### ISSUE TITLE
How Do I Add Items Into The Vote Shop?

### ISSUE THREAD

**Issue by JGCKyle** [BenCodez/VotingPlugin#808]
**Versions**
Latest Plugin Version, and 1.15.2 Spigot

**Relevant information**
Looking for information on how I can add items in to the vote shop.. Is there a format you have on hand that I should use to add items into the config file, or is their a built in GUI for this as well? Can not seem to find.

**Context**
I am going live tonight and hope to add in some rewards for players who want to use votepoints.

**Comment by JGCKyle** [comment]
I can see this in the config for shop section:

VoteShopEnabled: true
# Hide items in vote shop which user can not buy
VoteShopHideLimitedReached: true
# Requires above to be false
VoteShopLimitReached: '&aYou reached your limit'
VoteShopRequireConfirmation: false
Shop:
  # Identifier
  # Used in placeholders for formats
  # Do not have spaces in the identifier
  Diamond:
    # Item
    Material: 'DIAMOND'
    Data: 0
    Amount: 1
    Name: '&4Buy A Diamond'
    # You can set skulls of the player using the following
    # Remove the # to enable
    #Skull: '%Player%'
    Lore:
    - '&c&lCost: &c3 Voting Points'
    # Number of voting points this cost
    Cost: 3
    # Permission required, leave blank for no permission
    Permission: ''
    # Limit how many times you can buy this
    #Limit: 3
    # Reset limit daily/weekly/monthly
    #Reset:
      #Daily: false
      #Weekly: false
      #Monthly: false
    # If true, item is not buyable
    #NotBuyable: false
    # Rewards to run if player buys successfully
    Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 1     

I am not really sure which sections I would need to add in in order to add new items. Any help is much appreciated!

**Comment by BenCodez** [comment]
That whole section under VoteShop.

**Comment by JGCKyle** [comment]
Okay excellent, so I just edit the entire thing for each item, keeping the format??  Do you happen to have an example of one that has been done with custom rewards in it?

I have the same general question about vote rewards too.. I can submit a seperate ticket though..

**Comment by BenCodez** [comment]
Same format. The Rewards work the same everywhere. (Reward file examples show what I can do). Don't need to bother with a separate issue.

**Comment by JGCKyle** [comment]
Okay perfect. Sorry last question, where would I access the reward file?

**Comment by BenCodez** [comment]
VotingPlugin/Rewards/FILEHERE or github page if needed

**Comment by JGCKyle** [comment]
Okay cool. I will look in to that, thank you
