### ISSUE TITLE
Milestones issue

### ISSUE THREAD

**Issue by TKwSni** [BenCodez/VotingPlugin#809]
**Versions**
spigot 1.15.2   5.21.2

**Describe the bug**
Players not receiving milestones at all and some receving all the milestones before the goal.

I have checked users with this issue in the DB

User that was not getting rewards, for some reason had all milestones set to true with over 200 votes in the month

User that got all the rewards, I couldnt check if he had all milestones true, but in this month he had less than the minimun required for the first milestone 

**To Reproduce**
No idea, some people have voted 10 times in 1 month and received all milestones I have setup at once, and some have voted and have never received anything, or this case that complained today said he receive some except the last one.

**Expected behavior**
To not do that? 

**Screenshots/Configs**
https://paste.gg/p/anonymous/c5536f252a97457da8e057546a3f19f6

**Comment by BenCodez** [comment]
Yeah, not much I can do without more info.

**Comment by TKwSni** [comment]
And what can I do to help find the source of the issue ? is there a way I can "fix" this somehow?

**Comment by TKwSni** [comment]
whats the purpose of that command ?

**Comment by BenCodez** [comment]
Resyncs alltime total to milestone count.
