### ISSUE TITLE
Voting gives multiple rewards. 

### ISSUE THREAD

**Issue by MrNyoom** [BenCodez/VotingPlugin#810]
VotingPlugin v5.21.1 and Spigot 1.15.2 latest.

When voting and testing voting with /av vote, 3-7 voting rewards are given. I've attempted updating the jar. It's likely a config issue. 

1: Simply vote

When voting I expect people to only get one reward for voting on a site.
 
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
[Config.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4658280/Config.txt)
[VoteSites.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4658278/VoteSites.txt)

**Additional context**
I have gone through completed issues and tried to fix the problem before making this issue. Unfortunately the solutions I came across did not fix my problem.

**Comment by BenCodez** [comment]
Do you solve this?

**Comment by MrNyoom** [comment]
I did not

**Comment by BenCodez** [comment]
Did you name the files with .yml on it? Does the server get the vote?

**Comment by MrNyoom** [comment]
Yeah that's how I know it gives many items for one vote

**Comment by BenCodez** [comment]
what rewards are you getting?
