### ISSUE TITLE
How to properly use MYSQL?

### ISSUE THREAD

**Issue by romanshak** [BenCodez/VotingPlugin#811]
Hi,
i just wanted to ask how do we use MySQL with this plugin? 
Do i need nuvotifier on every server? What do I have to do?
Plzz help

**Comment by BenCodez** [comment]
Just set it to mysql?

**Comment by romanshak** [comment]
just add mysql? do i need votifier on every server? is that it?

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by romanshak** [comment]
thanks! :D
