### ISSUE TITLE
Questions about materials and data

### ISSUE THREAD

**Issue by Bibithom** [BenCodez/VotingPlugin#812]
Hi !
I get into some troubles setting up your plugin.
I tried things to give enchanted_book containing mending but nothing is working for me
And another thing i've tried to give some basics items like cooked_beef but i get "material:null" in console.

Can you give me an example with something else than diamonds ? And can you explain me how to give an enchanted_book with a particular 'StoredEnchantment' ?

I'm using your latest version of VotingPlugin from spigotmc

There's an example of a reward file :
Messages:
  Broadcast: '&a%player% a voté pour Draenor, merci à lui !'
  Player: 'Merci pour ton vote, nous t''envoyons tes récompenses'
Money: 1000
AdvancedPriority:
  Rec:
    Chance: 12
Items:
    Cooked_beef:
       Material: 'COOKED_BEEF'
       Amount: 8
     Message: '&aVoici 8 Steaks'
  Rec1:
    Chance: 10
    Items:
      Diamond:
        Material: 'OAK_LOG'
        Amount: 32
    Message: '&aVoici 32 bûches de chêne'
  Rec2:
    Chance: 10
    Items:
      emerald:
        Material: 'DIAMOND'
        Amount: 3
    Message: '&aVoici 3 diamants'
  Rec3:
    Chance: 10
    Items:
      iron:
        Material: 'EMERALD'
        Amount: 3
    Message: '&aVoici 3 émeraudes'
  Rec4:
    Chance: 10
    Items:
      item2:
        Material: 'NAME_TAG'
        Amount: 1
    Message: '&aVoici 1 étiquette'
  Rec5:
    Chance: 2
    Commands:
    - minecraft:give %player% enchanted_book{StoredEnchantments:[{id:"unbreaking",lvl:3}]}
    Message: '&aVoici un livre solidité III'
  Fallback:
    Money: 1000
    Message: 'Oh dommage, tu n''as rien eu d''intéressant ce coup-ci, tiens 1000 niandra de compensation'

Thank's in advance for your help !

**Comment by BenCodez** [comment]
Pastebin that.

**Comment by Bibithom** [comment]
Hi ! Many indentation problems, my bad, sorry for taking your time, it works perfectly now !
