### ISSUE TITLE
Disable VoteGUI button

### ISSUE THREAD

**Issue by Wukkel** [BenCodez/VotingPlugin#814]
Is there a way I can disable (Back to VoteGUI) option for players

**Comment by BenCodez** [comment]
Options in the config.

**Comment by Wukkel** [comment]
Where exactly I still can't seem to find it

**Comment by BenCodez** [comment]
just search backbutton? There is more than one.

**Comment by Wukkel** [comment]
Yeah I found this but when I set BackButton to false it still does not work. People can still click the barrier
  Material: 'BARRIER'
  BackButton: false
  Data: 0
  Amount: 1
  Name: '&8Back to VoteGUI'

**Comment by Wukkel** [comment]
Nevermind got it
