### ISSUE TITLE
Question about rewards.

### ISSUE THREAD

**Issue by Wukkel** [BenCodez/VotingPlugin#815]
I have a quick questions about voting rewards. Is it possible to give each group a different set of voting rewards?
Example:
Player has a chance to vote diamonds , exp
Donator rank has a chance to vote Mob spawner and Diamonds

If this is possible where do I configure this?

**Comment by BenCodez** [comment]
Use advancedpriority, example in default votesites.yml

**Comment by Wukkel** [comment]
https://gyazo.com/83c1b5041c3e6dd367bbbb8bb4aa13fe
Do I change the player to the name of the donator group for this to happen?

**Comment by BenCodez** [comment]
Instead of chance use permission

**Comment by Wukkel** [comment]
I'm really sorry for asking another question but I still don't understand how to set different rewards for ranks, I really tried watch tons of different tutorials. Do you have some sort of example that is a bit more clear or a more in dept tutorial? 

Once again sorry for the many many questions I really want to get this done and I do really like votingplugin

**Comment by BenCodez** [comment]
Rewards:
      AdvancedPriority:
        Reward1:
          RequirePermission: true
          Permission: 'perm'
          # rewards to give here
        Reward2:
          # same as above
        fallback:
          # just rewards here

**Comment by Wukkel** [comment]
Can I make up this permissions? Example: Donator.iron

**Comment by BenCodez** [comment]
Yes

**Comment by Wukkel** [comment]
Thanks again for the great assist.
I do however have two more question and thats it.
How do i give donator ranks priority?
I have setup milestones after you receive hit an x amount of votes you will be ranked up to a certain rank. However If someone has donator rank they will lose their donator ranked and be placed into the rank you earn from voting. Is it possible to set it up a way that they keep the donator rank even if they achieve a milestone

Second question is related to previous questions, so i managed to get rewards per rank done but is it possible to set a different chance on each item? 
Example; 
Mob spawner has 5% chance of being voted
1 diamond 95% chance

**Comment by BenCodez** [comment]
1. Use advancedpriority, example in default votesites.yml, just use permissions
2. Different rewards I guess would be the best? Depends on your exact rewards.

**Comment by Wukkel** [comment]
> 1. Use advancedpriority, example in default votesites.yml, just use permissions
> 2. Different rewards I guess would be the best? Depends on your exact rewards.

The first one do you have an example? I tried a few things but still places donator ranks into the voting ranks when achieving a milestone its so weird

**Comment by BenCodez** [comment]
Send what you have?

**Comment by Wukkel** [comment]
MCSL:
    Enabled: true
    ServiceSite: minecraft-server-list.com
    VoteURL: ....
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
    - 'rewardfilehere'
    - 'Secondrewardfile'
    - 'Etc,'
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

Also having issue with this with the rewards, if I put it like that it gives an error in console 

Well you said there was an example in votesites.yml 
But this is my votesites.yml
VoteSites:
  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/server/585768
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  MCSL:
    Enabled: true
    ServiceSite: minecraft-server-list.com
    VoteURL: https://minecraft-server-list.com/server/461127/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Minecraft-MP_com:
    Enabled: true
    ServiceSite: Minecraft-MP.com
    VoteURL: VoteURL
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by Wukkel** [comment]
You said an example would be in default votesites.yml 
And this is my votesites.yml i can't find an example
VoteSites:
  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/server/585768
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
    - 'memberreward'
    - 'ironreward'
    - 'goldreward'
    - 'redstonereward'
    - 'diamondreward'
    - 'emeraldreward'
    - 'ironrewardrare'
    - 'goldrewardrare'
    - 'redstonerewardrare'
    - 'diamondrewardrare'
    - 'emeraldrewardrare'
  MCSL:
    Enabled: true
    ServiceSite: minecraft-server-list.com
    VoteURL: https://minecraft-server-list.com/server/461127/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
    - 'memberreward'
    - 'ironreward'
    - 'goldreward'
    - 'redstonereward'
    - 'diamondreward'
    - 'emeraldreward'
    - 'ironrewardrare'
    - 'goldrewardrare'
    - 'redstonerewardrare'
    - 'diamondrewardrare'
    - 'emeraldrewardrare'
  Minecraft-MP_com:
    Enabled: true
    ServiceSite: Minecraft-MP.com
    VoteURL: https://minecraft-server-list.com/server/461127/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
    - 'memberreward'
    - 'ironreward'
    - 'goldreward'
    - 'redstonereward'
    - 'diamondreward'
    - 'emeraldreward'
    - 'ironrewardrare'
    - 'goldrewardrare'
    - 'redstonerewardrare'
    - 'diamondrewardrare'
    - 'emeraldrewardrare'


So i don't know how to give these ranks priority

**Comment by Wukkel** [comment]
Also this is one of my donator rank rewards
# Directly defined reward file. ANY EDITS HERE CAN GET OVERRIDDEN!
Delayed:
  Enabled: false
  Hours: 1
  Minutes: 0
  Seconds: 0
Timed:
  Enabled: false
  Hour: 12
  Minute: 0
Random:
  PickRandom: true
  Rewards:
    Commands:
    - lp user %player% parent add legend
  FallBack: []
RandomCommand:
- 'eco give %player% 2'
- 'exp give %player% 12l'
- 'give %player% diamond 3'
RequirePermission: true
Permission: AdvancedCore.Reward.Diamond
Javascript:
  Enabled: false
  Expression: ''
  TrueRewards: []
  FalseRewards: []
Javascripts: []
Priority: []
ChoiceRewards:
  Enabled: false
  Rewards:
  - Iron
  - Gold
Worlds:
- world1
- world2
RewardType: BOTH
ForceOffline: false
Potions:
  ABSORPTION:
    Duration: 100
    Amplifier: 1
Title:
  Enabled: false
  Title: '&cTitle!'
  SubTitle: '&aSubTitle!'
  FadeIn: 10
  ShowTime: 50
  FadeOut: 10
BossBar:
  Enabled: false
  Message: '&aBossbar'
  Color: BLUE
  Style: SOLID
  Progress: 0.5
  Delay: 30
Sound:
  Enabled: false
  Sound: BLOCK_ANVIL_USE
  Volume: 1.0
  Pitch: 1.0
Effect:
  Enabled: false
  Effect: EXPLOSION
  Data: 1
  Particles: 10
  Radius: 5
Firework:
  Enabled: false
  Power: 2
  Colors:
  - GRAY
  - SILVER
  FadeOutColor:
  - RED
  Trail: true
  Flicker: true
  Types:
  - BALL_LARGE
ActionBar:
  Message: '&cThis is an actionbar!'
  Delay: 30
OnlyOneLucky: false
Lucky:
  '10':
    Messages:
      Player: You were lucky and received an extra $100!
    Money: 100
  '50':
    Messages:
      Player: You were lucky and received an extra $1000!
    Money: 1000
DirectlyDefinedReward: true


But they don't receive anything when voting what causes this? i cant find the problem

**Comment by BenCodez** [comment]
Pastebin..... 

 Example in default file (look on github) or reward file.

**Comment by Wukkel** [comment]
[VoteSites.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4707364/VoteSites.txt)
[ironreward (1).txt](https://github.com/Ben12345rocks/VotingPlugin/files/4707365/ironreward.1.txt)
[ironrewardrare.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4707366/ironrewardrare.txt)
So these are how I setup my vote rewards, I did 99% chance on the normal vote rewards the iron rank should get and I made a new rare folder which they have 1% of receiving those items. But it still doesn't work I can't find the problem I gave the rank the custom permission etc, but It just doesn't work

**Comment by BenCodez** [comment]
Don't have .yml in the reward name, that will probably fix of the problems.

**Comment by Wukkel** [comment]
Still does not give any rewards,
https://gyazo.com/7fd60de6ff68cc9fea97f68944ea39ea
Does it have somethingto do with the world type? or do the rewards need to be between ''

**Comment by BenCodez** [comment]
You need to be in the worlds you specify, I'm guessing you don't have a world named world1

**Comment by Wukkel** [comment]
Omg I hope that solves the problem

**Comment by Wukkel** [comment]
It did work thanks alot, 3 small question though
[ironreward (2).txt](https://github.com/Ben12345rocks/VotingPlugin/files/4708533/ironreward.2.txt)
[ironrewardrare (1).txt](https://github.com/Ben12345rocks/VotingPlugin/files/4708534/ironrewardrare.1.txt)

As you can see I made 2 different folders for the iron rank, one standard reward 1 diamond, 1 balance, 1 xp level, that is set on 99% 
And one section for the extra rare things that is set on 1%, will this add up to 100% so they always receive something? 

And for somereason whenever I vote I receive so many items instead of just 1
https://gyazo.com/25d7dd4e905e0845e5f10b03bf7090bb
is this because I have Op and have all permissions?


And I still don't know where to put priority for donator ranks so they don't actually lose their donator rank when ranked up to a voter rank
https://gyazo.com/a0cdc8d3d2ebaabbc8f6fc30267d37b5 is it in this section?

These were actually my last 2 questions sorry for being a burden

**Comment by Wukkel** [comment]
https://gyazo.com/e4d02d7f6eda67dd97dc5d84d02cf080
Also how do I disable this?, It says false but people still sometimes get lucky from voting

**Comment by BenCodez** [comment]
1. You have no priority setup, so both rewards will try to be executed 
2. Probably the permission with op
3. Just priority within the rewards
4. Remove the whole lucky section. Same for anything in the rewards.

**Comment by Wukkel** [comment]
Where is the example on how to set this up correctly? do you have one by any chance?
https://gyazo.com/b8abb8099f6f6b036bff75223d08b986
I've got all these ranks

**Comment by BenCodez** [comment]
Default Votesites.yml has one, look on github

**Comment by Wukkel** [comment]
https://gyazo.com/d7e0b2edefce288e08f7770789f34eff
https://gyazo.com/d7e0b2edefce288e08f7770789f34eff
Yeah these, but I need the donator ranks to have some sort high priority so they don't get affected by milestone rank ups but I can't find an explanation on this
You do any paid votingplugin configurations? :p

**Comment by BenCodez** [comment]
It goes in order, will give the first reward it can. Just have a permission requirement for the ones you need.

**Comment by Wukkel** [comment]
Figured it all out, Thanks for the patience and the help much appreciated.
Also now when a player votes I made it so it says {Vote} %player% voted on the site name,
But I want to display the reward they received behind this how do i do this?

**Comment by BenCodez** [comment]
Add it to the message?

**Comment by Wukkel** [comment]
Yeah the reward they received to the message so it says {vote} Playername voted on the sitename and received itemname

**Comment by BenCodez** [comment]
Then change the message to include that?

**Comment by Wukkel** [comment]
yeah but what do I put for the item name since player = %player%

**Comment by Wukkel** [comment]
And since ive got multiple rewards for 1 voting link I can't just put diamond in the message since there are more things you are able to get then only a diamond

**Comment by BenCodez** [comment]
Have a separate message message in every reward and disable the other one
by setting it to a blank message

**Comment by Wukkel** [comment]
https://gyazo.com/1724e2cf7e07605d1a317ed8aab7a3d8 like this?
and then repeat this for every reward?

**Comment by BenCodez** [comment]
No, can't show you on my phone. Look in example basic and look for
broadcast near the bottom

**Comment by Wukkel** [comment]
https://gyazo.com/4699508143bd8274f8f03dd89c0fe2b5 It won't work but I don't see the issue?

**Comment by BenCodez** [comment]
You can only put that in one reward

**Comment by Wukkel** [comment]
btu how would I be able to set the message for the reward they get? I could set it like player has received one diamond but if they receive one iron it would still say diamond

**Comment by BenCodez** [comment]
You can't have multiple messages within the same reward. One per site.

**Comment by Wukkel** [comment]
How would I be able to showcase all rewards though? i've got multiple rewards in one file
Example:
RandomCommand:
- eco give %player% 1
- give %player% diamond 1
- exp give %player% 1l 
OnlyOneItem: true
RequirePermission: true
Permission: SurvCraftVote.Member

**Comment by BenCodez** [comment]
Use RandomReward and have each reward with a command and message.

**Comment by Wukkel** [comment]
Quick question about vote links so currently I have it like this
https://gyazo.com/0fee81625463271cc6284d3d00a771a6 
you see how its between [ ] but in the config its not like that
https://gyazo.com/da4b1c8783a5be5e18c99ed945e1753b
How do i fix this

**Comment by BenCodez** [comment]
Check the votesites.yml

**Comment by Wukkel** [comment]
https://gyazo.com/a96d758502763217dffa8d5d8d4ad62e Checked it but its not in there

**Comment by BenCodez** [comment]
Pastebin your config.yml?

**Comment by Wukkel** [comment]
[config.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4789374/config.txt)

**Comment by Wukkel** [comment]
Also would it be possible to create a message for the whole server to see in milestones?
https://gyazo.com/8ab880149d578b0d2998036e48105f1b This is what I currently have but only the player receives a message how do I make it so everyone sees?

**Comment by BenCodez** [comment]
Try with force links set to false

    Rewards:
      Messages:
        Broadcast: 'message'
