### ISSUE TITLE
Vote top command and the vote signs do not work.

### ISSUE THREAD

**Issue by Klawdek** [BenCodez/VotingPlugin#816]
**Versions**
Plugin version and spigot version.
VotingPlugin version 5.21.1
Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Describe the bug**
When doing the command /vote top 10 monthly or other numbers the response is always like this:
Top Monthly Voters 10/2
also when using signs for monthly top voters the numbers are rarly correct players who have less votes are shown as top voter.
THe sign problem has been going on for over a year and through numerous upgrades of this plugin and paper.
**To Reproduce**
DO the command /vote top 10 monthly
and set up some monthly signs and see how they become inaccurate over time.
**Expected behavior**
When doing the command /vote top  it should show a list of the top voters
When using signs it shouold correctly show the top monthly voters.

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
Here is ascreenshot of the signs:
![Screenshot (439)](https://user-images.githubusercontent.com/45950944/82843261-405dc880-9ea2-11ea-9c81-a42c1ed1d534.png)

**Additional context**

**Comment by BenCodez** [comment]
1. You can't show page 10 if there is only 2 pages. 
2. Do the signs still work? Can you right click them?

**Comment by Klawdek** [comment]
I thought nit was top 10 voters not pages.  Right clicking the signs does nothing sometimes and other times it prints in the chat who the correct voter for that sign is.

**Comment by BenCodez** [comment]
I think the signs need to get resynced, trying using the latest build from
Ben12345rocks.com, will still need to redo the signs

**Comment by Klawdek** [comment]
Ok I am using the latest build and redid the signs only time will tell if it works.  I would point out another thing.  The instructions for signs are incomplete.  Nowhere does it mentions that you must click the sign and then click the head if it says head not set to get the signs to work.  Not trying to bug you about this but I can see a lot of people not using this feature and thinking it is broken.
