### ISSUE TITLE
How to add player points/votes?

### ISSUE THREAD

**Issue by Cakellamc** [BenCodez/VotingPlugin#821]
**Versions**
5.21.3 and spigot 1.14

**Context**
I would like to manually give players votes/points but this command does not exist anymore: /vote givepoints

**Comment by BenCodez** [comment]
That's to transfer points between players (if enabled)

/av User (player) SetPoints (number)

**Comment by Cakellamc** [comment]
Thank you so much and such a quick response omg <3
