### ISSUE TITLE
How to add/set player votes?

### ISSUE THREAD

**Issue by Cakellamc** [BenCodez/VotingPlugin#822]
Sorry, new to GitHub, I closed the other thread way too soon :(

I am using autorank to check for votes, and I believe it looks for the vote stat and not the point one. The last command you told me added points to the player but it doesnt add to the vote stat in order to rank them up.

Is there a way to add votes for players? (our votifier was not setup so players missed out on two vote sites and I am trying to give them the points for voting even though it did not register)

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/wiki/Commands-&-Permissions

**Comment by Cakellamc** [comment]
I tried settotal alltime but it didnt add any votes

**Comment by Cakellamc** [comment]
Yes, did that

**Comment by BenCodez** [comment]
What are you trying to set? Month total? Does it actually set the value? /vote total?

**Comment by Cakellamc** [comment]
Hmm I seemed to have set them... Do you know if auto rank will allow these set votes?

**Comment by BenCodez** [comment]
No idea.
