### ISSUE TITLE
version 1.8.8

### ISSUE THREAD

**Issue by arthur9874** [BenCodez/VotingPlugin#823]
**Versions**
Plugin version and spigot version
1.8.8
**Relevant information**
Configs that relate to the issue in a pastebin.
i asked you for version 1.8.8 and you said "Read the plugin page" but i cant find anything in pages .
**Context**
Context about the question/concern
can you help me with version 1.8.8 please ? 
i really need help and your plugin is nice .
+sorry for my bad english .

**Comment by BenCodez** [comment]
From the plugin page:

Use v5.13.6 for 1.12 and older versions, support WILL NOT be provided for these versions, so please don't ask for support for these versions.
