### ISSUE TITLE
AllSites Reward Triggers more than it should.

### ISSUE THREAD

**Issue by adamromulus** [BenCodez/VotingPlugin#826]
**Versions**
Latest + Paper 1.15.2

**Describe the bug**
One of the five server lists we use has a vote time of 12 hours, while the others are all 24. We recently introduced a temporary "AllSites" reward to give somebody a bonus when all sites are voted on. If someone votes again on the 12 hour site, they get another AllSites reward. This isn't supposed to happen. Can I force wait times of 24 hours?

**Comment by BenCodez** [comment]
Set waituntilvotedelay to true on the votesite.

**Comment by adamromulus** [comment]
Thanks!
