### ISSUE TITLE
Reload plugin issue

### ISSUE THREAD

**Issue by HiMyNameIsBoxxy** [BenCodez/VotingPlugin#827]
Using the latest version.
Whenever I reload my config my top monthly voter gets reset and rewards are being given out. How?

https://pastebin.com/HMPiMmZS

**Comment by BenCodez** [comment]
Console log? Are you messing with ServerData.yml?

**Comment by HiMyNameIsBoxxy** [comment]
https://pastebin.com/9VhGuPCn

**Comment by HiMyNameIsBoxxy** [comment]
just messing with the config

**Comment by BenCodez** [comment]
Failed to load player data for 03db8e9f-0e77-4206-ab1e-3150db74dd5b

Could not save MonthlyAwards_1_Rewards.yml

I think you have some file issue.

**Comment by HiMyNameIsBoxxy** [comment]
What can I do?

**Comment by BenCodez** [comment]
No idea, not much I can do.

**Comment by HiMyNameIsBoxxy** [comment]
Do you know the which file may be the issue?
Because this happened after I changed config

**Comment by BenCodez** [comment]
It's not just one file, there is many. Does the server have space?

**Comment by HiMyNameIsBoxxy** [comment]
Yes 66gb left

**Comment by BenCodez** [comment]
Yeah, no idea. Your the only one having this issue. Switch to MySQL if your using SQLITE?

**Comment by HiMyNameIsBoxxy** [comment]
I will do restart later and see if the issue persists.

**Comment by HiMyNameIsBoxxy** [comment]
VotingPlugin:
  Version: 'git-Paper-188 (MC: 1.15.2)'
  ServiceSites:
  - PlanetMinecraft.com
  - MinecraftServers.org
  - Minecraft-MP.com
  - MCSL
  - TopG.org
PluginVersions:
  VotingPlugin: 5.21.3
PrevDay: 29
PrevWeek: 22
Month: May

**Comment by HiMyNameIsBoxxy** [comment]
I am still getting the issue. I started happening after May.

**Comment by BenCodez** [comment]
Is it constantly resetting? There will be info in console if that's the case.

**Comment by HiMyNameIsBoxxy** [comment]
It resets when I reload the plugin which never happened before.

**Comment by HiMyNameIsBoxxy** [comment]
https://pastebin.com/vDizH2Sf

**Comment by BenCodez** [comment]
java.io.FileNotFoundException: plugins/VotingPlugin/Rewards/ExampleAdvanced.yml (Permission denied)

[SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)

You have a lot of problems to sort out.

**Comment by HiMyNameIsBoxxy** [comment]
why is it being denied? And why is it trying to find ExampleAdvanced.yml

**Comment by BenCodez** [comment]
Because of the reload. But I can't do anything to help you.

**Comment by HiMyNameIsBoxxy** [comment]
will reinstalling the plugin and then keeping config and userdata, reward files help?

**Comment by BenCodez** [comment]
Probably not, contact your host (if you have one)
