### ISSUE TITLE
"InventoryCloseEvent may only be triggered synchronously" error - Causes loss of player data

### ISSUE THREAD

**Issue by JarrettMorrison** [BenCodez/VotingPlugin#830]
When using the votegui, going to vote shop, attempting to purchase something, and after verifying the purchase I get the following error sent to console: https://pastebin.com/VATei9jD

Config for vote shop: https://pastebin.com/dGDkT19S

My main issue with this is not that I am getting this error, but whichever player attempts to make the purchase (either successfully or unsuccessfully) their data gets wiped from the database completely. Their votingpoints get reset to 0, their next vote grants them first vote ever rewards, and all their Next/Last/Total/Top/Today data is gone.

I was able to confirm that this issue only happens when I have "VoteShopRequireConfirmation" set to true. When set to false, I do not receive the console error and I do not see player data wiped.

**Comment by JarrettMorrison** [comment]
Plugin version: 5.21.3 downloaded from Spigot
Server is running Paper 1.15.2 build 332

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

should fix it

**Comment by JarrettMorrison** [comment]
Just tested it and it's working as expected :) Thank you.

**Comment by JarrettMorrison** [comment]
Same warning is happening on dev build 193 when clicking on the "URL" option in the votegui. Not severe because it is not wiping data.

**Comment by BenCodez** [comment]
Send the warning?

**Comment by JarrettMorrison** [comment]
https://pastebin.com/c5DVun0S

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should fix that.
