### ISSUE TITLE
Can't get BungeeCord Advanced Setup to work, tested for many hours.

### ISSUE THREAD

**Issue by ablac** [BenCodez/VotingPlugin#831]
**Versions**
5.21.3

**Relevant information**
BungeeCord - https://pastebin.com/y1c3AZYv

Lobby - https://pastebin.com/4nH0ku7R

Survival - https://pastebin.com/mDzrWLZa

Creative - https://pastebin.com/qATsiQPW

I have Redacted IP's as well as MYSQL Passwords.
Please note that anywhere it says My(Server)IP(External Server) or My(Server)IP(LocalHost) that is replaced with the IP address of that server, I did not use Localhost, or 127.0.0.1 for any of the configs, they are all external/internal facing IP's.

All 3 of my servers are able to communicate with each other, with an average ping between servers of .002MS, as well as ports 8192-8196 are open on all 3 servers. I am running my MC Server through CloudFlare but that shouldn't effect plugin due to using Absolute IP's

When running /votingpluginbungee test ablac PlanetMinecraft.com I get an error in my bungee cord server - https://pastebin.com/DTRsKjNZ

My MYSQL database is setup correctly, and i have verified all 4 VotingPlugin's are able to connect to the MYSQL database.

NuVotifier is only installed on BungeeCord
VotingPlugin is installed on all 3 MC servers as well as my BungeeCord
I have copied the SecureKey from the BungeeCord Server to all 3 MinecraftServers so there all the same.

Server Versions:
Paper: git-Paper-328
WaterFall: Build 346
NuVotifier: 2.60
 
**Context**
After countless changing and modifying of the config, I am still getting this error. please let me know if anything what I am doing incorrectly.

**Comment by BenCodez** [comment]
You only list the one spigot server in the spigot config. See the default
config for that.

**Comment by ablac** [comment]
Oh! So in the Spigot config sits only suppose to be itself not all 3 servers, I get it, the wiki was mildly confusing, it looks like it’s supposed to be the same information that’s in the Bungee section

**Comment by ablac** [comment]
I updated the config, and running /votingpluginbungee test ablac planet Minecraft.com gives no message and no error, does this mean it is correct?

**Comment by BenCodez** [comment]
You should see something on the other server in console.

If you want you try the dev build at Ben12345rocks.com and do
/VotingPluginbungee status, will return status okay for every server if
it's good

**Comment by ablac** [comment]
So I updated to newest dev build, doing /votingpluginbungee test Ablac planetMinecraft.com returns nothing in console or in game.

Doing /votingpluginbungee status returns the same errors I was getting above in only the BungeeCord server.

**Comment by BenCodez** [comment]
It's /VotingPluginbungee vote (player) (site)

The errors say it can't connect between servers

**Comment by ablac** [comment]
In the morning I’ll run a Ping on there open port to verify, but I unblocked those ports in my firewalls and all other plugins are able to communicate 🧐 question, why not use the BungeeCord delivery service and MYSQL instead of your own port?

**Comment by BenCodez** [comment]
Those work different what votingplugin is using. It's more reliable and doesn't have the issues with pluginmessaging that requires a player online.

I think waterfall has a system that I might add support

**Comment by ablac** [comment]
So I pinged the other servers, and unfortunatly it doesn’t seem like there’s a way to open the ports currently I added the IP’s to my trusted section of the firewall, as well as opened the ports in the public section of Firewalld, I also added the IP’s and Ports to my IPTables, and restarted all Of my Boxes and it’s still not allowing traffic through any of the 5 ports I opened 1892-1896 so having waterfall messaging support would be greatly appreciated :) cause I’m using waterfall :D

**Comment by BenCodez** [comment]
I'll take a look.

**Comment by BenCodez** [comment]
Do you happen to know the api? I never messed with waterfall

**Comment by ablac** [comment]
No I’m just about to start teaching myself java :( but I did find the api https://papermc.io/javadocs/waterfall/

**Comment by BenCodez** [comment]
I guess it was redisbungee I was thinking, so might not be an option. Look at the sockets I guess? Unless you know of another system that works that I could implement.

**Comment by ablac** [comment]
hmm, what if you use the BungeeSystem if the player is online, and implement a Cache of sorts though MYSQL or Flat Files when there offline then wait till the player is online, I don't care if it waits till the come online again to tell everyone they voted, and im sure a lot of server owners dont mind if when they come online it rewards them for the votes then either.

**Comment by BenCodez** [comment]
It was easier to make a socket system then to deal with that, might add that as an option in a future update.

**Comment by BenCodez** [comment]
After some looking into, seems like using sockets is the best way at the moment, As it is the most reliable system (once setup) that I know of.

**Comment by ablac** [comment]
Hey @Ben12345rocks Sorry for late response, its been a crazy few days, wanted to follow up on the sockets :D see if this is working?

**Comment by BenCodez** [comment]
Sockets are working just fine, just needs to be configured correctly, which
isn't always easy

**Comment by ablac** [comment]
:D let me know :) cause I checked everything and even completely disabled my firewall and it’s still
Being blocked for some reason :(

**Comment by BenCodez** [comment]
Use external ip? There isn't anything I can do to just fix it

**Comment by BenCodez** [comment]
In theory this should show the port open when using this website:
https://networkappers.com/tools/open-port-checker

See if that does anything.
