### ISSUE TITLE
How to chance color of the number and link of the votesite

### ISSUE THREAD

**Issue by GitHubLives** [BenCodez/VotingPlugin#834]
![javaw_eSDZIE1Iei](https://user-images.githubusercontent.com/66514137/83941393-41202400-a7eb-11ea-9198-254978b27bb3.png)
![dllhost_qdkjF9C9gn](https://user-images.githubusercontent.com/66514137/83941434-86dcec80-a7eb-11ea-895d-1fc6a5da6b1b.png)

Newest Plugin version & Paper Spigot version.

I'm wondering how I could change the color from RED / Dark red to the picture I've sent  below.

**Comment by BenCodez** [comment]
Config.yml under format.

**Comment by morjanmihail** [comment]
The color on link doesn't work:
![image](https://user-images.githubusercontent.com/13481999/85203655-deb14280-b317-11ea-96b8-51b689e5b109.png)

Is there any other way of doing it properly?
(1.15.2 paper + last version of plugin)

**Comment by BenCodez** [comment]
@morjanmihail 
Configs?

**Comment by morjanmihail** [comment]
Tried with the default ones, changed only the URLText. Same result. Or we can add color in VoteSites.yml?

**Comment by BenCodez** [comment]
@morjanmihail 
Show me your config?

**Comment by morjanmihail** [comment]
My last version is this.
[config.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4808467/config.txt)

Sry for my previous messed edit :)

**Comment by BenCodez** [comment]
Pastebin...
