### ISSUE TITLE
Votes autocompleting usernames and ignoring usernames that start the same

### ISSUE THREAD

**Issue by Th3l0stSpart4n** [BenCodez/VotingPlugin#835]
**Versions**
VotingPlugin 5.21.2
Tuinity 62cb704 (branch of paper)

**Relevant information**
VotingPlugin config
https://pastebin.com/5v3sf5mH

extradebug log, 2 relevant lines of info

[20:21:49] [Craft Scheduler Thread - 21/INFO]: [VotingPlugin] ExtraDebug: Player Demihe does not exist
[20:21:49] [Craft Scheduler Thread - 21/INFO]: [VotingPlugin] Debug: Offline vote set for Demihe (fd231b61-ea71-42f1-8174-d8390a899daa) on minecraftmp

**Context**
One of the users on our server brought forth the issue that votes on his second account were going to his first. For anonymity we'll call their usernames insertnamehere and insertnamehere2701. Votingplugin seems to prioritize the longer username with the numbers at the end as if it was auto-completing the usernames.

**Comment by BenCodez** [comment]
It should go by what the name is stored in data. /av user (name) viewdata

**Comment by Th3l0stSpart4n** [comment]
Doing a test using my personal account Demiheart, there is nothing stored for a user using "/av user Demihe viewdata". After voting on one of the sites already configured using the name "Demihe" it created a data entry that has the same uuid as "Demiheart". This is confirmed with /av user (name) viewdata.

**Comment by BenCodez** [comment]
Should be impossible to have duplicate uuids, manually edit the name/uuid?

**Comment by Th3l0stSpart4n** [comment]
Doesn't change that new entries are consistently behaving the same way. A vote for "gill" finds the uuid for "gilly" and uses that. How would it even be finding the correct uuid without there being some kind of typo checker that autocompletes to the longest name?

**Comment by BenCodez** [comment]
This solve it?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Th3l0stSpart4n** [comment]
Yes, thank you
