### ISSUE TITLE
.

### ISSUE THREAD

**Issue by vastolf** [BenCodez/VotingPlugin#836]

**Comment by BenCodez** [comment]
Console log of repeat rewards? Also pastebin your files, easier to read

**Comment by astolfivincent** [comment]
@Ben12345rocks the output is essentially this over and over again:

[10:33:27] [Server thread/INFO]: CONSOLE issued server command: /eco give PLAYER 125
[10:33:38] [Server thread/INFO]: CONSOLE issued server command: /adjustlandclaimblocks PLAYER 100
...

That is on Activation of the LegendReward you see in my VoteSites.yml, but it is happening with different reward levels as well.. Will update these to pastebin now

**Comment by BenCodez** [comment]
Set debuglevel to EXTRA and try to recreate this, then the log of that happening.

**Comment by astolfivincent** [comment]
So the error seems to have been triggered when I voted on https://minecraft-mp.com/ which I've set up with votifier, so it may be something on their end considering that the issue just started last night/today. Here are my logs:

https://pastebin.com/6QTynwD4

**Comment by BenCodez** [comment]
Can I see the AllSites reward?

**Comment by astolfivincent** [comment]
@Ben12345rocks 

# Directly defined reward file. ANY EDITS HERE CAN GET OVERRIDDEN!
Messages:
  Player: '&fYou voted on all sites in 1 day! Enjoy a bonus reward [&a+$75&f, &6+50
    Land Claim Blocks'
Commands:
- adjustbonusclaimblocks %player% 50
- eco give %player% 75
Rewards: allsites
DirectlyDefinedReward: true

**Comment by astolfivincent** [comment]
@Ben12345rocks also at one point, I had two instances of Minecraft MP tracked in the VoteSites.yml, as I added it manually and an automatic one was added after a vote on that site by a player. I've since removed the second instance of MMP and things have been working fine, up until a couple days ago. Just wanted to mention that in case it could have something to do with the issue.

**Comment by BenCodez** [comment]
Why is this within the allsites reward? 

    Rewards: allsites

As soon as you vote on allsites it will cause a loop.

Your votesite issue is due to not having the correct service site, so allsites couldn't be reached, thus not causing a loop. I'll note to have a failsafe to prevent infinite loops.

**Comment by astolfivincent** [comment]
Thank you
