### ISSUE TITLE
HELP ME SETUP BUNGEECORD REWARDS

### ISSUE THREAD

**Issue by XBeastXmc** [BenCodez/VotingPlugin#837]
Hi!
I have problems with setuping rewards on my bungeecord server. Can you help me what to do,,, i tried so many things and still dont get rewards on vote... 

This is my sites config setup... 
This is under my survival server
![Capture](https://user-images.githubusercontent.com/66681958/84155244-68375980-aa68-11ea-9919-9b6143b4e5bc.PNG)

**Comment by BenCodez** [comment]
What bungee setup are you using?

**Comment by BenCodez** [comment]
It's also Commands and Console, case sensitive

**Comment by XBeastXmc** [comment]
The lastest bungee jar file

![image](https://user-images.githubusercontent.com/66681958/84158631-61124a80-aa6c-11ea-80d8-63a982ba92f8.png)

**Comment by BenCodez** [comment]
Which setup from here?
https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by XBeastXmc** [comment]
First with bungee voting and spigot voting with nuvotifier

**Comment by XBeastXmc** [comment]
in bungeecord's plugin file needs to be secret key too?cause i dont have it. And which ports i need to add in configs? server ip ports or votifer ports?

**Comment by BenCodez** [comment]
1. The wiki page explains about the secretkey.key file
2. An ip/port that isn't used (just like votifier)

**Comment by XBeastXmc** [comment]
![image](https://user-images.githubusercontent.com/66681958/84272720-13f6ad00-ab2e-11ea-8257-f1bc4d43ddd4.png)


How can i setup votifier on only bungee server if i need to add votifier tokens to bungee votifier from each server? but on wiki i see bungee nuvotifier each server no votifier only voting plugin with database... i dont need to add token key if i have this setup?

**Comment by BenCodez** [comment]
You don't need to do any forwarding if you do the first setup.
