### ISSUE TITLE
Empty rewards menu

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#838]
**Versions**
Paper 345
Version: 5.1.23

**Describe the bug**
When I open /voterewards menu there is just grass and crafting table without custom name and lores.... and when I click on one of them, it's empty.

**To Reproduce**
1. Execute /voterewards
2. See normal MC items without custom names and lores
3. Click on them

**Expected behavior**
It should show normal item names and lores.... like what votesite is it and when player clicks on it, it should show rewards.

**Screenshots/Configs**
https://imgur.com/a/QST7iha

**Additional context**

**Comment by BenCodez** [comment]
You need to manually configure that GUI system. Hardly anyone uses it

**Comment by bobhenl** [comment]
And why it isn't created automatically? :(

**Comment by BenCodez** [comment]
Because no one uses it? And it's really hard to do.

**Comment by bobhenl** [comment]
So players shouldn't use /vote reward and the reward should be surprise?

**Comment by BenCodez** [comment]
If you want to use it, then use and configure it. I don't know why I should spend many hours to save a few minutes for something not many people use. You could just tell them what they get.

**Comment by bobhenl** [comment]
Ok, thanks.

**Comment by bobhenl** [comment]
Btw couldn't you add way to set custom command on opening rewards menu, for ex. I could use /kitpreview <name> <player> and it will show him vote rewards from kit.

**Comment by BenCodez** [comment]
Use a commands alias

**Comment by bobhenl** [comment]
But if I have there two votesites? How I will do it with two of them?

**Comment by BenCodez** [comment]
Make 2 commands?

**Comment by bobhenl** [comment]
And could they overwrite somehow submenus from /votereward?

**Comment by BenCodez** [comment]
What do you mean by that?

**Comment by bobhenl** [comment]
I mean for ex. players will use:
1. /vote and there they click on vote site with right click -> it should open vote reward, but it opens instead kit. what's command for it? How do I overwrite it with aliase?
2. If I should do this with /votereward and then overwrite submenus somehow with kits?

**Comment by BenCodez** [comment]
1. That's not possible exactly. 
2. Just use a command alias, google search it, it's built into spigot. Or create your own inventory.
