### ISSUE TITLE
Curious what this error means

### ISSUE THREAD

**Issue by Sotlol1** [BenCodez/VotingPlugin#839]
PL version: 5.21.3
Serv version: Paper 334. 

I'm curious what this error means "https://pastebin.com/ZwBduBqN" plugin worked fine a few hours ago and now it went down for this.

**Comment by BenCodez** [comment]
Redownload? If not I got no idea.

**Comment by Sotlol1** [comment]
Did some checks. It seems to be when it's connected to a MYSQL database. I have switched between three DBs even one from outside of my server and that one still throws the same error. 2 of those DBs were completely clean with nothing on them.

I redownloaded the plugin aswell.

**Comment by BenCodez** [comment]
Try a different java version?

**Comment by AngieC233** [comment]
PL version: 5.21.3
Server version: Latest Paper version git-Paper-350 (MC: 1.15.2)

Having similar issues and errors spamming over console.  Was working before and then suddenly errors showing.

https://pastebin.com/kDjJjJnH

**Comment by BenCodez** [comment]
@AngieC233 
http://ben12345rocks.com/job/VotingPlugin/

that better? If not use mysql.

**Comment by AngieC233** [comment]
It works fine after I deleted and re download jar.  Probably got corrupted
