### ISSUE TITLE
Quick Question about milestone rewards.

### ISSUE THREAD

**Issue by Kyles1201** [BenCodez/VotingPlugin#841]
VotingPlugin Version: 5.21.3

On my server I want to be able to have a monthly reward system that has different milestones that give rewards, and it resets monthly.

And also a total vote reward system that never resets, but also gives out milestone rewards.

is this possible?

**Comment by BenCodez** [comment]
Milestones can reset monthly already. The different milestone thing might be difficult, either do it manually or have some system to figure out when a player gets a milestone and will give a different one next time?

There is dual milestone system that can do a monthly version and non monthly version, cumulative is on a different system, maybe that works?

**Comment by Kyles1201** [comment]
Is there anyway to make cumulative reset monthly?

**Comment by BenCodez** [comment]
No, that's not possible

**Comment by Kyles1201** [comment]
Will Cumulative only give out the reward once if votesinsameDay and votesinsameWeek = false?

Like if there is a reward at 5, 25, and 50 Votes, and a player votes 5 times and gets the first reward. I dont want that player to be able to get that same reward ever again.

**Comment by BenCodez** [comment]
It will give every x number of votes using whatever total is selected using those options.

**Comment by Kyles1201** [comment]
For "ResetMilestonesMonthly:" can is be set for individual milestones or will it set for the entire milestone list.

**Comment by BenCodez** [comment]
All milestones

**Comment by Kyles1201** [comment]
ok thx.
