### ISSUE TITLE
Vote Reminder

### ISSUE THREAD

**Issue by TorrenStark** [BenCodez/VotingPlugin#843]
I've been trying to set up vote reminders for quite some time in the config file, ive been having trouble doing that because the messages are not showing up in the chat, can someone tell me how the vote reminder works, and instructions on how it can be done.

**Comment by BenCodez** [comment]
Configs, console logs? Some info on what isn't working exactly?

**Comment by TorrenStark** [comment]
here is the config file for the vote remind
VoteReminding:

  # Enable vote reminding

  # This will remind player when he can vote on all sites

  # Requires VoteDelays to be setup properly

  # Use /vote next to see when you can be reminded

  # Players require the perm "VotingPlugin.Login.RemindVotes" or "VotingPlugin.Player"

  Enabled: true



  # Whether or not to remind only once when the player can vote

  # Does not apply to login reminds.

  RemindOnlyOnce: true



  # Will remind player on login if he can vote

  # Ignores value above

  RemindOnLogin: true



  # Delay to remind votes in minutes

  # Only works if above is false

  RemindDelay: 30



  # Run reward files on remind

  # By default, the reward file will be created for you

  # and have the default message

  # Edit the message at AdvancedCore/Rewards/Remind.yml (or any other reward listed)

  # Can add titles and more in the reward file

  Rewards:

    Messages:

      Player: '&aRemember to vote!'

    Title:

      Enabled: false

      Title: '&cRemember to vote!'

      SubTitle: '&aType /vote'

      FadeIn: 10

      ShowTime: 50

      FadeOut: 10

    ActionBar:

      Message: '&cRemember to vote'

      Delay: 30

**Comment by TorrenStark** [comment]
VoteReminding:

  - Enable vote reminding

  - This will remind player when he can vote on all sites

  - Requires VoteDelays to be setup properly

  - Use /vote next to see when you can be reminded

  - Players require the perm "VotingPlugin.Login.RemindVotes" or "VotingPlugin.Player"

  Enabled: true



  - Whether or not to remind only once when the player can vote

  - Does not apply to login reminds.

  RemindOnlyOnce: true



  - Will remind player on login if he can vote

  - Ignores value above

  RemindOnLogin: true



  - Delay to remind votes in minutes

  - Only works if above is false

  RemindDelay: 30



  - Run reward files on remind

  - By default, the reward file will be created for you

  - and have the default message

  - Edit the message at AdvancedCore/Rewards/Remind.yml (or any other reward listed)

  - Can add titles and more in the reward file

  Rewards:

    Messages:

      Player: '&aRemember to vote!'

    Title:

      Enabled: false

      Title: '&cRemember to vote!'

      SubTitle: '&aType /vote'

      FadeIn: 10

      ShowTime: 50

      FadeOut: 10

    ActionBar:

      Message: '&cRemember to vote'

      Delay: 30

**Comment by TorrenStark** [comment]
the problem is not that its not working, the problem is, those messages are not showing up, not even on the console.

**Comment by BenCodez** [comment]
1. Pastebin?
2. Do you have the permission?

**Comment by TorrenStark** [comment]
I have every permission listed

**Comment by BenCodez** [comment]
pastebin?

**Comment by TorrenStark** [comment]
[permissions.zip](https://github.com/Ben12345rocks/VotingPlugin/files/4767777/permissions.zip)

**Comment by TorrenStark** [comment]
here are the permissions

**Comment by BenCodez** [comment]
Pastebin the config, I don't need to see your permissions, never asked for them.

**Comment by TorrenStark** [comment]
[config.zip](https://github.com/Ben12345rocks/VotingPlugin/files/4767784/config.zip)

**Comment by TorrenStark** [comment]
the config is here

**Comment by BenCodez** [comment]
Is the server getting the vote? Did you trigger a vote on a site? Can you vote on all sites (according to the plugin)?

**Comment by TorrenStark** [comment]
Yes

**Comment by BenCodez** [comment]
Yes what?

**Comment by TorrenStark** [comment]
All the vote sites work, getting the rewards, the broadcast works, its just the reminder i cant do.

**Comment by BenCodez** [comment]
It only reminds if you can vote on all sites.

**Comment by TorrenStark** [comment]
alright
