### ISSUE TITLE
Trying to make the reward for voting 5 diamonds for each link.

### ISSUE THREAD

**Issue by MarioMax05** [BenCodez/VotingPlugin#844]
This is my code, I am looking to make it give the player 5 diamonds every time they vote for each site. I'm kinda new to this, thanks for anyone willing to help :)

VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  ExampleVoteSite:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: true
    Enabled: true
    
    # Display name of voting site
    Name: 'PlanetMinecraft'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'PlanetMinecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="https://www.planetminecraft.com/server/pepsi-land-anarchy/vote",url="URLHERE"]'
    VoteURL: 'https://www.planetminecraft.com/server/pepsi-land-anarchy/vote'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Use to have a minute votedelay
    #VoteDelayMin: 30
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    Item:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'say hello'
      # Send player a message
      Messages:
        Player: 'Thank you for voting!'
  # Site 2 example
  Site2:
    Enabled: true
    Name: 'MC-Server-List'
    ServiceSite: 'minecraft-server-list.com'
    VoteURL: 'https://minecraft-server-list.com/server/462178/vote/'
    VoteDelay: 24
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next will be attempted
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'Thank you for voting!'
  # Site 3 example
  Site3:
    Enabled: true
    Name: 'MinecraftMP'
    ServiceSite: 'minecraft-mp.com'
    VoteURL: 'https://minecraft-mp.com/server/259853/vote/'
    VoteDelay: 24
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next will be attempted
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'Thank you for voting!' 
  # Site 4 example
  Site4:
    Enabled: true
    Name: 'MC Servers'
    ServiceSite: 'minecraftservers.org'
    VoteURL: 'https://minecraftservers.org/vote/587492'
    VoteDelay: 24
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next will be attempted
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'Thank you for voting!'  
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by BenCodez** [comment]
Pastebin that.

**Comment by MarioMax05** [comment]
https://pastebin.com/kY7mP3RW

here you go, sorry about that

**Comment by BenCodez** [comment]
Rewards:
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 5

Something like that should work.

**Comment by MarioMax05** [comment]
I'll give it a shot, thanks :)

**Comment by MarioMax05** [comment]
Hey, it's not working. This is what I did: https://pastebin.com/MMej4RSJ

**Comment by BenCodez** [comment]
https://pastebin.com/gbTMRYyv

**Comment by MarioMax05** [comment]
Sorry for the late response, this is what I have and I'm still having trouble. Sorry that I keep asking for help..

**Comment by MarioMax05** [comment]
https://pastebin.com/0dKNn5WA

**Comment by BenCodez** [comment]
Does the server get the vote? Check console on a vote. Does it work with /av vote?

**Comment by MarioMax05** [comment]
It shows that someone made the command to vote, but doesn't know they voted.

**Comment by BenCodez** [comment]
Then your issue is with votifier right now.

**Comment by MarioMax05** [comment]
Do you have an idea of what I could do to fix it?

**Comment by BenCodez** [comment]
https://mctools.org/votifier-tester

Try new host/port?

**Comment by MarioMax05** [comment]
Apparently I didn't have votifier at all. I will get back to you when I get it up and working.

**Comment by MarioMax05** [comment]
I have it installed and put on the right port, but do I put the public key in VotingPlugin? I also did the test and it went through

**Comment by BenCodez** [comment]
No, just the vote sites.

**Comment by MarioMax05** [comment]
Oh, what about the host in the config menu, anything go there?

**Comment by BenCodez** [comment]
That's for a bungee setup, don't use that unless you plan to for the first setup here:
https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by MarioMax05** [comment]
Just got it working. Thank you!!
