### ISSUE TITLE
Question about EverySiteReward in votesites.yml

### ISSUE THREAD

**Issue by ImToxik** [BenCodez/VotingPlugin#846]
**Versions**
Plugin version and spigot version

Plugin - 5.21.3
PaperSpigot - 1.15.2

**Relevant information**
Configs that relate to the issue in a pastebin.

VoteSites.yml - https://pastebin.com/VT3XxSva
Config - https://pastebin.com/5VZJ2vnv
Rewards/default.yml - https://pastebin.com/PKx42Tza

**Context**
Context about the question/concern
 
My primary confusion is just over the EverySiteReward option in votesites. I made a reward file named 'default.yml' and added it next to the everysitereward option, saved, reloaded config, and did /av vote [my name] [site]. It thanked me for voting on [site] like expected but did not generate the command or items from default.yml. Can someone tell me where I'm going wrong?

**Comment by ImToxik** [comment]
Also, my votesites are no longer showing in /vote, so I must've messed that up entirely. Appreciate the help in advance.

**Comment by BenCodez** [comment]
https://pastebin.com/L604wuzR

Try that.

**Comment by ImToxik** [comment]
Thank you so much. I feel like an idiot for not noticing that ' missing. How about the config file? When I run it through an YML checker it shows I have improper indentation on line 652 but when I try to fix it it just keeps shifting down the file, kinda worried I'll mess up worse and wreck the whole file

**Comment by BenCodez** [comment]
You had a missing ' :)

Edit: I missed your first sentence, I got too many conversations going :)

**Comment by ImToxik** [comment]
No worries! I appreciate the help a lot man, I'm re-learning this a bit at the moment lol.

**Comment by ImToxik** [comment]
> You had a missing ' :)
> 
> Edit: I missed your first sentence, I got too many conversations going :)

Any chance you could point out what I did wrong in votesites.yml at the bottom with the everysitereward: Default? Do I need to add default in differently? Or did I format default.yml wrong?

Thanks again in advance and sorry for the bother!

**Comment by BenCodez** [comment]
Try it with:

    EverySiteReward:
    - default (case sensitive name)

**Comment by ImToxik** [comment]
> EverySiteReward:
> - default

Is /av vote [my name] [site] supposed to generate the rewards from Default.yml when the vote goes through? Thank you so much for this help again man

**Comment by ImToxik** [comment]
> /av vote will trigger it.

okok so my console says it cant load default.yml when i /av reload, and ymlchecker says it's proper yml. Last thing you mind helping me with?

**Comment by BenCodez** [comment]
Console log?

**Comment by ImToxik** [comment]
> Console log?

https://pastebin.com/nVRgb1Cy

From the /av reload at top to /av vote toxik  and response at the bottom

**Comment by BenCodez** [comment]
You used a tab instead of spaces on line 4

https://yaml-online-parser.appspot.com/

**Comment by ImToxik** [comment]
> You used a tab instead of spaces on line 4

I'm an idiot for that, I can't believe I did that. Oh well, I appreciate you using your eyes better than me man. It's running just like I want, now. I appreciate your help greatly. Dropping a donation for your support and patience, thanks again man.
