### ISSUE TITLE
Can't remove 1000$ base voting reward

### ISSUE THREAD

**Issue by bastobasto** [BenCodez/VotingPlugin#847]
**Context**
How to remove it ? I can't find and it's kind of extremely annoying

**Comment by BenCodez** [comment]
There is no default reward for $1000.

**Comment by bastobasto** [comment]
How to remove it then ? There is 1000$ reward for every vote yet I don't want it, and I didn't set it

Its quite a problem because  I use gringotts, and 1000$ is a fortune

**Comment by BenCodez** [comment]
Probably another plugin if you didn't set it.
