### ISSUE TITLE
Voting keeps giving you the default 1 diamond when I want it to give you 5 emerald.

### ISSUE THREAD

**Issue by HyenaGodKing** [BenCodez/VotingPlugin#848]
**Versions**
Plugin version: 5.21.3 and paper version: 343

**Relevant information**
Examplebasic: https://pastebin.com/EwLsPwd9
Voting sites: https://pastebin.com/pUxVX1fd
**Context**
I'm unable to make it so that when people vote for the server they receive 5 emeralds. Unfortunately when they vote they only receive the default reward which is 1 diamond.

**Comment by BenCodez** [comment]
Do you have CMI?

**Comment by HyenaGodKing** [comment]
Yes I have CMI

**Comment by BenCodez** [comment]
Disable the diamond reward in CMI.
