### ISSUE TITLE
Votes Reset and Exception Error

### ISSUE THREAD

**Issue by Cakellamc** [BenCodez/VotingPlugin#849]
All of a sudden player votes were reset to 0 and I am receiving the following error:
https://pastebin.com/vSEFyZe7

**Comment by BenCodez** [comment]
/av reload or restart fix it? If not switch to MySQL

**Comment by Cakellamc** [comment]
A plugin reload and restart did not fix it. I tried switching to MySQL but then all the data is wiped again. I figured out that only some players had their data reset to 0, so moving to MySQL resets everyone

**Comment by BenCodez** [comment]
You can copy data over with /av convertfromdata SQLITE

**Comment by Cakellamc** [comment]
Okay I have now converted over to MySQL successfully. Is there anyway to get back the old voting data? Or at least see how many votes these certain players had?

**Comment by BenCodez** [comment]
That command will copy all the data there is in users.db file.

**Comment by Cakellamc** [comment]
Yes, but I'm referring to some of the data that got reset to 0

**Comment by BenCodez** [comment]
If you have backups enabled (within votingplugin or without) there might be something.

**Comment by Cakellamc** [comment]
I have a backup of the users.db, but how would I restore only the reset players data? Because players have voted since them so I don't want to back-peddle those players

**Comment by BenCodez** [comment]
There isn't really a way without some database viewer
