### ISSUE TITLE
how to run commands with voteshop

### ISSUE THREAD

**Issue by MatthewXcap** [BenCodez/VotingPlugin#850]
**Versions**
5.21.3, 1.15.2 paper spigot

**Relevant information**
https://pastebin.com/1Xxb695G

**Context**
I was wondering if someone could write out an example voteshop config thing where I can see how exactly I can have commands run for a player when they buy something from the voteshop. Like say I wanted to give a person /fly if they were to spend 50 points on it in vote shop, how would I do that?

**Comment by MatthewXcap** [comment]
nevermind I figured it out. Here is an example for anyone trying to run commands with their voteshop: https://pastebin.com/Bbx4a4u1

**Comment by BenCodez** [comment]
All good then?
