### ISSUE TITLE
VoteURL Text/URL doesn't work in config

### ISSUE THREAD

**Issue by LordOmen** [BenCodez/VotingPlugin#851]
**Versions**
5.21.3

**Relevant information**
[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"] doesn't work when added to the config.  It just displays that exact text in the chat box.

**Context**
Context about the question/concern

**Comment by BenCodez** [comment]
Just enable ForceLinks, might have to add it, check the default config
