### ISSUE TITLE
Reward with a crate key?

### ISSUE THREAD

**Issue by TheAdorkable1** [BenCodez/VotingPlugin#853]
**Versions**
Plugin version and spigot version
1.15.2

So I'm trying to set up the voting reward as a vote key with the plugin Crates Plus.
The command to issue a key is /crates key {player} Vote
I've tried every way I can to get this to work but the only reward at all I can get is the text that reads thank you for voting.
Here is what I have. Any assistance would be greatly appreciated. I've been trying to figure this out for a week!

![Annotation 2020-06-25 003343](https://user-images.githubusercontent.com/67204910/85660750-9aa5a100-b67b-11ea-9db5-5acd477544e9.jpg)

**Comment by BenCodez** [comment]
No / on commands

**Comment by TheAdorkable1** [comment]
took out the / and it still doesn't work >.<

**Comment by TheAdorkable1** [comment]
Even just giving a tripwire hook thats enchanged and name "Vote Crate Key" should work but I can't get any rewards to work

**Comment by BenCodez** [comment]
Pastebin what you have.

**Comment by TheAdorkable1** [comment]
<script src="https://pastebin.com/embed_js/WMQiMeLx"></script>

**Comment by TheAdorkable1** [comment]
[votesites.txt](https://github.com/Ben12345rocks/VotingPlugin/files/4834015/votesites.txt)

**Comment by TheAdorkable1** [comment]
VoteSites:
  PlanetMinecraft:
    Enabled: true
    ServiceSite: PlanetMinecraft_com
    VoteURL: https://www.planetminecraft.com/server/candylandmc-4652405/vote/
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands: 
      - crates key @p Vote
      Messags:
        Player: '&aThanks for voting on %ServiceSite%!'

**Comment by TheAdorkable1** [comment]
I don't know how to add an actual pastebin 0.0

**Comment by BenCodez** [comment]
https://pastebin.com/

Copy and paste and send the link.
