### ISSUE TITLE
Errors & Disables on startup

### ISSUE THREAD

**Issue by Curtis73** [BenCodez/VotingPlugin#855]
**Versions**
Plugin version: 5.22
Spigot version: Paper-372 

**Describe the bug**
When the plugin is loaded at startup, it throws a bunch of errors before disabling.

**Screenshots/Configs**
Plugin's startup log is here: https://pastebin.com/ZQpAfnhK

**Comment by BenCodez** [comment]
Does it happen with a different version? Anything different with this? http://ben12345rocks.com/

**Comment by BenCodez** [comment]
Also check what java your running.

**Comment by Curtis73** [comment]
I'm running on Java 8, and I get the same issue with the dev build you linked, though I have noticed that the issue is only present when MySQL is enabled in the config.

**Comment by BenCodez** [comment]
What happens if you downgrade a build?

**Comment by Curtis73** [comment]
I tried running it on version 5.20.6 and the plugin appears to function correctly - I'll do some more testing and see if I can find the latest version that will run

**Comment by BenCodez** [comment]
[02:12:31] [Server thread/WARN]: [VotingPlugin] Loaded class me.Zrips.TryMe.DataBase.DataBaseDrivers from TryMe v6.0.4.4 which is not a depend, softdepend or loadbefore of this plugin.
    [02:12:31] [Server thread/WARN]: [VotingPlugin] Loaded class com.mysql.cj.jdbc.Driver from SkinsRestorer v13.7.9 which is not a depend, softdepend or loadbefore of this plugin.

Does it work if you disable those plugins? I think they might be interfering.

**Comment by BenCodez** [comment]
What happens now if you use this?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Curtis73** [comment]
Hey, I've tried disabling both of those plugins and running the dev build, but unfortunately the same error's showing

**Comment by BenCodez** [comment]
Well, there isn't really much I can do.

**Comment by Baterka** [comment]
I have same problem. 
Seems like problem occuring only on Java 8.
I tested with Java 11 and it is working.

**Comment by BenCodez** [comment]
@Baterka What java 8 were you using?

**Comment by Baterka** [comment]
@Ben12345rocks  AdoptOpenJDK

**Comment by BenCodez** [comment]
@Baterk Need the exact java version. But it doesn't matter if you fixed it I guess.

**Comment by Baterka** [comment]
I fixed it by installing Java 11 :D So more like workaround than fix.

It was latest Java 8 for Debian 10 from https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/

I am sorry, I already installed Java 11 on production. I will be able to install it back and check for version later this day when no players on server.

**Comment by BenCodez** [comment]
@Baterka No need. I had a feeling it was java version related though.

**Comment by Baterka** [comment]
I would rather use 8, tho... There was no problem with older pre 1.16 versions on same java

**Comment by BenCodez** [comment]
I got no idea. Not really much I can do.

**Comment by Curtis73** [comment]
That's a shame - thanks for your help, though!
