### ISSUE TITLE
Question about VoteParty and AllSites in the config

### ISSUE THREAD

**Issue by SaltedBiscuit** [BenCodez/VotingPlugin#857]
**Versions**
5.22

**Relevant information**
https://pastebin.com/yApatcyd

**Context**
Setting up my config file for players voting daily and a voteparty requirement of 50 (1 vote needed that day to receive reward) I just wanted to make sure I had both sets of lines in my config correct before the server goes live later this week.

Trying to make sure a command is run when they vote on all each day, and when the server hits 50 votes for the day.
do i need a set of apostrophes around the command line?

**Comment by BenCodez** [comment]
Best way to test would be a test server or something. I don't see any problems from doing a quick look.
