### ISSUE TITLE
Few bugs regarding the menus

### ISSUE THREAD

**Issue by ChrisTaylor201** [BenCodez/VotingPlugin#859]
### Versions
Server core – PaperMC 1.15.2 build 375
Plugin – 5.22

#### Description
If you click on the item representing `URL` in the main menu, it will close instead of opening the desired menu. However, it can be still accessed using `/vote url` command.

#### How to reproduce
1. Open the main menu using `/vote gui` command.
2. Click on the item representing the `URL` menu.
3. Check for the issue described above.

#### Expected behavior
The `URL` menu should open.

#### Video
https://streamable.com/7zkx9t

#### Description
There's a several seconds delay when opening the `Today` menu.

#### How to reproduce
1. Try opening the `Today` menu either using `/vote today` command or via the main menu.
2. Check for the issue described above.

#### Expected behavior
There should be no delay.

#### Video
https://streamable.com/czbz7b

**Comment by BenCodez** [comment]
1. The vote url gui was removed from that GUI just add a command for it
2. It has to load the skulls. Either enable preload skulls or change the item.

**Comment by ChrisTaylor201** [comment]
#### The 1st issue
Ah, it's not a bug, it's a feature! Sorry for the false positive. (I can see the change in [this commit](https://github.com/Ben12345rocks/VotingPlugin/commit/fc6f1052d664b17e9ff97cab59fe6e01552d42a6#diff-bcfff47522ac973b6b4bba644a2618c4).)

Would be possible then to add this feature back as an option, something like this?
```java
// …

if (slot.equalsIgnoreCase("url"))
{
    if (Config.getInstance().openVoteURLOnClick())
    {
        openVoteURL(player)
    }
    else
    {
        user.sendMessage(Commands.getInstance().voteURLs(user));
    }
}

// …
```
#### The 2nd issue
I tried setting `PreloadSkulls` to `true` but it has no effect, the delay is the same. I think the item representing a vote with timestamp can't be changed?

I'm 100% sure there wasn't such a delay. Could it have something to do with one of the PaperMC updates? I know there've been some changes regarding skulls which have broken other plugins using them.

**Comment by BenCodez** [comment]
1. You can set it to run commands in the config, just run the command to open the gui
2. Preloading skulls does take time. It's not instant Start the server and just let it sit for awhile. Then see if it works.

**Comment by ChrisTaylor201** [comment]
#### The 1st issue
I'm sorry but I don't understand exactly what you mean – could you please explain? I can't see any option to enable this feature.

#### The 2nd issue
I let it run for a while, of course, our server has a daily restart at 3:30 AM and I tried it at 9:00 AM.

**Comment by BenCodez** [comment]
1. There is an option for the vote gui to run commands on specific items
2. I'll do some testing

**Comment by ChrisTaylor201** [comment]
Ah, thank you very much, now I can see [the option](https://github.com/Ben12345rocks/VotingPlugin/blob/85a8a29e6951026da173fbf973e5f26f6f61ad74/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/Config/Config.java#L1202-L1212)! I apologize for being confused, I was looking for the option in the config but it wasn't there, I had to add it manually.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

If you have debuglevel to EXTRA, you should some info of preloading skulls (might be a few minutes after starting)

**Comment by ChrisTaylor201** [comment]
Although I let the server run for 20 minutes, there was no debug message about preloading skulls (see [the server log](https://gist.github.com/christaylor201/4beb8b4d33466ed22b03d0cbc11ff30c)).

**Comment by BenCodez** [comment]
Is LoadSkulls and PreloadSkulls enabled?
Do you have enough free ram? I designed it to not preload if there isn't alot of spare ram.

http://ben12345rocks.com/job/VotingPlugin/

Will add a little more debug.

**Comment by ChrisTaylor201** [comment]
Yes, `LoadSkulls` and `PreloadSkulls` are enabled.

I think we have more than enough RAM – the maximum memory is 6 GB, at idle 1.2 GB are allocated and 450 to 650 MB are free with 20 player slots.

Adding a little more debugging info to the newest builds helped, as soon as I turned on the server, this message started spamming:
```log
[06:45:07] [Craft Scheduler Thread - 16/INFO]: [VotingPlugin] ExtraDebug: Not loading skull
```
(Because of that I had to turn off the server, you can see the full log [here](https://gist.github.com/christaylor201/b3ae83cec0933c39a084ccd41f6a1c47).)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I had the requirement at 2 GB for it to load, changed it to .8 GB, see how that works.

**Comment by ChrisTaylor201** [comment]
I let the server run for ~25 minutes, unfortunately there was no debug message about loading skulls like in the previous build.

**Comment by BenCodez** [comment]
Send your config?

**Comment by ChrisTaylor201** [comment]
[Here](https://gist.github.com/christaylor201/c01812f8c40ad80e5a0b1d3297ac38c3) you go.

**Comment by BenCodez** [comment]
Anything about not loading? Skulls take a long time to load, once you open the GUI it should open quickly.

http://ben12345rocks.com/job/VotingPlugin/

Any different?

**Comment by ChrisTaylor201** [comment]
Unfortunately, there was neither debug message about loading skulls nor a difference in the delay.

**Comment by BenCodez** [comment]
Can you send the log?

**Comment by ChrisTaylor201** [comment]
Of course, [here](https://gist.github.com/christaylor201/9c6d5bffb19cf3b943de2449694b5dab) you are.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I think that should fix it.

**Comment by ChrisTaylor201** [comment]
Yes, it fixed the issue, skulls will start loading ~10 minutes after server startup. Thank you for your effort!
