### ISSUE TITLE
Players not being rewarded for voting

### ISSUE THREAD

**Issue by antiGriefer** [BenCodez/VotingPlugin#861]
**Versions**
Voting Plugin: 5.21.3, Spigot: 1.15.2

**Relevant information**
Config: https://pastebin.com/ij5C483s
Vote Sites: https://pastebin.com/wZYMv7Qa
Example Basics: https://pastebin.com/9L0P1hHy

**Context**
When I vote I get standard message: ''[Broadcast] Thanks antiGriefer for voting on minecraftservers.org | You voted on all sites in 1 day!''
But I don't get rewards. Its really likely that I messed something up in one of the files, it would really help me out if you took a quik look into it, im not an expert at this.

**Comment by BenCodez** [comment]
1. Don't use the example reward as a reward
2. It should be something like this:


       Commands:
       - command here

**Comment by antiGriefer** [comment]
@Ben12345rocks Thank You for your respond, did I write the message's the right way?

**Comment by BenCodez** [comment]
Messages:
      Player: 'Line 1%NewLine%Line 2'

Something like that.

**Comment by antiGriefer** [comment]
@Ben12345rocks Thank You for your help, my rewards are working now!
