### ISSUE TITLE
Lores on items in GUI's will move to next line

### ISSUE THREAD

**Issue by flemflem90** [BenCodez/VotingPlugin#862]
Plugin version 5.22 

"Lores on items in GUI's will move to next line above a certain length (Will look nicer in GUI's)" feature was added in 5.22
this "broke" our 50+ lore items that we use to buy stuff using gui's. (these lore items are recieved after voting)

when a player votes, they get a reward item that they then use to buy a perk using a gui.
since the lore is shortened by this new plugin version, the lore item is no longer the same as the one that is configured in the shop.
we would have to reconfig our lore items to make our gui shop function as before. 
together with my friend ive seached for a way to disable this new feature but i am unable to find one.
can we not turn this feature off? or did i miss it in the config? 
it would save us about 3 hours of work if this can be disabled.

thanks in advance <3

p.s.
I am awfully sorry at the terrible state of my english abilities, as for english if not my mother tongue. I hope you forgive me for every foolish mistake I make.

**Comment by BenCodez** [comment]
NewLoreLength: 30 (Config.yml) 

That's the default value, change it as you need.

**Comment by flemflem90** [comment]
i might just be messing up somewhere  but i do not have a "NewLoreLength: 30" in my config.yml file. not even when looking it up with ctrl + f
do i add this entry myself or is something else wrong?
(screenshot of plugin version as verification)

![image](https://user-images.githubusercontent.com/67835651/86517203-7722e900-be27-11ea-959e-174b267730b7.png)

**Comment by BenCodez** [comment]
Just add it.
