### ISSUE TITLE
Placeholder not displaying in chat

### ISSUE THREAD

**Issue by antiGriefer** [BenCodez/VotingPlugin#865]
**Versions**
MC: 1.15.2
VotingPlugin: 5.21.3
**Relevant information**
Printscreen of the problem: https://imgur.com/a/B9SLGQN

**Context**
How do I use placeholders in text?

**Comment by BenCodez** [comment]
Are you trying to use placeholderapi?

**Comment by antiGriefer** [comment]
Yes

**Comment by BenCodez** [comment]
Did you install the expansion? Does /papi parse work?

**Comment by antiGriefer** [comment]
Thanks Ben, I didn't know you had to download the expension I thought it was included in the plugin, I just had to do /papi ecloud download votingplugin -> /papi reload , Is creating a discord for simple stupid problems like this a good idea?

**Comment by BenCodez** [comment]
I don't like discord that much, don't want to be pestered with notifications.
