### ISSUE TITLE
Voting not working after a day

### ISSUE THREAD

**Issue by NotEvenAUnicorn** [BenCodez/VotingPlugin#866]
Hello, I've had to completely redo the code and stuff in the plugin to get it to work about 3 times now. It was working just fine two days ago. It seems to work for a day after I fix it, then the next day it won't even register that someone is voting. If I could get some help to resolve this issue, that'd be great. I do really like it, it's just getting frustrating. Forcing votes works, but actually voting doesn't and this has been a constant issue we struggle with.

**Comment by BenCodez** [comment]
Is the server getting the vote?

**Comment by NotEvenAUnicorn** [comment]
It is. The plugin itself recognizes the vote as well and will show that in the GUI, but it won't read the rewards file again now with legit votes.

**Comment by BenCodez** [comment]
Send what you have?

**Comment by NotEvenAUnicorn** [comment]
The rewards file? or what?

**Comment by BenCodez** [comment]
All of it.

**Comment by NotEvenAUnicorn** [comment]
[server43927 - 7 Jul 2020 18_27_46.zip](https://github.com/Ben12345rocks/VotingPlugin/files/4887432/server43927.-.7.Jul.2020.18_27_46.zip)

**Comment by BenCodez** [comment]
1. Don't think your service sites are correct (vote on site and check console), or /av servicesites
2. It's Material, and use these materials https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by NotEvenAUnicorn** [comment]
It still isn't giving rewards, but is now broadcasting when a player votes.

**Comment by BenCodez** [comment]
Did you do everything I said?

**Comment by NotEvenAUnicorn** [comment]
Yes.

**Comment by BenCodez** [comment]
Send what you have?

**Comment by NotEvenAUnicorn** [comment]
[server43927 - 7 Jul 2020 19_4_15.zip](https://github.com/Ben12345rocks/VotingPlugin/files/4887554/server43927.-.7.Jul.2020.19_4_15.zip)

I can't get the service sites to work. I don't understand what I'm doing wrong, I'm sorry.

**Comment by BenCodez** [comment]
You didn't fix anything I said.

1. Service sites are wrong, vote on the site and look in console, it will say the service site, then change accordingly
2. https://pastebin.com/LJ6pXD4Z

**Comment by NotEvenAUnicorn** [comment]
It doesn't show in the console.

**Comment by BenCodez** [comment]
Then the server isn't getting the vote, check votifier.
