### ISSUE TITLE
VoteParty not triggering

### ISSUE THREAD

**Issue by wm-b** [BenCodez/VotingPlugin#870]
**Versions**
VotingPlugin 5.22, PaperSpigot 1.16.1 build 86

**Describe the bug**
When the daily amount required to trigger voteparty is reached, the specified commands don't run.

**To Reproduce**
Attempt to use the voteparty feature on Spigot 1.16.1.

**Expected behaviour**
The commands listed in the voteparty config should trigger when the specified amount of votes are reached.

**Screenshots/Configs**
https://pastebin.com/hzVpvEgR
No entries to show from console log, as nothing happens at the time the commands should be executed.

**Comment by BenCodez** [comment]
# Increase the amount of votes required on each vote party reached
    IncreaseVotesRquired: 1000

Don't think you can reach the amount within a day. The count resets each day and every vote party will increase the amount required.

**Comment by wm-b** [comment]
I didn't realise that it didn't also reset the increase required each day.

Closing as it was just a configuration issue.
