### ISSUE TITLE
Turning off the offline vote party reward

### ISSUE THREAD

**Issue by Gregdoesgithub** [BenCodez/VotingPlugin#871]
Hello, I've looked pretty much everywhere and I just can't seem to find how to turn off the offline vote party reward. What I mean by that is that I don't want the players that are offline to log in and take lots of voteparty rewards. I would also like to ask if there's a possibility for me to put a timer on it. F.e. A player can get the the offline voteparty reward only if max 1 day have passed. So a person that logs in after 3 days in the server wont get the rewards of those 3 days, but the latest day's one. I hope I make sense. 
P.s. The plugin is awesome.

**Comment by BenCodez** [comment]
Add RewardType: ONLINE in the reward.

**Comment by Gregdoesgithub** [comment]
Can it have a timer? Like the one I mentioned above? or its impossible

**Comment by BenCodez** [comment]
Use RewardExpiration

https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleAdvanced.yml#L64

**Comment by Gregdoesgithub** [comment]
Commands:
- eco give %player% 7500
Items:
  DIAMOND:
    Material: DIAMOND
    Amount: 1
DirectlyDefinedReward: true
RewardExpiration: 1440


So something like this should be okay? (I just added the rewardexpiration thing in the voteparty_rewards.yml file)

**Comment by BenCodez** [comment]
Yes, can't really tell without code tags or pastebin though
