### ISSUE TITLE
Config Math

### ISSUE THREAD

**Issue by antiGriefer** [BenCodez/VotingPlugin#872]
I have a small question and idk where to ask this but how do I make calculations in the config? For example: I have a vote ranking system on my server and I want my gui to display the number of votes the player has to get until he gets to the next rank, so the formula will be really easy its just:''100-%VotingPlugin_Total_AllTime%''(every rank step is 100 votes apart) any ideas on how this would be possible?

**Comment by BenCodez** [comment]
Could use javascript

https://github.com/Ben12345rocks/AdvancedCore/wiki/Javascript-API

**Comment by antiGriefer** [comment]
Thanks I will try
