### ISSUE TITLE
MySQL doesn't seems to work

### ISSUE THREAD

**Issue by Rouxshi** [BenCodez/VotingPlugin#874]
**Versions**
Plugin: 5.22
Spigot: git-Spigot-05da6fa-b0c6dfe (MC: 1.16.1)

**Relevant information**
https://pastebin.com/5AEMvF2k

**Context**
I'm actually trying to use VotingPlugin with MySQL, it works with SQLITE, but when I restart the server with the config for MySQL it throw the error in the pastebin.
I'm completly new with MySQLL databases so, surely I'm doing something wrong, could you help me or push me in the right direction?

**Comment by BenCodez** [comment]
Is it possible to change java version?

This do anything different?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by JimmySuckOn9** [comment]
> **Versions**
> Plugin: 5.22
> Spigot: git-Spigot-05da6fa-b0c6dfe (MC: 1.16.1)
> 
> **Relevant information**
> https://pastebin.com/5AEMvF2k
> 
> **Context**
> I'm actually trying to use VotingPlugin with MySQL, it works with SQLITE, but when I restart the server with the config for MySQL it throw the error in the pastebin.
> I'm completly new with MySQLL databases so, surely I'm doing something wrong, could you help me or push me in the right direction?

I got the same problem with you too!

**Comment by BenCodez** [comment]
@JimmySuckOn9 Try changing java version.

**Comment by Rouxshi** [comment]
Sorry for the delay response, looks like the version that you send in the first comment fix the issue, I'm using it since yesterday and is working absolutly perfect.

**Comment by JimmySuckOn9** [comment]
> @JimmySuckOn9 Try changing java version.

any recommended version?

**Comment by BenCodez** [comment]
Java 11, but try that build above and see if it that works for you
