### ISSUE TITLE
VotingPlugin Issue

### ISSUE THREAD

**Issue by Gavviinnn** [BenCodez/VotingPlugin#876]
**Versions**
1.16.1 | 5.22
**Describe the bug**
Problems with "Detected YML error"

**To Reproduce**
1. Go on server
2. See error

**Expected behavior**
I have recently tried to change voting links through votesites.yml. The first link worked, ingame as well. However, adding more than one link causes an error. The following links are all enabled.

**Screenshots/Configs**
`# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  Voting Site:
    Enabled: true
    Name: Minecraft Servers
    Priority: 5
    ServiceSite: minecraftservers.org
    VoteURL: https://minecraftservers.org/server/MyCodeisHere
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: DIAMOND 
      Amount: 1
    Rewards:
      Commands:
      - say &4%player% voted!
      - crates givekey %player% voting 1
      Messages:
        Player: You voted
  Site2:
    Enabled: true
    Name: Minecraft-MP
    ServiceSite: minecraft-mp.com
    VoteURL: https://minecraft-mp.com/server/MyCodeisHere/vote/
    VoteDelay: 24
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - say &4%player% voted!
      - crates givekey %player% voting 1
      Messages:
       Player: You voted
      
  TopG:
    Enabled: true
    ServiceSite: topg.org
    VoteURL: https://topg.org/Minecraft/in-MyCodeisHere
    VoteDelay: 24
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Commands:
      -say &4%player% voted!
      -crates givekey %player% voting 1
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
EverySiteReward: []
`

**Additional context**
Thank you for any solution.

**Comment by BenCodez** [comment]
Pastebin your file

**Comment by Gavviinnn** [comment]
https://pastebin.com/eBQCdsy6

**Comment by BenCodez** [comment]
https://pastebin.com/B2iyXEZW

**Comment by Gavviinnn** [comment]
Thanks fixed.
