### ISSUE TITLE
VotingPlugin fails to connect to website through database

### ISSUE THREAD

**Issue by ZNChano** [BenCodez/VotingPlugin#877]
**Versions**
5.22 and 1.15.2

**Describe the bug**
Me and My Website Developer have been trying for days to attach VotingPlugin to our NamelessMC site through the integration but nothing is working. I created a brand new database, hooked LiteBans and VotingPlugin to it. Then he hooked the integration to the same exact database, yet nothing appears and it says it failed to retrieve data. I have VotingPlugin on my Hub and Skyblock server and am Hooking the SkyBlock server to it, not the hub for now. 

**To Reproduce**
Due to it involving a database, Im not sure you would be able to reproduce it. But if you wish to:
1. Make a NamelessMC site.
2. Create a database
3. Hook VotingPlugin to the Database
4. Select VotingPlugin integration on namlessmc
5. Hook the integration to the same database
6. check the page.

**Expected behavior**
The integrated page to show the top voters like it is supposed to do.

**Screenshots/Configs**

![image](https://user-images.githubusercontent.com/67173433/87636911-720b4700-c70f-11ea-84f1-f42b8dc7e020.png)

**Additional context**
None.

**Comment by BenCodez** [comment]
I never use namelessmc or made the integeration for it, not much I could
really do
