### ISSUE TITLE
Question on how to create milestone rewards

### ISSUE THREAD

**Issue by DrSipp** [BenCodez/VotingPlugin#878]
**Versions**
Plugin version and spigot version
Plugin version 5.22 Spigot Version 1.16.1

**Context**
I'm not reporting an issue with the plugin, I was just hoping to get a little help. I'm not good with plugins and I'm not familiar with configuring them. I just need help setting up milestone rewards. I want to create rewards that run a command after X votes, but I don't know how to set that up. I don't even know where to start. Any help would be greatly appreciated.

**Comment by BenCodez** [comment]
MileStones:
      # Number of votes required
      # Allows multiple milestones
      # Number be around ' (E.g. '1')
      # Can have multiple listed here
      '20':
        Enabled: false
        Rewards: 
          Messages:
            Player: '&aYou got %milestone% milestone votes!'
          Commands:
          - command here

**Comment by DrSipp** [comment]
The issue I'm having is that whenever I edit that config, it disappears after reloading.

Milestones:
'5':
    Enabled: true
    Rewards: 
      Messages:
        Player: '&aThank you for voting'
      Commands:
      - 'eco give 5000'
      - 'say hello"

**Comment by BenCodez** [comment]
What do you mean? Then your doing something wrong.

**Comment by DrSipp** [comment]
Whenever I edit this part of the config, the entire segment disappears when I update the changes. It looks exactly like this. https://pastebin.com/6mZLpqiu
I apologize for my lack of knowledge on the subject, I'm still learning how to edit these plugins

**Comment by BenCodez** [comment]
Then whatever your using to edit sucks.

**Comment by DrSipp** [comment]
I don't even know what to say to that. Thanks? I guess.

**Comment by BenCodez** [comment]
What are you using to edit? Are you doing /av reload after? Is the file actually saving?

**Comment by DrSipp** [comment]
I'm using the FTP file manager offered by my service provider, Shockbyte. The file is saving, any other changes work just fine. I thought I was writing something wrong, but I'm writing exactly what I showed you there.

**Comment by BenCodez** [comment]
Would recommend FileZila. There isn't anything I can do to help you with file saving.

**Comment by DrSipp** [comment]
Yeah, I guess I can try using FileZilla. Thank you
