### ISSUE TITLE
Placeholder api bug

### ISSUE THREAD

**Issue by florensm** [BenCodez/VotingPlugin#879]
**Versions**
Version: 5.1.3.1
Server version: FoxSpigot 0.5.7

**Describe the bug**
It doesnt return what it should return

**To Reproduce**
1. Do: /papi parse me %VotingPlugin_VotePartyVotesCurrent%
2. It gives the error which i pasted below

**Expected behavior**
It should return how much votes i currently have and how much more i need.

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/52450422/87859831-7b2b2c80-c938-11ea-9ad0-f216ae09d3b7.png)

**Additional context**
https://paste.helpch.at/vojovitate

I know It's an outdated version for 1.8, but I think it would be awesome if you could fix this for the 1.8 users because it's still a version that gets used much.

And it used to work before, but i think PlaceholderAPI updated which broke it somehow.

**Comment by BenCodez** [comment]
Isn't much I can do. I think you might need an older version for that.
