### ISSUE TITLE
Plugin is being disabled on startup.

### ISSUE THREAD

**Issue by ItWasEnder** [BenCodez/VotingPlugin#880]
**Versions**
5.22
1.15.2
Waterfall (proxy)

**Describe the bug**
I am trying to setup this plugin with nuvotifier and bungeecord but I can't get the plugin working on my spigot server. I don't understand what is causing this error to begin with, I have been following the guide step by step but the plugin doesn't want to stay enabled.

https://pastebin.com/9pDFrpL2

**Comment by BenCodez** [comment]
Mysql isn't able to connect

**Comment by ItWasEnder** [comment]
The bungeecord is connecting just fine though...

Bungeeconfig: https://paste.helpch.at/sahojodeza.makefile

Main Server Config: https://paste.helpch.at/equdenemuh.makefile

**Comment by BenCodez** [comment]
Host: 'db.solarismc.com '

You have a space at the end there.

**Comment by ItWasEnder** [comment]
That did get rid of the mysql error but my problem still stands.

New Console Error: https://pastebin.com/HbhRButj

**Comment by BenCodez** [comment]
Try this build? http://ben12345rocks.com/job/VotingPlugin/
If no try changing java version?

**Comment by ItWasEnder** [comment]
Still have the error. Also how would I change the java version on a hosted server.

https://pastebin.com/CLE2VUWe

**Comment by BenCodez** [comment]
Any different?
http://ben12345rocks.com/job/VotingPlugin/

I was told by a few others updating to java 11 fixed it, not sure how to on a host (or using a JDK java version should work too)

Still trying to figure out why it's a problem now after 1.16 came out.

Edit: wait for it to build, build 271

**Comment by ItWasEnder** [comment]
Most if not all servers & companies use java 8, also technically I could change the java version since I have a dedicated server through my host, but this is still an underlying issue and I would rather find a different plugin than change the java version.

Longer stacktrace (same but new): https://pastebin.com/p6XpLfPa

This does seem like an issue inside of java and not really the fault of your plugin though.

**Comment by BenCodez** [comment]
@EnderGamingFilms Yeah it is, been trying to found a workaround, after all the googling and not much I can find on a proper solution.

This do anything? I tried something a little different, if not I got another idea
http://ben12345rocks.com/job/VotingPlugin/

**Comment by ItWasEnder** [comment]
Same error, shorter stacktrace
https://pastebin.com/M8Lp6GXW

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Either there will be different errors or it will work, no idea.

**Comment by ItWasEnder** [comment]
Now I'm getting a mysql error: https://pastebin.com/xpAQ1qMG

**Comment by BenCodez** [comment]
Yeah, I think I'll have to undo my changes, guess it won't work.

**Comment by ItWasEnder** [comment]
yeah, rip ig

**Comment by BenCodez** [comment]
Unless you got another solution, or some way to fix that missing resource error, or try another java version

**Comment by ItWasEnder** [comment]
After looking into it, I don't think its an issue with VotingPlugin i think its an issue with AdvancedCore. Somewhere, there is a path to a "resource" that doesn't exist or the path is just incorrect and I don't think you are passing anything to the AdvancedCore, only calling its functions for MYSQL and such.

**Comment by BenCodez** [comment]
AdvancedCore is compiled into VotingPlugin (every change I was doing is to that), but there really is nothing I can do, all google searches point to some java problem, unless you find something else.

**Comment by ItWasEnder** [comment]
Yeah, idk any fixes for it. Guess I'm going on the search for another plugin with extensive placeholders lol.

**Comment by BenCodez** [comment]
Just wondering, does this do anything different?

http://ben12345rocks.com/job/VotingPlugin/

Edit: Note build 283 and 284 have different changes (try both if you could) I have no way to recreate the issue, so I'm trying whatever I can right now.

**Comment by ItWasEnder** [comment]
Nope, still broken. https://pastebin.com/iftLsgyD

**Comment by EnderGamingFilms** [comment]
Nope, still broken. https://pastebin.com/iftLsgyD

**Comment by BenCodez** [comment]
You try both builds I sent? I'm trying to see if I can force the locale its
trying to use to another one. What Java version are you using?

**Comment by ItWasEnder** [comment]
I've tried every build you sent. I'm on have 1.18 aka Java 8

**Comment by BenCodez** [comment]
Yeah, I think the only current solution is updating java
