### ISSUE TITLE
Request: in /vote GUI clicking the vote site opens the link directly, not sending it in chat. 1 less click.

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#884]
When /vote opens the GUI, when clicking the single site, instead of sending the link in chat, just open that link on click. 1 extra click for no reason! X12 vote sites, means an extra 12 clicks, so 24 clicks instead of 12.

**Comment by BenCodez** [comment]
There isn't a way to do that. It's would be a bad security problem if you force people to open links without their knowledge, if it was even possible.

**Comment by TomLewis** [comment]
There is because I can do it with deluxe menus, it dousnt auto open it, it promps them if they want to open the link. So don't send it in chat send the API request to open a URL.
100% exists, I've used it many times in my chat plugin in books and in guis.

**Comment by BenCodez** [comment]
Got some api for it? I haven't looked at it in awhile on doing this.

**Comment by BenCodez** [comment]
Yeah, there is no way that I know of that can do this. Nor can I find anything. There isn't a way without making a player click a link in chat or a book. So, unless you got some code or something you can show me I can't add this.
