### ISSUE TITLE
How do I add more than 1 Vote Site?

### ISSUE THREAD

**Issue by Koo0311** [BenCodez/VotingPlugin#887]
**Versions**
Plugin version and spigot version

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Context about the question/concern

**Comment by BenCodez** [comment]
Just add another?

**Comment by Koo0311** [comment]
https://cdn.discordapp.com/attachments/557913753874857985/737416311142875136/unknown.png I copied and pasted the template and just changed the vote list and it doesnt work

**Comment by BenCodez** [comment]
It needs to be under the other votesite.

**Comment by Koo0311** [comment]
Can you give example?

**Comment by BenCodez** [comment]
VoteSites:
      Site1:
        # site 1
      Site2:
        #site 2

**Comment by Koo0311** [comment]
Like this?
![image](https://user-images.githubusercontent.com/68876202/88594931-be1b8d00-d027-11ea-8c30-00cfcec3793c.png)

**Comment by BenCodez** [comment]
Kinda your missing the first site though

**Comment by Koo0311** [comment]
![image](https://user-images.githubusercontent.com/68876202/88595302-531e8600-d028-11ea-9100-2ed873b637aa.png)
Those are the 2 vote sites?

**Comment by BenCodez** [comment]
There is nothing under the first site.

**Comment by Koo0311** [comment]
What has to be under it?

**Comment by BenCodez** [comment]
Same as the other site.

**Comment by Koo0311** [comment]
![image](https://user-images.githubusercontent.com/68876202/88595659-0b4c2e80-d029-11ea-8fe5-3c05b64a30a2.png)
Ok so this is my first site. Where do I start the next site at what line?

**Comment by BenCodez** [comment]
Somewhere past the screenshot or after VoteSites:
 Use pastebin as well, make it easier to send it back corrected.

**Comment by Koo0311** [comment]
![image](https://user-images.githubusercontent.com/68876202/88595846-6aaa3e80-d029-11ea-9e11-6b58b784ae12.png)
This is the bottom of the top image

**Comment by BenCodez** [comment]
Use pastebin, screenshots are pointless, anyway under line 47, also no commands with /

**Comment by Koo0311** [comment]
ok

**Comment by Koo0311** [comment]
I figured it out thank you
