### ISSUE TITLE
Rewarding users randomly

### ISSUE THREAD

**Issue by Timmy109** [BenCodez/VotingPlugin#889]
**Versions**
VotingPlugin version 5.22
git-Paper-384 (MC: 1.15.2)

**Describe the bug**
When a player logs on, sometimes they will get rewarded with voting rewards and multiple vote parties for no apparent reason. Usually voting on all 5 sites gives the player $5000 and 2 vote crate keys.

When the player logged on today, they were given 16 vote crate keys and multiple vote party (common) keys and rewarded with loads of cash even though they had not voted since the day before.
The log is here: https://paste.hypera.dev/ajigequyen.bash (No errors, just the player log in and the rewards given.

**To Reproduce**
To reproduce, I don't really know. This has happened a few times and I'm really not too sure why. A player just logs on and is greeted with loads of rewards (that they didn't deserve ;) )

**Expected behavior**
With this plugin, I expect the rewards to be only given to the player once, as I'm sure most other people would expect!
9 times out of 10 this plugin works flawlessly, not sure what happened the other 1/10 times.

**Screenshots/Configs**
Here is the config: https://paste.hypera.dev/iquqivodif.coffeescript

**Additional context**
No additional context.

**Comment by BenCodez** [comment]
VoteSites.yml?

Are you using a bungee setup? If so what are you doing?

**Comment by Timmy109** [comment]
hey mate,

I'm on my phone right now and can't provide the votesites.yml

However I dont think that would help anyway because I dont have rewards set up there. Only a message telling the player that they voted on the service site.

To answer your question no im not using bungeecord, although I used to. It happened when I was using bungee and now its happening when the server is running outside of the network.

Thanks

**Comment by BenCodez** [comment]
Well, only idea I have right now is that maybe some offline votes got stored up and was finally given on login?

You can set debuglevel to EXTRA and it will provide a lot more details on where the rewards are coming from.

**Comment by Timmy109** [comment]
I'll do that. This player is online most days of the week from what I can see. This is the second time it has happened to them this week. It happened to a few others too. They always vote when they are online, not sure what couldve happened here
