### ISSUE TITLE
Weekly Rewards that doesn't reset

### ISSUE THREAD

**Issue by eliyash31** [BenCodez/VotingPlugin#890]
Plugin version 5.22 and spigot version 1.16.1

Hello where could I find the config for Weekly Rewards? I can only see cumulative rewards, vote streak, and top weekly rewards.

What I want is that in every week that the player votes, they will receive a reward. 
With this it's okay that players cannot vote everyday especially when they are busy. 
I can't use vote streak because the streak will go back to 0 once a player forget to vote.
I can't also use top weekly rewards because I want all the players to receive the reward after they voted a week.
Cumulative rewards will also reset or back to zero after a day or a week depends on the option I enabled.

so where could I find the config for weekly rewards that doesn't reset? that just counts the total votes of the player.

Example: 
     every 7 votes = 7 days = 1 week.
so every 7 votes the player should receive a weekly reward
and after 7 votes in which the player gets 14 votes in total, they can again receive a reward
and another 7 votes again which the player gets 21 votes in total another reward just like that.

please help thank you!

**Comment by BenCodez** [comment]
Use cumulative with a total of 7. Either weekly or not?

**Comment by eliyash31** [comment]
I don't understand? I can use cumulative of 7 but how can I do it with the settings being forever? I mean sure I can use cumulative every 7 votes but the settings there is within a day and within a week. Does that mean if I choose to enable within a week, it will reset the cumulative again after a week? lets say

First Day
Player voted : 1 vote

2nd Day
Player voted : total of 2 votes

and then until the 7th day 
he only got 6 votes because he forgot to vote the other day.

on the 8th day he will be back to 0 right? or it will just continue? if on the 8th day he will vote again he will have a total of 7 cumulative votes, then can he still receive the reward?

**Comment by BenCodez** [comment]
Could set it to 6 then? Or you just do every 7 votes from his all time total. So it doesn't go by the exact week

**Comment by BenCodez** [comment]
Guess I should mention you can also do this:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L741

Require a percentage for vote streak, if that is useful in anyway.

**Comment by eliyash31** [comment]
That's what I meant every after 7 votes of his total he will get a reward how could I do that? or where could I find that option?

like 7 votes he will get a reward and another 7 votes again he will get another reward just like that, does that exist in the config?

**Comment by BenCodez** [comment]
Just use cumulative of 7, every 7 votes that reward will execute.

**Comment by eliyash31** [comment]
So if the player cannot vote for atleast 2 days, it won't reset their cumulative votes right? when I enable the within a week option?

**Comment by BenCodez** [comment]
Why bother with the week option, just every 7 votes get a reward?

**Comment by eliyash31** [comment]
Oh I didn't know that you can just disable the weekly and daily cumulative and it will still work okay I will try it out thanks!
