### ISSUE TITLE
Bungeecord setup - Some questions

### ISSUE THREAD

**Issue by SupaYoshi** [BenCodez/VotingPlugin#891]
Hi, We have been trying to setup the VotingPlugin for a while now. But we are unsure on the documentation.
It's not very clear to us, what to do with the config.

**What we want:**
- We want people to vote for our server, and receive the reward on the server the player is currently connected on within the Bungeecord network in their inventory. Our inventories sync over different servers... so we don't want the reward to be given on each server, just on the server they are currently in. All servers are connected to the same bungeecord network.

When I read the documentation, from here,
https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

I feel like I am reading contradictory information and am unsure what to do in my instance.
I think I should be using the first heading, : _VotingPlugin on each spigot server + Bungee (No votifier forwarding, most complicated, but most advanced_

When I configure it like that, I should have NuVotifier on the bungeecord hub server, but not on the individual servers. ( so far so good)

However when doing the configuration for the VotingPlugin on bungee I get no help.
Should SendVotestoAllServers be false or true?
Should SendToOnlineServer be false or true?
Should FailBackServer be anything?

the Bungeecommunication, should this be set to the Bungeecord Minecraft Protocol Port? Or the Votingplugin Port?

The MYSQL config is clear, we have no issue setting that up correctly.

**Comment by BenCodez** [comment]
SendVotesToAllServers false.
SendToOnlineServer true
Fallbackserver, pick a server to handle the reward if player isn't online

Host/port works the same as votifier in a sense. Needs it's own port.

You can also do a different method with just mysql for cross server handling.

**Comment by SupaYoshi** [comment]
Can you please explain what you mean with other methods using just MySQL ? I was under the believe you had to use both in combination?

**Comment by BenCodez** [comment]
VotingPlugin on each server with mysql, no vote forwarding, global reward (1 reward on neetwork, semi easy):

https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

Last one on that page.
