### ISSUE TITLE
some pages do not give votes to users and the keys are correct

### ISSUE THREAD

**Issue by ToxicPeople** [BenCodez/VotingPlugin#892]
**Versions**
Plugin version and spigot version
VotingPlugin 5.2.2 |  Paper version git-Paper-110 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
**Relevant information**
Configs that relate to the issue in a pastebin.
https://pastebin.com/n9iM96ZM
**Context**
Context about the question/concern
Users usually vote on 5 pages, of which only 2 are giving them rewards. Which even seems strange to me. This happens since I set up a firewall, I don't know if it will have to.

**Comment by BenCodez** [comment]
Does the server get the vote? Check console

**Comment by ToxicPeople** [comment]
No, the console does not receive any notification that they voted, only 2 pages only (as I mentioned earlier, all 5 pages worked so far, but now only 2).

**Comment by BenCodez** [comment]
Check the sites or votifier in that case.
