### ISSUE TITLE
Claim block reward? I need help on how to Put claim blocks as a reward. I use GriefProtection

### ISSUE THREAD

**Issue by Soggysap** [BenCodez/VotingPlugin#894]
**Versions**
Plugin version and spigot version

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Context about the question/concern

**Comment by BenCodez** [comment]
?

**Comment by Soggysap** [comment]
as a way to protect peoples homes from being destroyed, People are given a golden shovel with a certain ammout of claim blocks on it. I want to know if i could give people more claim space as a reward for voting, and how.

**Comment by BenCodez** [comment]
Use a command to give perms or something.
