### ISSUE TITLE
Bungeecord -> Spigot Errors

### ISSUE THREAD

**Issue by KyanG7** [BenCodez/VotingPlugin#897]
**Versions**
Latest, 1.16.1

**Relevant information**
https://hastebin.com/sadacojica.shell

**Context**
I am using a Bungee cord connection, the bungee cord is successfully redirecting but the VotingPlugin on the spigot server errors and I get nothing and I get the error listed in the haste bin.

**Comment by BenCodez** [comment]
Those errors are from Via version

**Comment by KyanG7** [comment]
Then why am I not receiving my items on the server when the bungeecord says its successful

**Comment by BenCodez** [comment]
Need to provide more info before I can say

**Comment by KyanG7** [comment]
What info do you need from me so I can get it?

**Comment by BenCodez** [comment]
Configs, reward setup, is the server receiving the vote (look in console)?

**Comment by KyanG7** [comment]
Here is the Bungeecord Config,  I see a message on the proxy that says the vote was received
https://hastebin.com/iwaquyimih.makefile

Spigot Server Config, I am not seeing any message on this server.
https://hastebin.com/dubazixupi.coffeescript

**Comment by BenCodez** [comment]
Your missing the bungee host/port on bungee and spigot host/port on spigot.

**Comment by KyanG7** [comment]
Oh I removed those because it said you only needed them on bungee host/port on spigot and other way around. Can you tell me what to put back there?

**Comment by BenCodez** [comment]
Look at the default configs, much easier.

**Comment by KyanG7** [comment]
Now I am erroring again.
The error:
https://hastebin.com/hubuzaxodu.css
Bungeecord Config
https://hastebin.com/omevuyufeq.makefile
Spigot Config
https://hastebin.com/miputimoce.coffeescript

**Comment by BenCodez** [comment]
Did you restart? Is there more errors?

**Comment by KyanG7** [comment]
Yes I restarted. That is the only error on the proxy.

**Comment by BenCodez** [comment]
Using the latest version? If so try this:
http://ben12345rocks.com/job/VotingPlugin/

Then send the full log of console.

**Comment by KyanG7** [comment]
Just downloaded the latest, bungee is no longer erroring
https://hastebin.com/kedafilika.shell
This is on the spigot server, you said this was ViaVersion but it only happens when a vote occurs.
Here is the FULL console log
https://hastebin.com/negebodive.shell

**Comment by BenCodez** [comment]
Cannot load plugins/VotingPlugin/VoteSites.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
in 'string', line 1, column 1:
VoteSites:
expected <block end>, but found '<block mapping start>'
in 'string', line 111, column 3:
Site2:

ailed to bind to 64.40.8.129:25568
> [15:54:38] [Server thread/WARN]: java.net.BindException: Cannot assign requested address (Bind failed)

Need to check that

**Comment by KyanG7** [comment]
Well its the server IP, I don't know what to tell you

**Comment by KyanG7** [comment]
We can connect to the server just fine, seeing thats it connected to the proxy

**Comment by BenCodez** [comment]
It needs its own port

**Comment by KyanG7** [comment]
Ohhh like another votifier port? I have 8192-8208 open.

**Comment by BenCodez** [comment]
Yeah.

**Comment by KyanG7** [comment]
Okay, thanks.

**Comment by KyanG7** [comment]
So the bungeecord transmitter should be new ports but the receiver should be 8192? (main votifier port) or should it be the server's IP. And the spigot transmitter should be a new port and the receiver should be 8193-8208

**Comment by BenCodez** [comment]
Each server needs a port. Then votifier needs one itself.

**Comment by KyanG7** [comment]
# Bungee communication, Add this to each spigot server
BungeeServer:
  Host: '64.40.8.129'
  Port: 8192
  
# Bungee communication, add each spigot server here
SpigotServers:
  lobby:
    Host: '64.40.8.129'
    Port: 8195

Like this? Or does Bungee need a third port.

**Comment by BenCodez** [comment]
Yeah, copy the info over to the spigot servers

**Comment by KyanG7** [comment]
Yeah thats correct or yeah it needs a third port?

**Comment by BenCodez** [comment]
Should match what you have on bungee (just swaped)

**Comment by KyanG7** [comment]
VoteSites is still erroring. :/

**Comment by BenCodez** [comment]
Because of a yml error...
