### ISSUE TITLE
Rewards Issue

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [BenCodez/VotingPlugin#898]
**Versions**
Plugin version and spigot version

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Context about the question/concern

Why can't rewards send to players when voting?
# Directly defined reward file. ANY EDITS HERE CAN GET OVERRIDDEN!
OnlyOneItemChance: false
Rewards:
Money:
  Min: 50
EXPLevels: 0
Commands:
  Console:
  - cc give physical Commoner 1 %player%
Messages:
  Player: '&aMessage on reward'
  Broadcast: '&aThis is a broadcast'
Command:
DirectlyDefinedReward: true

that is my rewards basic.yml file and idk why it wont send users rewards

**Comment by BenCodez** [comment]
Pastebin? Server get the vote?

**Comment by NXxEpicXCreeperxX** [comment]
Whats vote code? the broadcast comes in it just don't give the player a reward

**Comment by BenCodez** [comment]
Pastebin your configs/rewards

**Comment by NXxEpicXCreeperxX** [comment]
https://pastebin.com/gKum9Hbd

**Comment by NXxEpicXCreeperxX** [comment]
They are in seperate folders, i just combined them into 1 paste for you

**Comment by BenCodez** [comment]
Pastebin your votesites.yml

**Comment by NXxEpicXCreeperxX** [comment]
https://pastebin.com/j0Sp7gHa
/av rewards or /av givereward don't work anymore
it says adminvote help

**Comment by BenCodez** [comment]
You need to set the reward in the votesites.yml under Rewards.

**Comment by NXxEpicXCreeperxX** [comment]
How? also is there a way to give /av givereward?

**Comment by NXxEpicXCreeperxX** [comment]
Because av /giveonline don't work anymore

**Comment by BenCodez** [comment]
You need to add the reward name and player.

/av vote (player) (site) - add the rewards within the votesite.

**Comment by NXxEpicXCreeperxX** [comment]
Okay ill try to add one last time it reset my votessites

**Comment by NXxEpicXCreeperxX** [comment]
https://gyazo.com/ff2caa3c6b0de1048dcb9cfd3c3f7e56
Help??

**Comment by BenCodez** [comment]
Send what you have?

**Comment by NXxEpicXCreeperxX** [comment]
um my votesites folder reset and is empty?

**Comment by BenCodez** [comment]
There is no votesites folder?

**Comment by NXxEpicXCreeperxX** [comment]
the votessites file is empty

**Comment by BenCodez** [comment]
Then your doing something wrong.

**Comment by NXxEpicXCreeperxX** [comment]
well i put commands under rewards to do a command
and it didnt give me a key and reset my sites

**Comment by BenCodez** [comment]
Well, what are you using to edit? Notepad++? My guess it's failing to upload the file. Even if there is a yml error it won't just delete it. If not start from scratch. Vote on the site and let it auto generate votesites.

**Comment by NXxEpicXCreeperxX** [comment]
How do I add a reward vote key to a site then?
I use crazycrates

**Comment by BenCodez** [comment]
Rewards:
      Commands:
      - command here

With the proper spacing

**Comment by NXxEpicXCreeperxX** [comment]
is there an easy way to add back vote sites?
i voted before and it auto added it now i cant seem to vote till tomorrow

**Comment by BenCodez** [comment]
Get someone else to vote? Know the service sites just make it with /av vote?

**Comment by NXxEpicXCreeperxX** [comment]
Rewards:
    Commands:
    - cc give p Commoner 1 %player%
help?
it doesnt work

**Comment by NXxEpicXCreeperxX** [comment]
How do i make it so console gives the key?

**Comment by BenCodez** [comment]
Pastebin your Votesites.yml, you need the rewards in there, or specify the
reward file

**Comment by NXxEpicXCreeperxX** [comment]
https://pastebin.com/jVA5gvuG

**Comment by BenCodez** [comment]
https://pastebin.com/ZYumgpVb
