### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#899]
**Versions**
Paper 1.16.1
VotePlugin 5.21.3

**Describe the bug**
After someone voted, an almost endless error came along
It stopped after a while and a similar appeared after another vote.
Short error: https://pastebin.com/FgX7PzrA (I left the repeated lines away)
After about 2000 lines and 8 seconds, it stopped.
Then some votes came in fine.
Few minutes later it happened for the second time with another player.

**To Reproduce**
It just appeared out of nowhere. I didn't have this error before. Nothing has changed. Solved (for now) after a reboot. So not sure how to reproduce.

**Expected behavior**
No errors

**Screenshots/Configs**-

**Additional context**
Same error appeared when a player executed `/votepoints`

**Comment by BenCodez** [comment]
Need the full log of the error.

**Comment by x1p** [comment]
Hope this helps https://pastebin.com/eNQ0eUqA

**Comment by BenCodez** [comment]
Doesn't seem to say anything regarding votingplugin, so I got no idea right now
