### ISSUE TITLE
Improve PlayerCommandSendListener event performance

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#900]
**Versions**
Latest from Jenkins

**Describe the bug**
Higher values at timings? 

VotingPlugin::Event: c.B.V.L.PlayerCommandSendListener (PlayerCommandSendEvent)count(7)  total(0.41% 0.07s, 0.72% of tick)avg(10.01ms per - 0.36ms/0.04 per tick

https://timings.aikar.co/?id=d7837105e1c4497c9679a83da6e153b5

**Comment by BenCodez** [comment]
Disable AdvancedTab in the config

**Comment by bobhenl** [comment]
OK, but btw nice feature, couldn't it be improved to better perfomance somehow?

**Comment by BenCodez** [comment]
Yeah it can, just a matter of caching of some sort or something maybe

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should help with performance with advancedtab enabled.

**Comment by bobhenl** [comment]
OK, will try to enable again.

**Comment by bobhenl** [comment]
Hi, you probably did there some mistake? Now voting doesn't work and I'm getting this: https://pastebin.com/Xg1nAuCp @Ben12345rocks

**Comment by BenCodez** [comment]
Check what TimeFormat is in the config, I made no changes to cause that. Looks like it is set to 'v'

**Comment by bobhenl** [comment]
TimeFormat: '%amount% %TimeType%'
  TimeFormat: 'EEE, d. MMM yyyy v HH:mm'
  
  TimeFormats:
    Day: 'Den'
    Days: 'Dny'
    Hour: 'Hodina'
    Hours: 'Hodiny'
    Minute: 'Minuta'
    Minutes: 'Minuty'
    Second: 'Sekunda'
    Seconds: 'Sekundy'

Oh, I can't use there d**.** and "**v**" character?

**Comment by BenCodez** [comment]
I'm not sure what your saying. but I'm guessing that is the case.

**Comment by bobhenl** [comment]
TimeFormat: "EEE, d'.' MMM yyyy 'v' HH:mm"

And this is correct?  On https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html it's also used like this. "v" is "at" for our language

"yyyy.MM.dd G 'at' HH:mm:ss z" | 2001.07.04 AD at 12:08:56 PDT
-- | --

**Comment by BenCodez** [comment]
You didn't have ' ' around the v

TimeFormat: "EEE, d. MMM yyyy 'v' HH:mm"

try that.

**Comment by bobhenl** [comment]
and . hasn't to be in ''?

**Comment by BenCodez** [comment]
I mean just copy and paste
"yyyy.MM.dd G 'at' HH:mm:ss z"

then change the at to v

**Comment by bobhenl** [comment]
TimeFormat: "EEE, d. MMM yyyy 'v' HH:mm"¨
¨
But this format is also right? I wanted a little bit another one.

**Comment by BenCodez** [comment]
I got no idea, don't really use time format that often, just try and find out.
