### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by hammad-alhassan** [BenCodez/VotingPlugin#901]
10.08 19:21:11 [Server] INFO [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Starting...
10.08 19:21:11 [Server] INFO [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Start completed.
10.08 19:21:11 [Server] WARN java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale en_US
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
10.08 19:21:11 [Server] WARN at com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:354)
10.08 19:21:11 [Server] WARN java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale en_US
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
10.08 19:21:11 [Server] WARN at com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:354)
10.08 19:21:11 [Server] WARN java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale en_US
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
10.08 19:21:11 [Server] WARN at com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:354)
10.08 19:21:11 [Server] WARN java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale en_US
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
10.08 19:21:11 [Server] WARN at com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:354)
10.08 19:21:11 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'uuid'
10.08 19:21:11 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10.08 19:21:11 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10.08 19:21:11 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10.08 19:21:11 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:408)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175)
10.08 19:21:11 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052)
10.08 19:21:11 [Server] WARN java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale en_US
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
10.08 19:21:11 [Server] WARN at com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:354)
10.08 19:21:11 [Server] WARN java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale en_US
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
10.08 19:21:11 [Server] WARN at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.<init>(JdbcRowSetResourceBundle.java:105)
10.08 19:21:11 [Server] WARN at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(JdbcRowSetResourceBundle.java:124)
10.08 19:21:11 [Server] WARN at com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:354)
10.08 19:21:11 [Server] INFO [VotingPlugin] Shutting down mysql, query size: 1

**Comment by BenCodez** [comment]
Try with Java 11

**Comment by hammad-alhassan** [comment]
it worked but is there a way to let it work with java 8?

**Comment by hammad-alhassan** [comment]
my main plugins in my network dosen't support java 11

**Comment by hammad-alhassan** [comment]
version 5.20.7 works with no issues with MYSQL

**Comment by BenCodez** [comment]
This do anything different?
http://ben12345rocks.com/job/VotingPlugin/

Been trying to find the exact cause, but all point to some java issue.

Is that the oldest version that works? If not can you find exactly is the last version that works?

**Comment by hammad-alhassan** [comment]
yes this is the oldest working version for me ,i will try the one you sent and let you know

**Comment by hammad-alhassan** [comment]
its the same not working

**Comment by BenCodez** [comment]
Yeah I got no idea.

You can try this, see if it does anything different:
http://ben12345rocks.com/job/VotingPlugin/ (Compiled with java 9)

https://www.dropbox.com/s/rw15cb035zl8emv/VotingPlugin.jar?dl=0 (Compiled with java 11)

Try both, see what happens. Trying some random ideas I just had.

**Comment by hammad-alhassan** [comment]
still the same ,and dose version 5.20.7 support 1.16

**Comment by BenCodez** [comment]
No idea, should work. But I can't see any reason why 5.20.7 should work though.

**Comment by hammad-alhassan** [comment]
if you came up with something you can make me test it for you if you want.

**Comment by BenCodez** [comment]
New idea. Found one difference which I'm messing with.
http://ben12345rocks.com/job/VotingPlugin/

**Comment by hammad-alhassan** [comment]
still the same

**Comment by BenCodez** [comment]
https://www.dropbox.com/s/qa6n2tdefgqmhd1/VotingPlugin.jar?dl=0

That any different?

**Comment by hammad-alhassan** [comment]
still the same

**Comment by BenCodez** [comment]
Try using different Java 8 versions on the server?

**Comment by hammad-alhassan** [comment]
That wouldn't be possible unfortunately...what pebblehost said to me about changing the version

**Comment by hammad-alhassan** [comment]
is there another way to fix it?

**Comment by BenCodez** [comment]
Got one other idea, will let you know later.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

What happens with this?

**Comment by hammad-alhassan** [comment]
nice this is working perfectly

**Comment by BenCodez** [comment]
Nice, redid how mysql was handled, removed the whole problem altogether. 

Been trying to fix this for awhile, so glad it works :)
