### ISSUE TITLE
Reward the Top 5 Voters of the month

### ISSUE THREAD

**Issue by antiGriefer** [BenCodez/VotingPlugin#904]
Hello,

In the reward menu there are 2 reward files for the top 2 voters of the month. Can I just multiply them to get rewards for the top 5 or is there a other way to do it?

TY
-anti

**Comment by BenCodez** [comment]
Just set the rewards in the config?

**Comment by antiGriefer** [comment]
> Just set the rewards in the config?

How?

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L800
