### ISSUE TITLE
gui editor broke

### ISSUE THREAD

**Issue by Crazzyguyy** [BenCodez/VotingPlugin#905]
**Versions**
Plugin version and spigot version.
5.22
git-Paper-135 (1.16.1)

**Describe the bug**
after editing 7 players data, /av users <user> to edit data the gui for editing the data doesnt show up for anyone except those 7 players.

**To Reproduce**
1. Go to '/av users <user>'
2. Click on 'edit data'

**Expected behavior**
gui to edit the oplayers data, some do.

**Screenshots/Configs**
https://pastebin.com/QxvvNNHE

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Any better?

What data storage are you using?
