### ISSUE TITLE
Rewarding

### ISSUE THREAD

**Issue by bosnav** [BenCodez/VotingPlugin#906]
Latest version of VP.
Paper 1.16.1 server version. (Bungee Server)

How do I set it to only joined server will the reward be given? Because even though when they are joining the other server they still receive the reward.

**Comment by BenCodez** [comment]
What setup are you using?

**Comment by bosnav** [comment]
Proxy method

**Comment by BenCodez** [comment]
That's not a method?

https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

Anyway just set sendtoallservers to false

**Comment by bosnav** [comment]
ooof im talking about the method on votifier sorry.

**Comment by bosnav** [comment]
should I install the votifier to bungee server only?

**Comment by BenCodez** [comment]
Yeah, follow one of those setups, probably PLUGINMESSAGING or MYSQL

Both can do what you want

**Comment by bosnav** [comment]
Thanks for now. I'll be updating you as soon as I did it :D

**Comment by bosnav** [comment]
oofs sory, I couldn't find this > sendtoallservers

**Comment by BenCodez** [comment]
Its in the votingplugin bungee config

**Comment by bosnav** [comment]
Aight!

**Comment by bosnav** [comment]
Is there a new placeholder for the latest version? The current one I am using does not parse or what I think.

**Comment by BenCodez** [comment]
What do you mean?

**Comment by bosnav** [comment]
Help.

Error dispatching event com.vexsoftware.votifier.bungee.events.VotifierEvent@774c7d32 to listener com.Ben12345rocks.VotingPlugin.bungee.Bungee@20de05e5

**Comment by BenCodez** [comment]
Full error?

**Comment by bosnav** [comment]
WARNING Error dispatching event com.vexsoftware.votifier.bungee.events.VotifierEvent@4a9595b0 to listener com.Ben12345rocks.VotingPlugin.bungee.Bungee@20de05e5
16.08 17:50:15 [Server] INFO java.lang.NullPointerException
16.08 17:50:15 [Server] INFO at com.Ben12345rocks.VotingPlugin.bungee.Bungee.vote(Bungee.java:331)
16.08 17:50:15 [Server] INFO at com.Ben12345rocks.VotingPlugin.bungee.Bungee.onVote(Bungee.java:320)
16.08 17:50:15 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16.08 17:50:15 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16.08 17:50:15 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16.08 17:50:15 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
16.08 17:50:15 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
16.08 17:50:15 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
16.08 17:50:15 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
16.08 17:50:15 [Server] INFO at com.vexsoftware.votifier.bungee.NuVotifier.lambda$onVoteReceived$2(NuVotifier.java:366)
16.08 17:50:15 [Server] INFO at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
16.08 17:50:15 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16.08 17:50:15 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16.08 17:50:15 [Server] INFO at java.lang.Thread.run(Thread.java:748)

**Comment by BenCodez** [comment]
bungeeconfig?

**Comment by bosnav** [comment]
# Set bungeecoord to true on servers on the network (In VotingPlugin)
# Set server name in each server related to what it is on bungee
#
# MYSQL Required on all setups
# MYSQL INFO --------------------------
Host: ''
# Default port is 3306
Port: 3306 
Database: ''
Username: ''
Password: ''
# Max number of connections
MaxConnections: 1
# Maxium size of caching mysql
# -1 for no limit
# Affecting this value may affect performance
MaxSize: -1
# Table name prefix, for use with mutliple servers
Prefix: ''
#UseSSL: true

Debug: false
# Have a reward on each server
# If false, will send to online server only
SendVotesToAllServers: false
# List of servers the plugin won't send the vote to
# Uses names from bungeecoord config if not using SOCKETS method
BlockedServers:
- hub

# What type of bungee setup
# Requires restart and set on all servers
# https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups
# Available:
# SOCKETS 
# PLUGINMESSAGING 
# MYSQL
BungeeMethod: PLUGINMESSAGING

# ----------------------------
# SOCKET METHOD Only, ignore otherwise
# ----------------------------
FallBackServer: hub

# Tell servers to broadcast
Broadcast: true

# Bungee communication, Add this to each spigot server
BungeeServer:
  Host: '139.99.125.166'
  Port: 25570
  
# Bungee communication, add each spigot server here
SpigotServers:
  sb:
    Host: '51.79.136.100'
    Port: 25565
  survival:
    Host: '139.99.2.172'
    Port: 25565

**Comment by BenCodez** [comment]
Pastebin... Full startup log?


Use this build as well:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by bosnav** [comment]
https://pastebin.com/XJ9tYuCd

**Comment by BenCodez** [comment]
I'm lost on what your doing right now.

Pastebin your configs (including bungee) Looks like you didn't set the bungeemethod on the spigot servers.

**Comment by bosnav** [comment]
Here's the votingplugin config on one of my servers 
https://pastebin.com/jkYULw1z

**Comment by BenCodez** [comment]
Pastebin your bungee config... Full start log on bungee

**Comment by bosnav** [comment]
Config: https://pastebin.com/YrEXSepB
Start Log:https://pastebin.com/RsNALYx1

**Comment by BenCodez** [comment]
1. Mysql isn't setup
2. I don't see votingplugin enabling on bungee (is the jar on there)

**Comment by bosnav** [comment]
1.Aight, setting up mysql right away. sorry.
2. Yes, the dev build one

**Comment by bosnav** [comment]
Latest bungeeconfig: https://pastebin.com/XFRPTE2S
Latest bungee startup log: https://pastebin.com/df68q8je
Latest spigot startup log: https://pastebin.com/m7EUrSGL

**Comment by BenCodez** [comment]
There is no sign of votingplugin enabling on bungee

**Comment by bosnav** [comment]
But why does this show up > 16.08 18:19:42 [Server] INFO [VotingPlugin] Vote received MinecraftServers.org from service site MinecraftServers.org on my bungee console

**Comment by BenCodez** [comment]
No idea. Something is up with what your sending me.
