### ISSUE TITLE
Clickable Links

### ISSUE THREAD

**Issue by slvlr** [BenCodez/VotingPlugin#907]
**Versions**
5.2.3   Paper 1.16.1  build 135

**Describe the bug**
When you type /votelist all the vote links come up and you can click them.
When you type /vote and click on one site, when you click the link it is not clickable. 

**To Reproduce**
1) type /vote
2) click the emerald block to select a site
3) click the link it chat - it will not open a web page.

**Expected behavior**
Expected to open a web page, or be given the option to copy it.

**Comment by BenCodez** [comment]
Disable ForceLinks in the config?

**Comment by slvlr** [comment]
Where is this please? I can't see anything called ForceLinks in config.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L146

Might need to add it (It defaults to true)

**Comment by slvlr** [comment]
But my issue is that the links are not possible to click. I want them to be able to click?

**Comment by slvlr** [comment]
/votelist are clickable (correct)

but
/vote
*clicks vote site* then the link here is not clickable.  <-- how do I make it clickable this way too? It used to be.

**Comment by BenCodez** [comment]
Sometimes forcelinks needs the http or www for it allow the link to be forced, it acts up on not full url links, disabling it might fix it

**Comment by slvlr** [comment]
It is http:// https://gyazo.com/d6a6a811bd264a1480cf88c0a87dc544

I disabled this and now they work.

**Comment by BenCodez** [comment]
Didn't have www. in there, would do it.
