### ISSUE TITLE
votingplugin_next_anysite - Any available site

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#908]
**Is your feature request related to a problem? Please describe.**

Hi, this is a little bit related to the problem, when I show in my scoreboard when they can vote, I can only use scoreboard votingplugin_next_specificsite, but when I have multiple sites, then it's a little bit weird.

**Describe the solution you'd like**
I'd like solution if you add way to add placeholder votingplugin_next_anysite, which will show automatically the nearest possible voting on any available site.

**Describe alternatives you've considered**
Don't have an idea on alternative.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Give it a try, untested

**Comment by bobhenl** [comment]
No, doesn't work, it shows the voting for the second (later) vote site... https://imgur.com/a/93UUdXG

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should be good now.

**Comment by bobhenl** [comment]
Still seems that no? https://imgur.com/ZSjRNBz

**Comment by BenCodez** [comment]
Works fine for me. I also have no idea what I'm looking at on that screenshot

**Comment by bobhenl** [comment]
One emerald block is available, so one vote site is available, should show me, that I can vote, at the scoreboard on the right is time 16h 28m, what's showing time for next voting from redstone block (another site, longer waiting site)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Now?

**Comment by bobhenl** [comment]
No it isn't 😅 
Why it doesn't use string from?
        Info:
          # Message when player can vote
          CanVote: 

Wanna have it translated

**Comment by BenCodez** [comment]
Now?
http://ben12345rocks.com/job/VotingPlugin/

I just hard coded it, will use that option now.

**Comment by bobhenl** [comment]
Yeah now it seems working but we will see when I could vote on the second votesite.

And what about this?
				return "No votesites";

**Comment by BenCodez** [comment]
Should never return that unless there is an error.

**Comment by bobhenl** [comment]
Ok, great, now you can try focus on making this placeholder somehow related to IP or more players on one IP :P

**Comment by bobhenl** [comment]
And thanks for adding, you were fast 💯

**Comment by bobhenl** [comment]
Still doesn't work @Ben12345rocks  😅 When I voted for the second site, where I need to wait 20h, it worked, it showed me that I can vote again, because the first one, where I have to wait 2h was available, so I vote also there... but now, instead showing that I can vote for 2h again on the first site, it's showing me the second again.
https://imgur.com/Y4T2ftH

**Comment by bobhenl** [comment]
But now it's showing right, even when I voted it's showing 2 hours, but was broken after voting on this second one and then first one prob. https://imgur.com/E5rZKr, as you can see on previous image.

**Comment by BenCodez** [comment]
I think it works just fine. Your gonna have to explain more, those screenshots are pointless to me.

Use /papi parse me %VotingPlugin_Next_AnySite%

If you can vote on any site it should say you can vote, if all sites can't be voted on it says the shortest time.

**Comment by bobhenl** [comment]
Yeah now it shows right, but first time when I tried voting on the second (longer duration) site, then on the short, then it showed me time of the longer duration site.... If happens again, will let you know. Also will try papi parse when this happens.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Try with that

**Comment by bobhenl** [comment]
OK, seems fixed. CLosing.

**Comment by bobhenl** [comment]
Happened again Ben :( https://imgur.com/a/vqGp6wf @Ben12345rocks  There shoudl be 1h and 56 min instead of 19h 56 min

**Comment by bobhenl** [comment]
https://imgur.com/qi1N8gD And papi parse doesn't work.

**Comment by bobhenl** [comment]
https://imgur.com/SQItHT0 After downloading papi ecloud (wtf, but it worked without too... and look, it's wrong). Btw do I need to download it on second server too?


And look at this, I can vote earlier.... https://imgur.com/a/GcC6RPG

**Comment by BenCodez** [comment]
Each server needs the expansion.

http://ben12345rocks.com/job/VotingPlugin/

That fix it? From my testing it works.
