### ISSUE TITLE
Uppercase not translated inside commands reward.

### ISSUE THREAD

**Issue by Bibithom** [BenCodez/VotingPlugin#911]
Hello !
**Versions**
VotingPlugin : 5.23 | PaperMc #136

**Describe the bug**
In my reward file, i've define a commands wich give an enchantedbook with mending. When this reward is executed, command is not correctly translated so, enchanted_book is useless for players.
Error seems to be this : Uppercase are not used in command.

**To Reproduce**
1. Create a rewardfile with this command as reward :
    - minecraft:give %player% enchanted_book{StoredEnchantments:[{id:"minecraft:unbreaking",lvl:3s}]} 
2. Test reward
3. Here we go, you get an EnchantedBook, with unbreaking as nbt but unusable

**Expected behavior**
Get a traditionnal enchanted book that works with anvil

**Screenshots/Configs**
rewardfile :
Commands:
- minecraft:give %player% enchanted_book{StoredEnchantments:[{id:"minecraft:unbreaking",lvl:3s}]}

Difference between expected EnchantedBook and obtained : (first is traditionnal obtained via this command in game, second is obtained with rewardfile
![image](https://user-images.githubusercontent.com/18242631/90602757-89e85600-e1fa-11ea-8389-9038cd85fe08.png)

**Additional context**
No error in log.

Have a good day ! Thanks in advance for your help.

**Comment by BenCodez** [comment]
Could use the built in item reward? Also just tested it, casing seems to work fine

**Comment by Bibithom** [comment]
Which's data should i insert to assign an enchantement to an enchanted book ? I don't know where i can find this information.

id: ENCHANTED_BOOK
data: ?

**Comment by BenCodez** [comment]
Just add regular enchants (default examplebasic reward has an example)

**Comment by Bibithom** [comment]
I've tried it, thank's it seems working, have a good day !
