### ISSUE TITLE
Shutting down mysql can take significant time

### ISSUE THREAD

**Issue by Johnibur** [BenCodez/VotingPlugin#912]
**Versions**
VotingPlugin 5.23
git-Paper-134

**Relevant information**
Using mysql storage, with bungeecoord PLUGINMESSAGING configuration, this is one of the "clients" receiving votes from VotingPlugin on Bungee.

**Context**
Shutting down the server can take more significant time than it usually does, due to being blocked on VotingPlugin mysql shut down process. The following line is being displayed and can stay on this for up to 3 minutes before moving on:
`[VotingPlugin] Shutting down mysql, query size: 2082`

**Comment by BenCodez** [comment]
It will finish processing the queries before shutting down, it's just a matter of how slow the queries take to process. It's either that or you loose data

**Comment by Johnibur** [comment]
Why not making them process more regulary instead of waiting for shut down?

**Comment by BenCodez** [comment]
It is already. (Checks every few seconds) Not sure why it's taking so long for that. You would need to set debuglevel to EXTRA and send the log.

**Comment by Johnibur** [comment]
Okay I set debug to extra. Will send the logs on next restart.
I have already noticed no matter if the query size is a few hundred querries or a few thousands, the delay is always 2 minutes and 59 seconds.

**Comment by BenCodez** [comment]
It's set to a max of 3 minutes to finish the queries. Figured it would be long enough.

**Comment by Johnibur** [comment]
The extra level does not display anything usefull but the number of queries.

```
[22:22:55] [Server thread/INFO]: [VotingPlugin] Disabling VotingPlugin v5.23
[22:22:55] [Server thread/INFO]: [VotingPlugin] Shutting down mysql, query size: 2229
[22:22:55] [Server thread/INFO]: [VotingPlugin] ExtraDebug: Query Size: 2229
[22:25:56] [Server thread/INFO]: [Vault] Disabling Vault v1.7.3-b131
```

**Comment by BenCodez** [comment]
I lowered the delay to 1 minute in the latest dev build. Not sure why there is 2000 queries to run on shutdown, it shouldn't be that high at shutdown.

**Comment by Johnibur** [comment]
The issue does not happen with version v5.23.3, the number of remaining queries is no longer that high.
