### ISSUE TITLE
Split Votes

### ISSUE THREAD

**Issue by elaineandsparky** [BenCodez/VotingPlugin#914]
This was an issue on our 1.16.1 server and also when the server updated to 1.16.2. both with the latest plugin version and the previous one.

My votes (elaineandsparky) have been splitting in two for the past couple of months and this month it has happened for another player. 

![image](https://user-images.githubusercontent.com/69724087/90951739-63722700-e455-11ea-9302-316caab29fce.png)
![image](https://user-images.githubusercontent.com/69724087/90951764-8ef51180-e455-11ea-9529-ac23460944a0.png)

**Comment by BenCodez** [comment]
Confirm latest version? Might need a copy of your database to see what happened.

**Comment by elaineandsparky** [comment]
we are using 5.23

**Comment by BenCodez** [comment]
Gonna have to see a copy of your database then

**Comment by elaineandsparky** [comment]
sorry. could ihave a bit of guidence on what exactly you need to see and how to share it? I'm new to all this

**Comment by BenCodez** [comment]
Send either your user.db (if using SQLite) or mysql table

**Comment by elaineandsparky** [comment]
i hope this is what you are after

[voteplugin users.txt](https://github.com/Ben12345rocks/VotingPlugin/files/5112566/voteplugin.users.txt)

**Comment by BenCodez** [comment]
Take doesn't work. I think it might be mysql dump file I need, not sure, been awhile since I had to do it.

**Comment by elaineandsparky** [comment]
yeah i have no clue about that sorry

**Comment by BenCodez** [comment]
Just looked it up, you need to do a MySQL dump, can't really help you with that, google is my suggestion. But without that I can't really do anything to look into your issue.

**Comment by elaineandsparky** [comment]
ok i've found mysql database for my server but my host says it's not generally possible to get a dump for just one plugin database.
My dev is away for a week (she didn't know why votes were splitting and suggested contacting you) and i don't want to mess around with mysql not knowing what i'm doing.

**Comment by BenCodez** [comment]
Well, my first guess is there is 2 entries with your name. Which would have to be from 2 different uuids (Maybe online/offline uuids mixed?).

**Comment by elaineandsparky** [comment]
online/offline was my guess too but i'm pretty sure that would only be one vote site which happens online due to delay with the votes coming through (i do all my voting whilst i'm loading up mc so offline) is there a way to fix that so online and offline gets given the same uuid?

**Comment by BenCodez** [comment]
That's depending on the server setup.
