### ISSUE TITLE
%Player% placeholder doesn't work in GUI / VoteGUI

### ISSUE THREAD

**Issue by I-Knight-I** [BenCodez/VotingPlugin#915]
**Versions**
VotingPlugin: 5.23
Paper-110 MC 1.16.1

**Describe the bug**
%Player% placeholder doesn't work when using it under VoteGUI for player heads or player names. 

**To Reproduce**
1. Edit an item under `GUI.VoteGUI.Name` or `GUI.VoteGUI.Skull` to include %Player% (or %player%)
2. Reload using /av reload
3. Open GUI 
4. %Player% is not replaced with player name / skull

**Expected behavior**
%Player% is replaced with player name / skull

**Screenshots/Configs**
![Related configs + picture of GUI](https://user-images.githubusercontent.com/26165117/90959402-d3eb6900-e492-11ea-8fc4-8163fde5a61b.png)

[.ZIP from /av report](https://mega.nz/file/TVVlnSjT#1KdVeFdVVhcubI1ciEfEynS7rgctNaglUxZJHA5ElCU)

**Additional context**
%Top% and other placeholders from previously in the config also don't work. Would appreciate it if you parsed them within GUI's so that I can put the name of the item as the `Title`; like so:
![image](https://user-images.githubusercontent.com/26165117/90959339-5b84a800-e492-11ea-85b3-31bd6f5fad2c.png)

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This do it?

**Comment by I-Knight-I** [comment]
Yup, that fixed %Player% for both username and the skull.

Do you reckon you could also allow the other placeholders, like %Top%, too? Would greatly appreciate it.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Added

**Comment by I-Knight-I** [comment]
Appreciate it, thanks man.
