### ISSUE TITLE
Unable to click voting links.

### ISSUE THREAD

**Issue by JoshuaRouillard** [BenCodez/VotingPlugin#916]
Upon installing ViaVersion, ViaBackward, and ViaRewind my voting links have become unclickable. I've came here and Installed your latest stable version from earlier today hoping that it'd fix the issue but unfortunately it didn't. Anyway to fix this while keeping the viaVersion plugin + their addons. Thanks!

**Comment by BenCodez** [comment]
Set ForceLinks to false in the config (May need to add that option)

**Comment by JoshuaRouillard** [comment]
Fixed my issue. Thanks so much for the quick reply!
