### ISSUE TITLE
colored links not clickable anymore

### ISSUE THREAD

**Issue by ScuroK** [BenCodez/VotingPlugin#917]
**Versions**
Plugin: 5.23
Spigot: git-Paper-137

**Describe the bug**
colored links are not clickable anymore. if i use something like '&dLINK' its not clickable anymore.

**To Reproduce**
use colored voting link with '' symbols

**Expected behavior**
clickable links using color codes

**Comment by BenCodez** [comment]
Either have the color code in the Config.yml or disable ForceLinks in the config

**Comment by ScuroK** [comment]
i cant find this settings. did anything change? because untill i updated today it worked just fine using a url like '&dhttps://link.com'

**Comment by BenCodez** [comment]
You need to add it. Default config on github.

**Comment by ScuroK** [comment]
sry but i dont get it. can you give me an exemple how to get a colored url?

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L146

Set that option to false

**Comment by ScuroK** [comment]
ok that fixed it.  i didnt know that i have to manually update my config :S
