### ISSUE TITLE
Vote shop disabled- translatable?

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#918]
**Is your feature request related to a problem? Please describe.**
No, I just wanna translate vote shop disabled message, when I disabled vote shop.
**Describe the solution you'd like**
Adding this string to config.

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L588

http://ben12345rocks.com/job/VotingPlugin/

Added.
