### ISSUE TITLE
Can't find voting sites

### ISSUE THREAD

**Issue by Truongvv10** [BenCodez/VotingPlugin#919]
Hi there, I can't set up the votings sites on my server, I'm getting the following message: https://pastebin.com/sU03dBZ7

Here is also my logs: https://pastebin.com/QPjQg0e4

**Comment by BenCodez** [comment]
1. Don't use plugman to reload the plugin, use /av reload
2. Does the server get the vote? (There will be a message in console if so)
3. Check your votesites.yml
