### ISSUE TITLE
Latest Version of VotingPlugin 5.23.1 says that there is an update available '5.23'

### ISSUE THREAD

**Issue by TheLastBlockbender** [BenCodez/VotingPlugin#921]
**Versions**
Spigot 1.16.2 and VotingPlugin 5.23.1

Title pretty much explains it all.

**To Reproduce**
Simply start up the server and you'll see the error in the server console.

**Expected behavior**
It should know that 5.23.1 is the latest version, not 5.23

**Comment by BenCodez** [comment]
It's a bit delayed some times.

**Comment by BenCodez** [comment]
I just tested it and works fine for me.

**Comment by TheLastBlockbender** [comment]
Ok good to know thanks.
