### ISSUE TITLE
NullPointerException at boot

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#922]
**Versions**
5.23.1

**Describe the bug**
I switched from per server setup to bungeecord setup. (Bungee catches votes, broadcasting via pluginmessaging)
Most servers booted fine. 1 did not. Got an error, votingplugin kept nagging errors.
https://pastebin.com/raw/fcGy1w3j
After loading the plugin manually, it works fine.
(https://pastebin.com/raw/tSyrvS9D)

**To Reproduce**
1. Boot server

**Expected behavior**
No errors

**Screenshots/Configs**
Further information at request

**Additional context**
msql database is a Galera cluster
PlotSquared seems to be loading stuff from the msql database too, at that time

**Comment by x1p** [comment]
Unloading votingplugin via plugman is highly risky. If I try to unload/load/unload votingplugin on a test server (with connection to the database) it stalls the server, CPU 100%, completely hangs, reboot
https://pastebin.com/raw/EtpPSzK0

**Comment by BenCodez** [comment]
1. Looks like some database issue:
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock: wsrep aborted transaction
2. Don't use plugman, it will break things, any issues related to that is out of my control
3. http://ben12345rocks.com/job/VotingPlugin/ This will help a bit.

**Comment by x1p** [comment]
1. NPE is gone for now. It loads on all servers fine. :+1: 
2. I know plugman is not the recommended. But I had no option since votingplugin didn't start. The alternative is to reboot the game but that annoys players.
3. I'm used to the deadlock. From what I understand the deadlock appears when 2 things want to write at the same time. What I don't understand why it wants to write at boot. But that's more for issue #684.

**Comment by BenCodez** [comment]
Well the source the problem is that deadlock
