### ISSUE TITLE
Voting rewards not working

### ISSUE THREAD

**Issue by imbsqt** [BenCodez/VotingPlugin#924]
**Versions**
Plugin version and spigot version 5.23.1 & spigot-1.16.2.jar
![ingame](https://user-images.githubusercontent.com/70241440/91236301-7c1d5e00-e72f-11ea-8c94-3f3ef7868ab7.png)
![rewards](https://user-images.githubusercontent.com/70241440/91236303-7cb5f480-e72f-11ea-83f1-4cfce3167b5e.png)
![votesites](https://user-images.githubusercontent.com/70241440/91236304-7cb5f480-e72f-11ea-82bc-02317f632471.png)

Hi,

I am getting the following error when trying to run one single command from console when a player votes.

Can you assist?

Thank you

**Comment by BenCodez** [comment]
1. Don't use ExampleBasic as a reward, use a different name
2. You have to delete the messages part

**Comment by imbsqt** [comment]
Thanks so much! that all worked <3
