### ISSUE TITLE
Custom links with placeholders

### ISSUE THREAD

**Issue by Korinocho** [BenCodez/VotingPlugin#925]
It would be amazing to make customized links.
Like, for example, minecraft-mp.com allow customized vote-links, so i can add the nick in the link and it will be autofilled in the nick box.
Example: https://minecraft-mp.com/server/258785/vote/?username=KRNCHO (you can change KRNCHO to anything else and it will be autofilled)
It would be amazing to be able to make this automatic by some placeholder.

The way, can be this:
The link in the VoteSites file should be between '' and anything else will be detected as placeholder like this:
    VoteURL: 'https://minecraft-mp.com/server/258785/vote/?username='%nickname%

This can help some players dont misswrite their nicks and be 100% sure to receive their rewards.

**Comment by BenCodez** [comment]
Already possible with %player%

**Comment by Korinocho** [comment]
Really? oh,  didnt found it in the wiki. Thanks!
Could you indicate me how to use it? I changed the link to https://minecraft-mp.com/server/258785/vote/?username=%player%
but the plugin wont load :/
