### ISSUE TITLE
Point dupe

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#927]
**Versions**
Votingplugin 5.23.1 build 360
Paper 1.16.1

**Describe the bug**
A player voted this morning, Got 2 points
In the afternoon he came online. Saw his 2 points. And bought something.
Points went to 0.
After 15 min., his points were back on 2.
Bought again some stuff for those 2 points.
Then they remain on 0.

**To Reproduce**
1. I wish I knew. I did several tests and I haven't figured it out.

**Expected behavior**
Consistent counting

**Screenshots/Configs**
-

**Additional context**
Bungee setup using pluginmessaging. Config:
```
ExtraBackgroundUpdate: false
ClearCacheOnUpdate: true
ClearCacheOnJoin: true
ClearCacheOnVote: true
ClearCacheOnLeave: true
ClearCacheOnVoteShopPurchase: true
```

**Comment by BenCodez** [comment]
Are you forwarding with nuvotifier?

**Comment by x1p** [comment]
```
forwarding:
  method: none
```

**Comment by BenCodez** [comment]
I think I need more details. Number of servers connected? Do you get 2 points on a vote?

**Comment by x1p** [comment]
1 point per site. 2 in total
At this point I only have the normal logs.
Bungee: https://pastebin.com/MrGbJj2N
I'm trying to gather more debug logs.
4 servers connected
Bungee plus 4 game modes

**Comment by x1p** [comment]
I think the cause is somewhere in the buying in the voteshop, not updating the database. Not sure tho
Or maybe a conflict that 2 sync events overwrite each other

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Added more debug on bungee and minor spigot changes.

My guess is that it may not be saving the data fast enough, might be the cause.

**Comment by x1p** [comment]
Ok, I will try. I have the debug to file on the games.

**Comment by x1p** [comment]
It didn't happen today despite some testing with a couple of accounts.

**Comment by BenCodez** [comment]
Maybe those changes I did helped enough to solve it?

**Comment by x1p** [comment]
I thought only the debug was added but yeah who knows.

**Comment by BenCodez** [comment]
Made a little change to increase background query sending from half a second to 4 times a second, maybe that did it.

**Comment by x1p** [comment]
Ok, lets close this issue. I'll notify when it happens again

**Comment by x1p** [comment]
I have the feeling something is still not right.

Day1:
Morning: Player Votes twice.
Bungee says: "Setting Points to 2"
Bungee says: "Setting Points to 3"
Afternoon: buys something (on the spigot server), uses all points.
Evening: votes once.
Bungee says: "Setting Points to 4" actual points (visible in game) unknown, player was connected via chatapp

Day2:
Morning: Player Votes twice.
Bungee says: "Setting Points to 1"
Bungee says: "Setting Points to 2"
In game: points are 2 (player expected 3)

I wish I had a much simpler (transaction) log what happens to vote points without all cluttering from existing debug (file)

Edit: maybe there is a conflict in syncing. Maybe I should disable some sync triggers...

**Comment by BenCodez** [comment]
Well, bungee doesn't have any caching, so it pulls direct from the database. So somehow the spigots servers aren't uploading to the database correctly. Confirm latest version? What happens if you manually set points and do a vote?

**Comment by x1p** [comment]
av user player addpoints or av vote player ?

**Comment by BenCodez** [comment]
Yeah that works.

**Comment by x1p** [comment]
Player has 3 points now. The database is updated too.

**Comment by BenCodez** [comment]
Hmm. I'll need more info I guess? I could force the voteshop to not cache the query maybe.

**Comment by x1p** [comment]
I'll turn on some logging. I hate debating on points with players.

**Comment by BenCodez** [comment]
Yeah I bet. My only guess if there is a lot of data to sync it might take some time? Maybe see how long it takes?

**Comment by BenCodez** [comment]
Made points always update immediately
http://ben12345rocks.com/job/VotingPlugin/

See if that solves the issue.

**Comment by x1p** [comment]
```yaml
# Whether or not to log every vote to a file
# Use this if you wanna track player votes
# Not recommended though
LogVotesToFile: true
```
This does nothing, right?

**Comment by BenCodez** [comment]
Not with bungeecord, maybe should add something for that...

**Comment by x1p** [comment]
I haven't heard any complaints of lost points anymore.
No transaction log and no complaints so I can't tell if it still happens. Probably solved I guess.

**Comment by BenCodez** [comment]
What some sort of vote shop log help maybe?

**Comment by x1p** [comment]
Sure but my servers use both the internal as well as the bossshop as a vote shop so that would probably be not that easy.

**Comment by BenCodez** [comment]
Well, never mind then :P

**Comment by x1p** [comment]
Havent had any complaints since
