### ISSUE TITLE
Can't send command '/Vote List' in console

### ISSUE THREAD

**Issue by TheDevTec** [BenCodez/VotingPlugin#928]
**Versions**
PaperSpigot: 1.16.1, VotingPlugin: v5.20.5

**Error**
https://pastebin.com/zL5MCtJF

**Comment by BenCodez** [comment]
VotingPlugin v5.20.5

Your outdated.

**Comment by TheDevTec** [comment]
Ooh, Last update fixed this bug, but in console I see this "Czech-Craft - [Text="https://czech-craft.eu/server/XXX/vote/?user=%player%",url="https://czech-craft.eu/server/moneyak/vote/?user=%player%"]"

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should be good now.
