### ISSUE TITLE
1.16 Heads Not working in Reward Files

### ISSUE THREAD

**Issue by Royster-85** [BenCodez/VotingPlugin#929]
Im getting this issue when trying to run a reward file that only has heads in 1.16.2:

![Capture2](https://user-images.githubusercontent.com/44376499/91644541-d6bb0080-ea34-11ea-97b1-a89e3b262ad2.PNG)

However, I know the command is correct because it runs absolutely fine in a command block. I am using the correct 1.16 command as well.

Any ideas?

Thanks

**Comment by BenCodez** [comment]
For whatever reason those commands don't seem to work, use the builtin item rewards, even though it works fine what I test them.

**Comment by Royster-85** [comment]
Could you clarify where you mean. Do you mean in the config file itself?

Thanks

**Comment by BenCodez** [comment]
https://github.com/Ben12345rocks/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleBasic.yml#L26

**Comment by Royster-85** [comment]
Okies, Do you think you'll be able to get the issue resolved because I just found out that it doesnt just effect heads. If you try to give someone a shulker box with items in, it only gives them the shulker and named items and lore are not working either. Again this is in a reward file and the commands work fine in a command block.

**Comment by BenCodez** [comment]
Well everyone else that has reported this seems to have this issue but it works fine for me when I copy the command, so I got no idea.

**Comment by Royster-85** [comment]
Ahhh okies, I know it was working fine in 1.15.2 (using 1.15 commands) and using version 5.21.3. Just waiting to see if it was also fine in 5.22

**Comment by BenCodez** [comment]
What about the latest version?

**Comment by Royster-85** [comment]
It doesnt work in 1.15.2 using 5.23.1

**Comment by BenCodez** [comment]
Send your command, I'll test it later see if it works for me.

**Comment by Royster-85** [comment]
Ive sent a copy of 2 reward files. One is just heads commands and the other is one of my vote rewards.
[Reward FIles.zip](https://github.com/Ben12345rocks/VotingPlugin/files/5145934/Reward.FIles.zip)

**Comment by Royster-85** [comment]
Just re-looked at something and I've noticed that in the 1.16 command for heads, the "I" is capitalized but in the console, its turning it into a lower case "i" Could be whats causing the issue. Just a thought

**Comment by BenCodez** [comment]
Make the commands minecraft:give instead of give, seems to fix the issue.

**Comment by Royster-85** [comment]
Okies, i'll try that and get back to you. Thanks

**Comment by Royster-85** [comment]
Ok new development. In 1.16.2 Im using 5.23.1 VotingPlugin and PlaceholderAPI 5.10.9 and its giving me the issues. However, if I downgrade Placeholder to 5.10.7, Everything works fine. All the commands run, all the heads show up correctly, Shulkers with items in load correctly and Named/Lores appear. So it seems theres something not right with the PlaceholderAPI plugin. Not sure if this effects you or not but thought i'd share it

**Comment by BenCodez** [comment]
Update the expansion

**Comment by Royster-85** [comment]
Nope, updating the expansion and using 5.10.9 gives the issue. reverting back fixes it

**Comment by BenCodez** [comment]
Delete the expansion and redownload it? Confirm you have the latest expansion? If not I got no idea.

**Comment by Royster-85** [comment]
Ok, Ive done some more testing. Im using version 5.23.2 in both 1.15.2 and 1.16.2, im using PlaceholdersAPI plugin version 5.10.7 in both too. Im not using any of the extensions either. In both instances, everything works as it should. All commands run without issue. As soon as I update the Placeholders plugin to 5.10.9, it stops working. I also tried it with the extensions and still had the same failed result. So I know that some methods were depreciated in 5.10.9 according to their info page so it might have something to do with that.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That better? I disabled the bracket placeholders with {}, think that might be the cause. The latest version forces all the placeholders to lowercase.

**Comment by Royster-85** [comment]
I will test it shortly and let you know

**Comment by Royster-85** [comment]
Extremely promising. Just gonna run a few more tests but its so far working correctly with Placeholders 5.10.9 plugin version. Im not using extensions either.

**Comment by BenCodez** [comment]
When I tested it was working fine. Guessing it will be the same for you

**Comment by Royster-85** [comment]
Yep, can confirm its all back to normal. Just wanted to make sure but im happy with it, and im sure others will be too.. Many Thanks
