### ISSUE TITLE
Voteshop doesn't execute commands

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#931]
**Versions**
5.23.2

**Describe the bug**
Yesterday I had the bug that if someone bought something in the built in voteshop, the commands were not executed.
It appears that when `ProcessRewards: false` is set, the voteshop still works, but doesn't execute.
Maybe this is intentional, who knows. If so, it shouldn't withdraw the points.

**To Reproduce**
1. Set ProcessRewards: false
2. Set up a voteshop that gives to a certain permission or just any other command
3. Buy something from the voteshop
4. See that it takes the points
5. See if the command is executed
6. Repeat steps with ProcessRewards: true

**Expected behavior**
If voteshop works, the commands should be executed because it takes your points as well.

**Screenshots/Configs**
-

**Additional context**

**Comment by BenCodez** [comment]
Would disable the voteshop on that server in that case.

**Comment by x1p** [comment]
But I need the voteshop on that server. So i need to enable rewards. The rewards on the votesite file are empty so it doesn't care in this case. But it funny that disabling something has consequences on other things you might not expect.

**Comment by BenCodez** [comment]
Well, vote shop uses a reward, so disabling rewards will disable that.
