### ISSUE TITLE
Double, Tripple  broadcasts

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#932]
**Versions**
5.23.2

**Describe the bug**
I get double broadcasts, for every gamemode 1. So if there are players online on 4 gamemodes, I get 4 messages.
On 5.23.1, I didn't had this. I converted all config files nicely to new layout, exactly the same as it was on version 5.23.1.

**To Reproduce**
1. Set bungee to SendVotesToAllServers: true
2. Set all gamemodes as this: https://pastebin.com/srVhtkEU
3. Put several players online spreaded (or not) on the different gamemodes
4. See broadcasts

**Expected behavior**
I would expect to have a single broadcast per vote on all gamemodes under all circumstances no matter if there are people online or not.

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**
BungeeSettings: https://pastebin.com/srVhtkEU

**Comment by x1p** [comment]
If someone joins to another server, it empties a cache and broadcasts an old vote again. I didn't thought a gamemode had a cache and the bungee cache is empty.

I changed `BungeeBroadcast` to false on the gamemodes. Reload of the plugin didn't change anything but a complete restart seems to work. So I assume that this setting didn't work under 5.23.1 but works on 5.23.2 and it seems to function as an active broadcast to other gamemodes. I think it has to be false on a bungee setup if the bungee is the broadcaster.

I noticed the comments are changed a bit. But I have the feeling I miss something (after enable ...) :
```
# Get the plugin to broadcast to all servers
# If false you need to enable ...
BungeeBroadcast: false
```

**Comment by BenCodez** [comment]
Disable bungee broadcast?

**Comment by x1p** [comment]
> I changed BungeeBroadcast to false on the gamemodes.

I had BungeeBroadcast on every config. So on the bungee and the spigot servers.
I turned off the spigots' broadcast. Now it works well.

**Comment by BenCodez** [comment]
Good.
