### ISSUE TITLE
VoteParty (Vote Count isn't applying to the change)

### ISSUE THREAD

**Issue by DrSnowPengu** [BenCodez/VotingPlugin#933]
**Versions**
VoteParty 5.23.2 and Paper 1.16.2

**Describe the bug**
The vote party counts from /voteparty isn't change when i restart or reload the plugin after changing the amount to 500 from 150. It stays at 150 as for me instead of 500 when I type /voteparty

**Expected behavior**
I expect that the vote party count changes to 500 instead of 150 when I increased it.

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
1. https://gyazo.com/b45df249da49c238c66251cb93aebb0c and https://gyazo.com/b1294e4bfe7361d563b9ce7213a7ee34

**Comment by BenCodez** [comment]
Are you changing it in the specialrewards.yml?

**Comment by DrSnowPengu** [comment]
Nope, I was changing it in the config.yml

**Comment by BenCodez** [comment]
Latest update uses SpecialRewards.yml for that.

**Comment by DrSnowPengu** [comment]
Ah I see, ty for the advance notice. I guess it doesn't work on config.yml anymore.
