### ISSUE TITLE
Tab complete commands

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#934]
**Versions**
5.23.2 but I think this is present for a while

**Describe the bug**
The command `/avUserEditValue` is visible for all default players.
I don't think that av... commands should be visible for default players.

**To Reproduce**
1. Just start a server with votingplugin on it
2. join
3. Type in / and press tab
4. See command list presented by the tab completion of the server

**Expected behavior**
I don't think that av... commands should be visible for default players. Never.

**Screenshots/Configs**
![Screenshot_20200831_101830](https://user-images.githubusercontent.com/28690790/91698662-5e0e8e00-eb73-11ea-92e3-b6af9ac6f2ad.png)

**Additional context**
-

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should solve it, guess I removed that command awhile ago.

**Comment by x1p** [comment]
Fixed
