### ISSUE TITLE
Question of VoteURL

### ISSUE THREAD

**Issue by IstBolPlay** [BenCodez/VotingPlugin#935]
**Versions**
5.23.2 And Paper Spigot is 1.16.2

**Relevant information**
 VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'

**Context**
The context of this is based on that format, I see that I can hide the link through a text EJ: "Click here" And that clicking on that text opens the link, that's what I think. If so, I want to know how I can do it.

These are my questions:
1) What is this option really for?
2) How do I activate it?

**Comment by BenCodez** [comment]
Disable ForceLinks in the config, then set it like you have, should work.

**Comment by IstBolPlay** [comment]
disable ForceLinks option and use this '[Text = "Click Here", url = "www.planetminecraft.com/server/mexplex-survival-1-16-1-no-premium/"]' and it didn't work, how would it be the format in this case

Used Traslator, Sorry.

**Comment by BenCodez** [comment]
No spaces

'[Text="Click Here",url="https://www.planetminecraft.com/server/mexplex-survival-1-16-1-no-premium/"]'

**Comment by IstBolPlay** [comment]
No it doesn't work that way for me

**Comment by IstBolPlay** [comment]
No it doesn't work that way for me

**Comment by BenCodez** [comment]
Config.yml and VoteSites.yml?

**Comment by IstBolPlay** [comment]
Ammm what?

**Comment by BenCodez** [comment]
Send those files in a pastebin.

**Comment by IstBolPlay** [comment]
Okay

**Comment by IstBolPlay** [comment]
I'm sorry, as files of this style are sent, I don't know the term pastebin, I hope this doesn't bother

**Comment by BenCodez** [comment]
https://pastebin.com/ 

Copy and paste it there, send the link

**Comment by IstBolPlay** [comment]
Config
https://pastebin.com/nQfadRA1

**Comment by IstBolPlay** [comment]
VoteSites
https://pastebin.com/PWVG5Gby

**Comment by BenCodez** [comment]
You never set the vote url...

Also confirm your reloading with /av reload?

**Comment by IstBolPlay** [comment]
ou

**Comment by IstBolPlay** [comment]
All links work well until recently it stopped working, because it no longer gave rewards, it worked 1 time and no more

**Comment by BenCodez** [comment]
Because you added the color codes. Also don't use the special character for labing each vote site, just use vote3 instead vote3(whatever special character that is)

**Comment by IstBolPlay** [comment]
I'm sorry, could you help me

**Comment by BenCodez** [comment]
Just fix what I just said? 

Does the server get the vote? Check console on a vote

Does /av vote work?

**Comment by IstBolPlay** [comment]
![sadada](https://user-images.githubusercontent.com/68023645/91763952-0afd0100-eb9c-11ea-8623-58c672492ad3.png)
That's OK?

**Comment by BenCodez** [comment]
It's better

**Comment by IstBolPlay** [comment]
Okay then that's fine, now regarding this format '[Text = "ANY TEXT TO CLICK ON HERE", url = "URLHERE"]' could you help me now and tried and it still doesn't work

**Comment by BenCodez** [comment]
1. Don't use spaces (not counting within the "")
2. I don't see anywhere you set that

**Comment by IstBolPlay** [comment]
'[Text="Click Here",url="mcservidores.com/servidor/52"]'

Would it be like this?

**Comment by BenCodez** [comment]
Set as VoteURL, yes, just add https:// in the url

**Comment by IstBolPlay** [comment]
Oh it really works thank you very much
