### ISSUE TITLE
Client side hang up when near a top sign with skulls

### ISSUE THREAD

**Issue by rmalca** [BenCodez/VotingPlugin#936]
**Versions**
VotingPlugin version: 5.23.2
Paper version: 1.16.2 # 174

**Describe the bug**
Client side hang up when near a top sign with skulls.

**To Reproduce**
1. Create and teleport to empty world
2. Place block and sign with this content:
```
[votingplugin]
1
all
```

3. Walk away 150 blocks
4. Get closer to the sign (there will be a small hang). The more signs with skulls, it's more the hang.

**Expected behavior**
That does not generate any hang when you are near a sign.

**Screenshots/Configs**
![2020-08-31_18 40 08](https://user-images.githubusercontent.com/3759745/91779153-56bea300-ebba-11ea-95be-59f3df8bd376.png)

**Additional context**
Bungeecord setup.

**Comment by BenCodez** [comment]
Don't think there is anything I can do about that.

**Comment by rmalca** [comment]
Why not? Why is this problem? in my lobby it hangs between 3 and 6 seconds

**Comment by BenCodez** [comment]
I think it's just minecraft? Can your computer handle it?

**Comment by rmalca** [comment]
sure, it's just a 32GB ram i9 with NVME disk.

I have a plugin installed with the same functionality and I don't see the same thing happening to it

**Comment by BenCodez** [comment]
There is really nothing I can do, it's just minecraft loading in the skull. You can enable PreloadSkulls in the config, might help

**Comment by rmalca** [comment]
I already have that option enabled
``` PreloadSkulls: true ```

What happens there? Synchronously download data from server?

It's very strange. I just tried it with another plugin and it also has that hang (maybe even takes a little less)

Any advice? Write an issue to mojang? :v

**Comment by BenCodez** [comment]
PreloadSkulls is more for item form, wasn't sure if it applied to blocks. I mean, I have no control over it.

**Comment by rmalca** [comment]
question: when minecraft tries to load the head, is the load by the user id or by the head data? I don't have much information about how it works exactly

**Comment by BenCodez** [comment]
I got no idea

**Comment by ChrisTaylor201** [comment]
I think there's nothing we can do about this unless Mojang fixes it, see [MC-65587](https://bugs.mojang.com/browse/MC-65587).

**Comment by BenCodez** [comment]
Well closing this, since I can't do anything about it.

**Comment by rmalca** [comment]
Ok thanks for the information @christaylor201
