### ISSUE TITLE
Vote without name: additionalData:null

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#938]
**Versions**
5.23.2

**Describe the bug**
Someone voted but forgot to fill in it's name.
This results in an interesting expection. Maybe Votingplugin can protect itself and catch it gracefully.
https://pastebin.com/raw/GkZsNrpH

**To Reproduce**
1. Vote but forget to fill in the name
2. See error on bungee

**Expected behavior**
Catch gracefully like: no name received, disregarding vote or whatever

**Screenshots/Configs**

**Additional context**

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should do it.
