### ISSUE TITLE
Give/revoke voteshop items

### ISSUE THREAD

**Issue by phemmer** [BenCodez/VotingPlugin#939]
**Is your feature request related to a problem? Please describe.**
Currently there is no possible way to give or revoke voteshop items. At least not that I can see from the available commands.
This is problematic as sometimes it is desired to be able to give an item to a player without them having to spend points on it. This is not the same as just manually giving the result of the shop item (such as if the shop item is 1 diamond, giving the player 1 diamond directly), as voteshop items can have purchase limits, and so giving them the item without going through voteshop doesn't count towards that limit.
And inversely, if you want to refund a player, by taking the item (or whatever the shop item result is) from them, it doesn't decrement their purchase count, so they can purchase the item again in the future.

**Describe the solution you'd like**

While a "give voteshop item" command might be useful, this would not solve the problem of needing to refund. And for voteshop items which execute commands, reversing the command would require configuring the plugin to know what the reverse command is.

As such, it might instead be better to have a command which can adjust the tally of how many times the item has been purchased. Then the admin can manually give/refund, and adjust the counter without having to go into the database.

**Describe alternatives you've considered**

See previous section.

**Additional context**

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

/av user (player) forcevoteshop (shop) 

Already have a point command, not really gonna bother with a undo version, kinda hard to implement.
