### ISSUE TITLE
Grabbing/duping items from the gui

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#941]
**Versions**
5.23.2

**Describe the bug**
1. It seems that some players are able to grab the skulls from vote top menu
2. Clicking on the bow in the vote gui, triggers (my) worldguard.

Ad 2: on my creative server, the bow is prohibited. Clicking on this item in the menu triggers worldguard to tell me that this item is not possible.
I think these two bugs are caused by the same way the gui is presented. The client prob. thinks this items can be grabbed?

**To Reproduce**
1. Put the bow on the blacklist of worldguard
2. Click on the bow of the vote gui
3. See message

**Expected behavior**
No dupes, no extra worldguard message :-)

**Screenshots/Configs**
WorldGuard blacklist.txt
```yaml
[BOW]
on-place=deny,tell
on-acquire=deny,tell
on-drop=deny,tell
on-dispense=deny,tell
message=Sorry, this is prohibited.
```

**Additional context**

**Comment by BenCodez** [comment]
Does changing the item fix it?

**Comment by x1p** [comment]
I enabled the use of the bow. This solves it. Changing the bow to something different should solve it too.
I'm more concerned about the possible dupe of skulls/items in vote gui's

**Comment by BenCodez** [comment]
How is the duping happening? Is it worldguard that is doing it? Spam clicking? Or just open and grab the skull?

**Comment by x1p** [comment]
An new forein (overseas) player came online, went straight to vote top. (Without knowing what commands we have) He gave skulls to a regular player. He admitted he clicks very fast in order to try and grab the skull. Sometimes it works, mostly not.

**Comment by BenCodez** [comment]
You have the latest version right? If so this better? http://ben12345rocks.com/job/VotingPlugin/

You can also add SpamClickTime: 250 to the config.yml and increase that number a bit if needed. Will prevent spam clicks altogether.

**Comment by x1p** [comment]
At that time I had build 381 running

**Comment by BenCodez** [comment]
Would try with adding that option and setting it to 350 or something.

**Comment by x1p** [comment]
Will do

**Comment by x1p** [comment]
I already have 387 running. I'll add this option

**Comment by BenCodez** [comment]
What's your ip? I'll pop on and test it.

**Comment by x1p** [comment]
I don't have this option yet. Tomorrow.

**Comment by BenCodez** [comment]
Made some more changes, should completely prevent the duping, build 396 or higher.

**Comment by x1p** [comment]
I think we can close this issue
