### ISSUE TITLE
vote party

### ISSUE THREAD

**Issue by elaineandsparky** [BenCodez/VotingPlugin#942]
Can I check this is setup correctly to give all players who voted in one day a voteparty crate key once 30 votes have been reached. I don't think i've got the reward command at the bottom correct. Also what time does it reset (and timezone), do the players who voted need to be online or will they get their rewards when they next login and can more than one party be had a day?
Can I also check what the command /voteparty does as when i tested it it states "vote party not enabled" despite the below config being live on the server already.

VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 30
  # Increase the amount of votes required on each vote party reached
  #IncreaseVotesRquired: 10
  # If true, players who did not vote to reach the votes required will
  # recieve the reward
  GiveAllPlayers: false
  # If true, the vote count will reset each day
  ResetEachDay: true
  # Reset at the end of the month
  ResetMonthly: true
  # Reset extra votes
  ResetExtraVotesMonthly: false
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 0
  # Broadcast when vote party reached
  Broadcast: '&cReached the vote party amount!'
  # List of commands to execute, these only execute once.
  # %player% does not work here
  Commands: []
  # Rewards to give per player
  Rewards:
    Commands:
    - say 'crates givekey %player% voteparty 1'
    Items:
      DIAMOND:
        Material: 'DIAMOND'
        Amount: 1

**Comment by BenCodez** [comment]
You need to edit in the SpecialRewards.yml after a recent update

**Comment by elaineandsparky** [comment]
ok thanks. Is the reward command correct though? and did you see my other questions?

**Comment by elaineandsparky** [comment]
ok i'm using the adminvote forcevoteparty command and i can not get the server to give people a crate key. I'm all out of ideas on the correct command in the Special Rewards yml. The forcevoteparty command is working as console says players names as currently setup and it was issuing diamonds as per the original settings before i removed it.

for other plugins to issue the key the command is crates givekey %player% voteparty 1

Could you give me the command to insert please to get this to work as i believe i've tried everything (but clearly not!)

VoteParty:
  Enabled: true
  VotesRequired: 30
  GiveAllPlayers: true
  ResetEachDay: true
  ResetMonthly: false
  ResetExtraVotesMonthly: false
  CountFakeVotes: true
  UserVotesRequired: 0
  Broadcast: '&cVote party activated. Thank you for your votes!'
  Commands: []
  Rewards:
    Commands:
    - say %player% **- what do i insert here?**

**Comment by BenCodez** [comment]
Just type the command? You had say (command) basically before.

**Comment by elaineandsparky** [comment]
well apparently it works now!

**Comment by elaineandsparky** [comment]
This still isn't working in the special rewards config:

VoteParty:
  Enabled: true
  VotesRequired: 30
  GiveAllPlayers: false
  ResetEachDay: false
  ResetMonthly: false
  ResetExtraVotesMonthly: false
  CountFakeVotes: true
  UserVotesRequired: 30
  Broadcast: '&cVote party activated. Thank you for your votes!'
  Commands: []
  Rewards:
    Commands:
    - crates givekey %player% voteparty 1

**Comment by BenCodez** [comment]
Pastebin the whole file.

**Comment by elaineandsparky** [comment]
https://pastebin.com/FesC9gVS

**Comment by BenCodez** [comment]
Did you reload the plugin /av reload?

Are you using the latest version?

**Comment by elaineandsparky** [comment]
i've been using reload yes and also the server has been restarted and i updated when you released a new update on monday

**Comment by BenCodez** [comment]
What does /av version show?

I just tested it and it works fine for me.

**Comment by elaineandsparky** [comment]
version 5.23.3

**Comment by BenCodez** [comment]
Type /av report and send the zip file in /VotingPlugin/Reports

**Comment by elaineandsparky** [comment]
[Reports.1599771126803.zip](https://github.com/Ben12345rocks/VotingPlugin/files/5204595/Reports.1599771126803.zip)

**Comment by BenCodez** [comment]
I got no idea

This build do anything different?
http://ben12345rocks.com/job/VotingPlugin/

Anything in console?

**Comment by elaineandsparky** [comment]
i'll try that build in the morning but console didn't give anything not even the announcement (which did get sent) it was like console didn't recognise anything had happened

**Comment by BenCodez** [comment]
Something is up, that's for sure.

**Comment by elaineandsparky** [comment]
new build in and still not working. 
![image](https://user-images.githubusercontent.com/69724087/92882132-8a45cc80-f407-11ea-8b22-e603de301e1b.png)

**Comment by BenCodez** [comment]
There is a command to force vote party, what happens with that?

**Comment by elaineandsparky** [comment]
nothing. Although when i was setting this up and testing with the forcevoteparty command I had set the give all players to true not realising it was for offline players and thought it was for all players online not just those who had voted and now when players login for the first time since then it gives them 29 keys and 29 diamonds!

**Comment by BenCodez** [comment]
Set debuglevel to EXTRA and send the logs on forcing the vote party and startup log?

**Comment by elaineandsparky** [comment]
turns out it was this blocking it
UserVotesRequired: 30

**Comment by BenCodez** [comment]
Hmm, didn't see that

**Comment by BenCodez** [comment]
So this is all good then?
