### ISSUE TITLE
after restart files wipe

### ISSUE THREAD

**Issue by rooster7679** [BenCodez/VotingPlugin#944]
**Versions**
Plugin version and spigot version.5.23.3

**Describe the bug**
A clear and concise description of what the bug is. Every time server is restarted it wipes votesites.yml

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**
Add any other context about the problem here. Also the command for votes not working I get that I voted on the website but no key shows up in game.
 Rewards:
     -console:
       -command:
        -'crate give %player% vote 1 '

**Comment by BenCodez** [comment]
Send your votesites.yml?

**Comment by rooster7679** [comment]
VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  ExampleVoteSite:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: false
    
    # Display name of voting site
    Name: 'ExampleVoteSite'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'PlanetMinecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'link to vote URL here, used in /vote'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Use to have a minute votedelay
    #VoteDelayMin: 30
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'say hello'
      # Send player a message
      Messages:
        Player: 'You voted'
  # Site 2 example
  Site2:
    Enabled: false
    Name: 'Site2'
    ServiceSite: 'PlanetMinecraft.com'
    VoteURL: 'link to vote URL here, used in /vote'
    VoteDelay: 24
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next reward will be attempted
          # Use permission requirement for rank based rewards
          #RequirePermission: true
          #Permission: 'permhere'
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'You voted'
    
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by rooster7679** [comment]
VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  ExampleVoteSite:
    # Enable voteSite
    # If false, votesite will not be loaded by plugin
    # Default: false
    Enabled: false
    
    # Display name of voting site
    Name: 'ExampleVoteSite'
          
    # Priority of this site
    # Used for sorted list
    # High prority, higher on the list
    Priority: 5
          
    # The serviceName from the vote, has to be correct to work correctly
    # Gotten from voting on the site (will be in console/log)
    # Usually is the main part of the url(e.g. PlanetMinecraft.com), but not always
    # See console when you vote (it will notify you if the plugin didn't find a votingsite matching the service site
    ServiceSite: 'PlanetMinecraft.com'

    # vote url for /vote
    # Format for this can be set in Format.yml
    # Do not include colors here
    # If you need to force a url set the url as this:
    # VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="URLHERE"]'
    VoteURL: 'link to vote URL here, used in /vote'

    # Time between votes in hours (used for /vote next)
    # Most sites are 24 hours
    VoteDelay: 24
    
    # Use to have a minute votedelay
    #VoteDelayMin: 30
    
    # Require waiting until votedelay time has pasted in order to accept vote
    # Recommend: false
    WaitUntilVoteDelay: false
    
    # Reset vote delay each day (for certain sites that do this)
    # Recommend: false
    VoteDelayDaily: false
    
    # If true, rewards can be executed offline (requires ForceOffline to be true in the reward)
    # Setting this to true will execute the reward offline while the player is offline
    # This basiclly disables offline voting if set to true, don't misinterpret this option
    ForceOffline: false
    
    # VoteSite Material for some GUI's
    # Removing this may result in an error, required on each site
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1

    # Rewards to give
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    Rewards:
      # Execute console commands
      Commands:
      - 'say hello'
      # Send player a message
      Messages:
        Player: 'You voted'
  # Site 2 example
  Site2:
    Enabled: false
    Name: 'Site2'
    ServiceSite: 'PlanetMinecraft.com'
    VoteURL: 'link to vote URL here, used in /vote'
    VoteDelay: 24
    DisplayItem:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
      - 'say hello'
      # Advanced example
      # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
      AdvancedPriority:
        # Similar to priority, but no need to have to use reward files
        # Add requirements under each reward
        # Will go in order from list here and try to run each of the following rewards...
        # This name can be anything, but they need to be different
        Reward1:
          Chance: 50
          # Any other requirement here
          # If any requirement fails, the next reward will be attempted
          # Use permission requirement for rank based rewards
          #RequirePermission: true
          #Permission: 'permhere'
          Messages:
            Player: 'You got first reward'
        Reward2:
          Chance: 20
          Messages:
            Player: 'You got second reward'
        # Fallback, 100% chance, after other rewards fail chances
        Fallback:
          Messages:
            Player: 'You got unlucky'

      Messages:
        Player: 'You voted'
    
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: []

**Comment by rooster7679** [comment]
https://mcpaste.io/d0d3c79cc3701c6a

**Comment by rooster7679** [comment]
It wiped vote sites yet again after reboot

**Comment by rooster7679** [comment]
also all the errors in console are here
https://mcpaste.io/bb5d9239c6ea97cb

**Comment by BenCodez** [comment]
Use pastebin for your votesites.yml

com.vexsoftware.votifier.io.netty.handler.codec.CorruptedFrameException: Could not decrypt data from /**.**.**.**:54232. Make sure the public key on the list is correct.

Need to check that.

**Comment by rooster7679** [comment]
https://pastebin.com/C8NR0drR

**Comment by BenCodez** [comment]
You have no votesites setup. Also doing a vote will auto generate a votesite (overriding any data you might have if the plugin hasn't reloaded before that)

Fix your votifier issue first, then worry about votesites

**Comment by rooster7679** [comment]
https://pastebin.com/98HqqCpN Is what I have now. Do I need to go into basic.yml to add rewards and if so where and what do I put

**Comment by BenCodez** [comment]
Just put what you want under Rewards. Don't need to use reward files.

**Comment by rooster7679** [comment]
10.09 19:42:08 [Server] Server thread/WARN [VotingPlugin] Detected no voting sites, this may mean something isn't properly setup wiped again

**Comment by BenCodez** [comment]
https://pastebin.com/cdAuu1ha

It didn't reset, it just wasn't valid for yml.

**Comment by rooster7679** [comment]
Do I need to add console?

**Comment by BenCodez** [comment]
No.

**Comment by rooster7679** [comment]
(<unknown>): did not find expected key while parsing a block mapping at line 63 column 5 is what I am getting in yamllint

**Comment by BenCodez** [comment]
You use what I sent?

**Comment by rooster7679** [comment]
oh no I thought it was a suggestion

**Comment by BenCodez** [comment]
I fixed it for you :)

**Comment by rooster7679** [comment]
what was I doing wrong?

**Comment by BenCodez** [comment]
Incorrect spacing, yml is picky

**Comment by rooster7679** [comment]
so when I add my other voting sites I should follow what ya sent

**Comment by BenCodez** [comment]
Yeah

**Comment by rooster7679** [comment]
says I voted but no key came through
I am using cratesplus plugin
Do I have the right command?

**Comment by BenCodez** [comment]
I'd check the command, I got no idea if that is right.

**Comment by rooster7679** [comment]
in game its /crate give vote 1

**Comment by BenCodez** [comment]
What about via console?

**Comment by rooster7679** [comment]
u can give keys via console

**Comment by BenCodez** [comment]
Then use whatever command that is.

**Comment by rooster7679** [comment]
ah got it its crate key give name

**Comment by rooster7679** [comment]
thanks So much for the help I have been trying to do this for the last 4 days

**Comment by BenCodez** [comment]
No worries.
