### ISSUE TITLE
Is there any possible way I could ask for a 1.8.x version of this plugin?

### ISSUE THREAD

**Issue by Snizce** [BenCodez/VotingPlugin#945]
Hi I am starting up a factions server and was really hoping to use this plugin that I saw on another server, my only problem is factions is on 1.8 not 1.12+. I was wondering if I could request it to be made into 1.8.x or not? Or If I could have the source code.

**Comment by BenCodez** [comment]
Code is on github. Your on your own for 1.8 support.
