### ISSUE TITLE
Votes not working?

### ISSUE THREAD

**Issue by doctorblanket** [BenCodez/VotingPlugin#946]
**Versions**
latest and 1.16.3

**Describe the bug**
The gui opens and gives a link to the voting website, but when voting, nothing happens. 

**Expected behavior**
For the vote to be announced and rewards given

**Additional context**
There are no errors in the console

**Comment by BenCodez** [comment]
Is the server getting the vote, check console, if nothing then the answer is no, would check votifier then.

**Comment by doctorblanket** [comment]
Yeah nothing happens. So do I contact votifier support instead?

**Comment by BenCodez** [comment]
Check the startup log, usually a port is already taken or something. There isn't much votifier support out there. Been dealing with it enough, I know most of the issues off by heart now.

**Comment by doctorblanket** [comment]
This is the error I found on startup: 12.09 20:36:58 [Server] Votifier epoll boss/ERROR [Votifier] Votifier was not able to bind to /54.39.250.214:8192

**Comment by BenCodez** [comment]
Try a different port.

**Comment by doctorblanket** [comment]
Yeah even trying a different port does nothing

**Comment by BenCodez** [comment]
You need to find something that can bind. Host/port need to be bindable. If you have a host ask them.

**Comment by Ben12345rocks** [comment]
You need to find something that can bind. Host/port need to be bindable. If you have a host ask them.

**Comment by doctorblanket** [comment]
Ok, I've contacted my host. Hopefully they can help. Thank you for the help!
