### ISSUE TITLE
MonthlyAwards use the Rewards inventory claim GUI 

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#947]
When you win the monthly rewards and have a full inventory the item drops on the floor, can you make the MonthlyAwards get added to the Rewards claim GUI instead so the item cant be stolen/despawn.

**Comment by BenCodez** [comment]
Could use the choice system, make players choose a reward they get. Could use a maybe a key system as well? I think a claim GUI is a little overkill.

**Comment by TomLewis** [comment]
> Could use the choice system, make players choose a reward they get. Could use a maybe a key system as well? I think a claim GUI is a little overkill.

Just needs to be super simple if their inventory is full, consistency is key too. So if they know how to claim something already, why not claim it the same way?

**Comment by BenCodez** [comment]
Could just wait for a slot to be empty and then give the items as well. Might work too. Not sure if there is another plugin that can give items like that currently, I'll see what I can do.

**Comment by TomLewis** [comment]
Was this solved?

**Comment by BenCodez** [comment]
Haven't done anything in regards to this at the moment

**Comment by TomLewis** [comment]
Ok, thanks for the update
