### ISSUE TITLE
Questions about Timings

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#949]
**Versions**
192 Paper, 1.16.3, 5.23.3 of VotingPlugin

**Relevant information**
https://timings.aikar.co/?id=4d0c974213ac434c9e7a7ffba1cce22d Hi, just want to ask if these values - avg(6.12ms per - 1.53ms/0.25 per tick, are good?

**Comment by BenCodez** [comment]
Should be okay enough. Little high I think, but should be fine.

Can always disable advancedtab if needed.

**Comment by bobhenl** [comment]
Ok, then I'll close it, but if you could try improve a little bit somehow, will be great.

**Comment by BenCodez** [comment]
I made a caching system on it already, so it should only be it needs to cache it when it takes a while.

**Comment by bobhenl** [comment]
And should I set something in configuration, or?

**Comment by BenCodez** [comment]
Does this help it?
http://ben12345rocks.com/job/VotingPlugin/

And no config settings needed
