### ISSUE TITLE
Total Daily/Weekly Vote Goals & rewards for those that voted.

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#952]
Hopefully all data for this is already saved.
I request being able to set a daily/Weekly Goal for all players to vote, say for example I want all users to try and get a goal of 150 votes per day and then reward all users with a special reward if they reach this daily goal.
Do this for all the votes you track, Daily, Weekly, Monthly and only give rewards to the people that voted if they reach that goal.
if they don't reach a goal, allow us to run commands too, so we can say the goal was 149/150 votes or something in chat.

**Comment by BenCodez** [comment]
So a vote party pretty much?
