### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by Bexr115** [BenCodez/VotingPlugin#953]
**Versions**
[5.23.3]

**Relevant information**
/

**Context**
Hello sir,
I have a quick question. How can i set the Vote message to a Broadcast so all Players see that someone just voted.
Linked a screenshot.

Screenshot : http://prntscr.com/uiginw [Lightshot] Screenshot programm
Bexr

**Comment by BenCodez** [comment]
Rewards:
      Messages:
        Broadcast: 'broadcast'
        Player: 'player message'

Or use the broadcast within the Config.yml (There is a default broadcast)
