### ISSUE TITLE
Can you make a custom "topvoter" rank wich updates dynamiccaly

### ISSUE THREAD

**Issue by JessePesse123** [BenCodez/VotingPlugin#954]
**Versions**
Plugin: 5:23:3
Paper:  git-paper-196

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
We would like to give our 3 topvoters (monthly) a custom rank wich updates dynamically. The only thing the rank adds is 1,2 or 3 stars in front of their name. as seen in the image below. Is there a way to do it with your amazing reward system! We are using luckperms. Thanks! 

![image](https://user-images.githubusercontent.com/66204768/93380855-1882de00-f860-11ea-9b48-b57ca4ebe185.png)

**Comment by JessePesse123** [comment]
Oops! closed it by accident

**Comment by BenCodez** [comment]
Just add it as a reward with perm or something? Not sure exactly what you want?
