### ISSUE TITLE
Help bungeecord config

### ISSUE THREAD

**Issue by istarengwa** [BenCodez/VotingPlugin#955]
**Versions**
last version of plugin (5.23.3)
git-Purpur-740 (MC: 1.16.2)

**Context**
I have tried the 3 possible methods for my bungee server, none of the 3 work, I would need help with the configuration if possible. I'm also wondering what I should indicate to the voting site, the token votifier of a server or the bungeecord ?

when I put the plugin on a server without using bungee it works for that server, and when I switch with bungee, nothing works anymore

**Comment by BenCodez** [comment]
You need to explain what you did. Did you follow the wiki pages?

**Comment by istarengwa** [comment]
yes I followed everything, I succeeded with the method PLUGINMESSAGING. But impossible to make it work in MYSQL mode, or else I cannot configure it correctly

**Comment by BenCodez** [comment]
Well, I won't know what was wrong without details. MySQL mode requires a spigot server to receive the votes from votifier, so it's not an easy switch.

**Comment by istarengwa** [comment]
I have 3 spigot servers and a bungee, I put the mysql on the bungee in mysql mode, the same on the spigot servers. Everything is similar to the other mode, but with the mysql enabled, do you have to put the same mysql on bungee as on the spigot servers? (That's what I did) Did I forget a detail somewhere?

For the voting site, do you have to put the nuvotifier token from bungee or one of the spigot server? (I put the Bungee token)

**Comment by BenCodez** [comment]
Well, if pluginmessaging works then I would stick with that.

Yuo need nuvotifier to forward the votes to the spigot server with nuvotifier on that said server.

**Comment by istarengwa** [comment]
nuvotifier is already installed on all servers and linked to the bungee.

**Comment by BenCodez** [comment]
If your using pluginmessaging then you need to disable that then.

**Comment by istarengwa** [comment]
with pluginmessaging I don't need to nuvotifier ? or just need on the bungee?

**Comment by BenCodez** [comment]
Just bungee.
