### ISSUE TITLE
Players didn't receive vote points.

### ISSUE THREAD

**Issue by eliyash31** [BenCodez/VotingPlugin#957]
Hello do players still needs to be given a permission in order for them to receive vote points from voting?

I myself as an operator of the server can receive 1 vote points when voting on a website but players that are not operators didn't receive any vote points after voting. 

I don't think this is a bug because players that are op can receive points so maybe there is a permission first given to the players in order for them to have the rights to receive vote points from voting, am I right?

**Comment by BenCodez** [comment]
You shouldn't need any perm. Unless you added something to do that.

**Comment by eliyash31** [comment]
Okay I will check tomorrow again if there is still a problem when voting

**Comment by eliyash31** [comment]
Okay, I tried again and I noticed on using my alt account which is not an OP.
I tried to spam force vote for 10 times in a row and I noticed it always keep on saying that 
"You voted for the first time!"
I don't know what I did wrong in the config but I think it keeps on resetting the vote points for the players?
but if a player is OP, it won't reset the vote points

**Comment by eliyash31** [comment]
okay wait, I tried to op my alt account and yet it still resets the vote points or says you voted for the first time every time I vote

however this account is a new account to our server unlike me and my friend's account it counted our votes when we use our main account. 

however, all new accounts that joined our server that tries to vote for the server will reset their vote points to 0 every after voting :(

**Comment by eliyash31** [comment]
I will try to check mysql maybe it only give points to the registered accounts, I mean I think it got bugged after updating the server to 1.16.3 only those accounts before updating the server gets the vote points and I think new accounts is not registering on the mysql  database that's why vote points only sets to 0

**Comment by eliyash31** [comment]
Okay I tried checking the mysql however I still don't get the problem. but here is what happened, I see that when voting using our main accounts or the accounts that has been registered before updating the server, they will get points but in our alt accounts the points always stays at 1 (in mysql table) but in our TAB list which is the placeholder for vote points it says 0 I will give a screenshot so that it can easily be understand

Screenshot MYSQL: 
https://imgur.com/BEh0bNp
Screenshot of TABlist
https://imgur.com/undefined

**Comment by BenCodez** [comment]
What setup are you using?

Also confirm your on the latest version across all servers?

**Comment by eliyash31** [comment]
I am using a 5.23.3 version of the plugin and my server's version is 1.16.3
also, I am not using a bungeecord server, it's just a normal server or paperspigot. 
here is the pastebin of my yml config 
https://pastebin.com/Wd08g9FA

btw, later I will try to use the sqlite and try if it will fix the problem

**Comment by BenCodez** [comment]
Do you have bungeecord enabled in bungee settings.yml?

**Comment by eliyash31** [comment]
hello I'm sorry for the very late reply, this is my setup of the bungee on config.yml

UseBungeecoord: false
BungeeBroadcast: false
Server: PleaseSet

**Comment by BenCodez** [comment]
Just the one server on its own?

**Comment by eliyash31** [comment]
Yes I only have one server that is a survival server

**Comment by BenCodez** [comment]
Is MySQL saving the data correctly? Try sqlite?

**Comment by eliyash31** [comment]
Okay I tried sqlite and it fixed the problem. Should I just use sqlite from now on? however MySQL is better because I can see the data of the players :(

**Comment by BenCodez** [comment]
Try with a different mysql database?
