### ISSUE TITLE
How to broadcast vote just to one server on bungeecord?

### ISSUE THREAD

**Issue by Teleriann** [BenCodez/VotingPlugin#958]
Hello...

Please, how to broadcast player votes only on spigot server where player is online?

My settings:   BroadcastWhenOnline: true
Server is broadcasting all "voters" that click send vote on site, even when name is 123, am i doing something wrong?

Thanks...

**Comment by BenCodez** [comment]
Disable bungee broadcast on all servers? Never tested it with broadcast when online is true, so no idea if that works right now, atleast with bungee.

**Comment by Teleriann** [comment]
It is disabled on all servers, we have bungeecord with Survival and Economy server, it is disabled on both servers.

**Comment by Teleriann** [comment]
It seems like
  BroadcastWhenOnline: true
Is not working at all, it is on true on both servers, but it is broadcasting offline votes too.

**Comment by BenCodez** [comment]
Are you using bungee plugin messaging?
You can disable the broadcast from the config.yml and add it within a reward if you want.

**Comment by Teleriann** [comment]
Yes, iam using plugin messaging, i will try it.

**Comment by Teleriann** [comment]
But anyway, there is something wrong with plugin problably, i was using only spigot version of VP and it was working fine, yesterday i updated to bungeecord, everything is working fine, but that broadcast is kinda broken. It is weird.

**Comment by BenCodez** [comment]
Never tested the broadcast on bungee with the online option set to true, so that is probably broken.
