### ISSUE TITLE
Vote recevived but no reward

### ISSUE THREAD

**Issue by JustAMatt** [BenCodez/VotingPlugin#960]
**Versions**
5.23.3 for VotePlugin, Paper 1.16.3 202
**Relevant information**
https://mcpaste.io/103baf6d3e7bfaec

**Context**
When a player votes the server broadcasts their vote, however, they do not get a reward. When I emulate a vote I do get a reward.

**Comment by BenCodez** [comment]
1. Use pastebin
2. The service sites are incorrect. (Vote and look for the service site in console)

**Comment by JustAMatt** [comment]
Does emulate vote work for getting the service site?

**Comment by BenCodez** [comment]
Depends, you need to vote from the actual voting site.

**Comment by JustAMatt** [comment]
https://pastebin.pl/view/58641b51

It's the same as in the config

**Comment by BenCodez** [comment]
Received a vote from service site 'Minecraft-MP.com'

Did you set that as the service site?

**Comment by JustAMatt** [comment]
https://pastebin.pl/view/debd46dc yeah

**Comment by BenCodez** [comment]
ServiceSite: https://minecraft-mp.com/

No you don't, it needs to be Minecraft-MP.com

**Comment by JustAMatt** [comment]
Oh, My bad by adding the https://. Thank you!
