### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by OriginalMistake** [BenCodez/VotingPlugin#961]
**Versions**
VotingPlugin 5.23.3

**Context**
Was wondering if there was a support discord server or channel? Maybe a quicker way to contact support? Need assistance in setting this plugin up. I spent a month trying to get it to work but I am unsuccessful... not sure what I am doing wrong. Message me on discord: OriginalMistake#3021

**Comment by BenCodez** [comment]
Just message here. I find it faster to just message here or on spigot than discord.

**Comment by OriginalMistake** [comment]
ok, i am trying to get the voting plugin thing to work but i can't get it to work sadly. when i test vote it goes through into the server but when i vote like a player it does not go through and sometime the voting sites just disappear... is it possible you could assist me in getting it to work?

**Comment by BenCodez** [comment]
Most likely have an incorrect service site or a yml error

**Comment by OriginalMistake** [comment]
is it possible you could set up the votesites.yml file for me? as i just cannot get it to work and i'm doing something wrong i just don't know what

**Comment by BenCodez** [comment]
Send what you have?

**Comment by OriginalMistake** [comment]
i have the default file

**Comment by BenCodez** [comment]
Then vote on the voting site and the VoteSites.yml autogenerates
