### ISSUE TITLE
Rewards always when player it connected to server

### ISSUE THREAD

**Issue by Teleriann** [BenCodez/VotingPlugin#962]
**Versions**
Newest version of plugin and Spigot 1.16.1

**Describe the bug**
Every time, when player is connected to server where voting plugin is he gets reward, when he disconnect and connect again, he gets reward again.

**Expected behavior**
It should give vote to player, just when he vote...

**Screenshots/Configs**
![558](https://user-images.githubusercontent.com/71602218/93796193-c6183780-fc3a-11ea-8b50-2006ce1bb0d6.png)

**Comment by BenCodez** [comment]
Whats your setup?

**Comment by Teleriann** [comment]
[Config.zip](https://github.com/BenCodez/VotingPlugin/files/5263801/Config.zip)

This is my config.

**Comment by Teleriann** [comment]
I also have enabled 2 hours cooldown in sites config... So i do not know how this is even possible

**Comment by BenCodez** [comment]
Are you running bungee? If so what setup?

**Comment by Teleriann** [comment]
Bungee was kinda broken with message broadcast, iam using just normal spigot version, i have spigot version of VP on our Survival and Economy server. Votifier send votes to both servers, and then VP gives reward, bet when players type /survival when they are on economy, and then back to economy server /economy, they have keys again and again. It is not happening always, i do not know how it works but couple of players have already ban for abusing that system. And it looks like, when players disconnects completely from our server, and then connect to economy, then it is fine, until he vote again, then bug will happen again, sorry for my terrible english.

**Comment by BenCodez** [comment]
Disable the clear cache options and have separate databases between servers then.

**Comment by Teleriann** [comment]
There is another problem, i need to have voteshop connected on both servers.

**Comment by BenCodez** [comment]
You need to follow one of these:

https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by Teleriann** [comment]
Yes i tried, but if you remember, i had problem with broadcasts. when player voted on site with nickname "Idiot" it showed up ingame, you said that you never tested it that way, and probably, it is not working. And if i can ask, do you know where my problem is right now, like what exactly is causing that unlimited rewards?

**Comment by BenCodez** [comment]
Your using a mix of different setups combined. Also when I said 'never tested it that way' was due to something else (And more so related to plugin messaging method). Though I haven't added the not allowing unjoined players feature to bungee (atleast with plugin messaging, both other methods work with that)

**Comment by Teleriann** [comment]
Ok, i will try to fix it somehow, thank you for your fast replies <3
