### ISSUE TITLE
VoteParty Not Working.

### ISSUE THREAD

**Issue by Woodypop12** [BenCodez/VotingPlugin#966]
Versions
Plugin version: 5.23.3
Server Version: 1.16.2

Bug
The VoteParty is not working.
https://user-images.githubusercontent.com/71799449/94087446-9f850880-fdc2-11ea-864c-db982e082bf1.png

**To Reproduce**
1. VoteParty doesn't work, it doesn't give the reward for the VoteParty

**Expected behavior**
It is supposed to give everyone on the server a key

**Screenshots/Configs**
https://user-images.githubusercontent.com/71799449/94087446-9f850880-fdc2-11ea-864c-db982e082bf1.png
https://pastebin.com/CAAQW22x

**Comment by BenCodez** [comment]
https://pastebin.com/9rcMEZTi

You also need to change the command to give per player and not the whole server.
