### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by TheOneKalleYT** [BenCodez/VotingPlugin#967]
I have a question about the rewards as it is quite confusing for me. How and where can I set it up so that players receive money after voting?

**Comment by BenCodez** [comment]
Votesites.yml

**Comment by TheOneKalleYT** [comment]
Yes. And where exactly at votesites.yml? I have set that you will get 300 money after voting. But it does not work.

**Comment by BenCodez** [comment]
Just under Rewards, send what you have.

**Comment by TheOneKalleYT** [comment]
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  ExampleVoteSite:
    Enabled: false
    Name: ExampleVoteSite
    Priority: 5
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://minecraft-server.eu/server/index/21A3B
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 10
    Rewards:
      - "Money: 300"
      Commands:
      - say hello
      Messages:
        Player: Du hast gevotet!
  Site2:
    Enabled: false
    Name: Site2
    ServiceSite: PlanetMinecraft.com
    VoteURL: link to vote URL here, used in /vote
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      - "Money: 300"
      Commands:
      AdvancedPriority:
        Reward1:
          Chance: 50
          Messages:
            Player: You got first reward
        Reward2:
          Chance: 20
          Messages:
            Player: You got second reward
        Fallback:
          Messages:
            Player: You got unlucky
      Messages:
        Player: Du hast gevotet!
  minecraft-server_eu:
    Enabled: true
    ServiceSite: minecraft-server.eu
    VoteURL: https://minecraft-server.eu/server/index/21A3B
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 10
    Rewards:
      Messages:
        Player: '&aDanke fürs voten auf %ServiceSite%!'
EverySiteReward: "Money: 300"

**Comment by TheOneKalleYT** [comment]
and currently it is so that the votesite is no longer displayed. Probably changed something by mistake. :(

**Comment by BenCodez** [comment]
Use pastebin, also it should be like this:

    EverySiteReward:
      Money: 300
