### ISSUE TITLE
VoteGUI command checks for 'V' permission.

### ISSUE THREAD

**Issue by mibby** [BenCodez/VotingPlugin#969]
**Versions**
VotingPlugin dev 418
Paper dev 204 (Spigot 1.16.3)

**Describe the bug**
Players are unable to open the vote GUI with the command ``/votegui``. They get a no permission message. However they _are_ able to open the vote gui with the command ``/vote gui``. 

Debugging permissions, it seems the permission ``V - undefined`` is being checked. When I debug myself as Admin/OP, it returns ``V - true``. 

**To Reproduce**
1. Try to open ``/votegui`` while having the permission votingplugin.player
2. Can't.

**Expected behavior**
No weird ``v`` permission being checked.

**Comment by BenCodez** [comment]
There is no such permission, not sure where you are getting that from. /votingplugin:vote gui, that do anything?

**Comment by mibby** [comment]
That's why I'm a bit confused, I couldn't find any ``V`` permission, but that is what shows up in LuckPerms verbose output. 

``/votingplugin:votegui``, players can't open the voting gui.
``/votingplugin:vote gui``, players can open the voting gui.

As an admin, I can do both.

**Comment by BenCodez** [comment]
VotingPlugin.Player or VotingPlugin.Commands.Vote.GUI, either permission should do it. Set debuglevel to EXTRA and votingplugin should spit some info out as well.

**Comment by mibby** [comment]
Players already have the permission ``VotingPlugin.Player``. I'll change the debuglevel later tonight and re-test, this is just an oddity I noticed. Not sure why the command & permission would be disconnected from each other to begin with without a space.

**Comment by BenCodez** [comment]
No idea.

**Comment by mibby** [comment]
The non-spaced ``/votegui`` command outputs debug info. The spaced ``/vote gui`` command does not. Might have something to do with it, if it's being registered as an entirely different command with a separate perm check?

```
[04:40:34] [Server thread/INFO]: mibby issued server command: /votegui
[04:40:34] [Server thread/INFO]: [VotingPlugin] Debug: Attempting cmd...
[04:40:34] [Server thread/INFO]: [VotingPlugin] Debug: Inputed args: GUI
[04:40:34] [Server thread/INFO]: [VotingPlugin] Debug: cmd found, ran cmd
[04:40:38] [Server thread/INFO]: mibby issued server command: /vote gui
```

**Comment by BenCodez** [comment]
Try giving players the permission VotingPlugin.Commands.Vote.GUI

**Comment by mibby** [comment]
Giving the permission ``VotingPlugin.Commands.Vote.GUI`` doesn't fix it. Players are still not able to use ``/votegui``, but can ``/vote gui``. The permission checked is still ``V`` according to LuckPerms debug.

**Comment by BenCodez** [comment]
Do you get any message ingame when you do the command?

**Comment by mibby** [comment]
No permission message.

**Comment by BenCodez** [comment]
You have load aliases in the config enabled right? Other than that I got no idea. Can you recreate it on a test server?

**Comment by mibby** [comment]
```
# Load command aliases, such as /avgui
# Requires restart to take effect
LoadCommandAliases: true
```

Maybe it's related to this setting being turned off? As I use LuckPerms with Vault. If VotingPlugin has its own permission checking injections, it may just be broken or conflicting with something? Hence LuckPerms debug outputting the permission checked being ``V``?
```
# Use vault for permission checks
# May not work on some plugins
UseVaultPermissions: false
```

The only other thing I could think of is this setting being off. I give ``VotingPlugin.Player`` to the permission group manually, not let VotingPlugin grant it.
```
# Give VotingPlugin.Player by default
# Requires restart to take affect
GiveDefaultPermission: false

# Permissions given by VotingPlugin.Player by default
# Permissions listed here will no be accessible with the default permission
DisabledDefaultPermissions: []
```

**Comment by BenCodez** [comment]
I would try both things you said to do. With vault permission and votingplugin permission (do it separately, so you know which one does it, player permission requires restart.)
