### ISSUE TITLE
Vote sites order

### ISSUE THREAD

**Issue by slvlr** [BenCodez/VotingPlugin#970]
**Versions**
VotingPlugin 5.23.3      Paper 1.16.3 Build 198

**Relevant information**
https://pastebin.com/hKqMiXc5

**Context**
https://gyazo.com/b7118aecbaf97343aa11dfb5f3414ecf
https://gyazo.com/d997c9995818df607bf8d22eb471a5dd

I have ordered my vote links in the config in order 1-11 (please see snippet of Votesites.yml on above pastbin link). 
When I type /vote and click the first emerald, link number 9 shows up (They seem to be in a random order). How do I link the vote sites in order of Votesites.yml ingame?

**Comment by BenCodez** [comment]
Use priority on each site.

**Comment by slvlr** [comment]
I have checked config and votesites but cannot see how to use priority please?

**Comment by BenCodez** [comment]
It's an option for every votesite, check the default Votesites.yml

**Comment by slvlr** [comment]
looks like my votesites.yml is rather outdated.
I will manually add this thanks for the prompt support!
