### ISSUE TITLE
SO when i add a website to voteing plugin it does not show up it gives me this 

### ISSUE THREAD

**Issue by cb12438** [BenCodez/VotingPlugin#972]
![Screen Shot 2020-09-29 at 10 49 02 AM](https://user-images.githubusercontent.com/55159369/94596843-92906b00-0241-11eb-964f-c11f6bcf35dc.png)
thats what it says in game and here the console
![Screen Shot 2020-09-29 at 10 52 07 AM](https://user-images.githubusercontent.com/55159369/94597059-ec913080-0241-11eb-8212-78c896594b25.png)
does anyone know how to fix that?

**Comment by BenCodez** [comment]
1. Send your votesites.yml with pastebin
2. that error has nothing to due with votingplugin

**Comment by cb12438** [comment]
https://pastebin.com/YzPX4E2d

**Comment by cb12438** [comment]
yea thats what i am also trying to say it does not show in the console

**Comment by BenCodez** [comment]
The error would be on startup.

https://pastebin.com/uCKMpqJR

**Comment by cb12438** [comment]
error whould be on start up wdym by that?

**Comment by BenCodez** [comment]
The error happens while server starts up?

**Comment by cb12438** [comment]
ah ok so it would be the server itself or the plugin or a dif plugin i can list the plugins i have if needed sorry a bit new to this

**Comment by cb12438** [comment]
like just started 1 month ago

**Comment by BenCodez** [comment]
Just use the pastebin I sent you.

**Comment by cb12438** [comment]
the old votesites yml with that? i will replace*

**Comment by BenCodez** [comment]
Replace the votesites.yml with that

**Comment by cb12438** [comment]
arl thx
