### ISSUE TITLE
Editing gui menu

### ISSUE THREAD

**Issue by Sky-Evil** [BenCodez/VotingPlugin#973]
Hello!
The standard graphical menu has only 1 item line.
I need to expand this menu, and add my own blocks with information and additional menus to it.
I tried to do this in config.yml. But it didn't work out for me. The only thing I understood "Slot:" shifts all blocks in the menu to the selected position. But this information is not enough.

**Comment by BenCodez** [comment]
https://github.com/BenCodez/AdvancedCore/blob/master/AdvancedCore/Resources/Rewards/ExampleBasic.yml#L26

That enough info?

**Comment by Sky-Evil** [comment]
It seems not.
Maybe you misunderstood me.
I need to add information to this (1 screenshot) menu by creating my own blocks and descriptions for them. I'm sure this is editable in the config.yml(2 screenshot), but my attempts don't work.
![image](https://user-images.githubusercontent.com/39336712/94631029-02e5cd80-02d0-11eb-856e-fd68c2699a40.png)
![image](https://user-images.githubusercontent.com/39336712/94631099-36c0f300-02d0-11eb-910f-c5a9de93afd4.png)

**Comment by BenCodez** [comment]
You placed it in the wrong spot. Need to put it under VoteGUI, not URL.

**Comment by Sky-Evil** [comment]
Okay, this is all VERY complicated.
Look ...
Option1: Screenshot1
![image](https://user-images.githubusercontent.com/39336712/94632101-6a048180-02d2-11eb-886a-7108251d9523.png)
If I do code like this. A new empty menu is created called VoteGUI.

Option2: Screen2
![image](https://user-images.githubusercontent.com/39336712/94632117-7557ad00-02d2-11eb-9f96-d149c977b7d1.png)
With this code, I create a menu from screen3
![image](https://user-images.githubusercontent.com/39336712/94632157-915b4e80-02d2-11eb-90a8-776e39507592.png)

**Comment by BenCodez** [comment]
Option 2, change Infos to Item.

**Comment by Sky-Evil** [comment]
Oh my God, I realized what my mistake was, years of editing files like this, and I did not understand that the URL is the name of the first block and not the menu...
Just, thanks for your patience while you explain this to me ...

**Comment by BenCodez** [comment]
No worries, I've done the same from time to time :)
