### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by cb12438** [BenCodez/VotingPlugin#975]
**Versions**
Newest

**Relevant information**
https://pastebin.com/P7GHFhnw
**Context**
So idk what i did wrong with that config i am new to developing servers so if someone knows what i did wrong could fix it possibly?

**Comment by BenCodez** [comment]
https://pastebin.com/XsGu79Gk

**Comment by biggin62182** [comment]
what is the issue that you are having all i see is the same thing in both pastebins. If your using crazy crates as your crate system then you have the command all wrong. its cc give physical/virtual 1 %player% (you pick either physical or virtual).

**Comment by BenCodez** [comment]
@biggin62182 Use this https://www.diffchecker.com/diff, commands I don't know, and that's an easy fix
