### ISSUE TITLE
Bungee Question

### ISSUE THREAD

**Issue by Gilthunderx** [BenCodez/VotingPlugin#976]
Hello im using a bungeecord, i have two survival servers and one of them only works with VoteParty, My players can receive votes from each server but the vote party only works on one survival server.

How do I fix this?

Using latest version 5.24

**Comment by BenCodez** [comment]
Voteparty is per server, one for each server?

**Comment by Gilthunderx** [comment]
Yeah , but it seems to not work on the other one . It only works on my Survival A .

**Comment by BenCodez** [comment]
What's your bungee setup?

**Comment by Gilthunderx** [comment]
what do you mean setup?

**Comment by BenCodez** [comment]
How do you have it setup? Bungee Method? Forwarding votes? There's a wiki
page on it https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups
