### ISSUE TITLE
PlanetMC Rewards Not Working

### ISSUE THREAD

**Issue by Xidle** [BenCodez/VotingPlugin#977]
**Versions**
5.24

**Describe the bug**
Anytime someone votes with site 3 (planetminecraft) it seems to not give the rewards back to players!?

**To Reproduce**

**Expected behavior**

**Screenshots/Configs**
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  ExampleVoteSite:
    Enabled: false
    Name: ExampleVoteSite
    Priority: 5
    ServiceSite: PlanetMinecraft.com
    VoteURL: link to vote URL here, used in /vote
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - say hello
      Messages:
        Player: You voted
  Site3:
    Enabled: true
    Name: XidsCraft
    ServiceSite: planetminecraft.com
    VoteURL: https://www.planetminecraft.com/server/classic-survival-3807459/vote/
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - Broadcast &c&l%player% &2Voted For This &d&lBeautiful Server
      - eco give %player% 1500
      - crate give %player% daily 2
      Messages:
        Player: You voted
  planetminecraft.com:
    Enabled: false
    ServiceSite: https://www.planetminecraft.com
    VoteURL: https://www.planetminecraft.com/server/classic-survival-3807459/vote/
    VoteDelay: 24
    DisplayItem:
      Material: PURPLE_CONCRETE
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
  Site2:
    Enabled: true
    Name: XidsCraft
    ServiceSite: minecraftservers.org
    VoteURL: https://minecraftservers.org/vote/595816
    VoteDelay: 24
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - Broadcast &c&l%player% &2Voted For This &d&lBeautiful Server
      - crate give %player% daily 2
      AdvancedPriority:
        Reward1:
          Chance: 50
          Messages:
            Player: You got first reward
        Reward2:
          Chance: 20
          Messages:
            Player: You got second reward
        Fallback:
          Messages:
            Player: You got unlucky
      Messages:
        Player: You voted
  MinecraftServers_org:
    Enabled: false
    ServiceSite: minecraftservers.org/server/595816
    VoteURL: minecraftservers.org/server/595816
    VoteDelay: 24
    DisplayItem:
      Material: PURPLE_CONCRETE
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
 
**Additional context**

**Comment by BenCodez** [comment]
Pastebin what you have
