### ISSUE TITLE
VoteParty rewards given to offline players.

### ISSUE THREAD

**Issue by Woodypop1** [BenCodez/VotingPlugin#981]
**Versions**
1.16.3 
plugin version: 5.23.3

**Describe the bug**
The bug is that it gives players offline voteparty rewards. but i want it to give them vote keys when offline.

**To Reproduce**

**Expected behavior**
to not give the players offline a vote party reward.

**Screenshots/Configs**
https://pastebin.com/9Y4wMbTc

**Additional context**

**Comment by BenCodez** [comment]
Add RewardType: ONLINE to the reward

**Comment by Woodypop1** [comment]
Would this disable people to not receive a crate key when not online or just for voteparty?

**Comment by BenCodez** [comment]
On whatever reward you add it won't run the reward unless their online

**Comment by Woodypop1** [comment]
Could you give me an example?

**Comment by Woodypop1** [comment]
so you're saying that voting rewards will not give them a vote key when offline, plus the voteparty rewards aswell?

**Comment by BenCodez** [comment]
Rewards:
      RewardType: ONLINE
      Commands:
      - 'command'

Only where you add the rewardtype online it won't give as a online reward.

**Comment by Woodypop1** [comment]
Rewards: 
    RewardType: ONLINE
    Commands:
      Console:
      - 'crates give p global 1 %player%'

**Comment by Woodypop1** [comment]
this look good?

**Comment by BenCodez** [comment]
Need to pastebin or use code tags so the formatting stays

**Comment by Woodypop1** [comment]
https://pastebin.com/9XWrQy2j

**Comment by BenCodez** [comment]
Looks good.

**Comment by Woodypop1** [comment]
Thanks for the help :)

**Comment by Woodypop1** [comment]
06.10 17:22:03 [Server] ERROR [VotingPlugin] Failed to load Config.yml
06.10 17:22:03 [Server] INFO [VotingPlugin] VotingPlugin has an update available! Your Version: 5.23.2 New Version: 5.24.1 Use /av download to get the latest update!
06.10 17:22:04 [Server] INFO [BuycraftX] Fetching all due players...
06.10 17:22:04 [Server] INFO [DiscordSRV] [JDA] Connected to WebSocket
06.10 17:22:04 [Server] INFO [BuycraftX] Fetched due players (0 found).
06.10 17:22:04 [Server] WARN [PlaceholderAPI] Loaded class com.Ben12345rocks.VotingPlugin.Util.PlaceHolders.PlaceHolders from VotingPlugin v5.23.2 which is not a depend, softdepend or loadbefore of this plugin.

**Comment by BenCodez** [comment]
You have a yml error in the config.yml. And your not using the latest version.

**Comment by Woodypop1** [comment]
Ok, I updated and line 53 had an error in it. All fixed 👍

**Comment by Woodypop1** [comment]
Wait, now the voteparty doesnt show up lol

**Comment by BenCodez** [comment]
What do you mean?

**Comment by Woodypop1** [comment]
https://cdn.discordapp.com/attachments/698976970129801287/763152743661043742/unknown.png
look at the featherboard

**Comment by BenCodez** [comment]
What does /vote party show?

**Comment by Woodypop1** [comment]
"VoteParty not enabled"

**Comment by BenCodez** [comment]
Your using SpecialRewards.yml right?

**Comment by Woodypop1** [comment]
yes, here is my config.
https://pastebin.com/mp5MN2JW

**Comment by BenCodez** [comment]
Is the config.yml loading? Startup log? Config.yml?

**Comment by Woodypop1** [comment]
Config.yml: https://pastebin.com/YYiQPbCY
SpecialRewards.yml: https://pastebin.com/bPfVUWqX
Lastest Logs: https://pastebin.com/kuBdR39P

**Comment by BenCodez** [comment]
[VotingPlugin] Enabling VotingPlugin v5.21.3 

Update....

**Comment by Woodypop1** [comment]
ok it works.
