### ISSUE TITLE
Running Multiple Commands as a Reward for Voting on All Sites

### ISSUE THREAD

**Issue by HuskerFan34** [BenCodez/VotingPlugin#982]
**Versions**
5.24.1 & Paper 1.16.1

**Relevant information**
Config: https://pastebin.com/2CQ0nuqT
(I'm focusing on around line 690)

**Context**
For the longest time I've only had one reward for voting on all sites in one day - permissions to /back for 24 hr. I'm trying to add an additional command to give a crate key, but I haven't been able to get it to work. The luckperms commands to give permission to /back is still working fine, but the key isn't being given (I've triple checked that it's the correct command). Do I have to use a different context in the config to run more than one command as a reward? What's the best way to do this?

**Comment by BenCodez** [comment]
You need to edit it in the specialrewards.yml in the newer updates
