### ISSUE TITLE
Restriction in MySQL

### ISSUE THREAD

**Issue by ShockCharge** [BenCodez/VotingPlugin#986]
git-Paper-220 (MC: 1.16.3)
VotingPlugin v5.24.1

So here is my question, pretty much i want to set a restriction lets just say i want to have a currency in my 2 lobby server using Vault
by connecting both of them into one database the players balance in lobby shall be the same and even items and etc. but here is the problem when they try to vote in one of the lobby and visit another they get a double reward instead. 

So do you have any option to restrict this?

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

Follow one of those setups
