### ISSUE TITLE
command rewards

### ISSUE THREAD

**Issue by Thezul1** [BenCodez/VotingPlugin#987]
**Versions**
Plugin version and spigot version
VotingPlugin Version 5.24.1
Spigot Version 1.16.3 Config Version 12

**Relevant information**
https://pastebin.com/zLZmvvxj

**Context**

I need to add a reward as a command to be executed when a player votes
that command should be as following
crate givekey playername voting 1

However, i am unsure how to write that as a working executing command.
i tried command: crate givekey {uuid} voting 1
but that just crashed the plugin

**Comment by BenCodez** [comment]
https://pastebin.com/Km3Tw1JZ

Assuming the command is right, it should work

**Comment by Thezul1** [comment]
let me add into file and test. and i will come back with answer

**Comment by Thezul1** [comment]
this worked. thank you so much
