### ISSUE TITLE
Getting this message twice

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#988]
**Versions**
Paper: 214
Plugin: 5.24.1

**Describe the bug**
The problem is, that player's are getting double message after their connecting. It's maybe because they can vote on 2 vote sites, that's why they're getting two of them? But I think that they should get only one message, when it's same.

**To Reproduce**
1. Try set same config setting as I have (or maybe you don't have to).
2. Have atleast 2 vote sites.
3. Join on server!
4. You will see 2 messages that you can vote.

**Expected behavior**
There should be prob. just one message that will remind players to vote.

**Screenshots/Configs**
In config:
```
  Rewards:
    Messages:
      Player: '&c&lHlasování &f» &eZískej užitečné odměny! &c/vote &e& &c/denniodmena&e.'
```
In game:
https://imgur.com/xlwAQ0A

**Comment by BenCodez** [comment]
Full config? Any other plugins giving messages? If you change does both messages change?

**Comment by bobhenl** [comment]
WTF, now it prints just once, don't know how it happened, will close until new appearance.
