### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by Thetduong** [BenCodez/VotingPlugin#990]
I'm trying to use the placeholders: https://github.com/BenCodez/VotingPlugin/wiki/PlaceHolderAPI-Expansion

But none of them are working for me.

Trying to add them in HoloGraphicDisplays and I have HDPlaceholders installed as well.

**Comment by Thetduong** [comment]
Plugin Version: 5.24.1

Running: Tuinity 88a2c88 (1.16.3)

**Comment by BenCodez** [comment]
You have the expansion installed? /papi parse work?

**Comment by Thetduong** [comment]
Yeah I have PAPI installed and that command works

**Comment by BenCodez** [comment]
Then it's the plugin your using the placeholder in that's causing trouble.

**Comment by Thetduong** [comment]
I'm using HoloGraphicDisplays, and placeholders from other plugins work with it

**Comment by BenCodez** [comment]
If /papi parse me (placeholder) works, then there is nothing can do.

**Comment by Thetduong** [comment]
Oh, I didn't know how to use that. Sorry about that, but I used /papi parse thetduong %VotingPlugin_GlobalDailyTotal% and it came out as "%VotingPlugin_GlobalDailyTotal%"

**Comment by BenCodez** [comment]
Then download the expansion (/papi commands will do it)

**Comment by Thetduong** [comment]
Okay got it, thanks.
