### ISSUE TITLE
Placeholder For Number Of Votes A Player Has Contributed Towards The Current Vote Party Goal

### ISSUE THREAD

**Issue by WhatsTheBadNews** [BenCodez/VotingPlugin#992]
Since my server requires players to contribute 5 votes towards a Vote Party (`UserVotesRequired: 5`) to be rewarded, it would be a useful to have a Placeholder for the number of votes a player has contributed toward the current Vote Party.

**Comment by BenCodez** [comment]
There's a few placeholders already, any of them work for you?

/av placeholders list them all in game (and /av placeholders (player) will shows the values)

**Comment by WhatsTheBadNews** [comment]
![image](https://user-images.githubusercontent.com/29821149/96658275-bc512500-1309-11eb-8713-0c0394367d30.png)

These are the only 3 Placeholders for Vote Parties, and none of them perform the function I described. I'd like a Placeholder that shows how many votes a player has contributed toward the current Vote Party goal.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Should note there is quite a few changes in that build (Such as using GUI.yml for gui options and more)

Edit: Placeholder %VotingPlugin_VotePartyContributedVotes%
