### ISSUE TITLE
Moderation can get CrazyCrate Rewards, but the members dont. Doesnt make sense.

### ISSUE THREAD

**Issue by UltimateInfamous** [BenCodez/VotingPlugin#993]
**Versions**
Plugin version and spigot version
Latest Version
**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
Context about the question/concern
So I've set up the voting plugin with the help of Apex, but when my regular members go to vote they arent given the reward. But when my moderation votes they are.

Heres the code:
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  PlanetMinecraft:
    Enabled: true
    Name: Planet Minecraft
    Priority: 5
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://www.planetminecraft.com/server/iridiumcraft-4796016/vote/
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - 'cc give common 1 %player%'
      - 'acb %player% 100'
      Messages:
        Player: You voted on Planet Minecraft for IridiumCraft! Thank you for the
          support!
  
EverySiteReward: []

**Comment by BenCodez** [comment]
Is the other command working?
Does the player still get the key?

**Comment by UltimateInfamous** [comment]
The player does not get the key.

**Comment by BenCodez** [comment]
My best guess at the moment is that the crate plugin is not giving the key

**Comment by UltimateInfamous** [comment]
https://pastebin.com/6gQ2zE4m Heres my pastebin of the code.

**Comment by BenCodez** [comment]
That looks all fine to me. How are you testing? /av vote? Actually voting on the site? My best guess is that it's from the command itself.

**Comment by AfkF24** [comment]
@UltimateInfamous does the `acb` command listed under commands get executed properly? To my knowledge, CrazyCrates requires you to specify the crate type (physical/virtual), so you should be using `cc give p common 1 %player%` (note the "p" letter in front of the crate name, means physical key).
