### ISSUE TITLE
How does cumulative rewards work?

### ISSUE THREAD

**Issue by eliyash31** [BenCodez/VotingPlugin#994]
**Versions**
Paper version 1.16.3
Plugin version 5.24.1

**Relevant information**
https://pastebin.com/Uz0W4Q5m

**Context**
Hello how does cumulative rewards work? I want my players to receive bigger rewards after they voted weekly.
we got 4 voting sites so 1 week is = to 28 votes.
I already tried troubleshooting it and try to forcevote myself 28 times for a single website with all the permissions of weekly rewards (tenderfoot_weekly) permission for example.
But the reward is not given.. is there any wrong with my config? how should I do it? I already doublechecked the permissions of players and they already have the permissions needed in order for them to receive the reward.

**Comment by BenCodez** [comment]
Your editing the rewards in specialrewards.yml right?

**Comment by eliyash31** [comment]
Oh no.. I only edited the config.yml I didn't know it is in the Special Rewards. Should I just remove the settings in the config.yml and transfer or only use the specialrewards.yml?

**Comment by BenCodez** [comment]
Use only the specialrewards.yml, it was changed to that in a recent update

**Comment by EvilPandaMan** [comment]
Can I test milestones with the /av test? because I have been trying and I did not succeed. Will milestones only work for real votes?

**Comment by EvilPandaMan** [comment]
Could you do a mini tutorial on how to set up special rewards, I don't know what I'm doing wrong, players are voting and they are not getting the milestone stuff.... what folder does it goes? i'm struggling :(

https://hasteb.in/ufasolob.yaml

**Comment by BenCodez** [comment]
https://pastebin.com/crPXRXfH

Try that

**Comment by eliyash31** [comment]
Btw Sir thank you so much for the help was just really busy getting the server to shape after so many bugs. btw the it fixed the problem after changing the names or rewards in the specialrewards.yml

**Comment by BenCodez** [comment]
So all good then?

**Comment by eliyash31** [comment]
Yes all good ☺️ thanks
