### ISSUE TITLE
[VotingPlugin] Detected an issue with voting sites, check the server startup log for more details

### ISSUE THREAD

**Issue by MithrandirCraft** [BenCodez/VotingPlugin#995]
**Versions**
5.24.1

**Context**
The plugin keeps sending this message:
[14:59:53 WARN]: [VotingPlugin] Detected an issue with voting sites, check the server startup log for more details
Every time it starts up. No further details are provided anywhere I know of. This was extracted from the server startup log itself, where there's nothing else, so IDK where else it would refer to.

**Comment by BenCodez** [comment]
Send the full log.

**Comment by MithrandirCraft** [comment]
Oh, one of my sites isn't sending votes. My bad.
