### ISSUE TITLE
Asking for the new 1.16 text format for votesites.yml (/vote all) | 

### ISSUE THREAD

**Issue by antiGriefer** [BenCodez/VotingPlugin#996]
**Versions**
5.24.1 - 1.16.3

**Relevant information**
VoteSites:
  PlanetMinecraft_com:
    Enabled: true
    Name: PlanetMinecraft.com
    Priority: 10
    ServiceSite: PlanetMinecraft.com
    VoteURL: '[Text="&9[Link]",url="https://www.planetminecraft.com/server/salagne-survival/vote/"]'
    VoteDelayDaily: true
    Item:
      Material: GRASS_BLOCK
      Amount: 1
  MC-server-net:
    Enabled: true
    Name: minecraft-server.net
    Priority: 5
    ServiceSite: minecraft-server.net
    VoteURL: '[Text="&9[Link]",url="https://minecraft-server.net/vote/Salagne/"]'
    VoteDelayDaily: true
    Item:
      Material: DIAMOND_ORE
      Amount: 1
  MCSL:
    Enabled: true
    Name: minecraft-server-list.com
    Priority: 4
    ServiceSite: MCSL
    VoteURL: '[Text="&9[Link]",url="https://minecraft-server-list.com/server/456385/vote/"]'
    VoteDelayDaily: true
    Item:
      Material: GOLD_ORE
      Amount: 1
  mc-mp:
    Enabled: true
    Name: minecraft-mp.com
    Priority: 3
    ServiceSite: minecraft-mp.com
    VoteURL: '[Text="&9[Link]",url="https://minecraft-mp.com/server/262949/vote/"]'
    VoteDelayDaily: true
    Item:
      Material: COAL_ORE
      Amount: 1
  MC-Servers-org:
    Enabled: true
    Name: minecraftservers.org
    Priority: 1
    ServiceSite: minecraftservers.org
    VoteURL: '[Text="&9[Link]",url="https://minecraftservers.org/vote/587705"]'
    VoteDelayDaily: true
    Item:
      Material: LAPIS_ORE
      Amount: 1
EverySiteReward:
- VoteRewards.yml

![image](https://user-images.githubusercontent.com/67378144/97010686-09b9d600-1546-11eb-9b7b-60662d2b878b.png)

VoteRewards.yml:
Commands:
- crate givekey %player% vote
- eco give %player% 100

Messages:
  Player: '&3&lVote Confirmed, Total Votes: &r&6&l%VotingPlugin_Total_AllTime%'

**Context**
After I updated the server to 1.16 the /vote all list doesn't show the link properly

**Comment by BenCodez** [comment]
Remove the [Text=... or disable forcelinks in the config.yml

**Comment by antiGriefer** [comment]
This worked! Thanks BenCodez
