### ISSUE TITLE
Error when launching votingplugin "The maximum length a channel may be is 20 chars"

### ISSUE THREAD

**Issue by leifadev** [BenCodez/VotingPlugin#997]
**Versions**
Paper-1618 - Plugin version: 5.24.1

**Bug**
Whenever I launch the plugin on my spigot server, which uses bungee, I get the following error when it gets disabled in a stack of code:
```
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 20 chars (attempted 25 - 'votingplugin:votingplugin.
```

**To Reproduce**
1. Drag jar in
2. Click restart
3. See an error in the console 

**Expected behavior**
I expected the plugin to not have any error messages, and it come up as green instead of red when listing plugins with /pl

**Screenshots/Configs**
https://pastebin.com/2KWsLe5a
<img width="533" alt="Screen Shot 2020-10-23 at 5 57 25 PM" src="https://user-images.githubusercontent.com/49649192/97060533-3aefd180-1559-11eb-8280-3158346bef8b.png">

**Additional context**
I am not sure it is referring to where I input 25 characters instead of the maximum allowed 20. I input the information correctly in SQL on bungee and such.
[Bungeesettings.yml](https://pastebin.com/Qv4VAuyA)
[Config.yml](https://pastebin.com/ANMDrRf7)

EDIT: Tried restart again/doing command again and got this [different error](https://pastebin.com/x6GVpCVQ)

**Comment by BenCodez** [comment]
Does this happen on spigot?

**Comment by leifadev** [comment]
Yes, paper

**Comment by BenCodez** [comment]
No, I mean try with spigot

**Comment by leifadev** [comment]
oh ok

**Comment by leifadev** [comment]
When I use the /av and /vote command there is no output in the console or in game. Also the maximum length notice was still there from my first paste

**Comment by BenCodez** [comment]
What server version are you running?

**Comment by leifadev** [comment]
1.12.2-ro1-snapshot

**Comment by BenCodez** [comment]
Don't think you'll be able to use plugin messaging on 1.12, not much I can do about that.

**Comment by leifadev** [comment]
ok, ill use mysql then

**Comment by leifadev** [comment]
I am getting that original error when a vote comes through, successfully though. I switched fully to MySQL on voting plugin but still used plugin messaging on nuVotifier. Is there a way to stop it, or know whats going on?

**Comment by BenCodez** [comment]
Disable bungee altogether or use sockets.

**Comment by leifadev** [comment]
Could you fix this issue by allowing more compatibility for pluginMessaging which I assume is for lower versions?

**Comment by BenCodez** [comment]
The only way would be using a shorter channel name, which could be possible I guess

**Comment by leifadev** [comment]
Ok, how would I make it shorter if at all? Is that something in the source code

**Comment by BenCodez** [comment]
Change it where I register the plugin channel

**Comment by leifadev** [comment]
which just to be clear is somewhere in the source code right?

**Comment by BenCodez** [comment]
Yep

**Comment by leifadev** [comment]
it seems to be in src/com/Ben12345rocks/VotingPlugin/bungee/Bungee.java, and I found this with the numbers 20, is this it? new to java. its parsing UUIDs tho
```
private UUID parseUUIDFromString(String uuidAsString) {
		String[] parts = { "0x" + uuidAsString.substring(0, 8), "0x" + uuidAsString.substring(8, 12),
				"0x" + uuidAsString.substring(12, 16), "0x" + uuidAsString.substring(16, 20),
				"0x" + uuidAsString.substring(20, 32) };
```

**Comment by BenCodez** [comment]
That has nothing to do with plugin messaging, atleast for what your looking for

**Comment by leifadev** [comment]
yeah just giving it a shot then, ill close this for now

**Comment by leifadev** [comment]
Hey sorry lol but I looked at Bungee.java and BungeeHandeler.java and some other places and I couldn't find an integer where you registered the plugin channel. Is this unchangeable? Thanks :D

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/bungee/Bungee.java#L259

https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/bungee/Bungee.java#L311

https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/bungee/Bungee.java#L328

https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/bungee/Bungee.java#L393

https://github.com/BenCodez/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/AdvancedCorePlugin.java#L754

https://github.com/BenCodez/AdvancedCore/blob/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/Util/PluginMessage/PluginMessage.java#L40

That should be everything you need to change.

**Comment by leifadev** [comment]
ok got you

**Comment by leifadev** [comment]
yeah thanks, saw those but I didn't expect the plugin message to be like that for some reason. built your project with maven in command line thx :D
