### ISSUE TITLE
Vote after restart/reload problem.

### ISSUE THREAD

**Issue by Teleriann** [BenCodez/VotingPlugin#998]
Hello,

I have another problem with VP, i was here, some time ago, with query problems, it is working fine, but im experiencing another bug now. Always when i reload VP (/av reload) or restart the server, lost of votes will pop up for players, for example player x was online on server, then i told him that server need restart. I turned off the server, then started it again, and when he connected VP gave him 8 Votes. I do not know why this is happening, any suggestions how to fix that?

Sorry for my english, and thanks for your help.

**Comment by BenCodez** [comment]
What's in the database? Assuming your using mysql?

**Comment by Teleriann** [comment]
Yes, we use mysql database.

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Does using that build make a difference?

**Comment by Teleriann** [comment]
I will try it

**Comment by Teleriann** [comment]
All right so, i put new version of the plugin to the server, and it is not better, here is starting log and i will explain:

Chat message "[CZS] Hrac Dragon74  zahlasoval pro server a ziskal Vote Kluc! Hlasuj aj ty /vote" Means: "Player Dragon74 voted for server and got vote gey! vote too /vote" so that is message from VP that server sent vote to our server.

Command: "[CZS] Prave si dal Dragon74 1 klucov!" means "You just gave Dragon74 1 key" So that means, that player got reward too.

All players were on server online, before server restard, and had no queued votes.
As you can see, there are lot of messages of giving keys or chat messgaes.

Also i wanted to ask, is it possible for VP to say "Player xxx voted for server, and got vote key" vote too /vote x3" for example, because when someone voted 10times, and then he connects, server chat is unreadable, there are just vote messages.

Thanks for your help and sorry for my bad english.

**Comment by BenCodez** [comment]
Are you using a bungee setup?

https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by Teleriann** [comment]
BungeeMethod MYSQL i guess, we have just one mysql for votepoints, votes etc... We do not have VP on bungee (it was causing some problem)

**Comment by BenCodez** [comment]
Are you forwarding to each server? If so that won't work.

**Comment by Teleriann** [comment]
Do you mean forwarding votes throught nuvotifier?

**Comment by BenCodez** [comment]
Yeah

**Comment by Teleriann** [comment]
Then yes, I do

**Comment by Teleriann** [comment]
Ok then, you are saying that it wont work that way, so if i forward votes just to one of my two servers, then is it possible to give rewards on another server, where forwarding is not turned on too?

**Comment by BenCodez** [comment]
Only with PLUGINMESSAING or SOCKETS on the bungee methods or having different storages on each server. That's if you want rewards on both server for one vote, otherwise it would work.

**Comment by Teleriann** [comment]
Ok so, yes, I want to have rewards on both servers. And also, I want to have voteshop synchronized on both servers. I want vote broadcast message to pop up just on server where player is playing (not on both servers, if possible just one time when he connects, because it really spam chat, when someone connects with lots of votes).  I need to remove that "thing" that is cousing problems with server restart/plugin reload, that i described.

Is all of that even possible?
And again, thanks for your patience with me.

**Comment by BenCodez** [comment]
Use this setup
https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by Teleriann** [comment]
Also, with that version of plugin, that you sent me, it looks like that votingplugin is constantly creating new connections to the database instead of keeping existing ones, so it halts our database with connections, we have 150 max connections and almost all of them are VP.

**Comment by BenCodez** [comment]
I would downgrade, but there is no difference with mysql in that version.

**Comment by Teleriann** [comment]
![votez](https://user-images.githubusercontent.com/71602218/97372789-be405880-18b4-11eb-8b9c-a935c2bcf849.png)

Here it is

**Comment by BenCodez** [comment]
Are you doing /av reload? This will do it as well.

**Comment by Teleriann** [comment]
This is from av reload right now, but it is same after restart, not just av reload.

**Comment by BenCodez** [comment]
If it's the same after a restart then I don't know.

Might just be showing a history?

**Comment by Teleriann** [comment]
Hm, we will see, i will text here tomorrow, thanks for now.

**Comment by Teleriann** [comment]
Hello so, pluginmessaging is working, but i have one problem this:
  - Broadcast only when player is online
  BroadcastWhenOnline: true

Is not working for me at all, players can type random names and vote for them, how to fix this please?
Thanks

**Comment by BenCodez** [comment]
I can look at a way on that. It's kinda hard to validate players on bungee (since there is no way to really do that without just storing every player)

I'll note it on the todo list.

**Comment by Teleriann** [comment]
All right, so it is not possible to turn it off right now right? (Players can type something like: ThisServerIsShit voted for this server etc...)

**Comment by BenCodez** [comment]
Not right now

**Comment by Teleriann** [comment]
Ok so, for now, i will turn off that broadcast messages completely, thanks for now.

**Comment by Teleriann** [comment]
Ok so, now I have another weird problem, players that are online are just randomly getting keys every couple of minuter, I do not understand why. I should have MYSQL storage on all server including bungee right?

**Comment by Teleriann** [comment]
Also, i have enabled WaitUntilVoteDelay: true, but it is not working.

Right now, i turned off one of my server, and this again popped up: [11:32:04 INFO]: [VotingPlugin] Shutting down mysql, queries to do: 2276, if number is higher than 1000, then something may be wrong

Edit: Another problem popped up, voteparty is hooked to nuvotifier, so right now, when we do not have nuvotifier on spigot server, it does not work right now.

**Comment by BenCodez** [comment]
If you use the socket method most of the problems, with usernames and for waituntilvotedelay (bungee kinda ignores this option I guess) should be solved. 

Can't really do much about another plugin, could use vote party within votingplugin?

**Comment by Teleriann** [comment]
We have currently exchanged voteplugin for another plugin for voting, we will see what updates will be in the future and we will return if necessary, you are an amazing developer, I appreciate your efforts.

Thank you so much, and good luck in future.
