### ISSUE TITLE
Reward files aren't limited to .yml (includes OS files)

### ISSUE THREAD

**Issue by mrfloris** [BenCodez/VotingPlugin#999]
**Versions**
Plugin version and spigot version.

**Describe the bug**
It seems the rewards files it tries to load in aren't limited to .yml files, so any other file in the directory will be attempted to be used, such as the operating system files. On macOS this for example would be .DS_Store, and in a sandbox it could be a .git or other .vm file. 

**To Reproduce**
```
> avreload
[05:43:57 INFO]: Reloading VotingPlugin...
[05:43:57 WARN]: [VotingPlugin] Detected that a reward file named .DS_Store already exists, cannot load reward file /Users/floris/mctest/1.16.3/plugins/VotingPlugin/Rewards/.DS_Store
[05:43:57 INFO]: VotingPlugin v5.24.1 reloaded!
>
```

**Expected behavior**
Limited to valid .yml reward files

**Screenshots/Configs**
n/a 

**Additional context**
n/a

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

If you want to test it right away, otherwise ignore it.

**Comment by mrfloris** [comment]
i will get it - but wont be able to test until tomorrow morning eu time.

**Comment by BenCodez** [comment]
Make sure it's build 25 or later, incase you downloaded it already

**Comment by mrfloris** [comment]
I've finally had time! 

I am on nov 2nd build and restarted and so far things are fine. I didn't spot the system files pop up. Thank you. this looks promising.
